### ISSUE TITLE
[0.4.8] Autoscroll for logfile is no longer implicit on start

### ISSUE THREAD

**Issue by xarses** [MultiMC/Launcher#1415]
The "Minecraft Log" window no longer implicitly auto-scrolls the log output on startup, but will scroll automatically again when the bottom of the window is reached (as before)

Linux 0.4.8. Last worked on 0.4.7

**Comment by peterix** [comment]
Oh, it is still the case, but you ran into a weird bug. If you resize the window, it will most likely go away.

Fixing this is basically waiting for me to rewrite the whole log view and use something other than a 'rich text' control.
