### ISSUE TITLE
"Change LWJGL" greyed out

### ISSUE THREAD

**Issue by Sakata-MC** [MultiMC/Launcher#169]
Hey there.  For some reason the LWJGL button is greyed out.  Did a search and came up blank.

Is the "Change LWJGL" button greyed out due to something I've done incorrectly, or is this feature not yet implemented?

**Comment by xarses** [comment]
I'm going to have to re-raise this. 

In the features list on https://multimc.org/ we have `LWJGL version changing built-in` and additionally, 2.9.x is deprecated by the LWJGL folks. As such, the expectation is that A) The button works or B) that the button loads documentation on how to change the version

**Comment by 02JanDal** [comment]
This was removed "temporarily" (yeah, right) at some point. We are getting closer to getting it back in now though. See #1153 for the currently open issue tracking this.

**Comment by wlhlm** [comment]
> 2.9.x is deprecated by the LWJGL folks

That doesn't mean you're able to run Minecraft with newer versions (except for _2.9_.3 maybe) since the API changed for LWJGL3 and the game was written for the older API.
