### ISSUE TITLE
No way to control account selection via command line interface

### ISSUE THREAD

**Issue by Strahan201** [MultiMC/Launcher#1795]
System Information
-----------------------------
MultiMC version: 5 - 0.5.0-929

Operating System: Windows 7 Pro 64

Summary of the issue or suggestion: 
----------------------------------------------
I love the fact I can launch an instance from the command line, but it would be great if I could also select the account to use.

What should happen:
------------------------------
A switch added like -u or something for user to use so I could do like multimc -l myinstance -u Strahan

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
Not applicable

Suspected cause:
---------------------------
Just a lack of a feature

Logs/Screenshots:
----------------------------
Not applicable

Additional Info:
---------------------------
I believe the above summarizes it.  I was asked to submit this by peterix in the Discord chat.

**Comment by 133Seven** [comment]
i'll create a pull request.

**Comment by peterix** [comment]
I closed all ideas / feature requests at some point.

**Comment by peterix** [comment]
And fixed :)

**Comment by pierrep** [comment]
This is amazing, thanks so much
