### ISSUE TITLE
Unable to abort modpack import dialog

### ISSUE THREAD

**Issue by wlhlm** [MultiMC/Launcher#1949]
System Information
-----------------------------
MultiMC version: 0.6.0-develop-1050

Operating System: Windows 10 x64

Summary of the issue or suggestion:
----------------------------------------------

The "Abort" button in the modpack import-dialog is non-functional when importing from URL.

What should happen:
------------------------------

Modpack download should stop immediately when clicking "Abort" and no new instance should be created.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Click "Add new instance"
2. Choose "Import Modpack (local file or link)"
3. Paste modpack link (in my case [Age of Engineering](https://minecraft.curseforge.com/projects/age-of-engineering/files/2461598/download))
4. Click "OK"
5. Click "Abort" in the dialog window that'll open

**Comment by peterix** [comment]
The import was a quick hack, and is for the most part still a placeholder for something better. This should be implemented.

**Comment by AverageComet250** [comment]
Is this fixed yet?

**Comment by jamierocks** [comment]
No, it hasn't been implemented yet.

**Comment by NewoIsTaken** [comment]
I would assume that when this does get implemented that the downloaded files get deleted if aborted?

**Comment by AverageComet250** [comment]
Multimc can add a caching system where it keeps mods, so it doesn't have to download them. 

This means that the only trace of the modpack should be mods in the cache.

**Comment by Evolution0** [comment]
Just want to chime in on this and add that the abort does nothing when creating an instance via Curse/ATL/etc modpack selection in general.

**Comment by jamierocks** [comment]
The merged fixes are not a complete solution to the problem, but fix it for many modplatforms :)

**Comment by phit** [comment]
The remaining platforms that could not be cancelled have been removed with the Curseforge integration https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
