### ISSUE TITLE
Not Remembering Credentials and Invalid credentials.

### ISSUE THREAD

**Issue by ultimaterex** [MultiMC/Launcher#2311]
System Information
-----------------------------
MultiMC version: 6.2-1222

Operating System: Windows 10 64-bit

Summary of the issue or suggestion:
----------------------------------------------

When i go to launch my instance (modded or otherwise), MultiMC prompts for my credentials and it works fine. Generally it remembers my credentials and doesn't ask for my details for a while, but starting today it prompted for my credentials, and it's saying invalid credentials. so i went over to the normal mine craft launchers and filled in the exact same credentials (copy/paste) and it lets me login there.

What should happen: get authentication token from Minecraft auth.
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.Launch instance

2.Input credentials

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------
![image](https://user-images.githubusercontent.com/7915408/41205917-2cca8fba-6cdb-11e8-82fc-37fa9e3acd3a.png)

**Comment by Janrupf** [comment]
Can you upload the MultiMC log? Its in the MultiMC dir and called mutlimc.0.log
