### ISSUE TITLE
Can't run minecraft with forge on linux (openjdk10)

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#2321]
System Information
-----------------------------
MultiMC version: 0.6.2-develop-1143 (issue is the same on stable)

Operating System: manjaro linux 18 beta 2 (on manjaro 17 no difference)

Summary of the issue or suggestion:
----------------------------------------------
When i try to run minecraft with forge installed it just crashes.
I tried different versions of minecraft and MultiMC but it still was the same.
My java is openjdk10. (maybe it is the issue)

What should happen:
------------------------------
Minecraft just should run properly.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Have some kind of linux with openjdk.

2. Try to install forge in one version of minecraft.

3. Fail.

Suspected cause:
---------------------------
It's probably because of openjdk 10. But still i don't know how to change to orcale java and I'm afraid that i'll f**k whole system up (linux in a nutshell)

Logs/Screenshots:
----------------------------
https://paste.ee/p/pEZyD

Additional Info:
---------------------------
In my log "pulpit" means desktop.

**Comment by tehbasshunter** [comment]
Downgrade to 8. Modded doesn't work with anything higher than that.

**Comment by NightSheep23** [comment]
As I expected it was fault of java. Thank you for help

**Comment by Arzte** [comment]
@NightSheep23 This fixed then?
