### ISSUE TITLE
Compile issues on Gentoo Linux

### ISSUE THREAD

**Issue by GuntherDW** [MultiMC/Launcher#2350]
System Information
-----------------------------
MultiMC version: 14f85813c82f9202d39e292965b1ab710a479d4e

Operating System: Gentoo Linux (GCC 7.3.0-r3, glibc 2.27-r5, cmake 3.12.0, qt5 5.11.1)

Summary of the issue or suggestion:
----------------------------------------------

A couple of recent changes made it impossible to compile without changes in Gentoo Linux.
The changes with regards to CMakeList.txt in 8108c617450547b1fcdf8175abfd5a521fbe50d5, especially "-D_FORTIFY_SOURCE=2" in combination with "-Werror" causes issues.
D_FORTIFY_SOURCE is something which is added by default in Gentoo when compiling with an optimiser flag (-O*), hence the error. (log 1)

When I remove said define however it fails down the line somewhere else. (log 2)

I've tried the same compile on a Debian machine and it compiled just fine. So it seems to be Gentoo specific?

EDIT: As discussed in the closed referenced issue report (Funtoo) I have checked out what might be causing the compilation issues and updating CMake to 3.12.1 seems to have fixed the discrepancy I was having.
I still need to modify CMakeList.txt to remove/modify D_FORTIFY_SOURCE but at least it compiles cleanly after that.

What should happen:
------------------------------

A compile that actually finishes and being able to run said program.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Clone the git repo (at 14f85813c82f9202d39e292965b1ab710a479d4e currently)

2. Run the CMake program to generate the Makefiles needed to compile the program

3. attempt to "Make" the program

Suspected cause:
---------------------------

The commit with specific fixes for Arch, possibly others but haven't been able to compile it cleanly just yet. 8108c617450547b1fcdf8175abfd5a521fbe50d5

Logs/Screenshots:
----------------------------
[1] https://paste.ee/p/lCz9I#352lS6Sy9TfxbSUBltgF8NPmA81DXTTc
[2] https://paste.ee/p/tTEem#0M3Z0HbsTt0KbHu2rya8X3kROnFxooqt

Additional Info:
---------------------------

A somewhat recent Gentoo profile (17.0) update also enabled PIE (Position Independent Executable) by default.
It used to be a hardening only feature but now it's on by default.
I don't think it has anything to do with this issue though?

https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo/src/patchsets/gcc/7.3.0/gentoo/10_all_default-fortify-source.patch?revision=1.1&view=markup is a link to the patch Gentoo uses to patch GCC to enable FORTIFY_SOURCE by default when using the -O flags.

**Comment by peterix** [comment]
I added a bunch of draconian compiler flags to the default build and it looks like it clashes with a bunch of distros out there...

Hmm.
