### ISSUE TITLE
All servers appear down OpenSUSE

### ISSUE THREAD

**Issue by enderger** [MultiMC/Launcher#2521]
System Information
-----------------------------
MultiMC version: 0.6.4-1206

Operating System: OpenSUSE Linux/SUSE Enterprise Linux

Summary of the issue or suggestion:
MultiMC refuses to connect to any of Mojang's servers despite the computer's internet connection being fully functional.

What should happen:
MMC should be able to detect an internet connection

Steps to reproduce the issue (Add more if needed):
1. Install MultiMC on OpenSuse with a working NetworkManager-based internet connection

2. That's it

3.

Suspected cause:
No idea

Logs/Screenshots:
All servers are shown as offline.

Additional Info:
None

**Comment by Janrupf** [comment]
Please upload the MultiMC log file `MultiMC-0.lg`

**Comment by enderger** [comment]
I found the issue: OpenSSL

**Comment by Janrupf** [comment]
I see, maybe leave the way to fix it and close the issue so others can look it up :)
