### ISSUE TITLE
Cannot install instance on different hard drive

### ISSUE THREAD

**Issue by gatlinnewhouse** [MultiMC/Launcher#2830]
System Information
-----------------------------
MultiMC version: 0.6.7-1375

Operating System: Windows 10 64bit

Summary of the issue or suggestion: Tried to hard link from my installation folder of multimc (on drive P:) to an instance folder (on my ssd C:). Does not work.
----------------------------------------------

What should happen:
------------------------------
Should run the instance

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Copy instance to another drive

2. Create hardlink to new instance running cmd in admin mode, run this command:
```cmd
mklink /J Link Target
```

3. Run multimc, try to start instance

Suspected cause:
---------------------------
Permissions error on folders

Logs/Screenshots:
----------------------------
[logs](https://pastebin.com/6Wi1xze3)

suspected errors:
```
    4.008 C Exception: "Couldn't open P:/Program Files/MultiMC/instances/1.14.4 SHADERS/instance.cfg for writing: Access is denied.\r\n"
    4.009 C Couldn't open P:/Program Files/MultiMC/instances/1.14.4 SHADERS/instance.cfg for writing: Access is denied.
```

Additional Info:
---------------------------

**Comment by phit** [comment]
multimc should not be put in the program files folder.. especially not the instances

**Comment by gatlinnewhouse** [comment]
@phit where do you recommend?

Many of my other folders are on HDDs, and Windows is not my most comfortable operating system tbh

**Comment by calloatti** [comment]
Some examples:

%homepath%
%localappdata%
%programdata%
%userprofile%
%appdata&
Your desktop
c:\multimc

**Comment by gatlinnewhouse** [comment]
Ty for the suggestions. I know my desktop is on an HDD, but some of those folders must be on my ssd! Tysm
