### ISSUE TITLE
MultiMC Logging me in Offline

### ISSUE THREAD

**Issue by iBeGhostting** [MultiMC/Launcher#284]
I click my instance and start it and it says "refreshing login token" then when that completes it says "Choose your offline mode player name" I can either type my name in and press enter or press cancel. I have pressed cancel and retried after many times. and when I press enter and start up that instance I cant connect to online servers due to being in offline mode. I cant even put my Minecraft account in the multimc to start it. It says Authentication operation canceled.

**Comment by MasterOfLukky** [comment]
Whenever I try to use MultiMC it always says at the bottom:
Loading news...                                        More news...
Web, Account, Skins, Auth and Session are all off (They have red X's)

**Comment by jikuja** [comment]
Open new bug report and fill template, please.
