### ISSUE TITLE
Downloads hang near finished when installing modpacks, repeating NetJob tasks

### ISSUE THREAD

**Issue by marineug** [MultiMC/Launcher#2868]
System Information
-----------------------------
MultiMC version: 0.6.7-develop-1390

Operating System: Win 7 64x

Summary of the issue or suggestion: 
----------------------------------------------
This has happened with multiple packs before but the latest is RLCraft. When I install using a .zip it eventually stops, and when I check the logs the last lines are always this repeating, with the amount varying depending on how long I left it alone (sometimes an hour):

 6061.461 D Task "NetJob(Status JSON)" starting for the first time
 6061.461 D Downloading  "https://status.mojang.com/check"
 6061.780 D Download succeeded: "https://status.mojang.com/check"
 6061.780 D Task "NetJob(Status JSON)" succeeded
 6061.780 D Finished loading status JSON.
 6061.781 D Status loading succeeded.

Sometimes it happens in the middle of the download but usually towards the end. In the past trying to restart and reinstall has worked after a few tries but not this time.

What should happen:
------------------------------
Mods download as usual and I get to die lots in hardcore mode.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Start new instance installing RLCraft 1.12.2 singleplayer via .zip

2. Download stops and I look at logs

3. Cry

Suspected cause:
---------------------------
Possibly the modpack but perhaps not because this has happened with at least half the modpacks I've tried... unsure.

Logs/Screenshots:
----------------------------
[https://paste.ee/p/oUNjw](url)
[https://paste.ee/p/OR8KA](url)
Additional Info:
---------------------------

**Comment by kb-1000** [comment]
The mojang check job will always repeat, no matter what you're currently doing. It's called periodically for those service status things at the bottom right of the window.

**Comment by marineug** [comment]
If it takes longer than an hour should I keep waiting?

**Comment by kb-1000** [comment]
Maybe my previous comment was a bit misworded... the https://status.mojang.com/check task is completely unrelated to this.

**Comment by Janrupf** [comment]
```
 5009.430 C Failed  "https://media.forgecdn.net/files/2791/354/lycanitesmobs-1.12.2-2.0.0.7.jar"  with reason  QNetworkReply::NetworkError(RemoteHostClosedError)
```
Looks like something went wrong there tho. But something is really weird here, it looks like some callback is missing or something.

**Comment by Colonizor48** [comment]
im having this issue

**Comment by bensuperpc** [comment]
Same issue, no errors in the logs :/

**Comment by JustCryen** [comment]
Same here, once it stops it won't continue, clicking abort at first doesn't do anything, clicking it again crashes PolyMC

**Comment by Pyker** [comment]
> Same here, once it stops it won't continue, clicking abort at first doesn't do anything, clicking it again crashes PolyMC

@JustCryen This is the MultiMC issue tracker, not PolyMC's. You can find that one over at https://github.com/PolyMC/PolyMC/issues.

**Comment by peterix** [comment]
This issue tracker is for MultiMC only.

**Comment by peterix** [comment]
Also, the referenced functionality has been removed.
