### ISSUE TITLE
Allow launching offline instance from command line

### ISSUE THREAD

**Issue by ChanceSD** [MultiMC/Launcher#3012]
System Information
-----------------------------
MultiMC version: 0.6.9-develop-1421

Operating System: Windows 10

Summary of the issue or suggestion: 
----------------------------------------------
Basically add more arguments to the launch (-l) command to allow an offline instance

What should happen:
------------------------------
I was thinking something like -launch ID -online true/false -name NAME which would allow launching an instance in offline mode with NAME as the nickname.
In my case i test interactions between two players on a server and was looking to start up 2 instances in a quick way but one of them needs to be in offline mode so they have different nicknames. Otherwise i would just launch 2 online instances.

**Comment by x0reaxeax** [comment]
Oh man, can't stress enough how helpful that would be!

**Comment by hipeopeo** [comment]
This would be cool right now.

**Comment by Sethur** [comment]
+1

**Comment by barraIhsan** [comment]
+1

**Comment by bigpresh** [comment]
Came to make the same feature request.  This would be invaluable for my kids laptops, to give them a one-click icon to launch offline without having to remember to select launch offline and enter their name every time, so this would be a big :+1: from me!

**Comment by Geagg427** [comment]
+1

**Comment by Hund** [comment]
This would be really helpful to have. :)

**Comment by peterix** [comment]
Just implemented this.

Should be live in develop!
