### ISSUE TITLE
Unable to import newly exported instance

### ISSUE THREAD

**Issue by ibrokemypie** [MultiMC/Launcher#3045]
System Information
-----------------------------
MultiMC version: 0.6.8

Operating System: arch linux

Summary of the issue or suggestion:
----------------------------------------------
after exporting a pack zip it cannot be imported and states ``   40.965 C Exception: "Document is not an object"
   40.965 C Task "InstanceImportTask(0x55d6aa45f6d0)" failed:  "Could not understand pack manifest:\nDocument is not an object"`` in the console

What should happen:
------------------------------
the pack imports fine

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. import ftb 3 remix from curse

2. add some mods to the instance

3. export the instance

4. import the exported zip

Suspected cause:
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

```
   40.955 D Extracting subdir "piepack/minecraft/config/brandon3055/ProjectIntelligence/" from "/home/pie/piepack.zip" to "/home/pie/.local/share/multimc/instances/_MMC_TEMP/{2837deb4-2050-4e76-a67c-302a3d5f6601}"
   40.958 D Extracted file ""
   40.958 D Extracted file "GuiStyle/"
   40.958 D Extracted file "GuiStyle/CustomPresets/"
   40.958 D Extracted file "GuiStyle/DefaultPresets/"
   40.958 D Extracted file "GuiStyle/DefaultPresets/darcula.json"
   40.959 D Extracted file "GuiStyle/DefaultPresets/vanilla.json"
   40.959 D Extracted file "GuiStyle/ActiveStyle.json"
   40.959 D Extracted file "ModDocs/"
   40.959 D Extracted file "ModDocs/Draconic Evolution/"
   40.959 D Extracted file "ModDocs/Draconic Evolution/draconicevolution-en_US.xml"
   40.959 D Extracted file "GuiConfig.json"
   40.959 D Extracted file "manifest.json"
   40.959 D Extracted file "options.json"
   40.960 D Extracted file "projectintelligence.xml"
   40.964 D Fixing permissions for extracted pack files...
   40.965 C Exception: "Document is not an object"
   40.965 C Task "InstanceImportTask(0x55d6aa45f6d0)" failed:  "Could not understand pack manifest:\nDocument is not an object"
   40.965 C Task "InstanceStaging(0x55d6aa45bb10)" failed:  "Could not understand pack manifest:\nDocument is not an object"
```

Additional Info:
---------------------------

**Comment by phit** [comment]
Curseforge integration has been removed with https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
