### ISSUE TITLE
Prime offloading launch wrapper not working

### ISSUE THREAD

**Issue by Knogle** [MultiMC/Launcher#3062]
System Information
-----------------------------
MultiMC version: 0.6.8

Operating System: Fedora 31

Summary of the issue or suggestion: Launch wrapper not working for new nvidia offloading command.
Using the new Nvidia drivers the following command is being used to provide NVIDIA offloading
"__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only %command%"

It works fine for everything else when running games from the command line, but i'm struggeling in this case.

----------------------------------------------

What should happen: Game should start, providing offloading
------------------------------

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Add __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only to launch wrapper field.

2. Start the game

Suspected cause: Maybe lacking support for this new command
---------------------------

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)

Additional Info:
---------------------------

**Comment by kb-1000** [comment]
Try writing a shell script to set the environment variables. MultiMC probably just doesn't use a shell for executing the command, which would break that, so a shell script wrapper would probably fix it.

**Comment by Knogle** [comment]
> Try writing a shell script to set the environment variables. MultiMC probably just doesn't use a shell for executing the command, which would break that, so a shell script wrapper would probably fix it.

Thanks for your advice!
Unfortunately it didn't work as well, the shell script can't be execupted properly by MultIMC.

**Comment by kb-1000** [comment]
Did you mark it as executable using chmod?

**Comment by Knogle** [comment]
> Did you mark it as executable using chmod?

Yeah, executing from shell it's running fine, but through MultiMC it doesn't.
For now i got a little workaround.
Currently i built up a shell script to run MultiMC itself using the enviroment vars, so for now the MultiMC instances are using prime offloading as well. I hope there will be a proper solution in the future.

**Comment by phit** [comment]
a correct wrapper command would be, what you posted isn't a valid command

```
sh -c "export __NV_PRIME_RENDER_OFFLOAD=1; export __GLX_VENDOR_LIBRARY_NAME=\"nvidia\"; export __VK_LAYER_NV_optimus=\"NVIDIA_only\"; exec $INST_JAVA \"$@\""
```
