### ISSUE TITLE
Feature: download server.jar directly from MultiMC

### ISSUE THREAD

**Issue by GabDug** [MultiMC/Launcher#3097]
System Information
-----------------------------
MultiMC version: MultiMC 5 version 0.6.11-1430

Operating System: Windows 10 64 bits 18363

Summary of the issue or suggestion:
----------------------------------------------

MultiMC lacks one feature from the official launcher: the ability to download the server.jar quickly from the "Edit Installation pane". This is a small feature, but as far as I know it's not possible to do so inside MultiMC. I'm not sure if this is intended - it's true it's not used often, or maybe it's too complicated to manage with all different versions of Minecraft - or this is simply something that could be added, at least to download the vanillas server.jar.

In the following screenshot, notice the "Server" buton on the right of the "version" field.
![image](https://user-images.githubusercontent.com/1116720/79565071-34673580-80b0-11ea-9033-f716f616152a.png)

What should happen:
------------------------------
We should be able to download the server.jar from MultiMC, without the need of opening the official launcher, for each instance of Minecraft.

**Comment by Continous** [comment]
Better support for servers overall would be better in my opinion. Ability to launch and manage servers through multimc would be an easy feature to add in my opinion, and would allow people to easily manage basically all Minecraft-related stuff within multimc.

**Comment by spannerman79** [comment]
**No**

MultiMC manages **client instances**. 

I think people need to know the difference between a client and a server.

For those that are too lazy... https://bfy.tw/QRvh

This issue is invalid.

**Comment by Continous** [comment]
There is no reason for it not to extend to supporting simple server functionality. At the very least, the capacity to download the server files.

MultiMC is not an exclusively client-managing application. To highlight various functions that are not client-specific that it manages:

* A central mods folder. This may be _useful_ for client functionality, but not necessary.
* External tools like MCEdit, text editors, and profilers. These are strictly not client instances.
* Proxy management within MultiMC. I actually don't even know why this exists. Most OSes do this for you at a global level.

The fact of the matter is that MultiMC is a general purpose Minecraft instance manager. It has never been explicitly for client instances, it just never had server functionality.

**Comment by kb-1000** [comment]
> A central mods folder. This may be useful for client functionality, but not necessary.

This is not "managed" at all. It's just the default folder for the file picker.

> External tools like MCEdit, text editors, and profilers. These are strictly not client instances.

The text editor is just setting up paths for when MultiMC's own functionality needs it, and MCEdit and VisualVM operate on the client. Also I don't see how this relates to servers.

> Proxy management within MultiMC. I actually don't even know why this exists. Most OSes do this for you at a global level.

Sure, but that OS level functionality often doesn't work properly (see Ubuntu's GUI for this), and this only applies for MultiMC itself. It does not start a proxy server by itself. Again, I don't see how this relates to servers either.

That being said, I like the idea being able to start servers with the same configuration as an instance (e.g. for quickly testing mods in a production environment)
But downloading a single jar is not going to do it, that's not how it works

**Comment by brisingre** [comment]
I would like this too.

Also wow what a jerk lmao
