### ISSUE TITLE
could not create the java. virtual machine 

### ISSUE THREAD

**Issue by darklink845** [MultiMC/Launcher#327]
i was trying to run FTB monster pack and no matter what i do this hapens in the console log
MultiMC version: 0.3.6

Minecraft folder is:
C:/Users/JafriPC/Desktop/stuff/11amultmc/instances/FTB/minecraft

Java path is:
java

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2944m, -Xmx3200m, -XX:PermSize=400m, -Duser.language=en, -jar, C:/Users/JafriPC/Desktop/stuff/11amultmc/jars/NewLaunch.jar]

Error occurred during initialization of VM
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Could not reserve enough space for object heap
Minecraft exited with exitcode 1.

**Comment by SrM4ze** [comment]
I have 32gb of ram and I want to allocate 20gb, but if I try more than 512M the error happens... What should I do?

**Comment by QuImUfu** [comment]
create a new issue, post a log and follow the issue-template instead of necroing an ancient closed issue.
