### ISSUE TITLE
Manifest version change on Twitch causes failed download of pack.

### ISSUE THREAD

**Issue by Sakata-MC** [MultiMC/Launcher#3376]
System Information
-----------------------------
MultiMC version: MMC 5 - 0.6.12-develop-1475 on Win32

Operating System: Windows 10.0.19041.508

Summary of the issue or suggestion:
----------------------------------------------
Twitch appears to have changed manifest for modpacks.
User reported in Discord, was able to replicate. 
Attempted to download this pack:
https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack
It starts, errors with "Could not understand pack manifest: Unknown manifest version (5)"

What should happen:
------------------------------
Mod pack should download manifest and continue as usual.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1.  User reported in Discord, was able to replicate. 

2.  Attempted to download this pack:
https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack

3.  It starts, errors with "Could not understand pack manifest: Unknown manifest version (5)"

Suspected cause:
---------------------------
Manifest changed.

Logs/Screenshots:
----------------------------
![image](https://user-images.githubusercontent.com/3158362/95809368-98278f80-0cdc-11eb-8546-4829b30e62b6.png)

Additional Info:
Importing the mod with a direct link to an older version of the pack, at this link, works:
Used 8.0.2 in test-
https://www.curseforge.com/minecraft/modpacks/the-pixelmon-modpack/files/all

**Comment by Sakata-MC** [comment]
Little more research.
Appears that the line in the manifest file describing version will cause MMC to throw an error since the value is unexpected.
If I manually edit the file to show
  "manifestVersion": 1,
Then the modpack appears to download normally, and mods are in fact present, and for me in testing, the pack launches.

Perhaps the user modified the line, or there may be something more to this. Other modpacks I've downloaded that have been updated recently have worked without issue, in my testing.

**Comment by mpavkovic** [comment]
This is either an issue with Twitch launcher itself using the newer manifest version when it's not needed (hard to know since I couldn't find an official manifest.json specification, but I don't see any difference in structure between v1 and v5) or somehow a developer manually changed the value of `manifestVersion` field. Modpack installs and runs perfectly fine when `manifestVersion` is changed to `1`, I tested it.

**Comment by James-Oswald** [comment]
Had the exact same issue, manually changing `manifestVersion` to 1 fixed it for me. Thanks.

**Comment by WoopDeDoo** [comment]
![Document 300](https://user-images.githubusercontent.com/73322720/103392503-3a8d2d00-4aec-11eb-9ce7-723aae1ae231.png)

Confirming, changing `manifestVersion` does work

**Comment by mindcombatant** [comment]
Yeah, this specific modpack seems to be incrementing the manifestVersion every main release, which isn't how that's supposed to work, anyone want to go yell at them on their issue tracker? [https://pixelmonmod.com/tracker.php](https://pixelmonmod.com/tracker.php)

**Comment by peterix** [comment]
This shouldn't work in the curse client either.

**Comment by Piceee** [comment]
> Little more research.
> Appears that the line in the manifest file describing version will cause MMC to throw an error since the value is unexpected.
> If I manually edit the file (line 12, image below) to show
> "manifestVersion": 1,
> Then the modpack appears to download normally, and mods are in fact present, and for me in testing, the pack launches.
> 
> Perhaps the user modified the line, or there may be something more to this. Other modpacks I've downloaded that have been updated recently have worked without issue, in my testing.
> 
> ![image](https://user-images.githubusercontent.com/3158362/95810926-1cc7dd00-0ce0-11eb-8cbc-998315a4f1a6.png)

Where is the manifest.json file? after searching for a while i couldnt find it

**Comment by mpavkovic** [comment]
@Piceee The file is inside the modpack zip file

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
