### ISSUE TITLE
Adjust icon size for MacOS Big Sur

### ISSUE THREAD

**Issue by jkroepke** [MultiMC/Launcher#3507]
Mac OS Big Sure changes the icon style for dock icons. It would be great if MultiMC would have the same icon style like other apps.

Current Example:
![image](https://user-images.githubusercontent.com/1560587/103354282-72c04b80-4aab-11eb-8365-90c4fd0952b7.png)

I found some templates for sketch or photoshop, this may helps.

https://developer.apple.com/design/resources/#macos-apps

**Comment by ThePotatoKing55** [comment]
![Big Sur Icon](https://user-images.githubusercontent.com/18623872/111550124-76c74580-874b-11eb-80d0-0681a6b9d16f.png)
I made a new icon for Big Sur, but it doesn't quite match the original. [Here's the .icns.](https://github.com/MultiMC/MultiMC5/files/6160265/multimc-big-sur.zip)

**Comment by ThePotatoKing55** [comment]
<img width="512" alt="multimc_current_style" src="https://user-images.githubusercontent.com/18623872/111699553-485a7080-8806-11eb-8976-f113a2ed705f.png">

Different icon that actually does fit the original [(icns download)](https://github.com/MultiMC/MultiMC5/files/6167289/multimc_current_style.zip). I adjusted it a bit so that the corners fit, though.

**Comment by phildenhoff** [comment]
Amusing timing, I was just updating my icons and here you are, posting this not a half hour ago! These both look really good, don't forget to submit them to https://macosicons.com so others can find them easily :)

**Comment by phit** [comment]
updated in the development channel, thanks @ThePotatoKing55

**Comment by phit** [comment]
@ThePotatoKing55 can you edit the Icon and remove the shadow, it's not rendering nicely, also if you could share the source file that would be appreciated

![](https://cdn.discordapp.com/attachments/134843027553255425/856191873094123540/unknown.png)

**Comment by peterix** [comment]
Alright... I'll have to do something about this, because the logo is definitely getting entirely removed from the main repo and will not be in the codebase at all.

**Comment by peterix** [comment]
Reverted.

**Comment by levifig** [comment]
Just made an icon from scratch. Feel free to use it. 😊 
![MultiMC](https://user-images.githubusercontent.com/1605/127714502-4313d88e-879f-46f6-acdb-ebde6e1ca732.png)


And here's the [ICNS](https://github.com/MultiMC/MultiMC5/files/6910103/MultiMC.icns.zip) ✌️

**Comment by bryiewes** [comment]
the idea is there, but that dosent match multimcs icon style

**Comment by jobukkit** [comment]
This has been fixed by now and should be closed.

<img width="388" alt="Schermafbeelding 2022-08-25 om 13 39 00" src="https://user-images.githubusercontent.com/2750434/186654661-86ce23e2-086e-4f0c-91da-f4cb231ce042.png">
