### ISSUE TITLE
Error Installing Minecraft

### ISSUE THREAD

**Issue by LividJava** [MultiMC/Launcher#351]
Tried to install minecraft (Modded 1.7.10 Forge/Liteloader) Please Help
Error Msg Reads:
Error downloading the following files:
http://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar

**Comment by leozzyzheng** [comment]
Still 404.
I'm using Internet in China, plz help. I downloaded recommended version from main page yesterday.

**Comment by Heufneutje** [comment]
Your issue is most likely different. Please create and include your log file as described in [these](https://github.com/MultiMC/MultiMC5/wiki/Feedback#issues) instructions.
