### ISSUE TITLE
Technic Version selection

### ISSUE THREAD

**Issue by jopejoe1** [MultiMC/Launcher#3516]
System Information
-----------------------------
MultiMC version: 0.6.12-custom

Operating System: Linux (Manjaro)

Summary of the issue or suggestion:
----------------------------------------------
Technic Version selection

What should happen: 
------------------------------
Version selection in New Instance - Technic similar to FTB version selection

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. click Add Instance

2. select Technic

3. search mod pack

4. click on mod pack

5. select version (missing) 

Suspected cause:
---------------------------
Not Implemented

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
How FTB does it:
![ftb](https://user-images.githubusercontent.com/34899572/104113730-420ccb80-5361-11eb-81cf-7b1151ae599b.png)
How Technic does it:
![Tenic](https://user-images.githubusercontent.com/34899572/104113731-43d68f00-5361-11eb-947d-53beb058ee75.png)

Additional Info:
---------------------------

**Comment by jamierocks** [comment]
We've discussed this in the past on the Discord - I'll look into adding this Monday :)

**Comment by kb-1000** [comment]
Only Technic Solder packs have this ability, and a surprisingly little amount of packs are Solder packs.
That being said, often not even the Technic launcher can offer this.

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/164064665-fb3b6051-f817-41a5-b594-21524522449f.png)
something like this would be interesting
