### ISSUE TITLE
Port of Curseforge Modpack doesn't work on MultiMC

### ISSUE THREAD

**Issue by Razatop** [MultiMC/Launcher#3641]
System Information
-----------------------------
MultiMC version: 0.6.11-1430

Operating System: Windows 10 64x

Summary of the issue or suggestion:
----------------------------------------------
Ported my friends and I current private modpack to MultiMC (Because I/We prefer it) and it ends up crashing when trying to create/load into a singleplayer world (Haven't tested Multiplayer, haven't got around to making a server for it) The end of the log reads something about immersive engineering but even after removing that the problem still happens. I also reinstalled MultiMC to see if that was the issue, did not fix it.

What should happen:
------------------------------
World should load up without incident much like it does on the Curseforge launcher.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Download our Modpack [TestCraft ](https://drive.google.com/file/d/12GYLREJP61aLw7mZi2lv2i_5lZDoSMrv/view?usp=sharing)(if needed) 

2.Import to MultiMC

3.Launch and try to create a world only to encounter linked at the bottom of the issue page.

Suspected cause:
---------------------------
No Idea, this only happens when using MultiMC

Logs/Screenshots:
----------------------------
[Here is the log after the crash.](https://paste.ee/p/vSlVS)

**Comment by phit** [comment]
worldedit crash is https://github.com/EngineHub/WorldEdit/issues/1398
not related to multimc

**Comment by Razatop** [comment]
> worldedit crash is [EngineHub/WorldEdit#1398](https://github.com/EngineHub/WorldEdit/issues/1398)
> not related to multimc

So what's the issue then? If it works with the forge client, and without the forge client. But not with multimc. How is it "Not related to multimc"

**Comment by phit** [comment]
because you are probably not running the same versions, i just linked you the crash you are getting, could be different java versions or forge either way its a usererror and or modbug, multimc just launches the game

**Comment by Razatop** [comment]
> multimc just launches the game

Which is exactly why I'm confused why forge and the normal mc launcher can do it just fine I guess is what I'm trying to say, thank you for your help either way. Making a post on the Worldedit github to see if anyone there has more insight. Thank you for the help!

**Comment by Forkk** [comment]
Closed. Not an issue with MultiMC itself.

**Comment by peterix** [comment]
Sounds like a mod bug to me. Especially when looking at the other issue. Downgrade the mod. Apparently it uses some functionality it shouldn't be.

**Comment by Lartza** [comment]
Can you revisit this based on https://github.com/EngineHub/WorldEdit/issues/1398#issuecomment-803545431

**Comment by AverageComet250** [comment]
Just looked at the world edit issue and I think it might actually be a multimc issue. Like said in the latest comment there, multimc is loading optional classes that don't need to be loaded unless other mods are present, and in this case they aren't.

**Comment by spannerman79** [comment]
No, I was able to replicate this using the Vanilla Launcher @AverageComet250 

My comment https://github.com/EngineHub/WorldEdit/issues/1398#issuecomment-803556476

**Comment by jamierocks** [comment]
@kb-1000's context from the WorldEdit repository is handy here:
> Just checked, log4j is both defined in net.minecraft/1.16.5.json and net.minecraftforge/36.0.42.json.
In net.minecraft/1.16.5.json, the version is 2.8.1. In net.minecraftforge/36.0.42.json, the version is 2.11.2.
---

My guess here is that with the Vanilla launcher both versions are on the classpath and the ReflectionUtil is loaded from the old version of log4j (possibly depending on order, everything is loaded from that version).

The trouble on MultiMC is by design - it will only allow one artefact to be present on the classpath (https://github.com/MultiMC/MultiMC5/blob/5400d4e61389694597381f360e0462932d33bfe1/api/logic/minecraft/LaunchProfile.cpp#L154-L158). It will specifically use the latest version of the library.

**Comment by peterix** [comment]
This looks like a Forge bug to me. Ending up with various junk on the classpath from two versions of the library is probably the very definition of undefined behaviour.

Welcome to Jar Hell.

**Comment by peterix** [comment]
Correction: this absolutely IS a bug in vanilla.

After some discussion with Lex, we decided that the vanilla behavior is buggy and should be amended.
Forge should force the version to what it wants it to be and the one specified by Minecraft should be removed by it.

**Comment by peterix** [comment]
So that modpack? Buggy because of a buggy mod. You can expect it to break.

**Comment by peterix** [comment]
This also means what I'll look at the behavior in MultiMC and probably change it too.
Specifically, not look for the highest version, but let the last component in the list win.

**Comment by peterix** [comment]
Is it going to break something? Probably, if you are depending on undefined behavior.

**Comment by peterix** [comment]
Anyway, use a version of WorldEdit that doesn't depend on this buggy behavior.
