### ISSUE TITLE
Add button in instance menu to add desktop shortcut.

### ISSUE THREAD

**Issue by jonot-cyber** [MultiMC/Launcher#3688]
### Role

I play modded and vanilla minecraft on diffferent profiles

### Suggestion

I want a button on the sidebar of an instance (like where the edit instance button is) to create a desktop shortcut to launch the instance.

### Benefit

It would allow you to launch a specific minecraft instance in one click.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

Currently, I have a .desktop file to launch my vanilla + performance instance. I think it would be nice to be able to automatically generate this.

**Comment by Splarkszter** [comment]
Is [Wiki: Creating-Instance-Shortcuts](https://github.com/MultiMC/Launcher/wiki/Creating-Instance-Shortcuts) Deprecated?

Why it was removed?, It's so annoying that making shortcuts is so inconvenient.

**Comment by phit** [comment]
no this ticket predates that feature being added, so it can be closed

**Comment by Splarkszter** [comment]
@phit am i blind or it isn't there?

![image](https://user-images.githubusercontent.com/90066319/198891200-420e3f8a-bb53-4576-ba1b-bab525adddcf.png)

**Comment by Splarkszter** [comment]
![image](https://user-images.githubusercontent.com/90066319/198891240-0ec30ccd-85f3-4979-8fa5-5f0c2320f037.png)

**Comment by phit** [comment]
switch to the development version in the settings

**Comment by Splarkszter** [comment]
thanks. that page should say that dev branch needs to be activated.
