### ISSUE TITLE
Opening MMC with shortcut leads to modpack not installing

### ISSUE THREAD

**Issue by MarvTekko** [MultiMC/Launcher#3738]
### Operating System

Windows

### Description of bug

I created a shortcut from the MultiMC.exe on my desktop and started it. Then i wanted to install the ATM6 modpack from curseforge and it stops the process in the middle without any concrete error message. 

### Steps to reproduce

- Create a shortcut from MultiMC.exe on desktop
- Open MMC with that shortcut
- Create an instance from ATM6 from curseforge
- experience error

### Suspected cause

I think it may be cause by different relative paths from the shortcut to the original .exe.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please provide your `MultiMC-0.log`  by uploading it to https://paste.gg/ or https://gist.github.com/ from when the error is happening, the file will be in the main MultiMC folder.

**Comment by Rika-TH** [comment]
Just found this issue myself attempting to install E6 and confirmed it works fine running in the folder
here's the log, local zip install and curse link both gave same error (unable to rename overides folder iirc) https://paste.gg/p/anonymous/b2ecab0ae0744ffcb23290e34589dc96

**Comment by phit** [comment]
Curseforge integration has been removed with https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
