### ISSUE TITLE
Add Quilt Mod Loader.

### ISSUE THREAD

**Issue by RDKRACZ** [MultiMC/Launcher#3742]
to here
![image](https://user-images.githubusercontent.com/43277609/115753286-4f434880-a39b-11eb-8c58-93f04bf528c4.png)

https://quiltmc.org/faq/
It's a Fabric fork.

**Comment by jamierocks** [comment]
For the time being I don't think it's notable enough.

**Comment by AverageComet250** [comment]
The thing is, however, adding it to multimc will spark more interest in it and increase its popularity.

There's waiting until it's popular, or making it more popular ourselves.

There's waiting, or there's doing.

**Comment by kb-1000** [comment]
It's not even released yet, so of course it's not notable enough _yet_.

**Comment by peterix** [comment]
Well, if you got the metadata that MultiMC's `meta` scripts could consume, this should be fairly easy?

**Comment by peterix** [comment]
See:
https://github.com/MultiMC/meta/blob/master/updateFabric.py
https://github.com/MultiMC/meta/blob/master/generateFabric.py

**Comment by AverageComet250** [comment]
I think this issue should stay open until quilt is released, and then be implemented when public builds are available for quilt.

**Comment by kb-1000** [comment]
https://meta.quiltmc.org is already up, however it still refers to Fabric.

**Comment by AverageComet250** [comment]
Quilt is a fork of fabric so that makes sense, but they do say that may change in the future, so setting it to grab the metadata weekly may work

Thanks,
Shravan Mandava

________________________________

**Comment by peterix** [comment]
Weekly? That doesn't make much sense. Nobody wants to wait half a week on average for an already released version to appear.

**Comment by RDKRACZ** [comment]
>Nobody wants to wait half a week on average

Still better than nothing :-)

**Comment by kb-1000** [comment]
There isn't even anything to update yet, yet you're already arguing about update periods.
Just keep it at the regular 1 hour, and _wait until they release it_ until you start doing so.
It wouldn't harm having a PR ready IMO though.

**Comment by AverageComet250** [comment]
I meant doing one week until they release, since there won't be many changes until then, before moving to the normally hourly update.

Sorry for any confusion
