### ISSUE TITLE
Loading icon displays instead of the mouse on Debian

### ISSUE THREAD

**Issue by MrMelon54** [MultiMC/Launcher#3755]
### Operating System

Linux

### Description of bug

The mouse displays as a loading icon when over the title bar. This reverts to a normal mouse pointer after clicking on the title bar.

### Steps to reproduce

* Open MultiMC and the mouse displays as a loading icon when it is over the title bar

### Suspected cause

I have no idea what causes it. I hope you figure it out.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MrMelon54** [comment]
![image](https://user-images.githubusercontent.com/48031324/116816132-a04ffb00-ab58-11eb-8001-75ed99c7f908.png)
An image of my pointer displaying as a loading icon when over the title bar. You can ignore my custom cursor as it happened before I installed a cursor pack.

**Comment by jamierocks** [comment]
Unable to reproduce in Gnome 4, Fedora 34.

**Comment by kb-1000** [comment]
@MrMelon54 which desktop environment and distro are you using?

**Comment by MrMelon54** [comment]
> @MrMelon54 which desktop environment and distro are you using?

GNOME 3.38.4, Debian sid

**Comment by phit** [comment]
@MrMelon54 can you still reproduce this on latest stable or development? I've yet to see anyone else with this issue.

**Comment by MrMelon54** [comment]
Yes it still occurs I'm now on Debian Bullseye (I decided to stick at this stable release instead of continuing with sid) and gnome 3.38.6. I have noticed that occasionally it will happen when opening firefox but with multimc it happens everytime. I'm not sure if its specifically an issue with multimc anymore?

**Comment by peterix** [comment]
I'm sorry, but that's like blaming the car breaking down on the radio.

MultiMC does absolutely nothing with Gnome, has nothing in common with firefox and does not even ship with Qt. You use your system version of Qt.

MultiMC also does not even interact with the title bar in any way - this is specifically the responsibility of your system.

There's nothing to fix.
