### ISSUE TITLE
curseforge install modpacks title added to show modpacks version

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/Launcher#3769]
### Role

MultiMC updated modpacks version

### Suggestion

curseforge install modpacks title added to show modpacks version

### Benefit

Determine the specific version to update the latest version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by jamierocks** [comment]
ThIs is equally applicable to other modpack platforms - and is probably a good idea.

However for CurseForge it may be a little horrid since they have shitty version names :(

**Comment by graytoowolf** [comment]
> ThIs is equally applicable to other modpack platforms - and is probably a good idea.
> 
> However for CurseForge it may be a little horrid since they have shitty version names :(

CurseForge platform "manifest.json" file is provided with modpack version number

**Comment by phit** [comment]
Curseforge integration has been removed with https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

all other platforms already do this by now
