### ISSUE TITLE
Optifine with forge

### ISSUE THREAD

**Issue by Xtendera** [MultiMC/Launcher#3782]
I am new to PC Minecraft. I bought PC Minecraft almost 2 years ago, but never switched from Xbox to PC, even though I knew its advantages. When I finally did, a friend suggested that I use MultiMC. I managed to make an instance made and I even figured out how to install forge and fabric. I found a mod on curse forge which I wanted to install, but it said it **required** Optifine. I found [this](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine). I first tried the OptiFabric method, but soon realized that I can't use Forge and Fabric together. OptiFabric, as it turns out, was the only way I could get OptiFine working at all. I then tried "The jar mod way" as they list it. It didn't give me errors, but nothing happened. I opened Minecraft and OptiFine was nowhere to be seen. Even if I pressed F3 while in a game, it didn't show me anything related to OptiFine. I also tried the method called "The launchwrapper tweaker way (listed versions)", but it gave the same result as "The jar mod way". Can anyone tell me what I am doing wrong?

**Comment by ImperatorStorm** [comment]
This is a bug tracker, not a support forum. Try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
