### ISSUE TITLE
Missing trad key -- dev version

### ISSUE THREAD

**Issue by Starmania** [MultiMC/Launcher#3885]
### Operating System

Windows

### Description of bug

Missing Traducting key for this line in code https://github.com/MultiMC/MultiMC5/blob/6c0ff0b46fa153960c592ff789a6053dbd9730f9/application/dialogs/LoginDialog.ui#L26

### Steps to reproduce

* Set language of MMC an another of English
* Go profiles
* Click on Add button
* "NOTICE: [...] used." won't be traducted

OR

* Go Crowdin project
* You can't traduce this text.

### Suspected cause

Missing Crodin key for this line

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Though frustrating, as I understand translations target stable - so there's a while bunch of currently untranslatable strings at the moment.
