### ISSUE TITLE
Inconsistent Launch Directory on Ubuntu/Plasma

### ISSUE THREAD

**Issue by rehashedsalt** [MultiMC/Launcher#3974]
### Operating System

Linux

### Description of bug

Upon launch via the provided `.desktop` file from the `.deb` package, MultiMC functions as expected, `cd`-ing to this directory and unzipping a release tarball before executing MultiMC:

```
~/.local/share/multimc
```

However, many desktop environments have functionality to pin MultiMC to some form of quick-launch bar. In my case, I'm using Plasma and pinning it to a taskbar while the application is running. When MultiMC is later launched from this pinned entry, CWD is mangled and MultiMC creates an entirely new base directory structure (with `instances` and whatnot) in this directory:

```
~/.local/share/multimc/bin
```

### Steps to reproduce

* Install some form of supported operating system -- for my tests I used KDE Neon to ensure the bug wasn't fixed in a later version of the DE, but I have also replicated on Ubuntu 20.04
* Install MultiMC from the stable `.deb` package on multimc.org
* Launch MultiMC via the `.desktop` file (i.e. from the Application Launcher)
* Run through the setup screen
* Pin the application to the Task Manager
* Open MultiMC via the Task Manager
* Get greeted with another setup screen
* Peer in `~/.local/share/multic/{,bin}` to see weirdness

### Suspected cause

This all seems to stem from some weird behavior with MultiMC's portability. MultiMC as installed from the package is intended to be run out of this directory (sans `XDG_DATA_HOME` weirdness):

```
~/.local/share/multimc
```

But because the binary executed is actually located in `multimc/bin/`, Plasma thus executes MultiMC out of this directory after it's pinned:

```
~/.local/share/multimc/bin
```

Which causes MultiMC to duplicate directory structures in there. I suspect this is the case based on the contents of `~/.config/plasma-org.kde.plasma.desktop-appletsrc`, which use the following URI for the Task Manager pin:

```
file:///home/user/.local/share/multimc/bin/MultiMC?iconData=[an SVG in base64 here]
```

And based on the destination of `/proc/$MULTIMC_PID/cwd` when the application is launched from the taskbar:

```
cwd -> /home/user/.local/share/multimc/bin/
```

What's confusing is that the release tarballs for Linux appear to contain *two* binaries for MultiMC, and the shell script bundled in the `.deb` archive executes the one in `multimc/`, not `multimc/bin/`. Does MultiMC later pivot to the one in `multimc/bin/` during the startup process, confusing the DE?

---

As a mitigation, a user can -- instead of first launching the application and pinning it to the Task Manager -- pin the application by right-clicking the entry in the Application Launcher and pinning that. This causes the Task Manager to instead pin the `.desktop` file, which will launch properly every time:

```
# From ~/.config/plasma-org.kde.plasma.desktop-appletsrc
applications:multimc.desktop
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
> What's confusing is that the release tarballs for Linux appear to contain _two_ binaries for MultiMC

No, there is not two binaries.  `MultiMC` located in `~/.local/share/multimc` is a bash/shell script.

If you look at the `.desktop` entry it correctly exec's the shell script - not the binary located in `~/.local/share/multimc/bin`

In fact I have seen similar issues like this with other programs that exec a bash script and users try to pin those to the taskbar.  For those other issues its been either closed with `wontfix` or `external` labels.

This is a known KDE bug that has been around for quite some time.

**Comment by rehashedsalt** [comment]
Ah, that makes a bit more sense. `multimc.desktop` -> `/opt/multimc/run.sh` -> `~/.local/share/multimc/MultiMC` -> `~/.local/share/multimc/bin/MultiMC`, but Plasma only sees the last process.

I can understand closing these sorts of issues as `wontfix`, but there really isn't a good solution from the DE side. Plasma has no way of inferring what executable to pin. You could argue that Plasma should launch programs in their own cgroups or something and tie the `.desktop` file to that cgroup, but even that causes issues when programs launch other programs via normal POSIX means or when `.desktop` files launch programs in terminals.

The easiest way for the wrapper script to communicate to the system what executable should be pinned would be by setting `argv[0]`, which is where Plasma looks to get the path to the executable to pin. A small tweak accomplishes this and thus fixes Plasma's broken invocation (and likely the invocation of any other DEs that implement similar features) while using `exec` gets rid of a redundant parent Bash shell during runtime:

```diff
--- MultiMC.bak 2021-07-27 13:10:56.999668636 -0500
+++ MultiMC     2021-07-27 13:20:59.959123190 -0500
@@ -35,7 +35,7 @@
     chmod +x "${MMC_DIR}/bin/MultiMC"
 
     # Run MultiMC
-    "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
+    exec -a "${MMC_DIR}/MultiMC" "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
 
     # Run MultiMC in valgrind
     # valgrind --log-file="valgrind.log" --leak-check=full --track-origins=yes "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
@@ -43,9 +43,6 @@
     # Run MultiMC with callgrind, delay instrumentation
     # valgrind --log-file="valgrind.log" --tool=callgrind --instr-atstart=no "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
     # use callgrind_control -i on/off to profile actions
-
-    # Exit with MultiMC's exit code.
-    exit $?
 else
     # apt
     if which apt-file &>/dev/null; then
```

**Comment by peterix** [comment]
Interesting... But will KDE run it correctly with the `-d "${MMC_DIR}"` preserved?

I guess that needs to be tested.

**Comment by peterix** [comment]
Yep. It fixes the issue on KDE... at hte very least.
