### ISSUE TITLE
"Add Microsoft" account login cannot complete the sign-in process.

### ISSUE THREAD

**Issue by NohanMV** [MultiMC/Launcher#4050]
### Operating System

Windows

### Description of bug

**OS**: WIndows 11 build 10.2000.160
**MultiMC**: 0.6.12-develop-2042

_Summary_: 

MultiMC cannot complete the sign-in process after the Microsoft to MultiMC link and either gets stuck indefinitely or instantly crashes.

_Detailled explanation_: 

When adding a Microsoft account via the "Add Microsoft" button on MultiMC, after the initial Microsoft web sign-in process, MultiMC does not seem to be able to finish adding the account, giving two case scenarios;

- The progress bar goes back and forth while switching between "Logging in on XBox and Mojang services" and "Connect to Xbox user" and seems to never finish (I had to close MultiMC manually):
Thank you captainboggle#4865 for the images
https://postimg.cc/YGQtKV7K
https://postimg.cc/rRcM8Jyd

- Right after the web sign-in finishes, MultiMC instantly crashes.

**(Hope this can help)**
Weirdly enough I have noticed that by just clicking on the "Add Microsoft" button and not doing anything after that, the progress bar seems to slowly go up by itself, and after about two minutes of waiting, the green progress bar occupied more than 1/3rd of it's space, at that point I wanted to see what would happen if I tried doing the setup, so I clicked the link, connected my Microsoft account, and ABRACADBRA! it worked! No hiccups and it was instantaneous. So it's either that or you just need to retry again and again until it works.

### Steps to reproduce

**Reproduce bug**:

Launch MultiMC.
Go to accounts.
Press the "Add Microsoft" button and connect your Microsoft account.
Go back to the progress bar.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by coffeepostal** [comment]
Same problem, but on Mac.

OS: macOS Mojave 10.14.6
MultiMC: 0.6.12-develop-2433

Summary:
MultiMC creates link and generates a code, everything appears to connect on Microsoft's side, but MultiMC returns the error: "XBox user authentication failed." in red.

[Screen Shot](https://postimg.cc/gxYRSZPg)

**Comment by peterix** [comment]
Should be fixed in dev.
