### ISSUE TITLE
FTB Modpack "Failed to copy files"

### ISSUE THREAD

**Issue by zkov96** [MultiMC/Launcher#4055]
### Description of bug

I have bug on downloading FTB Presents Direwolf20 1.16 modpack with duplicated record on manifest.

### Steps to reproduce

1. Open New instance
2. Select FTB
3. Select FTB Presents Direwolf20 1.16
4. Choose version 1.11.0
5. Press Ok
6. Wait for "Failed to copy files" message

### Suspected cause

Duplicated file records in manifest https://api.modpacks.ch/public/modpack/79/2067 : "name": "metadata.json"
{
            "version": "9",
            "path": "./config/",
            "url": "https://dist.modpacks.ch/modpacks/9/metadata/config/7a8538e323c8854678d0bc3d2f9b086d5f8b69f6",
            "sha1": "7a8538e323c8854678d0bc3d2f9b086d5f8b69f6",
            "size": 116,
            "tags": [],
            "clientonly": false,
            "serveronly": false,
            "optional": false,
            "id": 283485,
            "name": "metadata.json",
            "type": "config",
            "updated": 1629315332
}

{
            "version": "10",
            "path": "./config/",
            "url": "https://dist.modpacks.ch/modpacks/10/metadata/config/73666710978bc42f2811ef07782cffad3a3cfd7a",
            "sha1": "73666710978bc42f2811ef07782cffad3a3cfd7a",
            "size": 116,
            "tags": [],
            "clientonly": true,
            "serveronly": false,
            "optional": false,
            "id": 283657,
            "name": "metadata.json",
            "type": "config",
            "updated": 1629315337
}

May be fix them by check largest version of record

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by xenoflot** [comment]
Interestingly, I'm getting this with MMC 0.6.12-develop-2431 but my friend downloaded just fine, running 0.6.12-1530

**Comment by Zetabite** [comment]
They might have fixed the issue.

**Comment by jamierocks** [comment]
No, they haven't. It works on stable, because it doesn't verify checksums.

**Comment by Blockguy24** [comment]
I'm also getting this on version 0.6.13-2519

**Comment by jamierocks** [comment]
Yeah, a new stable release was made. MultiMC should probably revert that change for the time being.

**Comment by phit** [comment]
workaround was added a while ago, the metadata is on FTB to fix
