### ISSUE TITLE
Add "Copy to Clipbord" to Microsoft Account Login

### ISSUE THREAD

**Issue by LifeLifeLP** [MultiMC/Launcher#4095]
### Role

I play Minecraft modded and unmodded.

### Suggestion

Copy to Code in need to login with a Microsoft Account in the Clipbord

### Benefit

This would make logging in with a Microsoft Account faster and easier. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by udu3324** [comment]
I agree with this. This would be a pretty nice QOL feature.

**Comment by jamierocks** [comment]
This is a decent suggestion, I think.

It is worth noting, if you're not already aware though, that you can select and copy the text at present.

**Comment by LifeLifeLP** [comment]
@jamierocks Very true. I made this Suggestion because (at least on Windows) it is very uncommon that you can select and copy Text from Info/Dialog Windows.

**Comment by phit** [comment]
was added 2 years ago https://github.com/MultiMC/Launcher/commit/86f68389c9056279c198be3ab0854f1a607dc24f
