### ISSUE TITLE
Mojang authentication is unstable

### ISSUE THREAD

**Issue by oplexz** [MultiMC/Launcher#4131]
### Operating System

Windows

### Description of bug

The issue appears when you try to add a new Mojang account. The progress stops at "Getting Minecraft profile", as seen on the screenshot below.

![image](https://user-images.githubusercontent.com/12859907/135244654-c26200c9-fa90-4c78-b207-f40222cd29af.png)

Originally discovered by a fellow: he was able to add the account, but the game couldn't start, as the launch progress was stuck on "Getting Minecraft profile".
I tried reproducing it on my laptop, could add the account, but launcher was stuck with the same message.
Upon trying to reproduce the issue on my PC, at first I couldn't add the account at all, as it was stuck on "Getting Minecraft profile". Then after restarting MultiMC, I could add the account, but couldn't start the game - "Getting Minecraft profile". After another restart, it got past that message, but got stuck on "Checking for migration eligibility".

If "Getting Minecraft profile" appears upon adding an account, you can close the login dialog, and try to add it again.

If "Getting Minecraft profile" appears upon trying to start the game, it gets stuck for about 30 seconds (presumably timeout?), then another dialog appears, says "Minecraft Java profile acquisition failed" (screenshot attached below), and lets you input the password once again. Once you input the password again, it logs in and the game starts up correctly.

If "Checking for migration eligibility" appears upon trying to start the game, the launcher is frozen and you can't do anything. You can't press "Play Offline" or close the "Please wait" window.

![image](https://user-images.githubusercontent.com/12859907/135245001-eea44681-e50e-4394-8001-c3ffd45ebeca.png)

### Steps to reproduce

1. Add a new Mojang account (that you haven't used with this MultiMC build before)
2. If you got past point 1, try starting any Minecraft instance (I created a brand new 1.17.1 instance)
3. If you got stuck on "Getting Minecraft profile", wait until the timeout, and input the password again
3.1 If you got stuck on "Checking for migration eligibility", there's nothing you can do, other than kill the MultiMC process

Was reproduced on Windows 10 19042.746 (with MultiMC 0.6.13-2517), Windows 11 22463.100 (with MultiMC 0.6.13-2517, 0.6.13-develop-2570)

### Suspected cause

Unknown

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by oplexz** [comment]
I'm willing to provide the Mojang account in question for testing purposes.

**Comment by oplexz** [comment]
Here are the logs from 0.6.13-2517.
The file may have some unneccessary logs, but it was stuck on "Checking for migration eligiblity" for an hour or so before I killed the process.

[MultiMC-0.log](https://github.com/MultiMC/MultiMC5/files/7251666/MultiMC-0.log)

**Comment by phit** [comment]
error 4 is a timeout, is something blocking the connection the the microsoft servers?

**Comment by oplexz** [comment]
@phit I don't think so, I'm using a freshly installed Windows 11, so nothing should be blocking the connection. Also, from what I see, once it starts up properly once, no problems occur anymore. So it's just the first startup.

I just removed the profile from accounts.json manually, tried adding the account again and ended up getting error 4 again. Here are the logs (and a screenshot, just in case)

![add-account-getting-minecraft-profile](https://user-images.githubusercontent.com/12859907/135269133-4d53208d-845a-415f-bf45-5e7ebf6119b2.png)
[MultiMC-0-add-account.log](https://github.com/MultiMC/MultiMC5/files/7251817/MultiMC-0-add-account.log)

**Comment by phit** [comment]
Reproduced in https://github.com/MultiMC/MultiMC5/issues/4147, network errors aren't being caught properly so the process gets stuck.

**Comment by phit** [comment]
error handling has gone through many changes now and should be a lot more stable, if you run into this or new issues on the latest development versions please open a new issue with updated MultiMC logs
