### ISSUE TITLE
issue when logging on to a microsoft account

### ISSUE THREAD

**Issue by Enderlord252** [MultiMC/Launcher#4152]
### Operating System

Linux

### Description of bug

every time it redirects to the login (web browser im using is Firefox+chrome) i get a error that it doesn't show the client id, is this a redirect problem or a bug on Microsoft's end

### Steps to reproduce

pressed the log in with Microsoft button

### Suspected cause

![dangit](https://user-images.githubusercontent.com/92061710/136290161-6d70df15-f2c5-4863-9ec8-a8a8f54cdf0d.png)
i have a feeling this is more on Microsoft's end

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Seek support from whoever maintains the MultiMC package you're using.
