### ISSUE TITLE
I Can't Use My Minecraft Account And The Services Are All Red

### ISSUE THREAD

**Issue by escaleirex** [MultiMC/Launcher#4166]
I Just Installed Multi MC in Linux and i Can't use my account and every service is red.
![image](https://user-images.githubusercontent.com/69918820/136853846-03acdab7-f2d8-43c8-8f3a-5dd657e196e7.png)
![image](https://user-images.githubusercontent.com/69918820/136853879-c6429987-788d-4962-a4da-c28d920e793b.png)

**Comment by Zetabite** [comment]
You can ignore the status bar, its discontinued by mojang and already fixed in the dev version. As for the microsoft account, its a common issue. Removing and then readding the account to MMC seems to work, but that might not necessarly fix it and this is sadly not in our hand.

**Comment by 12345AVD** [comment]
oh i just made another issue about it
