### ISSUE TITLE
Instance update failed: impossible to fetch required libraries

### ISSUE THREAD

**Issue by Tewarsk** [MultiMC/Launcher#4171]
i recently saw multimc support now microsoft account so i wanted to go back on mmc.
i make an instance with mods and launch with microsoft account and i get this error:
if someone can help cuz i don't want to go back on minecraft launcher...

MODS I USE: (version 1.12.2)
cocricotmod
customnpcs
justenoughids
moarsigns
nefdecomod
optifine
signpost
worldedit

On the minecraft launcher i have no crash so idk why i have on mmc
thanks for reading ;)

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Sword Tale' failed to process:
https://files.minecraftforge.net/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
https://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2855/forge-1.12.2-14.23.5.2855-universal.jar
https://files.minecraftforge.net/maven/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
https://files.minecraftforge.net/maven/org/jline/jline/3.5.1/jline-3.5.1.jar
https://files.minecraftforge.net/maven/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
https://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
https://files.minecraftforge.net/maven/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
https://files.minecraftforge.net/maven/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar

**Comment by phit** [comment]
please upload your main log file `MultiMC-0.log` from the main launcher folder to https://paste.ee/ and post the link here

**Comment by burunduk** [comment]
https://paste.ee/p/yFRH2

**Comment by phit** [comment]
@burunduk open https://maven.minecraftforge.net/ in Internet Explorer or Edge and then try again
