### ISSUE TITLE
[Feature Request] Adding pack version number to default instance name

### ISSUE THREAD

**Issue by csonyi** [MultiMC/Launcher#4185]
### Role

I play modded minecraft

### Suggestion

Changing the behaviour of the instance name when adding a new instance

### Benefit

Adding a new version of a pack would be a bit easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would be awesome if you could add the pack version to the default name of the instance you are creating.

Currently if I install a new version of a pack after its updated, I have to type out the pack name and add the version number behind it manually.

If it had the version number by default the pack update process would be as easy as few clicks, no typing neccessary.

**Comment by jamierocks** [comment]
Yeah I brought this up a short while back, I think this should be done too.
