### ISSUE TITLE
"Add Microsoft" button greyed out on Linux?

### ISSUE THREAD

**Issue by Reactified** [MultiMC/Launcher#4189]
### Description of bug

I recently migrated my Mojang account to a Microsoft account (because of threats of losing your account otherwise) and I am able to play using MultiMC on Windows, but for some reason, the button to add a Microsoft account is greyed out on Linux.

Is there some setting I need to change, or do Microsoft accounts not currently work on Linux?

I'm running Manjaro KDE (arch based), if that helps.

### Steps to reproduce

- Download the multimc5 package from the Arch User Repository
- Attempt to add a Microsoft account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SDWaps** [comment]
Im, sorry ,but how to install?

**Comment by peterix** [comment]
Go to https://multimc.org/

Get the deb package (it's labeled ubuntu)

It should work on Debian too

**Comment by PurpleVsGreen** [comment]
I followed the build instructions on https://multimc.org/#Source and still got a greyed out "Add Microsoft" button

Which sources should I build instead?

**Comment by jamierocks** [comment]
You would need to supply your own Microsoft OAuth client identifier. See 'notsecrets'.

**Comment by PurpleVsGreen** [comment]
Thank you for your quick response! I made an application in Azure Active Directory, placed the ID in the relevant QString, and now it says "Microsoft user authentication failed."

The terminal shows this output:
```
    4.251 D Task "MSAInteractive(0x708c0000a9d0)" starting for the first time
    4.251 D OAuth2::unlink
    4.251 D OAuth2::link
    4.251 D O2ReplyServer: Starting
    4.251 D OAuth2::setLinked: false
    4.251 D OAuth2::setRefreshToken "" ...
    4.681 W OAuth2::onTokenReplyError:  QNetworkReply::AuthenticationRequiredError :  "Host vereist authenticatie"
    4.681 D OAuth2::onTokenReplyError:  "{\"error\":\"invalid_client\",\"error_description\":\"AADSTS70002: The provided client is not supported for this feature. The client application must be marked as 'mobile.'\\r\\nTrace ID: e2383cc6-627d-4961-a4ce-d82ee99ab000\\r\\nCorrelation ID: c1307975-2744-4f48-85b0-35190c94e44f\\r\\nTimestamp: 2021-10-30 09:53:24Z\",\"error_codes\":[70002],\"timestamp\":\"2021-10-30 09:53:24Z\",\"trace_id\":\"e2383cc6-627d-4961-a4ce-d82ee99ab000\",\"correlation_id\":\"c1307975-2744-4f48-85b0-35190c94e44f\",\"error_uri\":\"https://login.microsoftonline.com/error?code=70002\"}"
    4.681 D OAuth2::setRefreshToken "" ...
    4.683 C Task "MSAInteractive(0x708c0000a9d0)" failed:  "Microsoft user authentication failed."
    4.683 D OAuth2::onDeviceAuthReplyFinished
```

I'm probably doing something wrong, but there isn't an option anywhere in the azure portal to mark the application as "mobile". And I already loathed MSFT, they keep giving me more reasons

**Comment by PurpleVsGreen** [comment]
I think I got it! First of all, this only works on a /desktop/ browser, not phones or tablets. Secondly, on a desktop browser when editing the application there's a menu on the left titled "Manage". Select "Verification" from that menu and then there's 2 yes/no buttons. Enable them and click "Save" at the top.

**Comment by Zetabite** [comment]
that discussion should be lead on discord in development case. else use the existing packages.

**Comment by peterix** [comment]
This is not a support site for forks. Neither is the discord server.
