### ISSUE TITLE
Easy Native M1 Instances

### ISSUE THREAD

**Issue by Jomyy** [MultiMC/Launcher#4191]
### Role

I Play on a m1 mac 

### Suggestion

Detect if a macbook has the new m1 chip and automatically choosing the right libs for the game

### Benefit

easyer better performance for casual players

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would help casual not Programmer people to get good performance in minecraft on m1 (or in the future m1 max/pro) macbooks without having to use terminals and wierd things

**Comment by AurevoirXavier** [comment]
It looks like ARM was supported officially now.

**Comment by iMonZ** [comment]
> We already choose the appropriate natives for the system being used.
> 
> However, Mojang do not support ARM systems and consequently neither do we.

But you could just add arm support. Why not? Would run much better. And the game itself is using java. with the right runtime no need for arm support in minecraft itself

**Comment by jamierocks** [comment]
> But you could just add arm support. Why not? 

We're not the game developers. We could have built the launcher for Apple Silicon, but it wouldn't have meant the game would run (natively) on those systems.

> And the game itself is using java. with the right runtime no need for arm support in minecraft itself

The game also uses libraries such as LWJGL (and it many libraries) and OSHI that require native libraries. It's not as simple as just having a JVM available on the system.

---

With that said, I believe that the game (atleast recent releases) supports Apple Silicon systems now (I say Apple Silicion specifically, as I'm unsure to aarch64 support more broadly than on Mac). I'm unsure what level, if any, of support MultiMC has for aarch64 today. I don't believe that it is shipped for Apple Silicon currently, but there is a new major version being worked on.

Unfortunately I don't work on MultiMC anymore, so I can't comment on that.
