### ISSUE TITLE
Recent Enigmatica 6 packs will not launch

### ISSUE THREAD

**Issue by Brenlen** [MultiMC/Launcher#4196]
### Operating System

Windows

### Description of bug

The last two versions of Enigmatica 6, added as a new instance via the the CurseForge server, fail to launch following installation. I am playing an older version I downloaded from the same source several months ago, that launches without problem.

MultiMC version: 0.6.13-develop-2743

Minecraft folder is:
D:/games/MultiMC/instances/Enigmatica 6 - E6 - 1.16.51/minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_311/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_311, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Enigmatica 6 - Does not launch' failed to process:
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.4/forge-1.16.5-36.2.4-installer.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.4/forge-1.16.5-36.2.4-launcher.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.4/forge-1.16.5-36.2.4-universal.jar
https://maven.minecraftforge.net/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
https://maven.minecraftforge.net/com/opencsv/opencsv/4.4/opencsv-4.4.jar
https://maven.minecraftforge.net/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
https://maven.minecraftforge.net/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
https://maven.minecraftforge.net/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
https://maven.minecraftforge.net/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
https://maven.minecraftforge.net/net/md-5/SpecialSource/1.10.0/SpecialSource-1.10.0.jar
https://maven.minecraftforge.net/net/minecraftforge/installertools/1.2.6/installertools-1.2.6.jar
https://maven.minecraftforge.net/net/minecraftforge/jarsplitter/1.1.4/jarsplitter-1.1.4.jar
https://maven.minecraftforge.net/net/minecraftforge/srgutils/0.4.3/srgutils-0.4.3.jar
https://maven.minecraftforge.net/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
https://maven.minecraftforge.net/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
https://maven.minecraftforge.net/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm/9.1/asm-9.1.jar
https://maven.minecraftforge.net/org/ow2/asm/asm/9.1/asm-9.1.jar

Clipboard copy at: 24 Oct 2021 17:48:46 +0100

### Steps to reproduce

1) Add new instance
2) Go to CurseForge
3) Select & download Enigmatica 6 - E6 - 1.16.5 version 0.5.17 or 0.5.16 
4) Launch game
5) Read log of failed launch

This specific problem is not listed in the active bug list

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the fix is probably to visit https://files.minecraftforge.net with Internet Explorer or Edge. but that's just a guess and without a log we can't help you any further, I'll be happy to reopen this issue if you provide a log file
