### ISSUE TITLE
MultiMC Launcher fails to run when Huion tablet software is running

### ISSUE THREAD

**Issue by Gepleo** [MultiMC/Launcher#4202]
### Operating System

Windows

### Description of bug

Starting with HuionTablet app version 15, MultiMC fails to launch if HuionTablet is running. A MultiMC process is created, but the application does not fully launch. Closing HuionTablet will let MultiMC run again. 

### Steps to reproduce

1. Run HuionTablet v15. (Lower versions seem to not cause this issue.)
2. Try to run MultiMC
3. Fail
4. Cry when you can't play Minecraft

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
looks like an external issue, nothing we can do about that
