### ISSUE TITLE
Despite wrapper scripts working correctly, pre-launch and post-exit scripts do not run

### ISSUE THREAD

**Issue by cocona20xx** [MultiMC/Launcher#4208]
### Operating System

macOS

### Description of bug

Expected Behavior: Pre-Launch and Post-Exit scripts launch correctly when a path to a file containing said script(s) are specified in the Custom Commands settings window arguments

Actual Behavior: Despite Wrapper scripts running correctly (as I use one to tell minecraft to use ARM64/Apple Silicon native LWJGL binaries), and regardless of if I actually run a wrapper script on the instance or not, Pre-Launch and Post-Exit scripts *do not run*, with multimc reporting `The process failed to start. [Command-Type] command failed with code 0.` where [Command-Type] is, of course, replaced with Pre-Launch or Post-Exit. This is regardless of if the script is valid or not. 

### Steps to reproduce

* Create a valid python or shell script to be ran before or after the instance launches. 
* Set the script as a Pre-Launch or Post-Exit command
* The script will fail to start, and return an exit code of 0, irregardless of location. 
Furthermore, if the script is a Pre-Launch script, the game will fail to run as it should when an 0 exit code is returned.

### Suspected cause

Not sure, honestly; might be some weirdness with macOS file protection conventions going on? I *have* turned off Gatekeeper file signage checking for multimc and the script, but doing so does not solve the issue. It's also really odd that wrapper scripts seem to work fine?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
MultiMC is not a python interpreter. Or a bash script interpreter. Or anything like that at all.

If you want to run a program like python or bash, you have to run those programs.

**Comment by cocona20xx** [comment]
Issue seems to be an oddity with macOS that is probably not fixable on multimc's end, see https://apple.stackexchange.com/a/269045

Basically, script files have to be at least 28 bytes in size, or they simply will not run, this is likely what I was running into

**Comment by peterix** [comment]
Hmm. Directly running the interpreter and telling it to load the script should still work?
