### ISSUE TITLE
demon slayer

### ISSUE THREAD

**Issue by Alonchips** [MultiMC/Launcher#4210]
### Description of bug

i added the koopekul modpack in and it dosent do it like it dosent work

### Steps to reproduce

e

### Suspected cause

e

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
Your issue has so little information that it is not actionable. "koopekul" is not found on CurseForge and "demon slayer" is ambigious. Don't provide so little information and expect anyone to help you. "like it doesn't work" says absolutely nothing of value.

**Comment by phit** [comment]
Please fill out the issue form correctly. There is not enough information provided here for anyone to help you.

**Comment by Alonchips** [comment]
i dont want now

**Comment by Zetabite** [comment]
then you wont get help yet.

**Comment by Alonchips** [comment]
i know
