### ISSUE TITLE
Microsoft account login unavalible when building from source on Linux

### ISSUE THREAD

**Issue by getchoo** [MultiMC/Launcher#4212]
### Operating System

Linux

### Description of bug

After compiling from source using the instructions (found [here](https://github.com/MultiMC/Launcher/blob/develop/BUILD.md)) on Arch Linux, I am unable to login to my migrated Microsoft account.

### Steps to reproduce

My reproducible PKGBUILD for Arch Linux can be found [here](https://aur.archlinux.org/packages/multimc5/).

Simply run something like `makepkg -si` in the PKGBUILD's directory, launch MultiMC, and try to login to a Microsoft account.

### Suspected cause

My best guess for the cause would be something to do with the API keys not being correctly enabled in user-compiled builds.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
thats intentional. use packages distributed by mmc, else you will have to deal with this on your own by reading notsecrets
