### ISSUE TITLE
Multiple Java version without changing instance by instance.

### ISSUE THREAD

**Issue by Starmania** [MultiMC/Launcher#4213]
### Role

Minecraft use different version of Java.

### Suggestion

At the creation of instance, tell what Java version (8, 11 or 16) use for this minecraft version 

### Benefit

Internal at MultiMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Also, allow multiple java detection by version.

**Comment by Starmania** [comment]
PS: sorry for my english, I'm french...

**Comment by peterix** [comment]
Nope. We're not going to do it this way. We already should know what Java version to use based on the Minecraft version, no need to tell it.

But the problem *will* be addressed.

**Comment by Starmania** [comment]
Ok, thx.
I suspected it ...

**Comment by Starmania** [comment]
And for the paths to different versions, what do you think?

**Comment by Starmania** [comment]
And when I sent this suggestion, I imagine this.

![Imagine](https://user-images.githubusercontent.com/52313983/139665427-a33889bb-c267-4091-b67e-c0717b031c49.png)

**Comment by peterix** [comment]
I don't want to do it this way.
