### ISSUE TITLE
ftb packs with mc 16.5

### ISSUE THREAD

**Issue by silvolivi** [MultiMC/Launcher#4214]
### Operating System

Windows

### Description of bug

when i launch ftb packs (such as OceanBlock) i receive following error (italian)

Aggiornamento dell'istanza fallito perché: Aggiornamento di gioco fallito: impossibile recuperare le librerie richieste.
Causa:
Impossibile elaborare l'attività 'Librerie per l'istanza FTB OceanBlock 1.5.0':
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-installer.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-launcher.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-universal.jar
https://maven.minecraftforge.net/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar

### Steps to reproduce

installing from ftb repo and launc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Starmania** [comment]
No error for me.

**Comment by phit** [comment]
open https://files.minecraftforge.net/ in Internet Explorer or Edge then try again

**Comment by silvolivi** [comment]
on IE (via proxy, as for Multimc) https://files.minecraftforge.net gives me
back an https error (

DLG_FLAGS_SEC_CERT_DATE_INVALID

Il giorno lun 1 nov 2021 alle ore 16:25 Philip T. ***@***.***>
ha scritto:

**Comment by phit** [comment]
that should only happen once or so until Windows downloads the required certificate, then the site should work, if it doesn't for you that's your problem and out of scope for us to help you with

**Comment by silvolivi** [comment]
Tomorrow i'll try without the proxy, maybe it's is the problem.. even on
other previous ftb modpacks never happened..

Il Lun 1 Nov 2021, 18:52 Philip T. ***@***.***> ha scritto:

**Comment by silvolivi** [comment]
even without proxy same error.. i'll post all log :

MultiMC version: 0.6.13-develop-2786



Launched instance in online mode

Authentication server is online


authserver.mojang.com resolves to:

[13.226.160.74]


session.minecraft.net resolves to:

[N/A]


textures.minecraft.net resolves to:

[108.139.243.57, 108.139.243.6, 108.139.243.62, 108.139.243.16]


api.mojang.com resolves to:

[13.226.172.209]



Minecraft folder is:

C:/Program Files/MultiMC/instances/FTB OceanBlock 1.5.0/minecraft



Java path is:

C:/Program Files/Java/jre1.8.0_171/bin/javaw.exe



Checking Java version...

Java is version 1.8.0_171, using 64-bit architecture, from Oracle
Corporation.



Aggiornamento dell'istanza fallito perché: Aggiornamento di gioco fallito:
impossibile recuperare le librerie richieste.

Causa:

Impossibile elaborare l'attività 'Librerie per l'istanza FTB OceanBlock
1.5.0':

https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-installer.jar

https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-launcher.jar

https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-universal.jar

https://maven.minecraftforge.net/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar








Il giorno lun 1 nov 2021 alle ore 19:09 Silvio Oliviero ***@***.***>
ha scritto:

**Comment by silvolivi** [comment]
problem solved with ftb app ... sorry for u

Il giorno lun 8 nov 2021 alle ore 12:17 tortoise ***@***.***>
ha scritto:
