### ISSUE TITLE
Add suport to the new minecraft pc bundle

### ISSUE THREAD

**Issue by arcal2014** [MultiMC/Launcher#4217]
### Role

minecraft java is now inclued on game pass by the minecraft pc bundle.

### Suggestion

Add suport to the new minecraft pc bundle.

### Benefit

peploe that do not have the minecraft java buyed on mojang but have the pc bundle that is on the game pass.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
does logging in with a Microsoft account not work for this?

**Comment by peterix** [comment]
There should be no need to do anything.

**Comment by ObsidianOS7** [comment]
![image](https://user-images.githubusercontent.com/71942224/139967254-12b6904e-7798-4940-8623-ba5e273e2775.png)

**Comment by theofficialgman** [comment]
I've also heard from other uses that accounts with the gamepass subscriptions do not work in multimc
At least on the windows version of the minecraft launcher, microsoft seems to have updated it specifically to work with gamepass

![image](https://user-images.githubusercontent.com/28281419/140010241-0c623b7e-aa5e-48ed-ae73-962803884709.png)

**Comment by peterix** [comment]
Again, that should just work. All MultiMC cares about is whether you have a Minecraft profile.

**Comment by peterix** [comment]
I'll have to explore this.

**Comment by SilverGoldCharzard** [comment]
![image](https://user-images.githubusercontent.com/93889717/140667199-e7f0df83-d656-4d15-8a94-e849ff667911.png)
I can confirm that Xbox Gamepass Subscription Accounts do not work.

**Comment by tort-oise** [comment]
Well, can we do much about them not working? It's not like Microsoft will tell us how Game Pass authentication works.

It seems we might have to look into this further. Maybe make it a goal to support Game Pass users.

**Comment by theofficialgman** [comment]
@peterix atlauncher has added support for the gamepass users through this commit https://github.com/ATLauncher/ATLauncher/commit/1088aee8242af99159fd67c80138da71fe1fc1ca

not really sure whats going on here... it seems like they just removed more of their checks

**Comment by peterix** [comment]
@theofficialgman  That's actually exactly the wrong thing.

It needs a new endpoint for exchanging the X tokens fot Mojang tokens, and it needs to correctly handle setting up accounts without a profile that own the game.

You need entitlements for that. This is removing entitlements, and is an incorrect solution.

**Comment by theofficialgman** [comment]
thats what I thought.... just wanted to point it out incase you didn't know where to look. sounds like you got this understood

**Comment by peterix** [comment]
This should now be fixed in `develop` builds.
