### ISSUE TITLE
Some translations don't work

### ISSUE THREAD

**Issue by RDKRACZ** [MultiMC/Launcher#4218]
### Operating System

Linux but probably any other too

### Help button tooltip
![1a](https://user-images.githubusercontent.com/43277609/139917708-c1f96e94-1206-4d35-a2f6-d5635d30e2e9.png)
![1b](https://user-images.githubusercontent.com/43277609/139917709-c5152ac1-6821-4c1d-9335-a0614907c5d2.png)
### Patreon button
![2a](https://user-images.githubusercontent.com/43277609/139917711-5dbd379a-0288-4804-8430-739183ff2174.png)
![2b](https://user-images.githubusercontent.com/43277609/139917714-022be1c6-9d1e-4a9e-a04f-9c9a78825e70.png)
### Patreon button tooltip
![3a](https://user-images.githubusercontent.com/43277609/139917716-b901d9f8-a5af-4dd2-8cb3-bc62592a9188.png)
![3b](https://user-images.githubusercontent.com/43277609/139917718-305161a4-c9d4-4ee6-8923-82f8e6296bfc.png)
### Update button tooltip
![4a](https://user-images.githubusercontent.com/43277609/139917720-91766ad1-0a4f-405a-9f4a-acf9d6edfec8.png)
![4b](https://user-images.githubusercontent.com/43277609/139917721-65a67dde-1a4a-4b6f-9257-52afd5fea6ff.png)
### This is valid for many languages
![5](https://user-images.githubusercontent.com/43277609/139918497-e309a1e0-3c76-4e58-b989-bb94c54784cc.png)
![6](https://user-images.githubusercontent.com/43277609/139918518-1294155d-94e0-45b9-8a5f-3226f6117e3e.png)

### Steps to reproduce

Change UI language

### This issue is unique

- [X] I tried looking at open issues with the translation word.

**Comment by Percario** [comment]
Can confirm this issue on Windows as well.

**Comment by jamierocks** [comment]
Unable to reproduce this.

![image](https://user-images.githubusercontent.com/5103549/140650275-66bb81c0-4321-42cc-96fb-4ff3a9c9aa53.png)

**Comment by jamierocks** [comment]
Yeah, this isn't a bug. The term 'MultiMC' is no longer present in any translation keys.

When a new stable build is published, the new keys (e.g 'Get help with %1 or Minecraft.') will be available to be translated.
