### ISSUE TITLE
MultiMC fails to download Forge

### ISSUE THREAD

**Issue by Elinvynia** [MultiMC/Launcher#4219]
### Operating System

Linux

### Description of bug

Setup: Fedora 35, GNOME, Wayland, proprietary Nvidia drivers, Java 8

Error:
"Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Enigmatica 6 - E6 - 1.16.5' failed to process:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.4/forge-1.16.5-36.2.4-installer.jar

Log:
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/7466573/MultiMC-0.log)

### Steps to reproduce

Download either any modpack with Forge or just add any Forge version to a vanilla Minecraft instance.

### Suspected cause

Definitely not root certs since I am not on Windows (saw this as a solution to the exact same problem on similar issues)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Hotwire75** [comment]
Am getting the same thing trying to run oceanblock, might be an issue with minecraftforge.net, the links shown work when pasted into a browser, but when I use wget to try and get them, I see this:

---mylog---

$wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-installer.jar
--2021-11-03 22:25:26--  https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.8/forge-1.16.5-36.2.8-installer.jar
Resolving files.minecraftforge.net (files.minecraftforge.net)... 51.79.83.165, 2607:5300:203:65a5::
Connecting to files.minecraftforge.net (files.minecraftforge.net)|51.79.83.165|:443... connected.
ERROR: The certificate of ‘files.minecraftforge.net’ is not trusted.
ERROR: The certificate of ‘files.minecraftforge.net’ has expired.

---end_mylog---

**Comment by ImperatorStorm** [comment]
> Am getting the same thing trying to run oceanblock, might be an issue with minecraftforge.net, the links shown work when pasted into a browser, but when I use wget to try and get them, I see this:

works on my end, try updating `ca-certificates`

**Comment by Hotwire75** [comment]
Tried that, now have ca-certificates_20211016 from debian sid installed, and still no joy.

**Comment by Hotwire75** [comment]
Built and installed OpenSSL 1.1.1l instead of the default 1.1.0l in Debian 9, and it now works. It would appear that the older default OpenSSL may be no longer compatible.

**Comment by Elinvynia** [comment]
I have OpenSSL 1.1.1l and wgetting/downloading via browser worked even when I was getting that error.

This error is pretty weird since there is no underlying cause in the logs, and it has been working fine several hours later. (no packages were updated during that time nor anything else changed on my system)

**Comment by phit** [comment]
the fix is in https://github.com/MultiMC/meta-multimc/commit/4b2258c5207c85442d81879c59f274ab93be6ea3, forge changed their installers so you got a checksum mismatch
