### ISSUE TITLE
island.nbt file is not in the structures folder for FTB OceanBlock from MMC launcher.

### ISSUE THREAD

**Issue by Boocheh** [MultiMC/Launcher#4223]
### Description of bug

The file insland.nbt is missing from the destination it should be in. I know this because I added it manually and everything worked. With this file missing the world gen for the island selection does not work properly.

### Steps to reproduce

Download FTB OceanBlock from the MMC launcher and launch. Or just immediately check your folder for the island.nbt.
![](https://media.discordapp.net/attachments/889915860481892382/905961092721819719/unknown.png)
![unknown](https://user-images.githubusercontent.com/93745646/140434978-1c2b4267-16c0-4842-bb8b-c34887ba0b81.png)
 

### Suspected cause

Not sure, the file is just missing.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Fixed in the development update channel :)
