### ISSUE TITLE
Java is not detected

### ISSUE THREAD

**Issue by Samisafool** [MultiMC/Launcher#4224]
### Operating System

Linux

### Description of bug

MultiMC does not show java except default java

The different versions are stored in /usr/lib64/jvm/ (OpenSUSE default)

### Steps to reproduce

1. Start MultiMC in a new folder
2. See it only detects the java that's on $PATH

### Suspected cause

It should detect JREs and JDKs in /usr/lib64/jvm/, but it doesn't.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
missing 64 variant here https://github.com/MultiMC/Launcher/blob/fca2e9e44cb44004eec7f47c03b186bd5e44dc32/launcher/java/JavaUtils.cpp#L389

**Comment by phit** [comment]
fix is in the latest development version, thanks @NewoIsTaken
