### ISSUE TITLE
MultiMC launcher doesn't resize properly

### ISSUE THREAD

**Issue by SebbaIndustries** [MultiMC/Launcher#4225]
### Operating System

Linux

### Description of bug

So I use my own fork of dwm (dynamic window manager) from [dwm](https://dwm.suckless.org/), and every other application resizes properly so the issue is not with the window manager.

Here is a screenshot showing MultiMC going behind other windows when there should be 6px gap between windows at all times.

![image](https://user-images.githubusercontent.com/53937833/140516796-2f7cbd38-16a5-406e-bc27-bf60291a4109.png)

Example of correct behavior:
![image](https://user-images.githubusercontent.com/53937833/140516854-9989e597-c367-48ce-95d5-fba084ebebd8.png)

### Steps to reproduce

Arch Linux with kernel 5.14.15-arch1-1
dwm window manager (I can provide the my fork that I'm using in case you need it)

Open MultiMC and another application
Note: if only MultiMC is open and at full size it resizes perfectly.

### Suspected cause

No idea :/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Janrupf** [comment]
Resizing is handled by Qt. Either you messed up something in your fork or Qt is messing things up. See if the same issue occurs with upstream dwm. If not, then you'll have to see what your fork is doing

**Comment by SebbaIndustries** [comment]
Alright, I will try to replicate this with other Qt based applications, 
I'm skeptical that my dwm fork is to blame because only MultiMC has this issue but you can never know so thanks for the tips.

I'm closing the issue for now as this is most likely not the problem with actual MultiMC code base.
