### ISSUE TITLE
I cant open up 1.12.2

### ISSUE THREAD

**Issue by Orbitalmaker112** [MultiMC/Launcher#4226]
Whenever I get 1.12.2 setup from the videos i have seen it says this..

Couldn't extract native jar 'C:/Users/1686181/Downloads/MultiMC/mult/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar' to destination 'C:/Users/1686181/Downloads/MultiMC/mult/instances/1.12.2/natives'

Steps I take:
Create Instance > 1.12.2 > Edit Instance > Install Forge 14.23.5.2855(Recommended) > Launch     Then this happens ^^^

**Comment by phit** [comment]
Please fill out the issue form. There is not enough information provided here for us to help you.
