### ISSUE TITLE
Crash regarding invalid mods

### ISSUE THREAD

**Issue by halotroop2288** [MultiMC/Launcher#4227]
### Operating System

Windows

### Description of bug

When the mod list is loaded, or when the game is launched, MultiMC crashes without printing an error to the log.
We have narrowed this down to this specific mod file as a cause. It is probably corrupted, causing a parsing error. A [fresh download of the file](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct/files/2902483) does not cause this issue. (Thanks, Wiviw)

[TConstruct-1.12.2-2.13.0.183.jar.zip](https://github.com/MultiMC/Launcher/files/7491135/TConstruct-1.12.2-2.13.0.183.jar.zip)

Attached MD5 checksum: `DB85A498B1459C0CED53C994B44168DE`
Fresh MD5 checksum: `710d64342d41042b7d6ced891448e727`

### Steps to reproduce

0. Download the latest version of `MultMC (0.6.13-develop-2791)` and launch MultiMC
2. Create a new instance of Minecraft `1.12.2`, and install Minecraft Forge `14.23.5.2854`
3. Download the [attached file](https://github.com/MultiMC/Launcher/files/7491135/TConstruct-1.12.2-2.13.0.183.jar.zip) and place it in the new instance's mod folder
4. Edit the instance
	4a. Select the previously created instance from step [2]
	4b. Click the `Edit instance` button
	4c. Click the `Loader mods` tab
	4d. Observe as MultiMC closes without warning, before the tab fully loads.
5. Launch the instance
	5a. Open MultiMC
	5b. Select the previously created instance from step [2].
	5c. Click the `Launch` button
	5b. Observe as MultiMC closes without warning, the instance fails to launch.

### Suspected cause

The cause might be a corrupted mcmod.info file inside the jar, or it might be a corrupted jar.
One way or another, it seems to be caused by this specific mod file, as other mod files do not seem to cause this crash.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
could reproduce, nothing in the MultiMC log when it crashes

**Comment by Janrupf** [comment]
Weird, I can't reproduce the issue... but I'm getting a totally different checksum?!
`f280fae47171f3ad599761cb1c22a96f`
