### ISSUE TITLE
Game won't load: "Failed to create mod instance. ModId cb_microblock..."

### ISSUE THREAD

**Issue by jaalte** [MultiMC/Launcher#4232]
### Operating System

Windows 10, 64-bit
16GB RAM
GTX 1060-6GB

Java:    OpenJDK    jdk-16.0.1.9-openj9

### Description of bug

For some reason every time I try to run a pack through multimc that includes cb_microblock, it fails to load and my game won't start. It's affected FTB Oceanblock, Create: Above and Beyond, and potentially any other modpack which includes this mod.

I've been able to run the same modpacks through the ftb launcher and curseforge without this issue, so it looks like it's something to do with multimc or my configuration.

![image](https://user-images.githubusercontent.com/28464218/140681962-6c2bedfe-7a91-4845-ac52-fb3173bf6d8d.png)

### Steps to reproduce

Not sure, but here's my logs

The error happens on line 255 of latest.log
`[07Nov2021 19:46:13.986] [modloading-worker-15/ERROR] [net.minecraftforge.scorge.lang.ScorgeModContainer/LOADING]: Failed to create mod instance. ModId cb_microblock for class codechicken.microblock.handler.MicroblockMod`
[latest.log](https://github.com/MultiMC/Launcher/files/7494154/latest.log)
[crash-2021-11-07_19.46.30-fml.txt](https://github.com/MultiMC/Launcher/files/7494162/crash-2021-11-07_19.46.30-fml.txt)

### Suspected cause

I assumed it was a problem with allocating memory, because I only had about 6GB available and 5GB allocated to the game, but it seems weird that it's always cb_microblock that it crashes on and not some other step.
The crash still occurs when there is enough free memory.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefore not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
