### ISSUE TITLE
Cant login using the microsoft login feature

### ISSUE THREAD

**Issue by AzzyDR** [MultiMC/Launcher#4235]
### Operating System

Windows

### Description of bug

i cant get it to authinticate my account but it shows the name of the account and skin it wont let me launch any instance

### Steps to reproduce

try to login in with a migrated account and launch an instance

### Suspected cause

something maybe wrong on microsofts end

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what error are you getting?

**Comment by icebarf** [comment]
I have tested this ~2 hours ago and it works fine. Just letting know

**Comment by rrbrussell** [comment]
I have a similar problem myself. In my case it just says Xbox or Mojang API failure.

**Comment by TheElectroclassics** [comment]
I had this problem after going offline. It says ``XBox user authentication failed.``

**Comment by Zetabite** [comment]
> I have this problem after going offline. It says `XBox user authentication failed.`

Offline doesnt work with MSA yet afaik

**Comment by Zetabite** [comment]
Anyway, we need OP to actually post the error they are getting, else this is nothing to base your experience of

**Comment by rrbrussell** [comment]
Where do you get the more detailed error messages from?

**Comment by Zetabite** [comment]
From the dialog that appears, which they didnt give, so lets wait on OP, if they actually have the same message

**Comment by rrbrussell** [comment]
Version 0.6.13-develop-2827 fixed the issue for me.

**Comment by peterix** [comment]
Cool :)

**Comment by peterix** [comment]
Let's see what @AzzyDR says.

**Comment by AzzyDR** [comment]
It had no error i logged in and it wouldnt let me launch anything it was right after i updated i couldnt get any error log just every thing on the launcher showed up like my internet was off

**Comment by AzzyDR** [comment]
I still cant use the launcher either even after restarting my pc

**Comment by AzzyDR** [comment]
But if its been fixed let me see havent been on in a couple days

**Comment by AzzyDR** [comment]
Ok yes its been fixed

**Comment by AzzyDR** [comment]
Use the launcher to build packs thanks for fixing it so quickly
