### ISSUE TITLE
Can not add microsoft account

### ISSUE THREAD

**Issue by MuffleDuke1** [MultiMC/Launcher#4236]
### Operating System

Windows

### Description of bug

I get a message that i don't own a Microsoft account when i try to add my account to MultiMC. however i do own an account and bought it directly from Minecraft.net a few years ago.

Account is missing a Minecraft Java profile.

While the Microsoft account is valid, it does not own the game.

You might own Bedrock on this account, but that does not give you access to Java currently.

### Steps to reproduce

Account is missing a Minecraft Java profile.

While the Microsoft account is valid, it does not own the game.

You might own Bedrock on this account, but that does not give you access to Java currently.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
then add your mojang account that owns the game to the launcher, or the microsoft account that you migrated to

**Comment by MuffleDuke1** [comment]
Great. You closed it. No response from you guys and no communication. And I
still have the same problem. But it is clear now. I will most
certainly make sure every one in my community knows about the great
assistance I received.....


     Hennie Mare

     Cell: 066 457 7788

     Fax: 0864541846

**Comment by peterix** [comment]
It says you don't have a profile. That generally means you don't own the game.

You could try the dev builds - there's a recent change that walks you through setting up a profile when you do own the game and somehow didn't complete that step.

But generally, what @phit said is correct. Log in with an account that owns the game. Maybe you are using the wrong account to log in?

Also, threats do not work here.

**Comment by peterix** [comment]
And ... no, I don't think I'll call you.
