### ISSUE TITLE
Multiple java instances support

### ISSUE THREAD

**Issue by mkikets99** [MultiMC/Launcher#4237]
### Role

Old versions nowadays

### Suggestion

Support many java instances

### Benefit

Playing minecraft up to 1.16 on Java 1.8 and 1.17+ on Java16

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

To play older minecraft versions i need to switch java version every time i need to play 1.8 or 1.17  
It would be better to have some sort of config for every instance of minecraft to use specific Java version.

**Comment by jotoho** [comment]
You can already set java versions/installs on an instance level.

**Comment by jotoho** [comment]
As far as I can tell, you're asking for something to be added that has existed for years.

**Comment by mkikets99** [comment]
Sorry, my bad... didn't searched deeper...
