### ISSUE TITLE
Add Microsoft greyed out on Linux

### ISSUE THREAD

**Issue by Foxyll-Akora** [MultiMC/Launcher#4239]
### Operating System

Linux

### Description of bug

Can't add Microsoft account to play since the button is greyed out.

![image](https://user-images.githubusercontent.com/84254263/141097757-a25e6843-f2a5-47be-a88d-7d16cfaa5f82.png)

### Steps to reproduce

Cloned multimc5 from AUR
Compiled and installed
Launched and installed ATM3 modpack
Tried to add account, but could not

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
> [x] I have searched the issue tracker and did not find an issue describing my bug

Liar. Duplicate of #4115, #4189, #4159, #4413 and probably a few more.

**Comment by Foxyll-Akora** [comment]
How did you find these? I am new to Github and just typed "microsoft" and "linux" as keywords in the search and did not find those.

**Comment by jotoho** [comment]
`multimc-bin` is the only official/supported AUR package for MultiMC. This is caused by a packaging issue.

**Comment by jotoho** [comment]
> How did you find these? I am new to Github and just typed "microsoft" and "linux" as keywords in the search and did not find those.

you need to delete the `is:open` part so closed issues are shown too

**Comment by Foxyll-Akora** [comment]
> you need to delete the `is:open` part so closed issues are shown too

Oh ok, I'll make sure to do that in the future

> `multimc-bin` is the only official/supported AUR package for MultiMC. This is caused by a packaging issue.

Thank you, I'll clone and build that one then

**Comment by gudenau** [comment]
The AUR package is on version `0.6.12.1438-2` which does not seem to have MS support where as `0.6.13-2` from `multimc5` has MS support but it's grayed out.

**Comment by kb-1000** [comment]
gudenau, that version says absolutely nothing. It's just the version that was up to date when the package was created. The package itself contains a wrapper script (from the debian package on the website) that downloads the latest stable version from the website on first launch, and then you have the updater for any newer versions.

**Comment by gudenau** [comment]
![Untitled](https://user-images.githubusercontent.com/5642329/143636621-38dce737-7efb-4fc0-a6ea-045b0c2e4238.png)

Well I have no idea what is going wrong then, this is the `multimc-bin` package from AUR and it appears to match the `pikaur` version string minus the `-2`.

**Comment by kb-1000** [comment]
There's nothing in the package that would be able to make that happen.
It's possible you just haven't updated since then, though (Which could in turn be caused by broken settings, verify you actually have an update channel selected)

**Comment by gudenau** [comment]
I just ran `pikaur -Sy` before messing with this again.

**Comment by kb-1000** [comment]
I'm not talking about the package manager.
![image](https://user-images.githubusercontent.com/18211838/143643996-bc51c1f7-a9cf-45d2-b124-0a8481b42c3f.png)
![image](https://user-images.githubusercontent.com/18211838/143644243-43f44184-6c6a-49be-9d61-5b98a8256900.png)

**Comment by gudenau** [comment]
It makes no sense that you would re-implement system functionality like that, but indeed the update channel was cleared.
