### ISSUE TITLE
Java for minecraft versions range

### ISSUE THREAD

**Issue by NiDzA-12** [MultiMC/Launcher#4240]
### Role

I play vanilla and modded minecraft and on variety of versions both new and old

### Suggestion

To have an option to use specific java for a range of versions (e.g. from 1.8 to 1.16 i want to use java 8 but for versions 1.17 and above i want to use java 16)

### Benefit

I think it would be save time when having a lot of instances especially in the future where Mojang might use and force the newest java versions

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
see related closed issues https://github.com/MultiMC/Launcher/issues?q=is%3Aissue+java+label%3Asuggestion+is%3Aclosed+

will be solved by https://github.com/MultiMC/Launcher/issues/4013 or something like this in the future
