### ISSUE TITLE
Can't load Roleplay Server's Pack

### ISSUE THREAD

**Issue by Frodnonag** [MultiMC/Launcher#4241]
### Operating System

macOS

### Description of bug

Expectation: I click launch, game is launched.
Reality: I click launch, get a bunch of windows flashing then back to the pack settings screen with a log.
I am uncertain if using a little known pac on a mac makes any difference with my trouble, especially since I seem to be the only one on the server with this issue.

### Steps to reproduce

Download modpack. Click Launch. Get this https://paste.ee/p/DljR7

### Suspected cause

From what can be seen by the other techies I have been talking, voth those related to the server I am trying to join, and from the MultiMC Discord dudes, it's an issue with Curseforge itself.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
update to the latest development version and try again, this should have been fixed with https://github.com/MultiMC/meta/commit/7df0fa86b34b5f79c0c52904c6a8b10f6d9e3f21
if you are still having issues let me know and I'll reopen this issue
