### ISSUE TITLE
Forge download issue

### ISSUE THREAD

**Issue by AlexCatze** [MultiMC/Launcher#4243]
### Operating System

Windows

### Description of bug

MultiMC can't get Forge files, when running under Windows 7. When same installation is launched under Windows 10 all is ok.
`Не удалось обновить сборку по причине: Не удалось обновить игру: Не было возможности получить необходимые библиотеки.
Причина:
Не удалось обработать рабочую задачу 'Библиотеки для сборки 1.7.10 modded':
https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar`

### Steps to reproduce

1. Install MultiMC on Windows 7 PC.
2. Create new instance.
3. Add Forge to it
4. Launch it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
open https://maven.minecraftforge.net/ in internet explorer does that work? if not wait a couple minutes and try again, if it does work restart multimc and try installing forge again

your pc is most likely missing the new ssl certificates used by forge and opening the site with internet explorer should make windows download them

**Comment by AlexCatze** [comment]
Thank you. It fixed this issue.
