### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by allen930309** [MultiMC/Launcher#4244]
### Operating System

Windows

### Description of bug

Keep stucking at "Using Xbox and Mojang service to login"
I did reconnect my internet, and my computer as well. Still not working.my computer as well. 

### Steps to reproduce

* Open MultiMC
* Login just like usual.
* Can't login
* Reconnect internet
* Restart internet
* Restart computer
* Still not working

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryenyuku** [comment]
Same issue in GNU/Linux here. I've also tried re-adding the account but it always got stuck at "Logging in to Xbox and Mojang services" and after a few mins it showed me this error message
![Screenshot from 2021-11-12 15-08-25](https://user-images.githubusercontent.com/59136093/141433145-ae150c0a-4b7e-4112-bb33-0182edbfcbd8.png)

**Comment by phit** [comment]
please provide your MultiMC log from the root launcher folder, it should have more information

**Comment by ryenyuku** [comment]
@phit for some reason, MS Auth is working fine now and I can play it normally. It looks like it's a problem on their side

**Comment by peterix** [comment]
Yeah. This stuff is a bit raw, and we don't show/process the errors well yet.

The services are slow, finicky and errors happen.

**Comment by peterix** [comment]
Still, look in the MultiMC log file. It has more info than the UI currently.

**Comment by phit** [comment]
closing, was probably an intermittent issue, nothing we can do about it without a log anyway and there's other open issues already for similar instabilities
