### ISSUE TITLE
XBox user authentication failed.

### ISSUE THREAD

**Issue by FrankoFM** [MultiMC/Launcher#4246]
### Operating System

Windows

### Description of bug

Can't add Microsoft Account.

Using the **0.6.13-2517** (current stable) and tried it on **0.6.13-develop-2828** (latest dev). Same results with same logs.
Tried using a VPN.
Did not check source how the process workes but looks like OAuth. So me not having my XBox Apps installed should not be the problem I guess.

Here is log:
```
   93.786 D First layer of XBox auth ... commencing.
   97.849 W AuthRequest::onRequestError: Error 1
   97.849 W AuthRequest::onRequestError: Error string:  "Connection refused"
   97.849 W AuthRequest::onRequestError: HTTP status 0 ""
   97.849 W Reply error: QNetworkReply::NetworkError(ConnectionRefusedError)
   97.850 C Task "MSAInteractive(0x75987a0)" failed:  "XBox user authentication failed."
```

### Steps to reproduce

- Try to add account
- Follow link
- Type in the code
- Login to Microsoft account
- Grand access to MutliMC
- ERROR

### Suspected cause

Might be a problem on the side of Microsoft or they may try to block MultiMC. I dont know.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
yeah network error on your end, not much for us to do about that

**Comment by FrankoFM** [comment]
> yeah network error on your end, not much for us to do about that

Any suggestions what it could be?
Tried istalling the xbox app again. But did not work. Login via normal Minecraft Launcher is working as intended.

**Comment by phit** [comment]
can you reach https://user.auth.xboxlive.com/?

**Comment by FrankoFM** [comment]
> can you reach https://user.auth.xboxlive.com/?

Actually not...

**Comment by FrankoFM** [comment]
Okey thank you. Something put it in my hosts... Problem resolved.

**Comment by FrankoFM** [comment]
If anyone finds this and needs a solution:
- Go to `C:\Windows\System32\drivers\etc`
- Open `hosts` with an editor that has admin privileges (vs code in my case)
- Remove every line saying `127.0.0.1 xboxlive.com`,  `127.0.0.1 presence-heartbeat.xboxlive.com` and stuff like that. Remove everything that contains xbox.
- Restart MultiMC

This fixed it for me. <3

**Comment by ramyILG** [comment]
I have the same problem but I don't find the hosts file

**Comment by ramyILG** [comment]
Can someone help me?

**Comment by Matocolotoe** [comment]
> If anyone finds this and needs a solution:
> 
>     * Go to `C:\Windows\System32\drivers\etc`
> 
>     * Open `hosts` with an editor that has admin privileges (vs code in my case)
> 
>     * Remove every line saying `127.0.0.1 xboxlive.com`,  `127.0.0.1 presence-heartbeat.xboxlive.com` and stuff like that. Remove everything that contains xbox.
> 
>     * Restart MultiMC
> 
> 
> This fixed it for me. <3

Doesn't fix anything. Had to reconnect at least 4 times for it to work.

**Comment by kerft** [comment]
> If anyone finds this and needs a solution:
> 
>     * Go to `C:\Windows\System32\drivers\etc`
> 
>     * Open `hosts` with an editor that has admin privileges (vs code in my case)
> 
>     * Remove every line saying `127.0.0.1 xboxlive.com`,  `127.0.0.1 presence-heartbeat.xboxlive.com` and stuff like that. Remove everything that contains xbox.
> 
>     * Restart MultiMC
> 
> 
> This fixed it for me. <3

This actually worked, thanks 👍🏽
