### ISSUE TITLE
中国区下载很慢，可以考虑加mcbbs等源

### ISSUE THREAD

**Issue by kill0es** [MultiMC/Launcher#4247]
### Description of bug

中国区下载很慢，可以考虑加mcbbs等源

### Steps to reproduce

中国区下载很慢，可以考虑加mcbbs等源

### Suspected cause

中国区下载很慢，可以考虑加mcbbs等源

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
This issuetracker is english-only.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/2246
