### ISSUE TITLE
 instance error when launching

### ISSUE THREAD

**Issue by Toaster2000** [MultiMC/Launcher#4248]
### Description of bug

I downloaded enigmatica 2 expert and used the "import from zip" feature to add it as an instance. I launched it and I received an error log. Here is the link: https://paste.ee/p/4Ua9b
I tried launching another instance, and it worked fine.

### Steps to reproduce

I downloaded Enigmatica 2 Expert from curseforge's website, then used the "import from .zip" button. Then I had the issue.

### Suspected cause

I do not know the cause but it seems to only be an issue with this instance in particular.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Toaster2000** [comment]
I just realized im using Java 16 for this. I will try another version.

**Comment by phit** [comment]
yep use java 8 for anything older than 1.17

**Comment by Toaster2000** [comment]
I downloaded Java 8 from the java website. Do you know where the file for it is stored? The installer didnt show where it would be stored and I only know the location of Java 16

**Comment by Toaster2000** [comment]
nvm I think i found it
