### ISSUE TITLE
MultiMC stuck at getting player skin

### ISSUE THREAD

**Issue by Anthonity** [MultiMC/Launcher#4250]
When I try to login or play Minecraft with MultiMC (ver. 0.6.13-stable), the auth process goes good until it starts getting the skin and it just gets stuck. It doesn't freeze, but it just gets stuck. When logging in, it just gets stuck at getting skin and I can close the login window and return to account manager. If I edit the MMC (short for MultiMC) files to make me logged in my account or I log in with different device and move the folder with MMC to my laptop, it becomes unresponsive at the auth process when trying to open the game. I don't wanna use the official launcher (the exe ver. and the W10 Store app) because it takes over 15 minutes of my time (on avg. even more) to show something other than stupid dark gray box (if it even goes out of that state ever). The skin issue didn't happen 0.6.12-stable, but once I updated to 0.6.13, the issue appeared. I tried the dev version, but nothing changed. When I updated, I moved the old MMC folder somewhere else, extracted the new MMC into the place of the old ver, and moved my worlds into the new MMC. My laptop is ASUS Vivobook Max X451NA with 1TB HDD, Intel Pentium N4200 and HD 505. Skin issue doesn't happen on other computers though.

**Comment by Anthonity** [comment]
I updated my drivers yesterday and nothing changed. Restarting doesn't work either.

**Comment by Xag8031** [comment]
Have you tried running the beta version of the launcher?

**Comment by phit** [comment]
please try the development version and if it still doesn't work upload your MultiMC log

**Comment by phit** [comment]
closed due to no reply, if you provide the log I'll be happy to help and reopen this
