### ISSUE TITLE
RLCraft MultiMC

### ISSUE THREAD

**Issue by FireFighter2020** [MultiMC/Launcher#4252]
### Role

I played modded minecraft this time

### Suggestion

I want that MultiMC starts Minecraft with the modpack RLCraft

### Benefit

I can only start the needed version with MultiMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
