### ISSUE TITLE
Forge Not Working

### ISSUE THREAD

**Issue by SolidTech69** [MultiMC/Launcher#4253]
### Description of bug

When I try to use forge I get an error message in the console. It did it on my last computer and when I installed optifine it did it on this one too.

### Steps to reproduce

Installing optifine?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
