### ISSUE TITLE
Cant chat

### ISSUE THREAD

**Issue by jackster1** [MultiMC/Launcher#4259]
### Operating System

Windows

### Description of bug

Anytime I try to chat in any version of Minecraft that was loaded via MultiMC it wont let me chat. It doesn't show the chat when I press T. I tried delting the options.txt file, changing the chat keybind and its still not working.

### Steps to reproduce

Load into an instance of MultiMC

Load into a world

Try to open chat

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
MultiMC's only job is managing instances and running them. The behaviour of those instances after having been started is not controlled by the launcher. This issue tracker is for bugs or problems with the launcher in particular. Please go somewhere else like appropriate public forums or the MultiMC discord for general minecraft support. (A link to the MultiMC discord can be found on multimc.org)
