### ISSUE TITLE
Bug download>minecraftforge.net

### ISSUE THREAD

**Issue by Natalia-Oreiro** [MultiMC/Launcher#4264]
### Operating System

Windows

### Description of bug

Get error:
https://paste.ee/p/eSljI
https://paste.ee/p/KzoJO

### Steps to reproduce

run any modspack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kb-1000** [comment]
open https://files.minecraftforge.net in IE/Edge and try again

**Comment by Natalia-Oreiro** [comment]
Still the same problem
