### ISSUE TITLE
resource pack folder

### ISSUE THREAD

**Issue by SuperFurias** [MultiMC/Launcher#4269]
### Operating System

Windows

### Description of bug

The "open resource pack folder" should open the folder where the resource packs are, but it show an error

### Steps to reproduce

Press the "open resource pack folder" button
![image](https://user-images.githubusercontent.com/34806112/142767367-74657a97-2c0a-4469-b3ad-2c9dcf612f49.png)

### Suspected cause

IDK, the fact that you can install multimc everywhere?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
this is a game bug, nothing we can do about it
