### ISSUE TITLE
potential issue... .minecraft folder is preferred over minecraft folder, even if empty

### ISSUE THREAD

**Issue by theofficialgman** [MultiMC/Launcher#4271]
### Operating System

Linux

### Description of bug

modpacks and multimc should setup the instance in the `.minecraft` folder on linux. this is no longer the case and everything gets downloaded to the `minecraft` folder.

Mods get downloaded to the wrong folder and then don't get used with launching the instance

### Steps to reproduce

1. run linux mutlimc from the dev channel (it works fine in windows)
2. download a modpack (lets use Fabulously Optimized as an example but it works on all modpacks)
3. Launch instance and only fabric is loaded, without any mods

### Suspected cause

~~not sure.. but the issues stems from commit:
https://github.com/MultiMC/Launcher/commit/0c861db7a201c813530e703257f286257f39872f~~

minecraft folder is still: `Minecraft folder is:
/home/gman/MultiMC/install/instances/Fabulously Optimized/.minecraft`
params are still : `/home/gman/MultiMC/install/instances/Fabulously Optimized/.minecraft` even with that folder does not exist

the `.minecraft` folder ends up getting created on launch. so now both `.minecraft` and `minecraft` folders exist. but all the mods are in the `minecraft` folder. the mods also disappear from the GUI after the .minecraft folder gets created on first launch

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
rolled back to the commit before the refactor and modpacks from curseforge downloaded to the `minecraft` folder and they get correctly launched from that folder

**Comment by theofficialgman** [comment]
ok so here is actually what is happening, I was mistaken about the commit but it could be considered to be a bug:
1. install instance with modpack when then creates a `minecraft` folder
2. have a prelaunch command (any command) create a .minecraft folder (yes I had one that did that, an auto mod updater of my making)
3. `.minecraft` gets attempted to be loaded instead of `minecraft`

**Comment by peterix** [comment]
This is not a MultiMC issue.

You should fix your updater logic to not break the instance.

**Comment by theofficialgman** [comment]
alright, cool. I debated closing the issue and noting working as intended myself but figured I should just leave it incase anyone else comes across having made the similar mistake as me.
Thanks

**Comment by peterix** [comment]
The `.minecraft` vs `minecraft` thing is there because we've switched between them several times in the past, and MultiMC needs to work with both.
Also, some very old mods break if they don't find a `.minecraft` folder while scanning upwards.
