### ISSUE TITLE
[BUG] Can't play Minecraft with account Microsoft if not have Internet/Wi-Fi

### ISSUE THREAD

**Issue by kyrtion** [MultiMC/Launcher#4272]
### Operating System

Windows 10 x64, latest version

### Description of bug

If you not have Internet, when you can't play Minecraft with account Microsoft.

### Steps to reproduce

(- Close MultiMC)
- Disable Internet/Wi-Fi;
- Open MultiMC;
- Set any installed account Microsoft for play;
- Play (ONLINE or OFFLINE) any instances with account Microsoft;
- Sended dialog reason error authification Microsoft: **Microsoft account has expired and needs to be logged into manually again.**

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kyrtion** [comment]
Priority for offline account: Major
@peterix

**Comment by phit** [comment]
see https://github.com/MultiMC/Launcher/issues/4071, also directly pinging developers for your issue is rude, please refrain from doing so unless there was prior communication

**Comment by CaldwellYSR** [comment]
> see #4071, also directly pinging developers for your issue is rude, please refrain from doing so unless there was prior communication

#4071 is a different issue. This issue is related to MSA accounts expiring immediately when trying to play offline. Offline play worked with Mojang accounts but now it's broken and you have to delete and readd the MSA account online in order to play again.

**Comment by phit** [comment]
yes, read the linked issue that behavior is discussed in detail, the underlying issue is the invalidation of login data when there's even a hint of an error, offline falls under that as all requests obviously fail when you are offline
