### ISSUE TITLE
1.8.9 Forge crashes on startup with no mods installed

### ISSUE THREAD

**Issue by wilcleve** [MultiMC/Launcher#4274]
Haven't done anything since installing multiMC. It launches fine without installing forge on the profile. Error looks like it can't find some files but I'm not sure what would be causing that.
MultiMC version: 0.6.13-2517

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [143.204.28.72]

session.minecraft.net resolves to:
    [34.225.33.249, 54.157.134.223, 174.129.108.178]

textures.minecraft.net resolves to:
    [65.8.236.19, 65.8.236.66, 65.8.236.121, 65.8.236.28]

api.mojang.com resolves to:
    [65.8.235.88]

Minecraft folder is:
C:/Users/wilcl/Documents/mmc-stable-win32/MultiMC/instances/Skyblock 1.8.9/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_311/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_311, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:

Job 'Libraries for instance Skyblock 1.8.9' failed to process:
https://maven.minecraftforge.net/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
https://maven.minecraftforge.net/com/typesafe/config/1.2.1/config-1.2.1.jar
https://maven.minecraftforge.net/jline/jline/2.13/jline-2.13.jar
https://maven.minecraftforge.net/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar
https://maven.minecraftforge.net/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
https://maven.minecraftforge.net/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
https://maven.minecraftforge.net/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
https://maven.minecraftforge.net/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar

**Comment by phit** [comment]
open https://maven.minecraftforge.net in internet explorer or edge, does the page work?

**Comment by wilcleve** [comment]
Ah, thank you. Not sure why I didn't follow the link it gave me.
