### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by jaireliecer83222** [MultiMC/Launcher#4275]
### Description of bug

oh no. this in my microsoft in login failed
so 1 mire missing crate guest.

### Steps to reproduce

update version.

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
I don't understand what the issue is.

**Comment by qmfkaovi** [comment]
I have this problem too in version 0.6.13(stable release). When I wanted to start an instance, the launcher told me my Microsoft account is expire so I need to delete it and readd it. I did so. The launcher told me XBox and/or Mojang verification steps were unsuccessful while I tried to add my account and I failed to add it. I restarted the launcher and tried many times but still have the problem. I tried the official launcher and seemed no problem.
[https://paste.ee/p/OEicv](url)
(I tried many times so I can't find the log of that the launcher told me my Microsoft account is expire.)
May it be my problem?
Thank you.

**Comment by qmfkaovi** [comment]
> I have similar or maybe same problem in version 0.6.13(stable release). When I wanted to start an instance, the launcher told me my Microsoft account is expire so I need to delete it and readd it. I did so. The launcher told me XBox and/or Mojang verification steps were unsuccessful while I tried to add my account and I failed to add it. I restarted the launcher and tried many times but still have the problem. I tried the official launcher and seemed no problem. https://paste.ee/p/OEicv (I tried many times so I can't find the log of that the launcher told me my Microsoft account is expire.) Just add a Microsoft account to reproduce the problem. May it be my problem? Thank you.

I just added my Microsoft account successfully and seems no problem now.

**Comment by phit** [comment]
please provide proper steps and explanations of the issue and I'll be happy to reopen this
