### ISSUE TITLE
MultiMC crashes when I try to add MC Eternal

### ISSUE THREAD

**Issue by bluetornado0614** [MultiMC/Launcher#4276]
### Operating System

Windows

### Description of bug

I add a knew instance and import the file form cursed forge and as soon as I add it, it stops responding.

### Steps to reproduce

installed latest version of MC Eternal
add instance
import Minecraft+Eternal+Client+1.5.zip
MultiMC stops responding

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
how long did you wait, the install process may freeze up the client https://github.com/MultiMC/Launcher/issues/2610
