### ISSUE TITLE
New UI redesign

### ISSUE THREAD

**Issue by louanfontenele** [MultiMC/Launcher#4277]
### Role

I play modded minecraft.

### Suggestion

Create a new layout from scratch

### Benefit

Improve for users the way they navigate the program

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I've noticed in the program, that it is excellent, but it only lacks in one subject, the UI/UX, it would be nice to have a new look, totally remodeled from scratch, with a new UI/UI, users will be able to have the program's complexity in a way more beautiful, drawing even more attention to the use of the program. I think it would be great if there was something like that

**Comment by peterix** [comment]
If you have some more concrete suggestion than this, sure. Let's talk about this on Discord.

But otherwise, no. I think it's good as it is.

**Comment by louanfontenele** [comment]
Just an example @peterix 

![File Menu Example](https://user-images.githubusercontent.com/2886066/143616730-014fa459-b195-4467-b25e-a797dcf71d17.png)

**Comment by Zetabite** [comment]
wouldnt set it as standard theme, but if someone gets onto better theming support, i can see something similar working out

**Comment by Zetabite** [comment]
anyway, peterix is right, its easier to discuss that on discord
