### ISSUE TITLE
Settings menu says "Launcher" rather than "MultiMC" in official builds

### ISSUE THREAD

**Issue by ImperatorStorm** [MultiMC/Launcher#4278]
### Operating System

Linux

### Description of bug

In prior builds, the first entry in the Settings menu said "MultiMC", as shown in this screenshot from the MultiMC Discord server.

![Image](https://cdn.discordapp.com/attachments/134843027553255425/855880510031003728/unknown.png)

However, in current builds, at least on Linux, it instead shows "Launcher".

![Image](https://i.imgur.com/5go7MQZ.png)

### Steps to reproduce

1. Download and open the linux version of MultiMC
2. Open the Settings Menu
3. Click to the first entry

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
can confirm thats the case, might be intended tho?

**Comment by phit** [comment]
this appears to be intentional
