### ISSUE TITLE
Update GLFW to newer version to avoid Minecraft bug of ignoring key presses

### ISSUE THREAD

**Issue by thatLeaflet** [MultiMC/Launcher#4279]
### Role

I play Vanilla Minecraft

### Suggestion

I want MultiMC to include a newer version of GLFW that has the bug patched

### Benefit

This would fix the key detection bug for MultiMC users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Minecraft bug report of the issue: https://bugs.mojang.com/browse/MC-122421. The TLDR is that GLFW has an issue that causes for key presses to not be registered if the user starts pressing multiple keys at once. This issue has been fixed in GLFW (in this PR: https://github.com/glfw/glfw/commit/9a3664b4a992a5a9b669179098542b0f882dece7), but neither Minecraft nor MultiMC ship the version of GLFW that has this issue fixed.

On my Arch Linux system, I installed glfw-x11 3.3.5 and told MultiMC to use my system installation of GLFW. The bug did not occur with this version.

**Comment by peterix** [comment]
Well, that's why the checkbox is there.

There's nothing to do, you can use system glfw.

**Comment by peterix** [comment]
MultiMC does not ship GLFW. Mojang does. And I'm not going to mess with what Mojang ships.
