### ISSUE TITLE
Microsoft Account refresh failed

### ISSUE THREAD

**Issue by JinguLan** [MultiMC/Launcher#4280]
### Description of bug

I added my Microsoft account just now, then i tried to launch my game but error happened.
Microsoft Account refresh failed: Microsoft account has expired and needs to be logged into manually again.

### Steps to reproduce

I remove my Microsoft account and then add again. However, it still says that Microsoft account has expired. 
WHY?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/4071
