### ISSUE TITLE
Bug with a modpack

### ISSUE THREAD

**Issue by ZuRuLLi** [MultiMC/Launcher#4282]
### Operating System

macOS

### Description of bug

I have installed the Last days of Humans modpack, and when I start it it does not work, I get an unexpected error

### Steps to reproduce

![Captura de pantalla 2021-11-27 a las 17 28 31](https://user-images.githubusercontent.com/95140088/143689318-999a4faa-dc1b-4e83-a16a-e5768854ebc4.png)
![Captura de pantalla 2021-11-27 a las 17 29 03](https://user-images.githubusercontent.com/95140088/143689324-b8aec706-76d2-425d-bd8a-29a4e11dc16a.png)
![Captura de pantalla 2021-11-27 a las 17 28 50](https://user-images.githubusercontent.com/95140088/143689356-6f43f7b0-4d44-4ca2-a497-0afeba76ffc8.png)

### Suspected cause

 I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
This isn't a bug with MultiMC, but rather game support.

This is a bug tracker for MultiMC, and therefore not the appropriate place for game support. There are many communities which may be able to provide game support for you - the MultiMC Discord being one, but also the Minecraft subreddit, Minecraft Forums, the #minecrafthelp IRC channel, and potentially many more.
