### ISSUE TITLE
Will there be Forge support ?

### ISSUE THREAD

**Issue by RemVan** [MultiMC/Launcher#4284]
### Role

I'm playing with mods

### Suggestion

Add Forgee Support

### Benefit

There are mods on Forge that are not on Fabric

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Will Forge be added to the new versions ? on the official Forge website, there are already new versions of Minecraft

**Comment by phit** [comment]
Probably at some point, see https://github.com/MultiMC/Launcher/issues/3936
