### ISSUE TITLE
Do for  shaders & resource packs and their assocated settings what the technicpack launcher does for mod packs.

### ISSUE THREAD

**Issue by strunberg** [MultiMC/Launcher#4286]
### Role

I play modded MC

### Suggestion

I want MultiMC to do for shaders & resource packs and their assocated settings what the technicpack launcher does for mod packs.

### Benefit

It seems like a novel idea that nobody has done before.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It would be neat if you could go into a menu and choose to download a pack that has a resource pack & pre-configured shader settings.

**Comment by jamierocks** [comment]
Please elaborate, I have no idea what this suggestion is for.

**Comment by strunberg** [comment]
https://www.technicpack.net/modpacks MultiMC is able to use technic mod packs that are created by the MC community.

Nobody offers a solution that lets you download a package of resourcepacks, shaders, and tweaked settings such as fog levels. It would be nice if MultiMC offered that solution.

**Comment by phit** [comment]
very much out of scope for MultiMC currently, nothing stops you from making a modpack with resourcepacks and shaders and whatever else you want to change on existing platforms like Technic or CurseForge
