### ISSUE TITLE
Crash. I don't know what causes it. Deleting libraires didn't help. ( MultiMC 5 hacked by Hackphoenix )

### ISSUE THREAD

**Issue by Kasia1403** [MultiMC/Launcher#4288]
### Operating System

Windows

### Description of bug

Minecraft should load and show main menu.
 
Crash log

[crash-2021-11-29_10.41.34-client.txt](https://github.com/MultiMC/Launcher/files/7617537/crash-2021-11-29_10.41.34-client.txt)

other logs

[debug.log](https://github.com/MultiMC/Launcher/files/7617548/debug.log)
[latest.log](https://github.com/MultiMC/Launcher/files/7617550/latest.log)

### Steps to reproduce

Sorry, but I don't understand this step. :(

### Suspected cause

OpenAL

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kasia1403** [comment]
Why this issue is closed ?

**Comment by KennethEhmsen** [comment]
Have you done this!

Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (!foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer

**Comment by phit** [comment]
because you aren't using MultiMC and your issue is irrelevant to this launcher
