### ISSUE TITLE
Filtering out "dangerous java crap" prevents it from running for me

### ISSUE THREAD

**Issue by L3P3** [MultiMC/Launcher#4291]
### Operating System

Linux

### Description of bug

When I try to run Minecraft using MultiMC on my old netbook, having only 2GB of memory, java does not start by default because it tries to allocate 1GB of memory. To fix that, I added the global variable:

export _JAVA_OPTIONS=-XX:CompressedClassSpaceSize=512M

But surprise, it works everywhere but not with MultiMC since someone was smart there.

### Steps to reproduce

Use a amd64 device with low memory in case you don't want to toss it away for nothing.

### Suspected cause

Simple reason: In JavaUtils.cpp you are filtering out my system-wide environment variable, called "dangerous crap" there, thankyou.

Could you please not tell me how I want java to run on my machine, thankyou. Or at least give me a way to add that option to every java call. By every I also mean the java version checker because java also does not start when just calling it with --version due to memory allocation error.

Please forgive me for my aggression. It is not that serious. :-)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
this is just a workaround, but have you tried adding swap space, zram, or similar options so that allocating 1GB of memory does not fail?
I don't have any issues with a system with only 2GB of ram and 1GB zram (compressed ram space)

**Comment by L3P3** [comment]
Regarding your workaround idea: I tried all of that. Have lots of swap space. I can use tens of applications at the same time on that device without issues. But Java fails to allocate 1GB even though system monitor shows that there is 1.8GB free. It is a Java issue that is not new at all.
There are good reasons for the existence of JAVA_OPTIONS env variable, please recognise it. :-)

**Comment by peterix** [comment]
This will not be addressed in MultiMC. You can add the options to instances individually.

**Comment by peterix** [comment]
The problem with this sort of thing is when random system things set these env vars and it breaks Minecraft. This is a much more common thing than it being used for a legitimate purpose.

**Comment by peterix** [comment]
The very common case was a broken driver/utility for gaming mice that would set these sorts of vars globally, on Windows.

So, MultiMC filters away the environment. This is a feature, and is fully intended.

**Comment by L3P3** [comment]
> This will not be addressed in MultiMC. You can add the options to instances individually, or use shared Java arg settings.

Nope, because your java version check does not use my custom java args. Starting fails with message that java does not work, in log I can see java was called without additional java args.
