### ISSUE TITLE
1.18 Vanilla- Cannot recognize Java 17

### ISSUE THREAD

**Issue by WhiteOutMk1** [MultiMC/Launcher#4296]
### Operating System

Windows

### Description of bug

I have Java 17 on my personal computer and uninstalled Java 16, but when original Minecraft starter started the game normally MultiMC can't. Every time I tried to start it the message "Minecraft 21w19a and above require the use of Java 16
" comes out and MultiMC prevents the start of the game.

### Steps to reproduce

Create a vanilla instance and run it, then the message "Minecraft 21w19a and above require the use of Java 16
" shows

### Suspected cause

MultiMC might have failed to recognize Java 17 for consumers
[Log.txt](https://github.com/MultiMC/Launcher/files/7638718/Log.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RDKRACZ** [comment]
You have Java 8 installed - C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Uninstall it or switch to Java 17 in MultiMC settings.
