### ISSUE TITLE
1.18 does not boot

### ISSUE THREAD

**Issue by kdoub05** [MultiMC/Launcher#4297]
### Operating System

Windows, macOS, Linux

### Description of bug

I tried to boot 1.18 and it did not boot. I expected it to work

### Steps to reproduce

Make a 1.18 instance.
Then try to boot it/play it.
It doesn't work

### Suspected cause

I dont know, I have selected Java 16 in the instance-pacific settings.

MultiMC version 06.1.13-2517

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kdoub05** [comment]
Logs:
MultiMC version: 0.6.13-2517


Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.33.162.72]

session.minecraft.net resolves to:
    [52.70.238.65, 3.211.245.5, 23.23.220.104]

textures.minecraft.net resolves to:
    [143.204.0.95, 143.204.0.16, 143.204.0.74, 143.204.0.5]

api.mojang.com resolves to:
    [13.33.163.190]


Minecraft folder is:
C:/MultiMC/instances/1.18/.minecraft


Java path is:
C:/Program Files/Eclipse Foundation/jdk-16.0.2.7-hotspot/bin/javaw.exe


Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Eclipse Foundation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/MultiMC/instances/1.18/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  C:/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  C:/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  C:/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.18/minecraft-1.18-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/MultiMC/instances/1.18/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms409m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 22280


Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.
Clipboard copy at: 02 Dec 2021 05:57:35 -0600

**Comment by RDKRACZ** [comment]
You are using Java 16 and Minecraft 1.18 requires Java 17.

**Comment by kdoub05** [comment]
Ok I will download OpenJDK 17 (because java is bad)

**Comment by kdoub05** [comment]
Thanks a lot. It works now.
