### ISSUE TITLE
Add 'Install Optifine' button

### ISSUE THREAD

**Issue by DavidoTek** [MultiMC/Launcher#4298]
### Role

I play Vanilla Minecraft with Shaders/improved FPS.

### Suggestion

Add a button to 'Edit Instance - Version' to install Optifine

### Benefit

Many use Optifine to improve their FPS or to use a shader. A standalone option for installing Optifine might be useful to many.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Not sure if Optifine's license would allow for automatically downloading it via MultiMC.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/3342 and many more

**Comment by luckydonald** [comment]
But that one is closed.

**Comment by phit** [comment]
yes, read them
