### ISSUE TITLE
My MultiMc is not working properly

### ISSUE THREAD

**Issue by RexMicky** [MultiMC/Launcher#4301]
### Description of bug

Whenever i try to launch forge minecraft this happens https://paste.ee/p/eNoBx . If someone knows whats happening please help.

### Steps to reproduce

MultiMC version: 0.6.13-2517

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [52.85.117.74]

session.minecraft.net resolves to:
    [52.70.238.65, 3.211.245.5, 23.23.220.104]

textures.minecraft.net resolves to:
    [52.85.3.117, 52.85.3.2, 52.85.3.63, 52.85.3.81]

api.mojang.com resolves to:
    [13.33.178.184]

Minecraft folder is:
C:/Users/micky/Downloads/MultiMC/instances/RexMicky/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_51/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_51, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/patchy/1.2.3/patchy-1.2.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/micky/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/micky/Downloads/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/micky/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.3/ForgeWrapper-1.5.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/forge/1.16.5-36.2.0/forge-1.16.5-36.2.0-launcher.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar
  C:/Users/micky/Downloads/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/tiny-remapper/0.6.0/tiny-remapper-0.6.0.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/access-widener/2.0.1/access-widener-2.0.1.jar
  C:/Users/micky/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader/0.12.8/fabric-loader-0.12.8.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] BetterAdvancements-1.16.5-0.1.0.108
  [✔️] betterendforge-1.16.5-1.6.3
  [✔️] BiomesOPlenty-1.16.5-13.1.0.484-universal
  [✔️] cavebiomeapi-1.16.5-1.4.2
  [✔️] chiselsandbits-1.0.43
  [✔️] DungeonCrawl-1.16.5-2.3.4
  [✔️] FastLeafDecay-v25
  [✔️] goblintraders-1.6.0-1.16.3
  [✔️] iceandfire-2.1.9-1.16.5
  [✔️] infernal-expansion-1.16.5-2.4.0
  [✔️] jei-1.16.5-7.7.1.137
  [✔️] mcw-bridges-2.0.0-mc1.16.5
  [✔️] StorageDrawers-1.16.3-8.3.0
  [✔️] supplementaries-1.16.5-0.17.12b
  [✔️] thermal_foundation-1.16.5-1.3.2
  [✔️] twilightforest-1.16.5-4.0.546-universal
  [✔️] Waystones_1.16.5-7.6.3
  [✔️] Xaeros_Minimap_21.22.2_Forge_1.16.5

Params:
  --username  --version MultiMC5 --gameDir C:/Users/micky/Downloads/MultiMC/instances/RexMicky/.minecraft --assetsDir C:/Users/micky/Downloads/MultiMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.0 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
Couldn't extract native jar 'C:/Users/micky/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar' to destination 'C:/Users/micky/Downloads/MultiMC/instances/RexMicky/natives'
MultiMC: Log upload triggered at: 03 Dec 2021 10:36:08 +0530

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
something is blocking the launcher from creating those files, antivirus or similar or simply bad folder permissions
since you've been already in Discord for this, closing this as there's no bug here
