### ISSUE TITLE
Read logs better in dark mode. 

### ISSUE THREAD

**Issue by PCD1CFbjDC** [MultiMC/Launcher#4303]
### Role

Read logs better in dark mode. 

### Suggestion

The color of the words should switched to white in dark mode

### Benefit

Read logs better in dark mode. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![截屏2021-12-03 下午10.29.21.png](https://i.loli.net/2021/12/03/IepJVKHMaSbZuOT.png)

**Comment by phit** [comment]
what theme are you using, what version, what OS, because the text color definitely doesn't look like that for most people

**Comment by PCD1CFbjDC** [comment]
> 

macOS
Colors default 
0.6.13 Development

**Comment by PCD1CFbjDC** [comment]
>what theme are you using, what version, what OS, because the text color definitely doesn't look like that for most people

macOS
Colors default
0.6.13 Development

**Comment by PCD1CFbjDC** [comment]
If you switch the Dark Mode while MultiMC is running, the words will not turn white. 🤔

**Comment by phit** [comment]
so it's fine after restarting the launcher?

**Comment by PCD1CFbjDC** [comment]
> so it's fine after restarting the launcher?

Yes...

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/1790
external issue with Qt which we can't fix

**Comment by PCD1CFbjDC** [comment]
> Duplicate of #1790 external issue with Qt which we can't fix

Sorry to bother you...

**Comment by phit** [comment]
Thanks for reporting it! You couldn't have know that it's out of our control.
