### ISSUE TITLE
Exit code 1 when starting Minecraft 1.18

### ISSUE THREAD

**Issue by Bauds1** [MultiMC/Launcher#4304]
### Operating System

Windows

### Description of bug

I have made a new instance for Minecraft 1.18
Windows 10
(account hasn't been migrated, if that matters)

MultiMC version: 0.6.13-2517

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.227.151.74]

session.minecraft.net resolves to:
    [23.23.220.104, 52.70.238.65, 3.211.245.5]

textures.minecraft.net resolves to:
    [13.227.172.98, 13.227.172.79, 13.227.172.30, 13.227.172.23]

api.mojang.com resolves to:
    [143.204.197.239]

Minecraft folder is:
D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/instances/1.18/.minecraft

Java path is:
C:/Program Files/Eclipse Foundation/jdk-16.0.2.7-hotspot/bin/javaw.exe

Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Eclipse Foundation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/instances/1.18/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.18/minecraft-1.18-client.jar

Native libraries:
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/instances/1.18/.minecraft --assetsDir D:/[Irl name]'s Files/Libraries/Documents/mmc-stable-win32/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms204m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 36364

Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with code 1.

### Steps to reproduce

- Make a new instance
- Use java 1.16.2

### Suspected cause

No idea.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use java 17
