### ISSUE TITLE
No instructions on the wiki on how to install Optifine on newer versions

### ISSUE THREAD

**Issue by vgl266** [MultiMC/Launcher#4307]
### Role

People need to have instructions

### Suggestion

Update instructions for newer Minecraft versions.

### Benefit

So people would not get lost on how to install Optifine in MultiMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Instructions for 1.13 for the tweaker way are outdated, since you cannot longer download launchwrapper from Minecraft repository, and the one they do have is crashing on load in newer versions. Instead you need to extract a file named `launchwrapper-of-<version>.jar` from Optifine jar and place it into the `libraries`. Then, you need to modify json file like this:
```
{
    "formatVersion": 1,
    "name": "OptiFine",
    "+libraries": [
        {
            "name": "optifine:launchwrapper-of:2.3",
            "MMC-hint": "local",
            "MMC-filename": "launchwrapper-of-2.3.jar"
        },
        {
            "name": "optifine:OptiFine:1.18_HD_U_H3",
            "MMC-hint": "local",
            "MMC-filename": "OptiFine_1.18_HD_U_H3.jar"
        }
    ],
    "+tweakers": [ "optifine.OptiFineTweaker" ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "requires": [
        {
            "uid": "net.minecraft",
            "equals": "1.18"
        }
    ],
    "uid": "optifine.OptiFine",
    "version": "HD Ultra H3"
}
```

**Comment by phit** [comment]
one can open a pull request on https://github.com/MultiMC/wiki to add it

**Comment by phit** [comment]
wiki was updated
