### ISSUE TITLE
Add environment variables

### ISSUE THREAD

**Issue by XakepSDK** [MultiMC/Launcher#4308]
I'd like to add `mesa_glthread=true` so i could get better performance on mesa drivers.
I haven't found straightforward way to add this env. variable.

**Comment by phit** [comment]
you can use the custom commands https://github.com/MultiMC/Launcher/wiki/Instance-settings#custom-commands to set env vars, e.g. as a wrapper

`sh -c "export mesa_glthread=true; exec $INST_JAVA \"$@\""`
