### ISSUE TITLE
Add Microsoft is greyed out

### ISSUE THREAD

**Issue by iio7** [MultiMC/Launcher#4309]
### Operating System

Linux

### Description of bug

The button "Add Microsoft" is greyed out and doesn't work.

### Steps to reproduce

![1](https://user-images.githubusercontent.com/12476695/144767047-54046ee2-6cc3-4cbb-9d32-10ce704666ce.png)
![2](https://user-images.githubusercontent.com/12476695/144767051-4fdaf632-e773-4526-b4d8-7d1bae627435.png)
![3](https://user-images.githubusercontent.com/12476695/144767055-d5ce1403-adc5-436d-bbe4-d21ce3298a17.png)

### Suspected cause

I am on Arch Linux and has build this using the AUR.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RDKRACZ** [comment]
> I have searched the issue tracker and did not find an issue describing my bug.

Sure. #4239 #4115, #4189, #4159, #4113, and maybe a few more.

**Comment by iio7** [comment]
> > I have searched the issue tracker and did not find an issue describing my bug.
> 
> For sure. #4239 #4115, #4189, #4159, #4113, and maybe a few more.
> 
> At least the suspected cause is true.

I am so sorry, I somehow overlooked those issues.

Thanks for taking the time to respond.
