### ISSUE TITLE
Selecting "Launch Offline" no longer promts for a username

### ISSUE THREAD

**Issue by TechnicallyCoded** [MultiMC/Launcher#4311]
### Operating System

Windows

### Description of bug

**_NOTE: I am using the development updates branch._**

Before the recent re-write of how accounts were handled I was able to enter a custom name when launching in offline mode. This is particularly useful for development purposes. As of recently, when selecting "launch offline", it tries using your "online"/premium accounts as the username.

EDIT: It tries authenticating with the mojang servers too. It's clearly not launching offline. I manually edited the account,json file to add a bogus account and it would refuse to launch using that account due to it not being a valid account with a valid token.

### Steps to reproduce

On any instance, click "launch offline". You won't be prompted to enter a username.

### Suspected cause

Recent re-write of how the login system works (from the recent changelogs)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
looks like the chosing username only shows up when you are actually offline, when I set an invalid proxy in the launcher, RESTART the launcher and then launch offline the prompt shows up as it did before

![image](https://user-images.githubusercontent.com/2097483/144848652-5f574f1c-1833-4ddb-ac8b-151fb5f145e6.png)

**Comment by TechnicallyCoded** [comment]
I could use that as workaround for the time being until it's fully fixed, thank you ^^

**Comment by phit** [comment]
please retest latest https://github.com/MultiMC/Launcher/commit/a5581b479e4c76a917716e915c4666d2be678f00

**Comment by TechnicallyCoded** [comment]
The offline launch now prompts for a username, ty!
