### ISSUE TITLE
error when luanching 1.8.9 with java 17

### ISSUE THREAD

**Issue by ThatOneDev-Code** [MultiMC/Launcher#4314]
log:
MultiMC version: 0.6.13-custom

Launched instance in online mode
Authentication server is online

authserver.mojang.com resolves to:
    [13.32.109.72]

session.minecraft.net resolves to:
    [23.23.220.104, 3.211.245.5, 52.70.238.65]

textures.minecraft.net resolves to:
    [13.33.68.39, 13.33.68.94, 13.33.68.36, 13.33.68.68]

api.mojang.com resolves to:
    [13.224.48.35]

Minecraft folder is:
/home/pugn/.local/share/multimc/instances/1.8.9/.minecraft

Java path is:
/usr/lib/jvm/java-11-openjdk/bin/java

Checking Java version...
Java is version 11.0.13, using 64-bit architecture, from Oracle Corporation.

Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz
Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

Subsystem: Dell Device 054f

Kernel driver in use: i915

NVIDIA Corporation GK107M [GeForce GT 640M] (rev a1)

Subsystem: Dell GeForce GT 640M

Kernel modules: nouveau, nvidia_drm, nvidia

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/pugn/.local/share/multimc/instances/1.8.9/natives

Using system GLFW.

Libraries:
  /home/pugn/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/pugn/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/pugn/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/pugn/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/pugn/.local/share/multimc/libraries/com/mojang/netty/1.7.7/netty-1.7.7.jar
  /home/pugn/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/pugn/.local/share/multimc/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/pugn/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/pugn/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/pugn/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/pugn/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/pugn/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/pugn/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/pugn/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/pugn/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/pugn/.local/share/multimc/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/pugn/.local/share/multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/pugn/.local/share/multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/pugn/.local/share/multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/pugn/.local/share/multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/pugn/.local/share/multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/pugn/.local/share/multimc/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/pugn/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
  /home/pugn/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
  /home/pugn/.local/share/multimc/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /home/pugn/.local/share/multimc/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  /home/pugn/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/pugn/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username  --version MultiMC5 --gameDir /home/pugn/.local/share/multimc/instances/1.8.9/.minecraft --assetsDir /home/pugn/.local/share/multimc/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 24119

Using onesix launcher.

[19:22:55] [Client thread/INFO]: Setting user: pugn
[19:22:55] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[19:22:57] [Client thread/INFO]: LWJGL Version: 2.9.4
Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.

any help would be great!

**Comment by Testsr** [comment]
You are using Java 11, not Java 17.

**Comment by phit** [comment]
use java 8 for anything older than 1.17

**Comment by ThatOneDev-Code** [comment]
Thanks!

**Comment by Emile2020** [comment]
Hi i have the same problem but i have java 8

**Comment by CasperOng** [comment]
I don't think that 1.8.9 support java 17

**Comment by Emile2020** [comment]
nvm can uc lose it found problenm
groeten Emile De Bruyckere


Op wo 19 jan. 2022 om 16:09 schreef Casper ***@***.***>:
