### ISSUE TITLE
Option to change the app icon back the old icon via launcher settings

### ISSUE THREAD

**Issue by StereoMadnessss** [MultiMC/Launcher#4316]
### Role

I like the old icon better than the new one. To bring it back, I have to replace the icon every single time the launcher updates (1 - 4 days) in development channel. I have to replace it a lot.

### Suggestion

I want MultiMC to add a new option in Settings -> Launcher -> User Interface -> Show Classic Icon. This restarts the launcher and replaces the new icon with the old one.

### Benefit

So that I can bring back the old icon without replacing it every single time the launcher updates.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Old Icon:
![MultiMC_256x256x32](https://user-images.githubusercontent.com/77188051/145131415-442ddeab-c984-4cb5-8f6e-30af07b0dcb3.png)

**Comment by phit** [comment]
the official build still uses this icon or am I missing something?

**Comment by StereoMadnessss** [comment]
The new icon is in the dev channel

**Comment by phit** [comment]
no?

**Comment by phit** [comment]
the official icon is still used in the official builds, if thats not the case you aren't using multimc
