### ISSUE TITLE
Create a release for 0.6.14 so distro based packages can be updated

### ISSUE THREAD

**Issue by txtsd** [MultiMC/Launcher#4318]
### Description of bug

There's a tag, but a release is missing

### Steps to reproduce

See releases

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
tags are automatically releases https://github.com/MultiMC/Launcher/releases/tag/0.6.14

**Comment by txtsd** [comment]
Yes, but they don't have the assets attached in releases (eg: https://github.com/MultiMC/Launcher/releases/download/0.6.13/mmc-stable-lin64.tar.gz) 
...which the AUR packages use: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=multimc-native#n22

**Comment by phit** [comment]
seems like an issue of that package, use multimc-bin its the only official aur package, otherwise that package should probably move to use https://files.multimc.org/downloads/mmc-stable-lin64.tar.gz

**Comment by txtsd** [comment]
Alright I'll let the package maintainer know.
