### ISSUE TITLE
Minecraft 1.17+ not working Mac OS Mojave 

### ISSUE THREAD

**Issue by SpeedyZ500** [MultiMC/Launcher#4320]
### Operating System

macOS

### Description of bug

I cannot open Minecraft 1.17 or Minecraft 1.18 on MultiMC, I have Java 17 installed and I am having it use Java 17 for both 
https://paste.ee/p/htnhs 

### Steps to reproduce

Use a Mac with Mojave, open Multi MC, create a 1.17 or 1.18 instance and force it to use Java 17, or have Java 17 as your default, try launching Minecraft 1.17 or 1.18, and you will find it does not work

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide a log https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#uploading-logs

**Comment by SpeedyZ500** [comment]
https://paste.ee/p/htnhs

**Comment by alexeevdv** [comment]
I see log provided as pastebin link. I have same issue:

```
[10:52:59] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:52:59] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics
```

The issue is that it tries to load LWJGL 3.2.2 but M1 support was added only in 3.3.0

**Comment by alexeevdv** [comment]
See https://github.com/LWJGL/lwjgl3/issues/601

**Comment by phit** [comment]
you need to download Java x86_64 not for ARM (M1)

e.g. https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=x86-64-bit&package=jre#download-openjdk

**Comment by SpeedyZ500** [comment]
I have an M1 Mac

**Comment by phit** [comment]
Minecraft does not support ARM as of now, neither does MultiMC. Use x64 Java and the game will work just fine through Rosetta.

**Comment by alexeevdv** [comment]
Issue is not in Java.  Issue is in LWJGL

**Comment by SpeedyZ500** [comment]
I guess I will just have to play using the normal launcher, because Using 84_64 java did not work, and I have no idea if I even installed it correctly, though if it is an issue LWJGL couldn't that be tested in the dev version, the normal launcher works just fine, but it also installs java for it self

**Comment by phit** [comment]
the other Java does work just fine, provide a log with it not working otherwise I'll assume you didnt pick it after installing it

**Comment by SpeedyZ500** [comment]
The thing is I don't know if I installed it correctly, as I don't know how to install java from azul, I got 1.17 from oracle

**Comment by SpeedyZ500** [comment]
https://paste.ee/p/sQTZB

**Comment by phit** [comment]
nope thats still for ARM, if you want Oracle https://www.oracle.com/java/technologies/downloads/#jdk17-mac
make sure to use the x64 DMG Installer

**Comment by SpeedyZ500** [comment]
Ok it did work thanks for your help
