### ISSUE TITLE
MultiMC can't run when installed on a read-only filesystem

### ISSUE THREAD

**Issue by starcraft66** [MultiMC/Launcher#4328]
### Operating System

Linux

### Description of bug

When attempting to launch multimc from a read-only filesystem, I get the following error.
![image](https://user-images.githubusercontent.com/1858154/145633080-f94dceb5-f8f1-44ea-847a-e52528051ae1.png)
This has only started happening since the latest release, it used to work fine.

### Steps to reproduce

1. Download MultiMC and put it on a filesystem
2. Remount the filesystem as read-only
3. Launch MultiMC

### Suspected cause

The source code seems to indicate that the binary attempts to create log files in the current working directory or the directory where the binary is located which is not possible on a read-only filesystem:

Relevant `strace`:
```
unlink("DevLauncher-4.log")             = -1 EROFS (Read-only file system)
access("DevLauncher-4.log", F_OK)       = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "DevLauncher-3.log", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
unlink("DevLauncher-3.log")             = -1 EROFS (Read-only file system)
unlink("DevLauncher-3.log")             = -1 EROFS (Read-only file system)
access("DevLauncher-3.log", F_OK)       = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "DevLauncher-2.log", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
unlink("DevLauncher-2.log")             = -1 EROFS (Read-only file system)
unlink("DevLauncher-2.log")             = -1 EROFS (Read-only file system)
access("DevLauncher-2.log", F_OK)       = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "DevLauncher-1.log", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
unlink("DevLauncher-1.log")             = -1 EROFS (Read-only file system)
unlink("DevLauncher-1.log")             = -1 EROFS (Read-only file system)
access("DevLauncher-1.log", F_OK)       = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "DevLauncher-0.log", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
unlink("DevLauncher-0.log")             = -1 EROFS (Read-only file system)
openat(AT_FDCWD, "DevLauncher-0.log", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = -1 EROFS (Read-only file system)
```

I would have assumed MultiMC would try to dump its log files to `$XDG_DATA_HOME/multimc` or something along those lines, not in the working directory or the directory where the binary is located. Additionally, I don't think not being able to write a log file should prevent the use of the program, it should just be a warning.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CasperOng** [comment]
To be honest, I don't think this is a bug. Because MultiMC needs to generate logs, temp files, cache, and something else to run properly. By generating files, it means it should save the files. If it is in a read-only filesystem it will be a pain to save it. Therefore, it is reasonable to crash or not working on read-only filesystem. Try to copy it to a filesystem that supports reading and writing.

Thanks a lot for sending this issue. I am Casper. Hope you fix your issue as soon as possible. Have an awesome day!

**Comment by starcraft66** [comment]
It's perfectly reasonable for me to expect MultiMC to run on a read-only filesystem when the expected location for producing cache files according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (`$XDG_CACHE_HOME`) is located on a read/write filesystem. The problem is that MultiMC is trying to write its log file in an unexpected location.

**Comment by phit** [comment]
@peterix removed here, not sure if intentional or an oversight during the refactor https://github.com/MultiMC/Launcher/commit/5b3dffce62f7e4c00436adeca33c5f2fc4a21db4#diff-4fdf8315c04e169711c816665529a857e3d78bb49fd9461458b6a59b721b35f3L301-L306

**Comment by iqgrande** [comment]
I noticed this same issue. I set up an installation of 0.6.13 within a readonly filesystem so all of the users of that system can use MultiMC. Their information was typically saved to `${HOME}/.multimc` which was ideal.

**Comment by hqurve** [comment]
A workaround is to supply the -d flag to specifiy where to store stuff in, otherwise ti attempts to store it in the same location as the application directory

**Comment by peterix** [comment]
MultiMC is not supposed to exist in read-only locations.

**Comment by starcraft66** [comment]
@peterix This has nothing to do with read-only filesystems, rofs is just a symptom of the problem. You're incorrectly following the XDG specification and attempting to write log files to the directory where the program is installed. MultiMC used to write logs to the correct folder before this update... What happened?

I would expect this to also fail on any Linux system where the user doesn't have permission to write into the folder where MultiMC is installed in which is more common that running it on a read-only filesystem.

**Comment by starcraft66** [comment]
By the way, this is also an issue on macOS. I installed MultiMC to `/Applications` with an administrative user, then logged into a standard user and attempted to launch `/Applications/MultiMC.app` and was promptly greeted by the same error message in first post.
