### ISSUE TITLE
Option to enable auto update modloader

### ISSUE THREAD

**Issue by AxoCode** [MultiMC/Launcher#4331]
### Role

I play modded minecraft

### Suggestion

A global & instance setting to automatically update the modloader to the newer version.

### Benefit

To make sure the modloader stay updated.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It will update the modloader version when you launch the instance.
For example
![image](https://user-images.githubusercontent.com/57800056/145662753-7300e9c2-0a2f-47ec-aa26-8058da9f83d3.png)
I have this version of forge. Then, when I launch this instance (by clicking the launch button) it will automatically update (select the newest version of forge)

**Comment by phit** [comment]
not gonna happen, there's no guarantee of compatibility between versions or even stability
