### ISSUE TITLE
Unable to launch Minecraft 1.12.2 

### ISSUE THREAD

**Issue by DokStook** [MultiMC/Launcher#4332]
### Operating System

Linux

### Description of bug

Tried to play version 1.12.2 of Minecraft using MultiMC. It didn't work with java 17 so tried java 8, again didn't work. Also it doesn't work with forge. Here are logs:
With Forge: https://paste.ee/p/lxANe
Without Forge: https://paste.ee/p/7OQi0

### Steps to reproduce

1. Launch MultiMC
2. Add Minecraft 1.12.2 instance
3. Error! 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what distro? you are missing the required ATK libraries for the game, on arch base distros I think the package is just called `atk`

**Comment by DokStook** [comment]
> what distro? you are missing the required ATK libraries for the game, on arch base distros I think the package is just called `atk`

I am on Arch. And no, the libraries are not missing.

**Comment by phit** [comment]
you clearly are, hence the log lol, not sure what you are saying

**Comment by DokStook** [comment]
When I do `sudo pacman -S atk` it says `warning: atk-2.36.0-1 is up to date -- reinstalling`

**Comment by phit** [comment]
I said I think that's what the package is called, not that it is that package specifically. Usually if you install a desktop JDK/JRE those dependencies are automatically added. Did you maybe install a headless Java?

**Comment by DokStook** [comment]
Yes, I have installed all available java versions in my repostories. Even before writing this comment I tried to install only atk libraries. Still didn't work :-(

**Comment by DokStook** [comment]
Update: somehow deleting atk-wrapper fixed the issue. Lol
