### ISSUE TITLE
Strange and viral bug.

### ISSUE THREAD

**Issue by DeltaStas365** [MultiMC/Launcher#4334]
### Operating System

Windows

### Description of bug

Firstly, I couldn't make instanse with 1.17 and above version. Secondly, when you open instanse's folder, it automaticly delete files like saves, shaderpacks and ect. Sometimes MultiMC even can delete java.

### Steps to reproduce

Create the instaler and etc.

### Suspected cause

I dunno

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
* no versions
* no logs
* multimc has no code to delete something like java

please provide a proper reproduction, otherwise this issue is meaningless and very much sounds not like anything caused by multimc but some broken antivirus for example

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
