### ISSUE TITLE
Add custom clients feature.

### ISSUE THREAD

**Issue by CasperOng** [MultiMC/Launcher#4337]
### Role

I play lots of different Minecraft clients.

### Suggestion

Add a feature makes someone like me can use custom jar files.

### Benefit

More convenient to switch between different clients. Although, I already know how to do this. But this is a little but to hard to do as a new MultiMC user. This took me 2 hours searching online, searching in MultiMC wiki, and finding help. I hope you can add a button to use custom jar files.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
Confused what you are asking for, you can already replace the minecraft.jar with one click in the instance, what do you propose being changed?

**Comment by CasperOng** [comment]
@phit To make my life easier. This is what I mean
![image](https://user-images.githubusercontent.com/90828938/145683382-f7f776d2-3848-4dcc-89dc-1a2bdc92d075.png)

**Comment by CasperOng** [comment]
Basically add a button while you are creating a new instance

**Comment by phit** [comment]
but like what would that jar be?

**Comment by CasperOng** [comment]
emm

**Comment by CasperOng** [comment]
https://youtu.be/tDQ0deA2VEc?t=515

**Comment by CasperOng** [comment]
@phit Back here

**Comment by phit** [comment]
yeah that kinda stuff hasn't been a thing to do in almost a decade, I don't think adding first party support for hackery like this is a good idea.
Those "client" need to learn how to properly distribute their mods and not this terrible jar modding.

**Comment by CasperOng** [comment]
@phit I see what you mean. This is your team's choice I just made this suggestion. The final decision is made by your team!
