### ISSUE TITLE
Getting `java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil` after log4j security fix

### ISSUE THREAD

**Issue by farblos** [MultiMC/Launcher#4339]
### Operating System

Linux

### Description of bug

Creating a new 1.16.4 world with WorldEdit mod installed results in

```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
  at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
  at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
  at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
  at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
  at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
  at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:113)
  at com.sk89q.worldedit.fabric.FabricWorldEdit.registerCommands(FabricWorldEdit.java:132)
  at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41)
  [...]
```

Crash file [crash-2021-12-11_19.12.01-client.txt](https://github.com/MultiMC/Launcher/files/7697538/crash-2021-12-11_19.12.01-client.txt) attached.

This seems to happen after the log4j fixes got rolled out recently, described e.g. [here](https://multimc.org/posts/log4j-remote-execution.html).

### Steps to reproduce

Use the following versions:

MultiMC 0.6.14-2998
Minecraft 1.16.4
Java 11.0.13

and mods:

```
Mods:
  [✔️] NoFog-1.16.2b1-Fabric
  [✔️] architectury-1.6.114-fabric
  [✔️] autoconfig1u-3.3.1
  [✔️] cloth-config-4.10.13-fabric
  [✔️] fabric-api-0.30.3+1.16
  [✔️] light-overlay-5.7.0
  [✔️] lithium-fabric-mc1.16.5-0.6.3
  [✔️] logical_zoom-0.0.8
  [✔️] malilib-fabric-1.16.4-0.10.0-dev.21+arne.5
  [✔️] minihud-fabric-1.16.4-0.19.0-dev.20201103.184029
  [✔️] modmenu-1.16.7
  [✔️] phosphor-fabric-mc1.16.3-0.7.1+build.11
  [✔️] randomblockplacement-1.16.5-fabric0.30.0-1.1.1
  [✔️] sodium-fabric-mc1.16.3-0.1.0
  [✔️] worldedit-fabric-mc1.16.3-7.2.2-dist
```

Results in the following library path being used:

```
  [...]
  /home/jschmidt/MultiMC-0.16.4/bin/libraries/org/apache/logging/log4j/log4j-api/2.15.0/log4j-api-2.15.0.jar
  /home/jschmidt/MultiMC-0.16.4/bin/libraries/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar
  [...]
```

Try to create a new world in above setup and you should see the exception.

### Suspected cause

Upgrade of log4j from 2.8.1 to 2.15.  When I manually replace the 2.15 jars with the 2.8.1 jars, things work as usual.

The [security message](https://multimc.org/posts/log4j-remote-execution.html) mentions that MultiMC would:

> Force all modern versions of Minecraft to use log4j 2.15.0, which doesn’t have this issue.
> Force old version of Minecraft to use a patched version of log4j 2.0-beta9, which has this issue fixed.

Can it be that in my particular setup MultiMC should better choose the log4j for "old versions"?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by farblos** [comment]
When I remove the WorldEdit mod (and only that) from the instance this bug won't reproduce.  So `worldedit-fabric-mc1.16.3-7.2.2-dist` seems to depend on a class that is available in log4j 2.8.1, but not in log4j 2.15.

**Comment by theofficialgman** [comment]
@farblos this issue may have already been fixed in worldedit
try using 7.2.5 which supports mc 1.16.3-1.16.5 https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3283693

**Comment by farblos** [comment]
@theofficialgman Despite your discouraging 2nd paragraph I gave it a try ... and it resolved this issue!  Feeling slightly embarrassed.  Thanks a lot.
