### ISSUE TITLE
Can't sideload Optifine Standalone with Fabric (Without Optifabric)

### ISSUE THREAD

**Issue by juliocoliveira** [MultiMC/Launcher#4340]
### Operating System

Windows

### Description of bug

We should be able to load Optifine standalone + Fabric.
I followed the tutorial https://github.com/MultiMC/Launcher/wiki/MultiMC-and-OptiFine to install Optifine standalone on MultiMC.
It works fine, But if i want to install fabric with it, it disable Optifine.
I can only load optifine OR fabric, Not both.

### Steps to reproduce

Use the tutorial: https://github.com/MultiMC/Launcher/wiki/MultiMC-and-OptiFine to install Optifine standalone, And add Fabric

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by juliocoliveira** [comment]
I would like to skip the need for Optifabric since the developer takes a good while to updated it to 1.18.1

**Comment by RDKRACZ** [comment]
This is a joke, right?

**Comment by juliocoliveira** [comment]
No its not a joke, Its a serious question, There is no joke here pal.
I don't know much about MultiMC, and didn't found any tutorials for that so.
I'm here to get help. Not to joke around.

**Comment by juliocoliveira** [comment]
I know that Optifine standard its a Forge, and i can't load fabric with forge, but I can install without forge, and there is Optifabric.
So one could say that would be possible to load Optifine Standalone with Fabric.

**Comment by phit** [comment]
its impossible and up to optifine to support such things
