### ISSUE TITLE
Resolving mod IDs fails on 0.6.14-develop-3011

### ISSUE THREAD

**Issue by Seegras** [MultiMC/Launcher#4342]
### Operating System

Linux

### Description of bug

Upon downloading a modpack, it takes a very long time "Resolving mod IDs" until it eventually fails with "Job Mod Download failed to process"
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/7698435/MultiMC-0.log)

### Steps to reproduce

1. Right click
2. "Create instance"
3. CurseForge
4. Choose any (I tried AQM2 1.3, All of Fabric 5, Better Minecraft 1.18.1)
5. Wait several minutes until it errors out

Same if you install from zip. 

### Suspected cause

Maybe related to https://github.com/MultiMC/Launcher/issues/1977 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> with reason  499

looks like the curse meta service was having issues, if it eventually errored out that seems like working as intended, it is also back up now
