### ISSUE TITLE
Downloading failed

### ISSUE THREAD

**Issue by PlayerIn3D** [MultiMC/Launcher#4343]
### Description of bug

While trying to download modpack Cave Factory i got an popup message saying that Mod download failed 

### Steps to reproduce

Add new instance -> sellect curse forge -> search for Cave Factory -> press OK button -> Fail

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by PlayerIn3D** [comment]
![image](https://user-images.githubusercontent.com/49489837/145708259-497766b6-ed5a-46db-a9b9-16850e3a3060.png)

**Comment by phit** [comment]
curse meta was having issues, which seem to be resolved now
