### ISSUE TITLE
switch to GPL3

### ISSUE THREAD

**Issue by binex-dsk** [MultiMC/Launcher#4346]
### Role

For distributing ebuilds on Gentoo.

### Suggestion

Switch to the GPL3 license, or a similar fully FLOSS license. And no, BSD and MIT do not count.

### Benefit

To be fully FOSS.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The developer's attitude towards forks, redistributions, and building from source has been incredibly odd. There is no reason we should not be allowed to build our own copies from source. And there is ESPECIALLY no reason we shouldn't be allowed to use the name of the project in our forks. Because of the attitude towards this, the project may as well be fully proprietary.

Switching to the GPL would fix this.

And to any bystanders reading this, ensure to use 0.6.12 or earlier. Later versions are heavily censored, and unable to be properly and fully compiled from source.

**Comment by jamierocks** [comment]
I don't particularly wish to go down a rabbit hole here, but I do want to say a few things.

> There is no reason we should not be allowed to build our own copies from source.

You absolutely can build the launcher from source. The author has even gone to pains to allow you to brand the launcher as you please, with relative ease.

> And there is ESPECIALLY no reason we shouldn't be allowed to use the name of the project in our forks.

Forks should use their own branding, as previously mentioned a large effort was made to facilitate forks being able to easily provide their own branding.

> Because of the attitude towards this, the project may as well be fully proprietary.

That's just silly.

**Comment by peterix** [comment]
Absolutely not, not in a million years.

**Comment by binex-dsk** [comment]
>fundamentally incompatible with Free Software

???? No it isn't, unless M$ is bribing you.
