### ISSUE TITLE
[AUR] multimc-bin package missing - 404

### ISSUE THREAD

**Issue by spannerman79** [MultiMC/Launcher#4352]
### Operating System

Linux

### Description of bug

On https://multimc.org/, under Download and Install, the AUR package that points towards https://aur.archlinux.org/packages/multimc-bin is now 404'ed

### Steps to reproduce

Browse to https://aur.archlinux.org/packages/multimc-bin - see result

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jotoho** [comment]
The prople in charge of the AUR decided to delete `multimc-bin` a few hours ago and reject peterix's request for the deletion of `multimc-git`

* Deletion record for `multimc-bin`: https://lists.archlinux.org/pipermail/aur-requests/2021-December/063471.html
* Rejection of peterix's deletion request in regards to `multimc-git`: https://lists.archlinux.org/pipermail/aur-requests/2021-December/063469.html

**Comment by Soup-64** [comment]
looks like the aur package was taken down for not following the AUR standards, as seen in this quote from the deletion record: "...but installing an installer that just runs shell to install the latest version of the installer is not acceptible".

**Comment by Soup-64** [comment]
The package is back up with a few changes, notably the run location has changed to /usr/bin/multimc, which required me to update the multimc.desktop file in KDE to be able to run it from kickoff. The PKGBUILD has also been changed as seen in the package's description to be complaint with AUR standards.

**Comment by Forkk** [comment]
The new `multimc-bin` package that the AUR has replaced our official package with is broken and unsupported here. `multimc-git` is unsupported as well. No AUR packages will be supported any longer. Use the "generic" tarballs from the website instead.

**Comment by spannerman79** [comment]
You still could provide a pacman ready package.  Many others do that aren't on the AUR.

The first one off the top of my head is [r2modman](https://github.com/ebkr/r2modmanPlus/releases) (look for the `.pacman` file).

Another one is overGrive.  

I am _ definatly _ sure that there are others out there.

**Comment by ProjectSynchro** [comment]
There is this PKGBUILD: https://github.com/MultiMC/multimc-pkgbuild
It looks like it has recently updated it to be in line with the rest of the packages. 

It's definitely a better solution than just using the generic tarballs.
