### ISSUE TITLE
Universal folders and/or mod

### ISSUE THREAD

**Issue by Cahseww** [MultiMC/Launcher#4357]
### Role

I use it to play multiple fabric instances.

### Suggestion

I want there to be a universal .minecraft folder.

### Benefit

Worlds and texture packs are universal.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know this has never been done (well not that i know of) but i think it is possible. I am no coder or whatever but could you rebind another button to take a screenshot but save it somewhere else? (this won't be like a vanilla screenshot function it is like fully modded). I dont know if this is a really dumb idea or not because i dont know anything about modding so dont make fun of me or something lol.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/3861
