### ISSUE TITLE
I just want to play beta 1.7 (with these fixes) I am inexperienced and just want to play a better beta. Here is the logs:

### ISSUE THREAD

**Issue by TakahashiEdenyako** [MultiMC/Launcher#4358]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffeb4f82d77, pid=12224, tid=0x0000000000000a58
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22d77]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
