### ISSUE TITLE
Performance Issues With Old Pack (MindCrack Pack)

### ISSUE THREAD

**Issue by WaterPasta** [MultiMC/Launcher#4359]
### Operating System

Windows

### Description of bug

I tried playing the MindCrack Pack (MC 1.4.7) and experienced major performance issues. These include rather slow chunk loading, an average of 40 fps while loading/rendering chunks (up to 80fps when not doing so), large framerate fluctuations, moderate to severe microstuttering (again, mostly on chunk loading), frequent drops down to 25fps, generally unstable performance. When the game is paused, I can get an excess of 150fps (not sure if that's normal). I tried playing the pack via the FTB Legacy launcher and averaged 100fps on the same settings with little to no loading, framerate or stuttering issues.

What I expected: Similar performance to other launchers.

What happened: Very poor performance.

What I have tried:
Restarting PC (no effect)
Changing graphics settings (setting every setting to lowest makes the game run ok, but that shouldn't be necessary)
Using/not using Optifine (no effect, this surprised me)
Using/not using custom textures (little to no effect)
Changing RAM allocation (no affect)
Various JVM arguments (no effect)
Trying various Java versions (no effect)
Updating graphics drivers (no effect)
Changing NVidia Control Panel settings (no effect)
Creating the instance via the FTB and FTB Legacy tabs (no difference)

### Steps to reproduce

Make an instance via either FTB modpack tab.
Run the game.

### Suspected cause

It's vague, but I'd think it might have something to do with how MultiMC structures the files and loads them. This issue seems like it might be caused by the game having difficulties with the loading, rendering or some other process regarding chunks, though I'm no expert.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please give us F3 screenshots of running the pack through MultiMC and through whatever other launcher, the issue doesn't really make any sense and that will help show what is different

**Comment by spannerman79** [comment]
> I tried playing the pack via the FTB Legacy launcher and averaged 100fps on the same settings with little to no loading, framerate or stuttering issues.

There are two possibilities here.

Either you are running via onboard Intel Graphics, or you are on a laptop with a hybrid setup.

As you can see from my [testing](https://flightlessmango.com/games/13928/logs/2384) you shouldn't be getting such low FPS

A "quick" test if you are using onboard/Intel graphics is to just rename `MultiMC.exe` to `Minecraft.exe` and run MultiMC and the pack again.  You can _always_ rename it back afterwards.

The other option if you are using a dual graphic system, and its an Intel/nVidia hybrid system is;

1. Open the NVIDIA control panel and go to 3D Settings>Manage 3D Settings.
2. Select the Program Settings tab and click the ‘Add’ button. Sort by: Recently Used.
3. Select java.
4. Down the bottom click "Add Selected Program"

What that will do is that when java starts up (its java that actually used to play minecraft) your dGPU will be used, not your iGPU (Intel).
