### ISSUE TITLE
Missing xcrun error when I try to launch.

### ISSUE THREAD

**Issue by elisionking125** [MultiMC/Launcher#4362]
### Description of bug

When I try and launch multimc, I get an error message saying: "xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun"

There is no file under the name of xcrun and if something needs to be renamed, I don't know what it is. Would anyone be able to explain how to fix the problem?

### Steps to reproduce

I don't think it is possible to reproduce, unless you also have a mac with the latest OS update.

### Suspected cause

It was working previously, but I think it may have been the new MacOS update that broke it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
That doesn't sound related to MultiMC at all, but your Xcode installation being broken, how are you launching MultiMC and where did you get it from?

**Comment by elisionking125** [comment]
I don’t know what you mean by how I launch it, but I downloaded it from multimc.org. And I think it may have something to do with multimc because I can still launch the game through the vanilla launcher.

> On Dec 17, 2021, at 02:01, Philip T. ***@***.***> wrote:
> ﻿
> That doesn't sound related to MultiMC at all, but your Xcode installation being broken, how are you launching MultiMC and where did you get it from?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

-- 




If you believe this email violates Canada's Anti-Spam Legislation 
(CASL), please contact us 
<https://docs.google.com/forms/d/e/1FAIpQLSemiJbGqN-4ClXBDKPoRp4-EKTswV5sSzp-KE6ff9LW64IMiA/viewform?usp=sf_link>.


Edmonton Public Schools, Centre for Education, 1 Kingsway NW, Edmonton AB 
 T5H 4G9

**Comment by phit** [comment]
the error probably has nothing to do with MultiMC at all, https://www.google.com/search?q=missing+xcrun+at%3A+%2FLibrary%2FDeveloper%2FCommandLineTools%2Fusr%2Fbin%2Fxcrun

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you need further support ask in the #help channel in the [MultiMC Discord](https://discord.gg/multimc).
