### ISSUE TITLE
[Suggestion] - one click install for important mods 

### ISSUE THREAD

**Issue by Sparkenstein** [MultiMC/Launcher#4369]
### Role

I play modded minecraft

### Suggestion

multimc supports 1 click install of API layers of fabric/forge etc. I wish there was a way to install the mods like sodium etc the same way

### Benefit

mods like sodium are 100% required in almost all cases with fabric. one very version we have to go through a lot of process to download it and paste it inside mods folder etc. this process can be saved

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Like stated above: the mods like Sodium, phosphor etc are must have for performance issues with fabric. I don't have much experience with forge but I am sure there are such mods with forge too. it'd be helpful if there's a way to have latest versions of these mods on single click just like we can install Fabric api etc.

## Problems
One problem with this feature I can think of is "how to decide which mods should be listed for single click install"
another problem is how and where to download them from, since sources can vary

a crude way to achieve this could be searching mods on curseforge itself. not sure if they have API available. this should solve the issue of which mods to install, since we don't have to give a pre-populated list. typing mods name, should just find it's version and list it out.

otherwise we can have a poll or vote on what are essential mods that most of the users use. and then have top 5 or 10 of them listed in the mods section, this will be like kind of hardcoding the feature but should solve the problem for most of the users.

let me know what you think, in case I am missing something

**Comment by phit** [comment]
> just like we can install Fabric api etc

there is no such feature, you can install fabric loader

anyway, installing mods like that is mostly tracked by https://github.com/MultiMC/Launcher/issues/3055 and literally 10s of optifine related issues, but as peterix said best

>  I don't want to special case one particular mod. If at all, this should be a general solution, because there are many mods.
