### ISSUE TITLE
Latest Version on Arch Linux Won't Launch

### ISSUE THREAD

**Issue by onkoe** [MultiMC/Launcher#4371]
### Operating System

Linux

### Description of bug

Using version multimc5-0.6.14-3 from the AUR. When launching from rofi, nothing happens. When launching from the terminal, it spits out `multimc: error while loading shared libraries: libLauncher_quazip.so: cannot open shared object file: No such file or directory` and returns you to your shell. This does not occur on MultiMC 0.6.13-1, so I am using it temporarily and it's working fine. 

### Steps to reproduce

* Try to open latest version
* Nothing happens :(

### Suspected cause

I think a library may be too old, as the older versions of MultiMC work normally. I suspect that quazip is a rolling dependency that's lagging a bit behind, but I'm not informed on that. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by zt64** [comment]
I'm also having this exact same issue on Arch Linux

**Comment by jotoho** [comment]
AUR packages are not supported. The official package got taken down: #4352

Contact your packager for help.
