### ISSUE TITLE
Resource Pack folder not found

### ISSUE THREAD

**Issue by Philo6978** [MultiMC/Launcher#4375]
### Operating System

Windows

### Description of bug

I just downloaded MultiMC to play RLcraft, however, when I try to open the resource folder in RLCraft it displays this
![Screenshot 2021-12-21 151633](https://user-images.githubusercontent.com/62268673/146870190-08e7ceca-01ad-450a-9ba5-c84fdfd9a848.png)

### Steps to reproduce

open RLCraft or maybe any mod.
go to settings
go to resource packs
press on resource packs folder
it will then bring up the error message in the image above

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Philo6978** [comment]
oh, thank you!
