### ISSUE TITLE
1.8.9 minecraft crash after launch

### ISSUE THREAD

**Issue by AwesomeAurick** [MultiMC/Launcher#4377]
### Operating System

Linux, Other

### Description of bug

Running on raspian 64bit
Minecraft version 1.8.9 with optifine and forge
Installed via pi-apps
Using java 8
Minecraft works with optifine only but crash after adding forge

Error log:
MultiMC version: 0.6.14-custom

Launched instance in offline mode

Minecraft folder is:
/home/pi/MultiMC/install/instances/1.8.9/.minecraft

Java path is:
/home/pi/MultiMC/install/java/java-8-temurin-aarch64/jre/bin/java

Checking Java version...
Java is version 1.8.0_302, using 32-bit architecture, from Temurin.

OpenGL version string: 3.3 (Compatibility Profile) Mesa 20.3.5

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/pi/MultiMC/install/instances/1.8.9/natives

Libraries:
  /home/pi/MultiMC/install/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/pi/MultiMC/install/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/pi/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/pi/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/pi/MultiMC/install/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /home/pi/MultiMC/install/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/pi/MultiMC/install/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/pi/MultiMC/install/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/pi/MultiMC/install/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/pi/MultiMC/install/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/pi/MultiMC/install/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/pi/MultiMC/install/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/pi/MultiMC/install/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/pi/MultiMC/install/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/pi/MultiMC/install/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/pi/MultiMC/install/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/pi/MultiMC/install/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/pi/MultiMC/install/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/pi/MultiMC/install/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/pi/MultiMC/install/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/pi/MultiMC/install/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/pi/MultiMC/install/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/pi/MultiMC/install/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  /home/pi/MultiMC/install/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/pi/MultiMC/install/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/pi/MultiMC/install/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/pi/MultiMC/install/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/pi/MultiMC/install/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/pi/MultiMC/install/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /home/pi/MultiMC/install/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /home/pi/MultiMC/install/libraries/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (missing)
  /home/pi/MultiMC/install/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar (missing)
  /home/pi/MultiMC/install/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar (missing)
  /home/pi/MultiMC/install/libraries/jline/jline/2.13/jline-2.13.jar (missing)
  /home/pi/MultiMC/install/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar (missing)
  /home/pi/MultiMC/install/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar (missing)
  /home/pi/MultiMC/install/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar (missing)
  /home/pi/MultiMC/install/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar (missing)
  /home/pi/MultiMC/install/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar (missing)
  /home/pi/MultiMC/install/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar (missing)
  /home/pi/MultiMC/install/instances/1.8.9/.minecraft/bin/minecraft.jar

Native libraries:
  /home/pi/MultiMC/install/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/pi/MultiMC/install/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Jar Mods:
  OptiFine_1.8.9_HD_U_M5_MOD (34fef903-7505-4dd4-8b6e-1d7fa3c99b9f.jar)

Params:
  --username  --version MultiMC5 --gameDir /home/pi/MultiMC/install/instances/1.8.9/.minecraft --assetsDir /home/pi/MultiMC/install/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType  --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xms409m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 3484

Using onesix launcher.

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code 255.
Clipboard copy at: 22 Dec 2021 14:07:03 +0800

### Steps to reproduce

Fresh install version of raspian 64bit
install pi-apps: https://github.com/Botspot/pi-apps
Install multimc using pi-apps via gui
Create a new minecraft 1.8.9 instance
Install optifine (you can search from google because this step is complicated)
add forge via multimc
launch minecraft 1.8.9 with optifine and forge

### Suspected cause

Forge incompatibility 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums.
