### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KalecN** [MultiMC/Launcher#4378]
### Operating System

Windows

### Description of bug

Sincere apologies if this is in the wrong place or anything like that, but I'm crashing on launch and though I've scanned the log several times, I don't really know what I'm looking for. I don't see anything obvious (to me at least) like a mod name that's causing it. All I know is that MultiMC is mentioned alot, and Sponge is mentioned alot- even though I don't have it installed? 

*long sigh*

Anything anyone can tell me is appreciated.

Additionally, this is a modpack I played months ago and I've upgraded MultiMC and the forge version since.

https://textbin.net/ia6a8v3fsc

### Steps to reproduce

Attempt to start the game/server.

### Suspected cause

At first I assumed it was typical mod incompatibility or missing libraries/etc. But even after removing any new mods the issue persists. I wouldn't be bothering people If I had any idea. ;_;

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
I'm unable to view that log, but this doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
