### ISSUE TITLE
Modded instance does not launch on macos 12.1

### ISSUE THREAD

**Issue by GamaG27** [MultiMC/Launcher#4380]
### Operating System

Macos 12.1

### Description of bug

New mooded instance should launch but crashes always

### Steps to reproduce

1. Open MultiMc
2. Load modded instance (Modpack Mineshafts and Monsters)
3. it crashes

### Suspected cause

Process crashed with exitcode 6.
 ( the solution given in another issues does not work)

2 crash logs;

1. Macos java's crash log
2. MultiMc's crash log

[Crash logs.zip](https://github.com/MultiMC/Launcher/files/7763806/Crash.logs.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
