### ISSUE TITLE
Hexxit 2 wont launch

### ISSUE THREAD

**Issue by G-Utopia** [MultiMC/Launcher#4382]
### Operating System

Windows 11
jdk-17.0.1

### Description of bug

The Modpack Hexxit 2 cant start because of unexpected internal reasons.
Log: https://paste.ee/p/duRZP

### Steps to reproduce

* Create a new Instance
* Choose Technic and select Hexxit II
* Install it 
* Run it

### Suspected cause

Internal conflicts with Java and/or Minecraft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
