### ISSUE TITLE
MultiMC doesn't launch because of missing library (?)

### ISSUE THREAD

**Issue by JustAnotherStrange** [MultiMC/Launcher#4383]
### Operating System

EndeavourOS (Arch based, uses Arch repos) 

### Description of bug

I try to launch multimc, but it gives this error
`multimc: error while loading shared libraries: libLauncher_quazip.so: cannot open shared object file: No such file or directory`
I'm using the AUR version. (package `multimc5`)
However, when I search for the file in question: 
![image](https://user-images.githubusercontent.com/64844168/147308409-60638dcd-081c-41ac-a4f7-83b83a05164c.png)
So the file is there... 
I just recomplied it from latest version on git. Same issue. 

### Steps to reproduce

- Try to start multimc
- On an arch based system. (that might be the issue...?)

### Suspected cause

![image](https://user-images.githubusercontent.com/64844168/147308551-be641633-a23c-4b0b-8f58-e0ff268cd8e5.png)
Something with the compiling. I'm not proficient in this, but it seems the shared library dependencies weren't linked correctly in the compilation process. Because the files *are* there, which is seen above.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc5 or any other multimc package on aur isn't supported by us nor is it multimc
please use the official source instead https://github.com/MultiMC/multimc-pkgbuild

**Comment by JustAnotherStrange** [comment]
Oh, I didn't know this. I installed it from that PKGBUILD and all is working great. Thanks for the help.
