### ISSUE TITLE
Be able to download mods from Curseforge and other sites that host mods for Minecraft that are reliable

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [MultiMC/Launcher#4384]
### Role

I play Minecraft.

### Suggestion

I would like to be able to download mods from websites.

### Benefit

Easier mod installing

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I think being able to download mods from websites like CruseForge with MultiMC would make it easier for users to use MultiMC and would encourage people to use MultiMC more.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/3055#issuecomment-964415542 and many many more, especially curseforge is unlikely to ever happen
