### ISSUE TITLE
Крашит multi mc

### ISSUE THREAD

**Issue by twin333** [MultiMC/Launcher#4386]
### Operating System

Windows

### Description of bug

почему то все мои сборки начали крашится врядли что то с версией или с модами так как не давно всё запускалось все сборки а сейчас сборки начинают крашится даже не начиная загружаться 
![image](https://user-images.githubusercontent.com/96664603/147392295-e90ce95b-2688-4cd8-bb86-2bbee4b9f042.png)
![image](https://user-images.githubusercontent.com/96664603/147392300-bd28f1cc-03da-4b56-a867-a9e24888e8bf.png)

### Steps to reproduce

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by twin333** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

спасибо помог
