### ISSUE TITLE
Relative JRE paths don’t work

### ISSUE THREAD

**Issue by ryleu** [MultiMC/Launcher#4387]
### Operating System

Windows

### Description of bug

If you use a relative path for the JRE location, Minecraft does not launch.

### Steps to reproduce

* Place the jre folder from wherever you get your JRE in the same folder that MMC is in.
* Set the Java path in MMC to `../jre/bin/javaw.exe`.
* Try to launch the game.

### Suspected cause

MultiMC doesn’t resolve relative paths before attempting to launch the game with them.

Possible solution: resolve relative paths before attempting to run the game. Ideally resolve them relative to the MultiMC executable.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by embeddedt** [comment]
This seems like it'd be hard to get right, especially if there were symlinks involved. IMO this is a feature request, not a bug.

**Comment by ryleu** [comment]
> This seems like it'd be hard to get right, especially if there were symlinks involved.

It could be. I believe that, at least on Linux, there's a command to resolve paths.

> IMO this is a feature request, not a bug.

I thought it fit as a BR, because I was expecting it to work and it didn't. I wouldn't mind it being re-tagged as an FR.

**Comment by phit** [comment]
this works already on Windows, are you sure it doesn't on Linux? 
![image](https://user-images.githubusercontent.com/2097483/147547943-3508bdac-5efe-40f3-8978-44cc46ef5bfa.png)

can you provide your launcher log file, MultiMC-0.log in the launcher folder

**Comment by ryleu** [comment]
It definitely doesn't work on Windows. Let me get you a log. I don't have a Windows machine though, I'm making this for a friend who does, so it might be a sec. I'll test it on Linux too though.

**Comment by spannerman79** [comment]
> Place the jre folder from wherever you get your JRE in the same folder that MMC is in.

This is how https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs is done.

> It definitely doesn't work on Windows.

Incorrect.

I know for a **fact** it does.  I was visiting family during new years and did https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs for my neice toaster laptop and it **definatly** worked.

And on linux;
![Screenshot_20220116_224543](https://user-images.githubusercontent.com/7542384/149658572-2de8f8f3-c655-43d6-86c4-c579f28f5cd2.png)


PEBKAC

**Comment by ryleu** [comment]
> I know for a **fact** it does.  I was visiting family during new years and did https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs for my neice toaster laptop and it **definitely** worked.

Maybe it's the ../ I used?

**Comment by SadDemon1111111111111111111111111111111** [comment]
**Try to write down the path by yourself** @ryleu

**Comment by ryleu** [comment]
fixed now, not sure how or why. i didn't change the path, but the error is gone.
