### ISSUE TITLE
macOS accounts not being saved

### ISSUE THREAD

**Issue by MrRedRhino** [MultiMC/Launcher#4389]
### Operating System

macOS

### Description of bug

When adding an account and closing the app, the account won't show up when opening MultiMC again.

### Steps to reproduce

- Add an account
- relaunch MultiMC
- The account has to be added again

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide your MultiMC-0.log or later, https://github.com/MultiMC/Launcher/wiki/Feedback#multimc-bugs
this sounds like your user doesnt have permissions to the MultiMC folder (app bundle)

**Comment by MrRedRhino** [comment]
Thank you for that tip with the permission, it didn't have permission to read it indeed, no it is working!
