### ISSUE TITLE
Join Server with resource pack

### ISSUE THREAD

**Issue by FayneAldan** [MultiMC/Launcher#4398]
### Role

I play on servers with required resource packs and dedicated mods.

### Suggestion

I want an option, when joining a server via MMC, to allow downloading server resource packs.

### Benefit

So that I can open my "Wynncraft" instance and have it automatically accept the required server resource pack when it joins.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When joining via the Servers menu, it should just respect the [Server Resource Packs / `acceptTextures` setting](https://github.com/MultiMC/Launcher/blob/b258eac215c791b2a8eed10cecbbf9551c87f0b9/launcher/ui/pages/instance/ServersPage.cpp#L21-L26) already saved within `servers.dat`.

When using the "Set a server to join on launch" setting, there should be an option in those settings to specify if server resource packs are allowed.

**Comment by phit** [comment]
none of this is handled by MultiMC to join servers on launch we just use the vanilla --server flag
