### ISSUE TITLE
Modded 1.18.1 Not working in offline mode (including no internet)

### ISSUE THREAD

**Issue by LayaReed** [MultiMC/Launcher#4400]
### Operating System

Windows

### Description of bug

When I would try to open my 1.18.1 modded instance when my computer was not connected to the internet, and through offline launch, it would pop up an error and not let me play. I know I correctly downloaded the instance since I had already opened it in online mode and correctly downloaded the files.

https://paste.ee/p/H58X2

### Steps to reproduce

1. Downloaded 1.18.1 vanilla, and opened game online for correct download of assets
2. Closed game and disconnected from internet
3. Tested offline mode with 1.18.1 vanilla, worked, went back online to download forge onto the instance
4. Downloaded forge through the side tab online and opened game to allow it to download correct assets, game launched correctly
5. Closed game and disconnected from the internet
6. Tested offline mode with 1.18.1 forge and it would pop up an error and not allow me to continue

### Suspected cause

I went through with the discord to find a solution. @__fastcall#8192 helped recreate the problem and they got the same outcome as me. They mentioned that it could possibly be a forgewrapper issue  He commented that in his personal logs, that forgewrapper would attempt to run every single time even in online mode and would not find the classes as well. 

Edit: Clarification in "suspected cause"
Edit: Added log of issue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by faastcall** [comment]
I can reproduce on Arch Linux, 5.15.12-zen1-1-zen, with MultiMC 0.6.14-develop-3121, installing using the official PKGBUILD.

Issue is only with minecraft versions that launch with ForgeWrapper, and only for 1.17.1 and above.(1.17.0 does not have any forge releases)

In 1.16.5, the latest version that does not have this issue, launching a new instance with forge installed will run ForgeWrapper, and every launch after that it will not, allowing the user to play in offline mode without a internet connection.

In 1.17.1 and above, launching a new instance with forge installed will run ForgeWrapper and allow the instance to launch, but it will continue running ForgeWrapper every subsequent time, download mappings everytime, as well as download and patch classes every time. 

ForgeWrapper also ignores if multimc is launched in offline mode or not, and will continue to do the above behavior if you have an internet connection, unlike the rest of multimc which completely skips networking when launching an instance if offline mode is selected.

This behavior makes it impossible to use offline mode for it's intended purpose, launching offline on 1.17.1 instances with forge.

**Comment by faastcall** [comment]
Log from 1.16.5 instance with forge 36.2.22, on it's first launch (online): https://paste.ee/p/T5qjB
Log from 1.16.5 instance with forge 36.2.22, on it's second launch (offline with no internet connection): https://paste.ee/p/dKkpi

Log from 1.17.1 instance with forge 37.1.1, on it's first launch (online): https://paste.ee/p/WKtSb
Log from 1.17.1 instance with forge 37.1.1 on it's second launch (offline with no internet connection): https://paste.ee/p/KK9EO, with a pop-up error message:
![Screenshot_20220101_140548](https://user-images.githubusercontent.com/95947746/147858242-00384ef0-17e9-4c3e-93f8-cd5dba12ac72.png)
Log from 1.17.1 instance with forge 37.1.1 on it's third launch (offline, but WITH a internet connection): https://paste.ee/p/QaM3b

Behavior from 1.17.1 also happens on any version above 1.17.1 with forge installed.

**Comment by peterix** [comment]
This is an error in the Forge installer:
```
        "PATCHED": {
            "client": "[net.minecraftforge:forge:1.17.1-37.1.1:client]",
            "server": "[net.minecraftforge:forge:1.17.1-37.1.1:server]"
        },
        "PATCHED_SHA": {
            "client": "'7233cb2e60ac0e49110593d7e4182e1a0bf081a7'",
            "server": "'bdf354470955786626a4d1c66a8c0f14b32e362d'"
        },
```

The patched client file is supposed to have SHA1 of `7233cb2e60ac0e49110593d7e4182e1a0bf081a7`
Instead, it's something else:
```
2dc8f1f71700f13b7465fff31c42337fc3a553b5  forge-1.17.1-37.1.1-client.jar
d367c3a836aeaca1c1b213deaab37d164b80a9bc  forge-1.17.1-37.1.1-installer.jar
82fd7860c2438fe9251b7a962999b0b2c8503a28  forge-1.17.1-37.1.1-universal.jar
```

The installer doesn't check the hash afterwards, so it happily completes.
But we check the hash on every launch, so we rerun the installer, which just produces broken junk again.

Repeat on every launch...

**Comment by peterix** [comment]
I guess ignore hash of `PATCHED`?

**Comment by peterix** [comment]
What hash does your `forge-1.17.1-37.1.1-client.jar` have?

**Comment by faastcall** [comment]
$ sha1sum /home/user/.local/share/multimc/libraries/net/minecraftforge/forge/1.17.1-37.1.1/forge-1.17.1-37.1.1-client.jar
694aa271e8cd02e5a6fe3181994f9d3e752e9082

**Comment by faastcall** [comment]
Hash changes each time you run the instance. Ran instance again, then did the same command: 
sha1sum /home/user/.local/share/multimc/libraries/net/minecraftforge/forge/1.17.1-37.1.1/forge-1.17.1-37.1.1-client.jar
524eaf2c3032be67f47c3653a34e368c36a020c6

**Comment by peterix** [comment]
Beautiful

**Comment by peterix** [comment]
The order of the files inside the jar is completely different every time

**Comment by peterix** [comment]
The obvious workaround is to ignore the hash of the output here...

**Comment by malte0811** [comment]
See also https://github.com/MinecraftForge/MinecraftForge/blob/41ea5b195bf5c818d1da8932d264a33de16fa632/build.gradle#L1387-L1391 (apparently a Vignette issue?)

**Comment by STEEPERCREVE** [comment]
I know this is probably necroposting, but I'm kind of out of options here. I have no mods, but my libraries file is completely empty. When launching offline mode it checks my microsoft account and sometimes the wifi I'm on (School/etc) wont let it download the assets. I'm on version 0.7.0 with MultiMC 5, and I'm running version 1.18. Trying to use MultiMC to run offline, but when I run offline where microsoft.com or mojang.com is blocked it disconnects my account and I have to reconnect on a more trusted wifi. Any Ideas? here's the log I get: "The Account has expired and needs to be logged in manually. Press OK to log in again." When I log in (with a free VPN because my parents still wont let me get a debit card) if I immediately launch in offline mode it works. Only way I can get it to work is to click on the version and click edit version, version, download all, (still needs a VPN, but doesn't make me sign into my account.) I don't know how else to help anyone answering this. Sorry.

**Comment by phit** [comment]
put invalid proxy settings in the options when on a filtered wifi, then multimc will see that its actually offline and not connect to anything
