### ISSUE TITLE
PKGBUILD version can't start; can't update, getting the error message: "Couldn't create folder for update downloads: /usr/lib/update/XXXXXX"

### ISSUE THREAD

**Issue by Erdragh** [MultiMC/Launcher#4401]
### Operating System

Linux

### Description of bug

General Info:
I'm on EndeavourOS, which is an Arch-based Linux distro using the default arch repositories and has access to the AUR

First off:
I installed multimc with [this pkgbuild](https://github.com/MultiMC/multimc-pkgbuild), as it says to avoid the AUR.
I tried both, git and wget, but neither worked as I would get the error:

    [erdragh@XXX multimc-pkgbuild]$ multimc
    /usr/bin/multimc: line 25: ./MultiMC: Permission denied

So the next thing I tried is installing the `multimc-bin` from the AUR, which is highlighted as installed when I tried the pkgbuild from above. Now I can start it and I already added my (Microsoft) account and played a few modpacks. However, I changed the update channel to development. It worked flawlessly when running pure Arch and I could update multimc without problems, but now, as I changed my drive I installed EndeavourOS instead of pure Arch.

Whenever I try to update It would download the packages and even shows progress bars, but also an Error Message saying:

> Couldn't create folder for update downloads:
> `/usr/lib/update/XXXXXX`

[Here are a few images of MultiMC displaying the issue](https://imgur.com/a/1KGGBYr)
[And here is part of the console output that I think is relevant to the issue](https://gist.github.com/Erdragh/60fc036500af5a3d90d46287d85c0538)

I may also be completely wrong and should not update MultiMC like this. If this is the case it would be nice if someone could provide a resource or an answer on how (or if) I should update MultiMC.

### Steps to reproduce

These may be the culprits, but I don't know:
- Use a freshly installed version of EndeavourOS
- Have the root partition formatted as `btrfs`
- Have no extra partition for home
- Use KDE Plasma
- Use the `linux-zen` kernel

For the issue with the pkgbuild:

- Follow [the instructions for git](https://github.com/MultiMC/multimc-pkgbuild#using-git) or [the instructions for wget](https://github.com/MultiMC/multimc-pkgbuild#using-wget)
- Try to start it from the console: `multimc`
- Observe the Error Message

For the issue with updating (the main issue):

- As the pkgbuild from above does not work, install the package `multimc-bin` from the AUR
- Launch it from the console, so you can see the output
- Go to `Settings` > `Launcher` > `Update Settings` and enable switch the `Update Channel` to `Development`
- Either click on the `Update` button or restart multimc (still from the console)
- Click on `Update Now`
- Either click on the Error Message behind the progress bars to view it or wait for the progress bars to complete
- Observe the Error Message (in dialogue form and in the console output)

### Suspected cause

I think it's a permission error with the File System. I don't know if it's relevant, but my root partition is `btrfs`
From the console output I think it downloads everything successfully, but can't update because it can't create a backup folder:

    8.622 D Task "NetJob(Update Files)" succeeded
    8.622 D Task "GoUpdate::DownloadTask(0x7ffdbffae810)" succeeded
    8.622 D Installing updates.
    8.623 W couldn't create folder "/usr/lib/update/backup"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Erdragh** [comment]
If I did anything extremely wrong or something I shouldn't have done in the first place, please tell me so as this issue/problem has been bugging me for about a week now

**Comment by phit** [comment]
use the pkgbuild anything else is and will not be supported here, whats the output of 
`ls -lsa /usr/bin/multimc`

**Comment by Erdragh** [comment]
Ok so I removed the package `multimc-bin` and installed it via the git cloned pkgbuild again and then ran the command, this is the output:

    4 lrwxrwxrwx 1 root root 19  1. Jan 21:07 /usr/bin/multimc -> /opt/multimc/run.sh

Sorry for this kind of stupid issue, but how would I go about fixing this permission problem?

**Comment by phit** [comment]
and `ls -lsa /opt/multimc/run.sh`? i suspect the script is just missing the execute bit

**Comment by Erdragh** [comment]
For that the output would be:

    4 -rwxr-xr-x 1 root root 729  1. Jan 21:07 /opt/multimc/run.sh

In `/opt/multimc/run.sh` there is a line in `deploy()`: `chmod +x MultiMC`. this same file gets executed later in `runmmc()` and that's probably where the Permission Errer stems from right? Sorry if that's wrong but just in case here's the output for:

    [erdragh@XXX ~] ls -lsa /home/erdragh/.local/share/multimc/MultiMC
    8 -rw-r--r-- 1 erdragh erdragh 4261  1. Jan 21:49 /home/erdragh/.local/share/multimc/MultiMC

**Comment by Erdragh** [comment]
Just in case anything messed up the PKGBUILD or the run.sh file, here's a gist with the content of these two files:
https://gist.github.com/Erdragh/8aa4d3099a425993e075b14b6779e2a0

**Comment by phit** [comment]
can you run `chmod +x /home/erdragh/.local/share/multimc/MultiMC` manually, and then try launching again

**Comment by Erdragh** [comment]
Yes I can, but it still won't launch:

    [erdragh@XXX ~]$ chmod +x /home/erdragh/.local/share/multimc/MultiMC
    [erdragh@XXX ~]$ multimc
    Launcher Dir: /home/erdragh/.local/share/multimc
    No missing dependencies found.
    chmod: cannot access '/home/erdragh/.local/share/multimc/bin/MultiMC': No such file or directory
    ./MultiMC: line 39: /home/erdragh/.local/share/multimc/bin/MultiMC: No such file or directory
    [erdragh@XXX ~]$ ls /home/erdragh/.local/share/multimc/bin
    ls: cannot access '/home/erdragh/.local/share/multimc/bin': No such file or directory

Seems like something isn't working right with the folder structure maybe?

**Comment by phit** [comment]
do those files not exist?

**Comment by Erdragh** [comment]
It seems as though instead of `......./bin/MultiMC` it somehow made `bin_MultiMC`:

    [erdragh@XXX ~]$ ls /home/erdragh/.local/share/multimc/
    accounts.json           bin_jars_NewLaunch.jar      bin_libLauncher_quazip.so   cache      libraries  MultiMC        MultiMC-2.log  multimc.cfg         translations
    assets                  bin_libLauncher_iconfix.so  bin_libLauncher_rainbow.so  icons      meta       MultiMC-0.log  MultiMC-3.log  notifications.json
    bin_jars_JavaCheck.jar  bin_libLauncher_nbt++.so    bin_MultiMC                 instances  metacache  MultiMC-1.log  MultiMC-4.log  themes

I don't know, but maybe a typo with an underscore instead of a slash?

**Comment by Erdragh** [comment]
Trying to run that file yields another permission error:

    [erdragh@XXX ~]$ /home/erdragh/.local/share/multimc/bin_MultiMC
    bash: /home/erdragh/.local/share/multimc/bin_MultiMC: Permission denied

**Comment by Erdragh** [comment]
in `..../multimc/MultiMC` there is this line, which is probably the chmod that fails to execute: 

    # Just to be sure...
    chmod +x "${LAUNCHER_DIR}/bin/${LAUNCHER_NAME}"

But I haven't found anywhere where this bin folder is created. But maybe that's the problem. I'm gonna try and install multimc in my EndeavourOS vm and see if it has the same issue. Maybe it was caused by the AUR version and if so then I will have learnt my lesson ;)

**Comment by phit** [comment]
well the problem is that the extraction of the tar.gz seems to have made no subfolders instead creating those files with _ instead, the bin folder and everything else comes from the downloaded tar.gz

**Comment by Erdragh** [comment]
First off I'm going to delete everything out of the .local/share/multimc folder and reinstall the pkgbuild from scratch.

Secondly I got another error in my VM:

    [erdragh@erdragh-virtualbox multimc-pkgbuild]$ multimc
    Launcher Dir: /home/erdragh/.local/share/multimc
    No missing dependencies found.
    /home/erdragh/.local/share/multimc/MultiMC: error while loading shared libraries: libicui18n.so.70: cannot open shared object 
    file: No such file or directory

**Comment by Erdragh** [comment]
Yup, deleting everything in .local/share/multimc worked, I got it starting and can select the language, now to see if I can use the development channel

**Comment by Erdragh** [comment]
Yup updating now works aswell. Seems as though at some point the extracting from the archive went wrong, probably when using the AUR version. Lesson learned.

I don't know if I should close this Issue here, so please do so if there's nothing more. If there is please let me know :)
Have a nice evening/day/night/etc.

**Comment by phit** [comment]
cool, yeah definitely don't use the aur version and uninstalling it probably doesnt do anything so all the files it left were messing up the official pkgbuild
