### ISSUE TITLE
Curseforge link handler

### ISSUE THREAD

**Issue by SurmanPP** [MultiMC/Launcher#4407]
### Role

I use curseforge for getting mods.(modpacks)

### Suggestion

Register multimc as handler for the curseforge:// links (if wanted).

### Benefit

It would allow to use the install button on the courseforge page.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/3647
