### ISSUE TITLE
MultiMC froze when launching instance

### ISSUE THREAD

**Issue by lt-shy-john** [MultiMC/Launcher#4411]
### Operating System

Windows

### Description of bug

When I tried to click on one of the instances today, MultiMC just went frozen and I observed that the RAM usage went flatten. No crash logs were produced by MultiMC/ Minecraft but I have to kill the process all the time. 

FYI, this only happens in one of my instances. I can play it last night but not now. 

My computer spec:
* Windows 10
* MultiMC ver. 0.6.14-3001 on win32

### Steps to reproduce

1. Open MultiMC and click on the problem instance
2. Click on "Launch"/ "Launch Offline"/ "Edit Instance"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
open the instance in explorer and go in its logs folder, I suspect you will find a very large log file there, delete it
see https://github.com/MultiMC/Launcher/issues/4228
