### ISSUE TITLE
Add LWJGL 3.3.0

### ISSUE THREAD

**Issue by ShayBox** [MultiMC/Launcher#4412]
### Role

I play Minecraft on a M1 Mac or with a High Polling keyboard

### Suggestion

Add LWJGL 3.3.0 support to meta-multimc

### Benefit

So I can play on my M1 Mac with my High Polling keyboard

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

LWJGL 3.3.0 Added support for ARM (M1 Macs) and also fixes an issue with high polling rate keyboards dropping inputs, I get this would be an experimental version and not the default, but having the option would be great so I don't have to manually edit the json and download the libraries. The game runs just fine in my and others testing, compared to not running at all with 3.2.2 or losing more than half inputs.

**Comment by phit** [comment]
Mojang does not support ARM and consequently MultiMC doesn't either, this will be a thing if Mojang chooses to add M1 support.
