### ISSUE TITLE
LabyMod being unable to access my mic when using MultiMC

### ISSUE THREAD

**Issue by rlelchev** [MultiMC/Launcher#4413]
### Operating System

Linux

### Description of bug

When using the official minecraft launcher, it works fine, but when I launch Minecraft with MultiMC, LabyMod's voicechat addon is unable to access any of my microphones. Any help? This is the part of the minecraft logs, regarding this issue - [the Minecraft logs](https://campfirebg.eu5.org/upload/linux/voicechat.log)

### Steps to reproduce

Install LabyMod and the voicechat addon and try to select a microphone.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. Please report this to LabyMod and/or ask them for support.

**Comment by rlelchev** [comment]
The thing is, that i asked on LabyMod's discord first, but they do not support MultiMC. I tried posting it here and then again I cannot find a fix. This reminds me of the times i went up to my mother and asked her if I could play on my tablet. Sometimes she says ask your dad. I go up to my dad and he tells me to ask my mother.

**Comment by phit** [comment]
I asked a Labymod team member before closing this, they said its on their end. All MultiMC does is launch the game, if it works with vanilla maybe try matching Java version to the vanilla launcher.

**Comment by rlelchev** [comment]
I made the minecraft-launcher use the system jvm instead of the bundled version and it didn't change anything. I tried changing MultiMC's java version, but again it didn't change anything.
