### ISSUE TITLE
Create: Above and beyond 

### ISSUE THREAD

**Issue by Geoid29** [MultiMC/Launcher#4415]
### Operating System

Windows

### Description of bug

I tried downloading Create: Above and beyond modpack multiple times but it's just stuck failed to load mods 

Here's the crash report
https://paste.ee/p/4zc6s
![image](https://user-images.githubusercontent.com/97341955/148643033-5da76ed2-206f-4a47-8eba-236178ba2423.png)

### Steps to reproduce

Download Create: Above and beyond modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
