### ISSUE TITLE
MY mutiMC just crashes randomly

### ISSUE THREAD

**Issue by SantiioYT** [MultiMC/Launcher#4418]
### Operating System

Windows

### Description of bug

My MultiMC game (so like minecraft) just randomly crashes
log
https://paste.ee/p/h31IH

### Steps to reproduce

idk
heres the log
https://paste.ee/p/h31IH

### Suspected cause

Idk
heres the log
https://paste.ee/p/h31IH

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
