### ISSUE TITLE
says im not using java 17, but i am?

### ISSUE THREAD

**Issue by WaterL0gged** [MultiMC/Launcher#4422]
### Operating System

Windows

### Description of bug

whn i try to launch 1.18 with java 17 i get this error message, but im already using java 17 

"Minecraft 1.18 Pre Release 2 and above require the use of Java 17"

### Steps to reproduce

launch by selecting 1.18 or 1.18.1 with java 17 installed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#setting-up-java-in-multimc
