### ISSUE TITLE
I am already over 18 years old but MultiMC says I'm not and I can't login

### ISSUE THREAD

**Issue by PopDJHi** [MultiMC/Launcher#4423]
### Operating System

macOS

### Description of bug

When I pasted the link, the webpage says that I'm logged on and I can leave, but when I return to MultiMC, it says that i'm not over 18 years old and can't play Minecraft, but I'm already over 18 years old. People in the Discord told me to contact MS but I don't think that is necessary.

### Steps to reproduce

Click "Accounts"
Click "Add Microsoft Account"
Paste the link
Login to Microsoft

### Suspected cause

Maybe MultiMC is not refreshing the data from Microsoft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
If your account age is over 18 and you are still having this issue there's nothing we can do, MultiMC just returns the status from Microsoft.
