### ISSUE TITLE
MultiMC failing to start Minecraft using onesix launcher

### ISSUE THREAD

**Issue by Morris-pi** [MultiMC/Launcher#4427]
### Operating System

Linux

### Description of bug

When trying to launch an instance of minecraft (except vanilla) [this](https://paste.ee/p/od62i) error message appears. Tested on RLCraft from curseforge and Technic and also on PO3 from curseforge and imported from a .zip file. This may be a User Error as I am brand new to MultiMC.

### Steps to reproduce

Whenever a non-vanilla instance is run, Minecraft fails to launch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use Java 8 for anything older than 1.17 https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older
