### ISSUE TITLE
Mod Pack version is not defaulted into Instance name

### ISSUE THREAD

**Issue by ByProxy** [MultiMC/Launcher#4430]
### Operating System

Windows

### Description of bug

Most recent stable version, released feature #4185. It states that the Mod Pack version is now defaulted into the instance name.

When creating an instance, the name defaults to using the Minecraft version.

**Expected Result**:
Mod Pack name + Mod Pack version

**Actual Result**:
Mod Pack name + Minecraft version

### Steps to reproduce

Create any new Mod Pack instance

### Suspected cause

Misunderstanding of what was meant in the original feature request.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
can you provide an example?

**Comment by ByProxy** [comment]
![image](https://user-images.githubusercontent.com/265632/149808221-b9d8c3fd-54ac-4ecf-b9c9-8e67e1de14bb.png)

**Comment by ByProxy** [comment]
Resulting Instance
![image](https://user-images.githubusercontent.com/265632/149808464-e13afb0c-9c5d-49e1-b337-9d8b2c560a28.png)

**Comment by phit** [comment]
that's the name of the pack from CurseForge, the feature is currently only supported for ATL and FTB packs, since Curseforge versions are nonsensical and usually just the zip filename.
