### ISSUE TITLE
MultiMc not working

### ISSUE THREAD

**Issue by StefanMenssen** [MultiMC/Launcher#4435]
Hey guys, 

just downloaded multimc, but i cannot open any of the premade modpacks. for example iskalls Vault Hunter. Here is my log code: https://paste.ee/p/hkmoM

**Comment by phit** [comment]
this is a Forge issue, downgrade Java 8 https://github.com/McModLauncher/modlauncher/issues/91

**Comment by StefanMenssen** [comment]
I cannot find where I can downgrade java?

**Comment by phit** [comment]
You can download older versions directly from Oracle at https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html
but those require a login, so I would recommend getting an older version from a different Java vendor like Azul instead
https://www.azul.com/downloads/?version=java-8-lts&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk

**Comment by StefanMenssen** [comment]
which version would you recommend as not to go with one thats too old or too young?

**Comment by phit** [comment]
312/313 is the newest release that works afaik
