### ISSUE TITLE
I can't launch instances

### ISSUE THREAD

**Issue by SkaarlMarx** [MultiMC/Launcher#4438]
### Operating System

Windows

### Description of bug

When I try to launch the instance, I get errors.

### Steps to reproduce

Launcher modes that I have in the instance:
![unknown (1)](https://user-images.githubusercontent.com/98092509/150328138-472629fb-bed8-4101-ad02-43d985c5637c.png)
Version: 
![unknown (2)](https://user-images.githubusercontent.com/98092509/150328185-d8a3d57a-2cf5-4c23-bc02-1fee841f5471.png)
The error: https://paste.ee/p/ik8WM

### Suspected cause

The first time I tried to launch the instance the error said that it needed the latest version of Java which was Java 17. I installed Java 17 afterward and got a different error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
