### ISSUE TITLE
Exit Code -1

### ISSUE THREAD

**Issue by Dragonista1** [MultiMC/Launcher#4439]
### Description of bug

When I boot up a modpack it shows with an exit code of -1

Exiting with -1
Process exited with code -1

### Steps to reproduce

?

### Suspected cause

I feel its due to me downloading the launcher multiple times on accident.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
