### ISSUE TITLE
Failed to launch instance

### ISSUE THREAD

**Issue by SkyDreamGFX** [MultiMC/Launcher#4443]
### Operating System

Linux

### Description of bug

Hi guys,

I have an error when trying to launch an instance with MultiMC, here is the error: https://pastebin.com/uHN9rCKa

This happens with every instance/modpack. When running Minecraft with the official launcher it works for me flawlessly. Could you please assist?

I am using the git version. 

### Steps to reproduce

1. Launch MultiMC
2. Launch an Instance
3. Not able to launch the instance since the error appears

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
