### ISSUE TITLE
Java8 321 has issues with forge 1.7.10 (perhaps others)

### ISSUE THREAD

**Issue by bombcar** [MultiMC/Launcher#4444]
### Operating System

Windows

### Description of bug

Windows auto updated a user to Java8 u321 which hit: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9532

### Steps to reproduce

Latest mutlimc, latest Java8 u321 set as main java, try to run a 1.7.10 pack that uses awt (in this case gtnh 2.1.2.0). 

### Suspected cause

This is the same as https://github.com/McModLauncher/modlauncher/issues/91 and apparently can be fixed in the launcher as such: https://github.com/McModLauncher/modlauncher/pull/92/files

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
no it needs to be fixed by Forge, nothing for MultiMC to do about it, just use an older Java version until Forge is fixed
