### ISSUE TITLE
[1.1 - 1.2.5] Cannot take screenshots on window sizes larger than default (854x480)

### ISSUE THREAD

**Issue by octanervoc** [MultiMC/Launcher#4445]
### Operating System

Linux

### Description of bug

The following error is displayed on console upon attempting to take a screenshot on a larger than default window size:

```
java.lang.IllegalArgumentException: Number of remaining buffer elements is 1229760, must be at least 1617363. Because at most 1617363 elements can be returned, a buffer with at least 1617363 elements is required, regardless of actual returned element count
	at org.lwjgl.BufferChecks.throwBufferSizeException(BufferChecks.java:162)
	at org.lwjgl.BufferChecks.checkBufferSize(BufferChecks.java:189)
	at org.lwjgl.BufferChecks.checkBuffer(BufferChecks.java:230)
	at org.lwjgl.opengl.GL11.glReadPixels(GL11.java:2450)
	at zh.a(SourceFile:46)
	at zh.a(SourceFile:26)
	at net.minecraft.client.Minecraft.y(SourceFile:842)
	at net.minecraft.client.Minecraft.x(SourceFile:790)
	at net.minecraft.client.Minecraft.run(SourceFile:671)
	at java.lang.Thread.run(Thread.java:748)
```

I tested it on many MC versions, and this does not happen even on 1.0.0, only on the versions between 1.1 and 1.2.5 (inclusive). Window prints have been attached below:

![Screenshot_2022-01-22_14-50-36](https://user-images.githubusercontent.com/98230395/150649950-8db0ae61-3abc-4c48-82f8-ec50f00f33a4.png)
![Screenshot_2022-01-22_14-50-13](https://user-images.githubusercontent.com/98230395/150649949-140c674d-dcd8-420a-b721-2817a8b04426.png)

Changing to another LWJGL version does not solve this. I've also used JRE 7 and it also didn't solve it. Java 1.8.0_312 will take screenshots perfectly fine for all other full release MC versions (1.0.0 and 1.3.1+).

### Steps to reproduce

1. Install a 1.2.5 instance;
2. Create a new world;
3. Adjust to a larger window size;
4. Take a screenshot (F2).

### Suspected cause

I have no idea. This happens on the base game, no mods need to be installed for this error to occur. What is strange is that, again, none of this happens on 1.0.0, only on 1.1 - 1.2.5.

**EDIT:** 1229760 = (854*480)*3. Is this number of buffer elements hardcoded into MultiMC, perhaps?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. We can't fix issues in the game.
