### ISSUE TITLE
Forge 1.16.5 don't launch

### ISSUE THREAD

**Issue by SmallGolem** [MultiMC/Launcher#4446]
### Operating System

Windows

### Description of bug

Minecraft 1.16.5 launch if forge isn't installed but if forge if installed, minecraft crash.

[pasbin](https://paste.ee/p/6RV6j)

### Steps to reproduce

- Create a new instance of minecraft 1.16.5
- Install forge in this instance
- Launch this instance

### Suspected cause

This bug provider is Onesix.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
forge is broken with java 321+, download an older version of Java 8 and swithc to that e.g.  https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk

**Comment by SmallGolem** [comment]
java 8 is already use by MultiMC

**Comment by SmallGolem** [comment]
java 8 is already use by MultiMC

**Comment by SmallGolem** [comment]
![image](https://user-images.githubusercontent.com/56472916/150653263-f2cb15df-5429-4de6-b3ca-4aa7f0bee829.png)

**Comment by phit** [comment]
yes that java version is too new, use java 8 update 312 or older

**Comment by SmallGolem** [comment]
ok, tanks

**Comment by SmallGolem** [comment]
I test but nothing change

[pastbin](https://paste.ee/p/DiJwQ)

**Comment by phit** [comment]
you are using 322, thats still too new

**Comment by SmallGolem** [comment]
> forge est cassé avec java 321+, téléchargez une ancienne version de Java 8 et passez à celle-ci, par exemple [https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show -old-builds=true#download-openjdk](https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk)

i have use this link

**Comment by phit** [comment]
yes and then you downloaded the latest version instead of downloading the older 312 version

**Comment by SmallGolem** [comment]
oh, ok
