### ISSUE TITLE
Minecraft instance unable to use dedicated gpu when using prime-run wrapper

### ISSUE THREAD

**Issue by Snakespeed** [MultiMC/Launcher#4455]
### Operating System

Linux

### Description of bug

When using a laptop with a discrete NVIDIA GPU, the minecraft instance is unable to use the discrete GPU instead of the integrated GPU (as seen in the log and F3) when using the prime-run command to offload to the discrete GPU

### Steps to reproduce

- Install MultiMC
- Set wrapper command to "prime-run" (no quotes)
- Run game instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what is the full wrapper command you are using and please post your log

**Comment by Snakespeed** [comment]
Had to put the full path of the command as /usr/bin/prime-run
