### ISSUE TITLE
Can't install a mod

### ISSUE THREAD

**Issue by iambeingtracked** [MultiMC/Launcher#4459]
### Operating System

Linux

### Description of bug

This mod is not letting me launch minecraft https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/files/3367098
It says that i don't have fabric

### Steps to reproduce

Make a 1.18.1 instance and install latest fabric. Then install this mod https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/files/3367098. And in the logs it shows that i don't have fabric.

### Suspected cause

I don't really know. It says that i have no fabric even tho i tried other versions.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need fabric api https://www.curseforge.com/minecraft/mc-mods/fabric-api
