### ISSUE TITLE
Combat update 1.16 of Minecraft does not use the correct Intermediary Mappings of fabric loader

### ISSUE THREAD

**Issue by Lolothepro** [MultiMC/Launcher#4465]
### Operating System

Windows

### Description of bug

Combat update 1.16 of Minecraft does not use the correct Intermediary Mappings of fabric loader.

### Steps to reproduce

Used version 1.16 combat-6 with fabric loader

### Suspected cause

Correct:

![image](https://user-images.githubusercontent.com/68275908/151624787-722a4367-123a-4761-aff5-03ed615dfda0.png)

Not correct:

![image](https://user-images.githubusercontent.com/68275908/151624850-c40cb67a-7686-4a5a-aa66-6ab51948e5fc.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
on first glance this seems correct, we can't just assume that the combat-3 mappings are compatible

**Comment by Lolothepro** [comment]
https://github.com/rizecookey/intermediary

This person did the "intermediary mappings", but I don't know if it's good, but if it is, it would be interesting to see the difference between the two

**Comment by phit** [comment]
we can't just add mappings from random people, we use the official mappings provided by fabric and their api
