### ISSUE TITLE
"Process exited with code -1,"

### ISSUE THREAD

**Issue by killme69420** [MultiMC/Launcher#4466]
### Description of bug

Running Forge on any version crashes about 2 seconds upon opening, with the same logs each time. I have tried updating Java and switching it, yet the issue still persists. It worked on Fabric and Vanilla yet never works for Forge.

logs: https://paste.ee/p/MDPEX

_No response_

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by killme69420** [comment]
i forgot to add the logs: https://pastebin.com/03KE3xU5

**Comment by GAMELXRD** [comment]
I totally agree.

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk

**Comment by GAMELXRD** [comment]
Thank you!
