### ISSUE TITLE
How to build for Void Linux Musl. 

### ISSUE THREAD

**Issue by rustzz** [MultiMC/Launcher#4468]
void-packages has the MultiMC 0.6.13 package but does not support Microsoft Accounts. I need latest version of the launcher. How to build for musl?

**Comment by phit** [comment]
you're on your own with that, maybe try #dev-talk in our discord for support

**Comment by rustzz** [comment]
ok, I understand that, i need to enter my Microsoft APPID in the notsecrets/Secrets.cpp file
