### ISSUE TITLE
Linux 5.15.16 - 64bit - MultiMC 0.6.14-2998 - Vanilla Minecraft all versions - Black screen

### ISSUE THREAD

**Issue by thedt** [MultiMC/Launcher#4469]
System Info
> OS: Manjaro Linux x86_64 
> Kernel: 5.15.16-1-MANJARO 
> Packages: 1499 (pacman), 5 (flatpak) 
> Shell: bash 5.1.16 
> Resolution: 1920x1080 
> DE: Plasma 5.23.5 
> WM: KWin 
> WM Theme: Breeze 
> Theme: Breeze Dark [Plasma], Breath-Dark [GTK3] 
> cons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
> Terminal: yakuake 
> CPU: AMD FX-8350 (8) @ 4.013GHz 
> GPU: NVIDIA GeForce RTX 2060 Rev. A 
> Memory: 5167MiB / 32002MiB

MultiMC Info
> Version: 0.6.14-2998
> Installed with Lutris

Java Info
> Version: 17.0.1 64bit
> Version 1.8 for Minecraft version 1.12.2

Mod Info
> No mods

Steps I've tried
> Making a new instance for each of the following versions and than launching 1.18.1, 1.17.1, 1.12.2
> Using the system installation of GLFW - package glfw-x11 (3.3.6-1)
> 

Issue:
> When I launch any version of vanilla Minecraft, the game will launch but it'll just show a blank black box in the window of the game.

Minecraft Log:
> https://pastebin.com/AXDGJdwu

If more info is needed let me know what you need.

**Comment by phit** [comment]
that log doesn't work <https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#uploading-logs>

**Comment by thedt** [comment]
Oh gotcha so I hit the upload button.
Here is the link it gave me: https://paste.ee/p/zLxOJ

**Comment by RewardedIvan** [comment]
Why install it whit lutris just use the aur package

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you need further support, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
