### ISSUE TITLE
Latest dev-version doesn't launch the game because it can't download a component from remote server

### ISSUE THREAD

**Issue by Raphoulfifou** [MultiMC/Launcher#4471]
### Operating System

Windows

### Description of bug

the game doesn't launch and send this message in console 

Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://meta.multimc.org/v1/index.json
Job 'Download of meta file org.lwjgl3/3.2.2.json' failed to process:
https://meta.multimc.org/v1/org.lwjgl3/3.2.2.json
Job 'Download of meta file net.minecraft/1.18.1.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/1.18.1.json
Job 'Download of meta file net.fabricmc.intermediary/1.18.1.json' failed to process:
https://meta.multimc.org/v1/net.fabricmc.intermediary/1.18.1.json
Job 'Download of meta file net.fabricmc.fabric-loader/0.12.12.json' failed to process:
https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.12.12.json

### Steps to reproduce

get the latest dev version (0.6.14-developp-3186) and launch an instance in 1.18.1

### Suspected cause

i have no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide your log https://github.com/MultiMC/Launcher/wiki/Feedback#multimc-bugs

**Comment by Raphoulfifou** [comment]
[latest.log](https://github.com/MultiMC/Launcher/files/7966458/latest.log)

**Comment by phit** [comment]
thats not your multimc log.. please read the page section I linked

**Comment by Raphoulfifou** [comment]
Ah yep my bad.
https://paste.ee/p/A9NZ8

**Comment by phit** [comment]
still didn't read

**Comment by Raphoulfifou** [comment]
wait is it the MultiMC-0.log / MultiMC-1.log ? Must admit I don't see the difference between these logs

**Comment by dragonmaus** [comment]
`MultiMC-1.log` is just the previous version of `MultiMC-0.log`, rotated out of the way in case you need to reference it.

The most recent log is always `MultiMC-0.log`.

**Comment by Raphoulfifou** [comment]
Ok so this is the one needed ?

**Comment by phit** [comment]
yes, as the wiki page says..

**Comment by Raphoulfifou** [comment]
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/7966524/MultiMC-0.log)
Ok this should be it

**Comment by phit** [comment]
ok so lots of errors in that, looks like there's things in your system blocking network and file access like a broken antivirus, disable whatever is doing that or whitelist multimc
