### ISSUE TITLE
Can't connect over LAN, received string length is longer than max allowed

### ISSUE THREAD

**Issue by PhilHibbs** [MultiMC/Launcher#4472]
### Operating System

Windows

### Description of bug

When connecting to each other's LAN games, both machines fail with "Received string length is longer than max allowed (22>16)". When I use the vanilla launcher to connect to my friend's LAN game, it works. The hosting machine sees "_xxx_ has joined the world" and "_xxx_ has left the world" or words to that effect, I didn't note the exact text.

We are both using the latest MultiMC with Minecraft 1.18.1 and I have tried creating a fresh instance on each.

Both machines are Windows 10, one is a cheap HP model, the other is a brand new Clevo gaming laptop. 

I have installed the Mojang launcher on my machine, and with that, I can connect to my friend's world launched with MultiMC.

### Steps to reproduce

- Set up a vanilla 1.18.1 instance on each machine
- Load up the game on one, and Open to LAN
- Connect from the other machine
- Fails with "Received string length is longer than max allowed ( 22>16)"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
logs from both instances please <https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#uploading-logs>

**Comment by PhilHibbs** [comment]
Will do, but can't until the week-end at the earliest.

**Comment by DeusMos** [comment]
I have the exact same problem other than mine is modded, and all linux. here are my logs.

https://paste.ee/p/O6gFL

**Comment by phit** [comment]
@DeusMos please don't take other people's issues your log doesn't even have the same error nor has Realms anything to do with LAN play

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
