### ISSUE TITLE
Error: Could not create the Java Virtual Machine, Error: a fatal exception has occurred. program will exit

### ISSUE THREAD

**Issue by Ciclone151** [MultiMC/Launcher#4479]
### Description of bug

Whenever I try to open MULTIMC the message Error: Could not create the Java Virtual Machine, Error: a fatal exception has occurred. program will exit,

### Steps to reproduce

I've tried uninstalling and installing java, putting an older version of java and even messing with the environment variables, but nothing worked.

### Suspected cause

MULTIMC is out of date

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
MultiMC doesn't require Java to launch, please provide reproduction steps.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.

**Comment by Ciclone151** [comment]
I just discovered one of the problems with my MultiMC without FORGE it runs, but with forge installed it doesn't work no matter what version of forge I try to put
