### ISSUE TITLE
Test failed successfully 

### ISSUE THREAD

**Issue by NotADinosaur** [MultiMC/Launcher#4481]
### Operating System

Windows

### Description of bug

![image](https://user-images.githubusercontent.com/76700400/152078663-435f6a1b-92ba-41c7-8dd7-1cccfe173be6.png)

### Steps to reproduce

run a version java test

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
I believe that's fixed in the dev builds already.

Just shows we need a new stable build.
