### ISSUE TITLE
what should I do??

### ISSUE THREAD

**Issue by cannogas** [MultiMC/Launcher#4483]
### Description of bug

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.156.71]

session.minecraft.net resolves to:
    [52.1.29.34, 18.210.95.126, 34.231.157.213]

textures.minecraft.net resolves to:
    [13.226.31.19, 13.226.31.90, 13.226.31.125, 13.226.31.7]

api.mojang.com resolves to:
    [65.8.209.24]

Minecraft folder is:
C:/Users/kauan/Downloads/MultiMC/instances/Dark Age 1.2.1/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/kauan/Downloads/MultiMC/instances/Dark Age 1.2.1/natives

Libraries:
  C:/Users/kauan/Downloads/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/kauan/Downloads/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/kauan/Downloads/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] aether-1.12.2-v1.5.2
  [✔️] ancientwarfare-1.12.2-2.7.0.772
  [✔️] architecturecraft-1.12-3.98
  [✔️] astikorcarts-1.12.2-0.1.2.7
  [✔️] AutoRegLib-1.3-32
  [✔️] backpack-3.0.2-1.12.2
  [✔️] BaseMetals-1.12-2.5.0-beta5.214
  [✔️] BetterFps-1.4.8
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] Bloodmoon-MC1.12.2-1.5.3
  [✔️] Ceramics-1.12-1.3.7
  [✔️] Chunk Pregenerator V1.12-2.4E
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CraftTweaker2-1.12-4.1.20.586
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] CustomStartingGear-1.12-1.2.0.9-universal
  [✔️] CyclopsCore-1.12.2-1.6.6
  [✔️] davincisvessels-1.12-6.340-full
  [✔️] deuf-1.1-1.12.2
  [✔️] DungeonTactics-1.12.2-0.15.9
  [✔️] Farseek-1.12-2.5
  [✔️] Flopper-1.12.2-1.0.3
  [✔️] FTBLib-5.4.7.2
  [✔️] Geolosys-1.12.2-2.2.6
  [✔️] gravestone-1.10.3
  [✔️] hexlands-1.9.0
  [✔️] HorsePower-1.12.2-2.6.4.74
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] Inspirations-1.12.2-0.2.9
  [✔️] InventoryTweaks-1.63
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.301
  [✔️] JJ Coats of Arms 1.12-1.12.2-v1.0.11
  [✔️] LibraryEx-1.12.2-1.1.3
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] millenaire-8.1.0
  [✔️] minecolonies-1.12.2-0.11.804-RELEASE-universal
  [✔️] MobDismemberment-1.12.2-7.0.0
  [✔️] modtweaker-4.0.18
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] movingworld-1.12-6.353-full
  [✔️] MTLib-3.0.6
  [✔️] NetherEx-1.12.2-2.1.8
  [✔️] phosphor-forge-mc1.12.2-0.2.7-universal
  [✔️] Quark-r1.6-179
  [✔️] randompatches-1.12.2-1.22.1.7
  [✔️] reauth-3.6.0
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] roost-1.12.2-2.0.10
  [✔️] RTFM-MC1.12-1.0.1.4
  [✔️] rustic-1.1.2
  [✔️] ScalingHealth-1.12.2-1.3.34135
  [✔️] SilentLib-1.12.2-3.0.14168
  [✔️] Streams-1.12-0.4.8
  [✔️] Surge-1.12.2-2.0.79
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] ToroQuestRevamped-9-22-2020r
  [✔️] trade-1.0.4
  [✔️] va-1.12.2-1.5.5
  [✔️] VanillaFix-1.0.10-150
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] YABBA-1.1.2.54
  [✔️] zombieawareness-1.12.1-1.11.16

Params:
  --username  --version MultiMC5 --gameDir C:/Users/kauan/Downloads/MultiMC/instances/Dark Age 1.2.1/minecraft --assetsDir C:/Users/kauan/Downloads/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms200m, -Xmx2000m, -Duser.language=en]

Minecraft process ID: 9952

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.
Clipboard copy at: 02 Feb 2022 19:52:36 -0300

### Steps to reproduce

just installed a mod pack and happened

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by zeroxoneafour** [comment]
This isn't a bug. Switch the instance to Java 8 and don't ask things like this in the GitHub.

**Comment by zeroxoneafour** [comment]
Not trying be rude, but this is probably the worst GitHub issue I have ever seen in my life.

**Comment by tracinnn** [comment]
> This isn't a bug. Switch the instance to Java 8 and don't ask things like this in the GitHub.

I had this exact issue... how do you do that?

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by tracinnn** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

I am still getting the same issue. I have never had issues before. This all happened when I updated java then it didnt work. I uninstalled it and reinstalled and same issue. I followed the instruction in this link

**Comment by phit** [comment]
Forge is broken with Java 8 Update 321 or newer
You need an older Java 8 version, e.g. 8u312 you can find downloads here https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk
