### ISSUE TITLE
Modpacks no work

### ISSUE THREAD

**Issue by LarrytheTurtle23** [MultiMC/Launcher#4484]
### Operating System

macOS

### Description of bug

I get a new modpack, everything checks out and all that. I try to launch the game, but it doesn't launch
![Screen Shot 2022-02-02 at 6 14 55 PM](https://user-images.githubusercontent.com/62360353/152270635-6ce08fd1-52c5-4a02-9e87-1e558af156a3.png)
What does any of this mean

I have Java, Vanilla works fine

### Steps to reproduce

Get modpack
Try to launch
Cry

### Suspected cause

Bad computer specs?????

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Pectacular** [comment]
Have you confirmed that this is an issue with MultiMC and not the modpack?

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by LarrytheTurtle23** [comment]
> Have you confirmed that this is an issue with MultiMC and not the modpack?

Yes, I used it with the official launcher before just fine
