### ISSUE TITLE
inabilety te re-enable instance toolbar

### ISSUE THREAD

**Issue by verified-gamer** [MultiMC/Launcher#4487]
### Operating System

Windows 10

### Description of bug

once disabled you cant re-enable the instance toolbar

### Steps to reproduce

right click on the instance toolbar and disable the instance toolbar and the news toolbar,
you are now unable to click on the instance toolbar to bring the menu up again

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
right click the top menu bar

**Comment by verified-gamer** [comment]
oh thanks
