### ISSUE TITLE
Failed to download forge libraries

### ISSUE THREAD

**Issue by rustzz** [MultiMC/Launcher#4489]
**Logs**
```
MultiMC version: 0.6.14-3001


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.156.252.68]

session.minecraft.net resolves to:
    [34.231.157.213, 18.210.95.126, 52.1.29.34]

textures.minecraft.net resolves to:
    [65.9.49.103, 65.9.49.23, 65.9.49.113, 65.9.49.119]

api.mojang.com resolves to:
    [108.156.255.89]


Minecraft folder is:
D:/MultiMC/instances/1.7.10/.minecraft


Java path is:
D:/Java/1.8/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.


Не удалось обновить сборку по причине: Не удалось обновить игру: Не было возможности получить необходимые библиотеки.
Причина:
Не удалось обработать рабочую задачу 'Библиотеки для сборки 1.7.10':
https://maven.minecraftforge.net/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
https://maven.minecraftforge.net/com/typesafe/config/1.2.1/config-1.2.1.jar
https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
https://maven.minecraftforge.net/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
https://maven.minecraftforge.net/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
https://maven.minecraftforge.net/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
https://maven.minecraftforge.net/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
https://maven.minecraftforge.net/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar


Clipboard copy at: 05 Feb 2022 12:26:16 +0500
```

When i go to `maven.minecraftforge.net` i get (screenshot)
![image](https://user-images.githubusercontent.com/74064444/152632944-48e4b17b-0778-4b9c-a889-273d0f527a8b.png)

**Comment by rustzz** [comment]
But directly download works
![image](https://user-images.githubusercontent.com/74064444/152633095-397ffafb-68df-44ba-b26a-d36ec0e4e941.png)

**Comment by phit** [comment]
open maven.minecraftforge.net in internet explorer or edge, restart multimc and try again

**Comment by rustzz** [comment]
multimc uses ie? why not wget or any. ok, empty page
![image](https://user-images.githubusercontent.com/74064444/152634556-e41d149a-e776-49cb-b3aa-2bc08baf3bba.png)

**Comment by rustzz** [comment]
i need update ie?

**Comment by phit** [comment]
no it doesn't use IE, it uses the Microsoft certificate store, which was probably missing the Let's Encrypt certificates needed to talk to Forge's server, which Windows automatically downloads if a website needs it, the page being blank is fine, restart MultiMC and try again

**Comment by rustzz** [comment]
i already update certs from lets encrypt

**Comment by phit** [comment]
then provide your MultiMC-0.log if it still doesn't work, preferably via https://gist.github.com/ or https://paste.ee/

**Comment by rustzz** [comment]
ok, i see ssl cert error. but
> i already update certs from lets encrypt. just yesterday
https://paste.ee/p/jmgCl

**Comment by rustzz** [comment]
i could install "windows 10" but i have screen glitches in it

**Comment by phit** [comment]
definitely looks like you are missing the ISRG Root X1, does this page work in internet explorer https://valid-isrgrootx1.letsencrypt.org/

**Comment by rustzz** [comment]
works, but images not loaded
![image](https://user-images.githubusercontent.com/74064444/152634950-bf2b9bba-77bc-4802-b32f-b05105eb5983.png)

**Comment by phit** [comment]
yeah sorry no idea then, something you'll have to figure out on your end, Windows 7 is very much dead, if 10 us causing issues with your hardware maybe try 8.1 it's still supported until next year
