### ISSUE TITLE
Forge 1.8.9 version 11.15.1.2318 is not launching, see logs

### ISSUE THREAD

**Issue by minecraftben** [MultiMC/Launcher#4490]
### Operating System

Windows

### Description of bug

Forge 1.8.9 version 11.15.1.2318 is not launching, it accepts all mods, then crashes and never launches the game; here is what is says

MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.59.75]

session.minecraft.net resolves to:
    [52.1.29.34, 34.231.157.213, 18.210.95.126]

textures.minecraft.net resolves to:
    [13.226.31.19, 13.226.31.90, 13.226.31.125, 13.226.31.7]

api.mojang.com resolves to:
    [99.84.40.162]

Minecraft folder is:
C:/Users/gaobe/Desktop/Games/Minecraft/instances/1.8.9 PVP Mods/.minecraft

Java path is:
C:/Users/gaobe/Desktop/jdk-17.0.2/bin/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/gaobe/Desktop/Games/Minecraft/instances/1.8.9 PVP Mods/natives

Libraries:
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  C:/Users/gaobe/Desktop/Games/Minecraft/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] [1.8.9] ArmorStatusHUD
  [✔️] [1.8.9] BlockOverlay-v2.1
  [✔️] [1.8.9] Crosshairmod-v0.5.1
  [✔️] [1.8.9] fncompassmod-1.0
  [✔️] [1.8.9] FPSModv2 PORT
  [✔️] [1.8.9] Powns Ghost Liquid Fix
  [✔️] [1.8.9] StatusEffectHUD
  [✔️] [1.8.9] Wings Mod-1.2
  [✔️] Autocorrect-1.1 (1.8.9)
  [✔️] AutoFriend-1.1_1.8.9
  [✔️] AutoGG-4.1.3 (1.8.9)
  [✔️] Autotip-3.0.1 [1.8-1.12.2]
  [✔️] chromapotions-1.8.9
  [✔️] ctjs-2.0.1-1.8.9
  [✔️] FastChat-1.0
  [✔️] FPS Booster 1.6.3
  [✔️] guiscale-1.8.9
  [✔️] Hypixel Autocomplete-1.1 (1.8.9)
  [✔️] Hytilities-1.0 (Beta 5)
  [✔️] ItemPhysic Lite 1.3
  [✔️] Keystrokes-8.1.2 (1.8.9)
  [✔️] Levelhead-8.0 (1.8.9)
  [✔️] LobbySounds-1.3.1 (1.8.9)
  [✔️] Motion Blur-2.1.2 (1.8.9)
  [✔️] NotEnoughUpdates-2.0.0
  [✔️] OldAnimationsMod-Animations & Cosmetics_2.6.5-mc_Forge1.8.9
  [✔️] OptiFine_1.8.9_HD_U_M5
  [✔️] Particle Mod
  [✔️] Patcher-1.8.0 (1.8.9)
  [✔️] Popup Events-1.3.2 (1.8.9)
  [✔️] Quickplay Premium 1.8.9-1.0.4
  [✔️] Quickplay-1.8.9-2.0.7
  [✔️] Quickreport
  [✔️] ResourcePackOrganizer++MC-1.8.9++v1.0.3
  [✔️] Scrollable Tooltips-1.4 (1.8.9)
  [✔️] Sidebar Mod Revamp
  [✔️] SkyblockAddons-1.6.1-for-MC-1.8.9
  [✔️] Skytils-1.1.2
  [✔️] Sound Subtitles-1.2.2 (1.8.9)
  [✔️] TimeChanger-1.0 (1.8.9)
  [✔️] TNT Time-1.1 (1.8.9)
  [✔️] Xaeros_Minimap_21.10.19_Forge_1.8.9
  [✔️] Zoomer-1.1

Core Mods:
  [✔️] [1.8.9] BspkrsCore

Params:
  --username  --version MultiMC5 --gameDir C:/Users/gaobe/Desktop/Games/Minecraft/instances/1.8.9 PVP Mods/.minecraft --assetsDir C:/Users/gaobe/Desktop/Games/Minecraft/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType  --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 10408

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

### Steps to reproduce

For me, I just launch the game and it happens, but it might not work for other people.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older
