### ISSUE TITLE
MultiMC Fails To Provide Proper Permissions to Allow Mic Access With Certain Mods on MAC

### ISSUE THREAD

**Issue by Virusnest** [MultiMC/Launcher#4491]
Using Mods That Require Mic Input Don't Work Because of a missing permission request in multimc, Launching Multimc In the macOS terminal allows the microphone request to appear as the Terminal has the correct permissions and multimc is running from it

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by phit** [comment]
for reference other mods have no problems requesting permission its up to mods to do whatever is needed for that https://github.com/MultiMC/Launcher/issues/2668

**Comment by Virusnest** [comment]
This is a multimc Issue as it requires a change to info.plist and correct application signing
