### ISSUE TITLE
MultiMC 0.6.14 error: Failed to load Minecraft 1.18.1 with mods and vanilla

### ISSUE THREAD

**Issue by zxcpivo** [MultiMC/Launcher#4492]
### Operating System

Windows

### Description of bug

I try start Minecraft 1.18.1 with Sodium and Sodium Extra and MC wrote me this:

		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		org_joml_joml: joml 1.10.2
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.9
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\User\MultiMC\instances\1.18.1\.minecraft\crash-reports\crash-2022-02-06_08.12.21-client.txt
Game closed with exit code -1

### Steps to reproduce

1. I install mods (This happens without mods) for optimization. 
2. Click on Play Offline.(because if I lick Play Online it cant download files.
3. Then everything as usual, and the game crashes before it has time to open.

### Suspected cause

I dont know(

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by zxcpivo** [comment]
help pls!

**Comment by zxcpivo** [comment]
heeeeelp

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
