### ISSUE TITLE
What do if I dont have C:\User\MultiMC\instantes\1.18.1\natives folder?

### ISSUE THREAD

**Issue by zxcpivo** [MultiMC/Launcher#4493]
### Operating System

Windows

### Description of bug

?

### Steps to reproduce

?

### Suspected cause

?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
it gets auto created each launch, if something is blocking it on your end, restart your pc
