### ISSUE TITLE
error: Minecraft 1.18 Pre Release 2 and above require the use of Java 17,          but im using java 17

### ISSUE THREAD

**Issue by SpyNoob170** [MultiMC/Launcher#4494]
### Description of bug

Crashing when launching my modpack. The logs:  MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.187.75]

session.minecraft.net resolves to:
    [34.231.157.213, 52.1.29.34, 18.210.95.126]

textures.minecraft.net resolves to:
    [13.225.198.8, 13.225.198.55, 13.225.198.113, 13.225.198.70]

api.mojang.com resolves to:
    [13.225.196.14]

Minecraft folder is:
C:/Users/felix/Desktop/MultiMC/instances/survival modpack/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_321/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_321, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/felix/Desktop/MultiMC/instances/survival modpack/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/felix/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/felix/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/felix/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/cpw/mods/securejarhandler/1.0.1/securejarhandler-1.0.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/cpw/mods/modlauncher/9.1.0/modlauncher-9.1.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/felix/Desktop/MultiMC/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  C:/Users/felix/Desktop/MultiMC/libraries/net/minecraftforge/fmlloader/1.18.1-39.0.66/fmlloader-1.18.1-39.0.66.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/felix/Desktop/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] alexsmobs-1.16.0
  [✔️] awesomedungeon-2.0.5 (1)
  [✔️] BiomesOPlenty-1.18.1-15.0.0.104-universal
  [✔️] castle_dungeons-3.2-1.18-forge
  [✔️] ChiselsBits-forge-1.18.1-1.2.79-universal
  [✔️] CraftTweaker-forge-1.18.1-9.0.45
  [✔️] create-mc1.18.1_v0.4d
  [✔️] Cyclic-1.18.1-1.6.10
  [✔️] DungeonCrawl-1.18.1-2.3.6
  [✔️] DungeonsArise-1.18.1-2.1.49d-beta (1)
  [✔️] DungeonsMod-1.18-1.4.61
  [✔️] FallingTree-1.18.1-3.2.0
  [✔️] findme-3.0.5-forge
  [✔️] FramedBlocks-4.2.0
  [✔️] jei-1.18.1-9.2.1.69
  [✔️] Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.9
  [✔️] physics-mod-2.6.7-mc-1.18-forge
  [✔️] Quark-3.0-334
  [✔️] repurposed_structures_forge-4.2.6+1.18.1
  [✔️] shulkerbox-1.18.1-1.0.0
  [✔️] soundphysics-forge-1.18.1-1.0.4
  [✔️] the-conjurer-1.18.1-1.1.1
  [✔️] ToolBelt-1.18-1.18.0
  [✔️] torohealth-1.18-forge-2
  [✔️] TravelersBackpack-1.18.1-7.0.1
  [✔️] vanilla-hammers-3.2.0-1.18.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/felix/Desktop/MultiMC/instances/survival modpack/.minecraft --assetsDir C:/Users/felix/Desktop/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 39.0.66 --fml.mcVersion 1.18.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20211210.034407

Window size: 854 x 480

Minecraft 1.18 Pre Release 2 and above require the use of Java 17
 

### Steps to reproduce

i just install these mods and it crashes 

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
read the log you posted, like literally just search for java

**Comment by YusufKhan-gamedev** [comment]
@phit incorrectly autodetecting java 1.8 instead of java 17 is a bug.

**Comment by dan55304** [comment]
I get the same error as OP: Minecraft 1.18 Pre Release 2 and above require the use of Java 17. My MacOS Java is version 1.8.0_131. As far as I can find out, that's the latest Mac version. So, what's the remedy?

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-117-and-newer
