### ISSUE TITLE
How to set a background image on a custom theme

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/Launcher#4497]
### Role

how to set background on custom theme

### Suggestion

how to set background on custom theme

### Benefit

how to set background on custom theme

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

how to set background on custom theme

**Comment by phit** [comment]
here's an example [custom_1.zip](https://github.com/MultiMC/Launcher/files/8026677/custom_1.zip)

**Comment by graytoowolf** [comment]
> 这是一个示例[custom_1.zip](https://github.com/MultiMC/Launcher/files/8026677/custom_1.zip)
![QQ截图20220214045439](https://user-images.githubusercontent.com/57069542/153774748-f6cccd3b-648e-4750-b14e-9a23b7022e76.png)
I downloaded the theme example and the settings have no effect.

**Comment by Loneattic** [comment]
try `InstanceView` selector

**Comment by graytoowolf** [comment]
> 试用`InstanceView`选择器

Thanks this can
