### ISSUE TITLE
Job "Libraries for instance ..." failed

### ISSUE THREAD

**Issue by Somemoron** [MultiMC/Launcher#4498]
### Operating System

Windows

### Description of bug

Shows this 
![image](https://user-images.githubusercontent.com/98904608/152902233-53acac36-f041-463e-b8ee-eef0680ab293.png)
when i make an instance and try to run it 

### Steps to reproduce

 make an instance and try to run it 

### Suspected cause

Maybe my java file is in the wrong place or something?
I'm new to this

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you get MultiMC?
