### ISSUE TITLE
Can't use Microsoft login

### ISSUE THREAD

**Issue by dezintgarecja** [MultiMC/Launcher#4499]
### Operating System

Linux

### Description of bug

Logging in with microsoft fails miserably:
After account's expiration and succesful auth on Microsoft's website, MultiMC says that it `Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Too Many Requests`.
Tried restarting MultiMC, logging in with a different profile (also expired), same results.

### Steps to reproduce

1. let account expire
2. go to microsoft auth page
3. auth
4. close page
5. get error

### Suspected cause

don't really know although it's probably not just a Linux thing (this is the first that it happened)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please try the dev version
![](https://cdn.discordapp.com/attachments/134843027553255425/855880510031003728/unknown.png)

**Comment by Leon5x** [comment]
That actually solves the problem for me. Thanks a lot!

**Comment by dezintgarecja** [comment]
worked, thanks
