### ISSUE TITLE
Failure to load any modpack/vanilla Minecraft instance after java update.

### ISSUE THREAD

**Issue by xellosmetallum** [MultiMC/Launcher#4500]
### Operating System

Windows

### Description of bug

Everytime I try to load one of the minecraft packs or vanilla it errors out after a brief loading screen with these errors. 

https://paste.ee/p/NmTte

### Steps to reproduce

Any instance installed from FTB/CurseForge/AT Launcher or Vanilla
Java Runtime ver 17.0.2 or Java 8.0_321
launch the instance with default arguments and settings in MultiMC

### Suspected cause

Something in the latest update of java causing issues with the way MultiMC launches instances. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
