### ISSUE TITLE
Account has expired - xbox authentication failed

### ISSUE THREAD

**Issue by michelledisraeli** [MultiMC/Launcher#4503]
### Operating System

Windows

### Description of bug

Unable to refresh account within MultiMC when expired, required to remove account, close MultiMC, launch Minecraft launcher, login through that, then reopen and confiure MultiMC. Using version 0.6.14, previous reported issues did not require use of the Minecraft Launcher to resolve.

### Steps to reproduce

1. configure MultiMC to use microsoft account
2. After period of usage, on attempting to start session receive notice that the Microsoft account session has expired
3. Refresh button on account does not work
4. Remove Microsoft account
5. Close MultiMC, ensuring process is terminated
6. reopening MultiMC and attempting to re-add the account results in the Microsoft authentication working but "xbox authentication failed" error message is displayed and account is not added
7. Close MultiMC as above
8. Launch the Minecraft Launcher
9. Log into Microsoft account through the Minecraft Launcher
10. XBOX authentication then completes within Minecraft Launcher
11. Reopen MultiMC and attempt to re-add the Microsoft account
12. Successfully able to add Microsoft account without any issues

### Suspected cause

MultiMC is unable to fully complete the XBOX authentication process.

Short term treatment: In the event of an XBOX authentication failure, error messages within MultiMC should direct the user to launch Minecraft directly via the Minecraft Launcher and authenticate using their Microsoft XBOX account

Long term treatment: Investigate if it is possible for MultiMC to successfully navigate all steps within MultiMC without needing use of an external launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by breadtard** [comment]
bump - same issue

**Comment by Keoo1711** [comment]
Same Issue. Unable to re-authenticate

**Comment by mben42** [comment]
Same issue

**Comment by CatPasswd** [comment]
Also facing this issue. However, I have also rebooted my machine, logged in via the Minecraft launcher, and am still unable to authenticate.

**Comment by Iresione** [comment]
To further clarify, the user end hackfix for this is dead simple, if annoying as hell:
You literally just launch the game while logged in on the vanilla launcher (if you can) and then reopen multimc and the link works.

**Comment by mben42** [comment]
> To further clarify, the user end hackfix for this is dead simple, if annoying as hell: You literally just launch the game while logged in on the vanilla launcher (if you can) and then reopen multimc and the link works.

It works, thank you!

**Comment by shinji257** [comment]
This is interesting because I did not have to do this.  I just deleted the account in MultiMC then added it back immediately after redoing the link.  It worked without all the other shenanigans that the rest of you had to go through.  With that said I would love a refresh button or relink button that when expired would start the link process again and just update the existing extry.

**Comment by BVengo** [comment]
> To further clarify, the user end hackfix for this is dead simple, if annoying as hell: You literally just launch the game while logged in on the vanilla launcher (if you can) and then reopen multimc and the link works.

Can confirm this fixed it for me too. Cheers :)
I'll be interested to know what's causing it and why this would fix it.

**Comment by bill88t** [comment]
Same here. Did try like 10 times to rebind.

```
111.613 D DeviceFlow::setLinked: true
111.613 D AuthFlow: "Logging in as an Xbox user."
111.614 D First layer of XBox auth ... commencing.
112.902 W AuthRequest::onRequestError: Error 302
112.903 W AuthRequest::onRequestError: Error string:  "Error transferring https://user.auth.xboxlive.com/user/authenticate - server replied: Bad Request"
112.903 W AuthRequest::onRequestError: HTTP status 400 "Bad Request"
112.904 W Reply error: QNetworkReply::ProtocolInvalidOperationError
112.904 C Task "MSAInteractive(0x7f94009d60)" failed:  "XBox user authentication failed."
```

**Comment by phit** [comment]
I don't see anything new in here that isn't covered by any of the previous auth issues, make sure you are using the [dev version](https://cdn.discordapp.com/attachments/134843027553255425/855880510031003728/unknown.png) of MultiMC other than that Microsoft seems to be having issues the last couple hours and the error handling isn't that great yet. See https://github.com/MultiMC/Launcher/issues?q=is%3Aopen+is%3Aissue+label%3AAuth

**Comment by desturr** [comment]
> ### Operating System
> Windows
> 
> ### Description of bug
> Unable to refresh account within MultiMC when expired, required to remove account, close MultiMC, launch Minecraft launcher, login through that, then reopen and confiure MultiMC. Using version 0.6.14, previous reported issues did not require use of the Minecraft Launcher to resolve.
> 
> ### Steps to reproduce
> 1. configure MultiMC to use microsoft account
> 2. After period of usage, on attempting to start session receive notice that the Microsoft account session has expired
> 3. Refresh button on account does not work
> 4. Remove Microsoft account
> 5. Close MultiMC, ensuring process is terminated
> 6. reopening MultiMC and attempting to re-add the account results in the Microsoft authentication working but "xbox authentication failed" error message is displayed and account is not added
> 7. Close MultiMC as above
> 8. Launch the Minecraft Launcher
> 9. Log into Microsoft account through the Minecraft Launcher
> 10. XBOX authentication then completes within Minecraft Launcher
> 11. Reopen MultiMC and attempt to re-add the Microsoft account
> 12. Successfully able to add Microsoft account without any issues
> 
> ### Suspected cause
> MultiMC is unable to fully complete the XBOX authentication process.
> 
> Short term treatment: In the event of an XBOX authentication failure, error messages within MultiMC should direct the user to launch Minecraft directly via the Minecraft Launcher and authenticate using their Microsoft XBOX account
> 
> Long term treatment: Investigate if it is possible for MultiMC to successfully navigate all steps within MultiMC without needing use of an external launcher
> 
> ### This issue is unique
> * [x]  I have searched the issue tracker and did not find an issue describing my bug.

hi. i had the same issue today. i logged in to my xbox account. then privacy settings. it wanted me to verify my phone number. i verified it. then tried to login again. it confirmed my xbox account.

**Comment by dashbarron** [comment]
> same. Use development version it fixes all this

Dev version didn't fix this for me months later. 

Have had ongoing login issues with launcher for years. Can't seem to find stable version that keeps login and then doesn't have authentication issues.

**Comment by topcassorole** [comment]
Same issue, but I'm having it on my phone whenever I try to log on to lifeboat

**Comment by milanmaricrock-eng** [comment]
Why
