### ISSUE TITLE
TLSv1.3 Support (Old OpenSSL)

### ISSUE THREAD

**Issue by DocterDum** [MultiMC/Launcher#4509]
### Operating System

Windows

### Description of bug

When trying to create an instance (Import from ZIP), if the path is a webserver which only accepts TLSv1.3, it fails

After temporarily enabling TLSv1.2 on the server, it downloads correctly

### Steps to reproduce

Open MultiMC
Create Instance
Import From ZIP
Insert link to TLSv1.3 only server
Click OK

### Suspected cause

Briefly discussed with AppleTheGolden in discord dev-talk channel on 1/10/2022 (MM/DD/YYYY), we believe the issue is caused by the old version of OpenSSL used in the windows executable.

If you need a file on a TLSv1.3 server to test you can use mine:
https://mcgeary.com.au/static/httpallow/Pixelmon.zip

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you can use the modern Windows builds if you need a more modern OpenSSL version

stable: https://files.multimc.org/downloads/mmc-stable-win32-5.15.2.zip
develop: https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip

**Comment by DocterDum** [comment]
Thanks @phit , that build worked perfectly. Are you aware if there are any plans to make this the default or is that's not possible?

**Comment by DocterDum** [comment]
Awesome, thanks for your help!
