### ISSUE TITLE
account profile contains keywords "No profile({gamertag})" making it exceed max legal length of 16 

### ISSUE THREAD

**Issue by 0xasim** [MultiMC/Launcher#4510]
### Operating System

MacOS Monterey
### Description of bug

I am first time using this xbox account. Somehow, in MultiMC, my profile contains keywords "No Profile({gamertag})" and is making me unable to to connect to a server. The server, i am trying to connect to is a Minecraft High-Performance Redstone Server 
https://github.com/MCHPR/MCHPRS

I tried changing my gamertag to still fit inside the limit but microsoft is asking premiums for shorter gamer tags

```
>>> len("No profile (a4s1m)")
18
```
<img width="709" alt="Screen Shot 2022-02-12 at 1 22 37 AM" src="https://user-images.githubusercontent.com/37139450/153666098-4662d48c-4a0d-4d16-8e01-82f384fd751b.png">

<img width="833" alt="Screen Shot 2022-02-12 at 1 10 49 AM" src="https://user-images.githubusercontent.com/37139450/153666117-3b91d74b-4f27-4cc3-9b6e-d394e898e08f.png">

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to setup your Minecraft account, and own the game to play
go to https://www.minecraft.net/en-us and login and then setup your profile

**Comment by 0xasim** [comment]
The profile's been set-up already and i am able to play game. The problem is when connecting to the local redstone high performance server, i can't connect with the profile because profile string is too long. However, if i connect in offline mode and enter a shorter profile name (as it asks in offline mode), it connects perfectly fine.

**Comment by phit** [comment]
the name is too long because you dont have a profile, the account you are logged in with either doesnt own the game or has no profile
