### ISSUE TITLE
Glfw crash if modpack has icon 

### ISSUE THREAD

**Issue by itsdinkd** [MultiMC/Launcher#4511]
### Description of bug

Any forge modlack that has a custom window icon and attempted to launch with MultiMC will get a glfw java crash. The only fix is to remove the mod trying to load the icon assets or remove the icons themselves. 

On 1.18.1 minecraft. The mod handling icons in this instance is its the little things 

This doesn't occur on any other launcher. 

### Steps to reproduce

Download Another Quality Modpack 3 or add itit and load custom windows icons 

Launch game using MultiMc

Crash 

### Suspected cause

Custom window icons and multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
logs?

**Comment by itsdinkd** [comment]
https://paste.ee/p/mw6c0

**Comment by phit** [comment]
thats a mod bug report it to the mod author, its not related to MultiMC but the Java version used, if I use the Java version shipped with vanilla it works fine

**Comment by itsdinkd** [comment]
Umm... doubt that. The modpack launches fine on GDlauncher and curseforge
launcher. It does not work however with multimc.

**Comment by itsdinkd** [comment]
So the people getting this crash are using a outdated Java version basically?

**Comment by phit** [comment]
no, probably newer and or just a different java vendor, the mod is just broken

**Comment by itsdinkd** [comment]
> no, probably newer and or just a different java vendor, the mod is just broken

the odd thing though is its able to launch just fine with curseforge / gdlauncher. what would be the reason for it crashing on multimc with it?

**Comment by phit** [comment]
because multimc doesnt use the java shipped by mojang it uses whatever the user tells it to

**Comment by itsdinkd** [comment]
> 

got it, thanks. I will open up an issue with ITIT
