### ISSUE TITLE
Mouse Lag Upon game starting

### ISSUE THREAD

**Issue by zxcvbnmasdfghjk7** [MultiMC/Launcher#4514]
### Operating System

Windows

### Description of bug

When I launch an instance of MultiMC. The mouse lags for me. When I enter the game, my fps is stable, but my mouse is lagging all over the place. Happens on any type of Minecraft version. 

### Steps to reproduce

1. Run MultiMC as a normal user.
2. Launch an instance. 

### Suspected cause

I have reached out on discord, they said it is some sort of mouse bug with a polling rate. However, even though I am using a trackpad, the mouse lag is still present.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
I tried to talk to you about this on Discord and you never replied, please keep it there. This page is for MultiMC issues and as far as I can tell there's no sign your issue is caused by MultiMC nor have you provided any logs so far.
