### ISSUE TITLE
1.16 c6 with fabric trying to access from YOUR mirrors

### ISSUE THREAD

**Issue by RewardedIvan** [MultiMC/Launcher#4515]
### Operating System

Windows, Linux

### Description of bug

Making an instance with the experimental update for 1.16 c6 and adding fabric should add fabric, but it's intermediary mappings don't work to well.

### Steps to reproduce

* make a new instance with the version 1.16 c6
* click the add fabric and any version (I used 0.11.6 btw)
* try to start it up

### Suspected cause

It might be reaching out to your mirrors, because the normal launcher works fine.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RewardedIvan** [comment]
This issue is not that unique, because I saw one closed like this, but it still should be fixed. Come on

**Comment by phit** [comment]
how are you installing fabric for that version? combat 6 isn't available in the official installer either

![image](https://user-images.githubusercontent.com/2097483/154351754-b21644f8-a2c0-4893-8ded-5183d768d586.png)

**Comment by RewardedIvan** [comment]
Oh, they used an modded installer for it. You said that your not gonna use random peoples code so it's not gonna get added \:
![09:38:25 22-02-20](https://user-images.githubusercontent.com/67065165/154861091-1b377680-fe3b-457d-a3f7-13aa56cf0245.png)
