### ISSUE TITLE
"Java binary not found" i need help

### ISSUE THREAD

**Issue by LegendarySkyrim** [MultiMC/Launcher#4516]
### Operating System

Windows

### Description of bug

Ok i am going to try to use much grammar as possible

So, I just installed MultiMc not long ago and I was going to play version 1.18 but I had to have Java 17.
So, I installed Java 17 and set it up, but it said there was an error, so i deleted my old java, so when I deleted my old Java i came back to it and it said "The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it." For some reason I just had the feeling i sussposed to delete my jars, so i deleted everything in my jars, and i tried going back on MultiMc but it still said the java binary wasn't found. I need help

### Steps to reproduce

1. Find a woman
2. Bring her to an bed
3. get her naked
4. seggs
5 couple months later she pregnant
6. baby

was i sussposed to put that?

### Suspected cause

I think its because Java 17 is missing something i dunno.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CharbelElBateh** [comment]
Did you update set up java correctly?
By setting it up I mean making sure the environment variables on your Device are correct?

**Comment by phit** [comment]
> Please fix the java path override in the instance's settings or disable it.

the solution is right there, see https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#setting-up-java-in-multimc

**Comment by Shiryu-cmd** [comment]
bro wtf did you write

**Comment by risknuc** [comment]
hahaahahahha wtf
