### ISSUE TITLE
Opening a particular world causes minecraft and multimc to freeze

### ISSUE THREAD

**Issue by MrRedstoneA1** [MultiMC/Launcher#4517]
### Operating System

Windows

### Description of bug

When opening a certain world, both minecraft and multimc freeze. This happened after I updated multimc to a developer version because I couldn't log in anymore. The world will open if I open another world first, close it and then open the world. I've searched everywhere for a fix but thus far it seems that I'm the only person experiencing this issue. This whole thing is really weird.

### Steps to reproduce

I don't think this can be reproduced. It's this one particular world that acts weird for no reason. 

### Suspected cause

Updating to the latest developer version of multimc caused the issue to surface. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MrRedstoneA1** [comment]
Here's the minecraft log from when it last happened. Since then I deleted the world and brought in a backup, went back to latest multimc release update and the issue hasn't happened again yet. Maybe the log can help prevent this issue in the future.
[2022-02-17-1.log](https://github.com/MultiMC/Launcher/files/8089653/2022-02-17-1.log)

**Comment by phit** [comment]
just a bug with rsgauges, nothing to do with mulitmc

> [11:05:19] [Server thread/ERROR] [FML]: A TileEntity rsgauges:gauge_entity(wile.rsgauges.blocks.BlockGauge$TileEntityGauge) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
