### ISSUE TITLE
Token Recognition Error

### ISSUE THREAD

**Issue by CobaltStarr** [MultiMC/Launcher#4519]
### Operating System

Windows

### Description of bug

[https://pastebin.com/raw/vHXQbyz2](https://pastebin.com/raw/vHXQbyz2)

I just received my "Migrate your Account" email from Microsoft. After doing so, I decided to test that my MultiMC mod packs would work. I was able to launch the few packs I have for 1.07 and 1.12, but the majority of my packs are for 1.16.5 and they can't launch due to the error. I have confirmed that my Java and MultiMC installs are up to date. I installed an entirely new and up to date mod pack and still received the error. Any assistance would be appreciated.

### Steps to reproduce

* Migrate account to Microsoft.
* Update account in MultiMC.
* Fail to load mod packs for 1.16.5.
* Don't profit.

More seriously, I have no idea what I could have done wrong or what's happening.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by JoshuaJoppie** [comment]
@phit This worked for me to get it to launch. Thanks for posting this! My specific case was Vault Hunters is set to launch with these versions of Forge.
I updated forge myself and it launched great!
