### ISSUE TITLE
rpc doesnt work

### ISSUE THREAD

**Issue by mnfari** [MultiMC/Launcher#4521]
### Operating System
Windows 11

### Description of bug

as the title said

### Steps to reproduce

it is just when I use the multimc launcher, mc rpc doesn't work but when I use the official launcher from mojang, it works

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
no idea what "mc rpc" is, but assuming its a mod that doesn't sound like an issue with MultiMC, report whatever is happening to them
they probably need more info than it doesn't work
