### ISSUE TITLE
Microsoft Token Creation Method is different

### ISSUE THREAD

**Issue by ramonGonzEdu** [MultiMC/Launcher#4525]
I was recently trying to make a Microsoft token for use with nixos, and following the general steps in the notsecrets/Secrets.cpp and the nixos page I wasn't able to find the Live SDK option. For some reason, the option to set the token as "Personal Account" isn't shown, and you have to change it in the JSON manifest, then the Live SDK option appears under Authentication.

This essentially requests that the Secrets file have up to date instructions, which just mentions having to set the signInAudience in the manifest.

Changes necessary to manifest:
```json
{
"accessTokenAcceptedVersion": 2,
"signInAudience": "PersonalMicrosoftAccount", 
}
```

**Comment by phit** [comment]
feel free to open a PR to adjust the documentation for this!

**Comment by ramonGonzEdu** [comment]
Could I create a new Markdown file in the `notsecrets` directory so that I can attach images and such?

**Comment by phit** [comment]
might be easier to add a page to the wiki https://github.com/MultiMC/wiki
and then link to that in the notsecrets folder

**Comment by ramonGonzEdu** [comment]
I've made the pull req on the wiki

**Comment by peterix** [comment]
Merged!
