### ISSUE TITLE
Post-1.12.2 minecraft crashes if 'Use system installation of GLFW' is ticked

### ISSUE THREAD

**Issue by BenjaminD06** [MultiMC/Launcher#4531]
### Operating System

Windows

### Description of bug

Trying to launch any installation of Minecraft that is a later update than 1.12.2 (or at least starting from 1.13.2) crashes. Disabling the 'Use system installation of GLFW' option in the workarounds section allows it to start.
Pastebin of the Minecraft log: https://pastebin.com/2MpisW7V

### Steps to reproduce

1) Create a MultiMC instance where the Minecraft installation is update 1.13.2 or later.
2) Ensure that the option 'Use system installation of GLFW' is ticked.
3) Launch the instance.

### Suspected cause

According to the logs, the instance seems to be unable to find glfw.dll, which causes it to crash. I'm unsure if this is an issue on my end or not - I've tried manually installing GLFW but that doesn't seem to change much.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by spannerman79** [comment]
>Ensure that the option 'Use system installation of GLFW' is ticked.

**Don't** tick it unless you have GLFW installed.

That option is there for those that know what they are doing and understand the implcations of actually enabling it.

**Comment by BenjaminD06** [comment]
Ah, right. Sorry for the duplicate issue. Thanks for the quick response, have a good one!
