### ISSUE TITLE
Create a way to update any mod directly from MultiMC `Loader mods` tab.

### ISSUE THREAD

**Issue by SpinyOwl** [MultiMC/Launcher#4532]
### Role

I play modded Minecraft.

### Suggestion

I want to have button on mod, that would update mod

### Benefit

So I don't have to manually download mod updates from curseforge and have mess in downloads folder.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Just like curseforge client has update button on mod that could be updated - it would be nice to have same functionality in MultiMC.

**Comment by phit** [comment]
CurseForge is due to be removed soon, since they are killing their API, see https://github.com/MultiMC/Launcher/issues/2640#issuecomment-1014738398
