### ISSUE TITLE
b1.7.3 doesnt work

### ISSUE THREAD

**Issue by OnDisease** [MultiMC/Launcher#4541]
### Operating System

macOS

### Description of bug

whenever I try to launch an instance of b1.7.3 it will launch with a black screen. i can hear when i click on something but the window is completely dark.

### Steps to reproduce

just launch an instance of b1.7.3 on MacOS.

### Suspected cause

no idea.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Game issue downgrade your Java, see https://github.com/MultiMC/Launcher/issues/3386
