### ISSUE TITLE
screen displays too zoomed in on 1.6.4

### ISSUE THREAD

**Issue by jredfox** [MultiMC/Launcher#4543]
### Operating System

Windows

### Description of bug

when hitting f11 on mc 1.6.4 it becomes too zoomed in. also graphics appear to be more blurry then usual

### Steps to reproduce

create 1.6.4 or 1.7.10 instance
link it to java "1.8.0_321"
click run
hit f11
![Minecraft 1 7 10 2_25_2022 8_16_30 AM](https://user-images.githubusercontent.com/9736369/155730343-4325807a-ab22-4b50-bf80-f2401be5d63f.png)

### Suspected cause

multimc being out of date. this issue started on 2/25/22 and it wasn't there yesterday

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
change your windows screen scaling to 100%, the game can't handle dpi scaling

you can also try switching to this build of multimc https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip

**Comment by jredfox** [comment]
No it worked with my dpi settings it's multimc that changed. It worked before now it does not it's a bug on your part not mine.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jredfox** [comment]
It also works on the normal launcher. You are doing something different fr vanilla launcher

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by phit** [comment]
just switch to the build I linked, if you want to ignore the advice given to you, then that's your loss
and no this isn't a new issue, it's been an issue since display scaling existed in Windows and caused by the old version of Qt that we use to support older Windows versions

**Comment by jredfox** [comment]
Well it didn’t happen on 1.6.4 before. Can’t you disable it for only Minecraft?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jredfox** [comment]
the version you linked does not even fetch minecraft versions nor log in. just fix it is all I am saying. It works on the vanilla launcher written in java and it worked before so fix it

**Comment by peterix** [comment]
MultiMC did not change.

**Comment by jredfox** [comment]
well fix it anyways. It occurs on 1.12.2 as well a recent version. The vanilla launcher has no such issue so multimc is doing scaling or something

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows


________________________________
