### ISSUE TITLE
java bug

### ISSUE THREAD

**Issue by begumAnthony** [MultiMC/Launcher#4546]
### Description of bug

when I try to start up a version it says The java binary "" couldn't be found. Please set up java in the settings. how do I fix this? and what javapath do I use because when I click auto detect it says no versions have been found.

### Steps to reproduce

idk

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please don't open multiple issues and read the wiki https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
