### ISSUE TITLE
can't open fabric instance

### ISSUE THREAD

**Issue by Tribuloidd** [MultiMC/Launcher#4547]
### Operating System

Windows

### Description of bug

When i try to launce the instance it comes up with:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Fabric 1.18.1' failed to process:
https://maven.fabricmc.net/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
https://maven.fabricmc.net/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
https://maven.fabricmc.net/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm/9.2/asm-9.2.jar

### Steps to reproduce

1. Launch the instance of fabric 1.18.1
2. Comes up with the error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
can you open those links in your browser?

**Comment by phit** [comment]
find the MultiMC-0.log in the MultiMC folder either look for errors yourself in there or put the file on https://gist.github.com/ and share the link here

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
