### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by GoodGolem** [MultiMC/Launcher#4549]
Idk why it happen so plz help.
my operating system: Windows 11
Java version: jdk 17
crash file:
[crash-2022-02-27_16.54.56-client.txt](https://github.com/MultiMC/Launcher/files/8148372/crash-2022-02-27_16.54.56-client.txt)
processor: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz   2.59 GHz
installed ram: 4.00 GB (3.84 GB usable)

**Comment by GoodGolem** [comment]
I know there is a issue report alr but I still don't understand why is it crashing. I appreciate your help

**Comment by GoodGolem** [comment]
BTW I only have the free official version of minecraft (demo version) because I have no permission and budget to buy minecraft so is it that I have to use offline launch?

**Comment by GoodGolem** [comment]
and is it also compatible with notenoughcrashes mod I used it and it says it is the problem but after I disable it, it is still crashing

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by GoodGolem** [comment]
no it still crashes without mods

**Comment by phit** [comment]
then provide a proper log please https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#usage
