### ISSUE TITLE
Game crashed, save won't load (SkyFactory 3 Modpack)

### ISSUE THREAD

**Issue by imadeadbrain** [MultiMC/Launcher#4550]
### Operating System

Windows

### Description of bug

Was playing the game for a few hours straight, and it randomly (or seemingly randomly) crashed. When I launched the game the save wouldn't go past 0% in loading, even after several minutes. It happened once before on the 15th, and this time on the 28th. Both crash reports should be attached below. People have similar crashing problems, but none seem to be the same as what I have. I don't have a VPN or anything that I can think of that would cause the crash or save loading issue...

[crash-2022-02-15_00.12.25-client.txt](https://github.com/MultiMC/Launcher/files/8154921/crash-2022-02-15_00.12.25-client.txt)

[crash-2022-02-28_02.21.42-client.txt](https://github.com/MultiMC/Launcher/files/8154924/crash-2022-02-28_02.21.42-client.txt)
.

### Steps to reproduce

Play modpack for several hours
See if it crashes while actively progressing
Game crashes
Try loading up save
It not load past 0%

### Suspected cause

Genuinely no clue. I'm not really tech savy, so I don't know how to read the crash reports, but I imagine they would help, which is why I attached them...Or why they should be attached after I did what github said to do, to attach them.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
