### ISSUE TITLE
Minecraft stuck at 100% load screen

### ISSUE THREAD

**Issue by awinkler79** [MultiMC/Launcher#4551]
### Operating System

Windows

### Description of bug

Minecraft load screen stuck at 100%

### Steps to reproduce

checked discord. I was advised to move RAM up and down. I have tried restarting and loading several times. The same issue occurs each time. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by awinkler79** [comment]
I tried there first. They were the ones who suggested testing the RAM and I sent activity logs all I got was “odd”

**Comment by phit** [comment]
The same volunteers that are on Discord read this issue tracker, this tracker is for MultiMC issues not game issues.
If nobody was able to help you at the time you posted, try again during a different time of day and always provide logs. Even if this tracker was for game issues you provided 0 information to troubleshoot.

**Comment by awinkler79** [comment]
Well I don’t know what’s wrong. The game is just stuck. I don’t know what more to say. I’m not tech savvy in the slightest. I’m just trying to enjoy a game and find someone to help. Clearly that won’t be from here.
