### ISSUE TITLE
Switching 1.18.1 to 1.18.2 crashes game on launch

### ISSUE THREAD

**Issue by iseeghosts** [MultiMC/Launcher#4555]
### Operating System

Windows

### Description of bug

Game crashing at launch when trying to play by changing a 1.18.1 versions of game to 1.18.2
Optifine configuration
 {
    "+tweakers": [
        "optifine.OptiFineTweaker"
    ],
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.minecraft:launchwrapper:of-2.3",
            "url": "https://files.multimc.org/maven/"
        },
        {
            "MMC-filename": "OptiFine_1.18.1_HD_U_H4.jar",
            "MMC-hint": "local",
            "name": "optifine:OptiFine:1.18.1_HD_U_H4"
        }
    ],
    "mainClass": "net.minecraft.launchwrapper.Launch",
    "name": "OptiFine",
    "requires": [
        {
            "equals": "1.18.2",
            "uid": "net.minecraft"
        }
    ],
    "uid": "Optifine.Optifine",
    "version": "1.18.1_HD_U_H4"
}

Crash Logs - 
[crash-2022-03-01_09.00.17-client.txt](https://github.com/MultiMC/Launcher/files/8175119/crash-2022-03-01_09.00.17-client.txt)
[crash-2022-03-01_09.00.53-client.txt](https://github.com/MultiMC/Launcher/files/8175120/crash-2022-03-01_09.00.53-client.txt)
[crash-2022-03-01_09.01.43-client.txt](https://github.com/MultiMC/Launcher/files/8175121/crash-2022-03-01_09.01.43-client.txt)
[crash-2022-03-03_10.32.39-client.txt](https://github.com/MultiMC/Launcher/files/8175122/crash-2022-03-03_10.32.39-client.txt)

### Steps to reproduce

Game crashes on switching a 1.18.1 world to 1.18.2 (optifine used with multimc)

### Suspected cause

Possible reasons - changing commands for a lot of things

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc). Also generally mods like Optifine will not work across multiple MC versions.
