### ISSUE TITLE
Issue with Minecraft 1.16

### ISSUE THREAD

**Issue by SkyDreamGFX** [MultiMC/Launcher#4556]
### Operating System

Windows

### Description of bug

Hi guys,

I downloaded a FTB pack and I am not able to run it. Could you please let me know what can cause this error?

Here is the log file: https://paste.ee/p/pvdJ8

Thank you! 

### Steps to reproduce

1. Download FTB Academy 1.16
2. Launch the game
3. Error while loading

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
