### ISSUE TITLE
OSX 10.7.5 Login Broken

### ISSUE THREAD

**Issue by jadenquinn** [MultiMC/Launcher#4557]
The Mojang login option on MultiMC (dev) does not work on Mac OS X 10.7.5, with the error "Mojang user authentication ended with a network error.

I am not having network issues myself, as everything else works except for the MultiMC login.

**Comment by phit** [comment]
minimum supported version for MultiMC is 10.13, sorry you will need to update it's basically impossible to keep supporting such ancient versions
