### ISSUE TITLE
Custom instances not showing up in instances list.

### ISSUE THREAD

**Issue by AlexBartles2012** [MultiMC/Launcher#4559]
### Operating System

Windows

### Description of bug

I put all of my versions from my .minecraft\versions\ folder to MultiMC\instances (my MultiMC will be moved later if I can fix this) and it doesn't show up.

### Steps to reproduce

Move all custom versions from .minecraft\versions\ to MultiMC\instances.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
thats not how that works at all, what are you trying to achieve?

**Comment by phit** [comment]
if you really must, read https://github.com/MultiMC/Launcher/wiki/Jar-Modding https://github.com/MultiMC/Launcher/wiki/Instance-Version#advanced
