### ISSUE TITLE
MultiMC not letting me launch any mods or modpacks

### ISSUE THREAD

**Issue by funnyplebnesman** [MultiMC/Launcher#4562]
### Description of bug

it shows some red text about java or something i dont understand
its not letting me launch anything it just shows the text everytime
![image](https://user-images.githubusercontent.com/100997761/156879770-a6c97298-48e9-410d-a793-340c0ee85535.png)

### Steps to reproduce

i open multimc
try to launch literally any mod
it loads for some time
then boom red text

### Suspected cause

idk what's causing this im not understanding shit
can someone help me please

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by funnyplebnesman** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

i've installed the most recent java and it still does the same
