### ISSUE TITLE
changing the mc version dont get checked by the game 

### ISSUE THREAD

**Issue by naecker21** [MultiMC/Launcher#4563]
### Operating System

Windows

### Description of bug

when changing the mc version of a instance and everything thats in that window to the recomendet one, the game doesnt check it that it is modded (i used fabric) and cant load the mods at all even tho the mods get registert at the log when loading the the instance

### Steps to reproduce

change the mc version of an instance and evrything to the recomendet version

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide some logs, there's no such thing as the game checking that it is modded and frankly I have no idea what you trying to say
