### ISSUE TITLE
"Use system installation of GLFW" only checks for for a file called "libglfw.so"

### ISSUE THREAD

**Issue by thatLeaflet** [MultiMC/Launcher#4564]
### Operating System

Linux

### Description of bug

Expectation: After installing glfw on Linux distros like Ubuntu and Fedora, I would expect to be able to enable this option and play the game

What happened: The game fails to launch due to being unable to find glfw

### Steps to reproduce

- Have Ubuntu installed
- Install glfw by running `sudo apt install libglfw3`
- Open MultiMC and check "Use system installation of GLFW"
- Attempt to launch the game

### Suspected cause

After installing glfw, some distros like Ubuntu and Fedora only create files called "libglfw.so.3.3" and "libglfw.so.3". However, MultiMC only seems to check for a file called "libglfw.so", and if it doesn't find it, the game will fail to launch. However, the game does launch correctly if you create a file called "libglfw.so" that is symlinked to "libglfw.so.3.3".

Other distros like Arch Linux automatically create the "libglfw.so" file and do not suffer from this issue.

If possible, it would be nice if MutliMC also checked for "libglfw.so.3.3" and "libglfw.so.3".

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc has no influence to what is being checked, its up to the game to do that, the option simply disables the glfw binaries provided by mojang being made available to the game
