### ISSUE TITLE
Can't use the latest forge version

### ISSUE THREAD

**Issue by juliocoliveira** [MultiMC/Launcher#4565]
### Operating System

Windows 11

### Description of bug

Can't use the latest version of forge, MultiMC just allow me to use 40.0.8 when the latest is 40.0.12.
Pressing Refresh does not show the newest versions.
I'm using the latest develop version: MultiMC 5 Version 0.6.14-develop-3224

![image](https://user-images.githubusercontent.com/6606725/156942384-a0d9d94d-cf58-4c6d-a702-1e7b43fc8625.png)
![image](https://user-images.githubusercontent.com/6606725/156942391-3d62b5ca-e19f-496c-b881-643cc4b1b947.png)

### Steps to reproduce

Install Forge

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
should be fixed, the update job was temporarily disabled due to some system maintenance

**Comment by juliocoliveira** [comment]
i can confirm that is fixed, thanks!
