### ISSUE TITLE
FTB Ultimate 1.4.7 - Black Screen on startup

### ISSUE THREAD

**Issue by XxTrollerCraftxX** [MultiMC/Launcher#4567]
### Operating System

macOS

### Description of bug

I'm loading FTB Ultimate 1.4.7 through multimc, with Java 8 installed but as soon as the java window opens the screens black.
I can hear the menu clicks so its still loading the game I just can't see anything.
I've done a complete reset of my computer and reinstalled java from (https://adoptium.net/?variant=openjdk8)
I can load other packs from different versions of MC including vanilla 1.4.7
I'm running osMonterey on a 2017 Mac (not m1) but had the same issue running osSierra 
I first went to the discord and tried a bunch of different versions of java and also added the javalegacyfixer.jar thing but nothing worked.
If you can help I'd appreciate it a bunch!!

### Steps to reproduce

No clue lol

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
which java versions did you try? you most likely need java 8 update 232 or older

**Comment by XxTrollerCraftxX** [comment]
you're a legend, 4 days of it not working but java 8 update 221 fixed it
