### ISSUE TITLE
Can't open Multimc if it is on my desktop, as it says "The code execution cannot proceed because libLauncher_iconfix.dll was not found"

### ISSUE THREAD

**Issue by Lucathejedi54** [MultiMC/Launcher#4568]
### Operating System

Windows

### Description of bug

When i try to open Multimc when it is on my desktop multiple error messages occur. it always has to do with this liblauncher file. Even though those files are in the folder. This is probably occurring due to me not having WinZip. this is not a big problem as I can open the app through the folder, its just annoying
![image_2022-03-07_170432](https://user-images.githubusercontent.com/101148359/157125722-6b0f2b84-f201-44e7-a64a-b024350f4152.png)
![image_2022-03-07_170632](https://user-images.githubusercontent.com/101148359/157125992-def1f541-8fa5-40d5-bdee-5a9d9e7a42b2.png)
![image_2022-03-07_170647](https://user-images.githubusercontent.com/101148359/157126018-391cb8e0-115d-4ee7-8695-d459a0422fbd.png)
![image_2022-03-07_170659](https://user-images.githubusercontent.com/101148359/157126038-fe62c9cd-aca1-41fd-a2e5-9df0e2fb5964.png)
![image_2022-03-07_170707](https://user-images.githubusercontent.com/101148359/157126058-5f09013c-53f7-4c6c-9320-0035b7869155.png)

### Steps to reproduce

download multimc, open file through extracting it, drag it to the desktop, and the error occurred when I tried to open it after moving it to desktop

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
move the launcher out of onedrive, it will mess up everything including the launcher and game

**Comment by Idontknow-121235** [comment]
same here. i deleted one drive and removed MultiMC from it but it still wont work
