### ISSUE TITLE
When attempting to launch Minecraft, it exits and returns error code 1 in the console.

### ISSUE THREAD

**Issue by TheMiningTeamYT** [MultiMC/Launcher#4570]
### Operating System

Windows

### Description of bug

I am using Windows 98. When attempting to launch Minecraft 1.8, which when using the soon-to-be-discontinued legacy launcher from Mojang works fine, crashes immediately after attempting to run it. In the console it returns “Process exited with error code 1.”
[The log](https://paste.ee/p/kafM7)

### Steps to reproduce

- Get a machine running fully updated Windows 98 with a powerful CPU and OpenGL 2 GPU
- Install KernelEx
- Install a version of Java newer than 6u15 (I am using a manual, as in I extracted the files from the JDK 8u152 installer instead of doing a normal install)
- Download MultiMC
- Login and add an instance of Minecraft 1.8
- Edit the instance and tell it to use the javaw.exe file from your earlier installation of Java manually, as auto detection of Java fails on Windows 98.
- Attempt to launch Minecraft.

Since I know most people don’t have a Windows 98 rig these days, if there’s anything I can do to help using mine, I’d be happy to do so.

### Suspected cause

I have no solid ideas, but I do wonder if it’s related to Windows 98’s 255 character command line argument limit, as in when you run a command, the entire string passed to the interpreter is limited to 255 chars. However, in the MultiMC-0.log saw “QProcess: CreateNamedPipe failed (this function is only valid in Win32 mode” so maybe that’s the true cause.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
We can't really invest time into fun experiments like that here, maybe some folks on our discord have an idea, but if you do stuff like this you are definitely on your own. [discord.gg/multimc](https://discord.gg/multimc).
