### ISSUE TITLE
Instances with forge before 1.17 crash

### ISSUE THREAD

**Issue by Lordnerdious** [MultiMC/Launcher#4572]
I recently got a new computer and obviously brought all my instances over so I could continue to play them. But the first thing I did was make a new one in 1.18. I'm using forge mods and installed forge, and it works fine. Recently I wanted to play one of my old packs and it failed to launch. I thought it was odd but I tried another one. The same thing happened. I created a new instance and it worked fine. I eventually narrowed it down to installing any version of forge on any instance using a version before 1.17. I've even reinstalled multi mc and tried making a new instance from scratch. Same issue. I want to play my older packs, I hope this can be fixed

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
