### ISSUE TITLE
Konsole is not opening

### ISSUE THREAD

**Issue by HerrDerLocken** [MultiMC/Launcher#4573]
### Operating System

Windows

### Description of bug

The Edit Instance button doesnt work. When i press it the window opens but i cannot see anything it displays a white field when i go over the multimc icon and when i want to click on it, it doesnt work, so i cant edit the version of java, mods, etc...
I tried it with all versions and modpacks that i have installed and it doesnt work at all.

### Steps to reproduce

Press the edit Instace button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
versions? logs (`MultiMC-0.log`, etc.) ?

**Comment by HerrDerLocken** [comment]
Version 0.6.14-300
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/8222443/MultiMC-0.log)
[MultiMC-1.log](https://github.com/MultiMC/Launcher/files/8222445/MultiMC-1.log)
[MultiMC-2.log](https://github.com/MultiMC/Launcher/files/8222446/MultiMC-2.log)
[MultiMC-3.log](https://github.com/MultiMC/Launcher/files/8222447/MultiMC-3.log)
[MultiMC-4.log](https://github.com/MultiMC/Launcher/files/8222448/MultiMC-4.log)
1

**Comment by phit** [comment]
try the dev build (settings > update channel) and or this build
https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip
