### ISSUE TITLE
Version 1.16.3-1.16.4 do not launch if any version of forge is installed despte having the right java

### ISSUE THREAD

**Issue by Lordnerdious** [MultiMC/Launcher#4574]
### Operating System

Windows

### Description of bug

I posted a report a few hours ago about a more common version of this issue, to which I was linked a file saying I needed a different version of java. So I got java 8 and made all of my pre-1.17 packs utilize java 8. And for some of them it worked. My 1.12-1.14 packs are working again. And 1.16.5 works too. But for some reason, 1.16.3-1.16.4 still refuses to work when forge is present regardless of any mods (or lack thereof.) It _does_ launch the game into the loading screen but during the loading screen, it crashes again.

### Steps to reproduce

Create an instance in 1.16.3-1.16.4 with any version of forge, even when using java 8

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
post logs
![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by Lordnerdious** [comment]
https://paste.ee/p/1ZAn5

**Comment by phit** [comment]
Thats java 17, you need java 8 and for those forge versions specifically you need an older java 8 version

> Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.

**Comment by Lordnerdious** [comment]
I cant seem to find a download link for java 8u311 anywhere, could you point me in the right direction?

**Comment by phit** [comment]
e.g. https://adoptium.net/archive.html?variant=openjdk8&jvmVariant=hotspot the oracle archives require an account but are also an option https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html

**Comment by Lordnerdious** [comment]
Thank you!
