### ISSUE TITLE
LoTAS doesn't work with Forge 1.12.2

### ISSUE THREAD

**Issue by bolt1117** [MultiMC/Launcher#4577]
### Operating System

Windows

### Description of bug

What happened:
Modpack crashed with LoTAS 1.12.2 enabled

What was supposed to happen
Modpack was supposed to actually work with LoTAS

Why this is bad:
LoTAS works with the vanilla launcher

(If you're wondering, the 2 modpacks I tested were Enigmatica 2: Expert and the FTB Legacy version of Stoneblock 2)

### Steps to reproduce

1. Install a 1.12.2 modpack
2. Add LoTAS1.12.2-2.0.1 as a loader mod
3. Launch the modpack
4. Get an InvocationTargetException from OneSixLauncher and watch your game crash

### Suspected cause

I'm not sure if this is a bug with MultiMC, Forge, or the LoTAS mod, but considering the error that the onesix launcher is giving, It seems like the bug is something with MultiMC.

(And yes, I am using Java 8. The pack works without LoTAS.)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
gonna need a log

 ![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by bolt1117** [comment]
Here it is: https://paste.ee/p/IDmbO

**Comment by phit** [comment]
> Mixin prepare failed preparing render.gui.MixinGuiGameOver in lotas.mixin.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: lotas.mixin.json:render.gui.MixinGuiGameOver target net.minecraft.client.gui.GuiGameOver was already transformed.

This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
