### ISSUE TITLE
Stuck at "Logging in with XBox and Mojang services", then "XBox and/or Mojang authentication steps did not succeed" (Mojang/Minecraft services outage)

### ISSUE THREAD

**Issue by LoganDark** [MultiMC/Launcher#4582]
### Operating System

Windows

### Description of bug

MultiMC sits at this screen for a while:

![chrome_YEFp6S6kfZ](https://user-images.githubusercontent.com/4723091/158600399-cbacc341-4426-41d6-a307-6c6dea331990.png)

then it errors and says this:

![MultiMC_IDwCMOTl23](https://user-images.githubusercontent.com/4723091/158600464-62267be1-7853-4dbf-8578-f02d775262bb.png)

### Steps to reproduce

I think, try to log in with a new Microsoft account that only has Minecraft? It was recently suspended for "violating the service agreement" or whatever, but I verified using a random friend's phone number and I was able to log in once before MultiMC told me that I needed to re-add the account and now this keeps happening.

I've tried removing MultiMC's connection before re-linking, the account is fine, no suspensions or anything, for some reason it just won't link properly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by IllagerCaptain** [comment]
I already have my account added, and I am stuck at this window:
![image](https://user-images.githubusercontent.com/76600137/158601829-62fff1fc-4994-431b-aeb1-f0e9b7600977.png)

After checking logs, its due to a gateway timeout:
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/8262547/MultiMC-0.log)

**Comment by LoganDark** [comment]
Maybe Microsoft is down? They don't have a status page so I can't check anyway

**Comment by DarkVen0m** [comment]
I guess it's not launcher related, there is a lot of reports of MC having problems. You can also check MojangStatus twitter (not sure if it's official) - it also states the problem.

**Comment by IllagerCaptain** [comment]
> I guess it's not launcher related, there is a lot of reports of MC having problems. You can also check MojangStatus twitter (not sure if it's official) - it also states the problem.

Does this also affect the vanilla Launcher?

**Comment by LoganDark** [comment]
> I guess it's not launcher related, there is a lot of reports of MC having problems. You can also check MojangStatus twitter (not sure if it's official) - it also states the problem.

I actually checked that before reporting this issue and there's nothing there. I don't think Mojang handles Microsoft accounts, only migrations.

**Comment by IllagerCaptain** [comment]
> > Maybe Microsoft is down? They don't have a status page so I can't check anyway
> 
> Yep, `api.minecraftservices.com` is down.

_*sigh*_

**Comment by DarkVen0m** [comment]
You can also check it here - https://mojan.ga/

**Comment by martinspp** [comment]
> > I guess it's not launcher related, there is a lot of reports of MC having problems. You can also check MojangStatus twitter (not sure if it's official) - it also states the problem.
> 
> Does this also affect the vanilla Launcher?

![image](https://user-images.githubusercontent.com/19413900/158603079-76f419ed-e3b7-4aee-9d0c-449d4f549048.png)

**Comment by IllagerCaptain** [comment]
![image](https://pbs.twimg.com/media/FN-YkLAXsAUa6p-?format=jpg)

**Comment by SammyWhamy** [comment]
How come that I'm not able to launch offline with these issues, isn't the idea of Offline that I don't need to connect to mojang services?

**Comment by LoganDark** [comment]
> How come that I'm not able to launch offline with these issues, isn't the idea of Offline that I don't need to connect to mojang services?

It's because MultiMC gets stuck waiting for the Mojang server, so Play Offline is never able to activate.

**Comment by SammyWhamy** [comment]
I see, that worked for me. Not gonna lie though that seems really dumb. If I click the button "Launch Offline" I expect it to **not** use an internet connection to launch, it shouldn't try to do so anyways.

**Comment by IllagerCaptain** [comment]
> I see, that worked for me. Not gonna lie though that seems really dumb. If I click the button "Launch Offline" I expect it to **not** use an internet connection to launch, it shouldn't try to do so anyways.

#4433

**Comment by LoganDark** [comment]
> I see, that worked for me. Not gonna lie though that seems really dumb. If I click the button "Launch Offline" I expect it to **not** use an internet connection to launch, it shouldn't try to do so anyways.

Play Offline doesn't use your internet connection - it's the fact that MultiMC is _already trying to connect_ that throws it off. There's a separate Play Offline button on the right sidebar that, I believe, should still work even with this downtime.

**Comment by martinspp** [comment]
> > I see, that worked for me. Not gonna lie though that seems really dumb. If I click the button "Launch Offline" I expect it to **not** use an internet connection to launch, it shouldn't try to do so anyways.
> 
> Play Offline doesn't use your internet connection - it's the fact that MultiMC is _already trying to connect_ that throws it off. There's a separate Play Offline button on the right sidebar that, I believe, should still work even with this downtime.

Welp, account became "expired" when i was attempting to launch. Launch Offline doesn't work because of that anymore.

**Comment by LoganDark** [comment]
> > > I see, that worked for me. Not gonna lie though that seems really dumb. If I click the button "Launch Offline" I expect it to **not** use an internet connection to launch, it shouldn't try to do so anyways.
> > 
> > 
> > Play Offline doesn't use your internet connection - it's the fact that MultiMC is _already trying to connect_ that throws it off. There's a separate Play Offline button on the right sidebar that, I believe, should still work even with this downtime.
> 
> Welp, account became "expired" when i was attempting to launch. Launch Offline doesn't work because of that anymore.

Oh I hate that too. Might need a separate bug report.

**Comment by vonas** [comment]
> It was recently suspended for "violating the service agreement" or whatever

Hate when that happens.

I can confirm, the launcher is in fact not able to launch anything while you're connected to the internet and mojang services are down. Only yanking your ethernet cable and restarting MultiMC helps. :^)

**Comment by LoganDark** [comment]
This issue has now been resolved.
