### ISSUE TITLE
I can't Load Into 1.17 Nor 1.18

### ISSUE THREAD

**Issue by BackbonedWord34** [MultiMC/Launcher#4586]
### Description of bug

When I go to open a 1.18 server/world I keeps saying "Minecraft 1.18 Pre Release 2 and above require the use of Java 17" and when i open 1.17 it says "Minecraft 1.18 Pre Release 2 and above require the use of Java 16" and i cant play normal Minecraft anymore

### Steps to reproduce

Don't necessarily have anything but here is the code
lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/instances/1.18.2/.minecraft --assetsDir C:/Users/caugh/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Minecraft 1.18 Pre Release 2 and above require the use of Java 17

### Suspected cause

maybe because I'm just not doing something right?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by juliocoliveira** [comment]
That means that you need have java jre or jdk version 17. And need to setup to use that version.
This is not a bug, is normal case of use, you just need to setup it up right.
Use this version https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.msi or download it from https://adoptium.net/.

Download and install. Then you need to setup up, go on MultiMC -> Settings -> Java -> Java runtime. OR Setup up the java per instance: Right Click on on instance -> Settings -> Java

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
