### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Aksh124** [MultiMC/Launcher#4587]
### Operating System

Windows

### Description of bug

Does not launch 

https://paste.ee/p/49iY5 <- log

### Steps to reproduce

press launch button

### Suspected cause

N/A

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
