### ISSUE TITLE
Title says "Java test failed" when it succeed

### ISSUE THREAD

**Issue by CashMan3000** [MultiMC/Launcher#4589]
### Operating System

Windows, Linux

### Description of bug

When testing the java installation in the setup, even if the java test was successful, it will say it failed.

### Steps to reproduce

Test java during setup

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/4481
