### ISSUE TITLE
Beta Modifed Version's are not working on my pc. Despite changes to memory and the Muti-MC Program.

### ISSUE THREAD

**Issue by Antonio115GH** [MultiMC/Launcher#4592]
### Operating System

Windows

### Description of bug

So every time I try to log into my beta nostalgic pack. Or better than adventure, I find myself having my frames drop and drop by each second. While the world is loading/when I'm moving around. Now yes booting up a world will have a few frame go down. But I mean like, the game just gets worse and worse until probably crashing or being in an unplayable state. I have allocated 6GB or ram, on instance and global settings. I have updated my java to be 64-bit. (Although, multi-mc won't updated to 64-Bit for some reason). I am using my recommend and auto detected java machine/version. I am not sure what to do, to get all of this to work. Can anyone help me out.  Cause old Minecraft cool and nostalgic.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/101994099/159179613-d420de32-dbc1-494d-9847-dc8550a058a2.png)

### Suspected cause

Could be of the following: 32 Bit Launcher not working with a 64 Bit Java Version. Older game files, not working with modern computer. Maybe AMD just being goofy, since NVIDIA is better for running older games properly and emulation. Or corrupt files.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
allocate less memory like 512mb https://vazkii.net/blog_archive/#blog/ram-explanation

**Comment by Antonio115GH** [comment]
That did not do anything. Unless I set the values, wrong. I lowered the max memory to 1024 and min memory to 512. Also vice versa. Nothing happened.

**Comment by phit** [comment]
logs? laptop or desktop?

**Comment by Antonio115GH** [comment]
laptop

**Comment by Antonio115GH** [comment]
> logs? laptop or desktop?

it was laptop. i don't if my message went through
