### ISSUE TITLE
RE-Post Beta Modifed Version's are not working on my pc. Despite changes to memory and the Muti-MC Program

### ISSUE THREAD

**Issue by Antonio115GH** [MultiMC/Launcher#4593]
### Operating System

Windows

### Description of bug

So every time I try to log into my beta nostalgic pack. Or better than adventure, I find myself having my frames drop and drop by each second. While the world is loading/when I'm moving around. Now yes booting up a world will have a few frame go down. But I mean like, the game just gets worse and worse until probably crashing or being in an unplayable state. I have allocated 6GB or ram, on instance and global settings. I have updated my java to be 64-bit. (Although, multi-mc won't updated to 64-Bit for some reason). I am using my recommend and auto detected java machine/version. I am not sure what to do, to get all of this to work. Can anyone help me out. Cause old Minecraft cool and nostalgic.

![image](https://user-images.githubusercontent.com/101994099/159197668-69f4b4ef-19f7-42ed-8822-43ecebc8ccd8.png)

![image](https://user-images.githubusercontent.com/101994099/159197681-0cc03d83-7749-487e-a715-ac69978bd373.png)

### Steps to reproduce

Ram leakage maybe

### Suspected cause

Could be of the following: 32 Bit Launcher not working with a 64 Bit Java Version. Older game files, not working with modern computer. Maybe AMD just being goofy, since NVIDIA is better for running older games properly and emulation. Or corrupt files.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please use the old issue, and don't make a new one https://github.com/MultiMC/Launcher/issues/4592
it's just closed because it's support for the game and theres nothing actionable for the multimc project in there
