### ISSUE TITLE
Unable to load forge

### ISSUE THREAD

**Issue by jagjotchahal** [MultiMC/Launcher#4594]
### Description of bug

I am not able to use forge on 1.18.2. Fabric works perfectly on the other hand.

Here is the log containing the error.
https://paste.ee/p/hMHwY

### Steps to reproduce

https://paste.ee/p/hMHwY

![image](https://user-images.githubusercontent.com/93255544/159280921-b042a8eb-5c14-4e9b-b554-bb36ef0d77ff.png)

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
go to http://files.minecraftforge.com/ in Edge! which browser matters, then restart multimc and then try again

**Comment by jagjotchahal** [comment]
> go to http://files.minecraftforge.com/ in Edge! which browser matters, then restart multimc and then try again

This didnt do anything. plus the site had nothing to do with forge.

**Comment by phit** [comment]
what antivirus are you using?

**Comment by ImperatorStorm** [comment]
navigating to http://files.minecraftforge.com/ on firefox just redirects me to some domain parking company
Correct website is http://files.minecraftforge.net, not .com

**Comment by phit** [comment]
my bad, either way something is either messing with your java install or the java you have installed is missing the required letsencrypt certficates
try switching to one of these vendors https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#windows
