### ISSUE TITLE
Wont let me make a account

### ISSUE THREAD

**Issue by JustMeKay2** [MultiMC/Launcher#4598]
So what is the requirements for making a account.  When i try to make a mojang account it just says Mojang user authentication ended with a network error.Also when i tryed to make a microsoft account before it would say like xbox verification failed or something like that but now once i type my email and password in it just sends me back to the code thing at the beggining so its a never ending cycle now im very comfused

**Comment by phit** [comment]
what do you mean with it wont let you set a Microsoft or Mojang account, please explain what you are doing and what the result is
the default account button is to set an existing account to be your default selection

**Comment by JustMeKay2** [comment]
So when i try to type and make a mojang account it just say Mojang user authentication ended with a network error.

**Comment by JustMeKay2** [comment]
Also when i tryed to make a microsoft account before it would say like xbox verification failed or something like that but now once i type my email in it just sends me back to the code thing at the beggining so its a never ending cycle now im very comfused

**Comment by phit** [comment]
don't edit your original message, then nobody will notice, did you buy the game?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
