### ISSUE TITLE
Can't add Minecraft account

### ISSUE THREAD

**Issue by qirdo** [MultiMC/Launcher#46]
When I try to add my account it says "Yggdrasil task cancelled" and my account doesn't get added. I've tried to add it multiple times trying both my username and email address. I can still log in on the normal Minecraft launcher without any problem and I'm absolutely positive that I typed my account information correctly on MultiMC.

**Comment by agentlupdey** [comment]
no accont plizz acont

**Comment by 02JanDal** [comment]
@agentlupdey: Sorry what?

**Comment by peterix** [comment]
![olde](https://cloud.githubusercontent.com/assets/203326/5882112/cd6c0cbc-a346-11e4-85b9-efae5465b39e.jpg)

**Comment by peterix** [comment]
![olde](https://cloud.githubusercontent.com/assets/203326/5882205/a6323cf6-a347-11e4-886c-330d9e2c0a56.gif)

**Comment by agentlupdey** [comment]
I said I do not know why I did not want to make a accont me sami MultiMc5 can not give an accont so I just want to play singal PLEY

**Comment by agentlupdey** [comment]
are beginner and want to play did not give me help you

**Comment by 02JanDal** [comment]
You need a paid Minecraft account in order to play.

**Comment by agentlupdey** [comment]
yes I just can not only play singal cost so love Minecraft terog sit around all day on it and tried to figure onlain someone to play with me and I have not found anyone is in Romenia extra hard not know English use google translator and extra money to pay nam

**Comment by agentlupdey** [comment]
terog not remain friends, thank you help me terooog plizzzzz

**Comment by Forkk** [comment]
This is dead. Stop posting.
