### ISSUE TITLE
Chat doesn't show in game.

### ISSUE THREAD

**Issue by omchoksi** [MultiMC/Launcher#4600]
### Operating System

Windows

### Description of bug

The chat is not shown in snapshot 22w12a.
It is logged in the console though.
No messages are shown, including gamemode change, command outputs(/data),etc.

### Steps to reproduce

1) Start snapshot 22w12a using multimc.
2) join a world. 
3) Now try to chat or run commands with output.

try the same with normal launcher

![using mmc](https://user-images.githubusercontent.com/49519439/160066898-2e9887c4-8928-43df-8c94-e718173622b3.png)
![mmc console](https://user-images.githubusercontent.com/49519439/160066972-c31634e0-52c2-4cf8-a184-885a52643dd3.png)

![using normal launcher](https://user-images.githubusercontent.com/49519439/160066663-a483fde1-27b7-4506-8a12-6f22e8f9d293.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jikuja** [comment]
Potential root cause: https://bugs.mojang.com/browse/MC-249405
