### ISSUE TITLE
Can't add a mojang account

### ISSUE THREAD

**Issue by grayson676** [MultiMC/Launcher#4601]
### Operating System

Windows, Linux

### Description of bug

When I tried to add a Mojang account it gives the error "Minecraft Java profile acquisition failed."
I tried on both Windows and Linux and with 3 different Mojang accounts.

Log
28.661 D Task "MojangLogin(0x29ba3f0)" starting for the first time
   28.661 D AuthFlow: "Logging in with Mojang account."
   28.661 D Task "Yggdrasil(0x29816a0)" starting for the first time
   29.081 D Processing authentication response.
   29.081 D Getting access token.
   29.081 D Finished reading authentication response.
   29.081 D Task "Yggdrasil(0x29816a0)" succeeded
   29.081 D AuthFlow: "Fetching the Minecraft profile."
   29.385 W AuthRequest::onRequestError: Error 201
   29.385 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/minecraft/profile - server replied: Forbidden"
   29.385 W AuthRequest::onRequestError: HTTP status 403 "Forbidden"
   29.385 C Task "MojangLogin(0x29ba3f0)" failed:  "Minecraft Java profile acquisition failed."

### Steps to reproduce

Try adding a Mojang account.

### Suspected cause

Error 403 means the api understands the request but refuses to comply, probably a Mojang issue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you probably need to migrate to a microsoft account https://multimc.org/posts/microsoft-migration.html

**Comment by MathiusXII** [comment]
Same. Worked fine yesterday. Today it said my account "expired" or something and I had to reenter it manually. Now I get "Minecraft Java profile acquisition failed." just like you.

**Comment by P90ForRetail** [comment]
It looks like microsoft has pulled the plug on the mojang accounts. I'm not sure if there is a way to play without migrating yet, but I think it would be possible in the future, or at least I hope so

**Comment by Kaydax** [comment]
Having the same issue for one of my accounts. Yet the account works fine on other launchers. This looks to be just a multimc issue

**Comment by phit** [comment]
merging this with https://github.com/MultiMC/Launcher/issues/4317
