### ISSUE TITLE
when i want to install fabric launcher not loading and crash? Can someone help?

### ISSUE THREAD

**Issue by Lowrlor** [MultiMC/Launcher#4603]
### Role

.

### Suggestion

.

### Benefit

.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

MultiMC version: 0.6.14-3001

Launched instance in online mode

Minecraft folder is:
D:/MultiMC/instances/1.16.5/.minecraft

Java path is:
C:/Program Files/Java/jdk-18/bin/javaw.exe

Checking Java version...
Java is version 18, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.16.5' failed to process:
https://maven.fabricmc.net/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
https://maven.fabricmc.net/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
https://maven.fabricmc.net/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm/9.2/asm-9.2.jar

Clipboard copy at: 26 Mar 2022 20:36:50 +0200

**Comment by phit** [comment]
can you access those files in your browser?

**Comment by Lowrlor** [comment]
to those file (https://maven.fabricmc.net/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar)?

**Comment by phit** [comment]
yes

**Comment by Lowrlor** [comment]
I think no couse those files had to be installed. I have a guess that I have a problem with dns or firewall but I don't know how to solve it

**Comment by phit** [comment]
sorry that's out of scope for us, if your computer/internet cant download those files at all thats on your end to figure out
