### ISSUE TITLE
Wont start on macOS

### ISSUE THREAD

**Issue by Bara03** [MultiMC/Launcher#4604]
### Description of bug

I started my modpack(it works well on windows) and after i agreed how much ram i gave the pack, and press start the minecraft window appears for a sec and then crash.

<details>

 <summary>Error:</summary>

Process:               java [978]
Path:                  /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
Identifier:            java
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        MultiMC [583]
Responsible:           MultiMC [583]
User ID:               501

Date/Time:             2022-03-26 21:41:31.6143 +0100
OS Version:            macOS 12.2.1 (21D62)
Report Version:        12
Anonymous UUID:        CA662258-F4C0-E3EB-DBA2-50F68D11CDE5

Time Awake Since Boot: 600 seconds

System Integrity Protection: disabled

Crashed Thread:        2  Java: Client thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000101479000
Exception Codes:       0x0000000000000002, 0x0000000101479000
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0x101479000 is in 0x101479000-0x10147a000;  bytes after start: 0  bytes before end: 4095
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC metadata             101472000-101479000    [   28K] rw-/rwx SM=ZER  
--->  VM_ALLOCATE                 101479000-10147a000    [    4K] r--/rwx SM=PRV  
      shared memory               10147a000-10147b000    [    4K] r--/r-- SM=SHM  

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
abort() called
terminating with uncaught exception of type NSException
</details>

### Steps to reproduce

after start

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Java-on-macOS
