### ISSUE TITLE
I can't play a modpack

### ISSUE THREAD

**Issue by mateibec** [MultiMC/Launcher#4606]
I wanted to play a modpack on MultiMC (Kinda Crazy Craft) and it gave an error code (-1) and it didn't launched! Here is the MultiMC log:
MultiMC version: 0.6.14-3001

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.230.232.55, 54.230.232.51, 54.230.232.58, 54.230.232.40]

session.minecraft.net resolves to:
    [3.224.239.34, 52.205.99.166, 3.211.39.224]

textures.minecraft.net resolves to:
    [54.192.235.98, 54.192.235.102, 54.192.235.113, 54.192.235.92]

api.mojang.com resolves to:
    [54.192.235.48, 54.192.235.56, 54.192.235.94, 54.192.235.15]

Minecraft folder is:
C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/instances/Kinda Crazy Craft/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/instances/Kinda Crazy Craft/natives

Libraries:
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1566-1.7.10/forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] [1.7.10] SecurityCraft v1.8.13
  [✔️] [1.7.10]DamageIndicatorsMod-3.2.0
  [✔️] [1.7.10]MoVillages-1.4.2
  [📁] 1.7 (folder)
  [✔️] adventurebackpack-1.7.10-0.8c
  [✔️] AnimationAPI-1.7.10-1.2.4
  [✔️] appliedenergistics2-rv2-stable-10
  [✔️] ArchimedesShips-1.7.1
  [✔️] Baubles-1.7.10-1.0.1.10
  [✔️] BetterBoat-1.7.10-1.1.0
  [✔️] BetterBuildersWands-0.8.1-1.7.10r92+aec06c3
  [✔️] BetterFps-1.0.1
  [✔️] BiblioCraft[v1.11.7][MC1.7.10]
  [✔️] BiblioWoods[BiomesOPlenty][v1.9]
  [✔️] BiblioWoods[ExtraBiomesXL][v1.4]
  [✔️] BiblioWoods[Forestry][v1.7]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] BigReactors-0.4.3A
  [✔️] BiomesOPlenty-1.7.10-2.1.0.1889-universal
  [✔️] Bookshelf-1.7.10-1.0.4.187
  [✔️] Botania r1.8-249
  [✔️] buildcraft-7.1.23
  [✔️] Carpenter's Blocks v3.3.8.1 - MC 1.7.10
  [📁] carpentersblocks (folder)
  [✔️] ChickenChunks-1.7.10-1.3.4.19-universal
  [✔️] Chisel-2.9.5.11
  [✔️] Chunk Pregenerator V1.7.10-2.1
  [✔️] CodeChickenCore-1.7.10-1.0.7.47-universal
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] CustomNPCs_1.7.10d(29oct17)
  [✔️] Decocraft-2.4.2_1.7.10
  [✔️] denseores-1.6.2
  [✔️] DoomlikeDungeons-1.11.0-MC1.7.10
  [✔️] Dynamic Lights-1.3.9a-MC1.7.10
  [✔️] Emerald-Mod-1.7.10_1
  [✔️] EnderIO-1.7.10-2.2.8.381
  [✔️] EnderStorage-1.7.10-1.4.7.37-universal
  [✔️] ExtendedPotions-MC1.7.10-1.2
  [✔️] extrabiomesxl_1.7.10-3.16.4
  [✔️] ExtraCells-1.7.10-2.3.14b200
  [✔️] extrautilities-1.2.12
  [✔️] fastcraft-1.25
  [✔️] FastLeafDecay-1.7.10-1.4
  [✔️] FoodExpansion1.1.1-mc1.7.10
  [✔️] forestry_1.7.10-4.2.16.64
  [✔️] fpsplus
  [✔️] FpsReducer-mc1.7.10-1.10.3
  [✔️] FTBLib-1.7.10-1.0.18.3
  [✔️] FTBUtilities-1.7.10-1.0.18.3
  [✔️] FullscreenWindowed-1.7.10-1.3.0b
  [✔️] GraveStone Mod 0.7.10.3
  [✔️] GrimoireOfGaia3-1.7.10-1.2.7
  [✔️] Hats-4.0.1
  [📁] ic2 (folder)
  [✔️] ICBM-1.7.10-2.15.4b497
  [✔️] ICBM-classic-1.7.10-2.16.2b205
  [✔️] iChunUtil-4.2.3
  [✔️] industrialcraft-2-2.2.827-experimental
  [✔️] inventorypets-1.7.10-1.4.9.9b-universal
  [✔️] ironchest-1.7.10-6.0.62.742-universal
  [✔️] itsrainingfood-1.7.10-1.0.4
  [✔️] Jabba-1.2.2_1.7.10
  [✔️] journeymap-1.7.10-5.1.4p2-unlimited
  [✔️] JurassiCraft-1.4.0
  [✔️] llibrary-1.5.1-1.7.10
  [✔️] logisticspipes-0.9.3.132
  [✔️] LootBags-1.7.10-2.0.17
  [✔️] magicalcrops-1.7.10_0.1
  [✔️] magicbees-1.7.10-2.4.4
  [✔️] malisiscore-1.7.10-0.14.3
  [✔️] malisisdoors-1.7.10-1.13.2
  [✔️] Mantle-1.7.10-0.3.2b
  [✔️] Mekanism-1.7.10-9.1.1.1031
  [✔️] MekanismGenerators-1.7.10-9.1.1.1031
  [✔️] MekanismTools-1.7.10-9.1.1.1031
  [✔️] MobiusCore-1.2.5_1.7.10
  [✔️] MobProperties-1.7.10-1.0.2
  [✔️] MoreChisels-1.7.10-1.0-28
  [✔️] Morph-Beta-0.9.2
  [✔️] Morpheus-1.7.10-1.6.21
  [✔️] MrCrayfishFurnitureModv3.4.7(1.7.10)
  [✔️] MutantCreatures-1.7.10-1.4.9
  [✔️] natura-1.7.10-2.2.0.1
  [✔️] neiaddons-1.12.14.40-mc1.7.10
  [✔️] NEIIntegration-MC1.7.10-1.1.2
  [✔️] NEIlootbags-1.7.10-1.1.3
  [✔️] NetherOres-[1.7.10]2.3.1-22
  [✔️] NotEnoughItems-1.7.10-1.0.5.120-universal
  [✔️] orespawn-1.7.10-20.3
  [✔️] Origin-1.7.10-8.0.3
  [✔️] Pam's Get all the Seeds 1.7.10a
  [✔️] Pam's HarvestCraft 1.7.10Lb
  [✔️] Pam's Simple Recipes 1.7.10a
  [✔️] PandorasBox-2.1
  [✔️] PortalGun-4.0.0-beta-6-fix-1
  [✔️] PortalGunSounds
  [✔️] PortalGunSounds.pak
  [✔️] ProjectE-1.7.10-PE1.10.1
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Base
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Compat
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Integration
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  [✔️] ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  [📁] railcraft (folder)
  [✔️] Railcraft_1.7.10-9.12.2.0
  [✔️] ResourceLoader-MC1.7.10-1.3
  [✔️] roguelike-1.7.10-1.5.0b
  [✔️] RunicDungeons-1.1.7b
  [✔️] secretroomsmod-1.7.10-4.7.1.413
  [✔️] StorageDrawers-1.7.10-1.10.9
  [✔️] Sync-4.0.1
  [✔️] TConstruct-1.7.10-1.8.8
  [✔️] Teletubbies-1.7.10-0.5.4
  [✔️] TextureGeneratorLib-1.7.10_vBeta2
  [✔️] Thaumcraft-1.7.10-4.2.3.5
  [✔️] ThermalExpansion-[1.7.10]4.1.5-248
  [✔️] ThermalFoundation-[1.7.10]1.2.6-118
  [✔️] TrailMix-4.0.0
  [✔️] Translocator-1.7.10-1.1.2.16-universal
  [✔️] twilightforest-1.7.10-2.3.7
  [✔️] Vampirism-1.7.10-0.7.9
  [✔️] VoltzEngine-1.7.10-1.9.14b302
  [✔️] Waila-1.5.10_1.7.10
  [✔️] WailaHarvestability-mc1.7.10-1.1.6
  [✔️] Wawla-1.0.5.120
  [✔️] witchery-1.7.10-0.24.1
  [✔️] WTFCaveBiomes-1.7.10_v1.6
  [✔️] WTFCore-1.7.10_v1.7
  [✔️] yafm-1.0.3

Params:
  --username  --version MultiMC5 --gameDir C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/instances/Kinda Crazy Craft/minecraft --assetsDir C:/Users/Europack/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 3320

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
