### ISSUE TITLE
MultiMC couldn't extract native Jar

### ISSUE THREAD

**Issue by SILENTxICE** [MultiMC/Launcher#4607]
I was playing plenty of Minecraft 12.2 Pack yesterday but when I went to start it today and received the following error was thrown: Couldn't extract native jar 'C:/Users/kaipe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar' to destination 'C:/Users/kaipe/Downloads/mmc-stable-win32/MultiMC/instances/The 1.12.2 Pack/natives'

Below is my pastebin of the full error log
https://paste.ee/p/Fg5bd

**Comment by phit** [comment]
restart your PC

**Comment by Willyrwyu5** [comment]
This has happened to me as well, and restarting has not worked. What do i do? 
(this is the error)
Unable to extract native files.
Error details: Minizip error while extracting: -111
Filename on disk: lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
Path: C:\Users\willj\curseforge\minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
Exists: File
