### ISSUE TITLE
Issue with 1.8.9 forge

### ISSUE THREAD

**Issue by 1Lightspeed1** [MultiMC/Launcher#4611]
### Operating System

Windows

### Description of bug

I'm trying to get 1.8.9 forge to work on my MultiMC, but it is always showing me this:
https://paste.ee/p/Iw9Ii
This issue always occurs whenever I install Forge, so I'm not sure what's happening. Can someone help me please?
Forge Version: 11.15.1.2318 (released on December 8, 2017)
OptiFine Version: 1.8.9 HD U M5

### Steps to reproduce

none

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ALIAS-001** [comment]
I tried to load Oceanblock 1.12.0 from FTB and the error I get is ReAuth unable to load correctly. I also get 2 mods failing to load as well, but I remember not being able to get oceanblock to work on multimc. 

Although ReAuth can handle Microsoft accounts now, I don't think it's able to apply that to legacy versions of Minecraft when it was only Mojang.

**Steps to reproduce**:
Install Oceanblock from FTB
Run Oceanblock with multimc
Once the game loads, forge will tell you what happened.

**Comment by ALIAS-001** [comment]
Your optifine is a mod. Try adding forge to the instance.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by 1Lightspeed1** [comment]
Thanks @phit your suggestion helped a lot I can run 1.8.9 forge now.
