### ISSUE TITLE
MultiMC Doesn't detect other Java versions

### ISSUE THREAD

**Issue by ALIAS-001** [MultiMC/Launcher#4612]
### Operating System

Windows

### Description of bug

When selecting the path of the java runtime, It only detects java 17.0.2
Im not sure how java numbers their versions so here's the folder names for each
- jdk1.8.0_301
- jdk-16.0.1
- jdk-17
- jdk-17.0.2
- jre1.8.0_321

They all have Javaw.jar in their bin folders

### Steps to reproduce

1. Have both java 17 and 8
2. Settings > Java > Java Runtime > Auto-Detect

### Suspected cause

Might be something in how it auto detects?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you put them? and from what vendor are they

**Comment by ALIAS-001** [comment]
1. All versions are located in C:\Program Files\Java
2. every version was downloaded from Oracle

**Comment by phit** [comment]
MultiMC version? The detection is based on registry keys the Java installer sets during install, did you use the portable Oracle download?

**Comment by ALIAS-001** [comment]
FIXED
It was a problem with the registry keys. I had to reinstalll java 8 on my computer.
