### ISSUE TITLE
MultiMC Instance Frozen on start (Stuck on Mojang Logo)

### ISSUE THREAD

**Issue by Areaxis** [MultiMC/Launcher#4614]
### Operating System

Windows

### Description of bug

The Minecraft Window a.k.a the instance freezes in the Mojang logo on startup. This specifically happens for the beta version of the game (in my case it is b1.7.3).

### Steps to reproduce

- Start MultiMC
- Start Minecraft instance b1.7.3
- Freeze on Startup (Mojang Logo)

### Suspected cause

https://paste.ee/p/MyYKR

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please try Java 8 Update 232 or older, you can get old versions for example here https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
