### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by MRSirBOB** [MultiMC/Launcher#4617]
Hi there,

I had my game crash on me after crafting a vault crystal.
Since then it will not open the world, it just crashes out.
[Crash Report.txt](https://github.com/MultiMC/Launcher/files/8402808/Crash.Report.txt)

See attached report.

**Comment by MRSirBOB** [comment]
Any help would be greatly appreciated

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
