### ISSUE TITLE
can't update multiMC

### ISSUE THREAD

**Issue by Axilotl17** [MultiMC/Launcher#4620]
### Operating System

Linux

### Description of bug

![image](https://user-images.githubusercontent.com/78441708/161441793-355c6c7a-b027-4e59-97b9-5509a9530a01.png)

Update failed

### Steps to reproduce

try to update on arch linux

### Suspected cause

no clue, probably arch incompatibility 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
whatever package you are using is broken, either get the tarball from the official website or use this https://github.com/MultiMC/multimc-pkgbuild/blob/master/README.md
