### ISSUE TITLE
Unable to Launch Modpack

### ISSUE THREAD

**Issue by SkyDragon720** [MultiMC/Launcher#4622]
### Description of bug

I created a new instance and installed Roguelike Adventures and Dungeons modpack using the CurseForge option. MultiMC would then freeze up for a few minutes before quickly downloading all of the necessary mods. Then, I click launch but not one second later, the log would pop up saying "exiting with -1, Process exited with code -1." I'm honestly not sure where I went wrong. My log is here: https://paste.ee/p/Njz5D.

### Steps to reproduce

1. clicked "Add Instance"
2. Clicked "Curseforge" button
3. searched for "Roguelike Adventures and Dungeons" modpack
4. clicked "Install"
5. after installation, clicked "Launch"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older
