### ISSUE TITLE
Multimc Isn't starting mc

### ISSUE THREAD

**Issue by Jonnytheone** [MultiMC/Launcher#4624]
### Operating System

Windows

### Description of bug

I opened Multimc and i put some mods to help with fps. When i clicked launch, it said "Minecraft 1.18 Pre Release 2 and above require the use of Java 17". I am currently using 1.18.2 so i am confused. 

### Steps to reproduce

* Open Multimc
* Open a new instance
* Click "Edit Instance"
* Go to "Loader Mods"
* Add the mods 
* Click "Launch"

### Suspected cause

I do not know what could be causing the problem.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
