### ISSUE TITLE
Fabric loader making 1.16.1 crash with few mods

### ISSUE THREAD

**Issue by Spezzu** [MultiMC/Launcher#4632]
### Operating System

Windows

### Description of bug

I have instance for 1.16.1 and I want to speedrun minecraft. Did everything told on this video: https://youtu.be/GAbnKAyireM
When I launch the game, it gives me a red issue code. It should run normally with the speedrun mods inside. It runs if I delete the fabric loader but without the mods, of course. I have tried multiple fabric loader versions and have reinstalled Multimc many times, changed the jawaw.exe location between the two ones but nothing works :/

### Steps to reproduce

Issue code in red: 
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.16.1' failed to process:
https://maven.fabricmc.net/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
https://maven.fabricmc.net/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
https://maven.fabricmc.net/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm/9.2/asm-9.2.jar

Whole code:
MultiMC version: 0.6.15-3247

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.156.12.57, 108.156.12.40, 108.156.12.63, 108.156.12.37]

session.minecraft.net resolves to:
    [34.192.124.100, 107.23.156.212, 34.197.136.50]

textures.minecraft.net resolves to:
    [108.156.22.106, 108.156.22.128, 108.156.22.122, 108.156.22.97]

api.mojang.com resolves to:
    [108.156.22.75, 108.156.22.3, 108.156.22.94, 108.156.22.58]

Minecraft folder is:
C:/Users/Leon/Downloads/mmc-stable-win32/MultiMC/instances/1.16.1/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.2/bin/javaw.exe

Checking Java version...
Java is version 17.0.2, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.16.1' failed to process:
https://maven.fabricmc.net/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
https://maven.fabricmc.net/net/fabricmc/intermediary/1.16.1/intermediary-1.16.1.jar
https://maven.fabricmc.net/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
https://maven.fabricmc.net/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
https://maven.fabricmc.net/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
https://maven.fabricmc.net/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
https://maven.fabricmc.net/org/ow2/asm/asm/9.2/asm-9.2.jar

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Xetaxheb** [comment]
Can you try again with a newly extracted multimc? Launch after fabric is installed and launch after every single one of the mods you install until you find a culprit. When you do end up with a crash, please try the rest without that mod (1 by 1) and if those work, load only the problem mod and tell us which it is; also helpful would be uploading your MultiMC.0.log from that single-mods crash.

**Comment by Spezzu** [comment]
I already fixed it! Not a bug, it's my fsecure which blocked the maven.fabricmc.net site, unblocked it and started working. Thank you and sorry for bothering you! :D
