### ISSUE TITLE
Hope to be compatible with a new modpack format.

### ISSUE THREAD

**Issue by huangsijun17** [MultiMC/Launcher#4638]
### Role

Player / Modpack author / Server administrator

### Suggestion

Compatible with a mod pack format on a Chinese MC forum.

### Benefit

There are a certain number of MultiMC Chinese users who need or will need to import this integration package.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This modpack format evolved from the HMCL modpack format. It is released as a Zip archive. The first layer of the archive contains overrides folder and manifest.json, mcbbs.packmeta files.
The creator release page of this mod pack:
https://www.mcbbs.net/thread-1247765-1-1.html

Example of modpack:
[https://wwu.lanzout.com/b030qzdtc](https://wwu.lanzout.com/b030qzdtc) (password: 25xc)

**Comment by Janrupf** [comment]
Just a heads up: mcbbs.net is blacklisted by [StopModReposts](https://stopmodreposts.org/)

**Comment by phit** [comment]
the site no longer seems to exist
