### ISSUE TITLE
you probably need to migrate to a microsoft account https://multimc.org/posts/microsoft-migration.html

### ISSUE THREAD

**Issue by blerrp** [MultiMC/Launcher#4639]
you probably need to migrate to a microsoft account https://multimc.org/posts/microsoft-migration.html

_Originally posted by @phit in https://github.com/MultiMC/Launcher/issues/4601#issuecomment-1079494387_

**Comment by blerrp** [comment]
Mojang accounts should still work and be supported in multimc! I migrated to microsoft and now I am unable to log back inside permanently

**Comment by phit** [comment]
please don't make new issues for no reason and use the existing issue
