### ISSUE TITLE
Install Files

### ISSUE THREAD

**Issue by Sussy-OS** [MultiMC/Launcher#4640]
### Role

When I downloaded MultiMC, I was very confused where to put the files.

### Suggestion

I would like to have install files for Linux, Windows, and Mac

### Benefit

So that people like me do not get confused about where to put the files, and how to uninstall the MultiMC5 client.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Here is the Windows install file I created:
[MultiMC-Install.exe](https://www.dropbox.com/s/z2fbm9tbctewwif/MultiMC-Install.exe?dl=1)
If this gets added, I will make install files for Linux and Mac as well.
Please take this offer into consideration.

**Comment by phit** [comment]
no

**Comment by Sussy-OS** [comment]
👍
