### ISSUE TITLE
can't launch alpha 1.2.6 on mac

### ISSUE THREAD

**Issue by soocc** [MultiMC/Launcher#4642]
**error:**

MultiMC version: 0.6.15-3246

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.230.84.35, 54.230.84.64, 54.230.84.43, 54.230.84.54]

session.minecraft.net resolves to:
    [107.23.156.212, 34.197.136.50, 34.192.124.100]

textures.minecraft.net resolves to:
    [18.65.229.16, 18.65.229.70, 18.65.229.21, 18.65.229.19]

api.mojang.com resolves to:
    [54.192.18.21, 54.192.18.15, 54.192.18.6, 54.192.18.107]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/a1.2.6/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 11.0.3, using 64-bit architecture, from Oracle Corporation.

Main Class:
  

Native path:
  /Applications/MultiMC.app/Data/instances/a1.2.6/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/a1.2.6/minecraft-a1.2.6-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: a1.2.6", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 7908

Using onesix launcher.

Launching with applet wrapper...
28
Setting user: soocc, token:<ACCESS TOKEN>:<PROFILE ID>
Failed to load options
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at gq.a(SourceFile:150)
	at gq.<init>(SourceFile:52)
	at net.minecraft.client.Minecraft.a(SourceFile:210)
	at net.minecraft.client.Minecraft.run(SourceFile:559)
	at java.base/java.lang.Thread.run(Thread.java:834)
org.lwjgl.LWJGLException: Native cursors not supported
	at org.lwjgl.input.Cursor.<init>(Cursor.java:88)
	at oi.<init>(SourceFile:32)
	at net.minecraft.client.Minecraft.a(SourceFile:220)
	at net.minecraft.client.Minecraft.run(SourceFile:559)
	at java.base/java.lang.Thread.run(Thread.java:834)
Apr 15, 2022 8:46:04 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.OSXEnvironmentPlugin

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
OpenAL initialized.

**Comment by phit** [comment]
please try https://github.com/MultiMC/Launcher/wiki/Java-on-macOS

**Comment by shibahaczix** [comment]
use myMC

**Comment by Ectalite** [comment]
I don't know if it's related, but I can't start Minecraft 1.4.7 
https://paste.ee/p/q988B

**Comment by Ectalite** [comment]
> use myMC

Could you send the link ?

**Comment by phit** [comment]
@soocc  This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.

**Comment by Ectalite** [comment]
I think it's a issue with minecraft and is not related to multimc.
