### ISSUE TITLE
1.16.5 forge in MultiMc is always shutdown in seconds... EDIT: just instal the latest version of forge 1.16.5

### ISSUE THREAD

**Issue by Gaisrick** [MultiMC/Launcher#4644]
### Operating System

Windows

### Description of bug

I don't know what is happening. I downloaded forge (the recommended one) from MultiMC in a new 1.16.5 file. I have the latest java, which is 1.8.0_321 in the C drive, MultiMc files also In C drive.
Here is the Log:
https://paste.ee/p/gAsDS

### Steps to reproduce

....

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
