### ISSUE TITLE
MultiMC Window crashes when Clicking edit instance on some instances.

### ISSUE THREAD

**Issue by inmymunnn** [MultiMC/Launcher#4645]
### Operating System

Windows

### Description of bug

I have noticed this bug for about a year.

https://user-images.githubusercontent.com/96924315/163586741-7e95d940-6f93-4f75-b527-b9135df847ba.mp4

 

### Steps to reproduce

I don't know why this happens. If there is a MultiMC log I don't know where it is, so if there is I could provide it. I think it might happen because MultiMC crashed some random day when I clicked edit instance and this has happened since to those few instances. Sometimes it can open it. Like the instance I named meteor. As I was recording a video (it ended up being to big to be put here.)  it actually opened it. The other times I tried it crashed.    I noticed the sodium instance was unordinarly massive Instance downloads:
         https://download1477.mediafire.com/8i24046g1qag/y7qvbii7yzz9s8v/sodium1.18.zip
         https://download1653.mediafire.com/gifoodji0jng/jnqhowffb0x95z4/mathax+1.18.zip

### Suspected cause

I noticed that it's mostly fabric instances that do this. I have seen this with a forge instance though.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/4228
