### ISSUE TITLE
MultiMC suspends when game hangs and terminates, doesn't automatically unsuspend.

### ISSUE THREAD

**Issue by Koooper** [MultiMC/Launcher#4647]
### Operating System

Windows

### Description of bug

Sometimes, when a Minecraft instance hangs and is terminated by Windows, the MultiMC process gets suspended and isn't automatically unsuspended. This forces the user to either end the process in Task Manager or unsuspend it in Resource Monitor.

### Steps to reproduce

* Get Minecraft to hang, then terminate it with the "Not Responding" popup.
![image](https://user-images.githubusercontent.com/72723895/163693227-be9f052f-88ad-4fac-a0ea-7442c892a496.png)
* Try to open MultiMC
* ???
* Not profit
* Open Resource Monitor
* See that MultiMC.exe is suspended
![image](https://user-images.githubusercontent.com/72723895/163693341-0ce6c8c6-89b3-4fc9-8afe-95d6a03eeaa0.png)
* Manually unsuspend it
![image](https://user-images.githubusercontent.com/72723895/163693374-f8a7478e-3f99-4d36-8151-3b0fcf50a5fe.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
theres no functionality in MultiMC to suspend itself
