### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by JimmyTheGreat1500** [MultiMC/Launcher#4650]
### Role

I am a Linux and Windows user and I want to play more games on Linux

### Suggestion

I want a Linux port (flatpak preferably but anything would be nice)

### Benefit

So I can play on Linux 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I am a Linux and windows user and on windows this is my launcher of choice, it’s great, but I want to play more on Linux and there isn’t a port or anything for Linux besides like lunar client which isn’t for modding. It’d be awesome if someone ported this over which I imagine wouldn’t be impossible, considering it’s open source and such

**Comment by phit** [comment]
use the linux version from the website? https://multimc.org/#Download
