### ISSUE TITLE
LWJGL Issue

### ISSUE THREAD

**Issue by Permdog99** [MultiMC/Launcher#4655]
### Operating System

Windows

### Description of bug

I made a custom LWJGL for beta 1.7.3 since the one built into MultiMC broke for me but it won't download the jars into the library folders. Here is the json for my custom LWJGL:

> {
    "formatVersion": 1,
    "libraries": [
        {
            "downloads": {
                "artifact": {
                    "sha1": "a91a5631d319c8f50851b731c435cf66eb1d1e7e",
                    "size": 231781,
                    "url": "https://files.betacraft.uk/launcher/assets/libraries/universal/jinput/jinput-2.0.5.jar"
                }
            },
            "name": "net.java.jinput:jinput:2.0.5-fix"
        },
        {
            "downloads": {
                "artifact": {
                    "sha1": "6750639ccafa0cd413ee17c809252d24b4326412",
                    "size": 1042721,
                    "url": "https://files.betacraft.uk/launcher/assets/libraries/universal/jinput/lwjgl-2.9.3-amdfix.jar"
                }
            },
            "name": "org.lwjgl.lwjgl:lwjgl:2.9.3-fix"
        },
        {
            "downloads": {
                "artifact": {
                    "sha1": "6a147878f2d2675fe103f8bd0abee580f722b8a6",
                    "size": 187777,
                    "url": "https://files.betacraft.uk/launcher/assets/libraries/universal/jinput/lwjgl_util-2.9.3.jar"
                }
            },
            "name": "org.lwjgl.lwjgl:lwjgl_util:2.9.3-fix"
        }
    ],
    "name": "LWJGL 2",
    "releaseTime": "2017-04-05T13:58:01+00:00",
    "type": "release",
    "uid": "org.lwjgl",
    "version": "2.9.3-fix",
    "volatile": true
}

And here is the log:

> Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:95)
	at org.lwjgl.Sys.<clinit>(Sys.java:112)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(Minecraft.java:94)
	at net.minecraft.client.Minecraft.run(Minecraft.java:437)
	at java.lang.Thread.run(Thread.java:745)

To me the json doesn't seem broken or anything. The files from those sites work perfectly so idk.

### Steps to reproduce

To reproduce it use that json in MultiMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theofficialgman** [comment]
if that is your whole json, then it is 100% wrong.

there are no natives in your json. refer to the official json for 2.9.3 for the correct format
https://github.com/MultiMC/meta-multimc/blob/master/org.lwjgl/2.9.3.json

**Comment by Permdog99** [comment]
That worked! Thanks!
