### ISSUE TITLE
Non-latin characters shown incorrectly in console on English Windows

### ISSUE THREAD

**Issue by whitebear60** [MultiMC/Launcher#4657]
### Operating System

Windows

### Description of bug

The cyrillic characters are shown as incorrect characters in the console, see screenshot below.
![image](https://user-images.githubusercontent.com/42472132/165074538-b9860607-1be6-4a29-9553-1bca9258c5a5.png)

Windows: 11 21H2 (Build 22000.556) English (International)
MultiMC: 0.6.16-develop-3282

Language for non-Unicode apps in Windows settings: Ukrainian (Ukraine)

### Steps to reproduce

Open any Minecraft instance in MultiMC (used 1.18.1 in screenshot above), load a world
Type in chat some non-latin characters
Switch to console

### Suspected cause

Cyrillic characters should render properly in console

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what font are you using for your Console, this seems mostly to be a font issue, for me it's just all ??? 

![image](https://user-images.githubusercontent.com/2097483/168469001-78efa688-3f15-4837-8085-23eda1cb00a1.png)

**Comment by whitebear60** [comment]
I investigated the problem and found that the problem was in Java that I was using (the bundled one from Minecraft launcher). When I switched to OpenJDK, the problem resolved.

Probably using Java from Minecraft launcher was bad idea...
