### ISSUE TITLE
Hi I have been playing MultiMC for a few years now, but the past few weeks I keep getting the same error, where it is unable to start minecraft. I am on windows 10.

### ISSUE THREAD

**Issue by Zebraqueen8** [MultiMC/Launcher#4660]
[MultiMC log.txt](https://github.com/MultiMC/Launcher/files/8575524/MultiMC.log.txt)

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-117-and-newer

Java 18 isn't supported by Forge
