### ISSUE TITLE
1.8.9 Forge crashing

### ISSUE THREAD

**Issue by 1Lightspeed1** [MultiMC/Launcher#4661]
### Operating System

Windows

### Description of bug

I'm trying to get my instance setup for forge 1.8.9. Everything seems to go smoothly for vanilla, but when I install forge and try to run the launcher, the game instantly crashes without even showing the window.

Can anyone please help me with this? Idk if I'm the only one to ever have a bug like this.
Forge Version: 11.15.1.2318 (released June 8, 2017)
Instance Log: https://paste.ee/p/FMaW1

### Steps to reproduce

1. Open MultiMC, press Add Instance, and click on 1.8.9.
2. Run the instance for a few seconds to load the files.
3. Now, install the Forge version mentioned in the bug description (should be at the very top).
4. Try running the instance.

### Suspected cause

Theories:
There could be something wrong with my file directory and how it matches up with MultiMC files that prevents the launcher from running the instance. It could also be something wrong with Forge, or more specifically, the version of Forge that I'm trying to run.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older

**Comment by 1Lightspeed1** [comment]
ty this helped
