### ISSUE TITLE
Tablet version mismatch on opening

### ISSUE THREAD

**Issue by minhperry** [MultiMC/Launcher#4663]
### Operating System

Windows

### Description of bug

On clicking/launching MultiMC v0.6.15-3247 on Windows 10, first an error box will appear with title "Tablet Version Mismatch" and message "Please reinstall the tablet software.". Closing the error box will then launch the launcher itself without any problem.

Starting the executable from install directory still gives same error.

### Steps to reproduce

(Most likely some conflicts with Wacom driver)

1. Install Wacom Desktop Center as well as Wacom driver
2. Launch MultiMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by minhperry** [comment]
details about environment will be provided if needed

**Comment by phit** [comment]
what makes you think this is in any way caused by MultiMC?

**Comment by minhperry** [comment]
because it triggers on multimc launch so i think it's somehow involved?

**Comment by spannerman79** [comment]
This sounds like the so called "Wacom Desktop Center" is actually hijacking the MultiMC process.  Thinking its some sort of process/program that will use a Wacom tablet.

After doing a little bit of digging this is a **known** issue with Wacom's supposed "software" - even causing conflicts with (on windows) Photoshop, Blender, Krita and even Mudbox.

**Comment by minhperry** [comment]
> This sounds like the so called "Wacom Desktop Center" is actually hijacking the MultiMC process. Thinking its some sort of process/program that will use a Wacom tablet.
> 
> After doing a little bit of digging this is a **known** issue with Wacom's supposed "software" - even causing conflicts with (on windows) Photoshop, Blender, Krita and even Mudbox.

Hi, with what keywords did you search for this?

And from my testing, yes I can confirm that this is Wacom's fault. On restarting the driver acts very weird and force me to start it  from service.msc. Before starting it MMC acted fine, only when it started did the issue start to appear.

Waiting for your reply and I'll close this after.

**Comment by minhperry** [comment]
Edit: Apparenly kill one of the 3 task that is driver related stopped the problem
[There should be 3 with tablet icon and i already kileld one and i forgor the name](https://i.imgur.com/wQVHGK7.png)
