### ISSUE TITLE
Modpack crashes while launching

### ISSUE THREAD

**Issue by Chili1998** [MultiMC/Launcher#4665]
### Description of bug

So far every modpack (e.g. CaveFactory or Stoneblock) keeps crashing while trying to launch.
Tryed to reinstall Java version 8 update 333 (5/02/22) and older version 331, but same effect.
Pastebin link to crash file:
https://paste.ee/p/oAwfM

### Steps to reproduce

Try launching minecraft modpack with MultiMC
Java version either 8u333 or 8u331
Nvidia Graphic driver version 512.59

### Suspected cause

Probably a problem with a Java version, but after reinstalling Java for the third time I am clueless what to do next.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by Chili1998** [comment]
Thanks for the reply. I followed your proposal and it worked
