### ISSUE TITLE
Update the modpacks

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [MultiMC/Launcher#4666]
### Role

I play modded Minecraft

### Suggestion

I want to update my modpacks

### Benefit

This is a crucial feature

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
please use the search as the issue template suggests https://github.com/MultiMC/Launcher/issues?q=is%3Aissue+modpack+update+is%3Aclosed+label%3Aclose%3Aduplicate
