### ISSUE TITLE
Still allowing mojang accounts to be used.

### ISSUE THREAD

**Issue by sizquirt** [MultiMC/Launcher#4673]
### Description of bug

You're not supposed to use mojang accounts anymore and they're just about deprecated, so it wouldn't work forever.

### Steps to reproduce

Just click Add Mojang Account button

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jamierocks** [comment]
I'm confused how this is a bug? Mojang accounts still work for many.

**Comment by sizquirt** [comment]
Should enforce Microsoft accounts as migration is required outside of
MultiMC

**Comment by phit** [comment]
already does, see https://github.com/MultiMC/Launcher/commit/b39410a2c2adbe7027b4a68b3b9ea72a44a15875
