### ISSUE TITLE
[org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft

### ISSUE THREAD

**Issue by flarefluffsune** [MultiMC/Launcher#4674]
### Operating System

Windows

### Description of bug

I downloaded an older version (1.3.9) of Not Too Complicated due to massive amount of issues in the latest versions people are reporting. It appears to load to begin with then CTD's with the fault in title.

Here's the bug report: https://paste.ee/p/VgwsR

### Steps to reproduce

Launch Minecraft

### Suspected cause

Java maybe?

I have tried the packaged java with Minecraft Launcher, the Oracle JDK and the Microsoft OpenJDK java versions.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by flarefluffsune** [comment]
Its 1.16? I thought NTC was 1.18, wow how the hell did I miss that...? Thanks. I guess I am the stupid.

**Comment by flarefluffsune** [comment]
Its still crashing, what am I doing wrong? Here's the log: https://paste.ee/p/MGBrh

I switched it to my Java 331 build.

**Comment by phit** [comment]
read my comment again

**Comment by flarefluffsune** [comment]
Shoot sorry.
