### ISSUE TITLE
i  cant enter in my microsoft account

### ISSUE THREAD

**Issue by nykbocks** [MultiMC/Launcher#4675]
### Operating System

win7  32 bits 

### Description of bug

i put the code in the browser,the site says "now you can use multmc!" but when i came back the mc says "xbox user dont found"
i dont have any xbox in my home,but i make an account just to see if now works,you may now what i get.... how i can make it work!!! Pls read this 

### Steps to reproduce

i click to get the code
i copy the code in the site
i accept
but multimc says"xbox user dont found"

### Suspected cause

i dont now

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
have you bought minecraft?

**Comment by nykbocks** [comment]
yes!

**Comment by phit** [comment]
then login at https://www.xbox.com/en-US/ and finish setting up your profile

**Comment by nykbocks** [comment]
now work,
