### ISSUE TITLE
Kaspersky is saying that MultiMC is a trojan

### ISSUE THREAD

**Issue by juliocoliveira** [MultiMC/Launcher#4678]
### Operating System

Windows

### Description of bug

Kaspersky deleted my MultiMC exe saying it was a trojan.
![image](https://user-images.githubusercontent.com/6606725/168191144-bfb34e72-d424-4585-b319-52ba4cef60ff.png)

I'm sure its a false positive.

### Steps to reproduce

Use MultiMC dev with Kaspersky Security Cloud 21.3.10.391i

### Suspected cause

I don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by juliocoliveira** [comment]
The funny thing is that i sent the exe to virus total and none antivirus said that is a virus/trojan including kaspersky: https://www.virustotal.com/gui/file/4e8adf8bf4fddf38ce3926109dd47c729a480418e12000c73b306c258adf2d26

**Comment by phit** [comment]
report it to kaspersky, nothing we can do about bad software being bad
