### ISSUE TITLE
I'm trying to play Vault Hunters a moded version of minecraft, but When I try to open it it won't work. 

### ISSUE THREAD

**Issue by Migui137** [MultiMC/Launcher#4679]
### Description of bug

It crashes with code -1. Does anyone know how to solve this?
![image](https://user-images.githubusercontent.com/105522164/168390943-d47cbe9b-6f91-4100-ac5f-62f7fd0c81a9.png)

### Steps to reproduce

Install the modpack following the instructions at https://vaulthunters.gg/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RazGiGiTel** [comment]
I have this promlem too 
![image](https://user-images.githubusercontent.com/105528189/168405882-081dff0f-5553-44e4-b1c2-03cd97d0dfd4.png)

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by rubecuga** [comment]
I have another similar problem, can someone help please.

![image](https://user-images.githubusercontent.com/105712753/168782299-07454698-ef67-4919-b883-a40c0e24d5ac.png)

**Comment by RazGiGiTel** [comment]
I was able to launch only through a third-party launcher with a previously installed version of Forge 36.2.25. It will not work through MultiMC, it does not see versions higher than 36.2.24.
