### ISSUE TITLE
Exit code -1, on an instance of tekkit 3.14 pi(or ANY OTHER VERSION EVEN VANILLA except sometimes it gives exit code 255 instead)

### ISSUE THREAD

**Issue by KORPSE-PAINT-PISEAG** [MultiMC/Launcher#4680]
### Operating System

_Ubuntu 20.04.4 LTS_

### Description of bug

I tried to launch the game but it failed to start

link to log:https://paste.ee/p/OrMpY

### Steps to reproduce

lanch an offline or online instance of tekkit 3.14(or ANY OTHER VERSION EVEN VANILLA)

### Suspected cause

maybe a java issue idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
launch online, in that log it cant download the needed files
