### ISSUE TITLE
Crash On Loading

### ISSUE THREAD

**Issue by ssaagamemer** [MultiMC/Launcher#4681]
### Operating System

Linux

### Description of bug

i Try To Play mc buf it crash every time
log: https://paste.ee/p/zNSJ3

### Steps to reproduce

Download Some Mc Or Modpack
Launch It
Then Crash

### Suspected cause

Some Lag

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
