### ISSUE TITLE
[Suggestion] When Logging into an MS account, it would be helpful to have a button to copy the code to clipboard.

### ISSUE THREAD

**Issue by fooeyround** [MultiMC/Launcher#4684]
### Role

new Versions of Java for old mc and just as a launcher.

### Suggestion

have a save to clipboard icon in the Add Microsoft Account Screen (could be from clicking on the code))

### Benefit

it would be easier to login to mc with an MS account

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by JacktheDevel0per** [comment]
Ofc not (it would be a button with an icon or text or smth if they add it, or click on it with maybe hover of copy so I don’t have to move onto my keyboard

**Comment by phit** [comment]
was added 2 years ago https://github.com/MultiMC/Launcher/commit/86f68389c9056279c198be3ab0854f1a607dc24f
