### ISSUE TITLE
MultiMC Loads all instances except Vanilla

### ISSUE THREAD

**Issue by FlynnStingray** [MultiMC/Launcher#4685]
### Description of bug

So I just got Multi MC today and I've come across a bizarre problem when using it and that's that it loads no Vanilla Instances I put into it. 
Saying to me that Minecraft 1.18 Pre Release 2 and above require the use of Java 17 Despite the fact that I'm on the most recent version of Java, being Java 18.

This doesn't happen with Pixelmon at least and it makes me wonder if I may have set something up incorrectly

### Steps to reproduce

Here's the Instance Log for example when I try to load a Vanilla Instance 

MultiMC version: 0.6.15-3247

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.226.176.44, 13.226.176.63, 13.226.176.40, 13.226.176.38]

session.minecraft.net resolves to:
    [52.7.153.255, 54.173.66.187, 54.164.34.185]

textures.minecraft.net resolves to:
    [13.226.184.70, 13.226.184.4, 13.226.184.61, 13.226.184.27]

api.mojang.com resolves to:
    [99.86.102.79, 99.86.102.73, 99.86.102.59, 99.86.102.111]

Minecraft folder is:
C:/MultiMC/instances/1.18.2/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_333/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_333, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/MultiMC/instances/1.18.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Using system OpenAL.
Using system GLFW.

Libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Params:
  --username  --version MultiMC5 --gameDir C:/MultiMC/instances/1.18.2/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Minecraft 1.18 Pre Release 2 and above require the use of Java 17
Clipboard copy at: 15 May 2022 23:08:55 -0500

### Suspected cause

I probably messed something up for something is just not clicking in the code

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you are on Java 8 (1.8) you need Java 18 (1.18) https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
