### ISSUE TITLE
Failure Launch Vanilla 1.16.5

### ISSUE THREAD

**Issue by swear01** [MultiMC/Launcher#4686]
### Operating System

Windows

### Description of bug

crash report https://paste.ee/p/BjDdy
Minecraft 1.16.5 Vanilla
crash On Initialition
Tried HotSpot JVM OpenJ9 Java 16 8u332 8u282

### Steps to reproduce

IDK How
The same steps work on my laptop

### Suspected cause

MultiMC
Since Mojang Launcher with OpenJ9 8u332 init successfully

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide your full log, start the game and then click upload log in the console window

**Comment by swear01** [comment]
https://paste.ee/p/psYcB

**Comment by phit** [comment]
why did you turn on system library workarounds, go in the settings and turn that off

**Comment by swear01** [comment]
Thanks. It works!
