### ISSUE TITLE
Searching CurseForge modpacks from within MultiMC fails

### ISSUE THREAD

**Issue by James103** [MultiMC/Launcher#4687]
### Operating System

Windows

### Description of bug

Attempting to search for modpacks on CurseForge fails and gives zero results no matter the search query.
The same search terms on the CurseForge website do give results.

<details>
<summary> Log when attempting to search and it fails </summary>

```
   14.462 D Task "NetJob(Flame::Search)" starting for the first time
   14.462 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.546 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   14.546 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.546 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.585 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   14.585 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.585 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.627 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   14.628 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.628 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.669 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"  with reason  QNetworkReply::NetworkError(ContentOperationNotPermittedError)
   14.669 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
   14.669 C Task "NetJob(Flame::Search)" failed:  "Job 'Flame::Search' failed to process:\nhttps://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=valhelsia&sectionId=4471&sort=0"
```
</details>

This used to work a few weeks ago, but it's broken now.

### Steps to reproduce

1. Open MultiMC
2. Click "Add Instance"
3. In the left panel, click "Curseforge"
4. Enter any search term, such as "Valhelsia", then click "Search" or press enter.
5. Open https://www.curseforge.com/minecraft/modpacks in a browser.
6. Click where it says "Search Modpacks" and type the same search term.
7. Notice that the search gives results.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please update to the development build
https://github.com/MultiMC/Launcher/wiki/Switching-update-channels

**Comment by James103** [comment]
@phit What you said won't work for adding CurseForge modpacks from within MultiMC.
Actually, please do the following:

1. Use another launcher to download and install the modpack (PolyMC or the official CurseForge launcher).
2. Import the downloaded instance to MultiMC by creating a new instance with the same Minecraft and Forge/Fabric version, then copying the entire `.minecraft` folder from the imported instance in the other launcher.

**Comment by phit** [comment]
it did at the time..

**Comment by JustZacTTv** [comment]
what about people who cant use Curse launcher

**Comment by NicciZar** [comment]
The newest developer built doesn't have the option to directly browse CurseForge anymore.
![image](https://user-images.githubusercontent.com/43537611/172065157-8ba1154a-c020-46e1-8088-e53f8ecaac77.png)

It is still there in the stable release though. (but no search results)

**Comment by Luke112211** [comment]
And what is the solution for the problem?
Can‘t fix it too.
