### ISSUE TITLE
Hi , I have a problem with this error, can someone help me. It's the error code -1

### ISSUE THREAD

**Issue by rubecuga** [MultiMC/Launcher#4688]
### Operating System

Windows

### Description of bug

I can not enter the game because of the problem code -1 and I do not know how to repeare it

### Steps to reproduce

![image](https://user-images.githubusercontent.com/105712753/168783022-d664dab7-0d7b-4a02-b4e0-5b7889885a36.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```
