### ISSUE TITLE
Modpacks from Curseforge don't load/show

### ISSUE THREAD

**Issue by Them-Bones** [MultiMC/Launcher#4689]
### Operating System

Windows

### Description of bug

![Screenshot (10)](https://user-images.githubusercontent.com/105728990/168830255-d1c292aa-fec9-4f49-8dfd-3719bb366a2f.png)

When adding a new instance, there's simply no modpacks available for curseforge (FTB, ATLauncher, etc work fine).
It's not just me because I told my friend to try out the launcher and curseforge also didn't load any packs for him (He had a fresh install).

### Steps to reproduce

No clue.

### Suspected cause

Tell me.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Daefaer** [comment]
Hello,
Isn't it linked to the recent CurseForge API change ?
(See https://medium.com/overwolf/the-curseforge-official-api-is-now-live-d314606355c2)

**Comment by phit** [comment]
please update to the development build
https://github.com/MultiMC/Launcher/wiki/Switching-update-channels

**Comment by ayMason** [comment]
I am on development build and it's still not showing

**Comment by phit** [comment]
what version? did you try actually searching for anything?

**Comment by ayMason** [comment]
Ah yeah searching worked, nothing pops up still when you click CurseForge but yeah you can still search, cheers

**Comment by klugemonkey** [comment]
I'm on development build 0.6.16-develop-3404 and CurseForge is missing from the list of instance types.  Doesn't seem like there is any code for importing a mod pack from CurseForge under launcher/modplatform.  

Trying to download a CurseForge mod pack manually (Enigmatica 6 Expert for example)  using the Import from zip, resulted in an error message saying "Archive does not containe a recognized modpack type".  

As far as I can tell, support for CurseForge is no longer in the MultiMC codebase and this issue should not be closed as  without referring to a commit that resolves the bug, or a proper explaination as to the feature regression and what the plan is moving forwards.

**Comment by klugemonkey** [comment]
Commit in question is here:
https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

"Import from locally installed packs from the official clients will be
the replacement, but for now, you will have to do that manually."

Please explain how that is done exactly from MultiMC.

**Comment by phit** [comment]
at the time the issue was closed since the bug was fixed, the commit you linked happened **two days** after that. 

the latest development versions now have a tab to import locally installed packs from the FTB App (which can also install CF packs), please just use the issue search instead of making demands here

**Comment by klugemonkey** [comment]
RIP.
