### ISSUE TITLE
CurseMeta will go down permantly soon.

### ISSUE THREAD

**Issue by dries007** [MultiMC/Launcher#4690]
### Role

I maintain CurseMeta.

### Suggestion

I leave that up to you.

### Benefit

I won't get a bunch of traffic or help request anymore :)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As discussed on Discord, CurseMeta will go away soon as the underlying API is now officially dead.

I make this ticket so all discussions can be had here and I know when this is closed, MultiMC is no longer using it.

Fun fact, I get about 50M monthly requests from MultiMC.

**Comment by Janrupf** [comment]
I guess it's time to say goodbye now. Thanks for the awesome project!

**Comment by flarefluffsune** [comment]
Uh, would this be why I cannot load CurseForge mod packs in the new instance manager? Just asking here in case this isn't a bug because of this, but if it is can be made its own issue.

**Comment by Janrupf** [comment]
> Uh, would this be why I cannot load CurseForge mod packs in the new instance manager? Just asking here in case this isn't a bug because of this, but if it is can be made its own issue.

Partially, yes. The development version of MultiMC includes a fix, so you can use it for now.

**Comment by phit** [comment]
removed completely with https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

**Comment by admincheg** [comment]
Just for history. I wrote simple script, for fetching mods by manifest.json from CurseForge modpaks.
For use you should provide API_KEY as environment variable and path to manifest.json file. Script strongly stable, but can produce unexpected result, be careful. Of course this script can be written better, but what do you want for 5-min script.

```
#!/bin/bash

API_KEY=${API_KEY:='NONE'}
MANIFEST_PATH="$1"

if [[ -z ${API_KEY} || ${API_KEY} == "NONE" ]]; then
  echo "API_KEY from CurseForge should be defined!"
  exit 1
fi

if [[ -z ${MANIFEST_PATH} || ! -f ${MANIFEST_PATH} ]]; then
  echo "Path to manifest.json is not specified or file not found"
  exit 1
fi

urlencode() {
  python3 -c "import sys, urllib.parse as ul; print (ul.quote_plus(sys.argv[1]))" "${1}"
}

[[ ! -d mods ]] && mkdir mods/

ids=$(cat ${MANIFEST_PATH}  | jq -r '.files | .[] | .fileID' | tr '\n' ',' | sed 's/,$//')
curl -s -X POST -H"Content-Type: application/json" -H "X-api-key: ${API_KEY}" --data '{"fileIds":['${ids}']}' https://api.curseforge.com/v1/mods/files | jq -r '.data[] | "\(.fileName)|\(.id)|\(.downloadUrl)"' | while IFS="|" read name id url; do
  id1=${id::4}
  id2=$(echo ${id:4} | sed 's/^0*//')
  download_name=$(urlencode "$name")
  download_url="https://media.forgecdn.net/files/${id1}/${id2}/${download_name}"
  if [[ -f "mods/${name}" ]]; then
    echo "${name} already downloaded"
    continue
  fi
  status=$(curl -s --write-out "%{http_code}" --output "mods/${name}" "${download_url}")
  [[ $? -gt 0 ]] && exit
  if [[ ${status} != 200 ]]; then
    echo "Status is: $status"
    echo "Metadata url: $url"
    echo "Prepared url: $download_url"
    echo "Mod name: $name"
    exit
  fi
  echo "Mod $name downloaded with ${status}"
done
```

Fun fact - you can use download-url endpoint at CurseForge API, but time to time they doesn't return any URL to file, just null (but if you build URL by self - file will be found)
