### ISSUE TITLE
Will Amulet Editor be supported in future versions of MultiMC?

### ISSUE THREAD

**Issue by prpjzz** [MultiMC/Launcher#4696]
### Role

I use to export schema files

### Suggestion

You can update the Amulet Editor instead of MCEdit because this software has not been updated for too long (available only in version 1.12.2 and below)

### Benefit

I need the Amulet Editor to handle tasks related to exporting schema files as quickly as possible.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It's been over 6 years, but MCEdirt seems to have stopped developing new versions.

**Comment by phit** [comment]
see https://github.com/MultiMC/Launcher/issues/3713
