### ISSUE TITLE
New Instance - Curseforge Modpack

### ISSUE THREAD

**Issue by lullaby66** [MultiMC/Launcher#4698]
### Operating System

Windows

### Description of bug

when I look for a curseforge modpack, nothing appears, I waited a long time but still nothing
![screenshot ](https://user-images.githubusercontent.com/94006475/169476788-a9fe9ec9-32d7-4ff6-932c-b36d16306394.png)
 

### Steps to reproduce

Search a curseforge modpack
![screenshot ](https://user-images.githubusercontent.com/94006475/169476788-a9fe9ec9-32d7-4ff6-932c-b36d16306394.png)
 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the curseforge integration has been shut down https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
