### ISSUE TITLE
Modrinth Output Support

### ISSUE THREAD

**Issue by okunamayanad-zz** [MultiMC/Launcher#4699]
### Role

I make Forge and Fabric modpacks

### Suggestion

Export instances in the Modrinth modpack format

### Benefit

so that way MultiMC will have a way to upload instances to Modrinth

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by okunamayanad** [comment]
Oh and also here is the documentation for modpack format
https://docs.modrinth.com/docs/modpacks/format_definition/

**Comment by arthomnix** [comment]
Unfortunately MultiMC doesn't know where you got your mods from, which is required for Modrinth packs (they are essentially just a list of download links rather than containing all the actual jars). If all the mod jars were included it would likely be too big for Modrinth.

**Comment by wafflecoffee** [comment]
It would be possible to use the [reverse hashes lookup](https://docs.modrinth.com/api-spec/#tag/version-files/operation/getLatestVersionsFromHashes) route to check for any files which are available on Modrinth, then put the rest in overrides. That's essentially how ATLauncher does it.
