### ISSUE TITLE
Issue about modpacks installed on multi mc crashing on pre loading screen

### ISSUE THREAD

**Issue by BannedExperiment** [MultiMC/Launcher#4700]
### Operating System

Windows

### Description of bug

So Ive recently started using multi mc once again. And I personally love playing modpacks so ive decided to download one and play, i chose The 1.12.2 Pack on Technic Launcher, tried opening it but it crashed. So ive tried another modpack thinking there might be problem with the modpack itself. So this time i chose FTB Direwolf20 1.16, installed it but once again it crash same as the previous one. Then i installed FTB Ultimate reloaded and it crashed like any other modpack, then ive decided to check github but couldnt really find an answer so came here. Vanilla and Forge with Optifine installed minecraft works and im using the right java version for each version.

https://paste.ee/p/IPcW1 here is the crash log

### Steps to reproduce

1. I open Multi MC 0.6.15-3247
2. Try to open a modpack i installed on multi mc
3. Pre loading screen opens
4. Crashes after a few seconds

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please check the 1.12 and earlier section in the wiki https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
