### ISSUE TITLE
Exit code -1, happens when I just straight up install Forge into the instance.

### ISSUE THREAD

**Issue by TotakaObsidian** [MultiMC/Launcher#4701]
### Operating System

Windows

### Description of bug

As the title says, just installing Forge into the instance and launching it forces an exit code -1 I don't even have mods installed and yet it still fails. Is there something I'm missing or am I just dumb?

![image](https://user-images.githubusercontent.com/101663397/169631152-039b5d1b-9ab2-49da-9bd8-a5df7ba4b7e4.png)

### Steps to reproduce

Just install Forge in the instance.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
