### ISSUE TITLE
CurseMeta is done

### ISSUE THREAD

**Issue by admincheg** [MultiMC/Launcher#4702]
### Operating System

Linux

### Description of bug

ModPacks from CurseForge ca't be installed, because CurseMeta is not working.

Any request returns

`Please migrate towards the official API. This service has been deprecated for <b>years</b>.`

### Steps to reproduce

1. Download any modpack from CurseForge
2. Try to install

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
see https://github.com/MultiMC/Launcher/issues/4690 and https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
