### ISSUE TITLE
Typo in Exit note.

### ISSUE THREAD

**Issue by FeedTheChunk** [MultiMC/Launcher#4704]
### Description of bug

Please **not** that usually neither exit code nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

Please **note** that usually neither exit code nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Exit MC.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
yeah also missing a comma, should be 

> Please note that usually neither exit code, nor its description are enough to diagnose issues!

**Comment by FeedTheChunk** [comment]
At the risk of being pedantic it probably should read: Please note that usually neither the exit code, nor its description are enough to diagnose issues!
