### ISSUE TITLE
Not compatible with curseforge

### ISSUE THREAD

**Issue by CrypticalCoop** [MultiMC/Launcher#4705]
The version that is linked from fabricmc.net shows that I import or choose from CurseForge.  Anything that I have downloaded from CurseForge will not be imported due to a failure to ID mods.  When I click on the CurseForge option there it does not populate any mods.

**Comment by admincheg** [comment]
You're not first! :D

Welcome to the club, buddy.

https://github.com/MultiMC/Launcher/issues/4702
https://github.com/MultiMC/Launcher/issues/4690

I prepared simple script for downloading mods from CurseForge as workaround.

**Comment by HeyaGlitz** [comment]
PolyMC has a fix for this, try it out
