### ISSUE TITLE
Error importing Pax modpack

### ISSUE THREAD

**Issue by ThybeVB** [MultiMC/Launcher#4708]
### Operating System

Windows

### Description of bug

Hello, recently (a few weeks ago) I tried to import a pax-generated modpack into MultiMC and this worked fine. It downloaded all the mods normally and everything worked fine.
I tried this again yesterday, but this time it errors with "Unable to resolve mod IDs: Some mod ID resolving tasks failed".

I then tried to do the same on the development branch of the launcher. This time I got a different error "Archive does not contain a recognised modpack type".

Was support for this dropped? It used to work just a few weeks ago, so I'm a bit puzzled.
In the annex I put the pax zip which I tried to import.
[Cronk VI.zip](https://github.com/MultiMC/Launcher/files/8749073/Cronk.VI.zip)

Thanks!

### Steps to reproduce

Add an instance -> Import from zip -> Import any pax generated modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues?q=is%3Aissue+is%3Aclosed+curseforge
