### ISSUE TITLE
Import from zip busted for Curse packs

### ISSUE THREAD

**Issue by Norexlen** [MultiMC/Launcher#4709]
### Operating System
Windows 10 & Arch Linux
_No response_

### Description of bug

after starting to import the window goes to (Not Responding).
in a moment a windows shows up with a progress bar and text "Resolving mod IDs" this goes on for some time and shows an error
Unable to resolve mod IDs: Some mod ID resolving tasks failed.

tested with a zip that worked some time ago but still failed in the same way as a newly downloaded file

attempted on Arch and windows 10 with fresh installs

New Instance > Curse Forge > search doesn't show any results

### Steps to reproduce

Add Instance button
Import From Zip
Browse to .zip downloaded from curseforge page
OK

### Suspected cause

curse forge may have changed how mod ids are processed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KaidenP** [comment]
Same Issue. I no longer have a copy of the log but it looked like the API MultiMC uses has been depreciated and shut down

**Comment by phit** [comment]
> I have searched the issue tracker and did not find an issue describing my bug. 

no you didn't
