### ISSUE TITLE
Cannot display the cruseforge screen

### ISSUE THREAD

**Issue by hi23392** [MultiMC/Launcher#4710]
### Description of bug

As you can see, cruseforge cannot be displayed, how can I fix it?

### Steps to reproduce

![螢幕擷取畫面 2022-05-23 180716](https://user-images.githubusercontent.com/87599137/169797378-a2177a91-1e00-4d5d-8d6b-28116c6c18cd.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Curseforge support has been removed https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc
