### ISSUE TITLE
MultiMC opens text editor instead of file manager on Gnome when VScodium is installed

### ISSUE THREAD

**Issue by coreybruce** [MultiMC/Launcher#4712]
### Description of bug

When I go to config folder or Minecraft Folder it will open vscode when installed on Gnome Manjaro

### Steps to reproduce

Click on either option and it will open up VSCodium is installed 

### Suspected cause

No idea, this is a annoying and wierd bug when it should be looking for a default file manager 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
MultiMC just calls https://doc.qt.io/qt-5/qdesktopservices.html#openUrl its up to your system to what happens then.
