### ISSUE TITLE
All the forge 8 crashing while start

### ISSUE THREAD

**Issue by Dalailamer0684** [MultiMC/Launcher#4715]
### Description of bug

All the forge 8 crashing while start

### Steps to reproduce

Sarting ATF 8 via MMC every time

### Suspected cause

MultiMC version: 0.6.16-develop-3355

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.29.43, 108.138.29.38, 108.138.29.55, 108.138.29.49]

session.minecraft.net resolves to:
    [54.164.34.185, 52.7.153.255, 54.173.66.187]

textures.minecraft.net resolves to:
    [108.138.36.30, 108.138.36.72, 108.138.36.87, 108.138.36.128]

api.mojang.com resolves to:
    [108.138.36.72, 108.138.36.3, 108.138.36.30, 108.138.36.63]

Minecraft folder is:
Z:/MultiMC/instances/All The Forge 8 v0.5/minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.3.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.3.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  Z:/MultiMC/instances/All The Forge 8 v0.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  Z:/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  Z:/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  Z:/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  Z:/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  Z:/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  Z:/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  Z:/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  Z:/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  Z:/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  Z:/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  Z:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  Z:/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  Z:/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  Z:/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  Z:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  Z:/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  Z:/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  Z:/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  Z:/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  Z:/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  Z:/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  Z:/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  Z:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  Z:/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  Z:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  Z:/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  Z:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  Z:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  Z:/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  Z:/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  Z:/MultiMC/libraries/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar
  Z:/MultiMC/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  Z:/MultiMC/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  Z:/MultiMC/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  Z:/MultiMC/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  Z:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  Z:/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  Z:/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  Z:/MultiMC/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar
  Z:/MultiMC/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar
  Z:/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  Z:/MultiMC/libraries/cpw/mods/modlauncher/9.1.3/modlauncher-9.1.3.jar
  Z:/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  Z:/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  Z:/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  Z:/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  Z:/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  Z:/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  Z:/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  Z:/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  Z:/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  Z:/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  Z:/MultiMC/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar
  Z:/MultiMC/libraries/net/minecraftforge/fmlloader/1.18.2-40.1.20/fmlloader-1.18.2-40.1.20.jar
  Z:/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  Z:/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [✔️] [1.18.2] SecurityCraft v1.9.1
  [✔️] alexsmobs-1.18.3
  [✔️] Amplified_Nether_v1.1.1
  [✔️] appliedenergistics2-11.0.0
  [✔️] AutoRegLib-1.7-53
  [✔️] balm-3.0.30
  [✔️] bambooeverything-1.2.7-build.14mc1.18.2
  [✔️] baubles-1.10.0.1-1.18.1
  [✔️] BetterAdvancements-1.18.2-0.2.0.129
  [✔️] BH-Menu-1.18.2-1.3
  [✔️] BiomesOPlenty-1.18.2-16.0.0.109-universal
  [✔️] bwncr-3.12.20
  [✔️] catalogue-1.6.1-1.18.2
  [✔️] cfm-7.0.0-pre29-1.18.2
  [✔️] ChiselsBits-forge-1.18.2-1.2.87-universal
  [✔️] citadel-1.11.3-1.18.2
  [✔️] Clumps-forge-1.18.2-8.0.08
  [✔️] cofh_core-1.18.2-1.6.1.15
  [✔️] comforts-forge-1.18.2-5.0.0.4
  [✔️] configured-1.5.3-1.18.2
  [✔️] connectedglass-1.1.3-mc1.18
  [✔️] Controlling-forge-1.18.2-9.019
  [✔️] cookingforblockheads-forge-1.18.2-12.0.1
  [✔️] CosmeticArmorReworked-1.18.2-v2
  [✔️] create-mc1.18.2_v0.4.1
  [✔️] Decorative Blocks Compat-forge-1.18.2-2.1.0
  [✔️] Decorative Blocks-forge-1.18.2-2.1.0
  [✔️] defaultoptions-forge-1.18.1-14.1.0
  [✔️] DoggyTalents-1.18.2-2.5.0
  [✔️] drippyloadingscreen_forge_1.5.1_MC_1.18-1.18.1
  [✔️] ExtremeReactors2-1.18.2-2.0.42
  [✔️] fancymenu_forge_2.7.1_MC_1.18.2
  [✔️] FarmersDelight-1.18.2-1.1.1
  [✔️] farmingforblockheads-forge-1.18.2-10.0.1
  [✔️] FastLeafDecay-28
  [✔️] flywheel-forge-1.18-0.6.2
  [✔️] functionalstorage-1.18.2-0.0.15
  [✔️] ImmersiveEngineering-1.18.2-8.0.1-147
  [✔️] ironchest-1.18.2-13.1.9
  [✔️] Jade-1.18.2-5.1.0
  [✔️] jei-1.18.2-9.7.0.195
  [✔️] journeymap-1.18.2-5.8.4-forge
  [✔️] JustEnoughAdvancements-1.18.2-3.2.0
  [✔️] konkrete_forge_1.3.3_MC_1.18-1.18.1
  [✔️] lazydfu-1.0-1.18
  [✔️] LibX-1.18.2-3.2.15
  [✔️] Mantle-1.18.2-1.9.20
  [✔️] mcw-bridges-2.0.3-mc1.18.2
  [✔️] mcw-doors-1.0.6-mc1.18.2
  [✔️] mcw-roofs-2.1.2-mc1.18.2
  [✔️] mcw-windows-2.0.3-mc1.18.2
  [✔️] Mekanism-1.18.2-10.2.0.459
  [✔️] MekanismGenerators-1.18.2-10.2.0.459
  [✔️] MekanismTools-1.18.2-10.2.0.459
  [✔️] MmmMmmMmmMmm-1.18-1.5.1
  [✔️] MouseTweaks-forge-mc1.18-2.21
  [✔️] MyServerIsCompatible-1.18-1.0
  [✔️] netherportalfix-forge-1.18-9.0.0
  [✔️] oauth-1.1.13-1.18.2
  [✔️] OldCombatMod_1.18.2
  [✔️] OpenLoader-Forge-1.18.2-12.0.1
  [✔️] Placebo-1.18.2-6.4.0
  [✔️] polymorph-forge-1.18.2-0.44
  [✔️] productivebees-1.18.2-0.9.0.4
  [✔️] Quark-3.2-356
  [✔️] shutupexperimentalsettings-1.0.5
  [✔️] simple-rpc-1.18.2-3.0.1
  [✔️] sophisticatedbackpacks-1.18.2-3.16.4.584
  [✔️] sophisticatedcore-1.18.2-0.1.0.19
  [✔️] TConstruct-1.18.2-3.5.0.17
  [✔️] TerraBlender-forge-1.18.2-1.1.0.99
  [✔️] Terralith_v2.2.1a
  [✔️] thermal_expansion-1.18.2-1.6.0.8
  [✔️] thermal_foundation-1.18.2-1.6.0.20
  [✔️] thermal_innovation-1.18.2-1.6.0.6
  [✔️] titanium-1.18.2-3.5.0-32
  [✔️] ToastControl-1.18.2-6.0.2
  [✔️] TrampleStopper-3.1.0-build.27mc1.18.2
  [✔️] TreeChop-1.18.2-0.15.7
  [✔️] waystones-forge-1.18.2-10.0.0
  [✔️] YungsApi-1.18.2-Forge-2.0.8
  [✔️] YungsBetterDungeons-1.18.2-Forge-2.1.0
  [✔️] YungsBetterMineshafts-1.18.2-Forge-2.1.3
  [✔️] YungsBetterStrongholds-1.18.2-Forge-2.1.1
  [✔️] ZeroCore2-1.18.2-2.1.16

Params:
  --username  --version 1.18.2 --gameDir Z:/MultiMC/instances/All The Forge 8 v0.5/minecraft --assetsDir Z:/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 40.1.20 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 7704

Using onesix launcher.

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:185)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
fix is incoming with https://github.com/MultiMC/Launcher/pull/4714
