### ISSUE TITLE
Looks like CurseForge API in MultiMC is deprecated and unusable

### ISSUE THREAD

**Issue by Beleggrodion** [MultiMC/Launcher#4716]
### Operating System

Windows

### Description of bug

CurseForge API JSON Download looks like not working anymore.  ModID cannot be resolved. The URL's in the Logfile which had download errors say that a migration shoul'd be down. 

Ex. https://cursemeta.dries007.net/431135/3740565.json

> So long and thanks for all the fish.
> Please migrate towards the official API. This service has been deprecated for years.

### Steps to reproduce

I tried to add a new CurseForge Project (Fabric Medival Minecraft) to MultiMC and receive an error that not all ModID's are able to be resolved. First i tried the search directly, but no results and so the error comes when i try to add the ZIP manually. Source: https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric/files/3794469 

In the MultiMC-0.log i see then some messages like:

`   15.321 D Downloading  "https://cursemeta.dries007.net/418881/3706642.json"
   15.321 D Downloading  "https://cursemeta.dries007.net/365273/3769502.json"
   15.321 D Downloading  "https://cursemeta.dries007.net/504899/3789579.json"
   15.321 D Downloading  "https://cursemeta.dries007.net/348521/3782775.json"
   15.321 D Downloading  "https://cursemeta.dries007.net/424480/3683636.json"
   15.321 D Downloading  "https://cursemeta.dries007.net/443476/3717999.json"
   15.567 C Failed  "https://cursemeta.dries007.net/418881/3706642.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
   15.567 D Download failed in previous step: "https://cursemeta.dries007.net/418881/3706642.json"
   15.568 D Downloading  "https://cursemeta.dries007.net/392101/3673233.json"
   15.583 C Failed  "https://cursemeta.dries007.net/365273/3769502.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
   15.584 D Download failed in previous step: "https://cursemeta.dries007.net/365273/3769502.json"
   15.584 D Downloading  "https://cursemeta.dries007.net/596514/3718045.json"
   15.594 C Failed  "https://cursemeta.dries007.net/504899/3789579.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
   15.595 D Download failed in previous step: "https://cursemeta.dries007.net/504899/3789579.json"
   15.595 D Downloading  "https://cursemeta.dries007.net/596516/3782625.json"
   15.604 C Failed  "https://cursemeta.dries007.net/348521/3782775.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
   15.604 D Download failed in previous step: "https://cursemeta.dries007.net/348521/3782775.json"
   15.605 D Downloading  "https://cursemeta.dries007.net/596517/3704691.json"
   15.607 C Failed  "https://cursemeta.dries007.net/443476/3717999.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
   15.607 D Download failed in previous step: "https://cursemeta.dries007.net/443476/3717999.json"
`

And later then some message that the json has invalid values from the downloads.

### Suspected cause

Download an resolve of the json and then download of the files which are needed for the modpack.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> I have searched the issue tracker and did not find an issue describing my bug. 

no you didn't please do

**Comment by Beleggrodion** [comment]
Ok. then the short question as i now searched all closed (sory for the x-report, i only searched the open stuff) at the moment as i read curseforge support is gone and perhaps don't come back into multimc? I only read that you removed a workaround (which was a replacement for not change the complete code) from a request of curseforge, or is planned to implement the new api in the future?

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
