### ISSUE TITLE
CurseForge downloads don't work

### ISSUE THREAD

**Issue by Magnaderra** [MultiMC/Launcher#4717]
### Operating System

Windows

### Description of bug

CurseForge downloads don't work. The list does not appear.

### Steps to reproduce

Go to 

New instance -> CurseForge

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
