### ISSUE TITLE
custom jar not working

### ISSUE THREAD

**Issue by We-arc** [MultiMC/Launcher#4719]
### Operating System

Windows

### Description of bug

i tried to make a lot of instances but  the custom minecraft jar never worked

### Steps to reproduce

1.create instance
2.click replace minecraft.jar
3. try to launch the game

### Suspected cause

i dont know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
