### ISSUE TITLE
custom minecraft.jar not working

### ISSUE THREAD

**Issue by We-arc** [MultiMC/Launcher#4722]
### Operating System

Windows

### Description of bug

when I try to replace the jar of any version it doesnt work

### Steps to reproduce

1.create a instance on any version
2.click edit instance
3.replace the minecraft.jar with any version

### Suspected cause

I think it could be that it's old versions of minecraft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
