### ISSUE TITLE
Modrinth: alpha and beta modpacks aren't downloaded

### ISSUE THREAD

**Issue by Madis0** [MultiMC/Launcher#4724]
### Operating System

Windows

### Description of bug

Trying to download an alpha or beta version of a Modrinth modpack downloads the previous stable version instead.

Edit: an user also claimed this occurs for old stable versions, aka still the latest stable is downloaded.

### Steps to reproduce

1) Get latest MultiMC development version
2) Open the Modrinth modpack browser with New Instance
3) Find a modpack
4) Select an alpha or beta version from that modpack
5) See what gets downloaded

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by peterix** [comment]
Fixed in dev.
