### ISSUE TITLE
CurseForge gone?

### ISSUE THREAD

**Issue by ben5vik** [MultiMC/Launcher#4725]
Hello,
since the last MultiMC develop Update is the option for downloading modpacks from CurseForge gone and I also cant install them via the zip files from CurseForge.
Please add the CurseForge option back to MMC and fix the bug with the zip files
Thanks
Ben

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by ben5vik** [comment]
Okay, thank you for your awnser
