### ISSUE TITLE
Unable to open links directly

### ISSUE THREAD

**Issue by alba4k** [MultiMC/Launcher#4726]
### Description of bug

Since yesterday I am noticing that links no longer appear to open directly (I've had the same issue with the official launcher where links, after a few weeks of use, would just stop opening).

This specific line from the logs is likely relevant, since the same appears using the official launcher
`
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
`

The issue appears on minecraft 1.8.9 (with Java 8, jre8-openjdk , using Forge), while it doesn't in 1.18.2 (java 18, jre-openjd, using Fabric).

I am using an Arch Linux system with i3wm as desktop environnment, the same happens when trying on KDE Plasma.

One of the major things I noticed after switching to MultiMC was indeed that links where working again, but now the same issue appeared there again (I know it is a mostly java-related issue, but it would be nice to know if there was any fix for it)

### Steps to reproduce

Launch the game, enter a single or multiplayer world in 1.8.9, type a link to the chat (e.g. https://www.minecraft.net), try to click on it

Nothing happens

### Suspected cause

Java 8 fails to find a valid browser to open the link (what's weird is that it worked fine until some days ago)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
maybe try a standalone java that doesnt come from your package manager which could be the fault, like https://adoptium.net/ and see if that fixes it? we can't really offer support for game and OS specific issues here, you can try our [MultiMC Discord](https://discord.gg/multimc) or keep replying here but I'll close the issue
