### ISSUE TITLE
MultiMC unable to resolve mod IDs and curseforge packs not showing when adding a new instance

### ISSUE THREAD

**Issue by PerliousFalcon** [MultiMC/Launcher#4727]
### Operating System

Windows

### Description of bug

Mod ID resolves: When I try to add an instance from a downloaded zip file, it gives an error saying some ID resolving tasks failed.

Packs not showing: So this looks like a Curseforge unique problem, as I found the other launchers (FTB, Techinic, etc) to be fine, but for Curseforge, it does not show to packs to browse.

### Steps to reproduce

Mod ID resolving issue:

- Add Instance

- Import from zip (zip being the pack you want to install, Nomifactory dev versions in my case)

- Wait until it gets to Mod ID resolving

- Error saying that some ID resolving tasks failed

Curseforge browsing problem:

- Add instane

- Curseforge tab

- See that the pack space is empty and even searching doesn't change anything. Again other tabs don't have that problem for me.

### Suspected cause

I do not know what's the possible cause here as this didn't happen last time I used MultiMC, which I think it was at least month ago. I had a feeling for the 2nd issue that it might be the firewall, but I think I'm wrong since again, this wasn't a problem last time.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
