### ISSUE TITLE
CurseForge Integration seems broken - Mod pack List is empty & cannot resolve Mod ID's

### ISSUE THREAD

**Issue by jannis3005** [MultiMC/Launcher#4728]
### Operating System

Linux

### Description of bug

If you go to "Add Instance", and then select "CurseForge" no Modpacks show up (can reproduce this on two different Linux PC's):

![image](https://user-images.githubusercontent.com/38779449/170793963-cce2c0e6-2f77-4c64-a48d-5f389784999f.png)

if you download the zip-file and and try to import it, it's stuck for some time like this:
![image](https://user-images.githubusercontent.com/38779449/170794080-37b3f01b-6a03-4d3c-9d7c-4dec7a72103a.png)
And then ends up like this:
![image](https://user-images.githubusercontent.com/38779449/170794122-b81faf9e-e655-4848-92d0-d846332f6a33.png)

Running it from the terminal reveals the following errors:

<summary>Modpack List</summary>
<details>

```
44.404 D Task "NetJob(Flame::Search)" starting for the first time
44.404 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.752 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
44.752 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.753 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.858 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
44.858 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.858 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.964 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
44.964 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
44.964 D Downloading  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
45.070 C Failed  "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"  with reason  201
45.070 D Download failed in previous step: "https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
45.070 C Task "NetJob(Flame::Search)" failed:  "Auftrag 'Flame::Search' scheiterte bei:
https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&index=0&pageSize=25&searchFilter=&sectionId=4471&sort=0"
```

</details>
<summary>Importing a curseforge Zip File</summary>
<details>

```
  407.725 C Failed  "https://cursemeta.dries007.net/531834/3777498.json"  with reason  302
  407.725 D Download failed in previous step: "https://cursemeta.dries007.net/531834/3777498.json"
  407.726 D Downloading  "https://cursemeta.dries007.net/511733/3750118.json"
  407.726 C Failed  "https://cursemeta.dries007.net/245506/3791572.json"  with reason  302
  407.726 D Download failed in previous step: "https://cursemeta.dries007.net/245506/3791572.json"
  407.726 D Downloading  "https://cursemeta.dries007.net/256717/3757581.json"
  407.731 C Failed  "https://cursemeta.dries007.net/411045/3683767.json"  with reason  302
  407.731 D Download failed in previous step: "https://cursemeta.dries007.net/411045/3683767.json"
  407.731 D Downloading  "https://cursemeta.dries007.net/446870/3745833.json"
  407.732 C Failed  "https://cursemeta.dries007.net/393149/3683668.json"  with reason  302
  407.732 D Download failed in previous step: "https://cursemeta.dries007.net/393149/3683668.json"
  407.732 D Downloading  "https://cursemeta.dries007.net/232131/3630249.json"
  407.751 C Failed  "https://cursemeta.dries007.net/326041/3711541.json"  with reason  302
  407.751 D Download failed in previous step: "https://cursemeta.dries007.net/326041/3711541.json"
  407.751 D Downloading  "https://cursemeta.dries007.net/314905/3725556.json"
  407.764 C Failed  "https://cursemeta.dries007.net/256717/3757581.json"  with reason  302
  407.764 D Download failed in previous step: "https://cursemeta.dries007.net/256717/3757581.json"
  407.764 D Downloading  "https://cursemeta.dries007.net/364120/3789547.json"
  407.765 C Failed  "https://cursemeta.dries007.net/511733/3750118.json"  with reason  302
  407.765 D Download failed in previous step: "https://cursemeta.dries007.net/511733/3750118.json"
  407.765 D Downloading  "https://cursemeta.dries007.net/314906/3787348.json"
  407.766 C Failed  "https://cursemeta.dries007.net/357362/3768422.json"  with reason  302
  407.766 D Download failed in previous step: "https://cursemeta.dries007.net/357362/3768422.json"
  407.766 D Downloading  "https://cursemeta.dries007.net/422301/3773881.json"
  407.772 C Failed  "https://cursemeta.dries007.net/446870/3745833.json"  with reason  302
  407.772 D Download failed in previous step: "https://cursemeta.dries007.net/446870/3745833.json"
  407.772 D Downloading  "https://cursemeta.dries007.net/55438/3683524.json"
  407.787 C Failed  "https://cursemeta.dries007.net/314905/3725556.json"  with reason  302
  407.787 D Download failed in previous step: "https://cursemeta.dries007.net/314905/3725556.json"
  407.787 D Downloading  "https://cursemeta.dries007.net/297039/3789750.json"
  407.802 C Failed  "https://cursemeta.dries007.net/314906/3787348.json"  with reason  302
  407.802 D Download failed in previous step: "https://cursemeta.dries007.net/314906/3787348.json"
```

Opeing one of the failing links reveals this:
![image](https://user-images.githubusercontent.com/38779449/170794912-1a351967-a00e-4625-9a17-92d92e5d9be7.png)

</details>

### Steps to reproduce

- open MultiMC
- press add an instance
- select curse forge
- try to add a Modpack, find the list empty
- go to CurseForge Website, download the Modpack zip file
- import into MultiMC
- Mod ID's cannot be resolved

### Suspected cause

(?) A change in API maybe? 302 says temporarily moved and page says Goodbye! on it (for the mod id's)
(?) It says failed with 201 for some of me modpack list requests - which should be an OK but with an empty response - don't know what's expected there, but empty responses don't seem to make any sense when retreiving a list (for the modpack list)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Klikini** [comment]
This is happening to me as well on Windows 10.

**Comment by denzuko** [comment]
Looks like the API deprecated. https://twitter.com/CurseForge/status/1526136350910685184

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by Klikini** [comment]
@phit Forgive me if I missed an external discussion, but closing this seems premature. None of the short-term solutions are suitable permanent workarounds because they depend on other (more privacy-invasive and resource-intensive) software to do all the work.

Additionally, could you please point to the issue that this is a duplicate of so I can follow it for updates? :)

**Comment by phit** [comment]
duplicate of (excluding issues newer than this and i probably missed a few) 
https://github.com/MultiMC/Launcher/issues/4687
https://github.com/MultiMC/Launcher/issues/4689
https://github.com/MultiMC/Launcher/issues/4690
https://github.com/MultiMC/Launcher/issues/4695
https://github.com/MultiMC/Launcher/issues/4697
https://github.com/MultiMC/Launcher/issues/4698
https://github.com/MultiMC/Launcher/issues/4702
https://github.com/MultiMC/Launcher/issues/4705
https://github.com/MultiMC/Launcher/issues/4707
https://github.com/MultiMC/Launcher/issues/4708
https://github.com/MultiMC/Launcher/issues/4709
https://github.com/MultiMC/Launcher/issues/4710
https://github.com/MultiMC/Launcher/issues/4716
https://github.com/MultiMC/Launcher/issues/4717
https://github.com/MultiMC/Launcher/issues/4720
https://github.com/MultiMC/Launcher/issues/4721
https://github.com/MultiMC/Launcher/issues/4725
https://github.com/MultiMC/Launcher/issues/4726
https://github.com/MultiMC/Launcher/issues/4727

there is no viable workaround until Curseforge changes their TOS which we do not control, we just added the ability to import locally installed FTB packs with https://github.com/MultiMC/Launcher/commit/41e5b3b62816bc9662f846f89b23225dfe51ccce other than that there's currently no planned replacement and as such no ticket to follow

**Comment by Klikini** [comment]
Ah, I was looking for an _open_ duplicate. I didn't realize it was now a TOS violation, but regardless, I feel that an issue should be left open as this still needs to be resolved. That may be a workaround (permission from CurseForge?), removing the option from the UI, or something else, but just leaving this as-is will continue to confuse users and result in even more reports of this bug indefinitely.

**Comment by phit** [comment]
the UI was already removed two weeks ago, just hasn't made it into the stable yet https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc

**Comment by JustZacTTv** [comment]
Looks to me like curse just signed there down death warrant

**Comment by GSstarGamer** [comment]
Any fixes yet?
