### ISSUE TITLE
problem with multimc

### ISSUE THREAD

**Issue by hi23392** [MultiMC/Launcher#4731]
### Description of bug

This is the case, I found that the cruseforge becomes blank, and the search is useless, what should I do?

### Steps to reproduce

![螢幕擷取畫面 2022-05-23 180716](https://user-images.githubusercontent.com/87599137/170818046-456b1fec-b411-4d74-889c-c102d661266f.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
>
> For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
>
> FTB App can handle both on all systems:
https://www.feed-the-beast.com/app
>
> In the short term, we'll see if we can automate import of packs downloaded via FTB
>
> Long term, I would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by hi23392** [comment]
thanks
