### ISSUE TITLE
Minecraft  1.15.2 is crashing with forge and forge mods.

### ISSUE THREAD

**Issue by Ad82880** [MultiMC/Launcher#4732]
https://paste.ee/p/UeIgL. I don't know much about coding but my launcher isn't working, I even disabled all the mods and still it isn't working, can somebody please help?

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Ad82880** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

Thxs it got that working.
