### ISSUE TITLE
OptiFine installation appears to not load

### ISSUE THREAD

**Issue by ylluminate** [MultiMC/Launcher#4734]
### Operating System

Windows

### Description of bug

When installing OptiFine download .jar via Version tab for instance configuration "Add to Minecraft.jar" or by adding the same OptiFine .jar Loader mods, neither will show OptiFine as loaded with F3 when game is loaded.

### Steps to reproduce

* Download OptiFine from: https://www.optifine.net/downloads
* Try to load the .jar that's downloaded by either Version or Loader mods tabs of MultiMC for the instance in question (most recent version: 1.18.2).
* Load Minecraft and hit F3 when in a game instance to see if OptiFine is loaded.

Please note, I also tried to load the same version of Forge separately so that I would be sure it is loaded as well to see if it would alter anything and I ended up with a `java.lang.reflect.InvocationTargetException` error, so I suspect that since Forge appears to be included in OptiFine in some fashion that this evokes this error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ThexXTURBOXx** [comment]
https://github.com/MultiMC/Launcher/wiki/MultiMC-and-OptiFine
