### ISSUE TITLE
MultiMC Unable to resolve mod IDS

### ISSUE THREAD

**Issue by Firemonkey2870** [MultiMC/Launcher#4735]
### Operating System

Windows

### Description of bug

Whenever I try to install a Modpack using a Zip File it starts to unpack the modpack but it stops when it gets to the mods and says it can't resolve mod IDS I have used the exact same modpack download with MultiMC and didn't have an issue with installing it

### Steps to reproduce

I have tried installing Skyfactory 3, and Valhelsia: Enhanced Vanilla as well, and neither read the mod IDS. I have checked the modpack Zip files and nothing is wrong with them

### Suspected cause

Unknown

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hakanai** [comment]
Getting the same issue here. I did some quick investigation in the log.

I see these in the log:
```
  189.932 C Failed  "https://cursemeta.dries007.net/244049/2431869.json"  with reason  QNetworkReply::NetworkError(ProtocolInvalidOperationError)
```

Visiting that URL, I see:

> So long and thanks for all the fish.
> Please migrate towards the official API. This service has been deprecated for years.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by NovaLynxie** [comment]
Damn... that explains why this isn't working anymore. Well at least its possible to manually import the mods from other launchers.
