### ISSUE TITLE
i cant launch any modpacks

### ISSUE THREAD

**Issue by firstfractal** [MultiMC/Launcher#4738]
### Description of bug

a newly installed modpack didnt launch and error and stuff https://paste.ee/p/0LnmE is the crash  log

### Steps to reproduce

i dont know

### Suspected cause

i thought it was me using java 17 but i reinstalled java 8 and used curseforges java aswell as multimcs javaw but it didnt work

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
