### ISSUE TITLE
Step 4 doesn't work

### ISSUE THREAD

**Issue by Mremenar** [MultiMC/Launcher#4739]
We have followed the instructions at https://fabricmc.net/wiki/player:tutorials:install_multimc:windows down to step 4, but cannot proceed because the "Mods" button does not appear on our launcher screen (please see attached
![What we saee step 4](https://user-images.githubusercontent.com/48491179/171054095-05fa56bd-3762-44ea-afd0-4275dba73430.png)
)

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Mremenar** [comment]
How is it not your problem when your instructions don’t lead to the results that you assert will be achieved by following your instructions?



“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by phit** [comment]
well first those aren't our instructions, secondly you probably didn't install the mod that is mentioned in step 4 which adds that button in the first place

**Comment by Mremenar** [comment]
Dear Philip T.,
Thank you for the prompt responses.

1) Actually yes, we did install the "Mod Menu" mod, and no, it doesn't work, which is the reason for contacting you.
2) I'm sorry to hear that the instructions at player:tutorials:install_multimc:windows [Fabric Wiki] 


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
player:tutorials:install_multimc:windows [Fabric Wiki]


 |

 |

 |

are not "your" instructions, mea culpa.
3) Fabric/MultiMC still doesn't work us.
M



    On Tuesday, May 31, 2022, 11:52:04 AM PDT, Philip T. ***@***.***> wrote:  
 
 


well first those aren't our instructions, secondly you probably didn't install the mod that is mentioned in step 4 which adds that button in the first place
