### ISSUE TITLE
Issue on dowloading modpacks from Curseforge in launcher and website

### ISSUE THREAD

**Issue by DomMaster1337** [MultiMC/Launcher#4742]
### Operating System

Windows

### Description of bug

Curse launcher in the Launcher dont open and dont load, and also dont load zip files from curse website
![multimc fehler](https://user-images.githubusercontent.com/106687598/171442149-18d3a90f-cdb9-430b-920d-f3937f5c275e.png) curse tab in launcher issue
![fehler multi mc bei zip datei](https://user-images.githubusercontent.com/106687598/171442583-8d7335d5-e1e6-4fed-93de-1c7765c780b8.png) zip file issue
 

### Steps to reproduce

open curse tab on launcher
load zip file from downlaos from website

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
