### ISSUE TITLE
i cant get into my account

### ISSUE THREAD

**Issue by AntiSpacee** [MultiMC/Launcher#4743]
### Description of bug

when I try to log in my account it tells me authentication failed and in any minecraft launcher it works just fine
 i cant to go any other launcher because this launcher is easy to use for me

### Steps to reproduce

i dont know

### Suspected cause

i cant think of one

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AntiSpacee** [comment]
can someone help me with it

**Comment by FirePrincessITA** [comment]
It's probably becuase you need to migrate your account to Microsoft for using the launcher.
