### ISSUE TITLE
Job 'Mod download' failed to process

### ISSUE THREAD

**Issue by Kraugel13** [MultiMC/Launcher#4744]
### Description of bug

When attempting to add new Instance it would
 download halfway then it would say job 'Mod download' failed to process
![kjj](https://user-images.githubusercontent.com/106714932/171526322-a9cfd5e2-2820-4240-a9a6-d78d924c9a47.PNG)

### Steps to reproduce

click add instance, select modpack, press ok, then the message would display and the modpack would not download.

### Suspected cause

[MultiMC-1.log](https://github.com/MultiMC/Launcher/files/8819745/MultiMC-1.log)
not quite sure but this is the log.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by Yoplitein** [comment]
Is FTB not separate from CurseForge? At any rate, it doesn't seem to be an issue of a *missing* API, but one that's behaving unexpectedly. Looking at the [JSON from modpacks.ch](https://api.modpacks.ch/public/modpack/95/2132), some files have a blank URL field which seems to be what's tripping up MultiMC.

**Comment by phit** [comment]
FTB was removed completely in https://github.com/MultiMC/Launcher/commit/0a827ba70e6ef20187f8507a536d54a8441020dc just hasn't made it to stable
