### ISSUE TITLE
Curse forge modpack search issues

### ISSUE THREAD

**Issue by Nekothefemboy0** [MultiMC/Launcher#4746]
### Description of bug

when i go to the modpacks section and go to curse forge no modpacks come up and i cant search or pick a version for them
![image](https://user-images.githubusercontent.com/106837739/171931402-d6f8cb28-b198-4873-af79-b9157ca569c4.png)

### Steps to reproduce

*i click the "Add Instance" button
*i click the "CurseForge" button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
