### ISSUE TITLE
World will not open with datapacks. (Game crash)

### ISSUE THREAD

**Issue by ReubenBL** [MultiMC/Launcher#4748]
### Operating System

macOS

### Description of bug

Whether adding a data pack when creating a world, or placing datapacks in the 'datapack' folder after the world has been created, the game will not generate or open worlds with datapacks within them. This does not happen with the default Minecraft launcher.

I was using two data packs, [Blaze and Caves Advancements Pack](https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-1-12/), and [The Creeper Code](https://www.planetminecraft.com/data-pack/the-creeper-s-code/). I have tried generating a world with both datapacks installed, and with only one of either of the datapacks installed. In either case, the game will not open or generate the world, resulting in a crash.

Log file:
https://paste.ee/p/Qe9Cv

### Steps to reproduce

- Create a new world
- On the new world creation screen, click "Data Packs"
- Click "Open data pack folder"
- Drag desired data packs into the folder
- Go back to Minecraft and add them to your world
- Click on "Create new world"
- The game will get stuck on 0% generation
- After being frozen on this screen for a lengthy amount of, the game will crash.

OR

- Create a new Minecraft world
- Once created and generated, quit the game.
- Go to your worlds in the instance you were playing
- Click on the world you generated and click "Datapacks"
- Drag your datapacks into the folder
- Start your instance again and open the world you just added the datapacks to
- The game will get stuck on 0% generation
- After being frozen on this screen for a lengthy amount of, the game will crash.

### Suspected cause

I initially thought that MultiMC was struggling with the Experimental World Generation feature that some datapacks use - in this case, The Creeper Code. However, I tried generating the world with just Blaze and Caves Advancement Pack, which is a simple advancement data pack that does not affect world generation, and yet the world would still not open / generate.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
assign more memory to the game, multimc does not change anything about it to cause an issue like you described
