### ISSUE TITLE
New CurseForge instance and install modpacks via zip doesn't work!

### ISSUE THREAD

**Issue by Ciclone151** [MultiMC/Launcher#4752]
### Operating System

Windows

### Description of bug

I can't use the new instance option to download modpacks with CurseForge or install modpacks via zip, not even uninstalling and reinstalling multmc works

### Steps to reproduce

When I click on curseforge in the new instance section nothing works nor does anything appear to search is "completely blank"

### Suspected cause

The problem may have started when I changed computers, another suspicion of mine is the 0.6.15 update since in the 0.6.14 update everything was working, but it shouldn't have problems I installed MultiMC following the introduction of github

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by in-memory** [comment]
im relieved im not the only one having this issue. its also affecting my fedora 35 install along with windows. im currently unable to install modpacks via zip or from within the built integration in the launcher itself on both linux and windows

**Comment by mailmindlin** [comment]
I also got this problem when importing a modpack from a zip file. Examining the logs, it looks like CurseForge finally shut down the deprecated API that MultiMC is using.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

**Comment by FusionDragon** [comment]
> Q: Curseforge and FTB search/import/etc. does not work or is missing?
> 
> A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal.
> 
> For now, download the packs using their respective launchers and then import into MultiMC manually: https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
> 
> I recommend to use the FTB App, as it can handle both on all systems: https://www.feed-the-beast.com/app
> 
> In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC
> 
> Long term, we would prefer an arrangement like this: https://curseforge-ideas.overwolf.com/ideas/CF-I-2523

how is a linux user supposed to install curseforge packs?

**Comment by phit** [comment]
use the FTB App

**Comment by FusionDragon** [comment]
> use the FTB App

unrelated, but ads on my pc ;(
thanks though that worked, i didn't realize the ftb app supported curseforge

**Comment by phit** [comment]
use an dns based adblocker, e.g. pihole or nextdns
