### ISSUE TITLE
cant make a new instance that comes from curseforge

### ISSUE THREAD

**Issue by 12lewisFTW** [MultiMC/Launcher#4753]
![Capture](https://user-images.githubusercontent.com/41923809/172058275-6139f237-ab53-4dc3-8455-4e780413c9f3.PNG)

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal. 

For now, download the packs using their respective launchers and then import into MultiMC manually:
https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks

I recommend to use the FTB App, as it can handle both on all systems:
https://www.feed-the-beast.com/app

In the latest development versions of MultiMC there's also a new tab to import locally installed instances from the FTB App into MultiMC

Long term, we would prefer an arrangement like this:
https://curseforge-ideas.overwolf.com/ideas/CF-I-2523
