### ISSUE TITLE
1.18.2 closing on launch

### ISSUE THREAD

**Issue by 1Lightspeed1** [MultiMC/Launcher#4760]
### Description of bug

I tried opening 1.18.2 Fabric  on my MultiMC launcher, but it unexpectedly closed on start up. I have no idea what may have caused it, and I have no hunches as to how it happened.
Here is the log from startup: https://paste.ee/p/vVWEk

### Steps to reproduce

I don't think it's reproducable.

### Suspected cause

At first, I thought it might be because I was using MaLiLib and Litematica (a Fabric schematics mod), but I removed both of those mods from my folder and 1.18.2 still closed.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 1Lightspeed1** [comment]
I forgot to include it in the report, but the OS I'm using is Windows.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by 1Lightspeed1** [comment]
I don't think it's a mod issue, because I modified my mods list and the issue still persists.
