### ISSUE TITLE
Game crashing immediately upon startup

### ISSUE THREAD

**Issue by JNC9473** [MultiMC/Launcher#4763]
### Operating System

macOS

### Description of bug

When trying to start an unmodded, forgeless 1.12.2 instance with Java 8 version 333 on MultiMC version   0.6.16, the game crashes immediately upon the game window forming. This problem persisted even upon downloading another copy of MultiMC (with the same steps.)

### Steps to reproduce

- Possibly only on MacOS?
- Update MultiMC to 0.6.16
- Set Java 8 version used as 333
- Create vanilla 1.12.2 instance
- Try to launch instance online or offline
- See it crash

### Suspected cause

No idea, but here's the log
https://paste.ee/p/ikoqF

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
try an older java 8 version https://github.com/MultiMC/Launcher/wiki/Java-on-macOS

**Comment by JNC9473** [comment]
I cannot fully express my thanks. It seems to work perfectly, and I thank you very much for this.
