### ISSUE TITLE
Pixelmon not work

### ISSUE THREAD

**Issue by TagTTsZ** [MultiMC/Launcher#4766]
### Operating System

Windows

### Description of bug

i can't play the pixelmon i tried everything including try the new version of pixelmon on 1.16 but the modpack doesn't work

### Steps to reproduce

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.156.45, 52.84.156.55, 52.84.156.65, 52.84.156.57]

session.minecraft.net resolves to:
    [52.7.153.255, 54.173.66.187, 54.164.34.185]

textures.minecraft.net resolves to:
    [18.67.0.66, 18.67.0.94, 18.67.0.62, 18.67.0.12]

api.mojang.com resolves to:
    [65.8.214.110, 65.8.214.125, 65.8.214.11, 65.8.214.71]

Minecraft folder is:
C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/instances/The Pixelmon Modpack/minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 18.0.1.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/instances/The Pixelmon Modpack/natives

Libraries:
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2859/forge-1.12.2-14.23.5.2859-universal.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] BetterFps-1.4.8
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] BOP-Patch-1.0
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] fancymenu_1.5.2_MC_1.12-1.12.2
  [✔️] foamfix-0.10.11-1.12.2
  [✔️] Gameshark-1.12.2-6.0.6-universal
  [✔️] jei_1.12.2-4.16.1.301
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] konkrete_1.0.3_MC_1.12-1.12.2
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] OptiFine_1.12.2_HD_U_G5
  [✔️] PixelExtras-1.12.2-2.5.17-universal
  [✔️] Pixelmon-1.12.2-8.4.2-universal

Params:
  --username  --version 1.12.2 --gameDir C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/instances/The Pixelmon Modpack/minecraft --assetsDir C:/Users/NICOLAS/Desktop/atom gipsy/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx8092m, -Duser.language=en]

Minecraft process ID: 17164

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Exiting with -1

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
