### ISSUE TITLE
How run 1.7.10 please

### ISSUE THREAD

**Issue by Francis1131** [MultiMC/Launcher#4768]
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.156.65, 52.84.156.45, 52.84.156.55, 52.84.156.57]

session.minecraft.net resolves to:
    [54.164.34.185, 52.7.153.255, 54.173.66.187]

textures.minecraft.net resolves to:
    [18.67.0.94, 18.67.0.12, 18.67.0.66, 18.67.0.62]

api.mojang.com resolves to:
    [65.8.214.125, 65.8.214.110, 65.8.214.71, 65.8.214.11]

Minecraft folder is:
C:/Users/franc/Documents/MultiMC/instances/1.7.10 Aventura/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_333, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/franc/Documents/MultiMC/instances/1.7.10 Aventura/natives

Libraries:
  C:/Users/franc/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/franc/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/franc/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/franc/Documents/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/franc/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/franc/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/franc/Documents/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/franc/Documents/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/franc/Documents/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/franc/Documents/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/franc/Documents/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/franc/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/franc/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/franc/Documents/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/franc/Documents/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username  --version 1.7.10 --gameDir C:/Users/franc/Documents/MultiMC/instances/1.7.10 Aventura/.minecraft --assetsDir C:/Users/franc/Documents/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 3056

Using onesix launcher.

[19:11:24] [main/INFO]: Setting user: Francis113
[19:11:24] [main/INFO]: (Session ID is token:<TOKEN DE ACESSO>:<ID DO PERFIL>)
[19:11:25] [Client thread/INFO]: LWJGL Version: 2.9.4
[19:11:26] [Client thread/INFO]: Reloading ResourceManager: Default

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

[19:11:27] [Sound Library Loader/INFO]: Sound engine started
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff32d82ee7, pid=3056, tid=0x00000000000027d8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_333-b02) (build 1.8.0_333-b02)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.333-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22ee7]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\franc\Documents\MultiMC\instances\1.7.10 Aventura\.minecraft\hs_err_pid3056.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
O processo foi encerrado com o código 1 (0x1).
Lembre-se de que o código de saída e a descrição são insuficientes para diagnosticar problemas!
Sempre faça o upload completo do log e não só o código de saída.
Clipboard copy at: 11 Jun 2022 19:11:38 -0300

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

**Comment by Francis1131** [comment]
> https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
seriously man, thank you very much
