### ISSUE TITLE
Modrinth Downloader Fails When Downloading A Specific Modpack Due to URL Escaping.

### ISSUE THREAD

**Issue by pyrequest** [MultiMC/Launcher#4769]
### Operating System

Windows

### Description of bug

The MultiMC Modrinth downloader fails when downloading a specific modpack supposedly due to URL escaping.

The Modrinth downloader fails to download a specific modpack 'Infinity Evolved Reloaded' with specific mods which contain spaces and special characters. The issue doesn't seem to be related to the pack but MultiMC itself.

MultiMC Version: 0.6.16

### Steps to reproduce

1. Launch Multimc
2. Right Click > New Instance
3. Select Modrinth and find the pack 'Infinity Evolved Reloaded'
4. Click OK
5. At the end, MultiMC errors out with: Job 'Mod Download' failed to process
![modrinth](https://user-images.githubusercontent.com/66549814/173225265-aeffbdac-3454-4969-8403-7100812ab9ed.PNG)

### Suspected cause

Upon further investigation, I found that the urls in the error message weren't even valid in the first place:
```
curl https://media.forgecdn.net/files/3490/718/Chunk%2BPregenerator-V1.12-2.5.1.jar
```
Responds with the following error message:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>files/3490/718/Chunk+Pregenerator-V1.12-2.5.1.jar</Key>
  <RequestId>...</RequestId>
  <HostId>...</HostId>
</Error>
```
If we unespace `%2B` we get `+`. So putting that instead of the espaced character:
```
curl https://media.forgecdn.net/files/3490/718/Chunk+Pregenerator-V1.12-2.5.1.jar --output TheMod.jar
```
Downloads the mod successfully.

The issue seems to be with the url encoding since these mods with encodable characters in them also happen to be the only ones that error out.

I tried downloading the pack through MultiMC several more times and the result was exactly the same.

Failed mods:
```
https://media.forgecdn.net/files/2652/182/Advanced%2BSolar%2BPanels-4.3.0.jar
https://media.forgecdn.net/files/2700/845/Gravitation%2BSuite-3.1.1.jar
https://media.forgecdn.net/files/2707/353/Toast%2BControl-1.12.2-1.8.1.jar
https://media.forgecdn.net/files/2726/369/Floocraft%2B1.12.2-1.9.6.jar
https://media.forgecdn.net/files/2726/369/Floocraft%2B1.12.2-1.9.6.jar
https://media.forgecdn.net/files/2904/825/Pam%27s%2BHarvestCraft%2B1.12.2zg.jar
https://media.forgecdn.net/files/3330/934/Botania%2Br1.10-364.4.jar
https://media.forgecdn.net/files/3490/718/Chunk%2BPregenerator-V1.12-2.5.1.jar
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
that seems like an issue with the pack rather than MultiMC

**Comment by pyrequest** [comment]
It looks like this pack uses Forge's CDN while [this pack](https://modrinth.com/modpack/innovation-timespace-5) which doesn't fail uses Modrinth's CDN. Seems like downloading packs that use Forge's CDN isn't supported. Closing for now.

**Comment by phit** [comment]
1. there shouldn't even be anything on the Modrinth platform left that uses the Curseforge CDN
2. those URL's are simply wrong in the pack json, so the pack author needs to fix this
![image](https://user-images.githubusercontent.com/2097483/173227765-71289ac8-48be-4076-a22e-fbdd4243b2b7.png)
