### ISSUE TITLE
Archive does not contain a recognized modpack type.

### ISSUE THREAD

**Issue by MrFreakOne** [MultiMC/Launcher#4770]
### Operating System

Windows

### Description of bug

Hello,

Google Translator.

i get this error message no matter which ModPack I try to install. I can't install anything anymore, the ModPacks are all from www.curseforge.com. I haven't started MultiMC for a long time, today when I darted it, it upgraded and then it started, I can't install anything at all. I have uninstalled and reinstalled MultiMC several times. I don't know if this error is only happening to me. I haven't changed anything on my PC, what has changed is the MultiMC upgrades.

![B1](https://user-images.githubusercontent.com/53281959/173230232-be1135f6-5809-40f6-84f5-e008af490db9.jpg)

MultiMC v0.6.16
Windows 10 

See You.

### Steps to reproduce

I don't know what else to write here. I don't know why I can't install any more ModPacks.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Q: Curseforge and FTB search/import/etc. does not work or is missing?

A: Curseforge removed the old API that MultiMC used to search for modpacks and importing zips. A full replacement may take a while to put in place. None of the current options are ideal see https://github.com/MultiMC/Launcher/issues/4762

For now I recommend to use the FTB App, as it can handle both on all systems and MultiMC can import its locally installed instances
https://www.feed-the-beast.com/app
