### ISSUE TITLE
Multi MC cant identify my ownership of Minecraft on my MS account

### ISSUE THREAD

**Issue by Kiyunno** [MultiMC/Launcher#4771]
### Description of bug

When trying to enter any modpack, says that i dont have Minecraft on the account, and asks to start it in demo mode.
![image_2022-06-12_231601002](https://user-images.githubusercontent.com/107378356/173267623-b0961ac0-a172-404e-acba-91534e0fd6ce.png)

But I clearly have mincraft bought in this MS account!

### Steps to reproduce

Welp, I tried login in minecraft official, and it normally functioned.

### Suspected cause

I really cant think of anything bcs yesterday it was working just fine"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kiyunno** [comment]
oh, forgot to mention, I tried log out and re sync the account in multi MC but it still didn't work.

**Comment by Kiyunno** [comment]
Just tried Accessing minecraft.net and it says I don't have permission to access Minecraft.net in this server?

**Comment by SirKino** [comment]
I can confirm I had the same issue, turned off my computer to go to the store, came back to play some more and it now states that I don't own the game. Official launcher functions fine, however utilizing a bunch of different launchers isn't ideal in my mind. Wonder if the ownership issue is related to the bedrock and java edition merge?

**Comment by MacaylaMarvelous81** [comment]
Can reproduce. I think this log entry is relevant:
```
3.390 W AuthRequest::onRequestError: Error 403
3.391 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/entitlements/license?requestId=5e24d904-d06d-49f9-9896-0692473bb63d - server replied: Service Unavailable"
3.391 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
```

**Comment by annachibi2** [comment]
I'm having the same problem and when I log into minecraft.net it says I don't have the game either. Official launcher works fine, like SirKino. Pretty sure this must be on Microsoft's end.

**Comment by beveled-eggs** [comment]
Yeah same issue. Microsoft screwed up the auth service somehow when they merged java and bedrock ownership on pc. They'll probably fix it soon

**Comment by SirKino** [comment]
> 

Now that you mention it, yeah Minecraft.net indicates I don't own anything either. In this instance I suppose the only thing to do is to wait for Microsoft to iron out the kinks on their end. Guess I'll just use the official launcher in the mean time...

**Comment by suzakuwcx** [comment]
Yeah, I also have same issue.But yesterday(06-12) launcher works very well

version:0.6.16-3430 linux64
```
    6.573 D AuthFlow: "正在检查你是否购买了游戏。"    translate: (Check if you own the game)
    6.573 D Getting entitlements...
    6.926 W AuthRequest::onRequestError: Error 403
    6.926 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/entitlements/license?requestId=5786cb6f-ac50-495d-8523-3ebb32c59983 - server replied: Service Unavailable"
    6.926 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
```

**Comment by RodrigoTaipe93** [comment]
Same as everyone :(

**Comment by billbilllbill** [comment]
我也遇到同樣的問題不知道如何解決

**Comment by Kiyunno** [comment]
so I wasn't the only one with the same problem in minecraft net... well all we can do is wait for them to fix this....

i want to play Interactions so bad T----T

**Comment by LoSpol** [comment]
Yeah, just noticed that minecraft.net is broken. Though thing is, you can play on the official launcher.

**Comment by CollinDraws** [comment]
is anyone else having trouble with the Microsoft store and other software

**Comment by the-just-luke** [comment]
Im having the same problem

**Comment by xnite** [comment]
Seems to be related to an auth server bug that Mojang [tweeted about](https://twitter.com/MojangStatus/status/1536181567986475008).

**Comment by BigmanJr123** [comment]
Having same issue here. Worked this morning though. Weird.

**Comment by foreverxml** [comment]
I can also reproduce the bug.
```sh
    2.506 W AuthRequest::onRequestError: Error 403
    2.506 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/entitlements/license?requestId={REDACTED} - server replied: Service Unavailable"
    2.506 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
Unsupported modifier, resource creation failed.
```
Seems Minecraft changed server auth methods.

**Comment by LuckySnipe9** [comment]
I was on like 2 hours ago, why now?

**Comment by foreverxml** [comment]
> I was on like 2 hours ago, why now?

it seems the Minecraft server sysadmins pushed an update with no notification completely breaking MultiMC

**Comment by MaxTheMooshroom** [comment]
> Seems to be related to an xbox live services outage that Mojang [tweeted about](https://twitter.com/MojangStatus/status/1536181567986475008).

Following up on Mojang's status update, [3 xbox live services are down](https://support.xbox.com/en-US/xbox-live-status)
I would expect multimc to start working once "Games & Gaming" is back up.

**Comment by foreverxml** [comment]
hmmm wait their server is down? well that explains it then

this is what happens when DRM sadly

**Comment by jamescubito** [comment]
This is a Microsoft issue. I can only assume this is because of the merging of Java and Bedrock accounts. You can use the official launcher to redirect the .minecraft folder to MultiMC for the meantime.

**Comment by mnfu** [comment]
This isn't MultiMC's fault. Xbox Services are down. (Thanks Mojang for the forced migration to Microsoft accounts)
You can view the status of such here; https://support.xbox.com/en-US/xbox-live-status
Or, you can go to Mojang/Xbox's Twitter pages;
https://twitter.com/MojangStatus/status/1536181567986475008?s=20&t=7T1F_tfcgpP9h1Uj4inPVg
https://twitter.com/XboxSupport/status/1536175265524568064?s=20&t=q0VeMb6Jw61t7aS3XDXpFQ

**Comment by Kiyunno** [comment]
so this concludes this topic, ty everyone for the help in solving the mystery.

**Comment by Kiyunno** [comment]
ok now its the end

**Comment by kaliban71** [comment]
> > 
> 
> Now that you mention it, yeah Minecraft.net indicates I don't own anything either. In this instance I suppose the only thing to do is to wait for Microsoft to iron out the kinks on their end. Guess I'll just use the official launcher in the mean time...

If xbox live is done you will not be able to 

> ### Operating System
> _No response_
> 
> ### Description of bug
> When trying to enter any modpack, says that i dont have Minecraft on the account, and asks to start it in demo mode. ![image_2022-06-12_231601002](https://user-images.githubusercontent.com/107378356/173267623-b0961ac0-a172-404e-acba-91534e0fd6ce.png)
> 
> But I clearly have mincraft bought in this MS account!
> 
> ### Steps to reproduce
> Welp, I tried login in minecraft official, and it normally functioned.
> 
> ### Suspected cause
> I really cant think of anything bcs yesterday it was working just fine"
> 
> ### This issue is unique
> * [x]  I have searched the issue tracker and did not find an issue describing my bug.

You have to use the exact same email that you used to get minecraft before microsoft bought mojang when creating a microsoft acoount,( i had this issuse when migrating my mojang account to a ms acount), also if "xbox live" is down you will not be able to migrate your account, once you do migrate go back to minecraft.net sign-in and the click on the 'get minecraft' button in the top right corner of the page.

**Comment by MacaylaMarvelous81** [comment]
This is not an issue about Mojang -> Microsoft migration

**Comment by kaliban71** [comment]
I had the same issue when xbox live was down and it looks like a account issue where you do not have minecraft, that is why i wrote what i wrote
