### ISSUE TITLE
無法遊玩

### ISSUE THREAD

**Issue by currypudding** [MultiMC/Launcher#4772]
### Description of bug

<img width="959" alt="螢幕擷取畫面 2022-06-13 102522" src="https://user-images.githubusercontent.com/107379150/173269525-5368a1c2-dad7-4659-868e-e118d9db8f69.png">
我有購買Minecraft Launcher可是說我沒購買

### Steps to reproduce

<img width="959" alt="螢幕擷取畫面 2022-06-13 102522" src="https://user-images.githubusercontent.com/107379150/173269677-d1c609b5-cdcb-4f22-8498-6bddf88b44c9.png">

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by bighead945** [comment]
ME TOO !!!!!!!!!!!!!!

**Comment by MacaylaMarvelous81** [comment]
Duplicate of #4771

**Comment by LoSpol** [comment]
Some Xbox services are down. [Check here.](https://support.xbox.com/en-US/xbox-live-status)
