### ISSUE TITLE
Does not recognize Minecraft ownership

### ISSUE THREAD

**Issue by BlackJar72** [MultiMC/Launcher#4774]
### Description of bug

I expect Minecraft to launch so I could play it.

Instead a pop-up appeared saying, "This account does not own Minecraft. You need to purchase the game first to play it."  This is for an account that has had Minecraft since December 2012 and on which I was able to launch and play the game as recently as yesterday -- up until I installed the latest MultiMC update.

### Steps to reproduce

* Be logged in with a valid account which owns a valid Minecraft license.
* Double-click a (previously playable) installation icon
* See the pop-up appear and be forced to "cancel" (or "play demo")

### Suspected cause

Perhaps the latest update isn't detecting or processing account permissions correctly?  (Perhaps because of a bug in the latest MultiMC version, or perhaps because Mojang changed something on their end?)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LuckySnipe9** [comment]
Repeat of bug #4771 "Multi MC cant identify my ownership of Minecraft on my MS account"

**Comment by Zedicia** [comment]
This is happening to me as well

> ### Operating System
> _No response_
> 
> ### Description of bug
> I expect Minecraft to launch so I could play it.
> 
> Instead a pop-up appeared saying, "This account does not own Minecraft. You need to purchase the game first to play it." This is for an account that has had Minecraft since December 2012 and on which I was able to launch and play the game as recently as yesterday -- up until I installed the latest MultiMC update.
> 
> ### Steps to reproduce
> * Be logged in with a valid account which owns a valid Minecraft license.
> * Double-click a (previously playable) installation icon
> * See the pop-up appear and be forced to "cancel" (or "play demo")
> 
> ### Suspected cause
> Perhaps the latest update isn't detecting or processing account permissions correctly? (Perhaps because of a bug in the latest MultiMC version, or perhaps because Mojang changed something on their end?)
> 
> ### This issue is unique
> * [x]  I have searched the issue tracker and did not find an issue describing my bug.

**Comment by datsme** [comment]
Same here happened after the latest dev version update. Also noticed cant set a default account even though it shows connted. Tried disconnecting and reconnecting through the code log in thing and it connects ok but still same issue cant play

**Comment by baeleg** [comment]
Same here.  I didn't even update MultiMC, just tried to log in and play.  Worked fine last night, nothing right now.  I can separately launch Minecraft using the normal launcher.  Just not getting it to recognize in MultiMC.

**Comment by BlackJar72** [comment]
I can't launch older version of Minecraft from the vanilla launcher either -- it crashes.  As a result, I need MultiMC (or some other third-party launcher) to play the game with my mods.

**Comment by foreverxml** [comment]
The log shows an HTTP error 503 meaning it's a Minecraft server-side issue- they probably changed the login method with no notification.

**Comment by P529** [comment]
https://twitter.com/MojangStatus/status/1536181567986475008

**Comment by Spongman** [comment]
why does MultiMC fail when the official launcher works fine? <-- this is the bug.

**Comment by mnfu** [comment]
This isn't MultiMC's fault. Xbox Services are down. (Thanks Mojang for the forced migration to Microsoft accounts)

**Comment by Spongman** [comment]
it kind of is, though. the mojang launcher works just fine. so, whatever MultiMC is doing is _different_ from that...

**Comment by P529** [comment]
> 

The Mojang launcher is indeed not working fine for me. Multiple accounts that I have are not being recognized as an account that has access to Minecraft.

https://imgur.com/a/BVm3bgT

The account has a valid license for minecraft and also owns the name Loaderkitten as you can see in the second image. But its till not allowing me to play the full game, only the demo is available to the account.

**Comment by LoSpol** [comment]
There's currently issues with some Xbox servers. [Check here.](https://support.xbox.com/en-US/xbox-live-status)

**Comment by BlackJar72** [comment]
As this appears to be a problem with Microsoft involving the XBox Network I suppose this isn't really a bug in MultiMC.

I suspect the reason the vanilla launcher sill works for some people is that perhaps it caches permissions in someway? 

That might be a good feature request -- though how plausible it is without control of the Minecraft client I do not know.
