### ISSUE TITLE
Possible Adjustments to MultiMC When Downloading Minecraft Versions

### ISSUE THREAD

**Issue by Aeryn1023** [MultiMC/Launcher#4776]
### Role

Playing Minecraft

### Suggestion

Show an ETA counter or file sizes to give an idea of how long a download will take

### Benefit

I have a very weak internet connection, and often don't let MultiMC download a version because I think it's stuck.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/4329
