### ISSUE TITLE
No pulling Micrososft account

### ISSUE THREAD

**Issue by MRSirBOB** [MultiMC/Launcher#4777]
### Operating System

Windows 10

### Description of bug

I had the issue where MultiMC would not auto-refresh my MS account. Followed a couple fixes online and removed and re-added the account.

Now whjenever I load a world up (Vault hunters mod pack) none of my progress is saved and it seems like I am logging in with a freshj account. It is also not pulling my skin down.

### Steps to reproduce

Log in with MS account

### Suspected cause

Unknown

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
sounds like you were either launching offline before, or are launching offline now

**Comment by MRSirBOB** [comment]
Unfortunately not, I was logged in and Launching as normal then all of a sudden it stopped linking to my MS account

**Comment by TacoGS** [comment]
We may need to see the MultiMC logs or Minecraft logs in order to continue. 

Make sure to remove any private data like names, etc from the file before you do.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, please provide the requested log files.
