### ISSUE TITLE
MultiMC should have handling of game-wide Java edition bans

### ISSUE THREAD

**Issue by TheMCNerd2017** [MultiMC/Launcher#4780]
### Role

Potentially getting a game-wide ban from Minecraft Java

### Suggestion

MultiMC should be able to handle game-wide bans

### Benefit

So that users know if they have a game-wide ban

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Mojang/Microsoft recently added player reporting in a new snapshot, and it can be assumed from this that game-wide bans will eventually be implemented into the Java edition of the game, like it already is on the Bedrock edition. A game-wide ban on Bedrock blocks access to the entire game including singleplayer (only on certain platforms though), so it can be assumed that if Mojang/Microsoft implements game-wide bans on Java edition that it will be exactly like Bedrock, and block access to the entire game.

If Mojang/Microsoft continue onward with their player reporting system and implement game-wide bans, then MultiMC should have the capability of handling game-wide bans.

**Comment by phit** [comment]
lots of ifs in there, if it becomes relevant one can look at this, but probably won't be relevant to the launcher at all
