### ISSUE TITLE
There's a typo in the java wiki

### ISSUE THREAD

**Issue by MustafaKhalaf69** [MultiMC/Launcher#4781]
### Role

Linux java repos

### Suggestion

fix the typo from Unbuntu to Ubuntu

### Benefit

Making the wiki more clear

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

this wiki page https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#linux says 'Unbuntu' instead of 'Ubuntu'

**Comment by phit** [comment]
you can contribute to the wiki here https://github.com/MultiMC/wiki/blob/master/Using-the-right-Java.md

**Comment by phit** [comment]
thanks!
