### ISSUE TITLE
Fabric 1.19 installer doesn't install Intermediary Mappings

### ISSUE THREAD

**Issue by kurisubrooks** [MultiMC/Launcher#4782]
### Operating System

macOS

### Description of bug

Clicking Install Fabric and choosing the latest installs Fabric but doesn't install the intermediary mappings for 1.19
Fabric versions tested 0.14.7, 0.14.8
MultiMC version: v0.6.16-3434 (osx64)

![image](https://user-images.githubusercontent.com/6291467/174255557-f4b963d8-310d-4187-95d5-3966561320c5.png)

### Steps to reproduce

1. Create a new instance for Minecraft 1.19
2. Click Install Fabric and choose latest/recommended (0.14.8)
3. Fabric is installed but Intermediary Mappings are missing

This issue doesn't occur when installing Fabric for 1.18.2

### Suspected cause

Unknown.

Crash log upon launching Minecraft with Fabric without Intermediary Mappings:
https://gist.github.com/kurisubrooks/11a1d4dd6bdb18314291cc20a83f8ef2

Relevant parts from log when trying to launch with Fabric + Fabric API;
```
[15:20:57] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[15:20:57] [main/INFO]: Mappings not present!
... over 100 lines of @Mixin target not found & error loading class ...
... crash ...
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
was caused by the outdated and custom lwjgl version
