### ISSUE TITLE
so great if u'd ad forge 40

### ISSUE THREAD

**Issue by Intergalaxis** [MultiMC/Launcher#4785]
### Role

I compile modpacks

### Suggestion

I want to be able to install forge 40.0 and up

### Benefit

so that over 10 modpacks I have will work

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
![image](https://user-images.githubusercontent.com/2097483/174405345-d593d95b-e114-468f-b575-620708596b03.png)

?
