### ISSUE TITLE
Oopsie! In the Minecraft versions

### ISSUE THREAD

**Issue by Intergalaxis** [MultiMC/Launcher#4786]
### Operating System

Windows

### Description of bug

https://paste.ee/p/FSn8m

### Steps to reproduce

Put together mods shown here
https://drive.google.com/file/d/1ynKGKcMlMInR8W_fT3mosHtd6iXRlRS6/view?usp=sharing

### Suspected cause

Incompatibility within Minecraft versions (most need Forge 40 but are for MC 1.18)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
