### ISSUE TITLE
Log translates some parts for no reason.

### ISSUE THREAD

**Issue by agent-LuluDodo** [MultiMC/Launcher#4787]
### Operating System

Windows

### Description of bug

Some parts in the Log are German:
![Log](https://user-images.githubusercontent.com/98981925/174448223-c9d82574-b150-4843-8277-de9e2c83c0f3.png)
The Launcher and Minecraft are in English.

### Steps to reproduce

I don't know, sadly :(. I noticed the issue today and haven't changed any setting recently.

### Suspected cause

I live in Germany and my system language is German.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
that looks like a message output by the game, so you probably need to tell java your preferred locale

**Comment by agent-LuluDodo** [comment]
Ok. thx
