### ISSUE TITLE
There are about 800k users here. Them applying for keys on a manually processed form is pure insanity.

### ISSUE THREAD

**Issue by foul-fortune-feline** [MultiMC/Launcher#4790]
There are about 800k users here. Them applying for keys on a manually processed form is pure insanity.

_Originally posted by @peterix in https://github.com/MultiMC/Launcher/issues/4762#issuecomment-1152956771_

So they dug their own grave, threw us in, and you're pulling them out of it while leaving us

**Comment by foul-fortune-feline** [comment]
Sorry, didn't just throw us in. *Tried* to throw u in alongside us

**Comment by foul-fortune-feline** [comment]
They held a gun to your head and told you to intentionally faceplant into the asphalt and you complied jollily. Somebody aimed a gun at them and you jumped in the way to take the bullet

**Comment by foul-fortune-feline** [comment]
It's disappointing, more than a little pathetic, and reminds me of fascisticus potentialis

**Comment by Forkk** [comment]
Discussion on the previous issue was locked. It should be pretty obvious that continuing the same discussion in a separate issue to bypass the lock isn't acceptable.
