### ISSUE TITLE
Can't add modpack using Import from zip feature

### ISSUE THREAD

**Issue by NaruTeribery** [MultiMC/Launcher#4791]
Operating System
Windows

Description of bug
I can't seem to import any modpacks via the "Import from zip" feature. Every time I do, I get the error message "Archive does not contain a recognized modpack type". Not sure what is causing it or how to fix, but it's making it pretty much impossible to import a modpack I have been working on into MultiMC.

Steps to reproduce
1. Grab any modpack (I've been grabbing or exporting from Curseforge)
2. Click on "Add Instance" button in MultiMC and select "Import from Zip" and browse to zip file OR Drag modpack zip into MultiMC
3. Hit the OK button and get the error message in question.

This issue is unique
 I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Curseforge support was completely removed https://multimc.org/posts/0-6-16-update.html

**Comment by echoism7** [comment]
api key issues only apply to direct downloading from curseforge.  
Using the zip file is just a matter of parsing the manifest, and downloading each mod.  This can be done manually, without any api key, it's just tedious.  It's not too much to ask for MultiMC to have this convenient feature, unless you're just wanting to discourage people from using Curse mods (which, is also understandable).

**Comment by phit** [comment]
you need the api to get the download url from the file ids in the manifest, the manifest does not contain those, there's ways around this but none really apply to a project of this size if you don't want trouble

**Comment by echoism7** [comment]
Ah, I see PolyMC got in trouble for doing just that.
