### ISSUE TITLE
Error Code -1

### ISSUE THREAD

**Issue by Tjdraco97** [MultiMC/Launcher#4792]
### Operating System

Win 11 x64

### Description of bug

Here is the Log:
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.224.4.58, 13.224.4.54, 13.224.4.35, 13.224.4.53]

session.minecraft.net resolves to:
    [54.164.34.185, 52.7.153.255, 54.173.66.187]

textures.minecraft.net resolves to:
    [13.224.2.100, 13.224.2.89, 13.224.2.51, 13.224.2.19]

api.mojang.com resolves to:
    [65.8.243.62, 65.8.243.6, 65.8.243.44, 65.8.243.26]

Minecraft folder is:
S:/MMC/MultiMC/instances/Tekxit 3.14 Pi (Official)/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.3.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  S:/MMC/MultiMC/instances/Tekxit 3.14 Pi (Official)/natives

Libraries:
  S:/MMC/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  S:/MMC/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  S:/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  S:/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  S:/MMC/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  S:/MMC/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  S:/MMC/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  S:/MMC/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  S:/MMC/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  S:/MMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  S:/MMC/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  S:/MMC/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  S:/MMC/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  S:/MMC/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  S:/MMC/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  S:/MMC/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  S:/MMC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  S:/MMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  S:/MMC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  S:/MMC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  S:/MMC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  S:/MMC/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  S:/MMC/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  S:/MMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  S:/MMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  S:/MMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  S:/MMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  S:/MMC/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  S:/MMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  S:/MMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  S:/MMC/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  S:/MMC/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  S:/MMC/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  S:/MMC/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  S:/MMC/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  S:/MMC/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  S:/MMC/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  S:/MMC/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  S:/MMC/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  S:/MMC/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  S:/MMC/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  S:/MMC/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  S:/MMC/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  S:/MMC/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  S:/MMC/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  S:/MMC/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] 1-12-bspkrscore-universal-7-6-0-1
  [✔️] 1-12-treecapitator-client-1-43-0
  [✔️] aether-1-12-2-v1-5-3-2-custom
  [✔️] aiimprovements-1-12-1-0-0-1b1
  [✔️] animania-1-12-2-base-2-0-3-28
  [✔️] animania-1-12-2-extra-1-0-2-28
  [✔️] animania-1-12-2-farm-1-0-2-28
  [✔️] appleskin-mc1-12-1-0-14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] asgardshieldreloaded-1-12-2-1-0
  [✔️] attributefix-1-12-2-1-0-10
  [✔️] atum-1-12-2-2-0-20
  [✔️] autoreglib-1-3-32
  [✔️] backpack-3-0-2-1-12-2
  [✔️] backtools-1-12-2-7-0-1
  [✔️] battletowers-1-12-2
  [✔️] baubles-1-12-1-5-2
  [✔️] bibliocraft-v2-4-6-mc1-12-2
  [✔️] biggerpacketsplz-since1-8-1-2
  [✔️] bookshelf-1-12-2-2-3-590
  [✔️] botania-r1-10-364-4
  [✔️] buildcraft-all-7-99-24-8
  [✔️] cc-tweaked-1-12-2-1-89-2
  [✔️] chesttransporter-1-12-2-2-8-8
  [✔️] chisel-mc1-12-2-1-0-2-45
  [✔️] chococraft-1-12-2-0-9-9-0
  [✔️] chocolate-quest-repoured-1-12-2-2-6-9b
  [✔️] codechickenlib-1-12-2-3-2-3-358-universal
  [✔️] cofhcore-1-12-2-4-6-6-1-universal
  [✔️] cofhworld-1-12-2-1-4-0-1-universal
  [✔️] controlling-3-0-10
  [✔️] cosmeticarmorreworked-1-12-2-v5a
  [✔️] craftstudioapi-universal-1-0-1-95-mc1-12-alpha
  [✔️] crafttweaker2-1-12-4-1-20-674
  [✔️] crashtomainmenu-client-1-12-2-1-0-0
  [✔️] creativecore-v1-10-70-mc1-12-2
  [✔️] ctm-mc1-12-2-1-0-2-31
  [✔️] customloadingscreen-1-12-2-1-5-6-3141
  [✔️] custommainmenu-mc1-12-2-2-0-9-1-3141
  [✔️] defaultsettings-1-8-x-1-12-x-2-2-4
  [✔️] dimensionaldoors-3-0-9-288
  [✔️] durability-show-1-12-5-0-0
  [✔️] enchantingplus-1-12-2-5-0-179
  [✔️] enchantmentdescriptions-1-12-2-1-1-15
  [✔️] endercore-1-12-2-0-5-76
  [✔️] enderio-1-12-2-5-3-70
  [✔️] enderstorage-1-12-2-2-4-6-137-universal
  [✔️] energyconverters-1-12-2-1-3-7-30
  [✔️] entityculling-1-12-2-5-3-1
  [✔️] extrautils2-1-12-1-9-9
  [✔️] fastfurnace-1-12-2-1-3-1
  [✔️] fastleafdecay-v14
  [✔️] fastworkbench-1-12-2-1-7-3
  [✔️] foamfix-0-10-14-1-12-2
  [✔️] forgelin-1-8-4
  [✔️] forgemultipart-1-12-2-2-6-2-83-universal
  [✔️] furniture-6-3-1-1-12-2
  [✔️] galacticraftcore-1-12-2-4-0-2-280
  [✔️] galacticraft-planets-1-12-2-4-0-2-280
  [✔️] geckolib-forge-1-12-2-3-0-22
  [✔️] gunpowderlib-1-12-2-1-1
  [✔️] hexxit-gear-1-12-2-2-8-0
  [✔️] hwyla-1-8-26-b41-1-12-2
  [✔️] ic2classic-1-12-1-5-5-2-1
  [✔️] ichunutil-1-12-2-7-2-2
  [✔️] industrialforegoing-1-12-2-1-12-13-237
  [✔️] infernalmobs-1-12-2
  [✔️] instantunify-1-12-2-1-1-2
  [✔️] integrationforegoing-1-12-2-1-11
  [✔️] inventorysorter-1-12-2-1-13-4-1
  [✔️] ironchest-1-12-2-7-0-72-847
  [✔️] jei-1-12-2-4-16-1-302
  [✔️] jrftl-1-12-2-1-1
  [✔️] littleframes-v1-0-12-mc1-12-2
  [✔️] littletiles-v1-5-57-mc1-12-2
  [✔️] lootcapacitortooltips-1-3
  [✔️] mantle-1-12-1-3-3-55
  [✔️] mc-locale-fix-1-0
  [✔️] memorytester-0-4-2
  [✔️] micdoodlecore-1-12-2-4-0-2-280
  [✔️] mixincompat-0-8
  [✔️] moreoverlays-1-15-1-mc1-12-2
  [✔️] natura-1-12-2-4-3-2-69
  [✔️] netherending-ores-1-12-2-1-4-2
  [✔️] nomorerecipeconflict-0-13-1-12-2
  [✔️] nvlforcefields-1-12-2-2491-1-0
  [✔️] openblocks-1-12-2-1-8-1
  [✔️] openmodslib-1-12-2-0-12-2
  [✔️] oreberries-1-12-x-0-5-0
  [✔️] pam-s-harvestcraft-1-12-2zg
  [✔️] patchouli-1-0-23-6
  [✔️] phosphor-1-12-2-0-2-6-build50-universal
  [✔️] placebo-1-12-2-1-6-0
  [✔️] quark-r1-6-179
  [✔️] quickhomes-1-2-2
  [✔️] quickteleports-1-12-2-1-1-1
  [✔️] railcraft-12-0-0
  [✔️] randompatches-1-12-2-1-22-1-10
  [✔️] reachfix-1-12-2-1-0-5
  [✔️] redstonearsenal-1-12-2-2-6-6-1-universal
  [✔️] redstoneflux-1-12-2-1-1-1-universal
  [✔️] redwoods-1-12-1-2-3
  [✔️] reforged-0-7-5-1-12
  [✔️] reliquary-1-12-2-1-3-4-796
  [✔️] ruins-1-12-2
  [✔️] simplyjetpacks2-1-12-2-2-2-20-0
  [✔️] smoothfont-mc1-12-2-2-1-2
  [✔️] soulshardsrespawn-1-12-2-1-1-1-13
  [✔️] tconstruct-1-12-2-2-13-0-183
  [✔️] tesla-core-lib-1-12-2-1-0-18
  [✔️] thermaldynamics-1-12-2-2-5-6-1-universal
  [✔️] thermalexpansion-1-12-2-5-5-7-1-universal
  [✔️] thermalfoundation-1-12-2-2-6-7-1-universal
  [✔️] tmel-1-12-2-1-4-0-0
  [✔️] torohealth-1-12-2-11
  [✔️] traverse-1-12-2-1-6-0-69
  [✔️] trumpetskeleton-1-12-1-0-2-1
  [✔️] twilightforest-1-12-2-3-11-1021-universal
  [✔️] unidict-1-12-2-3-0-10
  [✔️] vanillafix-1-0-10-150
  [✔️] wanionlib-1-12-2-2-9
  [✔️] weirdinggadget-1-12-2-2-1-16-universal
  [✔️] worsebarrels-1-3-0
  [✔️] wr-cbe-1-12-2-2-3-2-33-universal
  [✔️] xaeros-minimap-22-6-0-forge-1-12
  [✔️] xaerosworldmap-1-20-6-forge-1-12

Params:
  --username  --version 1.12.2 --gameDir S:/MMC/MultiMC/instances/Tekxit 3.14 Pi (Official)/.minecraft --assetsDir S:/MMC/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx12288m, -Duser.language=en]

Minecraft process ID: 20332

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 24 Jun 2022 19:14:25 -0700
Clipboard copy at: 24 Jun 2022 19:16:26 -0700

### Steps to reproduce

Download Tekxit 3.14 Pi on MultiMC 5 and try to launch the game

### Suspected cause

I am assuming it is a Java issue, but I am unsure as I have the most recent Java (Java 17)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
