### ISSUE TITLE
[Linux] Missing "libqt5xml5" dependency in the installation tutorial.

### ISSUE THREAD

**Issue by Ankeraout** [MultiMC/Launcher#4793]
### Description of bug

The installation page states that for Ubuntu/Debian, MultiMC requires the following packages to be installed:
- libqt5core5a
- libqt5network5
- libqt5gui5

However, MultiMC will also refuse to start if libqt5xml5 is not installed:
```
user@LAPTOP:~/Documents/games/MultiMC$ ./MultiMC
Launcher Dir: /home/user/Documents/games/MultiMC
No missing dependencies found.
/home/user/Documents/games/MultiMC/MultiMC: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory
```

After installing it, MultiMC works.

This dependency should be added to the installation page, in the "Download & Install" category.

### Steps to reproduce

- Go to https://multimc.org/
- Scroll down to "Download & Install"
- Notice that libqt5xml5 is not listed in the Debian/Ubuntu dependencies

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LDuncAndroid** [comment]
Running `dpkg -I` on the `.deb` shows dependencies on `libqt5xml5`. So installing via the `.deb` file should resolve the dependency.

```
$ dpkg -I multimc_1.6-1.deb 
 new Debian package, version 2.0.
 size 7672 bytes: control archive=532 bytes.
     384 bytes,    12 lines      control              
      41 bytes,     3 lines   *  postrm               #!/bin/sh
 Package: multimc
 Version: 1.6-1
 Architecture: all
 Maintainer: Petr Mrázek <peterix@gmail.com>
 Section: games
 Priority: optional
 Installed-Size: 75
 Depends: zenity, desktop-file-utils, libqt5widgets5, libqt5gui5, libqt5network5, libqt5core5a, libqt5xml5, libqt5concurrent5, wget
 Recommends: openjdk-8-jre
 Homepage: http://multimc.org
 Description: A local install wrapper for MultiMC
```

**Comment by Labnann** [comment]
In Fedora 36, I had to install `qt5-qtbase` and `qt5-qtbase-devel` for it to work.

Otherwise I was getting: No such file: `libqt5xml5` and `libQt5Widgets.so.5`
