### ISSUE TITLE
Can't select modrinth modpack version

### ISSUE THREAD

**Issue by andersmmg** [MultiMC/Launcher#4797]
### Operating System

Linux

### Description of bug

Choosing a pack version in the dropdown let's me choose a version, but it doesn't use it.
![image](https://user-images.githubusercontent.com/16022203/175841941-4c6e7b92-4556-4fdd-8a8a-a4b6e4059e0c.png)
![image](https://user-images.githubusercontent.com/16022203/175841978-980c0d5c-c752-43be-b287-4eb73c1da0af.png)
It just uses the latest version no matter what.

### Steps to reproduce

* Press Add Instance
* Select Modrinth
* Select a modpack
* Choose a version in the dropdown
* Click OK
* It downloads the latest anyway

### Suspected cause

It seems like it just ignores the selection, maybe it's just not implemented correctly?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lunnaholy** [comment]
working also on windows version

**Comment by phit** [comment]
what MultiMC version are you on, this should be fixed in the development version via https://github.com/MultiMC/Launcher/commit/0917706b22b21a3074b31c2e8b6a047f9fc560ca

**Comment by andersmmg** [comment]
This was on the latest stable release version. I may just use another fork for now, as it seems to have less bugs

**Comment by phit** [comment]
yeah its not fixed on stable yet, we are currently in the process of reworking the release process to push out stable versions more frequently, for now update to the development version by switching to the development channel in the settings
