### ISSUE TITLE
Failed to start Minecraft Forge 1.8.9

### ISSUE THREAD

**Issue by cubigiabinh** [MultiMC/Launcher#4801]
### Operating System

Windows

### Description of bug

**Minecraft Log:**
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.230.84.54, 54.230.84.35, 54.230.84.43, 54.230.84.64]

session.minecraft.net resolves to:
    [34.202.22.53, 3.216.64.49, 52.204.38.144]

textures.minecraft.net resolves to:
    [108.138.246.85, 108.138.246.63, 108.138.246.57, 108.138.246.90]

api.mojang.com resolves to:
    [13.224.167.60, 13.224.167.80, 13.224.167.52, 13.224.167.75]

Minecraft folder is:
D:/programs/MultiMC/instances/forge/.minecraft

Java path is:
D:/programs/MultiMC/jre1.8.0_51/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_51, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Failed to download the assets index:
Job 'Asset index for forge' failed to process:
https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json

Clipboard copy at: 30 Jun 2022 01:39:09 +0700

**I tried to connect to the server in the browser and it's working fine.**
**I tried with another Minecraft Launcher and it's also working fine.**
**My firewall doesn't block this program at all. I do have NetLimiter but no rules are blocking MultiMC at all.**
**I also tried disabling all the mods but it's still not working**

### Steps to reproduce

1. Create a new instance of Minecraft 1.8.9
2. Installing Forge
3. Try to launch it

### Suspected cause

It might be my wifi being unstable or a MultiMC bug. Or the server just went down

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TacoGS** [comment]
Check to see what Event viewer (eventvwr.exe) says. See if under Windows -> System logs if there are any errors like schannel logged at the time of this happening.

**Comment by cubigiabinh** [comment]
I'm sorry for being inactive for the past 10 days since I opened this issue but I know how to fix this. I copy the link to browser and copy it to IDM (internet download manager), it will download the .json file. Then you search the file bcuz It was working fine right? so there must be a old file that hasn't be deleted. so I use everything tool to search the exact name file bcuz it's just download the file right? so after I search for the file, I copy the file I just downloaded then replace the file in the folder that has the old file .json. then after you replaced you can just start Minecraft normally. I think there is a problem with MultiMC downloader.
