### ISSUE TITLE
Minecraft 1.17 to 1.19 visual glitches

### ISSUE THREAD

**Issue by ChevalierTeutonique** [MultiMC/Launcher#4802]
### Operating System

Windows

### Description of bug

Wrong loading of textures, example uncludes menus buttuns being too short, the main screen of the game has writing policy way too big (over a quarter of screen size) graphics freaking out. Only visual, the rest seems to work just fine, i can create a world and access options. Everything works perferctly fine for all previous version. Images of the glitch :
![Presqbug](https://user-images.githubusercontent.com/108553635/176969277-f313883b-2837-43c6-bae6-0e384490ebbd.PNG)
![bug2](https://user-images.githubusercontent.com/108553635/176969764-d5a6cc47-c653-4c00-85ec-38ba835f0c49.PNG)
![bug3](https://user-images.githubusercontent.com/108553635/176969771-9b8ca307-03b2-446e-b94b-6a3a49efea6e.PNG)
![2022-07-01_23 28 13](https://user-images.githubusercontent.com/108553635/176970098-322b1711-37bb-4ee5-9404-6b06bd6f58fe.png)

May not be observable, but the the textures sometimes flash a lot.

### Steps to reproduce

Just launch the game, Windows 7, above version 1.16.5 and the glitch appears. I also have the correct version for java (17).

### Suspected cause

There is a change in java between 1.16.5 and 1.17 which might be the issue, however it could be anyhting, maybe my computer isn't really compatible or something. No other clue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what graphics card do you have, and can you post your full log

**Comment by ChevalierTeutonique** [comment]
My graphic card is a NVIDIA GeForce GTX 765M as for the full chat lig, here it is (From launch to opening a world) :

**Comment by phit** [comment]
no idea, probably worth trying updating/reinstalling your gpu drivers and trying different java vendors, not sure if anything still officially supports windows 7

either way, its a game issue out of our control
