### ISSUE TITLE
blank screen MultiMC

### ISSUE THREAD

**Issue by MittensMcMuffin** [MultiMC/Launcher#4803]
### Operating System

Windows

### Description of bug

When i select a building block the entire screen turns blank in one plain color (blue when i look at the sky, green when i turn the camera to the grass, brown when i look at trees etc.) and when i switch to empty hands, it instantly turns back to normal, but has to load all the chunks again. The game works fine with the official Minecraft launcher, so i can't imagine the drivers are the issue. My display adapter says Intel(R) UHD graphics 630. I already tried using an older version of Java, reinstalling the game, and playing with the vanilla version, but the problem persists.
![1](https://user-images.githubusercontent.com/108554437/176975238-c4dab281-1a5f-4ce5-9d47-a6f799cb19aa.png)
![2](https://user-images.githubusercontent.com/108554437/176975239-00e2b316-e3c8-457b-a96e-35420b438c1b.png)
![3](https://user-images.githubusercontent.com/108554437/176975240-ca47797f-ca41-4096-ad67-ff880258e10d.png)
![4](https://user-images.githubusercontent.com/108554437/176975241-07feac9d-b1d0-4915-b2b3-d2a4b11c9763.png)

### Steps to reproduce

[1.7.10.zip](https://github.com/MultiMC/Launcher/files/9031955/1.7.10.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what Java version are you using? have you tried [this version](https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs)? and please post your full log

**Comment by MittensMcMuffin** [comment]
Yes, that's the version i'm currently using.
https://paste.ee/p/qYQ4G
![5](https://user-images.githubusercontent.com/108554437/177003938-006cfdd2-c467-47f4-ad97-79c5a794e1f3.png)

**Comment by phit** [comment]
welp no idea then, you can maybe try renaming the MultiMC.exe to Minecraft.exe maybe it will trick your drivers into behaving differently

a quick search also found someone else having the same issue with the same gpu, so it's probably just broken drivers https://www.minecraftforum.net/forums/support/java-edition-support/3135913-1-7-10-modded-is-having-a-unplayable-visual-glitch
