### ISSUE TITLE
"Minecraft 1.18 Pre Release 2 and above require the use of Java 17" Message, with the correct directory chosen at settings

### ISSUE THREAD

**Issue by IDKimBoredCL** [MultiMC/Launcher#4807]
### Description of bug

Minecraft 1.18.2 w/Essential Mod doesn't launch, and the "Minecraft 1.18 Pre Release 2 and above require the use of Java 17" message appears. I downloaded Java 17, following the [https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java](url) page to resolve my problem. I chose the right directory at Java Settings, but it has no effect on the game
![2022-07-02_10-13_1](https://user-images.githubusercontent.com/107329129/177021802-9a74d272-f786-4514-8d0c-e6be2f8674d1.png)
![2022-07-02_10-13](https://user-images.githubusercontent.com/107329129/177021804-97a0a283-6284-49be-ba1f-d84419b7ab6e.png)
![2022-07-02_10-12_1](https://user-images.githubusercontent.com/107329129/177021805-bf4accbb-d42b-4f7a-b7eb-e453ce99d9de.png)
![2022-07-02_10-12](https://user-images.githubusercontent.com/107329129/177021806-76ebb584-863f-4f0a-b01f-6a728a88a2f1.png)
!

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.156.45, 52.84.156.55, 52.84.156.65, 52.84.156.57]

session.minecraft.net resolves to:
    [52.45.69.223, 3.229.83.86, 52.7.214.17]

textures.minecraft.net resolves to:
    [65.8.248.75, 65.8.248.105, 65.8.248.18, 65.8.248.86]

api.mojang.com resolves to:
    [52.85.213.57, 52.85.213.14, 52.85.213.79, 52.85.213.97]

Minecraft folder is:
C:/Users/yxlfr/Downloads/MultiMC/instances/1.18.2/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_333/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_333, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/yxlfr/Downloads/MultiMC/instances/1.18.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/datafixerupper/4.1.27/datafixerupper-4.1.27.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/authlib/3.3.39/authlib-3.3.39.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/minecraft/1.18.2/minecraft-1.18.2-client.jar

Native libraries:
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/yxlfr/Downloads/MultiMC/libraries/com/mojang/text2speech/1.12.4/text2speech-1.12.4-natives-windows.jar

Mods:
  [✔️] Essential

Params:
  --username  --version 1.18.2 --gameDir C:/Users/yxlfr/Downloads/MultiMC/instances/1.18.2/.minecraft --assetsDir C:/Users/yxlfr/Downloads/MultiMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Minecraft 1.18 Pre Release 2 and above require the use of Java 17
Clipboard copy at: 02 Jul 2022 22:19:01 -0400

### Steps to reproduce

- User: I'm the only one experiencing this bug
- Environment: My PC, C: drive at download carpet
- Page: MultiMC 1.18.2 instance
- Medium: Personal Computer, GTX and I3
- Action: I was trying to launch 1.18.2 with the Essential Mod when the message appeared. I installed Java 17 but it had no effect.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by arthomnix** [comment]
1.8.0 is actually java 8
