### ISSUE TITLE
Technoblade memorial

### ISSUE THREAD

**Issue by AndusDEV** [MultiMC/Launcher#4809]
### Role

Just a small addon for the memory of technoblade

### Suggestion

You could add a pig icon with the crown on it (I mean the instance icon)

### Benefit

There's no need to do this. But I think a technoblade remembrance for what he did for the entire Minecraft community would be a good thing. But that's just my proposition.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by mk-pmb** [comment]
I know it's a popular leisure to mention him all over the web: Is it just that, or is he actually relevant to this project?

**Comment by Primitive-Human** [comment]
> for what he did for the entire Minecraft community
Mostly being a pvp youtuber that caters to the younger audience, which doesn't entitle him to receiving an icon on MultiMC. You're free to add your own icons through the "Add Icon" button.
