### ISSUE TITLE
1.8.9 legacy fabric not working

### ISSUE THREAD

**Issue by 1Lightspeed1** [MultiMC/Launcher#4817]
### Description of bug

I installed legacy fabric by dragging it to my launcher, but for some reason, it is not working. I checked to make sure if there were any mods that were incompatible (didn't work), ran it on the right Java version (didn't work). I am confused and unsure as to why it hasn't worked, and I need help.
Log: [https://paste.ee/p/gWJvP](url)
Mods: 
![image](https://user-images.githubusercontent.com/102192779/177597621-9418575f-14de-44c0-a1ad-3eea2b549acf.png)

### Steps to reproduce

Install legacy fabric onto your launcher
Run it once
Install the mods shown
Run the legacy fabric instance again

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 1Lightspeed1** [comment]
OS: Windows 11

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
