### ISSUE TITLE
Failed to start any minecraft versions pre-1.13

### ISSUE THREAD

**Issue by elisionking125** [MultiMC/Launcher#4820]
MultiMC version: 0.6.16-3434

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.224.4.58, 13.224.4.53, 13.224.4.35, 13.224.4.54]

session.minecraft.net resolves to:
    [3.229.83.86, 52.7.214.17, 52.45.69.223]

textures.minecraft.net resolves to:
    [13.224.2.100, 13.224.2.19, 13.224.2.89, 13.224.2.51]

api.mojang.com resolves to:
    [99.86.38.45, 99.86.38.43, 99.86.38.128, 99.86.38.109]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.8.9/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 17.0.1, using 32-bit architecture, from Azul Systems, Inc..

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Applications/MultiMC.app/Data/instances/1.8.9/natives

Libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /Applications/MultiMC.app/Data/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /Applications/MultiMC.app/Data/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Applications/MultiMC.app/Data/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Applications/MultiMC.app/Data/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /Applications/MultiMC.app/Data/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Applications/MultiMC.app/Data/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Applications/MultiMC.app/Data/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Applications/MultiMC.app/Data/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Applications/MultiMC.app/Data/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Applications/MultiMC.app/Data/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /Applications/MultiMC.app/Data/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /Applications/MultiMC.app/Data/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Applications/MultiMC.app/Data/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /Applications/MultiMC.app/Data/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Applications/MultiMC.app/Data/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /Applications/MultiMC.app/Data/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /Applications/MultiMC.app/Data/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /Applications/MultiMC.app/Data/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar
  /Applications/MultiMC.app/Data/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar

Params:
  --username  --version 1.8.9 --gameDir /Applications/MultiMC.app/Data/instances/1.8.9/.minecraft --assetsDir /Applications/MultiMC.app/Data/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.8.9", -Xms2048m, -Xmx2048m, -Duser.language=en]

Wrapper command is:
/Users/adamwenzel/Minecraft/m1-multimc-hack/mcwrap.py

Minecraft process ID: 32043

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
Exiting with -1
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at net.minecraft.client.main.Main.main(SourceFile:41)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 9 more
Process exited with code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 08 Jul 2022 08:52:39 -0600

I've seen another person with the same issue but the possible solution given was only applicable on a windows computer, and I'm on macOS.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
