### ISSUE TITLE
 Minecraft backup level dat being used

### ISSUE THREAD

**Issue by Triliton** [MultiMC/Launcher#4823]
### Operating System

Windows

### Description of bug

Hi,

I havent runned Multimc since the last update. so i havent touched my save since over 1 month almost.

When i start my game it says Minecraft backup level dat being used, and that im adviced to create a backup save.
So i do. When entering my world, everything is corrupt.

Im at 1.12.2 Forge 14.23.4.2705 i have mods installed, and everything worked fine for a year now.

I have no error messages, since ive closed the console window before the level dat message appeared.

I have tried creating a new world, same instance, and copied the new level.dat file over the old.
This had no effect. I also have a backup of my world, and when i try it, i get the same message about level dat being used.

Im guessing this is a no fix issue and my 1 year of work is down the drain...

### Steps to reproduce

?

### Suspected cause

Forge modloader

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Triliton** [comment]
I just tried creating a new instance, excactly the same, it loaded up fine. Then i got a 4 months old backup world started, and i get the same error message with the level.dat file being used.

**Comment by Triliton** [comment]
I managed to resolve it.

**Comment by commandhat** [comment]
> I managed to resolve it.

Please read https://xkcd.com/979/ .
