### ISSUE TITLE
I can't open minecraft with forge

### ISSUE THREAD

**Issue by proooo10** [MultiMC/Launcher#4824]
### Description of bug

I've just installed forge and it gives me this error:

Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Install MultiMc
Install java jdk 18
Create an instance
Install forge
Open the instance

### Suspected cause

Maybe a problem with the launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by proooo10** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

@phit thanks bro but i've just installed java 17 and i can perfectly fabric instances but forge has the same error.
