### ISSUE TITLE
SkyFactory 4 | Failed to Process

### ISSUE THREAD

**Issue by ckalugyer** [MultiMC/Launcher#4827]
### Description of bug

The following error is shown when attempting to install SkyFactory 4 instance:
"Job 'Modpack download' failed to process: https://www.dropbox.com/s/dl/0gm1bd71p02dgrp/Skyfactory 4 Curseforge.zip?dl=1"
![sf4](https://user-images.githubusercontent.com/44153243/178178373-4d720e4b-774a-477f-92ae-524a69249ace.png)

### Steps to reproduce

- Click on add instance
- Click on Technic
- Click on Skyfactory 4 Curseforge
- Click OK

### Suspected cause

Dropbox link is no longer viable or has been updated/locked.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
packs on Technic are the responsibility of the uploader
