### ISSUE TITLE
Minecraft 1.18 Pre Release 2 and above require the use of Java 17

### ISSUE THREAD

**Issue by AyoTedd** [MultiMC/Launcher#4829]
I kept trying to install Fabric and Forge for 1.19, but it kept giving this error. Am I doing something wrong?
[New Paste 1.txt](https://github.com/MultiMC/Launcher/files/9090873/New.Paste.1.txt)
![image](https://user-images.githubusercontent.com/109137390/178441021-1253082b-1b3b-446f-b757-546fa68b83c7.png)

**Comment by phit** [comment]
get java 17

**Comment by AyoTedd** [comment]
> 

I did get Java 17, but it still gave me that error
