### ISSUE TITLE
[Suggestion] Discord's "Currently playing..." integration.

### ISSUE THREAD

**Issue by Blayung** [MultiMC/Launcher#4831]
### Role

I play minecraft.

### Suggestion

Integrate MultiMC with discord, to make it display "Currently playing MultiMC" or something similar, like with crystal launcher for example.

### Benefit

My friends can see that I'm playing minecraft using MultiMC launcher.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There are instructions:
https://discord.com/developers/docs/game-and-server-management/how-to-get-your-game-on-discord

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/3070

**Comment by Eterxnerl** [comment]
if there was a extra kinda plugin or a .dll file for discord rpc it would be awesome

**Comment by Blayung** [comment]
@Primitive-Human 

I made this a long time ago, definetely wouldn't advocate for this now :O
