### ISSUE TITLE
add curseforge and FTB again like ATLauncher or PolyMC

### ISSUE THREAD

**Issue by son123cats** [MultiMC/Launcher#4832]
### Role

play modded minecraft.

### Suggestion

Add again like 2 launcher, when we install a curseforge modpack, we just need to download some mod on the link launcher suggest

### Benefit

me and other can play more modpack

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

sorry about my english, because i'm Vietnamese
![Capture](https://user-images.githubusercontent.com/82934378/179191733-4f6228bd-a8f1-4f5f-a183-d6e8b09165c2.PNG)
![Capture1](https://user-images.githubusercontent.com/82934378/179191742-44233ede-d09d-41bd-be82-18788f372ace.PNG)
![Capture2](https://user-images.githubusercontent.com/82934378/179191743-413c4741-e2e9-4c38-a189-0494e65a7b38.PNG)
![Capture4](https://user-images.githubusercontent.com/82934378/179191745-0d80f01b-d9eb-4d9d-aca5-31646925de13.PNG)

**Comment by phit** [comment]
not until they fix their ToS
