### ISSUE TITLE
not rememebering groups

### ISSUE THREAD

**Issue by wackoamd1** [MultiMC/Launcher#4833]
### Operating System

Windows

### Description of bug

i used to have my instances in groups
now everytime i launch multimc all my groups are gone. not only like the instances are out of groups ( which ofc they are ) but all my groups are just gone they dont exist ,
i just have to remake the groups because they are not in the drop down list . 

multimc 0.4.16-3431

### Steps to reproduce

launch multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
groups are saved in each individual instance, the dropdown will only show groups that currently exist, are you saying all your instances are losing their current group on restart?
please reproduce the issue and add your MultiMC log file, you can find that in the main folder `MultiMC-0.log`

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to reply to this issue with the requested information.
