### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by xTektonic** [MultiMC/Launcher#4838]
### Description of bug

My game crashes on launch

### Steps to reproduce

1. Select that specific installation (1.19 with the latest Fabric)
2. Launch game

### Suspected cause

The cause is the mod "Origins"; the game runs fine if I disable it. ( In that specific crash report I had the wrong version of Origins, but that version was still compatible with 1.19, and the newer version wouldn't launch either)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by xTektonic** [comment]
I'm using the latest MacOS with a brand new MacBook Pro

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
