### ISSUE TITLE
MultiMC crashes after opening a world

### ISSUE THREAD

**Issue by alysa-mad** [MultiMC/Launcher#4846]
### Operating System

Windows

### Description of bug

https://controlc.com/d32da9f2

After I updated to Win 11, MultiMC started crashing after try to open worlds
With Forge or not, crashes everytime
Tried multiple versions of java too, and og launcher works fine

### Steps to reproduce

Install Windows 11
Open Instance
Try to open world or server
Crashes

### Suspected cause

Maybe some change on Windows 11

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
