### ISSUE TITLE
Instance parenting

### ISSUE THREAD

**Issue by HidingInEmptySpace** [MultiMC/Launcher#4848]
### Role

I create a lot of instances with partially the same config. Such as the same serverlist on all instances.

### Suggestion

I'd like some sort of parenting, so that you can change configurations on one instance and apply it on several automaticly.

### Benefit

Instead of changing the serverlist on every instance manually, i would like one parent instance to be applied to all other children of it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
closing as we have plenty of tickets for a similar kind of thing, some examples there's probably more

https://github.com/MultiMC/Launcher/issues/3795
https://github.com/MultiMC/Launcher/issues/3918
https://github.com/MultiMC/Launcher/issues/4403
