### ISSUE TITLE
MultiMC doesn't autodetect OpenJDK installation

### ISSUE THREAD

**Issue by Spongman** [MultiMC/Launcher#4852]
### Description of bug

I have OpenJDK in:
```
C:\Program Files\OpenJDK>where /r . javaw.exe
C:\Program Files\OpenJDK\jdk-18.0.1.1\bin\javaw.exe
C:\Program Files\OpenJDK\openjdk-11.0.12_7\bin\javaw.exe
C:\Program Files\OpenJDK\openjdk-11.0.13_8\bin\javaw.exe
C:\Program Files\OpenJDK\openjdk-11.0.14.1_1\bin\javaw.exe
C:\Program Files\OpenJDK\openjdk-11.0.15_10\bin\javaw.exe
```

but MultiMC fails to find them:

![image](https://user-images.githubusercontent.com/1088194/180699544-fc2176e4-04b7-4309-b98f-3e7a55b99e20.png)

and there's no way to add them manually

I have to manually search for them EVERY TIME.

### Steps to reproduce

* press the cat button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you get that OpenJDK from?

**Comment by CryoRenegade** [comment]
Did you add that to the PATH? Thats how MultiMC finds its java installs.

**Comment by phit** [comment]
> Did you add that to the PATH? Thats how MultiMC finds its java installs.

that is one way, but there can only be one active Java in the path, there's a couple hardcoded paths but the majority of detection on Windows happens via the registry, hence why I need to know their java vendor

**Comment by CmmmmmmLau** [comment]
> where did you get that OpenJDK from?

I had a similar problem, I installed many different versions of java via Scoop. However the auto detect only can find one version of Java that is added to the path.
![20220801225938](https://user-images.githubusercontent.com/42691172/182253304-ba58c22e-b80f-40f6-978b-82d8abfe5322.png)
![20220801230012](https://user-images.githubusercontent.com/42691172/182253316-9b3b631d-7bbb-460f-93ea-a9255e6d595f.png)

**Comment by CryoRenegade** [comment]
> > where did you get that OpenJDK from?
> 
> I had a similar problem, I installed many different versions of java via Scoop. However the auto detect only can find one version of Java that is added to the path.
> ![20220801225938](https://user-images.githubusercontent.com/42691172/182253304-ba58c22e-b80f-40f6-978b-82d8abfe5322.png)
> ![20220801230012](https://user-images.githubusercontent.com/42691172/182253316-9b3b631d-7bbb-460f-93ea-a9255e6d595f.png)
> 

Yeah i do this as well, scoop gives javaw to the latest installed java. But if you are using scoop, you can find your desired javaw relatively easily (C:/Users/_Username_/scoop) and point it manually.

**Comment by phit** [comment]
that's working as intended, if scoop doesn't set the registry keys the installers do there's no way for MultiMC to detect its Java versions
