### ISSUE TITLE
Close for multiple different strings

### ISSUE THREAD

**Issue by zwJimRaynor** [MultiMC/Launcher#4853]
### Operating System

Windows

### Description of bug

Check that there are multiple strings with the text Close and only some of them can be translated

### Steps to reproduce

close button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
What are you exactly asking for? I assume you mean https://github.com/MultiMC/Launcher/issues/1834 ?
