### ISSUE TITLE
希望可以添加一些便于中国玩家使用的功能

### ISSUE THREAD

**Issue by tgfydzs** [MultiMC/Launcher#4854]
### Role

一个普通的MC玩家

### Suggestion

下载源自定义更改

### Benefit

可以再国内获得更多的用户量

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

在中国大陆地区，由于有GFW的存在，导致我们无法便捷的访问国外的网站，进而导致我们在下载游戏版本时，时常会出现无法启动游戏的情况出现。
所以可以添加自定义的镜像源，可以参考hmcl，的相关设置，我认为一般情况下，国内用的最多的是mcbbs镜像源

**Comment by tgfydzs** [comment]
在国内会因为种种原因，导致我们访问同一个网站的速度不一样，例如：ISP，地理位置，使用时段等等问题。
而我非常喜欢这款启动器，他不像HMCL那样，没有门槛（不论是否拥有正版都可以使用），并不合理的整合包管理页面以及文件生成方式。
当然如果因为某些问题，目前无法满足我的愿望，或者之后也无法满足，请务必告诉我，我想知道为何

**Comment by Eawei** [comment]
maybe you should use English, and actually, mcbbs has a bad reputation outside.

**Comment by tgfydzs** [comment]
Yes, mcbbs has a bad reputation, but it can provide convenience to mainland China. mcbbs is one of the few. Of course, if there are other mirror sources, it is a better choice.

**Comment by tgfydzs** [comment]
Because the English level is not high (students), so there is something incomprehensible, you can bring it up, I will try my best to restore my meaning

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/2246

**Comment by tgfydzs** [comment]
thanks
