### ISSUE TITLE
I can't log in my account with MultiMC

### ISSUE THREAD

**Issue by JihwanPark11** [MultiMC/Launcher#4855]
### Operating System

macOS

### Description of bug

When I want to play some game, sometimes I can't open the game. Therefore, I erased the game and tried to download it again. I success in downloading but I can't log into my Microsoft account. 

### Steps to reproduce

<img width="987" alt="bug" src="https://user-images.githubusercontent.com/108569250/181035097-acd14d50-5b26-4561-9a4e-4400b1103435.png">

### Suspected cause

I'm not sure but I think it would be a system problem. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JihwanPark11** [comment]
ps. my Minecraft version is 12.5

**Comment by CryoRenegade** [comment]
What version of MacOS?

**Comment by JihwanPark11** [comment]
the newest version. after one night, Multimc shows I need to update and it worked after I update. You don't need to answer the question now :)
