### ISSUE TITLE
fabric loader but only 16 chunk

### ISSUE THREAD

**Issue by JihwanPark11** [MultiMC/Launcher#4857]
### Description of bug

this time, my maximum chunk is only 16 chunks. the fabric loader is usually 32 chunks but it only has 16 chunks

### Steps to reproduce

![Uploading 스크린샷 2022-07-27 14.30.12.png…]()

### Suspected cause

I think there's problem in multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
