### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by we2rxf2fwfxwdwwdxwdwdx** [MultiMC/Launcher#4862]
### Operating System

Windows

### Description of bug

Process exited with code -1. Im on 1.12.2 modded with mods, on the right java (java 8)
and everytime i try to load my world it crashes with code -1

### Steps to reproduce

I dont know

### Suspected cause

My hard drive or java version, but i dont know

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by we2rxf2fwfxwdwwdxwdwdx** [comment]
> 

You were right, it turns out my world was just corrupted lol,
