### ISSUE TITLE
Any Prelaunch command fails with code 0

### ISSUE THREAD

**Issue by DesirouseIce** [MultiMC/Launcher#4863]
### Operating System

Windows

### Description of bug

any prelaunch command fails to launch game and crashes with code 0.

[Log](https://paste.ee/p/XmZ2Ql)

### Steps to reproduce

use any relaunch command.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
your log doesn't work, and theres thousands of people using them, so please provide a concrete example

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, you can reply to this issue with the requested information.
