### ISSUE TITLE
Allow creating an instance of the latest version

### ISSUE THREAD

**Issue by xeruf** [MultiMC/Launcher#4865]
### Role

Vanilla on a server

### Suggestion

Allow adding an instance that always runs the latest minecraft version

### Benefit

So I don't need to recreate/reconfigure my instance on an update

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
please do use the search as the template suggests https://github.com/MultiMC/Launcher/issues?q=is%3Aissue+latest+label%3Asuggestion+

**Comment by xeruf** [comment]
sorry, apparently I used the wrong terms
