### ISSUE TITLE
Javas not working

### ISSUE THREAD

**Issue by AndrewDaGamer** [MultiMC/Launcher#4866]
### Description of bug

I have 4 mods installed on MultiMC. 1 for release 1.2.5, 1 for beta 1.2_02, and 2 for beta 1.7.3. But I don't know if I properly installed them because I can't run them! The auto-detect feature isn't working, and every java I installed isn't working! The latest version, Java 8, everything! Does anyone know what's going on and how to fix it?

### Steps to reproduce

Honestly, I don't know  what's causing this. That's what I can't figure out.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide some logs

![grafik](https://user-images.githubusercontent.com/2097483/183251099-de6412a5-3a9e-4c5b-9ffd-b461ae972ded.png)

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, you can still reply to this issue. Or feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
