### ISSUE TITLE
Accessibility Issue: MultiMC needs to respect Windows (or other OS) UI scaling

### ISSUE THREAD

**Issue by Sinhika** [MultiMC/Launcher#4868]
### Role

I play Modded Minecraft / develop Minecraft mods

### Suggestion

I want the UI and icons to scale per Windows desktop UI scaling

### Benefit

Accessibility--with high-res monitors, MMC's icons and text are microscopic and require a lot of squinting.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have no idea if this issue is unique, but I couldn't find it with obvious keywords.

When I launch MMC, I feel like I am launching some old Windows 98 program whose devs never imagined 2560x1440 resolutions, let alone 4K HD or better. The icons are tiny, as is the text accompanying them in and in the menus. I could not find any option in the Settings menu to scale the UI; if there is one, you need to make it easier to find.

Meanwhile, my Windows desktop has icons scaled to useful size, and likewise the text is easily readable. My native windows apps also respect the UI scaling settings. Linux, OTOH, has a problem with this.

**Comment by phit** [comment]
use this build https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip the old Qt version shipped by default does not handle scaling, but is needed for a wider version support on Windows
