### ISSUE TITLE
make it possible to different jvm for each instance

### ISSUE THREAD

**Issue by kdh8219** [MultiMC/Launcher#4869]
### Role

I play vanilla minecraft and moded minecraft

### Suggestion

Enable different version of jvm for each instance

### Benefit

1.19 and 1.12.2 will be able to be played together.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
That's already possible https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#set-instance-java-installation
