### ISSUE TITLE
Minecraft has stopped running because it encountered a problem; Failed to start game

### ISSUE THREAD

**Issue by Terror988** [MultiMC/Launcher#4872]
### Operating System

Windows

### Description of bug

when starting the game, it gives an error
[crash-2022-08-07_14.10.43-client.txt](https://github.com/MultiMC/Launcher/files/9276651/crash-2022-08-07_14.10.43-client.txt)

### Steps to reproduce

I start the game, it is loading, the game gives an error window

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
