### ISSUE TITLE
pixelmon modpack

### ISSUE THREAD

**Issue by Ryderr1221** [MultiMC/Launcher#4873]
### Operating System

Windows

### Description of bug

Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'
Couldn't extract native jar 'C:/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar' to destination 'C:/MultiMC/instances/pixelmon/natives'

### Steps to reproduce

open pixelmon reforged

### Suspected cause

?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
restart your pc

**Comment by Ryderr1221** [comment]
i restarted my pc but does't work

**Comment by phit** [comment]
then provide a full log

![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by Ryderr1221** [comment]
https://paste.ee/p/7tlLT

**Comment by phit** [comment]
well first https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
then do you have any other antivirus than windows'?

**Comment by Ryderr1221** [comment]
https://paste.ee/p/xR4ab

**Comment by phit** [comment]
that's still the wrong Java version
