### ISSUE TITLE
Making new or starting old instances do not work anymore, probably java problem

### ISSUE THREAD

**Issue by FeGiant** [MultiMC/Launcher#4874]
### Operating System

Windows

### Description of bug

Cannot download, install and launch old and new instances.
Here is the log for "Create Above and Beyond v1.2" for example: https://paste.ee/p/6xbr2

### Steps to reproduce

I messed arround with java . Had to delete and re-install it.
And what I mean is I downloaded the latest java first (jdk-18), then JavaSerup8u341, jre-9.0.4_windows-x64_bin, jdk-17.0.4_windows-x64_bin. None of them made it work.

### Suspected cause

All te versions of java were gone and I needed to re-install them. Even my chrome, that had google as the default search engine in the top bar, defaulted to YaHoo.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
