### ISSUE TITLE
Minecraft (B.1.7.3) Stops after  halfa' second of running

### ISSUE THREAD

**Issue by TheFourPointedStar** [MultiMC/Launcher#4875]
### Operating System

Windows

### Description of bug

https://paste.ee/p/yGwDN
Minecraft starts for a second, Then turns black and is killed
(Sorry if this has already been documented and "Fixed", I am very lazy and have a burning feeling of want that needs me to make this)

### Steps to reproduce

Double click b1.7.3 (Or press launch) 

### Suspected cause

![image](https://user-images.githubusercontent.com/100541355/184337260-6a525a87-0c86-473c-9899-800eb7fcc778.png)
 Either java (at 08)
 Or... something else!

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
try this Java version https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

**Comment by TheFourPointedStar** [comment]
> try this Java version https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

Tried that already, didnt work due to the config file being corrupted or somethin. (Mmc cant read it [could be a fault on my part though])

**Comment by TheFourPointedStar** [comment]
> try this Java version https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs


My brain is so smooth, Thank you so much!
At first it didnt work due to some config file not workin- But ty so much!
