### ISSUE TITLE
MultiMC crashing when setting user

### ISSUE THREAD

**Issue by DreadfulViolet** [MultiMC/Launcher#4876]
### Operating System

Windows

### Description of bug

Every single time the launch log reaches the point of setting the user it fails and exits, sometimes immediately crashing my entire PC. I've had times it's worked with certain internet connections, sometimes after restarting my PC, sometimes after removing and adding back in my MS account. It seems to decide to work at random times.

Including log file, https://paste.ee/p/EySCE

### Steps to reproduce

Anytime when launching MC

### Suspected cause

Potential issues with how MultiMC is handling the authorization process with MS? I really have no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
check the file C:\Games\MultiMC\instances\1.19 mods\.minecraft\hs_err_pid14092.log
the crash happening after the log message for user setting is probably unrelated and either way that's the games doing, not multimc
if it's crashing your pc, it could be bad hardware

**Comment by DreadfulViolet** [comment]
I've certainly gone down the path assuming it was my PC crashing but seeing as how nothing unusual happens to my hardware during the issue and the fact that I've stress tested every part of my PC and this is the only instance of it crashing like this i believe I've ruled out that much so far

The only things that have seemingly alleviated the issue has been switching internet connections, restarting my PC, and removing and re-adding the MS account.

[hs_err_pid14092.log](https://github.com/MultiMC/Launcher/files/9331511/hs_err_pid14092.log)

**Comment by phit** [comment]
can you try using Java 17, but this really does look like bad memory to me, also at least that crash is when vanilla code unrelated to auth is being called

**Comment by DreadfulViolet** [comment]
Yeah that was the first thing I tested, I ran stress tests on my memory for rather lengthy periods of time and never once came up with an error let alone crashed anything. I'll try Java 17 and see what happens.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
