### ISSUE TITLE
Specific version of Minecraft & Forge work on standard MC launcher but not on MultiMC

### ISSUE THREAD

**Issue by GreenbanditMZrider** [MultiMC/Launcher#4878]
### Operating System

Windows

### Description of bug

When this exact same combination of Minecraft & Forge are run using the Mojang launcher, they work. But when run using MultiMC the instance crashes when run giving the attached log
[mmc crash 220814.txt](https://github.com/MultiMC/Launcher/files/9332974/mmc.crash.220814.txt)
.

### Steps to reproduce

1 - Install minecraft 1.16.5.
2 - Install Forge 36.2.2.
3 - Set max mem to 2048MB
4 - Select either Oracle Java 17.0.4 (because this is what the Mojang launcher picks up), or select Oracle 1.8.0_341 (because this is the earlier version of java that I believe is needed for this version of Minecraft.
5 - Launch.

### Suspected cause

It seems to be the selection of Forge 36.2.2 with Minecraft 1.16.5 (because Forge 36.2.34 does not crash), but the specific combination of mods that I want to use (listed in the log file but all disabled) will not run using Forge 36.2.34.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by GreenbanditMZrider** [comment]
@phit , Thank you so much. As described by you, when I use 8U312, the instance works perfectly. 

Due to my lack of knowledge in these things, I would never have worked this out myself.
