### ISSUE TITLE
Multi MC error -1

### ISSUE THREAD

**Issue by Goan125** [MultiMC/Launcher#4879]
im trying to launch minecraft through MultiMC but it doesnt start. 

Process:
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [216.137.61.48, 216.137.61.34, 216.137.61.43, 216.137.61.49]

session.minecraft.net resolves to:
    [107.20.118.247, 52.72.238.122, 54.172.106.247]

textures.minecraft.net resolves to:
    [18.154.41.110, 18.154.41.80, 18.154.41.51, 18.154.41.31]

api.mojang.com resolves to:
    [13.224.115.45, 13.224.115.89, 13.224.115.123, 13.224.115.33]

Minecraft folder is:
C:/Users/Usuario/Desktop/amogus/MultiMC/instances/1.15.2/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 18, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/Usuario/Desktop/amogus/MultiMC/instances/1.15.2/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/forge/1.15.2-31.2.57/forge-1.15.2-31.2.57-launcher.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/cpw/mods/modlauncher/5.1.2/modlauncher-5.1.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/accesstransformers/2.1.3-shadowed/accesstransformers-2.1.3-shadowed.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/eventbus/2.2.1-service/eventbus-2.2.1-service.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/forgespi/3.0.0/forgespi-3.0.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/coremods/2.0.3/coremods-2.0.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/minecraft/1.15.2/minecraft-1.15.2-client.jar

Native libraries:
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] [1.15.2]+SecurityCraft+v1.9.0.2
  [✔️] AppleSkin-mc1.15.2-forge-1.0.13
  [✔️] ChunkPregenerator-V1.15-3.2.0
  [✔️] CosmeticArmorReworked-1.15.2-v3a
  [✔️] CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-325
  [✔️] dungeons-plus-1.15.2-1.0.2
  [✔️] Extra-Boats-Mod-1.15.2
  [✔️] Ma-Essentials-1.15.2-3.1.1
  [✔️] mine-mine-no-mi-1.15.2-0.8.1
  [✔️] performant-1.15-3.16m
  [✔️] PiratesAndLooters6.2-1.15.2
  [✔️] structure-gel-api-1.15.2-1.1.0
  [✔️] tombstone-4.6.0-1.15.2
  [✔️] TravelersBackpack-1.15.2-4.0.8
  [✔️] u_team_core-1.15.2-3.0.2.207
  [✔️] voicechat-1.15.2-1.0.2
  [✔️] Waystones_1.15.2-6.0.0
  [✔️] worldedit-forge-mc1.15.2-7.1.0
  [✔️] WorldProtector+1.15.2
  [✔️] XL-Food-Mod-1.15.2-2.2.2
  [✔️] xptome-1.15.2-v2.0.1

Params:
  --username  --version 1.15.2 --gameDir C:/Users/Usuario/Desktop/amogus/MultiMC/instances/1.15.2/.minecraft --assetsDir C:/Users/Usuario/Desktop/amogus/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 31.2.57 --fml.mcVersion 1.15.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200515.085601

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 19340

Using onesix launcher.

Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2022-08-14 12:07:04,078 main WARN Advanced terminal features are not available in this environment
[32m[12:07:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, goan111, --version, 1.15.2, --gameDir, C:/Users/Usuario/Desktop/amogus/MultiMC/instances/1.15.2/.minecraft, --assetsDir, C:/Users/Usuario/Desktop/amogus/MultiMC/assets, --assetIndex, 1.15, --uuid, <ID DEL PERFIL>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.57, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601, --width, 854, --height, 480]
[m[32m[12:07:04] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 18 by Oracle Corporation
[m[32m[12:07:08] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[32m[12:07:08] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Usuario/Desktop/amogus/MultiMC/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT

El proceso ha finalizado de forma inesperada con el código -1073741819 (0xffffffffc0000005).
Debajo se encuentra un análisis del código de salida. ¡ESTO PUEDE SER INCORRECTO Y DEBERÍA SER TOMADO CON PINZAS!
Nombre del código de salida del sistema: STATUS_ACCESS_VIOLATION
Descripción del código de salida del sistema: La instrucci�n en 0x%p hace referencia a la memoria en 0x%p. La memoria no se pudo %s.

¡Por favor, ten en cuenta que normalmente ni el código de salida ni su descripción son suficientes para diagnosticar problemas!
Sube siempre el registro entero y no solo el código de salida.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
