### ISSUE TITLE
CurseForge Annotation on Import From .zip

### ISSUE THREAD

**Issue by AndyKills457** [MultiMC/Launcher#4882]
### Role

I used to install modpacks this way and it took me a couple hours to find out it wasn't a fault on my end.

### Suggestion

Add an annotation to the [Import from zip] tab of the [Add Instance] menu

### Benefit

Users will have easy access to information about this topic.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The annotation should containin the fact that curseforge modpacks can no longer be added this way, a brief explanation as to why and a link leading to the github thread where the developer explains this in detail.

**Comment by phit** [comment]
There's a news post at the bottom of the launcher about it and the lack of dedicated Curseforge tab should be enough, we can't keep notices everywhere in MultiMC about removed features.
