### ISSUE TITLE
MultiMC crashes every time minecraft closes with code -1073740940, states heap corruption

### ISSUE THREAD

**Issue by Shadowex3** [MultiMC/Launcher#4887]
### Operating System

Windows

### Description of bug

Every time I close an instance it shuts down fine but MultiMC states the below (excerpt of [full log](https://paste.ee/p/NU4Vw)):

```
Process crashed with exitcode -1073740940 (0xffffffffc0000374).
Below is an analysis of the exit code. THIS MAY BE INCORRECT AND SHOULD BE TAKEN WITH A GRAIN OF SALT!
System exit code name: STATUS_HEAP_CORRUPTION
System exit code description: A heap has been corrupted.

Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

### Steps to reproduce

Enjoy minecraft (enjoyment optional), close game.

### Suspected cause

Unknown. Everything appears to work fine. This happens every time I close Minecraft, but there doesn't seem to be anything wrong otherwise. The only thing that doesn't work (and receives the same error) is trying to load or re-order resource packs. That will take several times as long as loading up minecraft to begin with and then crash every time with the same message.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
