### ISSUE TITLE
FTB App Import causing launching issues with FTB Oceanblock version 1.15.1

### ISSUE THREAD

**Issue by DanielB456** [MultiMC/Launcher#4890]
### Description of bug

I keep trying to use the FTB App Import tool to import the newly installed version of FTB Oceanblock 1.15.1. And I keep getting the "Failed to load mod" Error upon launch. But it launches perfectly fine from the FTB app. The two mods it's having a problem with are CBMultipart and ProjectRed Illumination, both mods remain unchanged from Oceanblock version 1.14.0 which did manage to import correctly without error.

![Screenshot 2022-08-24 183054](https://user-images.githubusercontent.com/91753281/186535063-48e2bfb4-f5d2-491e-8897-3f95fa1cbae0.png)
[crash-2022-08-24_18.26.16-fml.txt](https://github.com/MultiMC/Launcher/files/9419838/crash-2022-08-24_18.26.16-fml.txt)
.

### Steps to reproduce

-Install FTB Oceanblock verison 1.15.1 on Feed The Beast App from Overwolf.
-Open MultiMC and create a new instance
-Use the "FTB App Import" tool and import Oceanblock 1.15.1
-Launch the instance.

### Suspected cause

As stated in the description of the issue and crash log, CBMultipart and ProjectRed Illumination are causing the problems when launching the modpack, but the versions of them remain unchanged.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
You need Java 8 for 1.16
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by DanielB456** [comment]
Got it, thank you so much. I feel very fucking stupid right now.
