### ISSUE TITLE
Crash exit code -1 Or EnderIO/AE2 possible issue?

### ISSUE THREAD

**Issue by DemonicTYB** [MultiMC/Launcher#4893]
### Operating System

Windows

### Description of bug

This happened before but now im getting annoyed of going back 30 mins to past backups. When it first happened I was exploring new areas and then game froze and crashed , then I try to launch again and i load in and as soon as i try to move it crashes. So i just reboot my last backup and stayed away from the area.
Now im exploring a new area and it has happened again and im getting tired of it. At first I thought it had something to do with "The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED"
Then with more looking i see it says something along the line of being "exited with code -1"
Now it says "Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it"
 Now i havent tried reproducing this cause i have no clue if this is the actual issue or even how to update/degrade minecraft mods while keeping everything compatible              

https://paste.ee/p/Xm380

https://paste.ee/p/l545r

Im not too sure which log to post so if someone lets me know which one specifically i'll be more then happy to supply it. I just really am tired of dealing with this

### Steps to reproduce

Walk into a random chunk in my world and hope it crashes and check log, idk lol

### Suspected cause

"The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED"
 
"exited with code -1"

"Ender IO was build against API version rv2 and may or may not work with a newer version.
 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it"
 
 Maybe a block is spawning that is causing the crash but i cant find it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
