### ISSUE TITLE
'Archive does not contain a recognized modpack type' issue when trying to load a modpack

### ISSUE THREAD

**Issue by ValorGames** [MultiMC/Launcher#4894]
### Description of bug

Everytime I try to load a Curseforge modpack from 'Import from zip' since the update that removed Curseforge from 'Add Instance' I get this error message.

### Steps to reproduce

Loading a Curseforge modpack from 'Import from zip'

### Suspected cause

The Update that removed Curseforge from 'Add Instance'

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
not sure what you expect, as you already said, the feature was removed
