### ISSUE TITLE
Multi Mc keeps crashing

### ISSUE THREAD

**Issue by Monsterid28** [MultiMC/Launcher#4895]
### Description of bug

Normal Minecraft works fine but when I try to play it modded it starts for a second than crashes and says process existed with code -1

### Steps to reproduce

  .

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them.
![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by Monsterid28** [comment]
https://paste.ee/p/MfI4z

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Monsterid28** [comment]
which one do I need
