### ISSUE TITLE
1.12 does not open 

### ISSUE THREAD

**Issue by Robking0102** [MultiMC/Launcher#4896]
### Operating System

Windows

### Description of bug

properly 1.12 it opens with no problem, but when you add liteloader to the instance it crashes and doesn't open

when i try to open the instance, this is the error message:
![image](https://user-images.githubusercontent.com/112295592/187055332-8eaeda8d-cb3d-42c9-83b5-f1b777cabec8.png)

### Steps to reproduce

*

### Suspected cause

*

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
