### ISSUE TITLE
Minecraft keeps crashing when launching 

### ISSUE THREAD

**Issue by bytouille** [MultiMC/Launcher#4897]
### Description of bug

When i start MC 1.16.4 with only Optifine, it's crashing when i go to 350MB on 4000MB here is the crash report : 
https://paste.ee/p/uE1Zq

### Steps to reproduce

just launch minecraft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Forge 34.1.27 to 36.2.24 (Minecraft 1.16.3-1.16.5) are broken with Java 8 Update 321 or newer.
If you are on 1.16.5 try upgrading your instances Forge version. If this isn't an option for you, you need an older Java 8 version, e.g. 8u312 you can find downloads here <https://www.azul.com/downloads/?version=java-8-lts&os=windows&architecture=x86-64-bit&package=jre&show-old-builds=true#download-openjdk>

the crash will contain this
```
Caused by: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
```

**Comment by Monsterid28** [comment]
How do I know which one to use
