### ISSUE TITLE
Curseforge modpacks import from zip failure

### ISSUE THREAD

**Issue by Vinidia** [MultiMC/Launcher#4898]
### Operating System

Manjaro linux519

### Description of bug

Importing an archive downloaded from Curseforge causes error: 

"Archive does not contain recognized modpack." 

### Steps to reproduce

1. Find modpack of choice on Curseforge website. Download archive.
2. In the MultiMC launcher, select add instance, import from zip. 
3. Select browse, select downloaded archive. Select okay.

### Suspected cause

MultiMC may not currently be able to read HTML files such as "modlist.html."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://multimc.org/posts/0-6-16-update.html
