### ISSUE TITLE
Error where JRE can't run because of ''insufficient memory to continue''

### ISSUE THREAD

**Issue by awesomecoderguy** [MultiMC/Launcher#4900]
Error code 0x1
Modpack: Sugar 3.2.2 running BSL Shaders 8.1.03
Error report stored in https://paste.ee/p/Uqgnm

**Comment by phit** [comment]
Doesn't look like you are using MultiMC, ask whatever project you are using for support. We only support official releases here.

**Comment by awesomecoderguy** [comment]
i am using it

**Comment by phit** [comment]
no you are not, you are using something abusing the MultiMC trademark
