### ISSUE TITLE
feature request: when you upload a screenshot you'll be asked to be if we are really sure to upload it

### ISSUE THREAD

**Issue by Potffin** [MultiMC/Launcher#4901]
### Role

I play vanilla minecraft 

### Suggestion

Ask us (the user) to ask if we really want to uplaod the screenshot to imgur

### Benefit

to not mistakenly upload the wrong screenshot 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ryanbrown535** [comment]
Made pull request #4928
