### ISSUE TITLE
Can't start minecraft 1.8.9 forge

### ISSUE THREAD

**Issue by Lowrlor** [MultiMC/Launcher#4903]
### Operating System

Linux

### Description of bug

MultiMC version: 0.6.16-3430

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.119.37, 18.66.119.35, 18.66.119.38, 18.66.119.42]

session.minecraft.net resolves to:
    [44.199.38.182, 34.225.172.83, 52.5.26.48]

textures.minecraft.net resolves to:
    [18.66.112.103, 18.66.112.77, 18.66.112.79, 18.66.112.60]

api.mojang.com resolves to:
    [108.138.17.3, 108.138.17.109, 108.138.17.41, 108.138.17.100]

Minecraft folder is:
/home/vicheslav/.local/share/multimc/instances/1.8.9/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 11.0.16, using 64-bit architecture, from Ubuntu.

AMD A4-7210 APU with AMD Radeon R3 Graphics
Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R3 Graphics] (rev 45)

Subsystem: Lenovo Mullins [Radeon R3 Graphics]

Kernel driver in use: radeon

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.1.4 - kisak-mesa PPA

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/vicheslav/.local/share/multimc/instances/1.8.9/natives

Libraries:
  /home/vicheslav/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/vicheslav/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/vicheslav/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/vicheslav/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/vicheslav/.local/share/multimc/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /home/vicheslav/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/vicheslav/.local/share/multimc/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  /home/vicheslav/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/vicheslav/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/vicheslav/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  /home/vicheslav/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/vicheslav/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/vicheslav/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/vicheslav/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/vicheslav/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/vicheslav/.local/share/multimc/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  /home/vicheslav/.local/share/multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/vicheslav/.local/share/multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/vicheslav/.local/share/multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/vicheslav/.local/share/multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/vicheslav/.local/share/multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/vicheslav/.local/share/multimc/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/vicheslav/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/vicheslav/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /home/vicheslav/.local/share/multimc/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  /home/vicheslav/.local/share/multimc/libraries/net/minecraftforge/forge/1.8.9-11.15.1.2318-1.8.9/forge-1.8.9-11.15.1.2318-1.8.9-universal.jar
  /home/vicheslav/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/vicheslav/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /home/vicheslav/.local/share/multimc/libraries/jline/jline/2.13/jline-2.13.jar
  /home/vicheslav/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/vicheslav/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/vicheslav/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/vicheslav/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/vicheslav/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/vicheslav/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/vicheslav/.local/share/multimc/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  /home/vicheslav/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/vicheslav/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username  --version 1.8.9 --gameDir /home/vicheslav/.local/share/multimc/instances/1.8.9/.minecraft --assetsDir /home/vicheslav/.local/share/multimc/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType  --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms2048m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 21589

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 05 Sep 2022 13:41:21 +0300

### Steps to reproduce

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Lowrlor** [comment]
Yes, ty, it's helps
