### ISSUE TITLE
Downloading old modpack versions (with a different MCver than the newest modpack version) from Modrinth installs the wrong MCver

### ISSUE THREAD

**Issue by srbuttcheeks** [MultiMC/Launcher#4909]
### Operating System

Windows

### Description of bug

This actually caused windows to blue screen lol.

I was installing Fabulously Optimized v1.12.3, the 1.16.5 version of the modpack. Upon installing I noticed that on the Version tabs, the wrong loaders are used:

LWLGL 3.3.1; MC 1.19.2; Intermediary Mappings 1.19.2; Fabric Loader 0.14.9

These are all for 1.19.2, not 1.16.5 as would be expected.

### Steps to reproduce

1. Create instance -> Modrinth -> Fabulously Optimized
2. Change "Version selected" to 1.12.3
3. Install
4. Edit Instance -> Version

wrong things installed. 

### Suspected cause

The newest version of FabOpt is 4.3.0, a modpack for 1.19.2. MMC most probably just didn't notice there was a change between versions. I'd expect the same bug to happen across different modpacks with the same quality, but tbh I don't wanna risk another blue screen of death.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
this was fixed with https://github.com/MultiMC/Launcher/commit/0917706b22b21a3074b31c2e8b6a047f9fc560ca, please update to the development version (Settings > Update Channel)
