### ISSUE TITLE
Wrong version imported from modrinth modpack

### ISSUE THREAD

**Issue by JustRad123** [MultiMC/Launcher#4910]
### Operating System

_Windows 10_

### Description of bug

when trying to import  fabulously optimised 1.16 or simply optimised 1.17 it imports latest version instead 

### Steps to reproduce

create new instance , modrinth , choose eiehter fabulously optimised 2.7.3 or simply optimised 1.17 1.0 

### Suspected cause

no idea 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
this was fixed with https://github.com/MultiMC/Launcher/commit/0917706b22b21a3074b31c2e8b6a047f9fc560ca, please update to the development version (Settings > Update Channel)
