### ISSUE TITLE
cant open instance do not know why (Error code 255) (Ubuntu)

### ISSUE THREAD

**Issue by loudrockexe** [MultiMC/Launcher#4913]
**Log**
MultiMC version: 0.6.16-3430

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.239.36, 108.138.239.63, 108.138.239.55, 108.138.239.37]

session.minecraft.net resolves to:
    [44.199.38.182, 52.5.26.48, 34.225.172.83]

textures.minecraft.net resolves to:
    [108.138.246.90, 108.138.246.85, 108.138.246.57, 108.138.246.63]

api.mojang.com resolves to:
    [108.139.1.50, 108.139.1.70, 108.139.1.51, 108.139.1.102]

Minecraft folder is:
/home/loudrock/.local/share/multimc/instances/1.12.2/.minecraft

Java path is:
/usr/bin/java

Checking Java version...
Java is version 11.0.16, using 64-bit architecture, from Ubuntu.

Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)

DeviceName: Onboard IGD

Subsystem: Hewlett-Packard Company EliteBook 840 G3

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.6

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/loudrock/.local/share/multimc/instances/1.12.2/natives

Libraries:
  /home/loudrock/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/loudrock/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/loudrock/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/loudrock/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /home/loudrock/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/loudrock/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/loudrock/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/loudrock/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/loudrock/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/loudrock/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/loudrock/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/loudrock/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/loudrock/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/loudrock/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/loudrock/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/loudrock/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/loudrock/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/loudrock/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/loudrock/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/loudrock/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/loudrock/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/loudrock/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  /home/loudrock/.local/share/multimc/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  /home/loudrock/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/loudrock/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/loudrock/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/loudrock/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/loudrock/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/loudrock/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/loudrock/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/loudrock/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/loudrock/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/loudrock/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/loudrock/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/loudrock/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  [✔️] !mixinbooter-5.0
  [✔️] AdPoles-1.12.2-2.0.3.0-build.0552
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] Baubles-1.12-1.5.2
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] Botania+r1.10-364.4
  [✔️] Controlling-3.0.10
  [✔️] ExtraPlanets-1.12.2-0.7.4
  [✔️] FluxNetworks-1.12.2-4.1.1.34
  [✔️] ForgeEndertech-1.19.2-10.0.5.0-build.0599
  [✔️] ftb-ultimine-1202.3.5
  [✔️] FTBLib-5.4.7.2
  [✔️] FTBUtilities-5.4.1.131
  [✔️] FTBUtilitiesBackups-1.0.0.1
  [✔️] Galacticraft-1.12.2-4.0.3
  [✔️] HammerLib-1.12.2-2.0.6.32
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] JEROreIntegration-1.12.2-1.1.0
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] Mekanism-1.12.2-9.8.3.390
  [✔️] MJRLegendsLib-1.12.2-1.2.1
  [✔️] More-Planets-1.12.2-2.2.4-GC284
  [✔️] MushroomQuest+1.12.2+-+v1.7
  [✔️] Neat+1.4-17
  [✔️] OpenComputers-MC1.12.2-1.7.7+5413028
  [✔️] Patchouli-1.0-23.6
  [✔️] preview_OptiFine_1.12.2_HD_U_G6_pre1
  [✔️] rangedpumps-0.5
  [✔️] refinedstorage-1.6.16
  [✔️] refinedstorageaddons-0.4.5
  [✔️] SchnurriTV's Sexmod-1.6.2
  [✔️] SolarFluxReborn-1.12.2-12.4.11
  [✔️] Wawla-1.12.2-2.6.275

Params:
  --username  --version 1.12.2 --gameDir /home/loudrock/.local/share/multimc/instances/1.12.2/.minecraft --assetsDir /home/loudrock/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms3200m, -Xmx7838m, -Duser.language=en]

Minecraft process ID: 31784

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 13 Sep 2022 01:10:40 -0700

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
