### ISSUE TITLE
"Use defult game dictonary" Button for MultiMC!

### ISSUE THREAD

**Issue by TheNopCrafter** [MultiMC/Launcher#4914]
### Role

I play Minecraft with different mod combinations, But I don't want to have to copy always the worlds (when there are changes) and so on in the different instance folder.

### Suggestion

I want that there is a button called "Use Default Folder" in the Options for a single instance at the menu points Resource Packs, Shader Packs, World Folder, Server List, Screenshots and the Optionts.txt file (for key binds etc.) Then I would finally make MultiMC to my main launcher. Because this is the only missing thing!

### Benefit

Because I do not always want to copy the Resource Packs, Screenshots, Server list or update my hotkeys etc.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by TheNopCrafter** [comment]
Oh, sorry, I've searched for this, but probably not that thoroughly. Maybe I had some filter active... Sorry, I haven't been here that long!

**Comment by phit** [comment]
see https://github.com/MultiMC/Launcher/issues/4848, https://github.com/MultiMC/Launcher/issues/2440, https://github.com/MultiMC/Launcher/issues/3861
