### ISSUE TITLE
Minecraft crashes when fabric and forge runs with eachother.

### ISSUE THREAD

**Issue by FlyingCraby** [MultiMC/Launcher#4919]
### Operating System

Windows

### Description of bug

When running fabric and forge on minecraft version 1.19.2, minecraft crashes with exit code -1.  I have searched in the issues section and only found one same problem.  But the solution for the problem was out dated.

https://github.com/MultiMC/Launcher/issues/4211

### Steps to reproduce

- click on create new instace
- Add a fabric and forge mod together.\
- press launch

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you cant have both, pick one
