### ISSUE TITLE
Suggestion - Auto-disable old mods when adding new one

### ISSUE THREAD

**Issue by Mrredstone5230** [MultiMC/Launcher#4926]
### Role

I play anything Minecraft on MultiMC

### Suggestion

I'm very lazy, but could it be possible to, when adding a more recent mod in an instance, it could automatically disable the old mod?

### Benefit

Time beneficial when updating mods: Only have to drag and drop a mod to update it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
impossible to decide whats old or if its even the same mod, so never happening
