### ISSUE TITLE
can't join your discord

### ISSUE THREAD

**Issue by JLSkyzer** [MultiMC/Launcher#4927]
### Description of bug

Hello, i'm ban from the discord for nothing

Is possible to ban and unban me ? 

Id : 909862540945793094
Thx
I need help is very important

### Steps to reproduce

no

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you aren't on the servers ban list

**Comment by JLSkyzer** [comment]
but it's a discord bug, we need to ban / unban the user, because my old account has been hacked
