### ISSUE TITLE
Typo in 'Import Instance' wiki page

### ISSUE THREAD

**Issue by ejm554** [MultiMC/Launcher#4933]
### Role

I play modded Minecraft with MultiMC and sometimes consult the documentation.

### Suggestion

Correct typo (see details section)

### Benefit

The documentation will be correct

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I was reading the documentation regarding importing, and I saw reference to a "text bow." I was wondering what the heck this was until I realized that the writer probably meant to say "text _box_." 

I'd like to suggest that you correct this. Or, if there is such a thing as a "text bow," please elaborate and explain what that is. 🙂

![image](https://user-images.githubusercontent.com/26723535/194305545-1592c015-894a-4d6f-8caa-e39f379e9d6d.png)

**Comment by phit** [comment]
you can correct this yourself here https://github.com/MultiMC/wiki/blob/master/Import-Instance.md

**Comment by ejm554** [comment]
> you can correct this yourself here https://github.com/MultiMC/wiki/blob/master/Import-Instance.md

I didn't know that. Thanks! I submitted a pull request.
