### ISSUE TITLE
No modpacks are starting, including previously functional ones, after updating to the newest JDK version (JDK 19).

### ISSUE THREAD

**Issue by SKDemon820** [MultiMC/Launcher#4935]
### Operating System

macOS

### Description of bug

I tried making a 1.19.2 modded instance and it says "1.18 beta 2 and higher require Java 17 or higher," so I installed java 19 from [here](https://www.oracle.com/java/technologies/downloads/) and suddently no instances, even vanilla ones, are opening.  It says "Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version" implying I'm using an outdated java version, which doesn't make sense since the issue started when I _updated_ my java version.

![Screen Shot 2022-10-11 at 10 03 27 PM](https://user-images.githubusercontent.com/62918850/195232595-031d2acf-7eaa-4aa2-a151-367cd20da731.jpg)

[New Paste 1.txt](https://github.com/MultiMC/Launcher/files/9760894/New.Paste.1.txt)

### Steps to reproduce

- Make a working modpack with an old java version
- Update to JDK 19
- None of the modpacks open anymore

### Suspected cause

Updating to JDK 19

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SKDemon820** [comment]
Update: Completely deleting the JDK from the java folder in /Library makes old packs work again, but doesn't fix the issue for newer game versions because those higher java versions are required for them to run.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by SKDemon820** [comment]
> Check the line of text above the one you circled: your MultiMC had **selected** the 32-bit Java architecture, which is very limited in the amount of RAM it can use, so most modpacks simply cannot launch. Most computers now are 64-bit based, so you should always try to use the 64-bit JDK.
> 
> Go into your instance settings, Java, and select the appropiate JDK for EACH separate instance, which is how you can make older packs run on Java 8 and newer packs on Java 17 for example.
> 
> If that doesn't help either, start from using Java 17, **64-bit** and make sure that MultiMC actually selects it in the instance settings.

I'm using the Arm 64 JDK 19 from [here](https://www.oracle.com/java/technologies/downloads/#jdk19-mac) and Multi MC claims that it's using a 32 bit architecture, despite Oracle reporting it as 64 bit (Which makes sense because current macs can't even run 32 bit apps, so why would they make the standard install a 32 bit one in the first place?).  The 64 bit option in the ss doesn't work because it isn't JDK 17 or later, and JDK 19 doesn't work because it's apparently 32 bit.  The link I shared where I got my JDK is the main, official source (and as far as I can see, the only official source), so if that's 32 bit according to MMC where are the 64 bit versions?

![Screen Shot 2022-10-12 at 1 16 49 PM](https://user-images.githubusercontent.com/62918850/195409975-c1f09c2f-85a7-408d-983f-7eb44137f699.jpg)

**Comment by phit** [comment]
you need x64 Java, ARM is not supported by MultiMC

**Comment by SKDemon820** [comment]
> you need x64 Java, ARM is not supported by MultiMC

I know it's a pretty niche group so you probably don't know the answer, but are you aware of _anybody_ using 1.18+ MC versions with MultiMC on macs with Apple Silicon chips then?  Because the x64 JDK isn't compatible with those macs at all (it simply errors and directs you to the ARM one), I checked the MultiMC site for more specifics on mac compatibility but all it specifies is an OS of 10.13+, nothing about the chipset.

**Comment by SKDemon820** [comment]
Ya the default launcher works fine, although iirc it uses some compatibility layer or work around to do so (That's just something I remember reading though, I don't have any source and they may just use a native method).

I just prefer MultiMC for anything other than my main instance (1.8.9) because switching between versions like that messes up my controls on older instances (no idea why, you'd think all that data would be completely separate between instances but apparently not) , but if 1.18+ MultiMC doesn't work at all on M1/M2 macs then oh well.

**Comment by phit** [comment]
install x64 java from one of the sources listed in the wiki that isnt oracle and youll be fine https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by SKDemon820** [comment]
That worked, thanks!  Sorry to bother you guys, I completely missed that when looking at the wiki before because I saw it under the Windows section and assumed it was just for that OS.
