### ISSUE TITLE
Crash errors

### ISSUE THREAD

**Issue by KaiRocks2006** [MultiMC/Launcher#4936]
### Operating System

Windows

### Description of bug

Minecraft version 1.5.2 keeps crashing

### Steps to reproduce

Literally launch 1.5.2

### Suspected cause

Possibly my modded jar, though it worked fine before

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
