### ISSUE TITLE
No cursed forge button?

### ISSUE THREAD

**Issue by GrandmasterEgg** [MultiMC/Launcher#4938]
### Operating System

Windows

### Description of bug

I don't know if I'm just blind or if something is bugged but there's no way to install cursed forge mods. I followed the instructions from the home page, clicked on FTB Import, but then it said to look for the cursed forge logo and there just isn't one?

If this has been asked before I apologize, I don't know how to use GitHub

![Screenshot (481)](https://user-images.githubusercontent.com/115850991/195962606-ad71489b-b2c6-405f-9772-757c6edb004d.png)

### Steps to reproduce

* select new instance
* select FTB Import

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GrandmasterEgg** [comment]
Oh. Nevermind. Its in the FTB App itself. not MMC. I'm just blind. My bad.

**Comment by ffuentesm** [comment]
Can you explain how you solved this? 
I am trying to install the new Vault Hunters 3 in 1.18.2, but the ZIP file is not working and I am not sure how I should install the mod pack.
