### ISSUE TITLE
Fullscreen does not work

### ISSUE THREAD

**Issue by julienallexandre** [MultiMC/Launcher#4944]
### Operating System

Windows

### Description of bug

In the settings I activated the full screen mode and it doesn't work.

Version : 0.6.16-3431 
Platform : win32
Number of build : 3431
Canal : stable

### Steps to reproduce

Here is a video of the problem: https://user-images.githubusercontent.com/58303569/196560618-dc1114b5-1175-475d-87a0-2c1504894ce1.mp4

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the setting only works for a limited number of minecraft versions, use the in game settings for modern versions instead
