### ISSUE TITLE
Instance refuses to open 

### ISSUE THREAD

**Issue by Akanthodis95** [MultiMC/Launcher#4945]
### Operating System

Windows

### Description of bug

When I try to open instance, it crashes immediately and shows me the error report highlighted in black and red.

Here is the log upload from Paste.ee

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.149.48, 108.138.149.64, 108.138.149.51, 108.138.149.65]

session.minecraft.net resolves to:
    [34.199.236.154, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.249.74.68, 13.249.74.36, 13.249.74.84, 13.249.74.26]

api.mojang.com resolves to:
    [13.226.184.105, 13.226.184.29, 13.226.184.72, 13.226.184.36]

Minecraft folder is:
C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/fmlloader/1.19.2-43.1.2/fmlloader-1.19.2-43.1.2.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] OptiFine_1.19.2_HD_U_H9

Params:
  --username  --version 1.19.2 --gameDir C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/.minecraft --assetsDir C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 43.1.2 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 854 x 480

Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
Couldn't extract native jar 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar' to destination 'C:/Users/thebe/Downloads/mmc-stable-win32/MultiMC/instances/1.19.2/natives'
MultiMC: Log upload triggered at: 18 Oct 2022 18:04:14 -0500

### Steps to reproduce

1. After opening MultiMC, selecting instance to run (in this case, 1.19.2, which includes a hardcore world)
2. Goes immediately to error log

### Suspected cause

No idea. It's been working fine for weeks until now.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
restart your pc
