### ISSUE TITLE
Ferium integration

### ISSUE THREAD

**Issue by 3ri4nG0ld** [MultiMC/Launcher#4952]
### Role

I play minecraft with mods, especially from fabric.

### Suggestion

Add Ferium mods installer from the launcher, to install and update mods from one instance of MultiMC

### Benefit

This would allow users a way to install mods without having to manually search for the latest version, and would also allow an automatic update option to keep mods always up to date.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Looking for a way to update my fabric mods with more comfort for me and my friends I found that Ferium exists, and I thought it would be a good idea to have an option in MultiMC to update the mods in a simple way, since my friends don't have much knowledge of mods.

https://github.com/gorilla-devs/ferium

By the way sorry for my English, deepl is my friend. :P

**Comment by phit** [comment]
nothing stops you from doing so yourself
