### ISSUE TITLE
Can't play RLCraft anymore 

### ISSUE THREAD

**Issue by ArchFps** [MultiMC/Launcher#4953]
### Operating System

Windows

### Description of bug

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.108.35, 13.35.108.40, 13.35.108.56, 13.35.108.62]

session.minecraft.net resolves to:
    [35.153.153.200, 100.24.172.95, 34.199.236.154]

textures.minecraft.net resolves to:
    [99.84.252.120, 99.84.252.77, 99.84.252.57, 99.84.252.15]

api.mojang.com resolves to:
    [13.35.116.68, 13.35.116.10, 13.35.116.22, 13.35.116.108]

Minecraft folder is:
C:/Users/ArchFps/Desktop/MultiMc/instances/RLCraft/.minecraft

Java path is:
C:/Program Files/Java/jdk-19/bin/javaw.exe

Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/ArchFps/Desktop/MultiMc/instances/RLCraft/natives

Libraries:
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/ArchFps/Desktop/MultiMc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/ArchFps/Desktop/MultiMc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] # LibLoader
  [✔️] [___MixinCompat-0.8___]
  [✔️] _MixinBootstrap-1.1.0
  [✔️] AdHooks-1.12.2-3.3.1.0-build.0626
  [✔️] Advanced-Fishing-1.12.2-1.3.3
  [✔️] AIReducer-1.12.2-0.3.0
  [✔️] alcatrazcore-1.0.4
  [✔️] antiqueatlas-1.12.2-4.6.3
  [✔️] anvilpatch-1.1.1
  [✔️] Aquaculture-1.12.2-1.6.8
  [✔️] armorunder-mc1.12.2-1.0.0
  [✔️] astikorcarts-1.12.2-0.1.2.8
  [✔️] AutoRegLib-1.3-32
  [✔️] base-1.12.2-3.14.0
  [✔️] BattleTowers-1.12.2
  [✔️] Baubles-1.12-1.5.2
  [✔️] BedBreakBegone-1.0.1
  [✔️] better_survival-1.4.1
  [✔️] bettercaves-1.12.2-2.0.4
  [✔️] BetterCombat-1.12.2-1.5.6
  [✔️] BetterFoliage-MC1.12-2.3.3
  [✔️] BetterMineshaftsForge-1.12.2-2.2.1
  [✔️] betternether-0.1.8.6
  [✔️] BetterQuesting-3.5.329
  [✔️] BetterTabs-1.0.2
  [✔️] BlockOverlayFix-1.12.2-1.0.0
  [✔️] Bloodmoon-MC1.12.2-1.5.3
  [✔️] BNBGamingLib-1.12.2-2.17.6
  [✔️] Born In A Barn V1.8-1.12-1.1
  [✔️] Bountiful+Baubles-1.12.2-0.1.8
  [✔️] Bountiful-1.12.2-2.2.3
  [✔️] BQ_Multiblock_Structure_Integration-1.0.7
  [✔️] BQTweaker-1.3.3
  [✔️] callablehorses-1.12.2-1.1.1
  [✔️] carrotslib-mc1.12.2-1.0.0b1
  [✔️] carryon-1.12.2-1.12.6.20
  [✔️] Charm-1.12.2-1.4.1
  [✔️] ChunkAnimator-MC1.12-1.2
  [✔️] classyhats-1.6.0
  [✔️] CollisionDamage-1.2.1
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] CompatSkills-1.12.2-1.17.0
  [✔️] ContentTweaker-1.12.2-4.10.0
  [✔️] Controlling-3.0.8
  [✔️] CoralReef-2.5-1.12.2
  [✔️] corpsecomplex-1.12.2-1.0.12.0
  [✔️] craftablechainmail-1.0
  [✔️] CraftableHorseArmour-1.3.0-1.12
  [✔️] CraftTweaker2-1.12-4.1.20.674
  [✔️] CreativeCore_v1.10.70_mc1.12.2
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] defiledlands-1.12.2-1.4.3
  [✔️] disenchanter[1.12]1.8
  [✔️] DoomlikeDungeons-1.14.11-MC1.12.2
  [✔️] DynamicSurroundings-1.12.2-3.6.2.1
  [✔️] DynamicSurroundingsHuds-1.12.2-3.6.0.0
  [✔️] DynamicTrees-1.12.2-0.9.27
  [✔️] dynamictreesdefiledlands-1.12.2-1.0.0
  [✔️] DynamicTreesTraverse-1.12.2-2.1
  [✔️] ElenaiDodge-1.12.2-2.1
  [✔️] EnchantmentDescriptions-1.12.2-1.1.20
  [✔️] EnhancedVisuals_v1.4.4_mc1.12.2
  [✔️] EntityCulling-1.12.2-4.2.5
  [✔️] FamiliarFauna-1.12.2-1.0.11
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] FantasticLib-1.12.2.047
  [✔️] firstaid-1.6.20
  [✔️] FishingMadeBetter-1.12.2-2.2.4
  [✔️] foamfix-0.10.14-1.12.2
  [✔️] FoodExpansion1.3.3-1.12.2
  [✔️] ForgeEndertech-1.12.2-4.5.6.0-build.0619
  [✔️] Forgelin-1.8.4
  [✔️] forgottenitems-1.12.2-1.3.1
  [✔️] FriendlyEndermite_v1.0.1_mc1.12.2
  [✔️] fxcontrol-1.12-0.1.15
  [✔️] GlobalGameRules-1.12.2-2.2.7
  [✔️] GooglyEyes-1.12.2-7.1.1
  [✔️] grapplemod-1.12.2-v12.2
  [✔️] iceandfire-1.7.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] InfernalMobs-1.12.2
  [✔️] Inspirations-1.12.2-0.2.9
  [✔️] InventoryTweaks-1.64+dev.151
  [✔️] ISeeDragons-1.2
  [✔️] ItemPhysic_Full_1.4.37_mc1.12.2
  [✔️] itlt-1.12.x-1.0.4
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] Level Up! 2-1.1.23-1.12
  [✔️] librarianlib-1.12.2-4.22
  [✔️] llibrary-1.7.20-1.12.2
  [✔️] LoadingScreens-1.12.2-0.3.1
  [✔️] Locks-1.12.2-3.0.0
  [✔️] LootTweaker-0.3.1+MC1.12.2
  [✔️] lostcities-1.12-2.0.22
  [✔️] lycanitesmobs-1.12.2-2.0.8.5
  [✔️] MainMenuScale-1.3.2
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcw-bridges-1.0.6b-mc1.12.2
  [📁] memory_repo (folder)
  [✔️] MmmMmmMmmMmm-1.12-1.14
  [✔️] MoBends_1.12.2-1.2.1-19.12.21
  [✔️] modtweaker-4.0.20.5
  [✔️] MouseTweaks-2.10.1-mc1.12.2
  [✔️] MTLib-3.0.7
  [✔️] MultiMine-1.12.2
  [✔️] Neat 1.4-17
  [✔️] notreepunching-2.0.21
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] particleculling-1.12.2-v1.3.1
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] pigstep-1.12
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] playerbosses-1.12.2-1.1.0
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] PotionFingers-r1.0-8
  [✔️] QualityTools-1.0.7_for_1.12.2
  [✔️] Quark-r1.6-179
  [✔️] RealBench-1.12.2-1.3.3
  [✔️] RealisticTorches-1.12.2-2.1.2
  [✔️] RebornCore-1.12.2-3.19.5-universal
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Reskillable-1.12.2-1.13.0
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] RLTweaker-1.12.2-0.5.1
  [✔️] RoguelikeDungeonsFnarEdition-1.12.2-2.4.1
  [✔️] roughTweaks0.2.4-1.12.2
  [✔️] Ruins-1.12.2
  [✔️] rustic-1.1.7
  [✔️] ScalingHealth-1.12.2-1.3.42+147
  [✔️] SereneSeasons-1.12.2-1.2.18-universal
  [✔️] SetBonus-1.12.2.020
  [✔️] ShieldBreak-1.0.1
  [✔️] SilentLib-1.12.2-3.0.14+168
  [✔️] SimpleDifficulty-1.12.2-0.3.9
  [✔️] sit-1.12.2-v1.3
  [✔️] SnowRealMagic-1.12.2-0.6.1
  [✔️] SoManyEnchantments-0.5.5
  [✔️] SoundFilters-0.12.1_for_1.12
  [✔️] spartandefiled-1.0
  [✔️] spartanfire-0.05
  [✔️] SpartanHUDBaubles-1.12.2-1.0.0
  [✔️] SpartanShields-1.12.2-1.5.5
  [✔️] SpartanWeaponry-1.12.2-1.4.1
  [✔️] SpawnerControl-1.6.3b
  [✔️] SRParasites-1.12.2v1.9.1
  [✔️] StandardExpansion-3.4.173
  [✔️] switchbow-1.6.8
  [✔️] TickProfiler-1.12-0.0.10
  [✔️] tnt_utilities-mc1.12-1.2.3
  [✔️] Toast Control-1.12.2-1.8.1
  [✔️] ToolBelt-1.12.2-1.9.14
  [✔️] Traverse-1.12.2-1.6.0-69
  [✔️] Trinkets and Baubles-0.31.4
  [✔️] trumpetskeleton-1.12-1.0.2.1
  [✔️] tschipplib-1.12.2-1.1.7
  [✔️] tumbleweed-1.12-0.4.7
  [✔️] VariedCommodities_1.12.2-(13Jan22)
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] WearableBackpacks-1.12.2-3.1.4
  [✔️] WolfArmorAndStorage-3.8.1+1.12.2.alpha.1-SNAPSHOT-signed
  [✔️] XPFromHarvest-1.12.2-1.2.0
  [✔️] xptome-1.12.2-v1.1.6
  [✔️] YungsLaw-1.12.2-1.0.4

Params:
  --username  --version 1.12.2 --gameDir C:/Users/ArchFps/Desktop/MultiMc/instances/RLCraft/.minecraft --assetsDir C:/Users/ArchFps/Desktop/MultiMc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms16000m, -Xmx16169m, -Duser.language=en]

Minecraft process ID: 20064

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 25 Oct 2022 23:01:26 -0400

### Steps to reproduce

When I install and launch the modpack, it crashes instantly.

### Suspected cause

Changing my java version doesn't seem to work correctly, so maybe that's why. I've also been simultaneously switching between 1.19.2 & 1.12 modpacks and in order to do that I've had to switch between java versions. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older
