### ISSUE TITLE
org.lwjgl.LWJGLException: Pixel format not accelerated

### ISSUE THREAD

**Issue by GorkemTR45** [MultiMC/Launcher#4955]
### Description of bug

I expected the game to launch but it gave me this;
[crash-2022-10-28_12.37.10-client.txt](https://github.com/MultiMC/Launcher/files/9887308/crash-2022-10-28_12.37.10-client.txt)

### Steps to reproduce

idk just launched the instance

### Suspected cause

Probs something about drivers but they're up to date.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

**Comment by GorkemTR45** [comment]
> https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

didnt work.

**Comment by GorkemTR45** [comment]
> https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

also the game launched the past week but it doesn't launch now.
It also happens with gameloop games.
