### ISSUE TITLE
org.lwjgl.LWJGLException: Pixel format not accelerated

### ISSUE THREAD

**Issue by GorkemTR45** [MultiMC/Launcher#4956]
### Operating System

Windows

### Description of bug

It gave me this error.A week ago it was working well and fine but now it crashes before starting.Not related to this topic but a similar thing is happening in Gameloop rn it says update with Driver Genius and stuff.All my GPU's are up to date and i have looked for an answer in other bug reports but to no avail.And please don't close the bug report thing until i answer back.
Here's the full log:
[crash-2022-10-28_12.37.10-client.txt](https://github.com/MultiMC/Launcher/files/9887825/crash-2022-10-28_12.37.10-client.txt)

### Steps to reproduce

idk just launch the instance

### Suspected cause

GPU driver

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you are still using the same java version, stop making new issues and use your existing issue
