### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by Ukzan761** [MultiMC/Launcher#4957]
### Operating System

Windows

### Description of bug

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.9.75.38, 65.9.75.49, 65.9.75.58, 65.9.75.62]

session.minecraft.net resolves to:
    [100.24.172.95, 35.153.153.200, 34.199.236.154]

textures.minecraft.net resolves to:
    [18.66.171.46, 18.66.171.42, 18.66.171.67, 18.66.171.62]

api.mojang.com resolves to:
    [65.9.86.97, 65.9.86.65, 65.9.86.99, 65.9.86.17]

Minecraft folder is:
C:/Users/cauo/Documents/MultiMC/instances/FTB Revelation/.minecraft

Java path is:
C:/Program Files/Semeru/jre-18.0.2.9-openj9/bin/javaw.exe

Checking Java version...
Java is version 18.0.2, using 64-bit architecture, from IBM Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/cauo/Documents/MultiMC/instances/FTB Revelation/natives

Libraries:
  C:/Users/cauo/Documents/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/cauo/Documents/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/cauo/Documents/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/cauo/Documents/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/cauo/Documents/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/cauo/Documents/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2858/forge-1.12.2-14.23.5.2858-universal.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/cauo/Documents/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/cauo/Documents/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/cauo/Documents/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/cauo/Documents/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/cauo/Documents/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/cauo/Documents/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [📁] 1.12 (folder)
  [✔️] ActuallyAdditions-1.12.2-r152
  [✔️] ActuallyBaubles-1.12-1.1
  [✔️] Advanced Machines-61.0.1
  [✔️] Advanced Solar Panels-4.3.0
  [✔️] advmachinespatch-1.0
  [✔️] AdvSolarPatch-1.2.1
  [✔️] AE2WTLib-1.12.2-1.0.34
  [✔️] AkashicTome-1.2-12
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] architecturecraft-1.12-3.98
  [✔️] Aroma1997Core-1.12.2-2.0.0.2.b167
  [✔️] Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89
  [✔️] astralsorcery-1.12.2-1.10.27
  [✔️] AutoRegLib-1.3-32
  [✔️] badwithernocookiereloaded-1.12.2-3.4.18
  [✔️] base-1.12.2-3.14.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] bedpatch-2.2-1.12.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterBuildersWands-1.12.2-0.13.2.271+5997513
  [✔️] BiblioCraft[v2.4.6][MC1.12.2]
  [✔️] binnie-mods-1.12.2-2.5.1.203
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2445-universal
  [✔️] blockcraftery-1.12.2-1.3.1
  [✔️] BloodMagic-1.12.2-2.4.3-105
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] Botania r1.10-364.4
  [✔️] BrandonsCore-1.12.2-2.4.20.162-universal
  [✔️] buildcraft-all-7.99.24.8
  [✔️] careerbees-0.4.0
  [✔️] cc-tweaked-1.12.2-1.89.2
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChestTransporter-1.12.2-2.8.8
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] chiselsandbits-14.33
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] Computronics-1.12.2-1.6.6
  [✔️] conarm-1.12.2-1.2.5.10
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] CraftTweaker2-1.12-4.1.20.675
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] DankNull-1.12.2-1.7.101
  [✔️] DarkUtils-1.12.2-1.8.230
  [✔️] deepresonance-1.12-1.8.0
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] diethopper-1.1
  [✔️] dirt2path-1.8.0
  [✔️] Draconic-Evolution-1.12.2-2.3.28.354-universal
  [✔️] ElecCore-1.12.2-1.9.453
  [✔️] EnderCore-1.12.2-0.5.76
  [✔️] EnderIO-1.12.2-5.3.70
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] engineers_doors-1.12.2-0.9.1
  [✔️] EngineersWorkshopReborn-1.12.2-1.0.9.40
  [✔️] environmentaltech-1.12.2-2.0.20.1
  [✔️] etlunar-1.12.2-2.0.20.1
  [✔️] Exchangers-1.12.2-2.10.1
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.68
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] fencejumper-1.12-1.0.5
  [✔️] flatcoloredblocks-mc1.12-6.8
  [✔️] FluxNetworks-1.12.2-4.1.1.34
  [✔️] foamfix-0.10.14-1.12.2
  [✔️] forestry_1.12.2-5.8.2.422
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] ftb-auxilium-forge-1202.1.0-build.38
  [✔️] FTBBackups-1.1.0.1
  [✔️] FTBGuides-1.0.2.33
  [✔️] FTBLib-5.4.7.2
  [✔️] FTBUtilities-5.4.1.131
  [✔️] gendustry-1.6.5.8-mc1.12.2
  [✔️] Gravitation Suite-3.1.1
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] GunpowderLib-1.12.2-1.1
  [✔️] Harvest-1.12-1.2.8-25
  [✔️] ImmersiveCables-1.12.2-1.3.2
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.10
  [✔️] industrialcraft-2-2.8.221-ex112
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] IndustrialWires-1.7-35
  [✔️] InitialInventory-3.0.0
  [✔️] IntegrationForegoing-1.12.2-1.11
  [✔️] InventoryTweaks-1.63
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] jeibees-0.9.0.5-mc1.12.2
  [✔️] jeiintegration_1.12.2-1.6.0
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] JustEnoughEnergistics-1.12.2-1.0.8
  [✔️] just-enough-harvestcraft-1.12.2-1.7.2
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] letsencryptcraft-1.10.2-1.2.0
  [✔️] longfallboots-1.2.1b
  [✔️] lostcities-1.12-2.0.22
  [✔️] MagicBees-1.12.2-3.2.25
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] MCMultiPart-2.5.3
  [📁] memory_repo (folder)
  [✔️] MineTogether-1.12.2-2.4.5
  [✔️] modnametooltip_1.12.2-1.10.1
  [✔️] modtweaker-4.0.20.5
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] Morpheus-1.12.2-3.5.106
  [✔️] Morph-o-Tool-1.2-21
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] MTLib-3.0.7
  [✔️] mysticallib-1.12.2-1.13.0
  [✔️] natura-1.12.2-4.3.2.69
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] nice-1.12-0.4.0
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] notenoughwands-1.12-1.8.1
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-23.6
  [✔️] phosphor-forge-mc1.12.2-0.2.7-universal
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] platforms-1.12.0-1.4.6
  [✔️] plethora-1.12.2-1.2.3
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-compat
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] Quark-r1.6-179
  [✔️] QuickLeafDecay-MC1.12.1-1.2.4
  [✔️] railcraft-12.0.0
  [✔️] randompatches-1.12.2-1.22.1.10
  [✔️] rangedpumps-0.5
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.19.5-universal
  [✔️] RebornStorage-1.12.2-3.3.4.1
  [✔️] RedstoneArsenal-1.12.2-2.6.6.1-universal
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal
  [✔️] refinedstorage-1.6.16
  [✔️] refinedstorageaddons-0.4.5
  [✔️] Reliquary-1.12.2-1.3.4.796
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftools-1.12-7.73
  [✔️] rftoolsctrl-1.12-2.0.2
  [✔️] rftoolspower-1.12-1.2.0
  [✔️] rustic-1.1.7
  [✔️] ShadowMC-1.12-3.8.0
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] Simple-Void-World-1.12-1.2.0.9-universal
  [✔️] SimplyJetpacks2-1.12.2-2.2.20.0
  [✔️] Snad-1.12.1-1.7.09.16a
  [✔️] sonarcore-1.12.2-5.0.19-20
  [✔️] SoulShardsRespawn-1.12.2-1.1.1-13
  [✔️] SplashAnimation-0.2.1
  [✔️] StevesCarts-1.12.2-2.4.32.137
  [✔️] StorageDrawers-1.12.2-5.4.2
  [✔️] StorageDrawersExtras-1.12-3.1.0
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] tesla-core-lib-1.12.2-1.0.18
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] ThermalCultivation-1.12.2-0.3.6.1-universal
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal
  [✔️] ThermalExpansion-1.12.2-5.5.7.1-universal
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal
  [✔️] thutcore-1.12.2-5.21.0
  [✔️] thuttech-1.12.2-6.1.6
  [✔️] TinkerToolLeveling-1.12.2-1.1.0
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] topaddons-1.12.2-1.13.0
  [✔️] torchmaster_1.12.2-1.8.5.0
  [✔️] Translocators-1.12.2-2.5.2.81-universal
  [✔️] twilightforest-1.12.2-3.11.1021-universal
  [✔️] UniDict-1.12.2-3.0.10
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] WanionLib-1.12.2-2.9
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] WirelessCraftingTerminal-1.12.2-3.12.97
  [✔️] woot-1.12.2-1.4.11
  [✔️] xnet-1.12-1.8.2
  [✔️] Xtones-1.2.2
  [✔️] YABBA-1.1.2.54
  [✔️] zerocore-1.12.2-0.1.2.9

Params:
  --username  --version 1.12.2 --gameDir C:/Users/cauo/Documents/MultiMC/instances/FTB Revelation/.minecraft --assetsDir C:/Users/cauo/Documents/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 2216

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader incompatible with java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

I imported ftb revelation from ftb app

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
