### ISSUE TITLE
Make a guide on how to use multiple commands

### ISSUE THREAD

**Issue by Konglomneshued** [MultiMC/Launcher#4958]
### Role

I play modded Minecraft on Linux.

### Suggestion

I want a guide to show me how to add multiple commands in the line.

### Benefit

I looked everywhere online, even joined the socially akward Discord and nobody knows how to do it.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I need to run both of these.  The current syntax I'm using is not accepted and crashes.

![Screenshot from 2022-10-29 20-32-16](https://user-images.githubusercontent.com/94726665/198858604-572caff1-e865-480d-bb2c-4d64599dc9f5.png)

I already checked this Reddit thread:
https://www.reddit.com/r/MultiMC/comments/fn2iv6/how_do_i_launch_the_game_with_custom_environment/
even they didn't know how to do it.

**Comment by Konglomneshued** [comment]
I already checked this Reddit thread: 
https://www.reddit.com/r/MultiMC/comments/fn2iv6/how_do_i_launch_the_game_with_custom_environment/
even they didn't know how to do it.

**Comment by phit** [comment]
wrapper commands are not a shell, make a script that calls multiple commands and call that script
or call sh directly with `sh -c "yourcommand"`

**Comment by Konglomneshued** [comment]
> wrapper commands are not a shell, make a script that calls multiple commands and call that script or call a shell directly with for example `sh -c "yourcommand"`
> 
> that was also the first thing you were told on discord ![image](https://user-images.githubusercontent.com/2097483/198871544-b6164ee9-6a5f-4620-bf7e-54f3e63fc688.png)

That doesn't answer my question.  I don't want to use a script which is why I came here.  Is it or is it not possible to use multiple commands?

**Comment by phit** [comment]
please reread my comment, I specifically called out the alternative
