### ISSUE TITLE
Won't start only when forge is installed

### ISSUE THREAD

**Issue by Findingthings81** [MultiMC/Launcher#4963]
### Operating System

Windows

### Description of bug

[log](https://paste.ee/p/N4aRv) [video showing bug in action](https://youtu.be/dsW0LqCdEig) When I launch with forge, it crashes and gives the error code -1 which I have never seen anyone discuss. When I launch vanilla or fabric, it works perfectly fine. I also have the most recent version of java so it's not that.

### Steps to reproduce

Launching Minecraft with forge, happens at random. Sometimes works sometimes doesn't.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
