### ISSUE TITLE
Tekkit not working

### ISSUE THREAD

**Issue by Slimesoldier** [MultiMC/Launcher#4965]
### Operating System

Windows

### Description of bug

The tekkit modpack won't load up. This is the error code: MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.124.2, 13.35.124.14, 13.35.124.32, 13.35.124.18]

session.minecraft.net resolves to:
    [34.199.236.154, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [108.138.246.63, 108.138.246.90, 108.138.246.85, 108.138.246.57]

api.mojang.com resolves to:
    [13.35.125.26, 13.35.125.104, 13.35.125.60, 13.35.125.80]

Minecraft folder is:
C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/instances/Tekkit/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.4.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.4.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/instances/Tekkit/natives

Libraries:
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/argo/argo/2.25_fixed/argo-2.25_fixed.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/14.0/guava-14.0.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.6.4-9.11.1.965/forge-1.6.4-9.11.1.965-universal.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.6.4/minecraft-1.6.4-client.jar

Native libraries:
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] [1.6.4]ReiMinimap_v3.4_01
  [📁] 1.6 (folder)
  [✔️] appeng-rv14-finale3-mc16x
  [✔️] atomic-science-1.2.0.63-core
  [✔️] autoutils-1.6.4-1.0.1
  [✔️] backpack-1.28.37-1.6.x
  [✔️] bigreactors-0.3.0A
  [✔️] bspkrscorev5.3
  [✔️] BUILDCRAFT-A-1.6.4-4.2.2
  [✔️] buildcraft-Z-additional-buildcraft-objects-1.0.7.560
  [✔️] calclavia core-1.2.0.299-main
  [✔️] carpentersblocks v2.0.8 - MC 1.6+
  [✔️] ChickenChunks 1.3.3.3
  [✔️] codechickencore 0.9.0.7
  [✔️] cofhcore-2.0.0.5
  [✔️] ComputerCraft1.58
  [✔️] dimensional-anchor-57.1.95
  [✔️] dimensionaldoors-2.2.3-336
  [✔️] EnderStorage 1.4.3.5
  [✔️] equivalentexchange3-1.6.4-0.1.140
  [✔️] extracells-1.6.8f
  [✔️] extrautils-1.0.2
  [✔️] galacticraft-1.6.4-2.0.12.1026
  [✔️] galacticraft-planets-1.6.4-2.0.12.1026
  [✔️] GregsLighting-1.9.1-mc1.6.4
  [✔️] immibis-core-57.1.94
  [✔️] immibis-microblocks-57.6.3
  [✔️] InventoryTweaks-MC1.6.2-1.56-b77
  [✔️] ironchest-universal-1.6.4-5.4.1.697
  [✔️] legacyjavafixer-1.0
  [✔️] logisticspipes-mc1.6.4-0.7.4.dev.205
  [✔️] LumySkinPatch
  [✔️] micdoodlecore-1.6.4-2.0.12.1026
  [✔️] minefactoryreloaded-2.7.8-482
  [✔️] modular-force-field-system-3.6.2.56-core
  [✔️] modularpowersuits-1.6.4-0.10.0-91
  [✔️] mystcraft-uni-1.6.4-0.10.12.01
  [✔️] neiplugins-1.1.0.6
  [✔️] netherores-2.2.2-55
  [✔️] notenoughitems 1.6.1.8
  [✔️] numina-1.6.2-0.1.2-55
  [✔️] OPENCCSENSORS-1.6.4.1B
  [✔️] openmodslib-0.4b
  [✔️] openperipheraladdons-0.1.3
  [✔️] openperipheralcore-0.3.3
  [✔️] powercrystalscore-1.1.8-9
  [✔️] powersuitaddons-1.6.4-884
  [✔️] ProjectBench-1.6.2-v1.8.0
  [✔️] projectredbase-1.6.4-4.3.7.32
  [✔️] projectredcompat-1.6.4-4.3.7.32
  [✔️] projectredintegration-1.6.4-4.3.7.32
  [✔️] projectredlighting-1.6.4-4.3.7.32
  [✔️] projectredmechanical-BETA-1.6.4-4.3.7.32
  [✔️] projectredworld-1.6.4-4.3.7.32
  [✔️] qcraft1.1
  [✔️] RedstoneArsenal-1.0.0.0
  [✔️] redstoneinmotion_2.3.0.0_mc1.6
  [📁] rei_minimap (folder)
  [✔️] simplyjetpacks-0.1.4
  [✔️] slick-util
  [✔️] stevescarts2.0.0.b10
  [✔️] thermalexpansion-3.0.0.6
  [✔️] tradebooth.0.6.4.2
  [✔️] TREECAPITATOR.FORGE.1.6.4.R09.UNIVERSAL
  [✔️] universal-electricity-3.1.0.66-core
  [✔️] vending-1.6.4-1.1.1
  [✔️] waila_1.5.2a
  [✔️] WeaponMod
  [✔️] WR-CBE 1.4.0.6

Params:
  --username  --session  --version 1.6.4 --gameDir C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/instances/Tekkit/.minecraft --assetsDir C:/Users/jacki/OneDrive/Desktop/mmc-stable-win32/MultiMC/assets/virtual/legacy --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4608m, -Duser.language=en]

Minecraft process ID: 12856

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:33)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
	... 8 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Run tekkit

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
