### ISSUE TITLE
Weird behavour of minecraft in my new monitor with minecraft.

### ISSUE THREAD

**Issue by MKLEGOPRO** [MultiMC/Launcher#4967]
### Operating System

Windows

### Description of bug

So I just bougth a new monitor and I use multymc to play fabric with some mods like sodium. I recently bought a new 165hz monitor to connect to my laptop. My laptop and the monitor admit hdmi 1.4 and I use the cable that came with the monitor. I set the new monitor as the main monitor in wintows and lauched minecraft to see how it would look. Then, while launching minecraft, It got stuck in the loading animation with the mojang logo. 
I tried several times and it just didnt work, but when I tried to unplug the monitor, it launched minecraft normaly and if I plugged the monitor again it worked normaly at firs and I could get it on full screen. After playing for a bit I realised that my fps was lower than usual and, when I put the game on full screen on my laptop screen, I got 100 more fps than in the external monitor. 
Also when I created a new instance, installed fabric and then put all the mods from the same instance where I got stuck on the loading screen, it just worked normally. I havent tested the performance on that new instance yet but I will keep the post updated.

I would like to know mainly if it could be a problem with the monitor to return it.

### Steps to reproduce

You would need my exact monitor and laptop in order to reproduce so I think there is no easy way to reproduce the error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
sounds like you plugged the monitor into your onboard graphics instead of your dedicated gpu

**Comment by MKLEGOPRO** [comment]
> sounds like you plugged the monitor into your onboard graphics instead of your dedicated gpu

As i said, im using a laptop that only has 1 HDMI port
