### ISSUE TITLE
Service unavailable when logging in to microsoft.

### ISSUE THREAD

**Issue by rs-pro0** [MultiMC/Launcher#4968]
### Operating System

Linux

### Description of bug

When logging in to microsoft account this issue appears.
![image](https://user-images.githubusercontent.com/55341323/200497978-8ed3644d-bd97-4cec-8f55-e963bb424c6a.png)
Version of MultiMC 5:0.6.16 

### Steps to reproduce

1.Remove your account from list.
2.Click add Microsoft account.
3.Log in using website.
4.The error appears

### Suspected cause

Maybe new location or my ISP, because at first I was getting "Too Many Requests" error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by eimaiedo** [comment]
Exact same issue happening to me, location and connection did not change before the error occurred, using Windows too.

**Comment by phit** [comment]
https://twitter.com/MojangStatus/status/1589822938995621888

**Comment by Gwanny** [comment]
A quick fix is this: 
https://github.com/MultiMC/Launcher/issues/4499#issuecomment-1032636241

**Comment by phit** [comment]
> A quick fix is this:
> [#4499 (comment)](https://github.com/MultiMC/Launcher/issues/4499#issuecomment-1032636241)

completely unrelated, the xbox/mojang servers were experiencing an outage, but its mostly fixed now

**Comment by rs-pro0** [comment]
Thank you. Also want to mention that you can got "Too Many Requests"
![image](https://user-images.githubusercontent.com/55341323/200543646-33356654-1600-4c09-81c5-86fbb5e6d325.png)
