### ISSUE TITLE
Can't log in to microsoft account

### ISSUE THREAD

**Issue by iambeingtracked** [MultiMC/Launcher#4969]
### Description of bug

I'm trying to log into my Microsoft account, but I get this error "Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable"

### Steps to reproduce

Install MultiMC5
Try to log into a Microsoft account

### Suspected cause

I first thought that my DNS server is bad at it, but the domain gets resolved properly.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by iambeingtracked** [comment]
Seems like it's a dupe of https://github.com/MultiMC/Launcher/issues/4968

**Comment by iambeingtracked** [comment]
I tried to `curl https://api.minecraftservices.com/launcher/login --output login`
login is a blank file. Seems like MS is messing things up again.

**Comment by Alex33212** [comment]
Happening to me too

**Comment by iambeingtracked** [comment]
This is what they wrote in their discord server: 
"TO ANYONE EXPERIENCING ISSUES WITH MULTIPLAYER AND/OR ACCOUNT USAGE: 
Authentication servers are down. if you really have a burning desire to get in and play your chances are probably best with the Official Launcher, on Offline Mode, until Microsoft officially fixes things."
