### ISSUE TITLE
Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Gateway Timeout

### ISSUE THREAD

**Issue by TJPlaysNow** [MultiMC/Launcher#4970]
### Operating System

Windows

### Description of bug

I was prompeted my acount token had expired so I first tried refreshing which did nothing, so I removed the acount and tried adding it back to get this error.

![Screenshot 2022-11-08 012032](https://user-images.githubusercontent.com/17147463/200500138-f6efac8f-58d6-4b0d-a85f-eb8099ee3d95.png)
`Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Gateway Timeout`

Searching I find things similar but none have the `Gateway Timeout` error. Not sure what is happening, I even tried launching Minecraft through the default launcher and was able to play fine.

### Steps to reproduce

First account expired, then removed it, then tried adding it back.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Deni566** [comment]
i have the same issue today,cannot login in my microsoft account.

**Comment by TJPlaysNow** [comment]
Sometimes the issue changes to:
`Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable`

**Comment by TJPlaysNow** [comment]
I see it is a repeat of https://github.com/MultiMC/Launcher/issues/4968
