### ISSUE TITLE
I need help I keep geting exit codes with one or zero or even negative one and I don't know how to fix I tried all kinds of tutorials can you help me

### ISSUE THREAD

**Issue by SpecterZeroGaming** [MultiMC/Launcher#4972]
I keep getting an **exit code** similar to this it's usually one number either one or zero or even a negative one it's been a pain
in my ass can you please help me with this I have no idea what to do and I have already looked up tutorials
I can't fix it

https://paste.ee/p/YFn9F

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
