### ISSUE TITLE
Potential fix for 1.19 Narrator not working

### ISSUE THREAD

**Issue by TylerWDoesStuff** [MultiMC/Launcher#4975]
### Role

A mod I use uses the Narrator for announcements, and MultiMC's 1.19 implementation doesn't have a working Narrator.

### Suggestion

Add the needed DLLs to the TTS jar automatically, or allow for individual JARs to not be updated when laucnhing online

### Benefit

This reenables Narrator, though there is probably a better way to do this.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Adding the SAPIWrapper x86 and x64 dlls in a win32-x86-64 folder to text2speech-1.13.9.jar (I think) reenables TTS via Narrator. However, this only works currently in offline launching, as online automatically syncs a fresh copy off of Mojang's servers, which removes the "fix" and disables Narrator. Code could also be changed to bring back a similar implementation to 1.18's launcher, or an option could be added that allows specific dependency jars to be excluded from the update cycle, allowing this fix to exist in online play.

(I understand that this is _technically_ a duplicate of #4783, but that thread is locked, and there hasn't been movement on it in months. Also, this is a suggestion, not a bug report, so maybe less priority?)

**Comment by TylerWDoesStuff** [comment]
![Screenshot 2022-11-17 000830](https://user-images.githubusercontent.com/70175654/202393390-0a0e06f8-7008-4420-8f75-fa5d9434e4f7.png)
![Screenshot 2022-11-17 000835](https://user-images.githubusercontent.com/70175654/202393393-c26f4e64-8cbc-44a4-8efa-53f198c40a1a.png)

This works for me in offline mode.
![Screenshot 2022-11-17 002243](https://user-images.githubusercontent.com/70175654/202394064-db6ddcea-f402-4c39-9b91-71b9a7bff12c.png)

**Comment by phit** [comment]
this will be fixed properly eventually
