### ISSUE TITLE
Jre 8 EXCEPTION_ACCESS_VIOLATION bug

### ISSUE THREAD

**Issue by Grainfly520** [MultiMC/Launcher#4977]
### Operating System

Windows

### Description of bug

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd89952d77, pid=2816, tid=0x0000000000002b74
#
# JRE version: Java(TM) SE Runtime Environment (8.0_341-b10) (build 1.8.0_341-b10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.341-b10 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [ig7icd64.dll+0x22d77]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\ertur\OneDrive\Masaüstü\MultiMC\instances\FTB Academy\.minecraft\hs_err_pid2816.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

--I used jre1.8.0_341
--I set "Maximum memory allocation" to 3072mb
--I was trying to run FTB Academy
--The title screen opened but when I tried to create a world the bug happened

### Suspected cause

I don't think the bug has anything to do with the modpack or the memory,but I'm not completely sure.Maybe using another version of jre can help but I didn't test it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
