### ISSUE TITLE
Microsoft account expired, re-added, Microsoft reports success, but MultiMC reports fail because of repeats!

### ISSUE THREAD

**Issue by NULUSIOS** [MultiMC/Launcher#4979]
### Description of bug

Well subject says it all.
Microsoft account expired.
As always, we need to add a new account (no need to delete old as it gets replaced) to MultiMC and enable it.
(which is also a bug as it should just work with "Refresh")

So it gives the link and the code, I enter them, Microsoft reports that it gave access ok and I should close the browser page, but when I go back to MultiMC it reports:

`Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Too Many Requests`

Also this issue made all my MultiMC installs to expire (and all fail the same way...).
So I am basically locked out, when using MultiMC...

### Steps to reproduce

Find a Microsoft account that is expired (maybe it even works if it is not expired, just deleted and re-added).
Try to enable it using the process MultiMC dictates.
Login properly (Microsoft reports ok).
MultiMC fails to enable the account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ekristen** [comment]
This happened to me as well. Unable to login now. This is a pretty nasty bug.

**Comment by phit** [comment]
wait a while and try again, nothing we can do about microsoft rate limiting you

**Comment by NULUSIOS** [comment]
> wait a while and try again, nothing we can do about microsoft rate limiting you

It is NOT Microsoft limiting me.
Microsoft is accepting the unlock of the app and says that I can return to the application.
But the MultiMC itself believes it didn't get unlocked AFTER I return to it.

**Comment by ekristen** [comment]
No multimc is at fault, the account refresh window was up and constantly spamming the Minecraft services api like it was stuck in a loop trying to get authorization.

This is 100% a multimc bug.

**Comment by phit** [comment]
there was an auth outage at a time, so yes it kept trying to login

**Comment by NULUSIOS** [comment]
Well it is still happening...

**Comment by phit** [comment]
yes the issue is still ongoing for a lot of people, nothing we can do about it

**Comment by ekristen** [comment]
I would argue that you could make the launcher not spam when it encounters and error and instead back off or wait for manual input.

**Comment by phit** [comment]
it already does that, hence why you are seeing the `Too Many Requests`, Mojang is reporting that error wrongly for even the first request

theres a new tweet for it up too https://twitter.com/MojangStatus/status/1594094758585987072
