### ISSUE TITLE
Feature: Option for "Add instance" to auto-test title screen survival time.

### ISSUE THREAD

**Issue by mk-pmb** [MultiMC/Launcher#4981]
### Role

I tried to play modded Minecraft.

### Suggestion

When I add an instance, I want an option to automatically launch it online after install, and also a time limit option, and an option to restart it in offline mode.

### Benefit

I can be afk and MultiMC will do the right thing with much less hand-holding.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently, my process is this:
* Add instance
* Wait for stuff to download
* MultiMC is idle while I'm afk. This is a waste of my time.
* Launch online
* Wait for stuff to download and title screen to load
* The title screen is idle while I'm afk. This is a waste of my time because the next two steps won't happen until I'm back:
* Quit title screen and wait for it to quit properly.
* Launch offline, enter my offline player name. As soon as the previous step will have been automated, the name prompt would become the next phase of MultiMC idly waiting for me and thus wasting my time.
* Wait for title screen to load. Not a waste of time because there's nothing more left to do until I return from afk.

An auto-launch checkbox would be enough to eliminate the 1st and 2nd idle phase.

Unfortunately, most of the packs I tried today either crashed before opening their title screen, or survived it only for a few seconds. Some others had unexpected music in their title screen. Both are reasons why I'd like to specify a duration for how long to test the title screen. Let's call it "title screen survival duration" (TSSD).

If the TSSD is reached and the game window is still alive, kill it and interpret it as a success. If any failure occurred before that, give up and display a problem report.

A text field for TSSD can replace the checkbox for online auto-launch: You either give a time in minutes for the regular test, or "0" or "+" to skip the kill. Skipping the kill means the human can play online as soon as they return from afk. The TSSD field should remember the last used value.

However, I want offline. To launch offline, I have to select my offline nickname. Usually we can (soon) skip that annoying prompt because we will have offline accounts. However, here, the first launch had required that the account selection at top right is set to an online account. This means I'll need a 2nd option besides TSSD, the "then switch to offline mode using this name:" text field. When it's not empty, it means I want to play offline after the TSSD test. It should remember the last used value.

**Comment by phit** [comment]
sorry this is all way out of scope and specific to you, you can automate most of this using the launch arguments and some external script if you so desire

**Comment by mk-pmb** [comment]
>  you can automate most of this using the launch arguments

Thanks for the reminder!

The first step will be adding the new instance. I guess I should use `--import`? That wants a ZIP file URL. So assume I'm in the "Add instance" GUI and have selected the pack I want to try, how do I get that ZIP URL?

For example, with ATL RLCraft, I the link below the list only gives https://www.technicpack.net/modpack/shivaxi-rlcraft.1530385 which is the description page, not a ZIP.
The only bottom buttons are "Help", "Cancel" and "OK", all something I don't want.
I tried to find more options in a context menu, but right-clicking the RLCraft list entry had no effect.
