### ISSUE TITLE
Login pop-up when account is expired

### ISSUE THREAD

**Issue by Eiion** [MultiMC/Launcher#4982]
### Role

Starting a game of minecraft

### Suggestion

Automatically give me a log in windows when the account is "expired" (i.e. not logged in for a long time)

### Benefit

No need to search around what and how it's done if doing it is obligatory.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Due to months of hospital stays I wasn't able to play. Wanting to start an instance with MultiMC today I'm getting a pop up saying "The account has expired and needs to be logged into manually again." and an "OK" button.
You'd expect to get a log in pup op after clicking "OK" - but nothing.
It would absolutely make sense to have that if an account log in has expired so a user can comfortably log in again.

EDIT: Seriously, how to I log in again manually - even the account manager doesn't have an option to log in again. Deleting and re-creating the account shouldn't be the way to handle things.

**Comment by bobwarpath123** [comment]
In the top right of the Multi MC window you can click the drop down arrow for profiles, and then click manage accounts, and a new window will pop up. Then you can add a mojang or microsoft account. However for a good majority of the morning, I've been  getting errors when trying to start an instance, and when I would restart the program, it would just say account expired again. And when it did work, it would just keep erroring out saying user authentication failed. Hope this gets resolved!

**Comment by Eiion** [comment]
> In the top right of the Multi MC window you can click the drop down arrow for profiles, and then click manage accounts, and a new window will pop up. Then you can add a mojang or microsoft account. However for a good majority of the morning, I've been getting errors when trying to start an instance, and when I would restart the program, it would just say account expired again. And when it did work, it would just keep erroring out saying user authentication failed. Hope this gets resolved!

This is unrelated to the issue posted. If you read that again you'll see that this is about an already added account - not a fresh install that was never used with an account before.

**Comment by Eiion** [comment]
@phit you've closed this as duplicate but missed to link the issue this one supposedly is a duplicate of.

**Comment by phit** [comment]
Sorry, duplicate of https://github.com/MultiMC/Launcher/issues/4978
