### ISSUE TITLE
Looking For A Permament Account Log-On Solution

### ISSUE THREAD

**Issue by ProfessionaFiddler** [MultiMC/Launcher#4983]
### Role

Sinlgeplayer aka Offline

### Suggestion

Add Perma-Log-on

### Benefit

Convenience

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I need to find a way to freeze the whole account shenanigans. I am tired, and frankly mildly disturbed by how I am made to keep my account up-to-date and refreshed. Needless to say how easier it was back in the days. I bought a copy, and I *should* be able to play the game without internet for years if I wanted to.
It is really inconvenient being obligated to relog via multiple microsoft links JUST to boot up single player and test some mods. Core manipulative solutions are welcome. Really anything, just to make microsoft know its place.

**Comment by phit** [comment]
and you opened this issue here why? MultiMC will not provide any other login than the official one

**Comment by ProfessionaFiddler** [comment]
ask question - close issue
thx, really helpful
