### ISSUE TITLE
Repeated attempting to log me in locks out my microsoft account and prevents me from playing or logging in.

### ISSUE THREAD

**Issue by peppermilldetective** [MultiMC/Launcher#4984]
### Operating System

Windows

### Description of bug

MultiMC, after about a day or two of not playing, will attempt to log in my microsoft account, fail, and repeatedly attempt to log me in. Eventually, this loop fails and will lock out my account. Attempting to refresh my account requires me to delete my account and then log in again. Attempting to do so immediately fails with "too many server requests". Requiring me to wait some time before re-attempting to log in.

### Steps to reproduce

1. After some time not playing, (for me was about a day or two) attempt to launch an online minecraft instance with a microsoft account.
2. Notice the login loop attempts.
3. Attempt to re-activate the account. Have to delete the account and re-add.
4. Verify that the account adding fails with "too many requests".

### Suspected cause

I imagine the microsoft account issue is something with my account, but I'm not sure what. The main issue is the account loop which is locking me out of my account as a whole. Some auto-login loop is happening to cause a fail to attempt to retry until it fills the request cap, and at that point it's locking me out of being able to contact the microsoft servers.

I did attempt to see if this issue was a duplicate, but I couldn't find anything with some searching. If this is a duplicate, I apologize.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the too many requests is a bug on Mojangs end right now, you will hit this on literally the first login attempt in some cases, nothing we can do about until Mojang fixes it
see also https://github.com/MultiMC/Launcher/issues/4979
