### ISSUE TITLE
MultiMC fails to launch Minecraft on arm64 platform

### ISSUE THREAD

**Issue by jaknz** [MultiMC/Launcher#4986]
### Operating System

macOS

### Description of bug

MultiMC incorrectly identifies 64-bit ARM builds of Java as 32-bit, and fails to launch Minecraft. This was heavily investigated in an issue that was wrongly closed. Note of the two "related" issues that were referenced in the close, one has been completely deleted and one has been closed due to an issue with the Raspberry Pi operating system.
https://github.com/MultiMC/Launcher/issues/3933

### Steps to reproduce

Use a 64-bit ARM processor, like Apple M series or Ryzen ARM. Install native Java build. Try to launch MultiMC instance. Fail.

### Suspected cause

Why not integrate the fix that someone else has already done all the work for?
https://github.com/r58Playz/m1-multimc-hack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
There's nothing to investigate, this has been a known issue way before the M1 macs came out, hence why all these ARM issues are marked as dupes of the "Raspberry Pi operating system" issue, alternatively known as the most widespread ARM platform.

For the longest time Minecraft did not provide official ARM binaries and still doesn't in a lot of cases, adding some untrusted 3rd party binaries wasn't and never will be an option.

As for offficial M1 Mac support, there's a lot to be done for that to happen in both meta and the launcher itself, which simply hasn't so far. Until that our official recommendation will be, use x86 ARM builds on M1 Macs, Rosetta works good enough.

**Comment by Cat7373** [comment]
Working fix (tested): [Link Removed]

**Comment by TacoGS** [comment]
This should go without saying. Do not link in our issues to a page that tells them to not use MultiMC.
