### ISSUE TITLE
GLFW error 65543: GLX: Failed to create context: BadValue (Integer parameter out of range for operation). 

### ISSUE THREAD

**Issue by TimeViper** [MultiMC/Launcher#4987]
Hello, 
I'm at my wits end trying to figure this out... 
Currently running Fabric, OptiFabric, and Optifine. 

Get this error when loading off the discreet GPU on PoP_OS_22_04.LTS

If I do an entire system reset I can get it to launch ONE time. 
If I exit the game for a break, or if the game crashes, or if something closes the window, then I have to do a full system reset to re open the game. 

I've seen some items on running this with a new environmental variable for mesa version, but I can't find the executable for the launcher to point that at. 

Any thoughts or help would be apprecitated.

MultiMC version: 0.6.16-3430

Launched instance in online mode

authserver.mojang.com resolves to:
    [99.84.164.45, 99.84.164.62, 99.84.164.46, 99.84.164.48]

session.minecraft.net resolves to:
    [35.153.153.200, 100.24.172.95, 34.197.32.8]

textures.minecraft.net resolves to:
    [2620:1ec:46::51, 2620:1ec:bdf::51, 13.107.213.51, 13.107.246.51]

api.mojang.com resolves to:
    [99.84.160.117, 99.84.160.9, 99.84.160.28, 99.84.160.2]

Minecraft folder is:
/home/kyle/.local/share/multimc/instances/1.19.2/.minecraft

Java path is:
/usr/lib/jvm/jdk-19/bin/java

Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.

12th Gen Intel(R) Core(TM) i7-12700H
Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c)

DeviceName: VGA compatible controller

Subsystem: CLEVO/KAPOK Computer Device 867c

NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] (rev a1)

DeviceName: VGA compatible controller

Subsystem: CLEVO/KAPOK Computer GA106M [GeForce RTX 3060 Mobile / Max-Q]

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/kyle/.local/share/multimc/instances/1.19.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/kyle/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/kyle/.local/share/multimc/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/kyle/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/kyle/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  /home/kyle/.local/share/multimc/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/kyle/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /home/kyle/.local/share/multimc/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-x86_64.jar
  /home/kyle/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/kyle/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/kyle/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/kyle/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /home/kyle/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/kyle/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/kyle/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  /home/kyle/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/kyle/.local/share/multimc/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  /home/kyle/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  /home/kyle/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  /home/kyle/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  /home/kyle/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  /home/kyle/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.14.9/fabric-loader-0.14.9.jar
  /home/kyle/.local/share/multimc/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-linux.jar
  /home/kyle/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-linux.jar

Mods:
  [❌] fabric-api-0.62.0+1.19.2.jar (disabled)
  [❌] optifabric-1.13.16.jar (disabled)
  [✔️] OptiFine_1.19.2_HD_U_H9

Params:
  --username  --version 1.19.2 --gameDir /home/kyle/.local/share/multimc/instances/1.19.2/.minecraft --assetsDir /home/kyle/.local/share/multimc/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Java Arguments:
[-Xms512m, -Xmx16384m, -Duser.language=en]

Minecraft process ID: 24418

Using onesix launcher.

[10:11:20] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[10:11:20] [main/INFO]: Loading 3 mods:
	- fabricloader 0.14.9
	- java 19
	- minecraft 1.19.2
[10:11:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/kyle/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:11:20] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[10:11:21] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[10:11:22] [main/INFO]: Building optimized datafixer
[10:11:24] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:11:25] [Render thread/INFO]: Setting user: SKOJPROJ
[10:11:25] [Render thread/ERROR]: Error parsing option value 0 for option Max Framerate: Value 0 outside of range [10:260]
[10:11:25] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[10:11:28] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65543: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
	at net.minecraft.class_1041.method_4501(class_1041.java:223) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar:?]
	at net.minecraft.class_1041.<init>(class_1041.java:93) ~[client-intermediary.jar:?]
	at net.minecraft.class_3682.method_16038(class_3682.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:484) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 23 Nov 2022 10:12:45 -0600

**Comment by cylian914** [comment]
i think the issue is here "[10:11:25] [Render thread/ERROR]: Error parsing option value 0 for option Max Framerate: Value 0 outside of range "
try to change max framrate in the mincraft config file

**Comment by TimeViper** [comment]
Forgive my ignorance, but the max framerate in the MultiMC Config? Or in the Minecraft config file? 

I have a bunch of different configs and am not sure where to make the change.... 

I appreciate the help. Sorry I'm a noob at all this

**Comment by phit** [comment]
`options.txt` in the minecraft folder of the instance
does your game work without any mods installed?

**Comment by cylian914** [comment]
I also recommend you to not use optifine, look at the fabulously optimized modpack: https://www.curseforge.com/minecraft/modpacks/fabulously-optimized

**Comment by TimeViper** [comment]
Well... 
Seems to be some goofy dependency thing in Optifine. 
Vanilla seems to work well, Fabulously Optimized seems to work just fine. 
But optifine seems totally bugged and works occasionally on my setup. 

Well.... good to know it's not a MultiMC Issue. 

Thanks for all your help!
