### ISSUE TITLE
Forge Not working (exit code -1)

### ISSUE THREAD

**Issue by codebugissue** [MultiMC/Launcher#4989]
### Description of bug

Forge Should have launched with intended mod (undisclosed mod). Instead forge exited with code -1 (0xffffffffffffffff)

Upload link:[Log (exit code -1).txt] (https://github.com/MultiMC/Launcher/files/10096813/Log.exit.code.-1.txt)

### Steps to reproduce

1.Create a new instance.
2.Click edit instance.
3.Click install forge and add recommended version.
4.Launch created instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by codebugissue** [comment]
Quick information addon I use windows 10.

**Comment by Primitive-Human** [comment]
Are you sure this is caused by MultiMC itself, and not your rather sketchy mod? 

Try your own listed reproduction steps first, so without your 'mod', so we can exclude as causes as possible. But even then I doubt it's the launcher or Forge itself causing the issue. 

EDIT: You're using the wrong JAVA for 1.12.2. 

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by codebugissue** [comment]
Primitive-Human if you read the steps to produce you would know I didn't add any mods to the instance also forge can launch fine on other launchers and clients such as feather client and t-launcher. This confirms the problem is on multimc.

**Comment by codebugissue** [comment]
> Are you sure this is caused by MultiMC itself, and not your rather sketchy mod?
> 
> Try your own listed reproduction steps first, so without your 'mod', so we can exclude as causes as possible. But even then I doubt it's the launcher or Forge itself causing the issue.
> 
> EDIT: You're using the wrong JAVA for 1.12.2.
> 
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

Multimc still doesn't work launch when switching from C:/Program Files/Java/jdk-17.0.5/bin/javaw.exe to javaw this may be because I don't have the right java but I can't find "java 8" on oracle.com or java.com could you send me a download link?

**Comment by phit** [comment]
theres links in the wiki, scroll down
