### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by qweasdzxc123a** [MultiMC/Launcher#4990]
### Operating System

Windows

### Description of bug

crash bild minecraft  

### Steps to reproduce

--- BEGIN ERROR REPORT 1857e342 --------
Full report at:
C:\Users\kolay\Desktop\MultiMC\instances\7 сезон (Мигрирован)1\minecraft\crash-reports\crash-2022-11-27_00.35.32-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 11/27/22 12:35 AM

-- System Details --
Details:
	Minecraft Version: 1.5.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 331666144 bytes (316 MB) / 747634688 bytes (713 MB) up to 2130706432 bytes (2032 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx2286m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 Optifine OptiFine_1.5.2_HD_D5 70 mods loaded, 70 mods active
	mcp{7.51} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{5.2.23.737} [Forge Mod Loader] (coremods) Unloaded->Constructed
	Forge{7.8.1.737} [Minecraft Forge] (coremods) Unloaded->Constructed
	CodeChickenCore{0.8.7} [CodeChicken Core] (coremods) Unloaded->Constructed
	CoFHFramework{1.5.2.4} [CoFH Framework] (coremods) Unloaded->Constructed
	ImmibisMicroblocks{55.0.1} [Immibis's Microblocks] (coremods) Unloaded->Constructed
	NotEnoughItems{1.5.2.28} [Not Enough Items] (coremods) Unloaded->Constructed
	mod_bspkrsCore{v2.07(1.5.2)} [bspkrsCore] ([1.5.2]bspkrsCorev2.07.zip) Unloaded->Constructed
	TreeCapitator{Forge 1.5.2.r01} [TreeCapitator] ([1.5.2]TreeCapitator.Forge.1.5.2.r01.Uni.CoreMod.jar) Unloaded->Constructed
	CoFHCore{1.5.2.4} [CoFHCore] (CoFHCore-1.5.2.4.jar) Unloaded->Constructed
	CoFHWorld{1.5.2.4} [CoFHWorld] (CoFHCore-1.5.2.4.jar) Unloaded->Constructed
	ImmibisMicroblocksInstallCheck{55.0.1} [Immibis's Microblocks (Check for incorrect installation)] (immibis-microblocks-55.0.1.jar) Unloaded->Constructed
	DamageIndicatorsMod{2.7.0.1} [Damage Indicators] (1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed
	AsgardShield_Core{2.0.4} [AsgardShield] (1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed
	ASAddon_Hallowed{2.0.0} [AS Addon- Hallowed] (1.5.2ASAddonHallowed_v2.0.0Forge.zip) Unloaded->Constructed
	HarkenScythe_Core{2.1.6} [HarkenScythe] (1.5.2HarkenScythe_v2.1.6Forge.zip) Unloaded->Constructed
	ASAddon_HarkenScythe{2.0.0} [AS Addon- HarkenScythe] (1.5.2ASAddonHarkenScythe_v2.0.0Forge.zip) Unloaded->Constructed
	ASAddon_NetherEnder{2.0.0} [AS Addon- Nether-Ender] (1.5.2ASAddonNetherEnder_v2.0.0Forge.zip) Unloaded->Constructed
	ASAddon_ColorAPI{1.0.0} [ASAddon_ColorAPI] (1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed
	ChickenShed{1.1.2} [Chicken Shed] ([1.5+] ChickenShed (v1.1.2).zip) Unloaded->Constructed
	mod_MouseTweaks{2.0 (for Minecraft 1.5.2)} [Mouse Tweaks] ([1.5.2] Mouse Tweaks 2.0.zip) Unloaded->Constructed
	mod_ArmorStatusHUD{v1.7(1.5.2)} [ArmorStatusHUD] ([1.5.2]ArmorStatusHUDv1.7.zip) Unloaded->Constructed
	Thaumcraft{3.0.5h1} [Thaumcraft] (Thaumcraft3.0.5h.zip) Unloaded->Constructed
	BetterStorage{0.6.2.23} [BetterStorage] ([1.5.2]BetterStorage_0.6.2.23.zip) Unloaded->Constructed
	mod_ArmorBarMod{0.7.1} [Armor Bar Mod] (ArmorBarv0.7.1.zip) Unloaded->Constructed
	Artifice{1.5.2R1.1.1} [Artifice] (Artifice-1.1.1-131.jar) Unloaded->Constructed
	ArtificeCompat|Chisel{1.5.2R1.1.1} [Artifice Compat: Chisel] (Artifice-1.1.1-131.jar) Unloaded->Constructed
	ArtificeCompat|EE3{1.5.2R1.1.1} [Artifice Compat: EE3] (Artifice-1.1.1-131.jar) Unloaded->Constructed
	ArtificeCompat|MFR{1.5.2R1.1.1} [Artifice Compat: MFR] (Artifice-1.1.1-131.jar) Unloaded->Constructed
	ArtificeCompat|Vanilla{1.5.2R1.1.1} [Artifice Compat: Vanilla] (Artifice-1.1.1-131.jar) Unloaded->Constructed
	Backpack{1.9.11} [Backpack] (backpack-1.9.11-1.5.2.zip) Unloaded->Constructed
	mod_BackTools{1.5.2v1} [mod_BackTools] (BackTools1.5.2v1.zip) Unloaded->Constructed
	BattleTowers{1.3.4} [Battle Towers] (BattleTowers_1.5.2.zip) Unloaded->Constructed
	BetterDungeons{1.8} [Better dungeons] (BetterDungeons.zip) Unloaded->Constructed
	BiblioCraft{1.3.1} [BiblioCraft] (BiblioCraft[v1.3.1].zip) Unloaded->Constructed
	mod_BuffBarMod{0.7.1} [Buff Bar Mod] (BuffBarv0.7.1.zip) Unloaded->Constructed
	DimDoors{1.5.2R1.4.0RC1} [Dimensional Doors] (DimensionalDoors-1.5.2R1.4.0RC1-149.zip) Unloaded->Constructed
	eplus{1.15} [Enchanting Plus] (EnchantingPlus-1.15.jar) Unloaded->Constructed
	ExtrabiomesXL{3.13.4} [ExtrabiomesXL] (ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed
	hexxitgear{1.5.2R1.0} [Hexxit Gear] (HexxitGear-1.0-23.jar) Unloaded->Constructed
	ImmibisCore{55.1.2} [Immibis Core] (immibis-core-55.1.2.jar) Unloaded->Constructed
	InfernalMobs{1.3.1} [Infernal Mobs] (InfernalMobs_1.5.2.zip) Unloaded->Constructed
	inventorytweaks{1.54b} [Inventory Tweaks] (InventoryTweaks-1.54b.jar) Unloaded->Constructed
	IronChest{5.2.4.391} [Iron Chest] (ironchest-universal-1.5.1-5.2.4.391.zip) Unloaded->Constructed
	Meteors{2.10.2} [Falling Meteors] (Meteors Mod V2.10.2.zip) Unloaded->Constructed
	More Bows{1.5_v1} [More Bows mod] (More bows 1.5.2_2 Forge.jar) Unloaded->Constructed
	MoreFurnaces{1.3.4} [More Furnaces] (moreFurnaces_1.3.4_Universal.zip) Unloaded->Constructed
	Natura{1.5.1_2.1} [Natura] (Natura_2.1.jar) Unloaded->Constructed
	Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR] (Natura_2.1.jar) Unloaded->Constructed
	NEIPlugins{1.0.9.3} [NEI Plugins] (NEIPlugins-1.0.9.3.jar) Unloaded->Constructed
	LegendGear{1.5.2} [LegendGear] (NMcCoy-LegendGear-1.5.2.zip) Unloaded->Constructed
	ObsidiPlates{1.5.0} [Obsidian Pressure Plates] (obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed
	OffLawn{1.0} [offLawn] (OffLawn-1.5.1.zip) Unloaded->Constructed
	ProjectZulu|Core{1.0.3.8} [Project Zulu Core] (ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed
	ProjectZulu|Blocks{1.0.3.8} [Project Zulu Block and Items] (ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed
	ProjectZulu|Dungeon{1.0.3.8} [Project Zulu Mobs] (ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed
	ProjectZulu|Mobs{1.0.3.8} [Project Zulu Mobs] (ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed
	ProjectZulu|World{1.0.3.8} [Project Zulu World] (ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed
	xreliquary{1.5.2} [Xeno's Reliquary] (Reliquary1.0.6d.zip) Unloaded->Constructed
	rftl{1.0} [RottenFleshToLeather] (RottenFleshToLeather-1.5.1.zip) Unloaded->Constructed
	AS_Ruins{10.3} [Ruins Spawning System] (Ruins_1.5.2.zip) Unloaded->Constructed
	mod_SmartMoving{Not available} [mod_SmartMoving] (Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Errored
	mod_SmartRender{Not available} [mod_SmartRender] (Smart Moving Universal for ModLoader or Minecraft Forge or MCPC+.zip) Unloaded->Errored
	SoulShards{1.0.16} [Soul Shards] (SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed
	TConstruct{1.5.1_1.3.4.3} [Tinkers' Construct] (TConstruct_1.3.4.3.jar) Unloaded->Constructed
	TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR] (TConstruct_1.3.4.3.jar) Unloaded->Constructed
	TwilightForest{1.18.1} [The Twilight Forest] (twilightforest-1.18.1.zip) Unloaded->Constructed
	WildCaves3{0.4.2} [Wild Caves 3] (WildCaves3-0.4.2.zip) Unloaded->Constructed
	mod_ZanMinimap{0.9.4} [mod_ZanMinimap] (ZansMinimap1.5.2.zip) Unloaded->Constructed
	chococraft{2.8.6} [Torojima's ChocoCraft] (zzzChococraft_2.8.6.zip) Unloaded->Constructed
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 550 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Texture Pack: faithful64pack-v1.2.0b.zip
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

java.lang.RuntimeException: 

	========================================
	Client Player API 1.1 can not be created!
	----------------------------------------
	Mandatory member method "PlayerBase getPlayerBase(java.lang.String)" not found in class "net.minecraft.client.entity.EntityPlayerSP".
	There are two scenarios this can happen:
	* The file "net\minecraft\client\entity\EntityPlayerSP.class" of Player API universal has been replaced by a file of the same name but a different source.
	  Install Player API universal again to fix this specific problem.
	* Player API universal has been installed in the "mods" folder.
	  Deinstall Player API universal and install it again following the installation instructions in the readme file.
	========================================

	at PlayerAPI.register(PlayerAPI.java:84)
	at PlayerAPI.register(PlayerAPI.java:35)
	at PlayerAPI.register(PlayerAPI.java:28)
	at net.smart.render.statistics.playerapi.SmartStatistics.register(SmartStatistics.java:16)
	at net.smart.render.mod.Client.<init>(Client.java:35)
	at net.smart.render.mod.Client.create(Client.java:26)
	at mod_SmartRender.<init>(mod_SmartRender.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.common.modloader.ModLoaderModContainer.constructMod(ModLoaderModContainer.java:495)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:504)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:163)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:411)
	at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
	at net.minecraft.client.Minecraft.run(Minecraft.java:733)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodException: net.minecraft.client.entity.EntityPlayerSP.getPlayerBase(java.lang.String)
	at java.lang.Class.getMethod(Unknown Source)
	at PlayerAPI.register(PlayerAPI.java:54)
	... 39 more
--- END ERROR REPORT 243d1b9a ----------

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
