### ISSUE TITLE
bug when I launch beta version of minecraft (1.7.3)

### ISSUE THREAD

**Issue by athnade** [MultiMC/Launcher#4993]
### Operating System

Windows

### Description of bug

(i'll try my best to explain, i'm french)(and I'm not really good at code too)

when I launch minecraft, the game just stop on the mojang logo. It's only on beta version 1.7.3 or other beta. 
the code that shows on my console is this:

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.161.88.56, 18.161.88.48, 18.161.88.43, 18.161.88.50]

session.minecraft.net resolves to:
    [35.153.153.200, 100.24.172.95, 34.197.32.8]

textures.minecraft.net resolves to:
    [2620:1ec:46::42, 2620:1ec:bdf::42, 13.107.213.42, 13.107.246.42]

api.mojang.com resolves to:
    [18.161.111.121, 18.161.111.10, 18.161.111.117, 18.161.111.66]

Minecraft folder is:
C:/Users/Diego/Desktop/MultiMC/instances/b1.7.3/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_351/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_351, using 64-bit architecture, from Oracle Corporation.

Main Class:
  

Native path:
  C:/Users/Diego/Desktop/MultiMC/instances/b1.7.3/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  C:/Users/Diego/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Diego/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Diego/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Diego/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Diego/Desktop/MultiMC/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  C:/Users/Diego/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Diego/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 4300

Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: dieguidieg, token:<ACCESS TOKEN>:<PROFILE ID>
Nov 28, 2022 1:52:55 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Nov 28, 2022 1:52:55 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Nov 28, 2022 1:52:55 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin 

----------------------------------------------------------------------------------------------------------------------------------------------

I hope you can help me !

### Steps to reproduce

launch a beta version of minecraft.

### Suspected cause

I thought it was because of my java version, but I tried to change it and nothing changed.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Try switched your Java versions / get a new version of java

**Comment by phit** [comment]
does the game work with the official launcher?

**Comment by athnade** [comment]
I don't have any beta version on the official launcher, and yes i changed my java version

**Comment by phit** [comment]
then get a beta version on the official launcher and try it, usually this is an OS issue

**Comment by athnade** [comment]
Ok i see thanks you

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
