### ISSUE TITLE
1.16.5 Pixelmon crashing on opening HUD

### ISSUE THREAD

**Issue by KidoHyde** [MultiMC/Launcher#4994]
### Operating System

Windows

### Description of bug

Heya, so I know by the title this issue sounds more like a pixelmon issue, however I ultimately don't know if the mod, or the manager causes this issue.

On multiMC latest version trying to play pixelmon (either using the packed in modpack or manual setup (latest 1.16.5 forge and newest pixelmon version)), lets me into a world but crashes upon trying to get into a battle. My reason for thinking this is a MultiMC is because in a regular Minecraft instance Pixelmon with the above setup works just fine. my crash report is linked below, seems to be some error with getting the HUD from the jar itself?
[Crash Report](https://drive.google.com/file/d/1mZp5mxv5s648BqXXrC07lN_soqB9NdUr/view?usp=sharing)

I've also tried various forge versions and different pixelmon and they all yeild the same result, yet all work on base MC Launcher, my friend uses the Prism launcher and says that it also works there for him.

### Steps to reproduce

- Create a new Instance,
- Either manually install Pixelmon and the latest 1.16.5 forge, OR use the ATP Pixelmon modpack (has more mods but suffers the same main issue)
- Create new world
- Choose any starter
- get into a battle
- game Crashes

### Suspected cause

MultiMC's Asset folder reads from a different location, is it possible that the Asset in the pixelmon jar isn't read properly?
Seems largely like it's just huds having this issue, 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by KidoHyde** [comment]
My main reason for reporting this here is this bug only occurs with MultiMC, and not any other minecraft instance, so I'm uncertain what's different about MultiMC's launcher that causes this issue
