### ISSUE TITLE
Unable to import FTB Modpacks from FTB App 

### ISSUE THREAD

**Issue by MC-Boy1122** [MultiMC/Launcher#4995]
### Operating System

Windows

### Description of bug

I want to import a modpack from ftb app, but it shows nothing

### Steps to reproduce

press new instance, then ftb app import
there where it should show my modpacks, it show like i downloaded nothing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide your launcher log and what packs you installed in the ftb app

**Comment by Sel1432** [comment]
Hi, I'm having a similar issue where I have an up-to-date pack I would like to import from the FTB app (Vault Hunters 3rd Edition), but it's showing nothing available in the "Add Instance > FTB App Import" section! I would love to provide the launcher log to help resolve this, where do I find that?

**Comment by phit** [comment]
MultiMC-0.log in the launcher folder

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
