### ISSUE TITLE
cannot run modpack from modrinth due to inability to download forge.

### ISSUE THREAD

**Issue by QTpyeRose** [MultiMC/Launcher#4996]
### Operating System

Windows

### Description of bug

cannot run and install forge version 43.1.58+

```
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/43.1.58.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/43.1.58.json
```

### Steps to reproduce

- attempt to install 'technical electric' version 2.7.0 from the inbuilt modrinth section
- upon attempting to launch forge cannot be installed.

### Suspected cause

missing file on multimc servers: 43.1.58.json

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Should be fixed now!
