### ISSUE TITLE
Forge is messed up

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#4997]
### Operating System

Linux

### Description of bug

Failed to load native library libfliteWrapper (aarch64/libfliteWrapper.so) not found in resource path.

I may have messed up typing the bug, this wasn't copied and pasted, I rewrote it from my memory.

INFO:

- I have already done `sudo apt-get install flite`
- I've tried reinstalling Forge
- It worked perfectly fine before
- I haven't tampered with any multiMC files.

### Steps to reproduce

Launch Minecraft forge 1.12.2 with any mod on Linux aarch64 and it bugs.

### Suspected cause

Im not sure, maybe the JRE.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
MultiMC does not support ARM

**Comment by ghost** [comment]
clearly it does, it has worked fine for awhile.

**Comment by phit** [comment]
nope never has, and afaik neither does the game for Linux https://github.com/MultiMC/Launcher/issues/2133

**Comment by ghost** [comment]
Man, im not asking you if it works. I know it does, ive been using it for 2 years perfectly fine. Im asking how to resolve this.

**Comment by Zetabite** [comment]
I mean, you can ask, but you wont get help from us. We never supported ARM and still not do. So not our issue to fix, regardless of what the Launcher calls itself. In a matter of fact, your launcher might even infringe on the MultiMC trademark. So there is that.

**Comment by ghost** [comment]
oh no!1!1!1!!! what will i do!1!1!!!

**Comment by Zetabite** [comment]
I mean, its quite obvious, you go somewhere else with your problem. Not too much to ask for, now is it?

**Comment by ghost** [comment]
stinker
