### ISSUE TITLE
Microsoft account doesn't work

### ISSUE THREAD

**Issue by Troughy** [MultiMC/Launcher#4999]
### Operating System

Linux

### Description of bug

All of a sudden online mode stopped working. First I tried starting Minecraft, but it kept asking me for offline username. I checked the accounts, I'm logged in with my Microsoft account, but it just says offline. When I click on refresh, it still shows the account as offline. Clicking on "Add Microsoft" I just see a progress bar that's stuck at about 25% and it just says 'Working...'
I'm not sure if you're having some server issues, because at the bottom it also just says "Loading news..." and when I click on "Update" nothing happens.

### Steps to reproduce

* Be logged in with a Microsoft account (or try logging in, but you can't)
* Try starting an instance in online mode

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide your MultiMC log file via https://gist.github.com/ or similar, it can be found in the main folder

**Comment by Troughy** [comment]
So I also wrote in the #help channel in the Discord server and apparently the cause of the issue is that I replaced openssl with libressl.
You can find the log here https://discord.com/channels/132965178051526656/134843027553255425/1048664103767507045

**Comment by arthomnix** [comment]
You'd need to use a qt5 build that was compiled against libressl, if your distro doesn't provide this you should use openssl or switch to a distro that supports libressl properly.
