### ISSUE TITLE
https://maven.minecraftforge.net no longer open / forge json is wrong

### ISSUE THREAD

**Issue by mitcht** [MultiMC/Launcher#5003]
### Description of bug

When attempting to install forge, unable to get files because the urls are behind a password at 
https://maven.minecraftforge.net

### Steps to reproduce

Choose MC 1.16.5 and install forge in MultiMC

### Suspected cause

forge repository changes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please provide a log

**Comment by mitcht** [comment]
FWIW, I have used a version of Java that matches my server.  The same issue happens with the latest version of Java.

Windows8.1, all updates (older computer doesn't support newer video drivers).  Installed the x64 Visual C++ from here.

https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

`MultiMC version: 0.6.16-3431
Launched instance in online mode
authserver.mojang.com resolves to:    [65.8.46.62, 65.8.46.48, 65.8.46.49, 65.8.46.45]
session.minecraft.net resolves to:    [35.153.153.200, 100.24.172.95, 34.197.32.8]
textures.minecraft.net resolves to:    [13.107.246.51, 13.107.213.51]
api.mojang.com resolves to:    [13.226.22.37, 13.226.22.16, 13.226.22.46, 13.226.22.116]
Minecraft folder is: C:/MultiMC/instances/1.16.5/.minecraft
Java path is: C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe
Checking Java version... Java is version 1.8.0_241, using 64-bit architecture, from Oracle Corporation.

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.16.5' failed to process:
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.28/forge-1.16.5-36.2.28-installer.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.28/forge-1.16.5-36.2.28-launcher.jar
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.2.28/forge-1.16.5-36.2.28-universal.jar
https://maven.minecraftforge.net/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
https://maven.minecraftforge.net/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
https://maven.minecraftforge.net/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
https://maven.minecraftforge.net/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
https://maven.minecraftforge.net/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
https://maven.minecraftforge.net/com/google/guava/guava/20.0/guava-20.0.jar
https://maven.minecraftforge.net/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar
https://maven.minecraftforge.net/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
https://maven.minecraftforge.net/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
https://maven.minecraftforge.net/com/opencsv/opencsv/4.4/opencsv-4.4.jar
https://maven.minecraftforge.net/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
https://maven.minecraftforge.net/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
https://maven.minecraftforge.net/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
https://maven.minecraftforge.net/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar
`

... So on and so forth

**Comment by phit** [comment]
please check your MultiMC-0.log from the main launcher folder/ upload it here

**Comment by mitcht** [comment]
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/10169869/MultiMC-0.log)


Looks like a certificate issue with forge servers?. I am 99% sure my time on my machine is correct, having set it via the time update service.  Sometimes time differences cause cert issues.

**Comment by phit** [comment]
open https://maven.minecraftforge.net in internet explorer or edge, then restart multimc and try again

**Comment by mitcht** [comment]
@phit the root certificate stores on Windows8 were out of date.  I used the following website to assist http://www.chawn.com/RootCerts.htm

but here are the commands to fix, for anyone who needs them
```

# Create C:\temp\certs
md C:\temp\certs

# download latest SST from Microsoft
CertUtil –generateSSTFromWU C:\temp\certs\RootStore.sst

# Import RootStore.sst to Trusted Root CA Store
$file=Get-ChildItem -Path C:\temp\certs\Rootstore.sst
$file | Import-Certificate -CertStoreLocation Cert:\LocalMachine\Root\

```

**Comment by phit** [comment]
you should not do that, ever, since Windows 7 that's automatically done by Windows...

**Comment by mitcht** [comment]
I'm not sure.  Maybe its because I'm using a VL installation from my msdn subscription.  Thoughts?

Its a fresh installation of Windows8.1 VL

**Comment by phit** [comment]
no has nothing to do with that, if you would have opened the page in internet explorer or edge, windows will automatically download the needed certificates

**Comment by mitcht** [comment]
Forgot to mention.  That didn't work.  Sorry.

**Comment by mitcht** [comment]
Oh jeez I just saw that it has over 1.8gb of updates to install. I swear I checked it and it said "Up To Date".

Gotta love old OS's.

**Comment by phit** [comment]
what do you mean that didn't work, did the page load fine in internet explorer? then it did work

**Comment by mitcht** [comment]
No I mean, I did what you said. 

"open https://maven.minecraftforge.net/ in internet explorer or edge, then restart multimc and try again"

But I believe I didn't listen and used chrome.  So I can't be positive it would have worked or not, sadly.  Maven wants me to login so I know I hit the right page. Wrong browser though.

**Comment by phit** [comment]
It would have worked, that's the standard procedure for any user affected by this. And yes, Chrome will not work.

**Comment by mitcht** [comment]
Sorry about that.  This is all my fault.  I appreciate your time.  I learned something new though!

**Comment by phit** [comment]
no worries, enjoy the game :P
