### ISSUE TITLE
Error launching legacy 1.6.4 pack

### ISSUE THREAD

**Issue by homebromchambone** [MultiMC/Launcher#5008]
I've been attempting to launch an old private 1.6.4 pack to no avail. I have java 8 set properly, I'm running on the correct version, I've tried everything I currently could think of. Any help? 
https://paste.ee/p/CQXPx

**Comment by phit** [comment]
you are using java 17, instead of java 8 
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
