### ISSUE TITLE
Insta crash

### ISSUE THREAD

**Issue by DiamondHead1022** [MultiMC/Launcher#5013]
whenever i try to launch multi mc my game insta crashes and when i go to check my mods the .minecraft folder for that instalation does not show up

**Comment by DiamondHead1022** [comment]
here is the crash log 
[message (1).txt](https://github.com/MultiMC/Launcher/files/10241806/message.1.txt)

**Comment by FeedTheChunk** [comment]
You might try using Java 8.0.311 or earlier.  If I remember correctly, Forge will not run on any later version of Java 8.  It's been a while but I'm pretty sure that's the case.  I keep an old version of Java 8 on hand just for such emergencies. 

![image](https://user-images.githubusercontent.com/35508630/207998267-c1bc34b4-37fc-4397-ac16-b53b58090f0a.png)

**Comment by DiamondHead1022** [comment]
how would i do that

**Comment by FeedTheChunk** [comment]
Google java 8.0.311.  Download the installer, install.

**Comment by DiamondHead1022** [comment]
i dont understand

**Comment by DiamondHead1022** [comment]
i can not find the download

**Comment by FeedTheChunk** [comment]
See in the list that I have above?  There are several Java 8 versions installed.  You need 8.0.311.  Use Google to find the download, download the file and install it.  Goto to setting once you've done that and make sure you select the .311 version of Java for that Instance.
![image](https://user-images.githubusercontent.com/35508630/207998738-1bb9dc8f-8f86-4ea9-a948-1ef2b96a95d4.png)

**Comment by DiamondHead1022** [comment]
when i google for it Version 8 Update 35

**Comment by FeedTheChunk** [comment]
java version 8.0.311 download

**Comment by DiamondHead1022** [comment]
i found it here https://www.oracle.com/java/technologies/javase/javase8u211-later-archive-downloads.html b ut it makes me create a account

**Comment by FeedTheChunk** [comment]
Create an account or play a newer version of MC.  I can't do much more than that for you.

**Comment by DiamondHead1022** [comment]
ok i got it installed now how do i select it

**Comment by FeedTheChunk** [comment]
Scroll up and look at the screen shot.  Edit Instance > Setting > Java Installation > Auto-detect.

**Comment by DiamondHead1022** [comment]
is selecting 1.8.0_341
 not the one i want

**Comment by DiamondHead1022** [comment]
i got it to be 311 but it still insta crashes

**Comment by FeedTheChunk** [comment]
Log?

**Comment by DiamondHead1022** [comment]
https://paste.ee/p/yKjxC

**Comment by DiamondHead1022** [comment]
i got it working i just had to make a new instance

**Comment by FeedTheChunk** [comment]
Well I hope all of that helped.  Like I said earlier, I'm not 100% sure which version of MC / Forge was affected by the later versions of java but glad you got up and going!
