### ISSUE TITLE
Voicemeeter causes errors and high cpu usage

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5014]
### Operating System

Windows

### Description of bug

Voicemeeter is an audio utility driver that can, among other things, distribute audio to up to 3 different devices (which Windows can't).

Using Voicemeeter with MultiMC causes an avalanche of errors in the log: https://i.imgur.com/sRe025e.png

This causes high cpu usage and low fps in Minecraft.

### Steps to reproduce

- Install Voicemeeter Banana
- You might need to set up audio devices to be rerouted by Voicemeeter
- You might need to select Voicemeeter input in audio devices
- Run an instance of Minecraft with MultiMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
MultiMC has nothing to do with how the game does audio, you can try reporting this to Mojang.

**Comment by ghost** [comment]
Minecraft without MultiMC does not suffer from any high cpu usage or low fps with Voicemeeter open
