### ISSUE TITLE
exitcode 6

### ISSUE THREAD

**Issue by cosg2002** [MultiMC/Launcher#5015]
### Operating System

Linux

### Description of bug

Apparently curseforge made it so you cant simply import modpacks from their website into MultiMC as it will no longer recognize the zip archive, so i used this workaround https://www.reddit.com/r/VaultHuntersMinecraft/comments/vb5nab/archive_does_not_contain_a_recognized_modpack/ic743ze/
that i found by simply searching the issue on google. the problem is that I get to the launch screen and get this error log:
**[https://paste.ee/p/Pcl3y](https://paste.ee/p/Pcl3y)**

but i used minecraft version 1.18.2 which is the version ATM7 runs on. I also used Java 17.0.5 instead of java 8 as I got an error saying that it requires 17. Im also using forge 40.1.86 because it requires a newer version of forge than what is described in the workaround post.

### Steps to reproduce

https://www.reddit.com/r/VaultHuntersMinecraft/comments/vb5nab/archive_does_not_contain_a_recognized_modpack/ic743ze/
following the steps in this comment on reddit.
_"download zip
download serverfiles
create a 1.16.5 vanilla instance
click edit instance
add forge 36.2.23 to instance
click open .minecraft folder
unzip the modpack zip
open overrides folder
copy the folders from the overrides folder into the .minecraft folder of your instance
unzip the serverfiles
copy the mods folder from the serverfiles into the .minecraft folder of your instance"_

but i used minecraft version 1.18.2 which is the version ATM7 runs on. I also used Java 17.0.5 instead of java 8 as I got an error saying that it requires 17. Im also using forge 40.1.86 because it requires a newer version of forge than what is described in the workaround post.

### Suspected cause

im clueless.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
assign more memory to the game
