### ISSUE TITLE
Java Crash

### ISSUE THREAD

**Issue by DrekanHeim** [MultiMC/Launcher#5016]
### Operating System

Windows

### Description of bug

Game Should load, but I get a crash error

Crash error is:
MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [52.84.217.63, 52.84.217.37, 52.84.217.50, 52.84.217.44]

session.minecraft.net resolves to:
    [34.197.32.8, 100.24.172.95, 35.153.153.200]

textures.minecraft.net resolves to:
    [2620:1ec:46::66, 2620:1ec:bdf::66, 13.107.213.66, 13.107.246.66]

api.mojang.com resolves to:
    [18.154.101.35, 18.154.101.43, 18.154.101.16, 18.154.101.41]

Minecraft folder is:
C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 18.0.2.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.0/log4j-slf4j18-impl-2.17.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/text2speech/1.13.9/text2speech-1.13.9.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.16/JarJarSelector-0.3.16.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.16/JarJarMetadata-0.3.16.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/net/minecraftforge/fmlloader/1.19.2-43.2.0/fmlloader-1.19.2-43.2.0.jar
  C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/libraries/minecrift-1.19.2-jrbudda-VR-2-b8-forge.jar
  C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/libraries/OptiFine-1.19.2_HD_U_H9_LIB.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-ovr/3.2.2/lwjgl-ovr-3.2.2.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar
  C:/Users/bocke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl-ovr/3.2.2/lwjgl-ovr-3.2.2-natives-windows.jar

Mods:
  [✔️] appleskin-forge-mc1.19-2.4.2
  [✔️] architectury-6.4.62-forge
  [✔️] balm-4.5.3
  [✔️] BiomesOPlenty-1.19.2-17.1.1.162
  [✔️] blockui-1.19-0.0.64-ALPHA
  [✔️] Clumps-forge-1.19.2-9.0.0+14
  [✔️] collective-1.19.2-5.25
  [✔️] constructionwand-1.19.1-2.8
  [✔️] Controlling-forge-1.19.2-10.0+7
  [✔️] Croptopia-1.19.2-FORGE-2.1.0
  [✔️] CroptopiaAdditions-1.19.2-FORGE-1.0-fix
  [✔️] culinaryconstruct-forge-5.0.0-beta.1+1.19.2
  [✔️] Decorative Blocks-forge-1.19.2-3.0.0
  [✔️] domum_ornamentum-1.19-1.0.75-ALPHA-universal
  [✔️] FastLeafDecay-30
  [✔️] ftb-chunks-forge-1902.3.13-build.207
  [✔️] ftb-library-forge-1902.3.10-build.162
  [✔️] ftb-teams-forge-1902.2.10-build.76
  [✔️] ftb-ultimine-forge-1902.3.5-build.65
  [✔️] guardvillagers-1.19.2-1.5.2
  [✔️] ironchest-1.19.2-14.2.7
  [✔️] ironfurnaces-1.19.2-3.6.3
  [✔️] jei-1.19.2-forge-11.4.0.288
  [✔️] journeymap-1.19.2-5.9.0beta4-forge
  [✔️] JustEnoughResources-1.19.2-1.2.0.188
  [✔️] minecolonies-1.19.2-1.0.1137-ALPHA
  [✔️] moonlight-1.19.2-2.1.15-forge
  [✔️] MouseTweaks-forge-mc1.19-2.23
  [✔️] multipiston-1.19.2-1.2.21-ALPHA
  [✔️] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13
  [✔️] OptiFine_1.19.2_HD_U_H9
  [✔️] silent-gear-1.19.2-3.1.0
  [✔️] silent-lib-1.19.2-7.0.3
  [✔️] silents-gems-1.19.2-4.4.1
  [✔️] simplemagnets-1.1.8b-forge-mc1.19
  [✔️] SimpleStorageNetwork-1.19-1.6.4
  [✔️] structurize-1.19.2-1.0.468-ALPHA
  [✔️] supermartijn642configlib-1.1.6b-forge-mc1.19
  [✔️] supermartijn642corelib-1.0.19a-forge-mc1.19
  [✔️] supplementaries-1.19.2-2.2.26
  [✔️] TerraBlender-forge-1.19.2-2.0.1.128
  [✔️] theoneprobe-1.19-6.2.2
  [✔️] villagernames_1.19.2-4.3
  [✔️] waystones-forge-1.19-11.1.0
  [✔️] YungsApi-1.19.2-Forge-3.8.2
  [✔️] YungsBetterDesertTemples-1.19.2-Forge-2.2.1
  [✔️] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔️] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔️] YungsBetterOceanMonuments-1.19.2-Forge-2.1.0
  [✔️] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔️] YungsBetterWitchHuts-1.19.2-Forge-2.1.0
  [✔️] YungsBridges-1.19.2-Forge-3.1.0
  [✔️] YungsExtras-1.19.2-Forge-3.1.0

Params:
  --username  --version 1.19.2 --gameDir C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/.minecraft --assetsDir C:/Users/bocke/Desktop/MultiMC/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 43.2.0 --fml.mcVersion 1.19.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220805.130853

Window size: 854 x 480

Java Arguments:
[-XX:+UseZGC, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms8192m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 8976

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2022-12-18 14:40:54,397 main WARN Advanced terminal features are not available in this environment
[14:40:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, DrekanHeim, --version, 1.19.2, --gameDir, C:/Users/bocke/Desktop/MultiMC/instances/1.19.2/.minecraft, --assetsDir, C:/Users/bocke/Desktop/MultiMC/assets, --assetIndex, 1.19, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.0, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[14:40:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 18.0.2.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Caused by: java.lang.module.ResolutionException: Module optifine reads another module named optifine
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:719)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:130)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).

### Steps to reproduce

Launch Multimc, Run modpack, voila.

### Suspected cause

Java

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DrekanHeim** [comment]
Ran just fine before, but then i added Vivecraft and it crashes every single time

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
