### ISSUE TITLE
MultiMC doesn't load Forge on 1.12.2 

### ISSUE THREAD

**Issue by IDKimBoredCL** [MultiMC/Launcher#5017]
### Description of bug

I was trying to load a server that i'm working on, this server runs in MC 1.12.2 and has two mods. When i loaded the 1.12.2 instance that i made with Forge (latest version 14.23.5.2860) and the two mods, Pixelmon Reforged and Custom NPCs, it loaded perfectly until i tried to join the server. When i joined a message that wrote <### This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details### > It has never happened to me! I've tried to reinstall the instance with different versions of Forge and the error still pops up! 
![2022-12-19_08-57](https://user-images.githubusercontent.com/107329129/208551020-b6c9a673-3e95-4727-bb4f-86d80277e92b.png)

### Steps to reproduce

- Make the server
- Create a new instance of MC 1.12.2 
- Press the "Install Forge" button and select the LATEST version
- Load up the mods
- Open it up
- Join the IP

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
