### ISSUE TITLE
Tie an account to an instance

### ISSUE THREAD

**Issue by Merlin72875** [MultiMC/Launcher#5018]
### Role

I play MC with multiple MS accounts

### Suggestion

Set the account to be used with each instance

### Benefit

Keep from having to select hte account from the top-right menu before launching each instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently, I have three accounts and three instances which I use exclusively with each of those accounts. I only ever use the account with the specific instance. It would save time when launching the instances to just have the account selected for that instance.

Thank you!

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/3116
