### ISSUE TITLE
[Feature Request] Create instance shortcut

### ISSUE THREAD

**Issue by jeengbe** [MultiMC/Launcher#5020]
### Role

n/a

### Suggestion

Provide a button that creates a shortcut that directly opens the selected instance instead of MultiMC

### Benefit

I can directly pin my instance to the taskbar without needing to open MultiMC only to launch the instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is already possible by manually appending `-l instanceId` to the launch shortcut, converting the icon to .ico and changing it manually. It would be really nice if MultiMC had such a feature out of the box, amongst the following buttons for instance:
![image](https://user-images.githubusercontent.com/51749023/209429982-b873c580-1d89-4849-9a43-2a3b33952266.png)

Would be cool together with  #4960 to allow for instant recognition of the instance shortcuts (on desktop or taskbar for instance).

![image](https://user-images.githubusercontent.com/51749023/209430043-d346f6de-3f99-4195-a51a-df0622f1a43c.png)

**Comment by phit** [comment]
this was already added, update to the development version in the settings

**Comment by jeengbe** [comment]
Sweeet thanks

**Comment by Splarkszter** [comment]
> @phit this was already added, update to the development version in the settings

I guess Linux version hasn't been updated [I use Mint, btw]
![image](https://user-images.githubusercontent.com/90066319/210477552-44a533f7-ad0a-4cb2-9a42-6258fd96bfca.png)
