### ISSUE TITLE
Suggestion ( for all versions, especially 1.12.2 with Forge )

### ISSUE THREAD

**Issue by Kasia1403** [MultiMC/Launcher#5021]
### Role

I play modded Minecraft

### Suggestion

To make Minecraft load faster and show more details about loading progress and estimated time how long to wait until modpack will fully load.

### Benefit

I will know how much time my modpack is loading and how much time I must wait until my modpack will be loaded.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Is my description understandable ? I'm disabled and also my language is Polish, but here I'm trying to write in English unfortunately.

**Comment by phit** [comment]
multimc has no such info, and neither does the game for the most part, so even if we wanted to do this, we can't

**Comment by Kasia1403** [comment]
Maybe this info is showed only if Forge is istalled ( and I meant loading screen, not launcher itself ) ?

**Comment by phit** [comment]
multimc has nothing to do with the loading screen, thats the game
