### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [MultiMC/Launcher#5022]
### Role

I play modded Minecraft

### Suggestion

Add possibilty to update mods like in Prism launcher

### Benefit

so that I will always have updated mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Could You add at least this thing, please ? And I'm saying "Please" and I'm repeating it 1000 times - that much.

**Comment by Kasia1403** [comment]
Could You show me where is a similar issue or similar suggestion ?

**Comment by phit** [comment]
some examples include 
https://github.com/MultiMC/Launcher/issues/4532
https://github.com/MultiMC/Launcher/issues/4629

**Comment by Kasia1403** [comment]
Sorry, but I will be disappointed because of this situation ( not because of that, that my issue is a duplicate, but because of that, that my suggestion will not be added ).

**Comment by kasia1403-is-a-stupid-retard** [comment]
No one cares if you end up crying in your soiled diapers because mod authors don't agree to each one of your wishes.
