### ISSUE TITLE
Minecraft 1.12.2

### ISSUE THREAD

**Issue by Gseven2002YT** [MultiMC/Launcher#5023]
### Description of bug

Minecraft 1.12.2 if started with Forge and Mods installed does not start the game

### Steps to reproduce

Install Minecraft 1.12.2 and start with Forge and Mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
