### ISSUE TITLE
\a

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5025]
### Operating System

Windows

### Description of bug

It did not launch

### Steps to reproduce

I wanted to make version c0.24_03 survival test

so i first downloaded the jar from https://archive.org/download/Minecraft-JE-Classic/c0.24_st_03/

First i downloaded Multi Mc

Then I use jdk-17.0.1 as Java path goinh to bin then going to javaw 

Path to javaw :C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Then log into my account

Then made version c0.30_1c

Then copy instance

Then edited instance and click replace jar with Minecraft hilighted 

Then replaced it with the jar still in the downloads folder

Then I clicked Launch and not Launch offline and did not work

Minecraft Log conlose window:

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.162.59, 13.33.162.57, 13.33.162.50, 13.33.162.38]

session.minecraft.net resolves to:
    [35.153.153.200, 34.197.32.8, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.107.237.38, 13.107.238.38]

api.mojang.com resolves to:
    [13.33.165.103, 13.33.165.10, 13.33.165.17, 13.33.165.30]

Minecraft folder is:
D:/downloads/mmc-stable-win32 (1)/MultiMC/instances/c0.24_03_st/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  com.mojang.minecraft.l

Native path:
  D:/downloads/mmc-stable-win32 (1)/MultiMC/instances/c0.24_03_st/natives

Traits:
traits legacyLaunch
traits no-texturepacks

Libraries:
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-stable-win32 (1)/MultiMC/instances/c0.24_03_st/libraries/customjar-1.jar

Native libraries:
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/downloads/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 9644

Using onesix launcher.

Could not set base folder. Failed to find/access Minecraft main class:
java.lang.ClassNotFoundException: com.mojang.minecraft.l
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:101)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Suspected cause

I do not know suspected cause but maybe i just missed a step or did something wrong I do not know

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
instead of c0.30_1c use c0.0.13a as a base, otherwise follow the steps you outlined but also do the following:

customize the Minecraft entry in the version tab, by clicking on it then clicking customize on the right, clicking on it again and then clicking edit on the right, then look for the line mainClass and change it from 
`"mainClass": "com.mojang.minecraft.Minecraft",`
to
`"mainClass": "com.mojang.minecraft.Minecraft$OS",`

**Comment by Primitive-Human** [comment]
I don't think those very early versions of MC used Java 17 either.

**Comment by JJminecraftguy** [comment]
If you know the answer reply to this comment

**Comment by JJminecraftguy** [comment]
What java version do i use Primitive-Human

**Comment by JJminecraftguy** [comment]
> instead of c0.30_1c use c0.0.13a as a base, otherwise follow the steps you outlined but also do the following:
> 
> customize the Minecraft entry in the version tab, by clicking on it then clicking customize on the right, clicking on it again and then clicking edit on the right, then look for the line mainClass and change it from `"mainClass": "com.mojang.minecraft.Minecraft",` to `"mainClass": "com.mojang.minecraft.Minecraft$OS",` -phit

 when i click edit 7-zip says
 Unsuported command:
 D:\downloads\mmc-stable-win32
(1)\MultiMC\instances\c0.0.13a\patches\net.minecraft.json

please tell me how to fix this issue

**Comment by JJminecraftguy** [comment]
> I don't think those very early versions of MC used Java 17 either. -Primitive-Human

well the base version c0.30_1c worked fine with the java wich is the base of the survival test so that cant be it

**Comment by phit** [comment]
your file associations are broken, change the editor for json files https://www.digitaltrends.com/computing/how-to-change-file-associations/

**Comment by JJminecraftguy** [comment]
> your file associations are broken, change the editor for json files https://www.digitaltrends.com/computing/how-to-change-file-associations/ -phit

change what editor

**Comment by JJminecraftguy** [comment]
> your file associations are broken, change the editor for json files https://www.digitaltrends.com/computing/how-to-change-file-associations/

also it still says .json and not .7zip

what app should open it

**Comment by phit** [comment]
any text editor, like notepad

**Comment by JJminecraftguy** [comment]
> any text editor, like notepad -phit

Is it ok if i use notepad++

**Comment by phit** [comment]
as i said, any text editor

**Comment by JJminecraftguy** [comment]
ok

**Comment by JJminecraftguy** [comment]
what do i do know with net.minecraft.json open

**Comment by JJminecraftguy** [comment]
> as i said, any text editor -phit

what do i do know with net.minecraft.json open

**Comment by JJminecraftguy** [comment]
WHAT DO I DO

**Comment by JJminecraftguy** [comment]
BRO

**Comment by FluffyPuppyKasey** [comment]
> BRO

Necroposting I know but I can't stand when people don't read.

They told you exactly what to do earlier
