### ISSUE TITLE
Add 2 default java path

### ISSUE THREAD

**Issue by golemax** [MultiMC/Launcher#5026]
### Role

Configure Minecraft instances from many versions

### Suggestion

Add 2 default java path

### Benefit

Avoid reconfiguring java between Minecraft 1.17 and newer and Minecraft 1.16 and older

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Versions 1.17 and above uses java 17 and versions 1.16 and below uses java 8 but since there is only one default java path we have to reconfigure java in each instance or java must be different from base java path

**Comment by Primitive-Human** [comment]
I don't see this being that much better than just manually configuring the Java version **once** for every instance.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/4013
