### ISSUE TITLE
c0.24_03 survival test part 2

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5027]
### Description of bug

What do i do now since i opend it

### Steps to reproduce

look at 0.24_03 survival test part 1 and look in the comments

### Suspected cause

tell me phit what to do know since i open net.minecraft.json

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
stop making new issues and read what you were told already in the old one

**Comment by JJminecraftguy** [comment]
What do i do know since i opend net.minecraft.json

**Comment by JJminecraftguy** [comment]
TELL ME

**Comment by peterix** [comment]
This is not a chat room.
