### ISSUE TITLE
The Versions wont start no matter what i do

### ISSUE THREAD

**Issue by h1pixel** [MultiMC/Launcher#5029]
### Operating System

Windows

### Description of bug

just cant start minecraft i tried everything from reinstalling it to installing java again

### Steps to reproduce

press launch then crash with exit code 1 (Process exited with code 1 (0x1))

### Suspected cause

i suspect that multimc is broken

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them.

![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by h1pixel** [comment]
https://paste.ee/p/B25dU

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs

**Comment by h1pixel** [comment]
how do i install that version of java

**Comment by phit** [comment]
read the page I linked above

**Comment by h1pixel** [comment]
ok so i have tried install it like on the picture and all but if i try to open the file with multimc it just opens the folder and then i have to select something else and if i try that with putting the zip file in it still crashes

**Comment by h1pixel** [comment]
also my intel cpu is not even too old its an intel i5 cpu i think its just multimc beeing bad

**Comment by laydenallison12** [comment]
cant open minecraft

**Comment by catdogmat** [comment]
> cant open minecraft

Open your own issue, don’t use a closed one from a couple months ago
