### ISSUE TITLE
I recived the error "Process exited with code 255 (0xff)" and don't know the steps to fix it.

### ISSUE THREAD

**Issue by PoisonousInk** [MultiMC/Launcher#5030]
### Operating System

Windows

### Description of bug

I have been trying to get this program to work on my new raspberry 4 but I needed to download everything by hand. So I don't know if this error is coming up because I missed files or if there is some other underlying problem. Any help is appreciated. Oh and I was able to successfully download and run the Bedrock version of Minecraft, I'm just having trouble understanding what is the problem with this version.

### Steps to reproduce

https://paste.ee/p/OErfR

### Suspected cause

Lack of files or raspberry pi being unable to handle Java Mine craft.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
ARM isnt supported, duplicate of https://github.com/MultiMC/Launcher/issues/2133 and countless of others
