### ISSUE TITLE
Forge 1.12.2

### ISSUE THREAD

**Issue by VolinoKurama** [MultiMC/Launcher#5033]
### Operating System

Windows

### Description of bug

whenever i try to open version 1.12.2 with any version of forge downloaded it gives me error

### Steps to reproduce

as soon as I install Forge it won't let me open minecraft because it gives me an error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
