### ISSUE TITLE
My multimc crashed with exitcode -1073740940; System exit code name: STATUS_HEAP_CORRUPTION.

### ISSUE THREAD

**Issue by WhyMonkeInside** [MultiMC/Launcher#5034]
### Operating System

Windows

### Description of bug

I start the game, create a world, and when the world is fully loaded, minecraft crashes with this error. 

### Steps to reproduce

Run mods without lags and crashes.

### Suspected cause

Java also loads the i3 9100f processor at 100% even without mods, although before that everything was fine.
Perhaps this is due to the fact that I changed the type of the system disk from mbr to gpt and because of this the files are damaged. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by WhyMonkeInside** [comment]
Logs: https://paste.ee/p/DeYUr

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
