### ISSUE TITLE
betas 1.7-1.7.3 are not working on Mac

### ISSUE THREAD

**Issue by brown-sus** [MultiMC/Launcher#5036]
### Description of bug

They start up fine enough, just when the window opens the window turns black. The buttons, game, and audio still work, just not the video. After a minute or so, the screen flashes a violent grey and white for a few seconds, then turns white. From what I can tell, all of the other vanilla versions work just fine, just not these three. If it helps, I'm on macOS Monterey 12.6. Thanks for the fabulous product!

### Steps to reproduce

1. open MultiMC
2. start up new instance that is in the version: b1.7, b1.7.2, or b1.7.3

### Suspected cause

It could be a jank video file or something idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what Java version are you using?

**Comment by brown-sus** [comment]
Java 8 update 351

**Comment by phit** [comment]
use an older Java version https://github.com/MultiMC/Launcher/issues/3543#issuecomment-763407863
