### ISSUE TITLE
2b2t only crashing when using multimc

### ISSUE THREAD

**Issue by Veitaserum4** [MultiMC/Launcher#5037]
### Operating System

Linux

### Description of bug

(This issue is exclusive to Multimc) I keep crashing when in the 2b2t queue. The error that minecraft presents to me is: "An internal error occurred in your internet" Or "Timed out". I don't get this issue on the normal launcher however so I reinstalled multimc, reinstalled minecraft and cleared my dns cache. Nothing worked, I don't think it can be my internet because the issue persisted on another network. I've tried with and without hacked client and the issue still persists, every other server works perfectly fine. 
Here's a vanilla log: https://paste.ee/p/jW6Ob
Here's another vanilla log: https://paste.ee/p/2N7kV
Log with mods enabled (Impact, schematica, LunatriusCore and Optifine 1.12.2 G5): https://paste.ee/p/YRn2o
If you need any more information let me know

### Steps to reproduce

Create new 1.12.2 instance
launch it without any mods or mod loaders
Join 2b2t
Wait

### Suspected cause

Unknown

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> java.net.ConnectException: finishConnect(..) failed: No route to host

that's definitely on your end

**Comment by Veitaserum4** [comment]
I guess thats better than it being on 2b2t's end i suppose
Did i install multimc wrong or something??

**Comment by phit** [comment]
its your internet, network or anything else, multimc just launches the game files provided by mojang

**Comment by Veitaserum4** [comment]
I guess ill just use the official launcher then
