### ISSUE TITLE
anything under version 1.0.0 freezes upon launch

### ISSUE THREAD

**Issue by pickleplatypuz** [MultiMC/Launcher#5038]
,

**Comment by phit** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them.

**Comment by pickleplatypuz** [comment]
Here are the logs:


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Checking Java version...
Java is version 1.8.0_333, using 64-bit architecture, from Oracle Corporation.


Main Class:
  

Native path:
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/instances/b1.7.3/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/pickl/OneDrive/Desktop/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 10896


Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: pickleplatypuz, token:<ACCESS TOKEN>:<PROFILE ID>
Jan 11, 2023 12:39:27 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Jan 11, 2023 12:39:27 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Jan 11, 2023 12:39:27 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Process was killed by user.

**Comment by phit** [comment]
try [this Java](https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs) and move MultiMC out of OneDrive

**Comment by phit** [comment]
hm, what does the game window look like exactly? try adding `-Dnet.java.games.input.useDefaultPlugin=false` to your java arguments

**Comment by pickleplatypuz** [comment]
i put in the java argument and now it is working just fine and does not seem to have anymore issues
