### ISSUE TITLE
MultiMC crashing when playing in end practice

### ISSUE THREAD

**Issue by Power3722** [MultiMC/Launcher#5041]
### Operating System

Windows

### Description of bug

Whenever I open the end practice map the game freezes. It freezes when I start moving my mouse but this does not happen in a regular world. If I don't look around with my mouse it does not freeze but as soon as I start moving my mouse it freezes. Here is the log. https://paste.ee/p/C20c6

### Steps to reproduce

Whenever I open the end practice map the game freezes. It freezes when I start moving my mouse but this does not happen in a regular world. If I don't look around with my mouse it does not freeze but as soon as I start moving my mouse it freezes. Here is the log. https://paste.ee/p/C20c6

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
