### ISSUE TITLE
MultiMC fails to launch Minecraft on Apple Silicon chip

### ISSUE THREAD

**Issue by Cat7373** [MultiMC/Launcher#5044]
### Operating System

macOS

### Description of bug

MultiMC won't start Minecraft on Apple M1 chip, which could have been easily fixed.

### Steps to reproduce

1. A Mac computer with an Apple Silicon chip, with macOS installed
2. Install 1.19.3 with MultiMC and try to start

### Suspected cause

1. Use the wrong lwjgl configuration, you should use the arm64 version instead of the x86 version
2. The arm64 version can be downloaded at libraries.minecraft.net, which means that the official Apple Silicon is also supported by this method
3. Working fix (tested): [Link Removed]
4. It can be seen that this repair solution is simply replacing the native library from *-macos.jar to *-macos-arm64.jar, and repairing the file size and sha1 signature at the same time
5. It is recommended to use this solution to simply modify the support of MultiMC on Apple Silicon (for most people, it is too difficult to set up Rosetta, and the MultiMC downloaded from the official website does not support running through Rosetta

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Rosetta works fine, M1 support will come eventually but requires a lot of other work first.

**Comment by Cat7373** [comment]
After repeated tests, I used an arm64-based Java environment to install 1.19.3 directly and then start it. It must have failed to start unless the configuration of lwjgl is modified.

**Comment by phit** [comment]
There's your problem, you need to use x64 Java for Rosetta to work.. stop spamming our issue tracker with your "fix".
