### ISSUE TITLE
Cant launch the instance after I tried to clone it

### ISSUE THREAD

**Issue by shinenyugen** [MultiMC/Launcher#5045]
### Description of bug

Crash log : https://paste.ee/p/rlszv

I dont know how to fix it I hope you can help. It was working fine until i tried to copy the instance and I got an error

### Steps to reproduce

https://paste.ee/p/rlszv

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by shinenyugen** [comment]
> I think it crashes because I also moved the MultiMC folder somewhere else

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
