### ISSUE TITLE
Crash on older versions

### ISSUE THREAD

**Issue by pokemon12323** [MultiMC/Launcher#5046]
### Operating System

Windows 11

### Description of bug

Title says it all

### Steps to reproduce

* Have Java 17 installed
* Play 1.12 (I believe)

### Suspected cause

Maybe this version of java is too new for 1.12

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by pokemon12323** [comment]
https://pastebin.com/avCz7PKf is the log

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older

**Comment by pokemon12323** [comment]
> https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older

that didn't work
