### ISSUE TITLE
crash on older versions with exit code 1

### ISSUE THREAD

**Issue by pokemon12323** [MultiMC/Launcher#5047]
### Operating System

Windows

### Description of bug

Title says it all
(I made a post here before, but somebody closed it with https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#minecraft-116-and-older but that didn't work)

### Steps to reproduce

* have Java 8 312
* Launch 1.11.2

### Suspected cause

MultiMC version: 0.7.0-develop-3638

Launched instance in online mode

authserver.mojang.com resolves to:
    [2607:7700:0:30::6c8a:9533, 2607:7700:0:30::6c8a:9540, 2607:7700:0:30::6c8a:9530, 2607:7700:0:30::6c8a:9541, 108.138.149.51, 108.138.149.48, 108.138.149.65, 108.138.149.64]

session.minecraft.net resolves to:
    [2607:7700:0:30::2399:99c8, 2607:7700:0:30::6418:ac5f, 2607:7700:0:30::22c5:2008, 35.153.153.200, 100.24.172.95, 34.197.32.8]

textures.minecraft.net resolves to:
    [2620:1ec:4e:1::57, 2620:1ec:4f:1::57, 13.107.237.57, 13.107.238.57]

api.mojang.com resolves to:
    [2607:7700:0:30::de2:b824, 2607:7700:0:30::de2:b848, 2607:7700:0:30::de2:b869, 2607:7700:0:30::de2:b81d, 13.226.184.29, 13.226.184.105, 13.226.184.36, 13.226.184.72]

Minecraft folder is:
C:/Users/Luke/Desktop/MultiMC/instances/FTB Presents Skyfactory 3/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Luke/Desktop/MultiMC/instances/FTB Presents Skyfactory 3/natives

Libraries:
  C:/Users/Luke/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/mojang/realms/1.9.8/realms-1.9.8.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.0.12_mojang/fastutil-7.0.12_mojang.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.10.2-12.18.3.2477/forge-1.10.2-12.18.3.2477-universal.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/com/mojang/minecraft/1.10.2/minecraft-1.10.2-client.jar

Native libraries:
  C:/Users/Luke/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Luke/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] [1.10.x]FenceOverhaul-1.2.1.jar
  [✔️] ActuallyAdditions-1.10.2-r105.jar
  [✔️] actuallycomputers-1.0.0.jar
  [✔️] angelRingToBauble-1.10.2-0.2.4.19+d71eb9e.jar
  [✔️] AppleCore-mc1.10.2-2.2.2.jar
  [✔️] AppleShields-0.1.7.jar
  [✔️] AppleSkin-mc1.10.2-1.0.8.jar
  [✔️] autopackager-1.6.4b.jar
  [✔️] AutoRegLib-1.0-2.jar
  [✔️] baconators-1.10.2-3.0.6.jar
  [✔️] base-1.10.2-1.4.0.jar
  [✔️] Baubles-1.10.2-1.3.11.jar
  [✔️] bdlib-1.12.4.24-mc1.10.2.jar
  [✔️] BedBugs-1.10.2-1.1.6.jar
  [✔️] BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
  [✔️] BetterFps-1.4.5-1.10.jar
  [✔️] BetterThanBunnies-1.10.2-1.1.0.jar
  [✔️] BiomeTweaker-1.10.2-2.3.239.jar
  [✔️] BlockDispenser-1.0-1.jar
  [✔️] BloodMagic-1.10.2-2.1.11-80.jar
  [✔️] Bookshelf-1.10.2-1.4.4.347.jar
  [✔️] Botania r1.9-341.jar
  [✔️] BrandonsCore-1.10.2-2.1.12.130-universal.jar
  [✔️] Ceramics-1.10.2-1.1.6b.jar
  [✔️] Chameleon-1.10.2-2.3.0.jar
  [✔️] ChanceCubes-1.10.2-3.0.1.207.jar
  [✔️] Charset-mc1.10.2-0.3.5-fd38f2c944396214.jar
  [✔️] ChestTransporter-1.10.2-2.5.18.jar
  [✔️] ChickenChunks-1.10.2-2.2.0.52-universal.jar
  [✔️] chickens-4.3.2.jar
  [✔️] Chisel-MC1.10.2-0.0.14.33.jar
  [✔️] chiselsandbits-12.15.jar
  [✔️] ClientTweaks_1.10.2-1.1.16.jar
  [✔️] Clipboard-1.10.2-1.1.1.jar
  [✔️] Clumps-1.0.5.jar
  [✔️] CodeChickenCore-1.10.2-2.4.1.102-universal.jar
  [✔️] CodeChickenLib-1.10.2-2.5.9.283-universal.jar
  [✔️] ColossalChests-1.10.2-1.6.0.jar
  [✔️] CommonCapabilities-1.9.4-1.3.3.jar
  [✔️] compatlayer-1.10-0.2.9.jar
  [✔️] Controlling-1.0.5.jar
  [✔️] CookingForBlockheads_1.10.2-4.2.45.jar
  [✔️] CraftTweaker-1.10.2-3.0.26.jar
  [✔️] CTM-MC1.10.2-0.2.2.24.jar
  [✔️] CustomMainMenu-MC1.10.2-2.0.5.jar
  [✔️] CyclopsCore-1.9.4-0.10.9.jar
  [✔️] DarkUtilities-1.1.8.finalrc2.jar
  [✔️] Decocraft-2.4.2_1.10.2.jar
  [✔️] DefaultOptions_1.10.2-6.1.5.jar
  [✔️] dimensionalcake-1.9.4-0.0.1.jar
  [✔️] Draconic-Evolution-1.10.2-2.1.6.263-universal.jar
  [✔️] DragonMounts-r46-1.10.2.jar
  [✔️] DrawersBits-1.10.2-0.36.jar
  [✔️] ElevatorMod[V.1.3.0][MC.1.10.2].jar
  [✔️] EnderCore-1.10.2-0.4.1.66-beta.jar
  [✔️] EnderIO-1.10.2-3.1.193.jar
  [✔️] EnderStorage-1.10.2-2.2.1.106-universal.jar
  [✔️] energyconverters_1.10.2-1.0.0.26.jar
  [✔️] EngineersWorkshop-1.3.6-1.10.2.jar
  [✔️] environmentaltech-1.10.2-0.10.6b.jar
  [✔️] etlunar-1.10.2-0.10.6a.jar
  [✔️] ExCompressum_1.10.2-2.0.97.jar
  [✔️] exnihiloadscensio-1.10.2-0.1.20.jar
  [✔️] ExtraBitManipulation-1.10.2-2.5.1.jar
  [✔️] extrautils2-1.10.2-1.6.3.jar
  [✔️] ExtremeReactors-1.10.2-0.4.5.30.jar
  [✔️] fairylights-2.1.2-1.10.2.jar
  [✔️] FarmingForBlockheads_1.10.2-1.1.16.jar
  [✔️] flatcoloredblocks-mc1.10-v4.4.jar
  [✔️] FluxNetworks-1.10.2-1.2.8.jar
  [✔️] foamfix-0.7.2-anarchy.jar
  [✔️] Forgelin-1.5.1.jar
  [✔️] FTBLib-1.1x-3.6.5.jar
  [✔️] FTBUtilities-1.1x-3.6.5.jar
  [✔️] FullscreenWindowed-1.10.2-1.5.1.jar
  [✔️] Funnels-1.10.2-1.1.2.jar
  [✔️] GardenOfGlass.jar
  [✔️] generators-0.9.20.23-mc1.10.2.jar
  [✔️] GooglyEyes-1.10.2-6.0.0.jar
  [✔️] gravestone-1.5.13.jar
  [✔️] Grue-1.9.4-1.3.5.jar
  [✔️] Guide-API-1.10.2-2.0.3-46.jar
  [✔️] Gyth-1.10.2-2.0.0.27.jar
  [✔️] HammerCore-1.10.2-1.9.4.3.jar
  [✔️] hatchery-1.10.2-0.3.21.jar
  [✔️] Headcrumbs-2.0.3.jar
  [✔️] hopperducts-mc1.9.4-1.4.8.1.jar
  [✔️] Hwyla-1.8.17-B31_1.10.2.jar
  [✔️] hydrogel-0.9.jar
  [✔️] ImmersiveEngineering-0.10-61.jar
  [✔️] InGameInfoXML-1.10.2-2.8.1.89-universal.jar
  [✔️] InitialInventory-1.0.1.jar
  [✔️] IntegratedDynamics-1.10.2-0.7.12.jar
  [✔️] IntegratedTunnels-1.10.2-1.2.5.jar
  [✔️] inventorysorter-1.10.2-0.11.0+47.jar
  [✔️] IronBackpacks-1.10.2-2.2.31.jar
  [✔️] ironchest-1.10.2-7.0.15.804.jar
  [✔️] ItsBecauseUHasNoGoodSpawn-1.0.5.jar
  [✔️] itsrainingfood-1.10.2-0.1.0.jar
  [✔️] jei_1.10.2-3.14.7.420.jar
  [✔️] journeymap-1.10.2-5.5.0b4.jar
  [✔️] KleeSlabs_1.10.2-3.3.5.jar
  [✔️] literalascension-1.10.2-1.0.2.2.jar
  [✔️] llibrary-1.7.7-1.10.2.jar
  [✔️] LongFallBoots - Hard Mode.jar
  [✔️] LootBags-1.10.2-2.3.9.jar
  [✔️] LunatriusCore-1.10.2-1.1.2.38-universal.jar
  [✔️] Mantle-1.10.2-1.1.5.jar
  [✔️] mcjtylib-1.1x-2.4.3.jar
  [✔️] MCMultiPart-1.4.0-universal.jar
  [✔️] Mercurius-1.10.2-1.0.6.jar
  [✔️] MineMenu-1.10.2-1.4.5-universal.jar
  [✔️] minicoal-1.1.0.jar
  [✔️] missing_pieces-1.10.2-4.3.0.jar
  [✔️] MoarSigns-1.10.2-4.2.3.9.jar
  [✔️] MobGrindingUtils-0.1.8.22.jar
  [✔️] ModTweaker2-2.0.13.jar
  [✔️] MoreChickens-1.10.2-1.1.6.jar
  [✔️] MoreShearables1.2.1-1.10.2.jar
  [✔️] moreshears-1.10.2-1.0.5-release.jar
  [✔️] Morpheus-1.10.2-3.1.13.jar
  [✔️] MouseTweaks-2.8-mc1.10.2.jar
  [✔️] mpbasic-1.10.2-1.1.5.jar
  [✔️] mputils-1.10.2-1.2.9.jar
  [✔️] MTLib-1.0.3.jar
  [✔️] mysticalagriculture[1.10.2]-1.5.8.jar
  [✔️] natura-1.10.2-4.1.0.80.jar
  [✔️] Neat 1.3-12.jar
  [✔️] nice-0.1.0.jar
  [✔️] NotEnoughItems-1.10.2-2.1.3.220-universal.jar
  [✔️] notenoughwands-1.1x-1.5.5.jar
  [✔️] OpenComputers-MC1.10.2-1.6.2.7.jar
  [✔️] OreExcavation-1.2.102.jar
  [✔️] PackingTape-1.10.2-0.6.0.jar
  [✔️] Pam's HarvestCraft 1.9.4-1.10.2h.jar
  [✔️] platforms-1.10.0-1.2.10.jar
  [✔️] Psi-r1.0-42.jar
  [✔️] QuantumStorage-1.10.2-3.3.6.jar
  [✔️] RandomThings-MC1.10.2-3.7.7.1.jar
  [✔️] rangedpumps-0.3.jar
  [✔️] RebornCore-1.10.2-2.13.6.142-universal.jar
  [✔️] RebornStorage-1.10.2-1.0.3.30.jar
  [✔️] redstonepaste-mc1.9.4-1.7.4.jar
  [✔️] refinedstorage-1.2.26.jar
  [✔️] Reliquia-[1.10.2]-0.0.7.jar
  [✔️] ResourceLoader-MC1.9.4-1.5.1.jar
  [✔️] rftools-1.1x-6.13.jar
  [✔️] rftoolsctrl-1.1x-1.6.8.jar
  [✔️] rftoolsdim-1.1x-5.05.jar
  [✔️] roots-0.208.jar
  [✔️] SBM-WoodenShears-1.10.2-0.0.1b2-universal.jar
  [✔️] scanner-1.5.2.jar
  [✔️] ShadowMC-1.10.2-3.6.1.jar
  [✔️] shearmadness-1.10.2-1.7.0.4.jar
  [✔️] shetiphiancore-1.10.0-3.3.11.jar
  [✔️] SimpleAchievements-MC1.9.4-1.2.2-28.jar
  [✔️] simplebarrels-1.26e.jar
  [✔️] simpleCorn-1.10.2-2.2.0.jar
  [✔️] simplegenerators-1.10.2-0.10.6a.jar
  [✔️] simplelabels-1-10.2-0.0.3.jar
  [✔️] SimplyJetpacks2-1.10.2-2.1.3.55.jar
  [✔️] Snad-1.10.2-1.6.09.20a.jar
  [✔️] SolarFluxReborn_1.10.2-2.17r.jar
  [✔️] SonarCore-1.10.2-3.3.0.jar
  [✔️] StevesCarts-1.10.2-2.2.0.86.jar
  [✔️] StorageDrawers-1.10.2-3.7.10.jar
  [✔️] SuperCircuitMaker-1.0.4.jar
  [✔️] TConstruct-1.10.2-2.6.5.jar
  [✔️] The Beneath-1.10.2-1.2.0.jar
  [✔️] TinkerToolLeveling-1.10.2-1.0.1.jar
  [✔️] tinyprogressions-1.10.2-1.1.0.jar
  [✔️] torchmaster_1.10.2-1.4.1.34.jar
  [✔️] Translocators-1.10.2-2.1.4.55-universal.jar
  [✔️] TS2K16-1.0.3.jar
  [✔️] Twitchcrumbs_1.10.2-2.0.4.jar
  [✔️] UniDict-1.10.2-2.9b.jar
  [✔️] valkyrielib-1.10.2-0.10.6.jar
  [✔️] voidcup-1.10.2-0.0.1.jar
  [✔️] Waddles-1.10.2-0.5.4.jar
  [✔️] WanionLib-1.10.2-1.3.jar
  [✔️] Wawla-1.10.2-2.3.2.215.jar
  [✔️] witherCrumbs-1.10.2-0.9.jar
  [✔️] xprings-1.10-1.3.0.jar
  [✔️] YUNoMakeGoodMap-1.10.2-6.1.0.26.jar
  [✔️] zerocore-1.10.2-0.1.0.6.jar

Params:
  --username  --version 1.10.2 --gameDir C:/Users/Luke/Desktop/MultiMC/instances/FTB Presents Skyfactory 3/.minecraft --assetsDir C:/Users/Luke/Desktop/MultiMC/assets --assetIndex 1.10 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms8192m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 1884

Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you didn't follow the wiki and are still using the wrong java version, stop making new issues

**Comment by pokemon12323** [comment]
> you didn't follow the wiki and are still using the wrong java version, stop making new issues

sorry. I thought I had tried it previously with the one you gave me the link to, but it didn't work. Maybe I thought it happened but I just imagined it, or maybe it hadn't changed for some reason.

**Comment by pokemon12323** [comment]
the fix from the og post worked
