### ISSUE TITLE
[future request] auto download mod depedencies

### ISSUE THREAD

**Issue by rebokdev** [MultiMC/Launcher#5048]
### Role

Less time spend downloading mods

### Suggestion

I want to multimc auto download mod depedencies

### Benefit

It would be easier for users to install mmods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/4939, https://github.com/MultiMC/Launcher/issues/4629 and probably 20 or so closed issues

**Comment by rebokdev** [comment]
> #4939, #4629 and probably 20 or so closed issues

That are not the same issues

**Comment by Primitive-Human** [comment]
Automatic downloads of mods, whether they're dependencies or not, counts as a similar issue. 

Just read the mod page to see which dependencies are required, and download those.
