### ISSUE TITLE
Multimc is crashing BloodNBones modpack with CRITICAL TAMPERING WITH MINECRAFT error

### ISSUE THREAD

**Issue by captinwill** [MultiMC/Launcher#5049]
### Operating System

Windows

### Description of bug

Whenever I try to launch BloodNBones with Multimc, it crashes.

### Steps to reproduce

1. Get BloodNBones
2. Launch it
3. Crash

### Suspected cause

Multimc

https://paste.ee/p/UNl76

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
try adding `-Dfml.ignoreInvalidMinecraftCertificates=true` to your java arguments

**Comment by captinwill** [comment]
it worked thanks
