### ISSUE TITLE
Multimc doesn't start after update

### ISSUE THREAD

**Issue by AdamSacha** [MultiMC/Launcher#5050]
### Operating System

Linux

### Description of bug

Running multimc from terminal reads:
`/usr/bin/multimc: line 25: ./MultiMC: Permission denied`

sudo doesn't work:
`This program should not be run using sudo or as the root user!`

I've built using this tutorial:
https://github.com/MultiMC/multimc-pkgbuild

### Steps to reproduce

In terminal:

* git clone https://github.com/MultiMC/multimc-pkgbuild.git
* cd multimc-pkgbuild
* makepkg -si
* multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
output of `ls -lsa /usr/bin/multimc` and `id`

**Comment by AdamSacha** [comment]
ls -lsa /usr/bin/multimc
`0 lrwxrwxrwx 1 root root 19 Feb  4 10:17 /usr/bin/multimc -> /opt/multimc/run.sh`

id
`uid=1000(adam) gid=1000(adam) groups=1000(adam),998(wheel)`

**Comment by phit** [comment]
and `ls -lsa /opt/multimc/run.sh` ?

**Comment by AdamSacha** [comment]
`4 -rwxr-xr-x 1 root root 729 Feb  4 10:17 /opt/multimc/run.sh`

**Comment by phit** [comment]
that just leaves your system somehow messing up the deploy

try `chmod +x ~/.local/share/multimc/MultiMC`

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.

**Comment by phit** [comment]
If you installed an unofficial package before and are facing this, this will overwrite any weird things left behind with the official package..

```bash
cd ~/.local/share/multimc
wget https://files.multimc.org/downloads/mmc-develop-lin64.tar.gz
tar -xzf mmc-develop-lin64.tar.gz --transform='s,MultiMC/,,'
rm mmc-develop-lin64.tar.gz
chmod +x MultiMC
```

thanks to vovaska for helping figure out what a bad unofficial package leaves behind
