### ISSUE TITLE
Launcher is completely broken!

### ISSUE THREAD

**Issue by imnotadev-ineedhelp** [MultiMC/Launcher#5051]
### Operating System

Windows

### Description of bug

I updated my multimc few minutes ago. After that I launched the multimc then, I found my instance and account is missing from the launcher. So I clicked in the settings, just clicked it and closed it nothing touched and my instance showed up. Then I added my Microsoft account, and tried to launch the instance but it didn't ran and imminently showed the log. So, I restarted the multimc, again my account and instance was gone, again I cliched and closed settings, instance showed up again. Nothing changed even after I clean installed everything :(
Sadly I didn't recorded the logs :(

### Steps to reproduce

* press the settings button
* then close the settings window

and I tried to install it 2 time same result :(

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
without logs we can't really help you, whats the path of your multimc?

**Comment by ghost** [comment]
maybe try to uninstall and reinstall????

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
