### ISSUE TITLE
Add option to close on minecraft launch

### ISSUE THREAD

**Issue by andreasdc** [MultiMC/Launcher#5054]
### Role

-

### Suggestion

-

### Benefit

-

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

You could add option to close the launcher on minecraft launch, it will make things easier.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/3406
