### ISSUE TITLE
XSTS authentication

### ISSUE THREAD

**Issue by RedGamer12v** [MultiMC/Launcher#5061]
### Description of bug

I'm trying to add a Microsoft account, but I get an XSTS authentication error. How do I do that?

### Steps to reproduce

?

### Suspected cause

?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
can you login at minecraft.net and xbox.com?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
