### ISSUE TITLE
Game crashes on startup, Minecraft is just a white screen

### ISSUE THREAD

**Issue by AivenR** [MultiMC/Launcher#5062]
### Operating System

Windows

### Description of bug

Playing 1.19.2 All the Mods 8 and Minecraft crashes on launch
Note: I am using Java 17
https://paste.ee/p/zwUNQ#s=0 

### Steps to reproduce

Launch ATM8 with Java 17

### Suspected cause

Wrong Java Edition is the cause for other crashes like this

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
