### ISSUE TITLE
MultiMC completely broken on Ubuntu 22.10

### ISSUE THREAD

**Issue by Jrdnkasparek** [MultiMC/Launcher#5064]
### Operating System

Linux

### Description of bug

MultiMC won't launch vanilla Minecraft anymore, I have reinstalled MultiMC, reinstalled Java 17.0.6, it just won't even try. Log here: https://paste.ee/p/c8H5B (from MultiMC upload)

Can't add any instance from Technic just gives error seen here:

![Screenshot from 2023-02-09 10-51-01](https://user-images.githubusercontent.com/20908630/217866086-33e0a69a-676a-49d1-9d76-7142210a1a75.png)

### Steps to reproduce

Try to launch vanilla instance

Try to add instance from Technic

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Jrdnkasparek** [comment]
Also Java test returns fine
![Screenshot from 2023-02-09 10-59-38](https://user-images.githubusercontent.com/20908630/217866950-57a50430-a57b-45c3-91ae-52cbeca1b5d0.png)

**Comment by phit** [comment]
disable system glfw and openal in the settings

**Comment by Jrdnkasparek** [comment]
> disable system glfw and openal in the settings

Those are not even enabled

**Comment by phit** [comment]
they are, its in your log

> Using system OpenAL.
> Using system GLFW.

**Comment by Jrdnkasparek** [comment]
Oh interesting, global it was on but instance I had it turned off. weird, thank you!
