### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by ZombieStebo** [MultiMC/Launcher#5065]
### Operating System
Windows 11

### Description of bug

Whenever I start the game there is no sound at all It works on the normal mc launcher just not multimc its only on the alpha versions

### Steps to reproduce

I dont know launch alpha minecraft

### Suspected cause

When I look in the console or whatever it says Sound Shutting down

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/4849
