### ISSUE TITLE
Instance update failed because: Failed to download assets

### ISSUE THREAD

**Issue by AriOwO** [MultiMC/Launcher#5067]
cant launched 1.18 or higher verson 

MultiMC version: 0.7.0-3714

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.227.55.57, 13.227.55.35, 13.227.55.64, 13.227.55.63]

session.minecraft.net resolves to:
    [18.214.12.3, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.107.237.39, 13.107.238.39]

api.mojang.com resolves to:
    [13.224.167.75, 13.224.167.60, 13.224.167.80, 13.224.167.52]

Minecraft folder is:
C:/Users/Home/Downloads/MultiMC/instances/1.19.3/.minecraft

Java path is:
C:/Program Files (x86)/java/zulu17.40.19-ca-jdk17.0.6-win_x64/bin/javaw.exe

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Azul Systems, Inc..

Instance update failed because: Failed to download assets:
Job 'Assets for 2' failed to process:
https://resources.download.minecraft.net/5d/5dd32ce63e2ff412c0c1009255e944fae80b03b0
https://resources.download.minecraft.net/86/868c7a7c4d9358d631fa2f9abfc6bbf05d88292d
https://resources.download.minecraft.net/aa/aa1d3aace1c481ac32d5827fba287294b6bc99fb

**Comment by phit** [comment]
this is a mojang issue, please follow this ticket for more info https://bugs.mojang.com/browse/MCL-23025
