### ISSUE TITLE
Optifine crashes on 1.12.2

### ISSUE THREAD

**Issue by LeWolfYT** [MultiMC/Launcher#5068]
### Operating System

macOS

### Description of bug

Whenever I launch Forge (i've tried a few versions) it crashes with this error:

```2023-02-10 20:02:14.352 java[52418:2850566] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff8034f47b3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff803254bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff80351d066 -[NSException raise] + 9
	3   AppKit                              0x00007ff805ede2f4 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff805f058fb -[NSThemeFrame setStyleMask:] + 162
	5   AppKit                              0x00007ff805f0570b __25-[NSWindow setStyleMask:]_block_invoke + 2092
	6   AppKit                              0x00007ff805f04e87 NSPerformVisuallyAtomicChange + 132
	7   AppKit                              0x00007ff805f04d94 -[NSWindow setStyleMask:] + 170
	8   liblwjgl.dylib                      0x000000012c263cca Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 90
	9   ???                                 0x00000001132436c7 0x0 + 4616107719
	10  ???                                 0x00000001132332bd 0x0 + 4616041149
)
libc++abi: terminating with uncaught exception of type NSException
```

Not sure if this is a MultiMC bug, but I'm pretty sure it is, since the bug never happens on the vanilla launcher.

### Steps to reproduce

1. Create a 1.12.2 forge instance
2. Install Optifine G5/F5 (the only versions i tested)
3. Launch it with Optifine enabled
4. App appears in dock until it crashes.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
gonna need a proper full log, and the java version being used

**Comment by LeWolfYT** [comment]
Java 1.8.0_333
Logs (with optifine 1.12.2 F5)
[latest.log](https://github.com/MultiMC/Launcher/files/10713911/latest.log)

**Comment by phit** [comment]
that log has no crash, need the debug log 

easiest is to just run the game and then click the upload log button in the gui after the crash happens

![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by LeWolfYT** [comment]
https://paste.ee/p/tVoJP

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Java-on-macOS
