### ISSUE TITLE
icons for folders, settings, etc. are too big with "Simple" icon pack

### ISSUE THREAD

**Issue by Survivalcraftfreak** [MultiMC/Launcher#5069]
![image](https://user-images.githubusercontent.com/25420132/218231973-1f13df59-5e8e-4b18-983c-5638485f996b.png)
problem persists in full window mode. 
Tried on both a 21:9 Ultrawide 2560x1080 monitor and a 16:9 1920x1080 monitor.

**Comment by phit** [comment]
use this version https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip for better scaling support
