### ISSUE TITLE
MultiMC fails to load versions 17w43a+

### ISSUE THREAD

**Issue by TheFarlandsExplorer15** [MultiMC/Launcher#5070]
### Operating System

Windows

### Description of bug

MultiMC _fails to add the following librarys:
[oshi-project.zip](https://github.com/MultiMC/Launcher/files/10714856/oshi-project.zip)
[io.zip](https://github.com/MultiMC/Launcher/files/10714858/io.zip)
[commons-io.zip](https://github.com/MultiMC/Launcher/files/10714859/commons-io.zip)
[java3d.zip](https://github.com/MultiMC/Launcher/files/10714860/java3d.zip)
[tv.zip](https://github.com/MultiMC/Launcher/files/10714861/tv.zip)
[net.zip](https://github.com/MultiMC/Launcher/files/10714862/net.zip)
[lzma.zip](https://github.com/MultiMC/Launcher/files/10714863/lzma.zip)
[argo.zip](https://github.com/MultiMC/Launcher/files/10714864/argo.zip)
Now, this only works for Minecraft 17w43a and newer.
I believe it's because of the _size of the versions.
Please fix this, because I'm not able to mod 17w43a+ using .zip files!

### Steps to reproduce

Create instance 17w43a and newer and try to play the game.

### Suspected cause

I think it's because of the size of the files.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what? please provide a log with your issue, I have no idea what you are trying to tell us

**Comment by ghost** [comment]
maybe because you need java 17+ to run the newer games?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
