### ISSUE TITLE
Minecraft Forge 1.8.9 not launching

### ISSUE THREAD

**Issue by EdensWanderer** [MultiMC/Launcher#5071]
### Description of bug

Minecraft doesn't launch at all, log files shows me this;
[latest.log](https://github.com/MultiMC/Launcher/files/10716666/latest.log)
while MultiMC logs show me this
https://paste.ee/p/03j63
PS:  im using my brother's pc to launch minecraft, so I'm not sure about java vers

### Steps to reproduce

no idea, just made a new instance with 1.8.9 for the first time and the issue started

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
