### ISSUE TITLE
normal game instance wont open

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5073]
### Operating System 

Windows 11

### Description of bug

When I clicked launched it gave me error code -1

### Steps to reproduce

java: C:/Program Files/Java/jre1.8.0_361/bin/javaw.exe

so i made a instance rd-20090515

then clicked l launch and it did not work

console:

"MultiMC version: 0.7.0-3714

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.67.28.55, 18.67.28.46, 18.67.28.47, 18.67.28.38]

session.minecraft.net resolves to:
    [18.214.12.3, 100.24.172.95, 34.197.32.8]

textures.minecraft.net resolves to:
    [13.107.237.38, 13.107.238.38]

api.mojang.com resolves to:
    [18.67.39.54, 18.67.39.127, 18.67.39.22, 18.67.39.61]

Minecraft folder is:
C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/instances/rd-20090515/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_361/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_361, using 64-bit architecture, from Oracle Corporation.

Main Class:
  com.mojang.rubydung.RubyDung

Native path:
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/instances/rd-20090515/natives

Traits:
traits no-texturepacks

Libraries:
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/rd-20090515/minecraft-rd-20090515-client.jar

Native libraries:
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/seeon/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 14280

Using onesix launcher.

Failed to find Minecraft main class:
java.lang.ClassNotFoundException: com.mojang.rubydung.RubyDung
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:188)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code."

### Suspected cause

I clicked replaced jar and replaced it and it worked maybe the jar?????????
all my other versions after and before it work and i made the instance again and it still did not work

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Epicers** [comment]
btw my operating system is windows

**Comment by CeruleanFox** [comment]
I got the same error but I'm using a mod from curseforge. Can someone fix plz?
