### ISSUE TITLE
FTB list dont show up

### ISSUE THREAD

**Issue by RW2001** [MultiMC/Launcher#5076]
### Description of bug

cant create instance with ftb pack, nothing appear

### Steps to reproduce

version 0.7.0-3714 develop

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
it will show up once you install any packs in the ftb app

**Comment by RW2001** [comment]
> it will show up once you install any packs in the ftb app

i need install ftb app ?

**Comment by phit** [comment]
yes

**Comment by RW2001** [comment]
> yes

didnt work for me :(

**Comment by phit** [comment]
what pack did you install in the FTB App?

**Comment by RW2001** [comment]
> what pack did you install in the FTB App?

direwolf20 1.16.5

**Comment by phit** [comment]
did you try restarting multimc after installing the pack in the FTB App?

**Comment by RW2001** [comment]
> 

now show up) thank you
