### ISSUE TITLE
Fullscreen cropping weird

### ISSUE THREAD

**Issue by sweatygorilla2** [MultiMC/Launcher#5079]
### Operating System

Windows

### Description of bug

I am trying to play minecraft 1.7.10 and when i enter full screen the cropping is all weird and the screen is centered towards the side, i went in the latest version of minecraft and it worked fine. I dont know if this is actually a bug or what but i would like help.

### Steps to reproduce

i dont really know what to put here

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please upload your 1.7.10 log

![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
