### ISSUE TITLE
Shortcuts run builds

### ISSUE THREAD

**Issue by saanjkz** [MultiMC/Launcher#5080]
### Role

For a quick game

### Suggestion

Added assembly shortcuts to the desktop as desired

### Benefit

This helps players launch their favorite builds faster by bypassing the launcher.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

// Shortcuts will help them launch their favorite builds faster by bypassing the launcher entrance

**Comment by phit** [comment]
already exists, use the create shortcut button on an instance
