### ISSUE TITLE
OneSix Modpack Failure

### ISSUE THREAD

**Issue by usernames122** [MultiMC/Launcher#5081]
### Description of bug

When i launch FTB Presents Stoneblock 2, either in offline mode or normal, Onesix fails with a error.

### Steps to reproduce

- Set java to JDK 19 or similar.
- Try to start the modpack.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
