### ISSUE TITLE
Unable to open Minecraft as process exited with code -1

### ISSUE THREAD

**Issue by UltraGodsMC** [MultiMC/Launcher#5082]
### Operating System

Windows

### Description of bug

I keep trying to open the instance and it shows that mc opened and then it instantly closes.
[crash-2023-02-18_16.46.08-client.txt](https://github.com/MultiMC/Launcher/files/10773977/crash-2023-02-18_16.46.08-client.txt)

### Steps to reproduce

This keeps happening whenever i launch and the moment mc opens.

### Suspected cause

No idea how happen.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
