### ISSUE TITLE
minecraft window open bug

### ISSUE THREAD

**Issue by yakla** [MultiMC/Launcher#5083]
### Description of bug

I this bug before in the bug reports but i have new info the bug is that if your are setting size the screen in the windows setting to more or less then 100% that it set to 150% automaticly in laptops the lancher is opening the minecraft window on the side and not on the center

### Steps to reproduce

i know what the cause of it its i dont realy sure that is conected to the lancher 

### Suspected cause

 if your are setting size the screen in the windows setting to more or less then 100% that it set to 150% automaticly in laptops

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hazelwood-dal** [comment]
I just updated and now am having this issue as well. The current fix is to go into settings and change my scale layout from 250% to 100% to turn off full screen then I change my scale back to 250% and play the game out of full screen. I am on a Dell Inspiron 17 7000 2-in-1 Series Running Windows 10.

**Comment by phit** [comment]
please try this build https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip
