### ISSUE TITLE
xbox user authentication failed

### ISSUE THREAD

**Issue by Frxgxd** [MultiMC/Launcher#5084]
### Operating System

mac 

### Description of the bug

when I try to add an account to multi MC it says Xbox user authentication failed

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please fill out the issue form correctly. There is not enough information provided here for anyone to help you.
