### ISSUE TITLE
Can't Record With Shadowplay

### ISSUE THREAD

**Issue by Simiea** [MultiMC/Launcher#5089]
### Description of bug

I can never record any multimc instance with Nvidia Shadowplay. Does anyone know how to fix this

### Steps to reproduce

I don't know why this happens

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Hans5958** [comment]
I can't reproduce it. Recording and instant replay with NVIDIA ShadowPlay works in my end.
