### ISSUE TITLE
Option to launch MC in undecorated window

### ISSUE THREAD

**Issue by mk-pmb** [MultiMC/Launcher#5091]
### Role

I play a mostly-vanilla sodium + iris pack.

### Suggestion

I'd like to have an option to launch the Minecraft window undecorated, or have the window decorations be removed once the window has been opened.

### Benefit

No pixels wasted for the Minecraft window title but my dock and other apps are still displayed as usual.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know I can undecorate any window with devilspie or a small python script, but I think we should offer this option in a noob-friendly way. There also seem to be Minecraft mods to tweak the window from inside Java, but mods tend to become incompatible over time.

**Comment by phit** [comment]
Please elaborate how MultiMC could do this cross platform without modifying the game.

**Comment by mk-pmb** [comment]
I have no real idea how we should go about implementing this. It will probably be OS-specific.

Maybe we can figure out what mechanism Java uses to set up the Minecraft window, and inject a wrapper library into the class path that overloads that function with a proxy. My hope is that Java's window management interface API changes waaaaaay less frequently than MC game APIs, so a proxy would be more stable than game-specific mods.

For most Linux window managers, it would probably be a few calls to GTK. [This python snippet](https://gist.github.com/unhammer/1815146) floats around as an example, however some people wrote that they had trouble making the python GTK package work. Therefor we should probably evade Python and do it directly from C(++).

Another favorite of web forums is a long C snippet that sets Motif window hints, and a short command line that does the same with native tools (xprop) out of the box. However my favorite WM (xfce) doesn't understand Motif hints so meh.

There's a tool devilspie that can undecorate windows but its lisp-like config language seems overly complicated for such a simple task, similar with devilspie2 which uses LUA.

Back in the days when I used windows, I had "12ghosts" as a suite of 12 utilities to tweak lots of stuff. One was for various window placement and behavior, so it could probably have undecorated them as well. We could trace it to see what the relevant calls are.

From what I read in forums, MacOS seems to undecorate maximized windows by default, so those users probably won't need help.

**Comment by phit** [comment]
Well as you already described this is quite complicated and a possible maintenance burden, as such this will be better served by a mod. e.g. https://www.curseforge.com/minecraft/mc-mods/borderless https://www.curseforge.com/minecraft/mc-mods/borderless-mining
