### ISSUE TITLE
ive tried all i can think

### ISSUE THREAD

**Issue by austinofficia** [MultiMC/Launcher#5092]
### Operating System

Linux

### Description of bug

console error in link. I tried going through and installing anything "missing"  but it does not change anything. I tried changing settings and allocating more memory. If anyone has suggestions. Also it does not launch at all so i dont believe theirs a crash log. vanilla no mods,  or texture packs.
https://paste.ee/p/vZVcC

### Steps to reproduce

- launch minecraft 1.19 from multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong java version?

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by phit** [comment]
update your OS, Minecraft needs a newer libc
