### ISSUE TITLE
Day/year check for age lock/ change age lock to 13 years old to match microsoft

### ISSUE THREAD

**Issue by Pikachufan234** [MultiMC/Launcher#5096]
### Role

I believe it needs this because even though I am 13, it says I am too young whenever I have to sign in again.

### Suggestion

I want MultiMC to 1. Change the age lock to 13 and up and 2. Check the Internet every day to update the age lock

### Benefit

So that teens can sign into MultiMC with out changing their Microsoft account.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
none of this is related to multimc, the account system is all microsoft and we can't do anything about it
