### ISSUE TITLE
Assign Java version independantly

### ISSUE THREAD

**Issue by FSFan** [MultiMC/Launcher#5097]
### Role

I still play some older packs/mods that require version 8 of Java

### Suggestion

A  "per modpack install" choice to launch a specific version of Java

### Benefit

I have to do it manually every time now

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
already exists? go to the instance settings
