### ISSUE TITLE
-1 Error code

### ISSUE THREAD

**Issue by ninjatwinkie1** [MultiMC/Launcher#5098]
### Operating System

Windows 10

### Description of bug

I opened minecraft both online and offline and it crashed
Offline log- https://paste.ee/p/5PdQf
Online log- https://paste.ee/p/x9gWI
### Steps to reproduce

I open minecraft and it has a huge lag spike and then crashes a couple seconds after the lag settles

### Suspected cause

14.4 GB free in storage

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
