### ISSUE TITLE
Minecraft 1.12.2 Modded - Unable to extract native files

### ISSUE THREAD

**Issue by Willyrwyu5** [MultiMC/Launcher#5099]
### Description of bug

I made a modpack, and I was trying to start it, and this came up?
Unable to extract native files.
Error details: Minizip error while extracting: -111
Filename on disk: lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
Path: C:\Users\willj\curseforge\minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
Exists: File

### Steps to reproduce

.

### Suspected cause

I am not sure what made this bug.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
that path or log doesn't even look like multimc?
