### ISSUE TITLE
Graphic issue

### ISSUE THREAD

**Issue by Storpyn** [MultiMC/Launcher#5103]
### Operating System

Windows

### Description of bug

Im playing version 1.8.9 (it doesnt happen on other versions) on the Hypixel server with few mods, and once i enter Crystal hollows after 5-20 minutes this error occurs. After that wherever i teleport it stays and i have to restart the game. If i continue playing, multiMC crashes with message
 ""System exit code name: STATUS_ACCESS_VIOLATION""   Process crashed with exitcode -1073741819 (0xffffffffc0000005).

I removed all mods, started new instance, tweaked amd performance settings, completed tips from 1-6 on this website https://www.makeuseof.com/amd-driver-timeout-tdr-windows/
and it still happens. Im really hopeless atm and figured it might be problem with the client, any help?
![1679492615324](https://user-images.githubusercontent.com/84386619/227614533-5f380992-e472-41a5-b09f-ada61c714dbd.png)

### Steps to reproduce

1.8.9

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game  you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Storpyn** [comment]
What do i make of the crash code then?
