### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Storpyn** [MultiMC/Launcher#5105]
### Description of bug

Game fails to load chunks, then crashes with message saying "out of memory" "not enough allocated memory" 
but when i allocate more memore in the instance settings, the whole computer RAM is used up and it still keeps crashing with the same message. I have 6400 MiB allocated right now

### Steps to reproduce

1.8.9

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
