### ISSUE TITLE
Graphic issue

### ISSUE THREAD

**Issue by Storpyn** [MultiMC/Launcher#5106]
### Operating System

Windows 10

### Description of bug

Once i enter crystal hollows on hypixel server version 1.8.9 after 5-20 minutes of playing screen starts twitching with colorful shards, and then the game crashes with message:
https://paste.ee/p/6R3fB
 What does the message mean? and how should i solve it

### Steps to reproduce

After the bug appears, it cant be resolved by teleporting to other area or lobby, i have to restart the game before it crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
