### ISSUE TITLE
Not enought memory allocation

### ISSUE THREAD

**Issue by TheFarlandsExplorer15** [MultiMC/Launcher#5107]
### Description of bug

Minecraft can't allocate enough memory in b1.7.3 even though I do have enough memory.

### Steps to reproduce

Install OPENJDK-21-ea-13.

### Suspected cause

Here's the log

=====### LOG#=====

There is insufficient memory for the Java Runtime Environment to continue.
 Native memory allocation (mmap) failed to map 91226112 bytes for G1 virtual space
Possible reasons:
   The system is out of physical RAM or swap space
   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
Possible solutions:
   Reduce memory load on the system
   Increase physical memory or swap space
  Check if swap backing store is full
   Decrease Java heap size (-Xmx/-Xms)
  Decrease number of Java threads
  Decrease Java thread stack sizes (-Xss)
  Set larger code cache with -XX:ReservedCodeCacheSize=
   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
     placed in the first 4GB address space. The Java Heap base address is the
     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
    to set the Java Heap base and to place the Java Heap above 4GB virtual address.
 This output file may be truncated or incomplete.

  Out of Memory Error (os_windows.cpp:3593), pid=5364, tid=14908

 JRE version: OpenJDK Runtime Environment (21.0+13) (build 21-ea+13-1060)
 Java VM: OpenJDK 64-Bit Server VM (21-ea+13-1060, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
No core dump will be written. Minidumps are not enabled by default on client versions of Windows

---------------  S U M M A R Y ------------

Command Line: -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx2048m -Duser.language=en -Djava.library.path=C:/Users/super/Downloads/mmc-develop-win32/MultiMC/Versions/b1.7.3/natives org.multimc.EntryPoint

Host: AMD Ryzen 5 6600H with Radeon Graphics         , 12 cores, 7G,  Windows 11 , 64 bit Build 22621 (10.0.22621.1344)
Time: Sat Mar 25 11:55:05 2023 Eastern Daylight Time elapsed time: 544.735490 seconds (0d 0h 9m 4s)

---------------  T H R E A D  ---------------

Current thread (0x0000026122c3b380):  VMThread "VM Thread" [stack: 0x00000061db000000,0x00000061db100000] [id=14908]

Stack: [0x00000061db000000,0x00000061db100000]
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x6b1aba]
V  [jvm.dll+0x83b0aa]
V  [jvm.dll+0x83cc2e]
V  [jvm.dll+0x83d303]
V  [jvm.dll+0x27d4a1]
V  [jvm.dll+0x6ae689]
V  [jvm.dll+0x6a325a]
V  [jvm.dll+0x353433]
V  [jvm.dll+0x35b036]
V  [jvm.dll+0x3a998e]
V  [jvm.dll+0x3a9be8]
V  [jvm.dll+0x325e6a]
V  [jvm.dll+0x328936]
V  [jvm.dll+0x33293e]
V  [jvm.dll+0x3698ea]
V  [jvm.dll+0x842cce]
V  [jvm.dll+0x843de1]
V  [jvm.dll+0x8442d0]
V  [jvm.dll+0x844573]
V  [jvm.dll+0x7e3706]
V  [jvm.dll+0x6b06eb]
C  [ucrtbase.dll+0x29363]
C  [KERNEL32.DLL+0x126bd]
C  [ntdll.dll+0x5a9f8]

VM_Operation (0x00000061dacff840): G1PauseRemark, mode: safepoint, requested by thread 0x00000261061da790

---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00000261551a90a0, length=21, elements={
0x0000026122c57540, 0x0000026122c5a6a0, 0x0000026122c5d6e0, 0x0000026122c5e7e0,
0x0000026122c5f120, 0x0000026122c5fa60, 0x0000026122c6ac30, 0x0000026122c79370,
0x00000261271369c0, 0x000002612713b790, 0x000002612736b3b0, 0x000002612736e3c0,
0x00000261273718c0, 0x0000026128427350, 0x000002612845b360, 0x0000026128528190,
0x00000261284b7640, 0x00000261031c0120, 0x000002612851c650, 0x000002612851d0f0,
0x000002612851d640
}

Java Threads: ( => current thread )
  0x0000026122c57540 JavaThread "Reference Handler" daemon [_thread_blocked, id=17648, stack(0x00000061db100000,0x00000061db200000)]
  0x0000026122c5a6a0 JavaThread "Finalizer" daemon [_thread_blocked, id=29636, stack(0x00000061db200000,0x00000061db300000)]
  0x0000026122c5d6e0 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=29472, stack(0x00000061db300000,0x00000061db400000)]
  0x0000026122c5e7e0 JavaThread "Attach Listener" daemon [_thread_blocked, id=31004, stack(0x00000061db400000,0x00000061db500000)]
  0x0000026122c5f120 JavaThread "Service Thread" daemon [_thread_blocked, id=2332, stack(0x00000061db500000,0x00000061db600000)]
  0x0000026122c5fa60 JavaThread "Monitor Deflation Thread" daemon [_thread_blocked, id=10168, stack(0x00000061db600000,0x00000061db700000)]
  0x0000026122c6ac30 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=4868, stack(0x00000061db700000,0x00000061db800000)]
  0x0000026122c79370 JavaThread "C1 CompilerThread0" daemon [_thread_blocked, id=1616, stack(0x00000061db800000,0x00000061db900000)]
  0x00000261271369c0 JavaThread "Notification Thread" daemon [_thread_blocked, id=27308, stack(0x00000061db900000,0x00000061dba00000)]
  0x000002612713b790 JavaThread "Common-Cleaner" daemon [_thread_blocked, id=10016, stack(0x00000061dbb00000,0x00000061dbc00000)]
  0x000002612736b3b0 JavaThread "Java2D Disposer" daemon [_thread_blocked, id=20392, stack(0x00000061dbc00000,0x00000061dbd00000)]
  0x000002612736e3c0 JavaThread "AWT-Shutdown" [_thread_blocked, id=15192, stack(0x00000061dbd00000,0x00000061dbe00000)]
  0x00000261273718c0 JavaThread "AWT-Windows" daemon [_thread_blocked, id=6132, stack(0x00000061dbe00000,0x00000061dbf00000)]
  0x0000026128427350 JavaThread "AWT-EventQueue-0" [_thread_blocked, id=19676, stack(0x00000061dcb00000,0x00000061dcc00000)]
  0x000002612845b360 JavaThread "D3D Screen Updater" daemon [_thread_blocked, id=30016, stack(0x00000061dcc00000,0x00000061dcd00000)]
  0x0000026128528190 JavaThread "Timer hack thread" daemon [_thread_blocked, id=2212, stack(0x00000061dcd00000,0x00000061dce00000)]
  0x00000261284b7640 JavaThread "Minecraft main thread" [_thread_blocked, id=7332, stack(0x00000061dce00000,0x00000061dcf00000)]
  0x00000261031c0120 JavaThread "DestroyJavaVM" [_thread_blocked, id=9508, .............
END

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheFarlandsExplorer15** [comment]
TOO LONG

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
