### ISSUE TITLE
can't install the Rlcraft pack

### ISSUE THREAD

**Issue by ananthashesha3000** [MultiMC/Launcher#5109]
### Description of bug

I was trying to get the hardcore config to work, so, in foolishness, I deleted the Rlcraft instance. However, once I tried to reinstall it, it said, after a while: Failed to commit instance, even after multiple retries. It is being blocked by something.
 I tried to do it again but to no avail. Please help.

### Steps to reproduce

1. install Rlcraft
2. add optifine to the mods file
3. add and open the hardcore config .zip pack in the instance folder
4. delete the instance

### Suspected cause

Since I had modified the modpack before deletion (I installed optifine and, of course, the hardcore config pack), maybe something about the bug has to do with a problem caused by this. Also, the multimc version was multimc 5, and I downloaded optifine from their official website, and the hardcore pack form the curseforge website

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
close all programs that are using files in said instance, worst case reboot your pc, multimc cant do anything about files being locked externally
