### ISSUE TITLE
Inconsistencies with skins 

### ISSUE THREAD

**Issue by SamiTheAnxiousBean** [MultiMC/Launcher#5110]
### Operating System

Windows

### Description of bug

Your skin can not display under certain conditions

- Playing on a locally hosted server
- Playing on a server with support for offline/cracked clients (unlike the default client which would load your skin in this condition to both you and other players)
- Playing singleplayer (inconsistent with launch of instance, most of the time works though)

### Steps to reproduce

This bug can be reproduced by running a mojang account on:
- a local server
- a server with support for offline/cracked clients
- Playing singleplayer (inconsistent with launch of instance, repeated back to back launches likely needed)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the skin is loaded by the game, not multimc

**Comment by SamiTheAnxiousBean** [comment]
I assumed so myself, however I tested it under the same conditions with the
default launcher right after noticing the bug as a part of troubleshooting
and it loaded it fine, then switching to multimc under the same
circumstances didn't so I decided to report it
