### ISSUE TITLE
"Restart MultiMC" button

### ISSUE THREAD

**Issue by kaz-49** [MultiMC/Launcher#5111]
A new feature to make dealing with "Invalid session: Try restarting the game and launcher" easier. 

I like to close the folder that I have MultiMC in once i have Minecraft started, and whenever the invalid session error comes up it's inconvenient to have to open the folder again. So, I reckon a button to restart MultiMC in the top right of the main GUI, just to the left of the account selector might be a nice quality-of-life feature. 

The option to hide that button might also be nice for those who just have a shortcut to their their favourite instance on the desktop and don't want to accidentally click it I guess ¯\\\_(ツ)_/¯

**Comment by phit** [comment]
you dont have to restart multimc, relaunching the game is enough, alternatively open the profile screen and click refresh
