### ISSUE TITLE
MultiMC doesn't see or download more current versions of Vanilla?

### ISSUE THREAD

**Issue by jdiamondGitHub** [MultiMC/Launcher#5115]
### Description of bug

I expected previous behavior, in which when I create a new vanilla instance, in the version choices, it will show the later versions of minecraft.  If not, certainly after I click on the Refresh Button.

For context, I'm running on a 2021 M1 Max with MacOS Monterey.  The issue is I can't play games that connect to external servers like Realms until I get to a minimum of 1.19.4.

### Steps to reproduce

It may be hard to quickly reproduce, because I'm assuming that when you first install a fresh MultiMC it will download all the versions up to the latest one.  Then you have to wait until a newer release comes out and try to get it on MultiMC.  Which is in itself a possible way to fix the bug, but I have a complex MultiMC setup, and so I fear the idea of uninstalling it and reinstalling it.

### Suspected cause

Possible Mojang has changed the protocol that MultiMC used to use to detect and download new vanilla versions?  The last version it can see is 1.19.2.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Sounds like you aren't using MultiMC but some weird unofficial version, please provide your launcher log `MultiMC-0.log` in the launcher folder.

**Comment by jdiamondGitHub** [comment]
My apologies - yes - I'm using the ManyMC port of MultiMC to the Mac.  I was under the impression this was the only way to run MultiMC on the Mac?  Maybe this is of no use, then, but here is my launcher log.

[LauncherLog.txt](https://github.com/MultiMC/Launcher/files/11132763/LauncherLog.txt)

**Comment by phit** [comment]
Yeah thats not MultiMC , its a dead unrelated project. You could always just use MultiMC via Rosetta and download x64 Java.

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by jdiamondGitHub** [comment]
Ah.... thanks for the tip.  :) Here's hoping that at some point MultiMC gets an Apple Silicon Port.  I tried using Rosetta, and sadly, it wasn't really playable.  But are you saying that I could use MultiMC with an ARM native Java version?
NVM, just saw on your link that it's not compatible.

Well, if the ManyMC folks could do the port, then at least it's something that's possible. Thanks for your kind assistance.

**Comment by phit** [comment]
It's planned, just the project has been kinda slow as the main dev has been busy enjoying life and nobody else has stepped up to add support.

**Comment by jdiamondGitHub** [comment]
That's more than fair. :)
