### ISSUE TITLE
Не запускается майнкрафт

### ISSUE THREAD

**Issue by Cat123bat** [MultiMC/Launcher#5118]
### Description of bug

Когда я запускаю майнкрафт через этот лаунчер на любой версии майнкрафта вылезает эта ошибка: MultiMC version: 0.7.0-3732

Launched instance in offline mode

Minecraft folder is:
H:/Games/MultiMC/instances/1.19.4/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.

Main Class:
  

Native path:
  H:/Games/MultiMC/instances/1.19.4/natives

Libraries:

Native libraries:

Params:
  

Window size: 854 x 480

Failed to reconstruct Minecraft assets.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 1172

Using onesix launcher.

Exiting with -1
Not enough arguments.
org.multimc.NotFoundException
	at org.multimc.ParamBucket.all(ParamBucket.java:43)
	at org.multimc.onesix.OneSixLauncher.processParams(OneSixLauncher.java:62)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:240)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Процесс завершён с кодом -1 (0xffffffffffffffff).
Пожалуйста, обратите внимание, что обычно ни кода выхода, ни его описания недостаточно для диагностики проблем!
Всегда загружать весь журнал целиком, а не только код выхода.
Clipboard copy at: 05 Apr 2023 14:47:56 +0400
подскажите пожалуйста что мне делать

### Steps to reproduce

что тут вообще отправлять?

### Suspected cause

Даже не представляю что это может быть

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> Launched instance in offline mode

launch online
