### ISSUE TITLE
Light level is too large

### ISSUE THREAD

**Issue by TheFarlandsExplorer15** [MultiMC/Launcher#5119]
### Operating System

Windows

### Description of bug

When _Minecraft_ has a lot of light loaded (always) MultiMC fails to process all of the light causing a crash due to light corruption.

### Steps to reproduce

1. Load any old beta 1.7.3 or older level.
2. Walk around (or fly) the level for about 10 minutes.
3. When the game freezes, take a look at the log.
4. Finally, find the text which says "light is too large! skipping!".
5. You don't always see the text.

### Suspected cause

MultiMC fails to notice OVER 1,000,000 light updates.

Here's the log:

MultiMC version: 0.7.0-3732

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.225.59.51, 13.225.59.36, 13.225.59.63, 13.225.59.42]

session.minecraft.net resolves to:
    [13.107.238.40, 13.107.237.40]

textures.minecraft.net resolves to:
    [13.107.237.40, 13.107.238.40]

api.mojang.com resolves to:
    [13.107.237.40, 13.107.238.40]

Minecraft folder is:
C:/Users/super/Downloads/mmc-develop-win32/MultiMC/Versions/b1.2_02/.minecraft

Java path is:
C:/Users/super/Downloads/openjdk-21-16/jdk-21/bin/java.exe

Checking Java version...
Java is version 21-ea, using 64-bit architecture, from Oracle Corporation.

Main Class:
  

Native path:
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/Versions/b1.2_02/natives

Traits:
traits texturepacks
traits legacyLaunch

Using system OpenAL.
Using system GLFW.

Libraries:
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/Versions/b1.2_02/.minecraft/bin/minecraft.jar

Native libraries:
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/super/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Jar Mods:

Params:
  

Window size: max (if available)

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms128m, -Xmx2048m, -Duser.language=en]

Minecraft process ID: 30520

Using onesix launcher.

Launching with applet wrapper...
28
Setting user: SFusbass, token:<ACCESS TOKEN>:<PROFILE ID>
Fuck you options
Apr 05, 2023 9:56:13 AM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 11
Apr 05, 2023 9:56:13 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Apr 05, 2023 9:56:13 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Apr 05, 2023 9:56:13 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to initialize device HIDI2C Device because of: java.io.IOException: Failed to acquire device (8007001e)

Apr 05, 2023 9:56:13 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to initialize device ITE Device(8176) because of: java.io.IOException: Failed to acquire device (8007001e)

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add pack.mcmeta
Failed to add READ_ME_I_AM_VERY_IMPORTANT
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:578)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:181)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1657)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at java.base/java.net.URL.openStream(URL.java:1317)
	at net.minecraft.src.ThreadDownloadResources.run(ThreadDownloadResources.java:39)
Player is null
Player is null
Player is now null
176 recipes
Loading texture http://s3.amazonaws.com/MinecraftSkins/SFusbass.png
Player count: 1
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
I have no idea what happened, I just bypassed an exception of sorts, heh.
[Full log_5_4_2023.log](https://github.com/MultiMC/Launcher/files/11159790/Full.log_5_4_2023.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
