### ISSUE TITLE
MultiMC not initializing instances

### ISSUE THREAD

**Issue by Hedisus** [MultiMC/Launcher#5123]
I played last night with no issue, but got the following log this morning when I went to play. Nothing changed in settings between 1 instance and the other.

Linux Ubuntu Jammy version 22.04.2 (Debian)

https://paste.ee/p/cgQR8

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Hedisus** [comment]
Turned out to be my OS blocking a protocol it needed to update. I had
thought my restart had fixed it. Sorry
