### ISSUE TITLE
mmc is missing a file

### ISSUE THREAD

**Issue by gumball43** [MultiMC/Launcher#5126]
### Operating System

Windows

### Description of bug

when i try to launch in offline mode it cant find a file. i have no idea what is going wrong.

code that i am getting
[New Paste 1.txt](https://github.com/MultiMC/Launcher/files/11187449/New.Paste.1.txt)

### Steps to reproduce

download the launcher. create instance1.19.2. add mods from all the mods 8 to the instance. add existing world and the .mincraft files. click launch offline get that code error.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to launch online at least once
