### ISSUE TITLE
MultiMC 5 isn't recognizing that I own minecraft and keeps offering a demo even after restarting and logging in again.

### ISSUE THREAD

**Issue by Zeffzee** [MultiMC/Launcher#5127]
### Operating System

Windows

### Description of bug

Whenever I try to launch any version of minecraft it keeps saying I don't own it. I have logged out and in again and restarted the game multiple times but the issue is still there.

I have found similar issues on here already but when I tried the steps to fix it it still showed the issue.

### Steps to reproduce

I don't know how you could recreate this. I just logged in and attempted to play and it showed the error.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
not sure what to tell you, sounds like you are logging in with an account that doesn't own the game, what happens when you login with the same account at minecraft.net ?

**Comment by z5vix** [comment]
can you share the download? cant download it anymore
