### ISSUE TITLE
whenever i launch beta 1.7.3 the screen is just black

### ISSUE THREAD

**Issue by dilusional** [MultiMC/Launcher#5132]
i wanna play 1.7.3 but minecraft gives me like 10 fps so i found some tutorial on how to download optifine but when i try to launch the game on multimc my screen is just black

i can click randomly on the screen and i can hear the button sound but thats it
also when i expand the screen it flashes white and black

please help i am sad

logs:
https://paste.ee/p/SRZzE

the screen:
<img width="856" alt="Screenshot 2023-04-16 at 10 58 33 PM" src="https://user-images.githubusercontent.com/130916479/232321584-681346a0-4772-4762-a7ad-54aa0ea733d1.png">

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by dilusional** [comment]
i did what the website told me to and it's still black

i'm using this java (the one the website told me to download)
<img width="518" alt="Screenshot 2023-04-22 at 9 42 58 PM" src="https://user-images.githubusercontent.com/130916479/233788452-b844d055-c024-45d8-94ef-bdabfe9d8966.png">

**Comment by phit** [comment]
try this one https://github.com/MultiMC/Launcher/wiki/Java-on-macOS

**Comment by dilusional** [comment]
still a no

<img width="861" alt="Screenshot 2023-04-30 at 5 16 05 PM" src="https://user-images.githubusercontent.com/130916479/235345416-ef3ca3e7-c65a-4abe-b3a0-dd014e93f6e0.png">
<img width="237" alt="Screenshot 2023-04-30 at 5 16 13 PM" src="https://user-images.githubusercontent.com/130916479/235345436-85da8f95-a241-4a6e-81b4-b4010a4a685f.png">

**Comment by phit** [comment]
please post your log
![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by dilusional** [comment]
https://paste.ee/p/THoJN

**Comment by dilusional** [comment]
i killed it because it doesn't respond, i've waited like 10+ minutes before and it still doesn't load

**Comment by phit** [comment]
disable Use System OpenAL in the settings and try again

**Comment by dilusional** [comment]
still doesn't work

**Comment by dilusional** [comment]
https://paste.ee/p/qbYVm

**Comment by phit** [comment]
No clue then, you can try an even older Java version this post claims update 232 may work https://github.com/MultiMC/Launcher/issues/3386#issuecomment-710973076, I think the official launcher uses update 74, so googling for `jdk-8u74-macosx-x64.dmg` may help

**Comment by dilusional** [comment]
alr thanks for your help
