### ISSUE TITLE
Unable to link Microsoft account

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [MultiMC/Launcher#5133]
### Operating System

Linux

### Description of bug

The launcher did not respond to logging in to Microsoft when logging in with Github. (It should have)

### Steps to reproduce

* Open MultiMC settings
* "Accounts"
* "Add Microsoft"
* "Copy Code"
* Click the link
* Paste code
* "Next"
* Type email address
* "Next"
* *Redirecting you to GitHub to sign in...*
* *Stay signed in?*
* pick an option
* *Several redirects*
* *Microsoft account page*
* Go back to MultiMC
* nothing changed, except for the progress bar advancing slightly

### Suspected cause

not exactly sure, could be Microsoft auth APIs

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GalaxJann** [comment]
Yeah I have the same bug, when I login, authentication fails in MultiMC

**Comment by HeavnWolf** [comment]
Me too, I got disconnected today (profile expired) and I can't reconnect.

**Comment by hideki2k02** [comment]
It seems Microsoft broke something, this is happening across all MultiMC Forks.

**Comment by phit** [comment]
probably just you being blocked, try logging in on minecraft.net or the official launcher

**Comment by Emilgardis** [comment]
I had the same issue, I think this is a change done somewhere, probably on msofts side.
Opting to not use github for authentication resolved it. So when prompted, press the "Other ways to sign in" link and select another option than Github

Steps to reproduce.
1. Link your github account via https://login.live.com/ > sign-in options > GitHub
2. Add the microsoft account in MultiMC. Make sure when prompted that you use GitHub, use "Other ways to sign in > Github" if its not used.

you're redirected to https://account.microsoft.com, not to the correct oauth screen.

Using another authentication for sign-in solves it.

**Comment by Nihlus** [comment]
I have the same issue. Using another login method works for me as well.

**Comment by Ego-Matthisum** [comment]
I had the same issue.

I had to do the following to make it work:

1. sign-in options > forgot username
2. enter regular e-mail > enter code sent to e-mail
3.  log in normally

That worked for me

**Comment by sarpuser** [comment]
This is an issue on a Mac (Intel) as well. I also cannot seem to login to Microsoft another way besides GitHub. It just does not give me the option. So I cannot authenticate my account on MultiMC. Please fix this. I cannot play at all.
