### ISSUE TITLE
Ubuntu isn't providing libssl1.0-dev anymore, which MultiMC requires on Linux

### ISSUE THREAD

**Issue by Hexcede** [MultiMC/Launcher#5136]
### Operating System

Linux

### Description of bug

MultiMC can't be run on Linux anymore due to not having compatible OpenSSL support anymore. (`libssl1.0-dev` package is no longer provided, building & installing OpenSSL from sources was unsuccessful, other attempts of mine were otherwise unsuccessful)

I also wasn't able to get MultiMC to run after installing OpenSSL 1.0.2g from sources, and I wasn't able to get any useful debug information as to where there is failure, or what I am doing wrong. I cannot find any resources or answers as to how to get MultiMC to run correctly, as I cannot determine how MultiMC is trying to load libraries, or why it is failing to find them.

I can understand if it is infeasible or impossible (e.g. due to other dependencies) to upgrade the OpenSSL dependency, so there should at least be an easily available resource to guide installation of MultiMC on an Ubuntu system.

### Steps to reproduce

- Download the latest version of MultiMC for Linux on Ubuntu Jammy or later.
- Run MultiMC. The news section will not be updated, and accounts cannot be signed into.
- Logs like the one attached below will be generated.

[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/11305552/MultiMC-0.log)

### Suspected cause

MultiMC requires old versions of OpenSSL that can no longer be easily installed on Ubuntu. (See #1930 #1784 etc)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc doesnt require openssl 1, your qt install is just broken, possibly due to a distro upgrade

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
