### ISSUE TITLE
MultiMC will not launch.

### ISSUE THREAD

**Issue by Skyler0x2** [MultiMC/Launcher#5140]
### Operating System

Linux

### Description of bug

Every time I install forge mod(s)  MultiMC refuses to launch the game. 

### Steps to reproduce

1. Create new instance
2. Install forge 1.18.2
3. Download TerraFirmaCraft or any other mod and put into the instance.
4. Under setting tick java installations and change it to java 19 openjdk
5. launch the instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
