### ISSUE TITLE
macOS Ventura "not newer than macOS 10.13+"

### ISSUE THREAD

**Issue by CatsLover2006** [MultiMC/Launcher#5142]
### Operating System

macOS

### Description of bug

![Screenshot 2023-04-30 at 5 28 29 PM](https://user-images.githubusercontent.com/28163018/235380964-d4917a58-ed63-44ed-bc9a-5b5faa294694.png)
Screenshot kinda says it all.

### Steps to reproduce

Try to log in to a Microsoft Account on macOS Ventura. That's kinda it.

### Suspected cause

Maybe macOS Ventura reports 13.4 (in this case) instead of 10.18.4? I'm not 100% sure, maybe someone else can help me out here.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
update your multimc

**Comment by devksingh4** [comment]
I also have this issue - I have confirmed I'm using the latest version of MultiMC

**Comment by phit** [comment]
try upgrading manually then https://files.multimc.org/downloads/mmc-develop-osx64-5.15.2.tar.gz

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
