### ISSUE TITLE
Still not working after try many times for MultiMC (mods not an issue)

### ISSUE THREAD

**Issue by Caseypiano360** [MultiMC/Launcher#5145]
Hi MultiMC,

After I run again, I realized it still crashed. The mods are working fine but once I clicked on the world, it load and later shut it down by itself and it gave me this log as shown in the link:

[https://paste.ee/d/5AKgx](url)

How to solve it?

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
