### ISSUE TITLE
Ability to include disabled mods in .mrpack exports

### ISSUE THREAD

**Issue by kosma** [MultiMC/Launcher#5146]
### Role

Modpack developer

### Suggestion

Have some way to include the *.jar.disabled files in the .mrpack file

### Benefit

I want to be able to ship a modpack with some mods disabled by default, things like Entity Culling or Distant Horizons, to be enabled only by advanced users and save them time to download the mods separately.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

One way to implement this could be to add an "Include all files" option in the ModrinthExportDialog, shifting the responsibility for creating a proper file layout to the user.

Another option could be to use the "optional" flag in metadata, although it doesn't accomplish the exact same thing:
https://docs.modrinth.com/docs/modpacks/format_definition/#env-optional

**Comment by kosma** [comment]
Another option is to allow the user to select any file they want, they way Prism did it:

![image](https://user-images.githubusercontent.com/1089580/236636351-d81f2542-b4d2-4a1e-8af7-38f269660f7b.png)

**Comment by arthomnix** [comment]
Disabling mods by adding `.disabled` is a MultiMC thing, so it's probably best not to use it in a modpack format designed to be used by multiple launchers. MultiMC's Modrinth importer handles optional mods by adding the .disabled extension, so optional mods is probably the way to go here.

**Comment by arthomnix** [comment]
#5163 added an option to treat disabled mods as optional (if the pack is imported into MultiMC, these will be converted back to disabled mods)

**Comment by kosma** [comment]
This does I needed. Thank you very much! Issue can be closed at your discretion.
