### ISSUE TITLE
i cant start minicraft when it has a mod

### ISSUE THREAD

**Issue by nininheca** [MultiMC/Launcher#5148]
### Description of bug

every time I put the mod and start it appears in the log like this:

The process stopped working with exit code -1073741819 (0xffffffffc0000005).
Below is the analysis of the exit code. THE INFORMATION MAY BE INCORRECT AND IS DOUBTFUL!
System exit code name: STATUS_ACCESS_VIOLATION
System exit code description: Instruction no 0x%p referenced memory no 0x%p. The memory could not be %s.

Remember that the exit code and description are insufficient for diagnosing problems!
Always upload the entire log and not just the exit code.

### Steps to reproduce

1. open the instance and put the mod
2. when you put it, you start minicraft
3. and then the list of minicraft logs appears and the error appears with this message

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
