### ISSUE TITLE
Problem with starting FTB Infinitie Evolved 

### ISSUE THREAD

**Issue by RahulOmegalul** [MultiMC/Launcher#5150]
### Description of bug

my log https://paste.ee/p/dfPhP
my java path: C:/Program Files/Java/jdk-20/bin/javaw.exe
max ram provided: 10112 MiB

### Steps to reproduce

Starting the game

### Suspected cause

when i go to Settings -> Versions and then go on Forge an open path it opens C:\Users\Rahul\AppData\Roaming\UltimMC\instances\FTB Infinity Evolved 1.7\libraries
its empty?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
To start with you're using the wrong Java version. https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
