### ISSUE TITLE
MultiMC Crashing on First Launch

### ISSUE THREAD

**Issue by somedude72** [MultiMC/Launcher#5151]
**Operating System:** macOS
**System Architecture:** aarch64
**System Version:** macOS Ventura v13.3.1

### Description of bug

First time using MultiMC (been using default Minecraft launcher) to make the process of switching between 1.8 and 1.19 easier, encountered an error with Fabric loader on 1.19.4 with a fresh install (no mods). To troubleshoot, I tried it without Fabric Loader, and the same error occurred. In both instances, the game did not launch. 

Log: https://paste.ee/p/G2Bpo

### Steps to reproduce

1. Install MultiMC on MacBook
2. Add a 1.19.4 instance (default settings)
4. Launch the instance

### Suspected cause

One thing I found strange is that the java version I had installed on my machine is aarch64, however when MultiMC auto-detected my java, it stated that I had 32-bit java installed. That was the only thing that could've maybe caused the issue? 

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by SomedudeX** [comment]
I've also tried it without Fabric Loader, same error. 

Log: https://paste.ee/p/G2Bpo

**Comment by somedude72** [comment]
>**Native ARM Java is currently not supported on MultiMC.**
>
>Alternatively the Windows links above usually also provide macOS and Linux versions. On M1 Macs you need to make sure to get the x64 packages, native Arm Java is currently not supported!

Solved it myself
