### ISSUE TITLE
Mods won't appear in the mod folder correctly or show up when launched

### ISSUE THREAD

**Issue by MrPorkChop10** [MultiMC/Launcher#5153]
### Operating System

macOS

### Description of bug

I attempted to download a mod called 5zig. I downloaded it and inserted it into the loader mods folder, but it does not show the mod's name as it should and instead it appears as "Simple Inventory Sorter." When I start up the game, the mod does not appear. I had previously downloaded this mod with no problems a while ago, but I have since been forced to reset my computer and now it will not work now that I have installed it again.

<img width="691" alt="Screen Shot 2023-05-13 at 12 12 18 PM" src="https://github.com/MultiMC/Launcher/assets/133522946/efd05fc4-ff29-4181-bd71-cc18b7dca94a">

### Steps to reproduce

Put the mod in the folder.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
