### ISSUE TITLE
Configurable FTB App instance location

### ISSUE THREAD

**Issue by Heufneutje** [MultiMC/Launcher#5155]
### Role

I want to import a pack from the FTB app into MultiMC.

### Suggestion

I would like to be able to configure the FTB app instances location.

### Benefit

Currently if I understand the code right it is only possible to import packs from the default install location of the FTB app (for me %localappdata%\\.ftba on Windows). Being able to configure the location would allow MultiMC to find FTB packs anywhere on the system.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by FeedTheChunk** [comment]
FTB only allows you to install packs in one location anyway, for instance the ./instance directory.  If you change this location, according to the app, it will move your instances to the new location.  I have my FTB app instance directory pointing to e:/games/ftb/intances and MultMC uses that directory to import the pack from. Am I missing something? Having MultiMC search in a different directory wouldn't be necessary?

**Comment by Heufneutje** [comment]
I'm not sure. I did that but MultiMC is not seeing them. Unless I'm doing something wrong.

**Comment by Heufneutje** [comment]
Ah nevermind. It's just the FTB app being wonky. For some reason it reset itself back to the default location and then wouldn't work again until I deleted my instances and redownloaded them... It works now.
