### ISSUE TITLE
MultiMc crashes with no mods

### ISSUE THREAD

**Issue by Aleken1** [MultiMC/Launcher#5156]
### Operating System

Windows

### Description of bug

I'm trying to run a 1.8.9 instance with no mods and no forge installed and it crashes. Here is the log file: https://paste.ee/p/wbrZE

I'm using java 8u371 on windows 11. I also disabled microsoft defender for multimc

### Steps to reproduce

Create 1.8.9 instance

Go to settings

Change java version to java 8u371

Run instance

### Suspected cause

Maybe operating system

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
