### ISSUE TITLE
Beta 1.7.3: when turning on fullscreen, the video is split across both of my monitors

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5159]
### Description of bug

Whenever I turn on fullscreen, half of the game is shown in one monitor and half on the other.

### Steps to reproduce

1) use two monitors
2) press F11 while focused on the beta 1.7.3 game window

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
