### ISSUE TITLE
1.16.1 speedrun keeps craashing

### ISSUE THREAD

**Issue by Pickle0001** [MultiMC/Launcher#5161]
### Operating System

Windows

### Description of bug

Whenever i try to start a speedrun, open a world, or go into video settings it crashes. i just downloaded the new update, doe that maybe have anything to do with it?

### Steps to reproduce

i dunno what tyo write here

### Suspected cause

the update

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
