### ISSUE TITLE
Star Wars: Conquest 10.0.4 not opening

### ISSUE THREAD

**Issue by BL1Z33** [MultiMC/Launcher#5167]
### Operating System

Windows

### Description of bug

I was trying to open the Star Wars: Conquest 10.0.4 mod and it crashes.

### Steps to reproduce

Add a new instance
Select Import from zip
Download [Star Wars Conquest 10.0.4](https://www.mediafire.com/file/5h5p9cjrlavi0q5/Star+Wars-+Conquest+10.0.4.zip/file)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by BL1Z33** [comment]
> This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

Thx :D
