### ISSUE TITLE
WHEN I DOWNLOAD THE FORGE DO NOT RUN

### ISSUE THREAD

**Issue by dezindohaxixe** [MultiMC/Launcher#5168]
### Operating System

Windows

### Description of bug

In vanilla without forge run normally but when i download the forge editing with instance do not run
![image](https://github.com/MultiMC/Launcher/assets/135076650/be92a9a0-7333-4a30-8ac8-e6e677e1cb8d)

### Steps to reproduce

edit instance,install forge,lauch and boom

### Suspected cause

i dont have any idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ConfidentlyIncorrect** [comment]
While i can't exactly diagnose the issue, you should note that you are starting All the Mods 6 and not just forge directly, as such it may be a mod mismatch or game error in the modding area and not forge. As All the Mods 6 is NOT vanilla minecraft at all and can be very glitchy

**Comment by FeedTheChunk** [comment]
> While i can't exactly diagnose the issue, you should note that you are starting All the Mods 6 and not just forge directly, as such it may be a mod mismatch or game error in the modding area and not forge

Or the wrong Java version.  If you post the log someone might be able to help.
