### ISSUE TITLE
Incorrectly display aarch64 jvm as 32 bits

### ISSUE THREAD

**Issue by mio-19** [MultiMC/Launcher#5172]
### Operating System

Linux

### Description of bug

![image](https://github.com/MultiMC/Launcher/assets/57285379/cce1d7c5-dfc5-4840-a917-667e930dbaa0)

### Steps to reproduce

Built with https://aur.archlinux.org/packages/multimc5

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
thats not multimc just a package violating the trademark, the official arch package can be found here https://github.com/MultiMC/multimc-pkgbuild
as it stands multimc does not support arm though
