### ISSUE TITLE
1.20 Doesn't Show in Launcher

### ISSUE THREAD

**Issue by 4194304** [MultiMC/Launcher#5174]
### Description of bug

1.20 Doesn't display in the launcher

### Steps to reproduce

Go to the new instance menu and see that 1.20 is not there

### Suspected cause

Bad indexing?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by huoyan1231** [comment]
i have same problem

**Comment by Mulinix** [comment]
Same issue.

**Comment by KrishCapture** [comment]
same Issue.
![image](https://github.com/MultiMC/Launcher/assets/135947247/5df585ff-22fb-4d7a-abcb-738042dfded2)

**Comment by pinuxio** [comment]
same Issue.

**Comment by ThexXTURBOXx** [comment]
Just for future reference: "Same issue" does not help anyone. Such a comment only makes sense if you have additional information.

**Comment by phit** [comment]
waiting on https://github.com/MultiMC/meta/pull/13

**Comment by arthomnix** [comment]
for now, I've created some 1.20 instance zips you can import at https://arthomnix.dev/mmc-1.20/1.20.zip (vanilla) and https://arthomnix.dev/mmc-1.20/1.20-fabric.zip (fabric)

**Comment by Mistromy** [comment]
same

**Comment by zapteryx** [comment]
it's fixed! refresh your version list
