### ISSUE TITLE
Minecraft 1.20 crashes after being launched

### ISSUE THREAD

**Issue by Arkanu-of-Galatiel** [MultiMC/Launcher#5178]
### Operating System

Windows 7 64-bit

### Description of bug

I created a new instance and set it to version 1.20, but when I go to launch the instance, it soon shows a console window where it says it "Process exited with exit code -1 (0xffffffffffffffff)". A log is attached.
[crash-2023-06-09_22.34.40-client.txt](https://github.com/MultiMC/Launcher/files/11711346/crash-2023-06-09_22.34.40-client.txt)

Launching minecraft 1.20 with the regular minecraft launcher works as normal, and launching 1.20rc1 in MultiMC also works.

### Steps to reproduce

Create a new instance with version 1.20, or modify an existing instance to use version 1.20, then launch minecraft as normal.

### Suspected cause

Unknown.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Arkanu-of-Galatiel** [comment]
I tried uninstalling and re-installing Java, and updating Java, and re-configuring MultiMC's java settings. Nothing worked.

**Comment by phit** [comment]
Please upload your log like this
![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by Arkanu-of-Galatiel** [comment]
My bad. 
Here's the link: https://paste.ee/p/HKIdO

**Comment by maxdodge83** [comment]
When launching 1.20, I also got the error:

Instance update failed because: Instance has conflicting dependencies.

https://paste.ee/p/Pt6c1

[RESOLVED in 1.20.1]

**Comment by Arkanu-of-Galatiel** [comment]
Can confirm, 1.20.1 works on MultiMC, but I don't know why.
