### ISSUE TITLE
Launching Minecraft Java Edition in MultiMC Launcher prompts for "resource reload failure".

### ISSUE THREAD

**Issue by AkarinLiu** [MultiMC/Launcher#5179]
### Operating System

Windows

### Description of bug

It is possible that this problem may occur before version 1.20, or latest version may be.
[Clipboard](https://gitea.com/AkarinLiu/Clipboard/raw/branch/main/Minecraft/JavaEdition/10Jun2023_11:12:18_+0800.log)

### Steps to reproduce

Launch 1.19.4 Version Game Core
![图片](https://github.com/MultiMC/Launcher/assets/58081491/bcee9ba1-5f16-4249-ad63-240f13aef375)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
