### ISSUE TITLE
Update window opens; no new update

### ISSUE THREAD

**Issue by TechDudie** [MultiMC/Launcher#5180]
### Operating System

macOS

### Description of bug

Im using Macos, multimc is cool. I've used it before on other computers and when i downloaded it and set it up, MultiMC just blatantly lied to me. 😭 Not very important, but im sad that it lied to me
<img width="488" alt="image" src="https://github.com/MultiMC/Launcher/assets/73961295/e60580c2-e720-40be-a26a-788c4e6ebfc9">

### Steps to reproduce

Just download multimc, set it up, and have it lie to you.

### Suspected cause

The dialog probably opens by default for updates

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TechDudie** [comment]
When i hit Update Now, it just reinstalled multimc. bruh

**Comment by phit** [comment]
I have no idea what you are trying to communicate, presumably the removal of the stable channel, in which case the message is correct.
