### ISSUE TITLE
Play offline button not work

### ISSUE THREAD

**Issue by FazziCLAY** [MultiMC/Launcher#5182]
### Operating System

Linux

### Description of bug

Play offline button not work

### Steps to reproduce

Click to version & start

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what doesn't work?

**Comment by FazziCLAY** [comment]
> what doesn't work?

when you click nothing happens, the launcher continues to log in through the microsoft account ignoring my clicks

**Comment by phit** [comment]
ah so this, duplicate of https://github.com/MultiMC/Launcher/issues/5078

**Comment by FazziCLAY** [comment]
sorry

**Comment by phit** [comment]
no worries, sorry that I don't have a fix at this time
