### ISSUE TITLE
indev 0.31 wont launch

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5184]
### Operating System

windows 10

### Description of bug

i clicked launch and is did not work

### Steps to reproduce

first use c0.30_01c 

get the jar file for here https://minecraft.fandom.com/wiki/Java_Edition_Indev_0.31_20091223-2

then replace the jar file form c0.30_01c to the indev jar file next make the regular jar file to custom

the end

console:

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.165.53, 13.33.165.101, 13.33.165.48, 13.33.165.54]

session.minecraft.net resolves to:
    [13.107.213.38, 13.107.246.38]

textures.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38]

api.mojang.com resolves to:
    [13.107.213.38, 13.107.246.38]

Minecraft folder is:
D:/downloads/mmc-develop-win32/MultiMC/instances/c0.30_01c/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 20.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  com.mojang.minecraft.l

Native path:
  D:/downloads/mmc-develop-win32/MultiMC/instances/c0.30_01c/natives

Traits:
traits legacyLaunch
traits no-texturepacks

Libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/instances/c0.30_01c/libraries/customjar-1.jar

Native libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 4740

Using onesix launcher.

Could not set base folder. Failed to find/access Minecraft main class:
java.lang.ClassNotFoundException: com.mojang.minecraft.l
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.multimc.onesix.OneSixLauncher.legacyLaunch(OneSixLauncher.java:117)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:273)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Suspected cause

i do not know

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
I can't imagine a release from 2009 would use Java version 20.

**Comment by JJminecraftguy** [comment]
so wich version should i use

**Comment by JJminecraftguy** [comment]
all of the previos other version work

**Comment by JJminecraftguy** [comment]
bro i got it to work i used the infdev version instead and it worked

**Comment by JJminecraftguy** [comment]
> I can't imagine a release from 2009 would use Java version 20.

that was not the issue
