### ISSUE TITLE
certain versions of indev 0.31 wont work

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5185]
### Operating System

Windows 10

### Description of bug

it starts making the world then on post processing it almost gets done and then the game freezes

### Steps to reproduce

download this version of indev 0.31 

https://archive.org/download/Minecraft-JE-Indev/in-20100201-1/in-20100201-1.jar

then use the 1 version of infdev built in replace jar file with  the indev version then make the infdev jar file custom

log after using tak manager to stop the java running in the background:

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.165.48, 13.33.165.54, 13.33.165.101, 13.33.165.53]

session.minecraft.net resolves to:
    [13.107.213.38, 13.107.246.38]

textures.minecraft.net resolves to:
    [13.107.213.38, 13.107.246.38]

api.mojang.com resolves to:
    [13.107.213.38, 13.107.246.38]

Minecraft folder is:
D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 20.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.d

Native path:
  D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/natives

Traits:
traits legacyLaunch
traits no-texturepacks

Libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/libraries/customjar-1.jar

Native libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 20040

Using onesix launcher.

Could not find Minecraft path field.
Launching with applet wrapper...
43
Jun 13, 2023 10:16:31 AM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Jun 13, 2023 10:16:31 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Jun 13, 2023 10:16:31 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

FORCING EXIT!
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

also alot of other indev 0.31 version also do the same thing

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
#5184

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
