### ISSUE TITLE
indev 0.31 wont work

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5186]
### Operating System

Windows 10

### Description of bug

i open the game click new world and it gets tp post processing and freezes

### Steps to reproduce

I am using java 8 because the minecraft version is below 1.16

Java Edition Indev 0.31 20100131:
https://archive.org/download/Minecraft-JE-Indev/in-20100201-1/in-20100201-1.jar

make instance of infdev replace infdev jar file with indev jar file also use java 8

logs with java 8:

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.33.165.53, 13.33.165.54, 13.33.165.101, 13.33.165.48]

session.minecraft.net resolves to:
    [13.107.213.38, 13.107.246.38]

textures.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38]

api.mojang.com resolves to:
    [13.107.213.38, 13.107.246.38]

Minecraft folder is:
D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/.minecraft

Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_371, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.d

Native path:
  D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/natives

Traits:
traits no-texturepacks
traits legacyLaunch

Libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/downloads/mmc-develop-win32/MultiMC/instances/inf-201006189/libraries/customjar-1.jar

Native libraries:
  D:/downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 12928

Using onesix launcher.

Could not find Minecraft path field.
Launching with applet wrapper...
43
Jun 13, 2023 1:30:43 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Jun 13, 2023 1:30:43 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Jun 13, 2023 1:30:43 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

FORCING EXIT!
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

I'v used every version of java, java 8 64 bit, java 8 x86, java 20, and java 17

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by JJminecraftguy** [comment]
iv used every version of java i did not work

**Comment by JJminecraftguy** [comment]
my first issue was a diffrent version of indev 0.31 so all i needed to do is change to infdev instead of c0.0.13a

**Comment by phit** [comment]
not sure what you are expecting from some random ancient versions, if it doesn't work that really isn't something we can fix, there's a reason this ancient versions aren't provided by mojang, please stop making new issues and use our support discord for game support
