### ISSUE TITLE
Won´t open an instance

### ISSUE THREAD

**Issue by Marci261001** [MultiMC/Launcher#5190]
### Operating System

Windows

### Description of bug

Hi i tried to start one of my instances but instead of starting the instance it closed MultiMc same problem when i try to work on the instance it self need help to fix this

### Steps to reproduce

Try to start the instance or press the Instanz bearbeiten, Notizen bearbeiten Mods anzeigen etc. button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
open the instance in explorer, check the logs folder, there's probably a huge file in there, delete it

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
