### ISSUE TITLE
MultiMC Instance crashed when opening a world

### ISSUE THREAD

**Issue by ReaperOFCandies** [MultiMC/Launcher#5191]
### Operating System

Windows

### Description of bug

Whenever I open minecraft it opens normally but when I open a world to play it crashes...
I dont know much about about the codes and stuff so here is the log:
https://paste.ee/p/f3NMA

### Steps to reproduce

Sorry but idk... 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
