### ISSUE TITLE
Mods inside subfolders are not loading

### ISSUE THREAD

**Issue by Mahonzu** [MultiMC/Launcher#5194]
### Operating System

Windows

### Description of bug

I installed several mods in the `.minecraft/mods` folder. I wanted to separate some of them from others so that I could quickly toggle groups of mods. So I created a folder called `.minecraft/mods/addons` and put the mods there. However, the mods from this folder are not loading in the game. Although the folder itself is displayed in the list of mods. 

### Steps to reproduce

1. Put the first mod in .minecraft/mods
2. Put the second mod in .minecraft/mods/folder
3. Start the game
4. The first mod is loaded, the second is not

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
its up to the modloader to do so, most don't allow subfolders
