### ISSUE TITLE
I can't find binaries, working compile directions or "add Microsoft" button.

### ISSUE THREAD

**Issue by D4rkH0rs3** [MultiMC/Launcher#5195]
### Description of bug

I want to play minecraft on my laptop (pinebook pro).

I can't find a binary and would like pointers to same if it exists.

Compiled from source, launcher seems to run well aside form not having "add microsoft" button in accounts.

The compile instructions don't mention that it can't work, something about missing secrets.

### Steps to reproduce

compile (target and source need changed from the default 7)
go to accounts page
fail to press missing button

google MultiMC arm, wade through pages of people saying it's a good idea and discussing install paths that don't work. 

### Suspected cause

binary doesn't exist or is well hidden.

compile from source, something about secrets.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
we don't support arm, the [build.md](https://github.com/MultiMC/Launcher/blob/develop/BUILD.md) has a note on the secrets
