### ISSUE TITLE
abnormal crash

### ISSUE THREAD

**Issue by Robyg10** [MultiMC/Launcher#5196]
### Operating System

Windows

### Description of bug

after several time while playing my world black screen and game closes

### Steps to reproduce

No response

### Suspected cause

No response

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
