### ISSUE TITLE
Use system installation of liblwjgl

### ISSUE THREAD

**Issue by thalisky** [MultiMC/Launcher#5197]
### Role

vanilla and modded minecraft players running on a 32 bit architecture

### Suggestion

Add a checkbox that makes minecraft uses the system installation of liblwjgl

### Benefit

32-bit players would still be able to play minecraft

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello,
I'm running on a i386 linux machine, and I have compiled liblwjgl myself.
However, there isn't a checkbox that allows me to use it to play version of minecraft higher than 1.12.2.
Will it be added?
Also, here is the error when trying to launch minecraft:
[https://pastebin.com/9jUNJ1e3](https://pastebin.com/9jUNJ1e3)

Thank you.

**Comment by phit** [comment]
unlike the other system options, you can already change out lwjgl via the json patches, in the version tab select lwjgl and then click customize and then edit on the right

**Comment by FauconFR** [comment]
> unlike the other system options, you can already change out lwjgl via the json patches, in the version tab select lwjgl and then click customize and then edit on the right

hello and thank you for your answer.
can you help me doing that please? I only found how to change the url but can't find out how to swap it with the system installation.
thank you

**Comment by thalisky** [comment]
Hello and thank you for your answer.
I tried doing that but it does the same thing,
I swapped it with a 1.12.2 one

**Comment by phit** [comment]
that will not work, they use completely different versions, sorry if you need help with applying json patches feel free to ask, but we aren't gonna support you building your own libraries

**Comment by thalisky** [comment]
Thank you for your answer.
Thankfully my pc got repaired and I can get back to playing.
