### ISSUE TITLE
Exit Code -1

### ISSUE THREAD

**Issue by ninjatwinkie1** [MultiMC/Launcher#5199]
### Operating System

Windows

### Description of bug

I open modded 1.7.10 and it immediately closes with exit code -1.
https://paste.ee/p/JVFcp

### Steps to reproduce

- Launch Minecraft
- Be dissapointed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong version java.

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
