### ISSUE TITLE
New computer install, don't know why there's an issue

### ISSUE THREAD

**Issue by RuneofCloud** [MultiMC/Launcher#5200]
### Operating System

Windows

### Description of bug

I did search before hand and installed the supposed correct version of java btw, and I'm not exactly able to make sense of all the stuff in the log unfortunately. Help would be appreciated, also hope I posted this correctly.

### Steps to reproduce

This is a brand new install so i'm not sure how it happened however I am using minecraft 1.19.2 with windows 11. https://paste.ee/p/evvui 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
