### ISSUE TITLE
Could not understand pack manifest error when importing Tekxit from Technic 

### ISSUE THREAD

**Issue by OnlyC0RE** [MultiMC/Launcher#5203]
### Description of bug

Can't install Tekxit 3.14 Pi (Official) from Technic. Throws error: "Could not understand pack manifest: 'version' is not a string"

### Steps to reproduce

Try installing it. huh.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Duplicate of https://github.com/MultiMC/Launcher/issues/5066
