### ISSUE TITLE
1.7.10 crashing

### ISSUE THREAD

**Issue by ninjatwinkie1** [MultiMC/Launcher#5204]
### Operating System

Windows

### Description of bug

Whenever I launch minecraft I get an exit code of -1, I have Java 8 installed which I was recommended to do by others but it still doesn't work.

### Steps to reproduce

Open minecraft

### Suspected cause

Version of java

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please upload your log
![](https://cdn.discordapp.com/attachments/531598137790562305/575381000398569493/unknown.png)

**Comment by ninjatwinkie1** [comment]
https://paste.ee/p/p7l9b

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
