### ISSUE TITLE
Does MultiMC update regardless of the update setting?

### ISSUE THREAD

**Issue by allanonmage** [MultiMC/Launcher#5205]
### Operating System

Windows

### Description of bug

I noticed that minecraft now uses the Grass block icon, instead of the crafting table icon, matching the 1.20 releases same change.  Except I have updating turned off and play in a 1.19.2 server.

MultiMC is 0.7.0, and I turned off updates of the launcher.  Since older versions of the game don't get in-version updates, there should be no reason for anything to update, but clearly something did.

Did MultiMC update something?  Incidentally, this happened after my PC started itself, crashed, and started itself again, all of which are typical behaviors of modern software updating itself.  I go far out of my way to keep my updates manual, so this should not have been the case.  yet the new icon says otherwise.

### Steps to reproduce

Look at the task bar.

### Suspected cause

Someone updated themselves against my will.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
MultiMC updates have nothing to do with game updates, older versions get asset updates all the time for stuff like translations and those get applied automatically at launch.

Here is said icon update for example https://github.com/MultiMC/meta-upstream/commit/064136e48c281715a5e443217127fb93f54b016b
