### ISSUE TITLE
Minecraft crashing when going in fullscreen mode.

### ISSUE THREAD

**Issue by 7seasking** [MultiMC/Launcher#5207]
I've been playing 1.8.9 since very long time now, probably 4-5 years not and I never faced this issue, the issue is whenever I go in fullscreen mode my game crashes, I tried the older java verison which was recommended for older Intel Gpu's but it didnt work, please help me as windowed mode is  so laggy and I cant enjoy minecraft now. 1.9 and above versions are running great but 1.8.9 is not, it works but when fullscreened it crashes.
log file: https://paste.ee/p/nrjp4

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
