### ISSUE TITLE
Failed to upload a skin onto my Microsoft account

### ISSUE THREAD

**Issue by GTHB-plyr7510** [MultiMC/Launcher#5210]
### Description of bug

When I try to upload a skin on my Microsoft account, I expected it to work as normal, but instead I randomly got served this error. Which was odd.
<img width="960" alt="image" src="https://github.com/MultiMC/Launcher/assets/138413585/ae72ac90-ce29-4a93-80bf-df2ca12322ab">

### Steps to reproduce

1. Go to settings, then click "Accounts".
2. Click on your account and then click "Upload skin".
3. Try to upload your skin, but then get served this error.

### Suspected cause

I am not sure, but maybe it's because I "don't have a profile" or MultiMC doesn't support skins for Microsoft accounts. 

To phit: Yes, I was right. I did not use MultiMC. I used wrong download link. So I downloaded the real MultiMC and tried again... No luck.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to own the game to play the game and use skins
