### ISSUE TITLE
Is there no more update?

### ISSUE THREAD

**Issue by Tsaitou7361** [MultiMC/Launcher#5212]
well, I think this package is not done yet, but seems like no more updates, really?

**Comment by phit** [comment]
what makes you say that?

**Comment by Tsaitou7361** [comment]
latest update is on 2021, but now is 2023, if it's a undone software, it should keep update, but they dosen't.

**Comment by phit** [comment]
thats just github releases which haven't been used since then, there have been regular updates https://multimc.org/posts/0-7-0-update.html
