### ISSUE TITLE
unable to upload skin (cracked account not a purchased one)

### ISSUE THREAD

**Issue by GenosPro** [MultiMC/Launcher#5213]
### Operating System

Windows

### Description of bug

when i go the manage accounts option and try to add a new skin it doesnt work it just shows
"failed to upload skin"  even if i use a account of "ely.by" the username shows the email of what i entered in the login section
ely.by works on most cracked launchers some of them have their own skin system like sk launcher

### Steps to reproduce

1) Go to Manage Accounts.

2) Click on the desired account (non-migrated?).

3) Click Upload Skin.

4) Select a skin file.

5) Hit Okay.

### Suspected cause

i dont know i tried many fixes and options too tried search online for solutions but none of them work
just want to put on a skin 
i just hope that ely.by accounts work and display the skin i set in my account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
buy the game
