### ISSUE TITLE
Quilt Telemetry easier Opt-Out (checkbox)

### ISSUE THREAD

**Issue by macbrayne** [MultiMC/Launcher#5214]
### Role

Playing Quilt instances 

### Suggestion

Add a checkbox controlling the `-Dloader.disable_beacon=true` JVM argument for Quilt instances

### Benefit

This makes opting out of Quilt's opt-out userbase metric easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

More information at: [Evil Modding Project Adds Telemetry](https://quiltmc.org/en/blog/2023-06-26-mau-beacon/) and [Quilt Loader Telemetry Explained](https://quiltmc.org/en/blog/2023-07-12-quilt-telemetry-explained/)

Alternative options:
* always supply that JVM argument
* do nothing

**Comment by Primitive-Human** [comment]
Like their page mentions, you can just put that java argument in the launch options of your quilt instances.

**Comment by phit** [comment]
for context, quilt removed said telemetry
