### ISSUE TITLE
Internal server error when linking microsoft account

### ISSUE THREAD

**Issue by gitguette** [MultiMC/Launcher#5221]
### Operating System

Linux

### Description of bug

When trying to link my microsoft account, I will get the notification I can safely close the window after signing in. A few seconds later, MultiMC will have this error: 'Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Internal Server Error'.

### Steps to reproduce

- Register an azure app, change the required settings.
- Paste the client ID into Secrets.cpp.
- Build the program as normal according to the Linux section of BUILD.md(if it's important, the build location and installed files are in different locations).
- Run the program, and select the 'Add microsoft' option in the accounts menu.
- Open the microsoft link, paste the code, sign in, and my give the azure app the requested permissions.
- MultiMC tries to log in, but fails.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to apply for access as of end of may https://help.minecraft.net/hc/en-us/articles/16254801392141
