### ISSUE TITLE
crash led to launcher not functioning

### ISSUE THREAD

**Issue by mastercheeif82** [MultiMC/Launcher#5223]
### Operating System

Windows

### Description of bug

gtnh crashed and after multimc stopped working, attempting to launch modpack results in [this](https://paste.ee/p/sNc9J) crash log

### Steps to reproduce

atempt to launch any pack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong version of Java.

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by mastercheeif82** [comment]
im using the java 17-20 version of gtnh, it was working just fine for several months

**Comment by phit** [comment]
no you aren't, you are using java 19
