### ISSUE TITLE
New Instance Crashes

### ISSUE THREAD

**Issue by Akanthodis95** [MultiMC/Launcher#5224]
### Description of bug

When starting a 1.20.1 instance, the screen shortly after goes to black, with a small windowed white in the middle, then returns to MultiMC with the crash report. 

https://paste.ee/p/bO87p

### Steps to reproduce

1. Run the instance
2. That's it

### Suspected cause

I thought it was Forge and Optifine, but I removed it. Don't think it was Java, because the instance was working before I updated my server from 1.19.4 to this version. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
assign less memory
