### ISSUE TITLE
I don't know what I'm doing

### ISSUE THREAD

**Issue by tissthecat** [MultiMC/Launcher#5225]
I'm trying to use a mod for 1.2.5 and put it in the loader mods tab and I tried to launch it and all I saw was a white screen. I put it in the core mods, and same thing. it was a folder of .class files (whatever that means) so I turned the folder into a .jar file (after a quick google search) and I put that in instead and nothing. I even put it I the version tab and still, nothing. I see the errors in the logs but I don't know how to fix them. I'm using MacOS 14 dev beta 3 on an M2 15" MacBook Air. I don’t know if that has something to do with it. here are the screenshots of the red areas:
![Screenshot 2023-07-25 at 1 29 11 PM](https://github.com/MultiMC/Launcher/assets/140476362/af05c1cb-d7a0-4997-876b-227f8dbe655d)
![Screenshot 2023-07-25 at 1 29 56 PM](https://github.com/MultiMC/Launcher/assets/140476362/93902709-f4da-4212-932e-52ccae4a3591)

here are the Minecraft logs if it helps:

MultiMC version: 0.7.0-3774

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.239.199.19, 18.239.199.110, 18.239.199.52, 18.239.199.10]

session.minecraft.net resolves to:
    [13.107.253.57, 13.107.226.57]

textures.minecraft.net resolves to:
    [13.107.253.57, 13.107.226.57]

api.mojang.com resolves to:
    [13.107.253.57, 13.107.226.57]

Minecraft folder is:
/Applications/MultiMC.app/Data/instances/1.2.5/.minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Checking Java version...
Java is version 1.8.0_381, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  

Native path:
  /Applications/MultiMC.app/Data/instances/1.2.5/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Applications/MultiMC.app/Data/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Applications/MultiMC.app/Data/instances/1.2.5/.minecraft/bin/minecraft.jar

Native libraries:
  /Applications/MultiMC.app/Data/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Applications/MultiMC.app/Data/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar

Jar Mods:
  1_2_5_64bitcoords_v3 (fc37b06e-fb8c-4c83-a87f-da5fdd470f78.jar)

Params:
  

Window size: max (if available)

Java Arguments:
[-Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.2.5", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 75331

Using onesix launcher.

Launching with applet wrapper...
27 achievements
182 recipes
Setting user: YeetusgodV, token:<ACCESS TOKEN>:<PROFILE ID>
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
	at java.lang.Runtime.loadLibrary0(Runtime.java:843)
	at java.lang.System.loadLibrary(System.java:1134)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(SourceFile:184)
	at net.minecraft.client.Minecraft.run(SourceFile:657)
	at java.lang.Thread.run(Thread.java:750)
Process exited with exit code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
