### ISSUE TITLE
Ошибка аутентификации пользователя Xbox.

### ISSUE THREAD

**Issue by loch1686** [MultiMC/Launcher#5227]
### Description of bug

при попытке входа в аккаунт майкрософт через мульти мс выдает ошибку "Ошибка аутентификации пользователя Xbox.
", подскажите что делать пожалуйста

### Steps to reproduce

![image](https://github.com/MultiMC/Launcher/assets/140633303/43aa604f-f527-48c8-a858-29e09aa58432)

### Suspected cause

я думаю, что причина ошибки в забитых серверах майкрософт или санкций в сторону РФ

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
we can't do anything about this error, try signing in at minecraft.net and xbox.com, if neither work its out of our control
