### ISSUE TITLE
has no errors in logs, still shows blank white screen

### ISSUE THREAD

**Issue by tissthecat** [MultiMC/Launcher#5228]
I found the right java version for my system, and there were no errors in the logs, but when I try to launch 1.2.5, there's still a blank white screen. it says that it is loading but it never does. I even left it overnight and still nothing (M2 15" MacBook Air), I then tried a completely new instance of 1.2.5 with the mod. nothing. after that, I tried 1.16, and that did work. I don’t know.

**Comment by phit** [comment]
try this java version please https://files.multimc.org/downloads/jre-8u241-macosx-x64.dmg

**Comment by tissthecat** [comment]
I just tried that and it failed to install. I removed the other one I had and that didn't work.
![Screenshot 2023-07-27 at 12 29 32 PM](https://github.com/MultiMC/Launcher/assets/140476362/65fc31d7-a61d-449c-b66d-3762d55d4138)

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
