### ISSUE TITLE
Textures are not accessed correctly on older versions of minecraft

### ISSUE THREAD

**Issue by DASPELLER4** [MultiMC/Launcher#5229]
### Operating System

Linux

### Description of bug

Playing any version of minecraft on multimc before 1.13 results in textures not getting applied correctly or even at all
<h3>examples:</h3>
<img src="https://i.imgur.com/iwP1E3w.png">
<img src="https://i.imgur.com/14IHeyC.png">
<h3>attempts to resolve:</h3>
changing from the distribution supplied version of jdk 1.8 to 1.8_151 did nothing, updating video drivers did nothing, reinstalling multimc did nothing

### Steps to reproduce

Using jdk 1.8 (any other version causes a version error), launch an instance of minecraft that is 1.13 or below.

### Suspected cause

Literally no idea, my friend has the same exact issue on the same versions, two different linux distros, we both use ryzen zen 2 cpus so maybe thats a cause but i didnt have this issue when i first got my cpu on multimc so i doubt it. Cannot be a gpu issue as both of our gpus are fine and work.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what gpu, what gpu drivers? the issue looks exactly the same as this caused by broken nvidia drivers https://old.reddit.com/r/MinecraftHelp/comments/yr7g8b/java_completely_broken_visuals_on_mc_1710_nvidia/

**Comment by DASPELLER4** [comment]
I have a gtx titan x (maxwell) and my friend has a gtx 1060 (6gb) I've been continuously trying new versions since 520 so I'll revert to around 430 and see if that resolves it.

**Comment by DASPELLER4** [comment]
I tried to downgrade my gpu driver but dkms is being extremely tempermental so i couldn't, ill message my friend to see if he can try and then we'll see if that solves the issue.

**Comment by Lolothepro** [comment]
https://github.com/NVIDIA/open-gpu-kernel-modules/issues/522

**Comment by phit** [comment]
as a workaround you can add `sh -c "export __GL_THREADED_OPTIMIZATIONS=0; exec $INST_JAVA \"$@\""` as a wrapper command

**Comment by Cucuzacu** [comment]
I have the same issue on windows 11!!!!!!

**Comment by phit** [comment]
update your gpu drivers
