### ISSUE TITLE
Ability to change font & font size for the entire UI

### ISSUE THREAD

**Issue by tpowell11** [MultiMC/Launcher#5231]
### Role

Playing modded, as well as occasional pack development.

### Suggestion

I would like to be able to specify a custom font and font size.

### Benefit

I find the current UI font size to be a little small for easy reading.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Looking through launcher/ui/MainWindow.cpp, it seems like one should be able to import a font with `QFont font("Courier New");` and then apply it globally with `QApplication::SetFont` ([documentation](https://doc.qt.io/qt-5/qguiapplication.html#setFont)). The size could be changed with any of `setPixelSize()`, `setPointSize()`, or `setPointSizeF()`. All this information could be serialized to <install_directory_path>/multimc.cfg as:
``` cfg
ApplicationFont=<fontname>
ApplicationFontSize=<fontsize>
```
Not quite sure how this would all work in terms of a GUI font system in settings, but I'd honestly be happy with just changing it in multimc.cfg.

**Comment by phit** [comment]
MultiMC already follows system scaling in most cases, if you are on Windows make sure to grab the Qt 5.15 package https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip

other than that you can implement this using a custom theme, here's an example changing a bunch of colors and the font to comic sans [custom.zip](https://github.com/MultiMC/Launcher/files/12209856/custom.zip)

![image](https://github.com/MultiMC/Launcher/assets/2097483/a51c8592-e372-4cef-b4c1-fa5c9bd098fc)
