### ISSUE TITLE
Solution to "Failed to find Minecraft main class: java.lang.ClassNotFoundException: net.minecraft.client.main.Main"

### ISSUE THREAD

**Issue by LeakingAmps** [MultiMC/Launcher#5233]
### Role

I play Minecraft

### Suggestion

I'd like to provide a workaround/fix for the issue

### Benefit

This allows people with the issue to play normally

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

If a user gets the error 

```
Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

The fix is to click on the account in the upper right corner, head to Manage Accounts, select your account, and select Refresh.

Would it be possible to auto-refresh the account if MultiMC fails to download the minecraft instance that is being launched?

Edit: Relevant issues:
https://github.com/MultiMC/Launcher/issues/3064
https://github.com/MultiMC/Launcher/issues/3065
https://github.com/MultiMC/Launcher/issues/2836

**Comment by phit** [comment]
Basically https://github.com/MultiMC/Launcher/issues/4355, https://github.com/MultiMC/Launcher/issues/5166 and https://github.com/MultiMC/Launcher/issues/4356
Really don't need another issue for this, yes there needs to be some way to recheck for internet access automatically.

**Comment by morerokk** [comment]
Can we maybe add a readable warning message for this? I've run into this several times now and a cryptic error about not being able to find a random Minecraft class is extremely unhelpful.
