### ISSUE TITLE
Exit Code 255. REI is apparently crashing my game

### ISSUE THREAD

**Issue by CheekyPency** [MultiMC/Launcher#5237]
### Minecraft
Version 1.19.4 - Fabric with IRIS and Sodium - modded (if my mod list is needed, please do tell!)

### What led to the crash
Every time I open the inventory, my game crashes. I'm sure that the problem is with REI but I don't know how to resolve it.

### Important

I use Linux Mint and I only know the basics while using the terminal.

* All the info that I deemed necessary is above and below;
* I checked every mod I had, and I'm sure that the problem is with Roughly Enough Items (which is on it's latest version available for Fabric 1.19.4);
* If more info is needed, please do ask!

### More info
I already have all the required mods for every other one on my mod list. The problem suddenly started today, I didn't have any issues with this before and the game was working just fine yesterday; sometimes I can open the inventory, but this appears: ↴

![5074e53f-105f-4f08-a22c-218f6bb1fc66](https://github.com/MultiMC/Launcher/assets/142057025/62466884-92dc-4215-975f-ba3d12215f79)

sometimes it charges and I can use the inventory, but when I close it the game crashes: ↴

![e7ce9f78-a1ff-4dfa-83bd-679bb8f8567f](https://github.com/MultiMC/Launcher/assets/142057025/54cc86d1-4bce-466e-ae19-f9001e62b8f6)

**I don't know if this will be useful or not, but I only use my _laptop_ to run the game**

### Error Code 255

[crash-2023-08-11_17.53.33-client.txt](https://github.com/MultiMC/Launcher/files/12325674/crash-2023-08-11_17.53.33-client.txt)

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
