### ISSUE TITLE
When installing forge in minecraft versions 1.8.9 and below, it gives an error that I have the wrong path to textures for minecraft.

### ISSUE THREAD

**Issue by DangerXXL** [MultiMC/Launcher#5241]
### Operating System

_Windows_

### Description of bug

If I delete the forge, then I can install the textures, but if I install the forge, then I get an error.
Error:
Cannot find "\C:\Program Files(x86)\PM\MultiMC\instances\1.8.9\.minecraft\resourcepacks\\". Check if the name is correct and try again.

### Steps to reproduce

If I delete the forge, then I can install the textures, but if I install the forge, then I get an error.

### Suspected cause

There may be some kind of malfunction of the MultiMC forge, since there is no such error on other launchers.
Reinstalling MultiMC didn't help.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
