### ISSUE TITLE
Versions that use java 8 are "transparent"

### ISSUE THREAD

**Issue by Manazzez** [MultiMC/Launcher#5243]
### Operating System

Windows

### Description of bug

Whenever I launch any Minecraft version, besides the ones that use java 17, the game loads but is invisible. It plays Minecraft music and has a working process on task manager, but when I click on the icon of the game nothing pops up. I also tried to use Alt + Tab and the game is completely white 
This is only happening on my new pc build, on my old laptop it runs just fine 🤷‍♂️

### Steps to reproduce

1 step: donwload any Minecraft version that uses java 8 
2 step: click to launch the game

### Suspected cause

Could be some sort of driver malfunction since it works just fine on my laptop

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
