### ISSUE TITLE
Windows error window opens on latest update

### ISSUE THREAD

**Issue by gurns072** [MultiMC/Launcher#5244]
### Description of bug

After updating to the newest version of MultiMC, a windows error window appears, claiming the program is "either not designed to run on windows, or contains an error." Also created 6 unnamed instances and won't run Minecraft on account of "corrupted jar files"

### Steps to reproduce

I dunno, update the app?

### Suspected cause

corrupted jar file

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Primitive-Human** [comment]
I'm always on the latest version (0.7.0-3775 as of this moment) and I have never seen this occur.

Logs, screenshots, steps you've actually done, so we have something to work with rather than this weird vague issue.
