### ISSUE TITLE
MultiMC crashes with Forge installed on version 1.7.10

### ISSUE THREAD

**Issue by artsybigirl** [MultiMC/Launcher#5245]
### Operating System

Linux

### Description of bug

I keep trying to install a mod that requires Minecraft 1.7.10. When I install Forge, it crashes with an exit code 255, I think it was. I have searched but the solutions are either Windows-oriented or have something to do with Java. I've tried different versions of Java, nothing has changed. Before I install Forge, it functions. Afterwards, nothing. I've moved my mulitmc file to my desktop in an attempt to fix it. I've changed graphical drivers, but nothing has changed.
I am running Linux Mint 21.2, which is Debian if anyone needs that info. I am at a loss here.

MultiMC version: 0.7.0-3772

Launched instance in online mode

authserver.mojang.com resolves to:
    [3.160.5.105, 3.160.5.107, 3.160.5.60, 3.160.5.67]

session.minecraft.net resolves to:
    [13.107.246.51, 13.107.213.51, 2620:1ec:bdf::51, 2620:1ec:46::51]

textures.minecraft.net resolves to:
    [13.107.246.51, 13.107.213.51, 2620:1ec:bdf::51, 2620:1ec:46::51]

api.mojang.com resolves to:
    [13.107.246.51, 13.107.213.51, 2620:1ec:46::51, 2620:1ec:bdf::51]

Minecraft folder is:
/home/verlie/Desktop/multimc/instances/1.7.10/.minecraft

Java path is:
/usr/lib/jvm/java-11-openjdk-amd64/bin/java

Checking Java version...
Java is version 11.0.20, using 64-bit architecture, from Ubuntu.

Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)

Subsystem: ASUSTeK Computer Inc. GP104 [GeForce GTX 1080]

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 525.125.06

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/verlie/Desktop/multimc/instances/1.7.10/natives

Libraries:
  /home/verlie/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/verlie/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/verlie/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/verlie/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/verlie/.local/share/multimc/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /home/verlie/.local/share/multimc/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/verlie/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/verlie/.local/share/multimc/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /home/verlie/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/verlie/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/verlie/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /home/verlie/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/verlie/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/verlie/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/verlie/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/verlie/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/verlie/.local/share/multimc/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /home/verlie/.local/share/multimc/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  /home/verlie/.local/share/multimc/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /home/verlie/.local/share/multimc/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /home/verlie/.local/share/multimc/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /home/verlie/.local/share/multimc/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/verlie/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /home/verlie/.local/share/multimc/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /home/verlie/.local/share/multimc/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  /home/verlie/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/verlie/.local/share/multimc/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  /home/verlie/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/verlie/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/verlie/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/verlie/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/verlie/.local/share/multimc/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  /home/verlie/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/verlie/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  --username ffxplayer --version 1.7.10 --gameDir /home/verlie/Desktop/multimc/instances/1.7.10/.minecraft --assetsDir /home/verlie/.local/share/multimc/assets --assetIndex 1.7.10 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {} --userType msa --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 7935

Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code 255 (0xff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 24 Aug 2023 11:04:48 -0500

### Steps to reproduce

Start a mulitmc instance of Minecraft 1.7.10. 
Start it up, it runs fine.
Exit, and install Forge
Crash begins.
Change Java version
Crash still happens.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Wrong java version.

/usr/lib/jvm/**java-11-openjdk-amd64**/bin/java

**Comment by artsybigirl** [comment]
Which one is right then? Do I need to go thru every single version until I find the right one? I've tried this one, I've tried 20, I've tried another Java 11.

**Comment by FeedTheChunk** [comment]
There's a nice convenient Wiki just for things like this: [Using the right Java](https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java)

**Comment by artsybigirl** [comment]
Ahh thanks. To the future peeps, it’s Java 8.
