### ISSUE TITLE
Cannot add Microsoft account (New issue since old solution does not work)

### ISSUE THREAD

**Issue by sarpuser** [MultiMC/Launcher#5247]
> This is an issue on a Mac (Intel) as well. I also cannot seem to login to Microsoft another way besides GitHub. It just does not give me the option. So I cannot authenticate my account on MultiMC. Please fix this. I cannot play at all.

_Originally posted by @sarpuser in https://github.com/MultiMC/Launcher/issues/5133#issuecomment-1692726377_

When I try to add my Microsoft account, I get this loading bar that has my linking code as well as the Microsoft linking page. When I go to this page, I am prompted to log in and I cannot log in any other way than using my GitHub account, which was suggested in the old issue as the solution to this problem. Since I can't log in another way, I cannot play at all. When I sent this screenshot to the Discord one of the devs told me that this was an unsupported build but this is downloaded straight from the MultiMC website.

This progress bar takes about 10-15 minutes to fully load and in the end I get an error saying Microsoft authentication failed.
<img width="489" alt="Screenshot 2023-08-24 at 23 30 30" src="https://user-images.githubusercontent.com/23362324/263163262-a1fee3c2-dd73-40b1-bcee-34b7af07ecd7.png">

**Comment by phit** [comment]
this is a bug on microsofts end, we can't do anything about it, add another login method to your MS account

**Comment by ajturner** [comment]
@phit 

~Can you provide any more information about the bug from Microsoft when using Github authentication?  That may help people (like me) debug the underlying issue. Maybe even advocate to devs in Microsoft how to fix the issue.~

Here is a description for others how to get past this...

Choose `Other ways to sign in`
<img width="771" alt="image" src="https://github.com/MultiMC/Launcher/assets/1218/591a50f7-08be-4b35-818d-f82bcc192c5b">

Then choose the `Email: ...` option

<img width="780" alt="image" src="https://github.com/MultiMC/Launcher/assets/1218/f3ab2b18-b221-438d-a977-5d65b0035eed">

Then in your email app get the code and enter it on the next screen.

and finally you'll see this:
 
<img width="949" alt="Screenshot 2024-05-05 at 17 55 14" src="https://github.com/MultiMC/Launcher/assets/1218/9604e692-d285-42f3-bca3-a5ada417ec0e">
