### ISSUE TITLE
no version of java works.

### ISSUE THREAD

**Issue by cracktorio** [MultiMC/Launcher#5250]
### Operating System

Linux

### Description of bug

I am runnning arch linux and the latest of everything, with java 8 (because i'm trying to run 1.12, other java versions also don't work.). Everything i try doesn't work, and if i test a binary it just tells me "The specified java binary didn't work.
You should use the auto-detect feature, or set the path to the java executable.", while auto-detect doesn't work and i am able to use java from cmd. Does anyone know how to fix?

### Steps to reproduce

1. Install multimc
2. Install full java 8 jdk
3. it does not work

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please do the test in multimc and then upload your multimc-0.log that can be found in the launcher folder here

**Comment by FeedTheChunk** [comment]
Upload your logs so that someone can help you.

https://github.com/MultiMC/Launcher/wiki/Feedback

**Comment by cracktorio** [comment]
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/12478752/MultiMC-0.log)
here is the log

**Comment by phit** [comment]
not sure where you got that java from but its broken 

`java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-8-openjdk/jre/lib/amd64/libnio.so: /usr/lib/jvm/java-8-openjdk/jre/lib/amd64/libnio.so: undefined symbol: NET_Bind, version SUNWprivate_1.1`

**Comment by cracktorio** [comment]
Just found out, it's an issue with the multimc version. I downloaded from the site and not AUR, and it detected java after building. It asked me if i wanted to update, it didn't detect/use java after. I downgraded to the one from the site, and it worked again. So no, it's not my java that's corrupted it's something with the newest version of multimc.

**Comment by phit** [comment]
there is no multimc from the AUR, the only official arch package is https://github.com/MultiMC/multimc-pkgbuild
