### ISSUE TITLE
Instances randomly missing despite still being in the instances folder

### ISSUE THREAD

**Issue by Sourpunch14** [MultiMC/Launcher#5254]
### Operating System

Windows

### Description of bug

I have a handful of instances in my MultiMC\instances folder but they're not showing up in the MultiMC app

### Steps to reproduce

Unsure of what caused this. It was working last night just fine

### Suspected cause

Unsure of the cause

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
