### ISSUE TITLE
freedesktop (GNU/Linux) description should contain Minecraft.

### ISSUE THREAD

**Issue by Secret-chest** [MultiMC/Launcher#5255]
### Role

I play Minecraft on Linux/

### Suggestion

I want to search "minecraft" and have it listed

### Benefit

so I can easily access it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In fact, there's no description at all.

**Comment by phit** [comment]
this should already work, minecraft is one of the keywords in the desktop file https://github.com/MultiMC/Launcher/blob/develop/launcher/package/ubuntu/multimc/usr/share/applications/multimc.desktop#L5
