### ISSUE TITLE
Game crashes after opening inventory sometimes

### ISSUE THREAD

**Issue by benjirocker** [MultiMC/Launcher#5259]
### Operating System

macOS

### Description of bug

I expected the game to run functionally. But instead, it crashes after opening or closing inventory.
pastee: https://paste.ee/p/O0sJs
mods: https://imgur.com/a/l0CGd3t
version folder: https://imgur.com/a/jfYpK49

### Steps to reproduce

Download multimc
install 1.16.5
install java 17
install forge 36.2.34
install mods above
run the game
crash :(

### Suspected cause

no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
