### ISSUE TITLE
Update fabric

### ISSUE THREAD

**Issue by Shadowblitz16** [MultiMC/Launcher#5261]
### Role

I am trying to get split screen working with my freind

### Suggestion

I want to install midnight controls

### Benefit

for splitscreen

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I get this...
![image](https://github.com/MultiMC/Launcher/assets/2453707/1817ec28-e13f-4d58-a6fb-c0017eb07174)
but the version it requires does not exists...
![image](https://github.com/MultiMC/Launcher/assets/2453707/dc74dad2-bc45-4182-9057-178f0c6b78d7)

**Comment by FeedTheChunk** [comment]
From the version number it looks to me like it's probably talking about the Fabric API.  What version of Fabric API are you running?

**Comment by phit** [comment]
the error is talking about fabric api which you can get here https://modrinth.com/mod/fabric-api

**Comment by Shadowblitz16** [comment]
> From the version number it looks to me like it's probably talking about the Fabric API. What version of Fabric API are you running?

I don't know all I did was install fabric through multi mc

> the error is talking about fabric api which you can get here https://modrinth.com/mod/fabric-api

ok thanks
