### ISSUE TITLE
Minecraft crashed when i create a world

### ISSUE THREAD

**Issue by MicheleVeniero** [MultiMC/Launcher#5263]
### Description of bug

https://paste.ee/p/wqWAi

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
