### ISSUE TITLE
Allow opening lan world on launch

### ISSUE THREAD

**Issue by Shadowblitz16** [MultiMC/Launcher#5267]
### Role

I play minecraft with my friends

### Suggestion

I want to launch minecraft and open it to lan automaticly

### Benefit

I use multi mc to do split screen and controller support

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Maybe a command line argument and a option here...
![image](https://github.com/MultiMC/Launcher/assets/2453707/d924b936-1115-4df6-a9f3-83b3e39ff7b7)
To open to lan on launch

**Comment by phit** [comment]
is there a game argument to do this?

**Comment by Shadowblitz16** [comment]
> is there a game argument to do this?

What no! please reopen. 
I am suggesting the a gui and cli option be made to do this

**Comment by phit** [comment]
we can't add a command line option to the game, as the game doesn't have one there's nothing to do here
