### ISSUE TITLE
Recipe for Rail is not shown despite having all necessary ingredients.

### ISSUE THREAD

**Issue by ikunat33** [MultiMC/Launcher#5268]
### Operating System

Linux

### Description of bug

The recipe for Rail is unavailable even though I can manually create them.

### Steps to reproduce

Gather all ingredients for Rail into inventory and try to find Rail recipe in book.
MutiMC 5 Version 0.7.0-3809
Minecraft Java Version 1.20.1

### Suspected cause

Not a bleeding clue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by hendev1** [comment]
https://bugs.mojang.com/browse/MC/issues/MC-123966

You need to craft a minecart, then you can see the recipe for rails.
