### ISSUE TITLE
Use two java paths

### ISSUE THREAD

**Issue by cootshk** [MultiMC/Launcher#5270]
### Role

Using older minecraft versions

### Suggestion

Have 2 java paths in settings - a Java 8 path and a java 17 one

### Benefit

Convienence - you don't have to go into instance settings and manually change the java version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

If the minecraft version is above 1.17, use java 17, otherwise use java 8

in the settings (and install) windows, have two java options, one for j8, and one for j17

similar to how the modrinth launcher does it

**Comment by phit** [comment]
basically https://github.com/MultiMC/Launcher/issues/4013
