### ISSUE TITLE
Error al obtener el token de acceso de Minecraft: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Gateway Time-out

### ISSUE THREAD

**Issue by zlSiro** [MultiMC/Launcher#5272]
### Operating System

Windows

### Description of bug

Error en el token Gateway Time-out

### Steps to reproduce

Error al iniciar

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you can't reach the Minecraft servers you can't login, if you need help troubleshooting you can join our [Discord](https://discord.com/invite/multimc)
