### ISSUE TITLE
access the account

### ISSUE THREAD

**Issue by italoxf1** [MultiMC/Launcher#5276]
### Operating System

Windows

### Description of bug

When I click on the option to access MultiMC through my Microsoft account and then click on the copy the code button, an authentication error occurs and I cannot access my account, but when I copy the code without using the button it does not happen the mistake.

### Steps to reproduce

When I click on the copy code button to access my Microsoft account, an error occurs and I cannot access my account.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 0shu** [comment]
Confirming this also occurs for me when trying to log into my microsoft accounts

**Comment by Phoenixlink1** [comment]
Also getting:

Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable

**Comment by AgainPsychoX** [comment]
I have the same issue. Cannot play the game, even off-line... Pirated version doesn't have such issue, and when I mentioned it as workaround on MultiMC Discord I got banned.

**Comment by phit** [comment]
for the recent comments refer to https://github.com/MultiMC/Launcher/issues/5307#issuecomment-1849057195

@italoxf1 if this still an issue for you please provide your MultiMC-0.log after it happens
