### ISSUE TITLE
How to join Minecraft Classic server

### ISSUE THREAD

**Issue by TristanCorso911** [MultiMC/Launcher#5278]
### Role

I joined my server

### Suggestion

Minecraft Classic Server

### Benefit

How do I join my server

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

You can join my server in Minecraft Classic

**Comment by phit** [comment]
what game version are you actually talking about?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
