### ISSUE TITLE
Grouping Problems

### ISSUE THREAD

**Issue by GodGamers999** [MultiMC/Launcher#5279]
### Description of bug

When I created a new instance in the launcher, everything went in the unnamed group and deleted all the other groups. Also, it renamed 2 of my Alpha 1.16.05 preview instances to " Unnamed Instance" and in one of them, it only showed four options, Upgrade, Notes, Worlds, and Screenshots, with in the Upgrade option, it said "Upgrade is required.
MultiMC now supports old Minecraft versions and all the required features in the new (One Six) instance format. As a consequence, the old (Legacy) format has been entirely disabled and old instances need to be upgraded.
The upgrade will create a new instance with the same contents as the current one, in the new format. The original instance will remain untouched, in case anything goes wrong in the process.
Please report any issues on our [GitHub issues page] (https://github.com/MultiMC/Launcher/issues).
There is also a [discord channel for testing here] (https://discord.gg/GtPmv93)" for some reason. I managed to sort everything back to the way they were, and I'll fix the instances named "Unnamed Instances". I may have fixed the problem for me but please fix this to prevent this from happening to anybody else.

### Steps to reproduce

I chose the instance button in launcher, I chose Beta 1.8.1, Then the Minecraft group was the only other group left other then the unnamed group. The Create mod group gone, the Minecraft group almost gone. 

### Suspected cause

It might be because I deleted the MultiMC log 0 file or something else.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
sounds like your harddrive was full

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
