### ISSUE TITLE
Add forge list for 1.8

### ISSUE THREAD

**Issue by Marti2203** [MultiMC/Launcher#528]
There are public releases of 1.8 forge, but they are not in the launcher list. Will you add them soon?

**Comment by Rostepher** [comment]
It looks like there is builds for 1.8 http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.html

**Comment by peterix** [comment]
And you are free to install "1.8". It works :)

**Comment by xaeror35** [comment]
How do we install 1.8 forge? It doesn't show up in the list? And I cant manually add it to an instance.

**Comment by peterix** [comment]
Do not confuse "1.8" with "1.8.x"
