### ISSUE TITLE
Multi MC Is telling me to Buy Minecraft dispite owning it for years

### ISSUE THREAD

**Issue by KingKillswitch** [MultiMC/Launcher#5282]
### Operating System

Windows

### Description of bug

I tried to launch a new modpack through multi Mc for the first time and it said that i didnt own minecraft and needed to purchase it even though i have owned minecraft for several years at this point, How can i rectify this issue? 

P.S. I do not have the money to purchase minecraft again.

### Steps to reproduce

*Im unaware what to put here
*how do i fix

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
log in at minecraft.net with the same account, multimc has no control over your account, most likely you are using the wrong account
