### ISSUE TITLE
Block texture issue

### ISSUE THREAD

**Issue by JJminecraftguy** [MultiMC/Launcher#5283]
### Description of bug

I tried using c0.24_03 survival test and all the blocks are see through.

I am using windows 11 latest updates and java 8.

Download c0.24_03 survival test from https://minecraft.wiki/w/Java_Edition_Classic_0.24_SURVIVAL_TEST_03

Also about after 50 seconds of playing the lag is so bad it crashes. My laptop is pretty high end to.

Here is log log after it crashed:
MultiMC version: 0.7.0-3813

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.245.96.43, 18.245.96.50, 18.245.96.114, 18.245.96.19]

session.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38]

textures.minecraft.net resolves to:
    [13.107.246.38, 13.107.213.38]

api.mojang.com resolves to:
    [13.107.246.38, 13.107.213.38]

Minecraft folder is:
C:/Users/test/Downloads/mmc-develop-win32/MultiMC/instances/c0.0.13a/.minecraft

Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_381, using 64-bit architecture, from Oracle Corporation.

Main Class:
  com.mojang.minecraft.Minecraft$OS

Native path:
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/instances/c0.0.13a/natives

Traits:
traits no-texturepacks
traits legacyLaunch

Libraries:
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/instances/c0.0.13a/libraries/customjar-1.jar

Native libraries:
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/test/Downloads/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 14556

Using onesix launcher.

Could not find Minecraft path field.
Launching with applet wrapper...
Oct 19, 2023 10:51:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 11
Oct 19, 2023 10:51:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Oct 19, 2023 10:51:52 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Oct 19, 2023 10:51:52 PM net.java.games.input.ControllerEnvironment log
INFO: Failed to initialize device HIDI2C Device because of: java.io.IOException: Failed to acquire device (8007001e)

Flood filled 53630 tiles in 8.0077 ms
LavaCount: 12
Added 1660 mushrooms
271 mobs
com.mojang.minecraft.player.Player@6f27cd67
Process crashed with exit code -1073741819 (0xffffffffc0000005).
Below is an analysis of the exit code. THIS MAY BE INCORRECT AND SHOULD BE TAKEN WITH A GRAIN OF SALT!
System exit code name: STATUS_ACCESS_VIOLATION
System exit code description: The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 19 Oct 2023 22:53:17 -0500
Clipboard copy at: 19 Oct 2023 22:54:29 -0500

### Steps to reproduce

Get version c0.24_03 survival test and play

### Suspected cause

IDK

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by JJminecraftguy** [comment]
thanks
