### ISSUE TITLE
Game not opening once i use forge

### ISSUE THREAD

**Issue by praxzzLOLOL** [MultiMC/Launcher#5285]
### Operating System

Windows

### Description of bug

Ok so I installed a new version of java and everything became fucked, i first restarted my pc which didnt help then i reinstalled multimc deleted everything yk, then i reinstalled my profile cause obviously i want the same one, however i got suprised with it still not working. Not sure what to do now :/

https://paste.ee/p/wecMb (logs)

### Steps to reproduce

Open game
Be disappointed 

### Suspected cause

Something with java

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
