### ISSUE TITLE
MultiMC Error Code 1 (1.6.4)

### ISSUE THREAD

**Issue by Josifekjj** [MultiMC/Launcher#5288]
### Operating System

Windows

### Description of bug

The mmc launcher dissapeared as normaly but like half a second later the game crashed and the launcher pop out back. The log: https://paste.ee/p/eg931

### Steps to reproduce

1. Use ftb private packs

### Suspected cause

Config Files propably?

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to use an older java 8 version for these old game versions, e.g. https://files.multimc.org/downloads/jre-8u51-windows-x64.zip
