### ISSUE TITLE
MultiMC exit code -1

### ISSUE THREAD

**Issue by Josifekjj** [MultiMC/Launcher#5289]
### Operating System

Windows

### Description of bug

When i try to play any FTB private or public pack the game wont even launch and exit code -1 pops out.

### Steps to reproduce

1. play ftb legacy modpacks
2. launch
3. BOOM it crashed

### Suspected cause

something with java i guess?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Josifekjj** [comment]
i forgot log: https://paste.ee/p/ZwJlt

**Comment by FeedTheChunk** [comment]
Looks like the wrong version of java.  MC version 1.6.4 and java 21

**Comment by Josifekjj** [comment]
wtf

**Comment by Josifekjj** [comment]
so what java should i use

**Comment by Josifekjj** [comment]
i tried java 8u51 and it showed the same error

**Comment by phit** [comment]
post log with java 8

**Comment by FeedTheChunk** [comment]
post the log for java 8

**Comment by Josifekjj** [comment]
ok

**Comment by Josifekjj** [comment]
https://paste.ee/p/dpXaB

**Comment by FeedTheChunk** [comment]
Java is version 21.0.1

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#set-instance-java-installation

**Comment by Josifekjj** [comment]
i changed it

**Comment by Josifekjj** [comment]
now it says error code 0

**Comment by Josifekjj** [comment]
so now it says error code 0

**Comment by Josifekjj** [comment]
log here https://paste.ee/p/Y3slx

**Comment by FeedTheChunk** [comment]
Instead of posting to bugs reports from **9 years ago** why don't try and troubleshoot the problem?  It's either a java version issue, Forge version issue or maybe one of the mods in the warnings in you log.  Try disabling all mods see if it'll load.  Try disabling the 5 or 6 mods in the error log and see if it's that.  Try enabling one mod at a time until it fails. Try different versions of Forge, java, etc.

**Comment by Josifekjj** [comment]
not enough items f*cks up the entire modpack

**Comment by FeedTheChunk** [comment]
Well then there's your problem.  It has nothing to do with MultiMC.

**Comment by Josifekjj** [comment]
well idk i just fixed it

**Comment by Josifekjj** [comment]
thanks for  the idea of disabling mods

**Comment by Josifekjj** [comment]
and all the mods are running
