### ISSUE TITLE
MultiMC error code 0

### ISSUE THREAD

**Issue by Josifekjj** [MultiMC/Launcher#5290]
### Operating System

Windows

### Description of bug

When i try to play ftb legacy modpacks it just crashes and error code 0 pops out.

### Steps to reproduce

1. use ftb legacy
2. launch
3. boom it crashed

### Suspected cause

something with java i guess?
log here: https://paste.ee/p/Y3slx

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
dont make new issues, you can continue to get replies in the old one
