### ISSUE TITLE
It will not let me duplicate or make any new instances

### ISSUE THREAD

**Issue by minecrafter354** [MultiMC/Launcher#5293]
### Operating System

Windows

### Description of bug

When I try to create or duplicate the instance, It just says, Failed to commit instance, even after multiple retries. It is being blocked by something. And I don't know why

### Steps to reproduce

- Either try to duplicate the instance by right clicking or try to make a new instance
- Try the alpha versions of minecraft or newer
- If it comes back with that error message then that is it

### Suspected cause

I don't know Because I've tried everything

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
if something on your end is blocking MultiMC's file operations there's nothing we can do, try disabling your AV and make sure you have enough harddrive space, for further support your can ask in the [MultiMC Discord](https://discord.gg/multimc).
