### ISSUE TITLE
Window Resolution Please

### ISSUE THREAD

**Issue by Xiantrius** [MultiMC/Launcher#5294]
### Role

That doesn't play a role in this question.

### Suggestion

Add Please Window Resolution

### Benefit

I use the launcher because of the instances.

### This suggestion is unique

- [ ] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In Englisch Translate:
The window resolution and the maximize function are still missing. Another suggestion from me would be if the window were to run normally in window mode, the position of the window wouldn't be bad either so that you can decide from which position Minecraft starts. That might make the launcher a little more popular.
Would the developers here be kind enough to include this in the next Update?

best regards,
Xiantrius

Original in German Write:
Es fehlt noch die Fensterauflösung und die maximierfunktion. Ausserdem wäre noch ein Vorschlag meiner seits sollte das Fenster normal in Fenstermodus laufen wäre Position des Fenster's auch nicht schlecht das man entscheiden kann von welcher Position aus Minecraft startet. Das würde den Launcher eventuel noch etwas beliebter machen.
Würden die Entwickler hier so freundlich sein und das in nächsten Patch einbauen?

mit freundlichen grüßen,
Xiantrius

**Comment by phit** [comment]
for game versions that support it there's already the window size and maximize checkbox in the settings, for modern versions this is simply not possible without hooking into the game, which MultiMC won't do
