### ISSUE TITLE
Cannot connect to servers from last weekend

### ISSUE THREAD

**Issue by NewAmazingPVP** [MultiMC/Launcher#5295]
### Operating System

Windows

### Description of bug

I have been using MultiMC for around 3 years now, and I have never had this issue before. Recently, last weekend, I couldn't connect to many servers, such as Hypixel, my own private server, pvplegacy, etc. I found out that this issue only persisted for any client instances launched from MultiMC. Using other launchers, such as FeatherMC, Lunar Client, and even Vanilla, allowed me to connect to all the servers. What's funny is that while I couldn't connect to almost any server from any multimc instance client launched, I was still able to connect to MCCI island. Maybe it has custom authentication? I have no idea, but I would appreciate any help to fix this issue. I have tried disabling firewall, disabling antivirus, restarting, etc.—all the normal debugging practices—and none of that has fixed the issue.

### Steps to reproduce

Launch any multimc client instance any version any mods or forge, fabric, vanilla you won't be able to connect to servers

### Suspected cause

I assume there's some issue with the multimc client not passing Mojang authentication??? 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc just launches the game, if this is still an issue for your provide some game logs
