### ISSUE TITLE
All instances launch in offline mode

### ISSUE THREAD

**Issue by notavalable1** [MultiMC/Launcher#5296]
### Description of bug

When i click the regular launch button it asks "choose your offline player name" i click "confirm" then it crashes, so i dont know if these two things are related but i do know that i can't play any modpacks on multimc

### Steps to reproduce

Im not sure how to reproduce this bug but it is really annoying

### Suspected cause

Im not 100% sure but i think it might be because of a proxy or java issue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
