### ISSUE TITLE
[Suggestion] NeoForged

### ISSUE THREAD

**Issue by Kzitold** [MultiMC/Launcher#5299]
### Role

idk. Just getting back into Minecraft, and one thing to another.

### Suggestion

NeoForge

### Benefit

"The cooler Forge."

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Trying to kick my 3-year depression and get back to gaming with my friends. Noticed the Forge Discord server I was in changed to NeoForge, the Neo team told me there was drama on the Forge team, yada yada.
idk. If whatever going on with the old-Forge is not kosher, switch it to Neo. Heard it's the same, but "cooler" dev team.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/5232
