### ISSUE TITLE
Мой майнкрафт крашнулся с кодом: -1

### ISSUE THREAD

**Issue by held2817** [MultiMC/Launcher#5300]
### Description of bug

My Minecraft closed while I was working and the MultiMC console came in.

### Steps to reproduce

[crash-2023-12-05_10.25.20-client.txt](https://github.com/MultiMC/Launcher/files/13556646/crash-2023-12-05_10.25.20-client.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
