### ISSUE TITLE
Cannot login after newest update

### ISSUE THREAD

**Issue by AgainPsychoX** [MultiMC/Launcher#5301]
### Description of bug

Cannot login after newest update.

### Steps to reproduce

![image](https://github.com/MultiMC/Launcher/assets/23557839/c3ea3b5d-d885-4408-9069-5693867523df)

![image](https://github.com/MultiMC/Launcher/assets/23557839/62493a9b-9276-40c7-b345-2ff1bb629fae)

![image](https://github.com/MultiMC/Launcher/assets/23557839/8b2eb40d-4ccb-4d9a-8098-90f31b206ab0)

![image](https://github.com/MultiMC/Launcher/assets/23557839/47c9c6f8-3955-44e0-b122-306d957b9e9e)

![image](https://github.com/MultiMC/Launcher/assets/23557839/d99cb432-57fb-48c5-ac42-4348c7e1b2a4)

(success)

![image](https://github.com/MultiMC/Launcher/assets/23557839/5c865f3d-35c7-4700-9fa4-01f0277ab7d6)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by AgainPsychoX** [comment]
Sometimes it gives different error: 
![image](https://github.com/MultiMC/Launcher/assets/23557839/bd8801ce-6f1d-4ba0-a25b-9bfc9beadb76)

**Comment by AgainPsychoX** [comment]
It's so fucked up I can't play OFFLINE. Why the fuck I need to have account added, or rather, why the fuck it was removed. It's ridiculous. Should I go get pirated launcher??

**Comment by phit** [comment]
nothing was removed and the auth code wasn't changed in almost two years, this was a temporary xbox outage.. unfortunately that happens quite frequently and there's nothing we can do about that

**Comment by AgainPsychoX** [comment]
Why can't I play OFFLINE then.

**Comment by AgainPsychoX** [comment]
Tonight it's similar:
![image](https://github.com/MultiMC/Launcher/assets/23557839/9a1de55b-2f75-43ae-b20a-61b9b335b01f)

I can't play, even off-line.
