### ISSUE TITLE
Skin

### ISSUE THREAD

**Issue by EsoogDrut** [MultiMC/Launcher#5303]
### Operating System

Windows

### Description of bug

Whenever i try to upload my skin in the launcher it displays my skin but in the game im steve.

### Steps to reproduce

d

### Suspected cause

idk

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
does the skin change when you check on minecraft.net?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
