### ISSUE TITLE
forever develop release --> new versioning pattern

### ISSUE THREAD

**Issue by evan0greenup** [MultiMC/Launcher#5305]
### Role

make packaging more easily

### Suggestion

insead of semver, use date as version number like `2023.12.09`

### Benefit

check if my current installation is up-to-date, and make packaging easier.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Because from now on, there will no longer be stable release. keep the version stuck in 0.7.x provide no new information.

And use git commit hash as versioning does not provide information of which one is more updated if the versioning number is different.

datever can be more casual and frequent. 

It can also make downstream packaging more easier.

**Comment by evan0greenup** [comment]
If writing release note takes time. 

Using `git tag` would be **adequate**.

**Comment by phit** [comment]
the versioning will not change for multimc 5, the official releases all use 0.x.x-buildnumber, nobody claimed it will be forever stuck at 0.7.x

**Comment by evan0greenup** [comment]
@phit  will there be a MultiMC 6?

**Comment by phit** [comment]
eventually
