### ISSUE TITLE
macOS: Button text turns white when the button is selected

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5306]
### Operating System

macOS

### Description of bug

Text turns white when button is selected, making the text unreadable
I've also noticed that the box is going through the buttons.
 Suggestion: change the unselected button background color and change the text color when button selected to black ( or white if using dark mode)
<img width="475" alt="Screenshot 2023-12-10 at 15 55 40" src="https://github.com/MultiMC/Launcher/assets/124442838/e0206391-cd8c-449b-ad8d-4bbf3e2fa2cf">

### Steps to reproduce

Settings > Launcher tab
Press any of the page buttons in the launcher tab

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
macOS version? I'm unable to reproduce this on macOS 14.3

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
