### ISSUE TITLE
Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable

### ISSUE THREAD

**Issue by Packsolite** [MultiMC/Launcher#5307]
### Operating System

Windows

### Description of bug

I can no longer login with some of my minecraft accounts using multimc. The login process on the webpage finishes succesfully, yet multimc shows this error: 
![image](https://github.com/MultiMC/Launcher/assets/102829507/550d45fa-6467-4be6-8a41-c2b4ba98ee76)

However, the vanilla launcher works fine.

MultiMC 0.7.0
Windows 11

### Steps to reproduce

- Click on manage accounts 
- "add microsoft account"
-  copy the code from multimc to https://www.microsoft.com/link 
-  login with microsoft and click "allow"
- After it says "login successfull" on the page, multimc shows the error

### Suspected cause

Api changes?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by joakime** [comment]
Happening to me as well.
MultiMC 0.7.0
Linux / Ubuntu 22.0.4

**Comment by joakime** [comment]
The failure also removes the account from the Account Manager.
When adding your account back, it still fails, and the console logs show ...

```
    0.680 D News loading succeeded.
    0.721 D Location header: QUrl("https://files.multimc.org/update/lin64/develop/index.json")
    0.721 D Following redirect to  "https://files.multimc.org/update/lin64/develop/index.json"
    0.721 D Downloading  "https://files.multimc.org/update/lin64/develop/index.json"
    0.722 D Download redirected: "https://files.multimc.org/update/lin64/develop/index.json"
    0.889 D Download succeeded: "https://files.multimc.org/notifications.json"
    0.901 D Task "NetJob(Checking for notifications)" succeeded
    1.140 D Download succeeded: "https://files.multimc.org/update/lin64/develop/index.json"
    1.141 D Task "NetJob(GoUpdate Repository Index)" succeeded
    1.141 D Finished downloading repo index. Checking for new versions.
    1.143 D Processing repository version list.
    9.990 D Task "MSAInteractive(0x39be860)" starting for the first time
    9.991 D AuthFlow: "Logging in with Microsoft account."
    9.991 D DeviceFlow::link
    9.991 D DeviceFlow::setLinked: false
   10.219 D DeviceFlow::onDeviceAuthReplyFinished
   10.220 D DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:

   10.220 D "device_code" :  "...(PRIVAT)..."
   10.220 D "expires_in" :  "900"
   10.220 D "interval" :  "5"
   10.220 D "message" :  "To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code PRIVAT to authenticate."
   10.220 D "user_code" :  "PRIVAT"
   10.220 D "verification_uri" :  "https://www.microsoft.com/link"
   10.220 D DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
   10.221 D DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
   14.757 D PollServer::onPollTimeout: retrying
   19.759 D PollServer::onPollTimeout: retrying
   24.758 D PollServer::onPollTimeout: retrying
   25.834 D DeviceFlow::onVerificationReceived: Emitting closeBrowser()
   25.834 D DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
   25.834 D DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
   25.834 D DeviceFlow::setLinked: true
   25.834 D AuthFlow: "Logging in as an Xbox user."
   25.834 D First layer of XBox auth ... commencing.
   26.142 D Parsing "UToken" :
   26.142 D "UToken" is valid.
   26.142 D AuthFlow: "Getting authorization to access Xbox services."
   26.142 D Getting authorization token for  "http://xboxlive.com"
   26.492 D Parsing "Xbox" :
   26.492 D "Xbox" is valid.
   26.492 D AuthFlow: "Getting authorization to access Mojang services."
   26.492 D Getting authorization token for  "rp://api.minecraftservices.com/"
   26.706 D Parsing "Mojang" :
   26.706 D "Mojang" is valid.
   26.706 D AuthFlow: "Accessing Mojang services."
   26.706 D Getting Minecraft access token...
   26.954 W AuthRequest::onRequestError: Error 401
   26.955 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/launcher/login - server replied: Internal Server Error"
   26.955 W AuthRequest::onRequestError: HTTP status 500 "Internal Server Error"
   26.955 W Reply error: 401
   26.955 C Task "MSAInteractive(0x39be860)" failed:  "Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Internal Server Error"
```

**Comment by IFN3T** [comment]
i have same issue on 0.7.0-3813

5.243 D AuthFlow: "Connexion avec un compte Microsoft."
5.243 D DeviceFlow::link
5.243 D DeviceFlow::setLinked: false
5.633 D DeviceFlow::onDeviceAuthReplyFinished
5.633 D DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:

5.633 D "device_code" :  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
5.633 D "expires_in" :  "900"
5.633 D "interval" :  "5"
5.634 D "message" :  "Pour vous connecter, utilisez un navigateur web pour ouvrir la page https://www.microsoft.com/link et entrez le code XXXXXXXX pour vous authentifier."
5.634 D "user_code" :  "XXXXXXXX"
5.634 D "verification_uri" :  "https://www.microsoft.com/link"
5.634 D DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
5.635 D DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
10.635 D PollServer::onPollTimeout: retrying
15.902 D PollServer::onPollTimeout: retrying
21.242 D PollServer::onPollTimeout: retrying
21.749 D DeviceFlow::onVerificationReceived: Emitting closeBrowser()
21.750 D DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
21.750 D DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
21.750 D DeviceFlow::setLinked: true
21.750 D AuthFlow: "Connexion en tant qu'utilisateur Xbox."
21.750 D First layer of XBox auth ... commencing.
22.363 D Parsing "UToken" :
22.363 D "UToken" is valid.
22.363 D AuthFlow: "Récupération de l'autorisation d'accéder aux services Xbox."
22.364 D Getting authorization token for  "http://xboxlive.com"
23.153 D Parsing "Xbox" :
23.153 D "Xbox" is valid.
23.153 D AuthFlow: "Récupération de l'autorisation d'accéder aux services Mojang."
23.153 D Getting authorization token for  "rp://api.minecraftservices.com/"
23.419 D Parsing "Mojang" :
23.419 D "Mojang" is valid.
23.419 D AuthFlow: "Accès aux services de Mojang."
23.419 D Getting Minecraft access token...
25.461 W AuthRequest::onRequestError: Error 403
25.461 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable"
25.461 W AuthRequest::onRequestError: HTTP status 503 "Service Unavailable"
25.461 W Reply error: QNetworkReply::NetworkError(ServiceUnavailableError)
25.461 C Task "MSAInteractive(0x6bf3238)" failed:  "Impossible d'obtenir le jeton d'accès à Minecraft : Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable"

**Comment by Pristinewonder** [comment]
Windows 10  with MultiMC Version 0.7.0-3813 Had the same issue, did something with the API change like others thought?
I also checked the normal launcher and found no problems.

**Comment by phit** [comment]
microsoft outage, it's been happening the past 4 days wait until their servers recover

**Comment by Pristinewonder** [comment]
Is there any way to see when it comes back up/goes down? I wasn't aware of any Microsoft outages as I've been playing fine the past few days with no problems?

**Comment by phit** [comment]
its been on and off like it is right now every evening around this time, just keep retrying, sadly they got rid of the official status page a couple years ago

**Comment by Pristinewonder** [comment]
Darn. well thanks for the info 👍

**Comment by DeltaBravo** [comment]
fwiw I had to try around 12 times before it finally worked.

"Microsoft loves Open Source"...uh huh; I'm not feelin' the love Microshaft.

**Comment by IFN3T** [comment]
Problem Solved for me at 20:16 (UTC+1)

6.012 D AuthFlow: "Connexion avec un compte Microsoft."
6.012 D DeviceFlow::link
6.012 D DeviceFlow::setLinked: false
6.777 D DeviceFlow::onDeviceAuthReplyFinished
6.777 D DeviceFlow::onDeviceAuthReplyFinished: Tokens returned:

6.777 D "device_code" :  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
6.777 D "expires_in" :  "900"
6.777 D "interval" :  "5"
6.777 D "message" :  "Pour vous connecter, utilisez un navigateur web pour ouvrir la page https://www.microsoft.com/link et entrez le code XXXXXXXXXX pour vous authentifier."
6.777 D "user_code" :  "XXXXXXXXXX"
6.777 D "verification_uri" :  "https://www.microsoft.com/link"
6.777 D DeviceFlow::onDeviceAuthReplyFinished: Device auth request response
6.778 D DeviceFlow::startPollServer: device_ and user_code expires in 900 seconds
11.779 D PollServer::onPollTimeout: retrying
17.108 D PollServer::onPollTimeout: retrying
22.436 D PollServer::onPollTimeout: retrying
27.762 D PollServer::onPollTimeout: retrying
33.140 D PollServer::onPollTimeout: retrying
33.512 D DeviceFlow::onVerificationReceived: Emitting closeBrowser()
33.512 D DeviceFlow::onVerificationReceived: Access token returned for implicit or device flow
33.512 D DeviceFlow::onVerificationReceived: Token expires in 3600 seconds
33.512 D DeviceFlow::setLinked: true
33.512 D AuthFlow: "Connexion en tant qu'utilisateur Xbox."
33.512 D First layer of XBox auth ... commencing.
34.571 D Parsing "UToken" :
34.572 D "UToken" is valid.
34.572 D AuthFlow: "Récupération de l'autorisation d'accéder aux services Xbox."
34.572 D Getting authorization token for  "http://xboxlive.com"
35.391 D Parsing "Xbox" :
35.391 D "Xbox" is valid.
35.391 D AuthFlow: "Récupération de l'autorisation d'accéder aux services Mojang."
35.391 D Getting authorization token for  "rp://api.minecraftservices.com/"
35.794 D Parsing "Mojang" :
35.794 D "Mojang" is valid.
35.794 D AuthFlow: "Accès aux services de Mojang."
35.794 D Getting Minecraft access token...
43.135 D Parsing Mojang response...
43.135 D Mojang response is valid.
43.135 D AuthFlow: "Récupération du profil Xbox."
43.135 D Getting Xbox profile...
44.402 D AuthFlow: "Détermination de la propriété du jeu."
44.402 D Getting entitlements...
45.082 D Parsing Minecraft entitlements...
45.082 D AuthFlow: "Récupération du profil Minecraft."
45.348 D Parsing Minecraft profile...
45.348 D AuthFlow: "Récupération du skin."
46.037 D Task "MSAInteractive(0x478e230)" succeeded
46.039 D Writing account list to "accounts.json"
46.039 D Building JSON data structure.
46.039 D Building account array.
46.039 D Writing account list to file.
46.042 D Saved account list to "accounts.json"
46.042 D Writing account list to "accounts.json"
46.042 D Building JSON data structure.
46.042 D Building account array.
46.042 D Writing account list to file.
46.045 D Saved account list to "accounts.json"

**Comment by orl0pl** [comment]
i fixed that by logging in few times

**Comment by peterix** [comment]
Maybe there's something to be said for handling failures of Minecraft Services when we have a 'good enough' pre-existing tokens. It's not going to give you a full session, but at least we could maybe let people play the game offline.

Basically, if Minecraft Services has a `HTTP status 503 "Service Unavailable"`, we could soft-fail.

It should be reasonably easy to simulate the scenario.
Requires testing.

**Comment by phit** [comment]
right now even clicking play offline doesnt actually play offline, see https://github.com/MultiMC/Launcher/issues/5078

**Comment by lilbuddie** [comment]
im having this problem too as of today for some reason. im using a fork to multi mc not the actual multi mc it was working good in like 10am but now its broken
