### ISSUE TITLE
i cant add my microsoft account to MultiMC

### ISSUE THREAD

**Issue by Rafalastt** [MultiMC/Launcher#5308]
### Operating System

Windows

### Description of bug

the vanilla launcher works fine i just cant add my microsoft
Windows 11
The login process on the webpage finishes succesfully, yet multimc shows this error:
![Captura de ecrã 2023-12-10 190646](https://github.com/MultiMC/Launcher/assets/153457035/54678cbb-718a-43e1-97e1-038d907d30da)

### Steps to reproduce

Click on manage accounts
"add microsoft account"
copy the code from multimc to microsoft.com/link
login with microsoft and click "allow"
After it says "login successfull" on the page, multimc shows the error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Hilpop** [comment]
I am having the same problem. It worked earlier but said the session expired so I tried again and again but it would not work this time.

**Comment by phit** [comment]
microsoft outage, you'll have to wait
