### ISSUE TITLE
Async Microsoft login

### ISSUE THREAD

**Issue by andreasdc** [MultiMC/Launcher#5309]
### Role

Faster startup times

### Suggestion

Async login to Microsoft

### Benefit

Faster startup times

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello, I think a nice feature would be async loggin in on the Microsoft account. Just the login phase takes couple seconds of the startup time, if it's possible to do it in the background while already loading the game, we would achieve way faster startup times. Keep up the good work guys!

**Comment by phit** [comment]
that is not possible as the token is part of the games launch arguments

**Comment by andreasdc** [comment]
What is it needed for? How does UltimMC work?
