### ISSUE TITLE
Start of Minecraft 1.20.3 and 1.20.4 with Forge not possible

### ISSUE THREAD

**Issue by radiantraptor** [MultiMC/Launcher#5310]
### Operating System

Linux

### Description of bug

When I try to start a Minecraft 1.20.3 or 1.20.4 instance and install the available Forge versions an error like the following is shown:

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance 1.20.4' failed to process:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.0.8/forge-1.20.4-49.0.8-launcher.jar

Maybe this is not a bug at all, when I manually edit the Forge configuration the url of the error is not in the .json, and the forge installer, shim and universal files have been downloaded.
It feels like there is something cached from somewhere, but I can't find out where the url comes from.

### Steps to reproduce

-Add a Minecraft 1.20.3 or 1.20.4 instance in Multimc.
-Install the latest version of forge via Multimc.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GuiTaek** [comment]
If it helps, Forge is confusing about which version they support. In the official minecraft loader, forge also crashes for version 1.20.3. Here is the crash:
[crash-2023-12-17_18.47.10-client.txt](https://github.com/MultiMC/Launcher/files/13697245/crash-2023-12-17_18.47.10-client.txt)

On [https://forums.minecraftforge.net/topic/125488-rules-and-frequently-asked-questions-faq/](this) webpage, they say, 1.20.3 is not supported, but 1.20.4. On [https://forums.minecraftforge.net/topic/91712-supported-version-directory/](this) page, they say, they neither support 1.20.3 nor 1.20.4. On the official download page, there is no stable version for these two minecraft versions. If anyone found the solution, I'm interested in the solution, as I'd like to know, which versions are ready to be modded.

**Comment by phit** [comment]
the forge forums are pretty much abandoned as the project split into neoforge

either way with my patch here you can get to the launch state https://github.com/phit/meta/commit/24642e85f7c387f57fa6c38917d53e11d7d31a9d but there's probably some more work left to do in forgewrapper / or ideally just rip out forge and replace it with neoforge for newer mc versions

**Comment by radiantraptor** [comment]
Thanks for clarifying that! I thing I'm going to switch to NeoForge then.

**Comment by HanSolo0001** [comment]
Hey, I'm not sure if this helps with Linux, but I'm on Windows, and noticed an issue with this. The web URL that is called does not match what it should be. 

What is called is:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.0.19/forge-1.20.4-49.0.19-launcher.jar

When going to that site, it says you want files.minecraftforge...like this:
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.4.html (this isn't where that jar is actually located, because there's a download installer button on this page).

**Comment by phit** [comment]
yes none of those URL's are correct, please see the linked issues, the proper fixes are ready and are just waiting to be merged

**Comment by WiBlum** [comment]
Hello, still in progress ? I tried to see in forge installer if there is any of those url but don't work and manual install from the instances folder "1.20.4/.minecraft" using "java -jar forge-1.20.4-49.0.22-installer.jar" doesn't do anything.

**Comment by phit** [comment]
waiting on https://github.com/MultiMC/meta/pull/17 to be merged

**Comment by WiBlum** [comment]
Pretty nice ! 
Works well now, thanks you so much, actually it's seems work fine with Forge 49.0.22
I love to see it in the new update
