### ISSUE TITLE
Wont start idk why

### ISSUE THREAD

**Issue by CreepyCreeper199** [MultiMC/Launcher#5314]
### Description of bug

My game crashed since then ive gotten this error message 
MultiMC version: 0.7.0-3813

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.160.172.117, 18.160.172.91, 18.160.172.93, 18.160.172.50]

session.minecraft.net resolves to:
    [2620:1ec:46::57, 2620:1ec:bdf::57, 13.107.213.57, 13.107.246.57]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::71, 2620:1ec:46::71, 13.107.246.71, 13.107.213.71]

api.mojang.com resolves to:
    [2620:1ec:46::57, 2620:1ec:bdf::57, 13.107.246.71, 13.107.213.71]

Minecraft folder is:
G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jdk-17.0.8.7-hotspot/bin/javaw.exe

Checking Java version...
Java is version 17.0.8, using 64-bit architecture, from Eclipse Adoptium.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/intermediary/1.20/intermediary-1.20.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.21/fabric-loader-0.14.21.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.20/minecraft-1.20-client.jar

Native libraries:
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] (Fabric)SculkHorn-1.20-1.4.1.jar
  [✔️] 3dskinlayers-fabric-1.5.4-mc1.20.1.jar
  [✔️] AC-Revitalized-1.20-3.1FC.jar
  [✔️] additionallanterns-1.0.5-fabric-mc1.20.jar
  [✔️] AdditionalStructures-1.20.x-(v.4.2.0).jar
  [✔️] advancednetherite-fabric-2.0.2-1.20.jar
  [✔️] adventurez-1.4.18.jar
  [✔️] aggregate-1.1.0-1.20.jar
  [✔️] AmbientEnvironment-fabric-1.20-10.0.0.3.jar
  [✔️] AmbientSounds_FABRIC_v5.2.20_mc1.20.1.jar
  [✔️] amethyst_core-1.2.1+1.20.1.jar
  [✔️] amethyst_imbuement-1.20.1-05.jar
  [✔️] animal_feeding_trough-1.0.3+1.20.jar
  [✔️] appleskin-fabric-mc1.20-2.5.0.jar
  [✔️] architectury-9.1.12-fabric.jar
  [✔️] Armorful-2.0.1+1.20.jar
  [✔️] async-locator-fabric-1.20-1.3.0.jar
  [✔️] backslot-1.2.13.jar
  [✔️] backslotaddon-1.1.0.jar
  [✔️] balm-fabric-1.20-7.0.7 (1).jar
  [❌] BarteringStation-v7.0.0-1.20-Fabric.jar.disabled (disabled)
  [✔️] bclib-3.0.12.jar
  [✔️] BedBenefits-Forge-1.20.1-13.0.1.jar
  [✔️] BetterAdvancements-Fabric-1.20-0.3.2.159.jar
  [✔️] betterarcheology-1.0.2.jar
  [✔️] bettercombat-fabric-1.7.2+1.20.1.jar
  [✔️] better-end-4.0.9.jar
  [✔️] BetterF3-7.0.1-Fabric-1.20.1.jar
  [✔️] bettermounthud-1.2.2.jar
  [✔️] betterstats-2.10.3+1.20.1.jar
  [✔️] BetterTridents-v7.0.0-1.20-Fabric.jar
  [✔️] biomemakeover-FABRIC-1.20.1-1.10.2.jar
  [✔️] blissful-butterflies-1.2.0.jar
  [✔️] blockus-2.7.5+1.20.1.jar
  [✔️] BOMD-1.7-1.20.jar
  [✔️] Bookshelf-Fabric-1.20-19.0.16.jar
  [✔️] caffeinated-1.0.3.jar
  [✔️] caracal-1.20-2.3.3.jar
  [✔️] cardinal-components-api-5.2.1.jar
  [✔️] castle_dungeons-4.0.0-1.20-fabric.jar
  [✔️] cd.jar
  [✔️] CHAS-1.20-1.10-Fabric.jar
  [❌] chorus-links-1.9.1+1.20.1.jar.disabled (disabled)
  [✔️] Chunky-1.3.92.jar
  [✔️] cleancut-fabric-6.0+mc1.19.1-mc1.20.x.jar
  [✔️] cloth-config-11.1.106-fabric.jar
  [✔️] Clumps-fabric-1.20-11.0.0.2.jar
  [✔️] clutter-1.20-0.4.3.jar
  [✔️] collective-1.20.0-6.57.jar
  [✔️] combatroll-fabric-1.2.1+1.20.1.jar
  [✔️] comforts-fabric-6.3.3+1.20.1.jar
  [✔️] Controlling-fabric-1.20-12.0.2.jar
  [✔️] cozy-1.1.0-fabric.jar
  [✔️] CreativeCore_FABRIC_v2.10.28_mc1.20.1.jar
  [✔️] creeperoverhaul-3.0.1-fabric.jar
  [❌] CreoLib-1.20.1-1.0.0-beta.24.jar.disabled (disabled)
  [❌] CreoLib-1.20-1.0.0-beta.15.jar.disabled (disabled)
  [✔️] Croptopia-1.20-FABRIC-2.2.2.jar
  [✔️] ctov-3.3.2.jar
  [✔️] DarkPaintings-Fabric-1.20-16.0.2.jar
  [✔️] dawn-5.0.0.jar
  [❌] Decorative+Blocks-fabric-1.20.1-4.0.2.jar.disabled (disabled)
  [❌] Decorative+Blocks-fabric-1.20-4.0.0.jar.disabled (disabled)
  [✔️] dehydration-1.3.4.jar
  [✔️] DisableCustomWorldsAdvice-4.1.jar
  [✔️] doapi-1.2.6-fabric.jar
  [✔️] drippyloadingscreen_fabric_2.2.2_MC_1.20-1.20.1.jar
  [❌] Dungeon-and-Taverns-Mod-Fabric-1.20.jar.disabled (disabled)
  [✔️] dungeons-and-taverns-v2.1.4.jar
  [✔️] DungeonsArise-1.20.1-2.1.56-fabric-beta.jar
  [✔️] dynamiccrosshair-7.0.4+1.20-fabric.jar
  [✔️] dynamiccrosshair-compat-3.2+1.20.1.jar
  [✔️] dynamic-fps-2.4.0.jar
  [✔️] earth2java-fabric-1.10.1+1.20.jar
  [✔️] EchoChest-v7.0.1-1.20-Fabric.jar
  [❌] ecotones-0.9.3.jar.disabled (disabled)
  [❌] elytratrims-1.1.10-beta.3+1.20.jar.disabled (disabled)
  [✔️] enchantment-lore-1.3.2+MC1.20-1.20.1.jar
  [✔️] EnchantWithMob-1.20.1-10.6.0.jar
  [✔️] enhancedblockentities-0.9+1.20.jar
  [✔️] entityculling-fabric-1.6.2-mc1.20.jar
  [✔️] entity-view-distance-1.1.2+1.20.jar
  [✔️] explorify-v1.3.0-mc1.20u1.20.1.jar
  [✔️] extractpoison-1.20.0-3.1.jar
  [✔️] fabric-api-0.83.0+1.20.jar
  [✔️] fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
  [✔️] fabric-release-happytrails-1.20-83.9.3.jar
  [✔️] fabric-seasons-2.2.1+1.20.jar
  [✔️] fabric-seasons-croptopia-2.2.2-compat-1.0.jar
  [✔️] fallingleaves-1.15.2+1.20.1.jar
  [✔️] FallingTree-1.20-4.0.0.jar
  [✔️] fancymenu_fabric_2.14.9_MC_1.20.jar
  [❌] fastminecart-1.0.0.jar.disabled (disabled)
  [✔️] ferritecore-6.0.0-fabric.jar
  [✔️] firstperson-fabric-2.2.3-mc1.20.jar
  [✔️] fish_of_thieves-mc1.20.1-v3.0.2-fabric.jar
  [✔️] fleshz-1.5.0.jar
  [✔️] foodables-1.0.1-1.20+.jar
  [✔️] food-plus-2.3+1.20.1.jar
  [✔️] ForgeConfigAPIPort-v7.0.0-1.20-Fabric.jar
  [✔️] FriendlyFire-Forge-1.20-17.0.1.jar
  [✔️] friendsandfoes-beekeeperhut-fabric-mc1.20-1.3.0.jar
  [✔️] friendsandfoes-fabric-mc1.20.1-1.9.3.jar
  [✔️] friendsandfoes-flowerymooblooms-fabric-mc1.20-1.1.0.jar
  [✔️] frycmobvariants-4.2.2+1.20.jar
  [✔️] fzzy_core-0.2.5.1+1.20.1.jar
  [✔️] geckolib-fabric-1.20-4.2.jar
  [✔️] geophilic-v2.0.0-mc1.20u1.20.1.jar
  [✔️] giant-crops-1.20-1.0.1.jar
  [✔️] global_packs-fabric-1.19.4-1.16.1_fabric.jar
  [❌] glowing-torchflower-mc1.20-rc1-1.0.0.jar.disabled (disabled)
  [❌] great-big-world-1.20.1-1.2.7.jar.disabled (disabled)
  [✔️] grizzlybear-1.20-1.6.1.jar
  [✔️] HangGlider-v7.0.0-1.20-Fabric.jar
  [✔️] healingcampfire-1.20.0-5.1.jar
  [✔️] horseinboat-fabric-1.1.4.jar
  [✔️] horse-stats-vanilla-4.3.0.jar
  [✔️] immersive_aircraft-0.5.2+1.20-fabric.jar
  [✔️] Incendium_1.20.1_v5.3.1.jar
  [✔️] indium-1.0.18+mc1.20.jar
  [✔️] interactic-0.2.0+1.20.jar
  [✔️] InventorySorter-1.9.0-1.20.jar
  [✔️] iris-mc1.20-1.6.4.jar
  [✔️] ItemLocks-Fabric-1.20-1.3.2.jar
  [✔️] jamlib-0.6.1+1.20.x.jar
  [✔️] jei-1.20-fabric-14.0.0.11.jar
  [✔️] jobsaddon-1.1.2.jar
  [✔️] just-end-anchor-1.0.2-1.20.jar
  [✔️] keepmysoiltilled-1.20.0-2.0.jar
  [✔️] konkrete_fabric_1.6.1_MC_1.20.jar
  [✔️] krypton-0.2.3.jar
  [✔️] lambdynamiclights-2.3.1+1.20.1.jar
  [❌] language-reload-1.5.8+1.20.1.jar.disabled (disabled)
  [✔️] lenientdeath-1.20.1-0.9.4.jar
  [✔️] letsdo-vinery-fabric-1.4.4.jar
  [✔️] levelz-1.4.9.jar
  [✔️] libz-1.0.1.jar
  [❌] linkart-5.2.0-1.20.jar.disabled (disabled)
  [✔️] lithium-fabric-mc1.20-0.11.2.jar
  [✔️] mavapi-1.1.1-mc1.20.jar
  [✔️] mavm-1.2.4-mc1.20.jar
  [✔️] mcdw-8.0.3.jar
  [✔️] mcw-doors-1.1.0fabric-mc1.20.jar
  [❌] mcw-fences-1.0.7-mc1.20.1fabric.jar.disabled (disabled)
  [✔️] mcw-furniture-3.2.0-mc1.20fabric.jar
  [✔️] mcw-trapdoors-1.1.1-mc1.20fabric.jar
  [✔️] memoryleakfix-fabric-1.17+-1.1.1.jar
  [✔️] midnightlib-fabric-1.4.1.1.jar
  [✔️] modmenu-7.0.1.jar
  [✔️] moonlight-1.20-2.5.12-fabric.jar
  [✔️] mooshroomspawn-1.20.0-3.3.jar
  [✔️] MoreBows-1.0.11+1.20.x.jar
  [❌] MoreDecorativeBlocks-1.20.1-1.0.4-[FABRIC].jar.disabled (disabled)
  [✔️] MoreDecorativeBlocks-1.20-1.0.3-[FABRIC] (1).jar
  [✔️] more-geodes-1.8.2.jar
  [✔️] MouseTweaks-fabric-mc1.20-2.25.jar
  [✔️] mru-0.2.1+1.20.jar
  [✔️] Neat-1.20-35-FABRIC.jar
  [✔️] NetherChested-v7.0.1-1.20-Fabric.jar
  [✔️] no-telemetry-1.7.0.jar
  [✔️] notenoughanimations-fabric-1.6.4-mc1.20.jar
  [✔️] nutritious-feast-1.7.1.jar
  [❌] Nyctophobia_1.9_(FABRIC)_for_1.20+.jar.disabled (disabled)
  [✔️] nyfsquiver-1.20.1-fabric-1.0.1.jar
  [✔️] Origins-1.20.1-1.10.0.jar
  [✔️] owo-lib-0.11.1+1.20.jar
  [✔️] Packbackplus-0.5.0.jar
  [✔️] packedup-1.0.29-fabric-mc1.20.jar
  [✔️] panorama_screens-1.0+fabric+mc1.20.jar
  [✔️] partyaddon-1.0.3.jar
  [✔️] phantoms-see-phantoms-1.0.1-1.20.x.jar
  [✔️] player-animation-lib-fabric-1.0.2-rc1+1.20.jar
  [✔️] polymorph-fabric-0.49.0+1.20.1.jar
  [✔️] promenade-4.1.0.jar
  [✔️] PuzzlesLib-v7.0.9-1.20-Fabric.jar
  [✔️] rare-ice-0.6.0.jar
  [✔️] reeses_sodium_options-1.6.2+mc1.20.1-build.85.jar
  [✔️] RegionsUnexploredFabric-0.4.1+1.20.jar
  [✔️] repurposed_structures-7.0.0+1.20-fabric.jar
  [✔️] resourcefulconfig-fabric-1.20-2.0.0.jar
  [✔️] ResourcePackOverrides-v7.0.0-1.20-Fabric.jar
  [✔️] revive-1.0.7.jar
  [✔️] ridehud-1.2.3+1.20.jar
  [✔️] rpgdifficulty-1.3.12.jar
  [✔️] rpgz-0.5.3.jar
  [✔️] sculk_depths-1.20.1-0.0.7.jar
  [✔️] Searchables-fabric-1.20-1.0.2.jar
  [✔️] ShoulderSurfing-Fabric-1.20.1-2.4.1.jar
  [✔️] skeletonhorsespawn-1.20.0-3.6.jar
  [✔️] sodium-extra-0.4.23+mc1.20.1-build.106.jar
  [✔️] sodium-fabric-mc1.20-0.4.10+build.27.jar
  [✔️] soundphysics-fabric-1.20-1.1.1.jar
  [✔️] spark-1.10.42-fabric.jar
  [✔️] spellbound-weapons-v4.0.5f.jar
  [✔️] spelunker-1.5.3-mc1.20.jar
  [✔️] Stoneworks-v7.0.1-1.20-Fabric.jar
  [✔️] Structory_1.20.1_v1.3.2.jar
  [✔️] supermartijn642configlib-1.1.7-fabric-mc1.20 (1).jar
  [✔️] supermartijn642corelib-1.1.12a-fabric-mc1.20.jar
  [✔️] supplementaries-1.20-2.5.11-fabric.jar
  [❌] survivality-1.20.1-1.3.0.jar.disabled (disabled)
  [✔️] TerraBlender-fabric-1.20.1-3.0.0.164.jar
  [❌] TerraBlender-fabric-1.20-3.0.0.163.jar.disabled (disabled)
  [❌] TerraBlender-fabric-1.20-3.0.0.169.jar.disabled (disabled)
  [✔️] Terralith_1.20.x_v2.4.1.jar
  [❌] terrestria-6.0.10.jar.disabled (disabled)
  [✔️] terrestria-6.0.4.jar
  [✔️] The_Graveyard_2.9.1_(FABRIC)_1.20+.jar
  [✔️] tidal-towns-1.1.jar
  [✔️] TinySkeletons-v6.0.0-1.20-Fabric.jar
  [✔️] Tips-Fabric-1.20-11.0.1.jar
  [✔️] ToolStats-Fabric-1.20-15.0.3.jar
  [✔️] TravelersBackpack-1.20-9.0.2.jar
  [✔️] trinkets-3.7.1.jar
  [✔️] unloadedactivity-0.4.4+1.20.x.jar
  [✔️] utilitybelt-1.3.3+1.20.x.jar
  [✔️] vanillaconfig-1.2.7+1.20.jar
  [✔️] Variety_Aquatic-fabric-1.20-1.0.4.8.jar
  [✔️] VarietyAPI-Fabric-1.0 (1).jar
  [✔️] villagerleads-0.0.1.jar
  [✔️] villagernames-1.20.0-5.2.jar
  [✔️] villagespawnpoint-1.20.0-4.0.jar
  [❌] visuality-0.7.0+1.20.jar.disabled (disabled)
  [✔️] VisualWorkbench-v7.0.0-1.20-Fabric.jar
  [✔️] voidz-1.0.9.jar
  [✔️] waystones-fabric-1.20-14.0.1.jar
  [✔️] WilderWild-2.0.4-Fabric+1.20.jar
  [✔️] windchimes-1.2.4+1.20.jar
  [✔️] woof-4.0.2+1.20.jar
  [✔️] Xaeros_Minimap_23.6.0_Fabric_1.20.jar
  [✔️] XaerosWorldMap_1.31.0_Fabric_1.20.jar
  [✔️] zmedievalmusic-fabric-1.20.1-2.1.jar
  [✔️] zombiehorsespawn-1.20.0-4.6.jar

Params:
  --username Menoetius69 --version 1.20 --gameDir G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/.minecraft --assetsDir G:/mmc-stable-win32 (1)/MultiMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
MultiMC: Log upload triggered at: 23 Dec 2023 22:25:08 -0600
MultiMC: Log uploaded to: https://api.paste.ee/p/huRFx
Clipboard copy at: 23 Dec 2023 22:30:52 -0600

### Steps to reproduce

Not sure 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RedClouud** [comment]
_Note: I don't develop here, I'm just naively reading the logs and trying to help_ :)

Looks some of your native libraries won't load: `Couldn't extract native jar...`

For each affected library, I would:
1. Make sure that you have access to each of the locations in the error logs (below)
2. Find out where the library is used and disable it if you can (e.g. if one is used in a mod, disable the mod)
3. Hopefully not go insane
4. Done :)

### Error logs
```
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar' to destination 'G:/curseforge/minecraft/Instances/Another RPG Pack [FABRIC] 1.20/natives'
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar' to destination ...
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar' to destination ...
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar' to destination ...
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar' to destination ...
Couldn't extract native jar 'G:/mmc-stable-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar' to destination ...
```

### Affected libraries
```
glfw-3.3.1-natives-windows.jar
jemalloc-3.3.1-natives-windows.jar
openal-3.3.1-natives-windows.jar
stb-3.3.1-natives-windows.jar
5.3.1-natives-windows.jar
```
### Unaffected libraries

```
tinyfd-3.3.1-natives-windows.jar
```

Hope you had a great holiday and happy new year to you!

**Comment by phit** [comment]
restart your pc and make sure those folders are writable by your user

**Comment by RedClouud** [comment]
Is it fixed @CreepyCreeper199?
