### ISSUE TITLE
skins stopped working

### ISSUE THREAD

**Issue by KE888888888** [MultiMC/Launcher#5316]
### Operating System

MacOS

### Description of bug

I was playing minecraft beta 1.7.3 a few days ago and have been playing quite a while on multimc, and my skin has worked fine, got the "skinfix mod" and it worked, I havn't changed anything

but yesterday, I started playing and realised my skin wasn't on, I uploaded it on mojangs website, uploaded it on multimc, nothing works. it works on the normal minecraft launcher in modern versions, there's no reason it shouldn't work in beta as I'm using skin fix mod and it's been working for the past few months

### Steps to reproduce

I'm using mongsters beta 1.7.3 instance which you can get from https://discord.com/channels/1095527092508172318/1171914852428685322

(this has skin fix on it)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
