### ISSUE TITLE
When importing modpack, MultiMC will freeze if the zip archive is over 10MB.

### ISSUE THREAD

**Issue by graytoowolf** [MultiMC/Launcher#5318]
### Operating System

Windows

### Description of bug

When importing modpack, MultiMC will freeze if the zip archive is over 10MB.

### Steps to reproduce

When importing modpack, MultiMC will freeze if the zip archive is over 10MB.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
do you have an example?

**Comment by graytoowolf** [comment]
> 你有例子吗？

https://legacy.curseforge.com/minecraft/modpacks/stacia-2-expert/files

For example, import this modpack. MultiMC will be unresponsive for a long time

This modpack is only 34.82 MB. There must be no response for at least 20 minutes.

https://github.com/MultiMC/Launcher/assets/57069542/f88c0e3a-3939-4c60-ae8f-02efc57d697d

**Comment by phit** [comment]
multimc can not import curseforge modpacks
