### ISSUE TITLE
Crashes on "Freezing Data"

### ISSUE THREAD

**Issue by Gray-Person** [MultiMC/Launcher#5319]
### Operating System

Windows

### Description of bug

I expected my game to load yet it didnt

### Steps to reproduce

Not relevant

### Suspected cause

Not sure sadly

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Gray-Person** [comment]
Log: https://api.paste.ee/p/SAKeW

**Comment by phit** [comment]
Assign more memory to the game https://github.com/MultiMC/Launcher/wiki/Java-settings#memory

**Comment by Gray-Person** [comment]
When ever I do it says it cant allocate for it, I have more than enough memory on my pc

**Comment by phit** [comment]
then you need to install a proper 64-bit java version https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
