### ISSUE TITLE
output log: api.paste.ee/p/a6hQq

### ISSUE THREAD

**Issue by Sulyman200** [MultiMC/Launcher#5324]
### Description of bug

game wont run, runs just fine on 1.18 but on latest version it wont run

### Steps to reproduce

?

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
where did you get this multimc from and can you please launch the instance online once

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
