### ISSUE TITLE
Can't launch,  log: https://api.paste.ee/p/DH1zd

### ISSUE THREAD

**Issue by slipperysnake212** [MultiMC/Launcher#5327]
### Operating System

Windows

### Description of bug

trying to play on a server with friends not sure what the issue is

### Steps to reproduce

Download modpack and plane mod
add instance for modpack
add plane mod
launch mc
Log: https://api.paste.ee/p/DH1zd

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
"The java binary "" couldn't be found. Please set up java in the settings"  You don't have Java setup the settings for the instance.

**Comment by slipperysnake212** [comment]
> "The java binary "" couldn't be found. Please set up java in the settings" You don't have Java setup the settings for the instance.

so I dont have java in the correct settings for the instance?  which means I need to.... search up how to put into an instance? or is there a certain place a file needs to go or do I need to download another Java? or how do I fix this lol

**Comment by FeedTheChunk** [comment]
Edit Instance -> Settings

**Comment by slipperysnake212** [comment]
> Edit Instance -> Settings

If I got this error next: Minecraft 1.18 Pre Release 2 and above require the use of Java 17.  is that a simple download java17 instead?

**Comment by phit** [comment]
yep https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
