### ISSUE TITLE
MultiMC stuck in "working" loop when trying to launch Minecraft on a (now-invalid, migrated) Mojang account

### ISSUE THREAD

**Issue by PaladinOne** [MultiMC/Launcher#5329]
### Operating System

Windows

### Description of bug

I haven't launched MultiMC in several years, and in that time my Mojang account was migrated to a Microsoft account. Upon trying to launch a MultiMC instance, the launcher gets stuck in an endless, unbreakable loop of flickering the "Working" launch popup, opening the popup for a split second then closing then reopening it. The speed of popups is fast enough that MultiMC cannot be interacted with and has to be closed from Task Manager.
I updated MultiMC to 0.7.0-3813 via the auto-update however that didn't fix me.

Checking the MultiMC log, I found this sequence of lines repeated endlessly about every 100ms:

   28.942 D Writing account list to "accounts.json"
   28.942 D Building JSON data structure.
   28.942 D Building account array.
   28.942 D Writing account list to file.
   28.945 D Saved account list to "accounts.json"
   28.946 C Task "Yggdrasil(0x6f7fb58)" failed while not running!!!!:  "Authentication operation failed due to a network error: Error transferring https://authserver.mojang.com/refresh - server replied: Gone (207)"
   28.948 D Task "MojangRefresh(0x6fd11d0)" starting for the first time
   28.948 D AuthFlow: "Logging in with Mojang account."
   28.948 D Task "Yggdrasil(0x6f7f7d8)" starting for the first time
   29.021 C Task "Yggdrasil(0x6f7f7d8)" failed:  "The Mojang account no longer exists. It may have been migrated to a Microsoft account."
   29.022 C Task "MojangRefresh(0x6fd11d0)" failed:  "Mojang user authentication failed."

Updating MultiMC's user list to have my Microsoft account in it fixed the issue and let me launch the game, so the real reason I'm reporting this here as a bug is that MultiMC got stuck in an infinite loop re-trying to log in to an account which does not exist (a task which cannot succeed no matter how many times it re-tries it), rather than stopping after the first failure and popping up an error message.

### Steps to reproduce

* Have an old MultiMC install, with an old (now-Migrated) Mojang account previously authenticated, and set as the account to launch as
* Attempt to launch Minecraft
* Observe the infinite loop you get stuck in
* Check the logs and see this error sequence looped infinitely

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GLMidnight** [comment]
It looks as if you're logging in to the Mojang account rather than the Microsoft account. Try logging in with Microsoft.

**Comment by phit** [comment]
they quite literally said that, that's the bug.. these accounts need to be removed from the launcher

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/commit/7bd130ebaff4f0588099e111e292abfb261b8bd7
