### ISSUE TITLE
Can't open snapshot 23w42a

### ISSUE THREAD

**Issue by AngelToad465** [MultiMC/Launcher#5330]
### Operating System

Windows

### Description of bug

fails to install LWJGL 3
LOG: https://paste.ee/p/1dvcG

### Steps to reproduce

I think it's self-explanatory

### Suspected cause

java 21 not installed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
disable system openal and glfw, and update mutlimc
