### ISSUE TITLE
Stuck at launching

### ISSUE THREAD

**Issue by GurteX** [MultiMC/Launcher#5331]
### Operating System

Windows

### Description of bug

Stuck at Logging in as an Xbox user. Impossible to close the launcher, only closable in task manager

~~Only starts if the actual official minecraft launcher is open.~~

### Steps to reproduce

Start any instance

### Suspected cause

  201.481 W AuthRequest::onRequestError: Error 99
  201.481 W AuthRequest::onRequestError: Error string:  "Connection timed out"
  201.481 W AuthRequest::onRequestError: HTTP status 0 ""
  201.481 W Reply error: QNetworkReply::NetworkError(UnknownNetworkError)
  201.483 C Task "MSASilent(0x44065e8)" failed:  "Failed to get authorization for                                                                                                Xbox services. Error %2."
  201.498 D Task "MSASilent(0x4407e68)" starting for the first time

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
make sure your PC can reach and login at xbox.com

**Comment by GurteX** [comment]
> make sure your PC can reach and login at xbox.com

- I can reach the internet just fine
- I can reach xbox.com website
- I can reach their login page
- Its only the launcher thats stuck, i wouldnt make an issue if i didnt double check

**Comment by krazeral** [comment]
I have this problem too right now.

**Comment by GurteX** [comment]
> I have this problem too right now.

i believe that you can easily fix this error by changing your dns to google or cloudflare. closed for now

**Comment by krazeral** [comment]
I had google dns, tried cloudflare - same result

**Comment by krazeral** [comment]
I checked a lot of things, I logged into my account after turning on VPN on my PC and also this only needs to be done once. I believe in my case this is due to some sanctions on Russia. Maybe it will help someone.

**Comment by GurteX** [comment]
> I checked a lot of things, I logged into my account after turning on VPN on my PC and also this only needs to be done once. I believe in my case this is due to some sanctions on Russia. Maybe it will help someone.

not in my case but nice that you fixed it i guess
