### ISSUE TITLE
Minecraft error

### ISSUE THREAD

**Issue by MicheleVeniero** [MultiMC/Launcher#5333]
### Operating System

Windows

### Description of bug

Modpack error 

### Steps to reproduce
Here the log:
https://paste.ee/p/McrcK

### Suspected cause

Problably one of the mod make conflict

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
[Using the right Java](https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java )
