### ISSUE TITLE
Ownership of Minecraft on Microsoft account not recognized

### ISSUE THREAD

**Issue by Quippits** [MultiMC/Launcher#5334]
### Operating System

Windows

### Description of bug

I've attempted to log in with an account that I am 100% sure owns Minecraft on PC, but it is still showing me this error message, leaving me unable to use the software. 
![image](https://github.com/MultiMC/Launcher/assets/94474934/b6d9c412-a9c8-42b5-9bde-89dcc03b8c65)
Yes, I am 100% sure I am using the correct account.

### Steps to reproduce

Not sure how to reproduce, but I'm using MultiMC exactly as intented. Still happens when trying to open any instance of any version of Minecraft.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
please go to minecraft.net and check your game ownership, compare the username on minecraft.net to the one listed in multimc

**Comment by Quippits** [comment]
I have done so.
Again, as I've said, I am using a Microsoft account which owns Minecraft. I can login and play Minecraft under my username, EighthPompano33, using the modern Minecraft launcher, but when trying to use MultiMC, using the same username and Microsoft account, I am told by MultiMC that I do not own Minecraft.

**Comment by phit** [comment]
that's not what I asked, in the MultiMC accounts screen will be two names, one is the Minecraft username, and one is the Xbox gamertag, is the Minecraft username empty?

**Comment by Quippits** [comment]
I'm not sure what you mean, but here's the accounts screen on MutiMC
![image](https://github.com/MultiMC/Launcher/assets/94474934/83f06bcb-4e0c-40f6-90b9-61ee90f72ef5)
The top one is my second account, which I registered on MultiMC in hopes that I had misremembered which account owned minecraft

**Comment by phit** [comment]
there is no Java account in existence with that username https://mcuuid.net/?q=EighthPompano33
can you start your game on the vanilla launcher and check your username in game

**Comment by Quippits** [comment]
I'm not sure how to display my username to myself in Java Edition, but I can confirm that I can open and play Java Edition using the account connected to this username.

**Comment by phit** [comment]
open chat and send a message

**Comment by Quippits** [comment]
Here you go
![image](https://github.com/MultiMC/Launcher/assets/94474934/27940861-54b9-4ed5-afc4-62115bcc02cd)

**Comment by Quippits** [comment]
I see that it's not the same username. Not sure why, but it's the very same Microsoft account, promise.

**Comment by phit** [comment]
now we are getting somewhere, in the vanilla launcher, click in the top left on your profile image and then check view all accounts, what is the name shown over the minecraft username Quippits

**Comment by Quippits** [comment]
![image](https://github.com/MultiMC/Launcher/assets/94474934/3bb49e57-6a6b-482a-8b24-3d2acfb05937)
Here is what is shown when I click "View all accounts"

**Comment by phit** [comment]
well there is the proof you aren't in the same microsoft account, the account in the official launcher has the xbox username quippits8936, which is neither xbox account that you used for multimc

**Comment by Quippits** [comment]
Can different Microsoft accounts share the same email? Because I surely used the same email to log into all accounts.

**Comment by phit** [comment]
Not sure, I would try the whole login thing in a different browser, or better private browser window at xbox.com until you see the right gamertag "quippits8936" at xbox.com. Then you can go to minecraft.net and doublecheck that you own the game there and the gamertag is still the one that owns the game.

**Comment by Quippits** [comment]
This is a very strange circumstance indeed. My Minecraft launcher says Quippits8936, but if I hit "Manage Profile", it brings me to a page that says EighthPompano33, and it shows Quippits8936 as one of my online friends.

**Comment by phit** [comment]
manage profile just opens the page with whatever use is already logged in in your browser, so thats expected
