### ISSUE TITLE
Trying to launch Minecraft 1.20.4 with multiple fabric mods not working.

### ISSUE THREAD

**Issue by ilikedoodlez** [MultiMC/Launcher#5336]
### Operating System

Windows

### Description of bug

I'm trying to launch minecraft with a couple of fabric mods, with Vivecraft being one of them. The launch fails every time and I don't know how to spot the issue.

Here are the logs: https://paste.ee/p/cKLBS

### Steps to reproduce

Launch Minecraft 1.20.4 with a bunch of fabric mods.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
