### ISSUE TITLE
Immediate crash with recent update

### ISSUE THREAD

**Issue by MBMBMBMBMBMBMBMBMB** [MultiMC/Launcher#5337]
### Description of bug

World loads, but crashes as it opens. MultiMC lists the last play time as 01s. Started immediately after last update, unable to play.

### Steps to reproduce

Happens every time, even with new world creation.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs

Upload the log so that someone can help you.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
