### ISSUE TITLE
My MultiMC Keeps crashing.

### ISSUE THREAD

**Issue by AlmostProfessional** [MultiMC/Launcher#5338]
I am building a small mod set with a handful of mods, on minecraft 1.7.10. but keeps crashing with NotEnoughItems installed. and with them disabled it works fine. is there any fix, or is there an incompatibility?

Here's the crash log:
[multimc-crashlog.txt](https://github.com/MultiMC/Launcher/files/14157579/multimc-crashlog.txt)

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
