### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by Inbarking** [MultiMC/Launcher#5339]
It sends me this message when I click refresh on the auto detect an it tells me there is no available versions but I did download java from multiple websites

**Comment by phit** [comment]
make sure the multimc folder path doesn't contain any special characters, else for java versions follow the wiki https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Inbarking** [comment]
sorry for the delay, I tried moving the path and it worked but now there's another problem: when I try to launch a fabric instance it's showing me an error that says opening registry key and also could not find java

**Comment by Inbarking** [comment]
I tried moving the java path too and it worked!! thanks for the help!
