### ISSUE TITLE
Instances Crashing with JVM error:  EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by CallumBurnet** [MultiMC/Launcher#5340]
### Operating System

Windows

### Description of bug

[hs_err_pid24868.log](https://github.com/MultiMC/Launcher/files/14162253/hs_err_pid24868.log)

### Steps to reproduce

Java version 17, Multiple instances, 19-14900k ddr5 6000mhz  64gb

### Suspected cause

JVM crash, Memtest86 showed no memory errors

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This isn't a MultiMC issue, so please stick to Discord with it.
