### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by AngelToad465** [MultiMC/Launcher#5341]
### Operating System

Windows

### Description of bug

Will not start 1.19.2 Even with no mods 
log: https://paste.ee/p/AkXSv

### Steps to reproduce

may differ on a different pc

### Suspected cause

unsure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
disable system openal and glfw in the settings, they are disabled by default for a reason..
