### ISSUE TITLE
Update broke multimc: failed to download errors

### ISSUE THREAD

**Issue by Elastic-Mushroom** [MultiMC/Launcher#5343]
### Operating System

Windows

### Description of bug

After updating MultiMC broke with all instances not launching and not being able to create new ones. 
Create new instance: `List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/index.json` 
Finish creating instance: `Failed to commit instance, even after multiple retries. It is being blocked by something.` 
Try to launch an instance: `Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file index.json' failed to process:
https://meta.multimc.org/v1/index.json
Job 'Download of meta file org.lwjgl3/3.3.1.json' failed to process:
https://meta.multimc.org/v1/org.lwjgl3/3.3.1.json
Job 'Download of meta file net.minecraft/1.20.json' failed to process:
https://meta.multimc.org/v1/net.minecraft/1.20.json
Job 'Download of meta file net.fabricmc.intermediary/1.20.json' failed to process:
https://meta.multimc.org/v1/net.fabricmc.intermediary/1.20.json
Job 'Download of meta file net.fabricmc.fabric-loader/0.15.3.json' failed to process:
https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.15.3.json`

### Steps to reproduce

This appears to be a unique issue I can only tell you how it happened to me. I last played multimc/minecraft on December 24th with the launcher updated until launched it yesterday Febuary 11th and was prompted to update. This is the result. I do remember some message about downgrading possibly because the update failed but I accidentally clicked it off and it hasn't reappeared since.

### Suspected cause

Update failure
Multimc is failing to download files

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Elastic-Mushroom** [comment]
Log file:
[multimc_log.txt](https://github.com/MultiMC/Launcher/files/14248519/multimc_log.txt)
I have redacted my name, username and an "internal ID"

**Comment by phit** [comment]
nothing wrong in the log, what happens when you open one of those links in your browser like https://meta.multimc.org/v1/net.fabricmc.fabric-loader/0.15.3.json

**Comment by Elastic-Mushroom** [comment]
The file shows up fine if I click the link. Also the log file ends in `11.360 W Update failed!` are you sure thats fine?

**Comment by phit** [comment]
whats your antivirus? could it be maybe blocking multimc writing to its own folder?

**Comment by Elastic-Mushroom** [comment]
no additional antivirus just built in windows defender (or whatever it's called)

**Comment by Elastic-Mushroom** [comment]
Turns out it was windows defender with it's "ransomware prevention". why is microsoft so bad? silently but inconsistantly breaking multiple programs is super dumb
