### ISSUE TITLE
Forge 1.12.2 don't work

### ISSUE THREAD

**Issue by Blixza** [MultiMC/Launcher#5344]
### Operating System

Windows

### Description of bug

I can't start instance on version 1.12.2 with forge, without everything works
https://paste.ee/p/Xp9p6

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
