### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ForrestSprite** [MultiMC/Launcher#5345]
### Operating System

Windows

### Description of bug

Crashes on start up, crashes on save, crashes randomly.

https://paste.ee/p/1JvCI

### Steps to reproduce

https://paste.ee/p/1JvCI

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by ForrestSprite** [comment]
I am not so sure. As I created a vanilla world with no mods and it also crashed. Guess I will have to get a bug report for that as well.
