### ISSUE TITLE
Attempting to launch an instance of MC 1.7.10 with forge instantly crashes- even with no mods in instance

### ISSUE THREAD

**Issue by AzureMonument** [MultiMC/Launcher#5346]
### Operating System

Windows

### Description of bug

Upon clicking launch, an error immediately appears in the log and the game fails to start. Even with no other mods than forge installed. The game _does_ launch without forge. I've also checked another instance I had previously- a 1.19 forge modpack I made half a year ago- and that launches without issues.

I've also create about six instances in increasing order, immediately adding forge to them and attempting to launch them. I've launched 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12.2- all of which failed in the same manner. I've also launched 1.20 and 1.16 which worked fine. 
However, attempting to launch version 1.15.2 with forge caused my antivirus to react and instantly delete MultiMC, identifying it as a Trojan. Luckily it only removed the executable and not the actual folder, so I was able to backup my MC instances, but that's where I'm gonna leave my root hunting. 

Error message is as follows:
Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### Steps to reproduce

Create an instance of Minecraft version 1.7.10. Then, open the version tab of the edit instance and install forge (attempted to launch before installing- did not matter). Once forge is installed (tried all three of the top versions, none worked) launch the game. Error message will then appear and the game will fail to launch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Sounds like: https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

Hard to say for certain though without the actual log.

**Comment by AzureMonument** [comment]
It could very well be that. I'll try it. Give me a bit.

**Comment by AzureMonument** [comment]
Okay, yeah. It was the lack of Java 8. Thank you
