### ISSUE TITLE
Unable to download mods from Modrinth

### ISSUE THREAD

**Issue by RetroVape** [MultiMC/Launcher#5348]
### Operating System

Windows

### Description of bug

When I choose a mod to download it fails with this message:
Job 'Modpack download' failed to process:

This is only an issue with Modrinth, ATLauncher works fine. 

I'm not sure what make of the SSL certificate errors.
Logs:
[MultiMC-0.log](https://github.com/MultiMC/Launcher/files/14324436/MultiMC-0.log)

### Steps to reproduce

Download any mod from Modrinth. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
first update windows, then open https://cdn.modrinth.com/ in [internet explorer mode of edge](https://support.microsoft.com/en-us/microsoft-edge/internet-explorer-mode-in-microsoft-edge-6604162f-e38a-48b2-acd2-682dbac6f0de), restart multimc and try again
