### ISSUE TITLE
Process exited with code 255

### ISSUE THREAD

**Issue by Fedeppo** [MultiMC/Launcher#5349]
### Operating System

Mac OS

### Description of bug

Minecraft won't start, I've downloaded the recommended version of Java (17.0.10, x86 64-bit, JRE) but it isn't working.
I'm running on MacOS

### Steps to reproduce

https://paste.ee/p/micsH

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you aren't using MultiMC, please redownload it from the official site
