### ISSUE TITLE
[Ubuntu LTS 22.04] "Open folder" opens using browser rather than file handler

### ISSUE THREAD

**Issue by shrapnelnet** [MultiMC/Launcher#5351]
### Operating System

Linux 6.5.0-18-generic #18~22.04.1-Ubuntu

### Description of bug

On clicking any button that opens the file handler, the folder will be opened within firefox. I have MIME configured correctly on my system.

### Steps to reproduce

- Open MultiMC
- Open edit instance menu
- Press "Open .minecraft"

### Suspected cause

if mimeopen is being used, it sometimes messes up searching for the inode/directory configuration and will default to firefox. I could not find the code behind the open button option but it would be helpful to know what implementation is used (Qt?)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by shrapnelnet** [comment]
if someone who is knowledgable on the file structure of the project could point me to the file that handles this it would be of great help :cat: more than happy to make my own PR

**Comment by FeedTheChunk** [comment]
It works correctly on my Ubuntu system.  The links open in Dolphin as expected just fine.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

**Comment by shrapnelnet** [comment]
> It works correctly on my Ubuntu system. The links open in Dolphin as expected just fine. Distributor ID: Ubuntu Description: Ubuntu 23.10 Release: 23.10 Codename: mantic

strange. i had issues with my MIME config initially on my machine that i managed to resolve by rewriting my mime config, and it seems to work pretty well for everything but multimc. would my mimeapps.list be of any help, or do you think this is just a rare edge case?

i will provide any more information that may be helpful. cheers

**Comment by FeedTheChunk** [comment]
I only know enough about linux to be dangerous.  I would check your default application in settings.  Other than that, I'm sorry to say that I won't be much help.

**Comment by phit** [comment]
multimc just calls the qt methods https://doc.qt.io/qt-5/qdesktopservices.html#openUrl
nothing on our end that could affect this
