### ISSUE TITLE
CANNOT start an instance with forge installation for ALL FORGE VERSIONS

### ISSUE THREAD

**Issue by return0927** [MultiMC/Launcher#5353]
### Operating System

macOS

### Description of bug

Instance log: https://paste.ee/p/AHmbD
MultiMC log: https://paste.ee/p/bIEuH - says `W Checksum mismatch, download is bad.` for forge installer

### Steps to reproduce

1. Create an instance with Minecraft `1.20.2`
2. `Edit Instance` -> `Version` -> `Install Forge` -> Install `48.1.0` (just use latest)
3. Start the created instance

### Suspected cause

Mojang recently has shut down one of their domain names - `authserver.mojang.com` and that made all the Minecraft Forge installers unable to install. (Reference [Announcement @ Minecraft Forge Discord](https://discord.com/channels/1129059589325852724/1129077934330744882/1212091927038533662))
So Forge team has been updated all installers which refers to that domain without bumping version.

The lastest checksum of forge installer `forge-1.20.2-48.1.0-installer.jar` is `e15577724cc665f8f7691333c3deb73f317103d8` 
but [checksum @ MultiMC/meta-multimc](https://github.com/MultiMC/meta-multimc/blob/33c581989c6471f24b7d56f30cdbf2fc0117c0b1/net.minecraftforge/48.1.0.json#L361) is `fcdd5a19936c8c481bb204f27b486e8c4edef5bf`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
pending a fix for https://github.com/ZekerZhayard/ForgeWrapper/issues/20
