### ISSUE TITLE
-1 (0xffffffffffffffff). issue

### ISSUE THREAD

**Issue by yungrame** [MultiMC/Launcher#5356]
### Role

i tried to play modded minecraft

### Suggestion

help me so solve the problem

### Benefit

because I can't do it by myself

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i tried to play modded minecraft, downloaded it in mmc, downloaded fabric and update my java but i still cant play it, what should i do?
there is creash report
https://paste.ee/p/x879s

**Comment by yungrame** [comment]
and all of ftb and other modpacks have the same issue

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
