### ISSUE TITLE
Mojang User Authentification Ended With a Network Error when trying to add account through Mojang

### ISSUE THREAD

**Issue by yoninaW4917** [MultiMC/Launcher#5357]
### Operating System

Windows

### Description of bug

I was trying to add a new account with my email and password of my Mojang account. 

When I click OK after correctly key in my email and password it shows an error message saying that 
Mojang User Authentification Ended With a Network Error

![image](https://github.com/MultiMC/Launcher/assets/100385243/9daa156e-ca77-43aa-96f6-50fa3ccffbdd)

### Steps to reproduce

I was only trying to sign in through mojang because I wanted to add a skin. So if there is any solutions to adding skin on local account that would be GREATLY appericiated! 

### Suspected cause

I tried it with two different Mojang accounts of mine and they both did not work. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you aren't using MultiMC
