### ISSUE TITLE
Uninstall or Reinstall MultiMC completely

### ISSUE THREAD

**Issue by Fortress937** [MultiMC/Launcher#5358]
### Role

To reset MultiMC settings to its defaults and delete all MultiMC's files.

### Suggestion

To Uninstall or Reinstall (Probably by adding Uninstall, Reinstall, and Reset button at the settings's page)

### Benefit

So it's easier to remove it from the device or reinstall it to fix a problem.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I can't find any settings that let me uninstall or reinstall MultiMC, i tried using windows control panel and windows app settings but it doesn't show up. Deleting it by putting in recycle bin will not eventually remove MultiMC from the computer completely.

**Comment by phit** [comment]
> Deleting it by putting in recycle bin will not eventually remove MultiMC from the computer completely.

no it will do exactly that, multimc has no installer so deleting its folder is all you have to do to remove it from your pc

**Comment by Fortress937** [comment]
ooh, ok.
