### ISSUE TITLE
Crashes when loading a world in minecraft 1.7.10 modpack

### ISSUE THREAD

**Issue by NokerArtZ** [MultiMC/Launcher#5359]
### Operating System

Windows

### Description of bug

I played this in total for 20 hours and yesterday the world began to drop out when loading, while other worlds run

### Steps to reproduce

[crash-2024-03-01_21.57.03-server.txt](https://github.com/MultiMC/Launcher/files/14465010/crash-2024-03-01_21.57.03-server.txt)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
