### ISSUE TITLE
Window has unused margins/space regardless of window resizing.

### ISSUE THREAD

**Issue by LimeStripe** [MultiMC/Launcher#5362]
### Operating System

Windows

### Description of bug

At default scale in display settings (125%, default) The window has unused white space that won't go away unless changed to 100%. 150% and 175% scalings just compound the issue.

![image](https://github.com/MultiMC/Launcher/assets/113951189/ba6be683-ef55-446d-bb24-b9329efdebda)
![image](https://github.com/MultiMC/Launcher/assets/113951189/4580973c-0af0-47a2-9dce-4926a01a950f)

### Steps to reproduce

- Launch the game
- MultiMC version: latest
- Windows version: 10.0.19045
- Minecraft version: Beta 1.7.3. Also applicable to release 1.0, maybe other versions as well.
- Other info: I don't remember this being a problem when I played on an older version of MultiMC a year ago.
- Stretching the window borders doesn't fix the issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use this build on modern Windows for better scaling support https://files.multimc.org/downloads/mmc-develop-win32-5.15.2.zip
other than that there was some other approaches in this issue https://github.com/MultiMC/Launcher/issues/3365

**Comment by LimeStripe** [comment]
Windows won't let me run the exe from the above zip. Complaining about it being unrecognized.
Why is this triggering Microsoft Defender, and not the one I currently run? @phit

**Comment by phit** [comment]
I don't know, ask Microsoft I guess? haven't heard anyone complain about that recently and I had been using that version myself

**Comment by LimeStripe** [comment]
I can't test it, then.
I refuse to run something that defender is warning against.
But if others have said that it is a solution that works, then you can close this thread.

**Comment by phit** [comment]
virustotal also doesn't list it as being detected as anything by defender https://www.virustotal.com/gui/url/be94ae90ab283b37dcc3682ccf6015148dbb769f261fe660add89882e99239bc
what is defender actually reporting on your end?

**Comment by LimeStripe** [comment]
Hmm. I wanna try uninstalling the MultiMC I currently have, to try to run the one you sent. How do I uninstall it?

Defender is just saying that it's an unrecognized app, and the publisher is unknown.

**Comment by phit** [comment]
you can just extract the new one over the old one, multimc isn't installed, deleting the folder is enough

any multimc version will say that

**Comment by LimeStripe** [comment]
Decided to run the one you gave me.
Nope, this did not resolve the issue.
Not sure if this is a MultiMC problem, or something very specific to my machine.

**Comment by LimeStripe** [comment]
Update: Going fullscreen with f11 gets rid of the white space at other scales.
