### ISSUE TITLE
Sound not working, I have tried the existing advice to fixing it

### ISSUE THREAD

**Issue by ingrownpants** [MultiMC/Launcher#5364]
### Operating System

Windows

### Description of bug

MultiMC version: 0.7.0-3838

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.42, 13.107.213.42]

textures.minecraft.net resolves to:
    [13.107.246.42, 13.107.213.42]

api.mojang.com resolves to:
    [13.107.246.42, 13.107.213.42]

Minecraft folder is:
D:/Users/Luis Silva/Desktop/MultiMC/instances/Beta Unleashed  v1.1/.minecraft

Java path is:
C:/Program Files (x86)/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_401, using 32-bit architecture, from Oracle Corporation.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

Main Class:
  

Native path:
  D:/Users/Luis Silva/Desktop/MultiMC/instances/Beta Unleashed  v1.1/natives

Traits:
traits texturepacks
traits legacyLaunch

Libraries:
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Users/Luis Silva/Desktop/MultiMC/instances/Beta Unleashed  v1.1/.minecraft/bin/minecraft.jar

Native libraries:
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Users/Luis Silva/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar

Mods:
  [✔️] b1.7.3_FullscreenCursorFix_v1.zip
  [📁] sppcommands (folder)

Jar Mods:
  OptiFine_1.7.3_HD_S_G (0991d069-9ec6-49a1-82b4-9c0914fb14d0.jar)
  OptiTick-1.0_b173 (c424388a-35d5-41de-9f5e-e1b0d7675c6b.jar)
  Optifine_HD_S_G_LongDistancePatchV1 (321c73f1-710b-4061-8ffd-66b9bf44a18a.jar)
  ModLoader B1.7.3 (e4df2ae0-aa4d-44da-b71e-279ba6ef205b.jar)
  ModLoaderMp 1.7.3 Unofficial v2 (1f51fd0a-e925-4bad-85a9-d4fabbe036d0.jar)
  BitDepthFix (773f1f0d-cf82-4f0e-a9b5-82dee33553d0.jar)
  simpleF3info1.5FinalBugFix_copy (a0cb5352-5222-4ad0-87dd-6049a81f0c32.jar)
  SlabNames (65df7fa3-d812-4d4e-a7ac-24ba644dbe56.jar)
  Beta 1.8 Skeleton Bows for Beta 1.7.3 (9e4b604f-aae7-4e6b-aadf-2693882ccf91.jar)
  ToggleSneak-1.1.1_b173 (ec2c5d8f-b211-4be6-acfe-3ae01277af3d.jar)
  multiplayer_jitter_fix (caf64211-4c5e-42bc-8cf2-89fe6ca40d3c.jar)
  faceview-optifine (0b2500dd-0f70-4fd5-817e-ce0a64c53616.jar)
  Clipboard_screenshots (ae398518-4a20-49ae-bba4-e1fd76ba67ef.jar)
  AnnoyanceFix (5a90d57f-e117-4414-9f24-5992ee70245d.jar)
  BetaTweaks_v1.2.2_CLIENT_b173 (51974660-d399-4e72-94e3-114755826898.jar)

Params:
  

Window size: 854 x 480

Java Arguments:
[-Dhttp.proxyHost=betacraft.uk, -DsocksProxyHost=0.0.0.0, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms640m, -Xmx1408m, -Duser.language=en]

Minecraft process ID: 16348

Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: IngrownPants, token:<ACCESS TOKEN>:<PROFILE ID>

OptiFine_1.7.3_HD_S_G
Mon Mar 11 10:14:19 GMT 2024
OS: Windows 11 (x86) version 10.0
Java: 1.8.0_401, Oracle Corporation
VM: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4
OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 version 4.6.0 NVIDIA 551.76, NVIDIA Corporation
OpenGL Version: 4.0
ModLoader Beta 1.7.3 Initializing...
Mod Loaded: mod_FullscreenCursorFix v1
Mod Loaded: mod_BetaTweaks v1.2.2
Mod Loaded: mod_AnnoyanceFix AnnoyanceFix v1.4
Mod Loaded: mod_ToggleSneak 1.1.1 (1.7.3)
Mod Loaded: mod_SimpleF3info 1.5
Done.
ModLoaderMP Beta 1.7.3 unofficial Initialized
Mar 11, 2024 10:14:20 AM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 11
Mar 11, 2024 10:14:20 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Mar 11, 2024 10:14:20 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
Texture registered: cg@10542bf, image: 0, index: 237
Texture registered: vs@1da4c2e, image: 0, index: 205
Texture registered: hs@ec8da9, image: 0, index: 14
Texture registered: av@302e60, image: 1, index: 54
Texture registered: ku@631a07, image: 1, index: 70
Texture registered: oh@1bc2bc9, image: 0, index: 206
Texture registered: if@120dae3, image: 0, index: 238
Texture registered: sd@d24a12, image: 0, index: 31
Texture registered: sd@3bd92d, image: 0, index: 47
Texture removed: cg@10542bf, image: 0, index: 237
Texture registered: TextureHDLavaFX@92c38f, image: 0, index: 237
Texture removed: vs@1da4c2e, image: 0, index: 205
Texture registered: TextureHDWaterFX@a13cd2, image: 0, index: 205
Texture removed: hs@ec8da9, image: 0, index: 14
Texture registered: TextureHDPortalFX@1596686, image: 0, index: 14
Texture removed: av@302e60, image: 1, index: 54
Texture registered: TextureHDCompassFX@414a84, image: 1, index: 54
Texture removed: ku@631a07, image: 1, index: 70
Texture registered: TextureHDWatchFX@12f7411, image: 1, index: 70
Texture removed: oh@1bc2bc9, image: 0, index: 206
Texture registered: TextureHDWaterFlowFX@158c7c5, image: 0, index: 206
Texture removed: if@120dae3, image: 0, index: 238
Texture registered: TextureHDLavaFlowFX@187448, image: 0, index: 238
Texture removed: sd@d24a12, image: 0, index: 31
Texture registered: TextureHDFlamesFX@1c59e41, image: 0, index: 31
Texture removed: sd@3bd92d, image: 0, index: 47
Texture registered: TextureHDFlamesFX@11cf9d4, image: 0, index: 47

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.
java.lang.OutOfMemoryError
Exception in thread "Thread-10" java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at org.lwjgl.BufferUtils.createByteBuffer(BufferUtils.java:60)
	at paulscode.sound.libraries.ChannelLWJGLOpenAL.<init>(SourceFile:245)
	at paulscode.sound.libraries.LibraryLWJGLOpenAL.createChannel(SourceFile:299)
	at paulscode.sound.Library.init(SourceFile:253)
	at paulscode.sound.libraries.LibraryLWJGLOpenAL.init(SourceFile:217)
	at paulscode.sound.SoundSystem.CommandNewLibrary(SourceFile:1489)
	at paulscode.sound.SoundSystem.CommandQueue(SourceFile:2362)
	at paulscode.sound.CommandThread.run(SourceFile:121)
    ERROR MESSAGE:
        SoundSystem did not load after 30 seconds.

Starting up SoundSystem...
Switching to No Sound
    (Silent Mode)

Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Process exited with exit code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 11 Mar 2024 10:16:31 +0000

### Steps to reproduce

Java minimum allocation: 640 MiB
Java Maximum allocation: 1408 MiB
PermGen: 64 MiB

Windows 11

Lauch the game.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
