### ISSUE TITLE
Microsoft user authentification failed.

### ISSUE THREAD

**Issue by Ocazionalwinner** [MultiMC/Launcher#5366]
### Operating System

Windows

### Description of bug

I can't log into MultiMc with the add microsoft feature.
All of the info related to the login was inserted correctly and I got the typical Microsoft "You can now close this window safely" message at the end of the process but the account isn't connected and gives the red error message "Microsoft user authentification failed". I searched the github for similar errors but the closest I could find was Xbox live services not being available in someone's region. What is there to do? 
![image](https://github.com/MultiMC/Launcher/assets/115875378/f7bc8a27-a58f-4434-b092-c658c8b3d7ca)

### Steps to reproduce

Steps to reproduce:
-Open MultiMc
-Go to the accounts tab
-Press the Add Microsoft button
-Go trough the steps of auth. from Microsoft
-Enjoy the spooky red error sign 

### Suspected cause

I can suspect there to be only one cause: the Java version? ( I have java 8.401 )  

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
> Go trough the steps of auth. from Microsoft

what are those? are you using a login code or password?

**Comment by Ocazionalwinner** [comment]
> > Go trough the steps of auth. from Microsoft
> 
> what are those? are you using a login code or password?

Copy code from MultiMc -> click the lick given in the box -> paste code -> continue -> press send code -> copy and paste code from e-mail -> press Accept -> Bask in nothingness ( error )

**Comment by phit** [comment]
you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional
code via email does not work for oauth for a couple of months now

**Comment by Ocazionalwinner** [comment]
Did not work, I even tried the auth app and also didn't work. There must be a fix to this....

**Comment by phit** [comment]
you can try reaching anyone at microsoft that can fix this, this has been broken for a couple of months now, it immediately worked for others once they set a password for their account

**Comment by Ocazionalwinner** [comment]
> you can try reaching anyone at microsoft that can fix this, this has been broken for a couple of months now, it immediately worked for others once they set a password for their account

This is a really unfortunate situation, thank you for trying at least. I'll continue to seek a solution, have a nice day!

**Comment by Ocazionalwinner** [comment]
Update: I tried to log in again today and it just worked? ( I did nothing different btw )
I'm not sure what made the launcher to connect to microsoft but I guess it's fixed now!
