### ISSUE TITLE
Cannot attach instance screenshot to discord

### ISSUE THREAD

**Issue by nmay231** [MultiMC/Launcher#5369]
### Operating System

Linux

### Description of bug

The snap installed version of discord cannot read files in any of the minecraft instances directory, including `screenshots/`. I cannot upload or edit any screenshots or files in the multimc directory.

### Steps to reproduce

.

### Suspected cause

This is because some snap programs cannot access hidden files (like `~/.local/`!) in the home directory. The *REAL* solution is to get discord, and any other snap program that has this issue, to request the right permission set. However, the simpler solution is to move the instances folder from `~/.local/share/multic/instances` to something that isn't hidden (but still in the home directory!) like `~/multimc-instances`.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by nmay231** [comment]
I'm only opening this issue to help any future users from being confused about this. There is more information [here](https://askubuntu.com/questions/1238211/how-to-make-snaps-access-hidden-files-and-folders-in-home) about why this fails to work.

Cheers

**Comment by phit** [comment]
to add, you can move the instance folder location via the multimc settings https://github.com/MultiMC/Launcher/wiki/MultiMC-settings#folder-locations
