### ISSUE TITLE
Add QR code to account link dialog

### ISSUE THREAD

**Issue by papaia** [MultiMC/Launcher#5370]
### Role

I switch between (and log in to) multiple different accounts on different computers.

### Suggestion

When adding a Microsoft account, the dialog asks you to browse to /link and enter a code. A QR code that points to the link would make it easier to use. Also, the OTC can be embedded in the URL for easier access with the `otc` parameter: `https://www.microsoft.com/link?otc=CODE_HERE`.

### Benefit

This would make it easier and more smooth when logging in to the account on a mobile phone.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The addition would affect the MSALoginDialog UI, specifically the `MSALoginDialog::showVerificationUriAndCode` method, which would create the QR code and display it after along with the text.

https://github.com/MultiMC/Launcher/blob/056faf330757ef1cf3d79f46adfb9c183d1d8113/launcher/ui/dialogs/MSALoginDialog.cpp#L72-L72

**Comment by graytoowolf** [comment]
How should an Azure application be configured for https://www.microsoft.com/link?otc=CODE_HERE to embed the OTC code into the URL? By default, opening the link prompts the following error:

“The request is not valid. The application is a first party application, the user does not have consent, and users are not permitted to consent to first party applications. Rather, the first party application should obtain pre-authorization for the resource server.: invalid_request”

Thank you in advance for your help!

**Comment by phit** [comment]
completed with https://github.com/MultiMC/Launcher/commit/07907ded5cee269c338c2c7d12a1a1da1903294d
