### ISSUE TITLE
java runtime was wrongly reported

### ISSUE THREAD

**Issue by runlevel5** [MultiMC/Launcher#5371]
### Operating System

macOS

### Description of bug

the JRE was wrongly reported even though the game still start and run normally

### Steps to reproduce

* Download v0.7.0 for macOS 14.3.1 (23D60)
* Add 1.20.4 instance and launch it
* Follow the log message

```


Minecraft folder is:
/Applications/games/MultiMC.app/Data/instances/1.20.4/.minecraft


Java path is:
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java


Checking Java version...
Java is version 17.0.7, using 32-bit architecture, from Eclipse Adoptium.


Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
```

I can confirm the JRE is 64-bit architecture, not 32-bit

```
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)
```

### Suspected cause

Unsure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by runlevel5** [comment]
must be as same as https://github.com/MultiMC/Launcher/pull/5304

**Comment by Zetabite** [comment]
It is. Wont fix. The fix will be to be able to natively use arm, until then, detecting arm java is unecessary, since it doesnt work in the first place

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/commit/49970ae730f1f7db4aa07e3e75b15fd55e86cc3a
