### ISSUE TITLE
FTB App "settings.json" not found

### ISSUE THREAD

**Issue by mouse-an** [MultiMC/Launcher#5372]
### Operating System

Windows

### Description of bug

I have FTB App version 1.25.4 for windows and encountered problem with importing instances from it - Instance list was empty.
MultiMC log-file says
`3.978 C Exception: "Unable to open C:/Users/mouse/AppData/Local/.ftba/bin/settings.json for reading: No such file or directory"
`
Seems like FTB App moved settings.json from ".ftba/bin/" to ".ftba/storage/"

### Steps to reproduce

Run MultiMC, select Add Instance and go FTB App section.
List'll be empty.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Lancelu-Horse** [comment]
I had the same problem. I have find a settings.json file in .ftba\storage and copied it to .ftba\bin and worked, Looks like a temporary solution. I think latest version of ftb app changed location of the file.

**Comment by LindaJuffermans** [comment]
Workaround: Copy storage/settings.json to bin/settings.json; then FTB App Import
