### ISSUE TITLE
Game only runs in background

### ISSUE THREAD

**Issue by musashihumar09** [MultiMC/Launcher#5373]
Windows 10

_No response_

### Description of bug

When I try to run an instance through MultiMC, the only thing that happens is that I hear the menu music in the background, but am unable to open up the actual game itself when I click on the taskbar or try going through the task manager. I made sure I had the right Java version and that it was linked up as necessary. This happens regardless of whether I launch online or offline. 

### Steps to reproduce

MultiMC version: 0.7.0-3852

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::51, 2620:1ec:46::51, 13.107.246.51, 13.107.213.51]

textures.minecraft.net resolves to:
    [2620:1ec:46::51, 2620:1ec:bdf::51, 13.107.213.51, 13.107.246.51]

api.mojang.com resolves to:
    [2620:1ec:46::51, 2620:1ec:bdf::51, 13.107.213.51, 13.107.246.51]

Minecraft folder is:
C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/instances/1.7.3/.minecraft

Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_401, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/instances/1.7.3/natives

Libraries:
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/mojang/authlib/1.2/authlib-1.2.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch/5.12/twitch-5.12.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/com/mojang/minecraft/1.7.3/minecraft-1.7.3-client.jar

Native libraries:
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.12/twitch-platform-5.12-natives-windows-64.jar
  C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username MusashiHUmar --version 1.7.3 --gameDir C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/instances/1.7.3/.minecraft --assetsDir C:/Users/12196/OneDrive/Documents/mmc-develop-win32/MultiMC/assets --assetIndex 1.7.3 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {}

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 6092

Using onesix launcher.

[17:51:57] [main/INFO]: Setting user: MusashiHUmar
[17:51:57] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[17:51:57] [Client thread/INFO]: LWJGL Version: 2.9.4
[17:51:58] [Client thread/INFO]: Reloading ResourceManager: Default

Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

[17:51:59] [Sound Library Loader/INFO]: Sound engine started
[17:52:00] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[17:52:00] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[17:52:02] [MCO Availability Checker #1/ERROR]: Couldn't connect to Realms
Process was killed by user.
Clipboard copy at: 22 Mar 2024 17:56:00 -0500

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Sounds like the game is outside of the viewing distance on the monitor.  Try changing your resolution to something huge to see if you can see the game.  If you know how to use keyboard shortcuts you can you use the "move" function.  There may be be a way to tell java to set the starting corner at 0,0.  you could try Google and see what she has to say about it.

Another thing to try is to edit the options.txt file and replace fullscreen:false fullscreen:true.  This will get you out of a jam but as soon as you window the screen again you'll be in the same situation.  good luck

**Comment by musashihumar09** [comment]
I tried that, but to no avail. I'm wondering if it is an issue with my graphics card at all. I did check to see if for some reason my computer thought I had two monitors, but when I went into my control panel I didn't see anything of the sort.

**Comment by Zetabite** [comment]
IIRC, that was due to using a broken/headless java. Try installing one of the java 8 versions from here:
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
