### ISSUE TITLE
mods don't work

### ISSUE THREAD

**Issue by gbb123gfdsd** [MultiMC/Launcher#5375]
### Operating System

macOS

### Description of bug

the mod doesn't work or appear 

### Steps to reproduce

i don't have any idea 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
