### ISSUE TITLE
MultiMC Doesn't Use the System's Default Theme

### ISSUE THREAD

**Issue by Boobies** [MultiMC/Launcher#5376]
### Operating System

Linux

### Description of bug

I'm using GNOME on Debian in Dark Mode and it doesn't seem like MultiMC cares about it when using the system's theme. It just defaults to the light theme.

### Steps to reproduce

It's clear from the description.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Zetabite** [comment]
That might be due to missing libraries on your end. Since MultiMC uses QT, and Gnome isnt written in QT, you probably either need to set a QT theme and/or install a compatibility tool.
