### ISSUE TITLE
When modpack download mod fails,dont cancel the modpack installation,continue but the mod that has error on it wont be installed aka when error occurs,continue install

### ISSUE THREAD

**Issue by GodlyFirecracker** [MultiMC/Launcher#5377]
### Role

I play modded minecraft

### Suggestion

I want it

### Benefit

It's annoying since it can't be installed without completing it,aka the benefit is incomplete installation modpack

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by phit** [comment]
do you have an example modpack?

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
