### ISSUE TITLE
Minecraft 1.18 Pre Release 2 and above require the use of Java 17 im confused

### ISSUE THREAD

**Issue by 7777godlove** [MultiMC/Launcher#5381]
### Description of bug

Minecraft 1.18 Pre Release 2 and above require the use of Java 17 what does it mean how do i fix this

### Steps to reproduce

idk

### Suspected cause

Idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
