### ISSUE TITLE
Failed to connect to Microsoft Account using Ubuntu 22.04 / Multi MC 5 Version 0.7.0.3853 lin64

### ISSUE THREAD

**Issue by AmmarkoV** [MultiMC/Launcher#5382]
### Operating System

Linux

### Description of bug

After clicking to create a new microsoft account
I get the link, complete the procedure on microsoft's end however afterwards I get a  "Microsoft user authentication failed" message

### Steps to reproduce

Login with my account (that was working in the past) by adding it to MultiMC5

### Suspected cause

PollServer::onPollTimeout: retrying
   29.327 D PollServer::onPollTimeout: retrying
   34.326 D PollServer::onPollTimeout: retrying
   39.326 D PollServer::onPollTimeout: retrying
   45.327 D PollServer::onPollTimeout: retrying
   50.326 D PollServer::onPollTimeout: retrying
   55.326 D PollServer::onPollTimeout: retrying
   60.326 D PollServer::onPollTimeout: retrying
   66.326 D PollServer::onPollTimeout: retrying
   71.327 D PollServer::onPollTimeout: retrying
   76.327 D PollServer::onPollTimeout: retrying
   82.326 D PollServer::onPollTimeout: retrying
   82.864 D DeviceFlow::onVerificationReceived: Emitting closeBrowser()
   82.864 W DeviceFlow::onVerificationReceived: Verification failed: QMap(("correlation_id", "2c169e13-7ece-4104-a892-407819e375cd")("error", "invalid_grant")("error_codes", "")("error_description", "AADSTS70000: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope. Trace ID: 5a35bdb2-2265-41e0-a532-78ef7fc59d01 Correlation ID: 2c169e13-7ece-4104-a892-407819e375cd Timestamp: 2024-03-31 11:52:02Z")("error_uri", "https://login.microsoftonline.com/error?code=70000")("timestamp", "2024-03-31 11:52:02Z")("trace_id", "5a35bdb2-2265-41e0-a532-78ef7fc59d01"))
   82.864 C Task "MSAInteractive(0x2f8ce30)" failed:  "Microsoft user authentication failed."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional
code via email does not work for oauth for a couple of months now

**Comment by AmmarkoV** [comment]
> you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional code via email does not work for oauth for a couple of months now

Finally managed to login using a password. Thank you a lot for your help !
