### ISSUE TITLE
I can't connect to specific servers when using multimc

### ISSUE THREAD

**Issue by endor1231** [MultiMC/Launcher#5384]
### Operating System

Windows

### Description of bug

I and a friend of mine are experiencing a problem, where we can't connect to our privatly hostet server using multimc. This only only occures when using multimc and not when using minecrafts default launcher. We are using the newest update of multimc. We somehow are able to connect to servers like hypixel. For context we are using a fabric server with carpet, lithium, carpet extras and servux installed. We have tried connecting with a vanilla client while using multimc launcher and also tried with a fabric client. But when we try to connect to the server it just says "Connecting to Server". After a short time it then times out.

### Steps to reproduce

1. use a version of 1.20.4 (can be fabric or vanilla, others I haven't tested) and boot up the instance
2. try to join a server (for me it only didn't work on fabric servers)

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by endor1231** [comment]
so I can't reproduce it on other fabric servers but I can confirm that It isn't only on fabric servers but every server hosted over my friends pc with his ip. We tried with a fabric, vanilla and bukkit server they all timed out.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
