### ISSUE TITLE
Null.jar metadata issue

### ISSUE THREAD

**Issue by Jeffllama123** [MultiMC/Launcher#5386]
### Description of bug

I tried to launch my client and it returned with: Instance update failed because: Null jar is specified in the metadata, aborting.

Log:
PolyMC version: 6.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.51, 13.107.246.51]

textures.minecraft.net resolves to:
    [13.107.246.51, 13.107.213.51]

api.mojang.com resolves to:
    [13.107.246.51, 13.107.213.51]

Minecraft folder is:
/Users/danieb04/Library/Application Support/PolyMC/instances/1.20.1/.minecraft

Java path is:
/Users/danieb04/Downloads/jdk-21.0.2.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 21.0.2, using 64 (aarch64) architecture, from Oracle Corporation.

Instance update failed because: Null jar is specified in the metadata, aborting.

Clipboard copy at: 04 Apr 2024 10:53:08 -0400

### Steps to reproduce

Open Launcher
Launch Instance

### Suspected cause

Not sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
PolyMC?  It appears you're not even using MultiMC.
