### ISSUE TITLE
my account has full premium Minecraft java edition, but it keeps saying I need to buy it and asking if I wn

### ISSUE THREAD

**Issue by TwilightHound** [MultiMC/Launcher#5391]
### Operating System

Linux

### Description of bug

I expected it to launch minecraft 1.8.8 using java 1.8.0, instead it showed a notice about my account not owning minecraft. I used the website (https://minecraft.net) to verify I did indeed still own it. so it should not be rejecting my attempts to play it and asking about playing the demo

### Steps to reproduce

*add an account if you did not do it at setup
*refresh the account in case it gives an error
++++++++++++++++++++
*press "settings"
*press "java"
*press "auto detect"
*press 1.8.0
*press "OK"
*press "close"
++++++++++++++++++++
*press "add instance"
*scroll down and press "1.8.8"
*press "OK"
++++++++++++++++++++
*click the icon once
*hit "launch"*
*note the account error

### Suspected cause

it is likely an error in the most recent update of the authentication client.
![image](https://github.com/MultiMC/Launcher/assets/48195169/a826b1ce-acfb-45d2-aab0-e6526ddf9c56)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TwilightHound** [comment]
update: issue seems to be with account selection, it keeps trying to launch without an account associated with it, no further details are available at the moment

**Comment by phit** [comment]
you logged into the wrong microsoft account, 99% certain since I've seen this dozens of time now and eventually the person always figured out they were on the wrong account, so please try doing the login in a different browser or private tab

**Comment by TwilightHound** [comment]
negative, I have just confirmed that it is the right account, it even pulls up my skin. it just says I don't own it
![image](https://github.com/MultiMC/Launcher/assets/48195169/29e41b33-2637-4db4-931f-9316866ba161)

**Comment by phit** [comment]
what does the accounts screen show?

**Comment by TwilightHound** [comment]
It shows the same thing it always shows, the only thing that changed was that it says that the account does not own Minecraft On Apr 19, 2024, at 1:59 AM, Philip T. ***@***.***> wrote:﻿
what does the accounts screen show?

**Comment by JustSomeGuy7** [comment]
Experiencing the same issue on windows 10.

**Comment by TwilightHound** [comment]
> Experiencing the same issue on windows 10.

Update: set your account as “favorite”, it patched the bug, and when I reinstalled it for an unrelated issue the problem did not reoccur,

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/5438
