### ISSUE TITLE
Labymod 4 Update failed

### ISSUE THREAD

**Issue by Sevokoth** [MultiMC/Launcher#5392]
### Operating System

Windows 10 

### Description of bug

Minecraft with Labymod 4 is not starting, loading updates failed

### Steps to reproduce

Download Labymod 4, start it, close it, try to start it again and it shouldnt work 

### Suspected cause

https://paste.ee/p/H54zi (Chrashlog) / Startlog 

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by Sevokoth** [comment]
Thats bullshit, i already tried to kontakt the Labymod Support "We dont offer any support for MultiMC", you dont feel responsible for that, they dont, alright.. then i gotta switch the Launcher away from MultiMC, not possible Useing it anymore then.. atleast for Labymod. 

 
 

Gesendet: Freitag, 19. April 2024 um 14:03 Uhr
Von: "Philip T." ***@***.***>
An: "MultiMC/Launcher" ***@***.***>
Cc: "Sevokoth" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MultiMC/Launcher] Labymod 4 Update failed (Issue #5392)


 

This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the MultiMC Discord.
