### ISSUE TITLE
microsoft user failed autenfication

### ISSUE THREAD

**Issue by Ens0r4kk** [MultiMC/Launcher#5393]
### Operating System

Windows

### Description of bug

I log into my account, the microsoft link says that I am logged in and can safely close the page, but I get this error

### Steps to reproduce

log in
failed

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional
code via email does not work for oauth for a couple of months now

**Comment by Ens0r4kk** [comment]
> Вам нужно использовать другой способ входа в систему, например, код через приложение для аутентификации или пароль https://account.live.com/proofs/manage/additional код по электронной почте не работает для OAuth уже пару месяцев

bro, thank you for the health of your family, I really love you
