### ISSUE TITLE
Microsoft account authentication keeps failing

### ISSUE THREAD

**Issue by picklejar548** [MultiMC/Launcher#5395]
### Operating System

macOS

### Description of bug

When adding a Microsoft account, I went to the link it showed, https://www.microsoft.com/link, pressed "Copy Code" and entered it on the website, which worked fine. Then the website emailed me the code, which worked. Only when I pressed "Accept" did MultiMC say "Microsoft user authentication failed."

### Steps to reproduce

Go to Manage Accounts, then go to Add Microsoft, copy the code and click on the link, then enter said code you copied, allow it to go to the next page, then let it email you another code to allow the app to trust the Microsoft account, then press Accept. 

### Suspected cause

Possibly a browser issue.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by picklejar548** [comment]
Trying Google Chrome now to see if it works.

**Comment by phit** [comment]
you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional
code via email does not work for oauth for a couple of months now
