### ISSUE TITLE
Minecraft 1.20.4 - Mods not loading

### ISSUE THREAD

**Issue by Mister-Curious** [MultiMC/Launcher#5396]
### Operating System

Windows

### Description of bug

When I load an instance of Minecraft Java edition from MultiMC.the game loads fine, except there is no 'MODS' button present in the game menus like when I launch my game normally. Here is the missing mod button:

![image](https://github.com/MultiMC/Launcher/assets/81539091/8bf79f3e-3323-4d45-9053-e38fa8019eb6)

### Steps to reproduce

 - Launch MultiMC.exe
 - Create Instance of Minecraft, chosing 1.20.4 as the version to play.
 - Right click instance and chose 'Edit Instance'
 - Click on 'Loader Mods' tab in the left column, then click 'Add' in the top right corner.
 - Navigate to the directory with the mods, then seclect all files and click 'Open'. (This populates MultiMC with your mods). 
 - Launch the instance offline
 - Hook the process
 - Wait for game to load
 - Once game is loaded, observe that there is no 'MODS' button anywhere. 

### Suspected cause

I do not know what the cause of this might be as I am a new MultiMC user. In the Minecraft console log window it is showing that the mods are loading, as I can see the various names mods in the console. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You need to install a mod loader under the Version tab.

**Comment by Mister-Curious** [comment]
> You need to install a mod loader under the Version tab.

Thanks. I did this, and the game would not even launch. Here is console output for that:

https://paste.ee/p/QwvqA

I disbaled the Fabric API for this attempt, but the previous attempt it was loaded. Both times reproduced the same error.
The version I use normally is` fabric-api-0.96.4+1.20.4.jar`
This 0.96 version of Fabric that I normally launch with doesn't seem to be present when I am prompted for which version to intsal:
![image](https://github.com/MultiMC/Launcher/assets/81539091/82e72777-cdd8-4398-8a27-8983dc57274a)

**Comment by FeedTheChunk** [comment]
First, it doesn't look like a MultiMc issue to me but my opinion is just that mine.  Try this.  Go to the version tab and click download all.  It doesn't look like you downloaded Fabric mod loader.  If it still doesn't work, then you should probably ask on Discord for more help.  FWIW, I use Fabric version 0.15.7 for 1.20.4 and it loads just fine.  But it really looks like you don't have the loader downloaded to me.

**Comment by FeedTheChunk** [comment]
BTW: If you have vr 9x selected that version is like 4 yrs old.  You definitely need a newer Fabric Version.

**Comment by Mister-Curious** [comment]
> BTW: If you have vr 9x selected that version is like 4 yrs old. You definitely need a newer Fabric Version.

I understand that it is not the most up to date version, however all my mods load perfectly fine with `fabric-api-0.96.4+1.20.4.jar` when I use the vanilla launcher. I am not sure that I understand why MultiMC would allow for older versions of Fabric to be installed via the 'Versions' tab if that was something that prevented successful launching of the game. Certainly this cant not be true. 

As for your first suggestion, I tried 'Download All', but it did not populate this list of installed items with anything new:

![image](https://github.com/MultiMC/Launcher/assets/81539091/a64f1fd6-b66d-46ab-9e0a-2e66729c467c)

The game will still not load if Minecraft is at the top of this list. It will load if Fabric is at the top of the list, but mods still not being loaded. Any help is appreciated!

**Comment by Mister-Curious** [comment]
> 9x selected that version is like 4 yrs old.

I also tried to install the latest version from the 'Versions' tab and the game would not launch.

**Comment by FeedTheChunk** [comment]
You're missing LWJGL 3 in that list above.  Should be LWJGL, Minecraft, Mappings then Fabric.  

-- Ask in Discord for more help.    This really isn't the place to get help with your mod / mod list
