### ISSUE TITLE
MultiMC not running Minecraft 1.8.9 with Forge (Java 8 installed).

### ISSUE THREAD

**Issue by JadonCon04** [MultiMC/Launcher#5397]
### Description of bug

Expected Minecraft with Forge to complete launching and show the Minecraft home screen.
Minecraft began to load with Forge, but crashed before loading the Minecraft home screen.
Minecraft should be loading with Forge just fine. 

https://paste.ee/p/US4Jr - Minecraft Log

### Steps to reproduce

- Install Java 8
- Create an instance of Minecraft 1.8.9.
- Right click the instance and select "Edit Instance."
- Select the "Version" tab on the left side column of the window.
- Click the "Install Forge" button on the right side of the window.
- Select the recommended version, then click "ok."
- Select the "Settings" tab in the left side column of the window.
- Select the "Java" tab.
- Select the checkbox adjacent to the "Java Installation" text.
- Select the "Auto-detect..." button.
- Select Java Version 1.8.0_411
- Click the "ok" button.
- Click the "Launch" button
- Observe the screen as the instance launches, then crashes before loading the Minecraft menu screen.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Looks like you're not running 1.8.9 : **--version 1.16.4 --gameDir E:/Minecraft/MultiMC/instances/1.16/.minecraft**

**Comment by JadonCon04** [comment]
Sorry, I was testing across several instances trying to find the problem. Grabbed the wrong one on accident! Updated the link :)

**Comment by JadonCon04** [comment]
Aaaaand now there's no issue. I could've sworn I double and tripple checked that I got everything right, but I guess I missed some things. Closing this thread. Sorry!
