### ISSUE TITLE
Other versions work but the lastest doesn't (1.20.5)

### ISSUE THREAD

**Issue by ziphyfyi** [MultiMC/Launcher#5398]
### Operating System

Windows

### Description of bug

To launch Minecraft 1.20.5, it gaves this error https://paste.ee/p/jXFtr, for some reason 1.20.4 works but .5 doesn't. I am trying to just play java nothing modded.

### Steps to reproduce

Launching 1.20.5

### Suspected cause

Maybe something to do with java?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/wiki/blob/af0d16e2cc3c5f9b9f632b2f2102f6a3501509eb/Using-the-right-Java.md
