### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by TomagPlays** [MultiMC/Launcher#5400]
### Operating System

Windows

### Description of bug

I have java 17, but miltimc says i dont, i can play 1.18 and newer versions normally in the official launcher

### Steps to reproduce

try loading fabric 1.20.2

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You have to select the correct Java version in setting.  MM will probably default to vr. 8

**Comment by TomagPlays** [comment]
How do i do it?

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#set-instance-java-installation
