### ISSUE TITLE
MultiMC does not detect Java version 21

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5402]
### Description of bug

Despite installing Java versions from two different sources, Multi MC does not detect Java version 21 in settings.

### Steps to reproduce

Install this version of Java: https://www.java.com/en/download/windows_offline.jsp
Go into settings and go to java
Click Auto Detect.
Java version 21 is not listed thus being unable to run Minecraft 1.20.5
Now download and install this version of Java: https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jre&version=21 using MSI installer
Repeat steps 2 and 3
Java version 21 is still not detected by MultiMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
stop making new issues, use the previous issue for support, the detection works just fine

![image](https://github.com/MultiMC/Launcher/assets/2097483/52014ed1-1dd5-4622-9670-65ae7c19451e)
