### ISSUE TITLE
Curse Forge Crash (1.19.2)

### ISSUE THREAD

**Issue by Josifekjj** [MultiMC/Launcher#5406]
### Operating System

Windows

### Description of bug

So my friend wanted to play a modpack with me, i tried it with another and it worked but with this friend , it didnt work.
We tried to install different version of java, no it still didnt work.
[message.txt](https://github.com/MultiMC/Launcher/files/15191390/message.txt)

### Steps to reproduce

Just hit play in minecraft launcher

### Suspected cause

java

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Josifekjj** [comment]
It showed exit code 1

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC.
