### ISSUE TITLE
Minecraft Crashing on Multi MC

### ISSUE THREAD

**Issue by EpikGoose** [MultiMC/Launcher#5407]
### Operating System

macOS

### Description of bug

I started up Minecraft with MCSR Mods installed on it but for some reason the game crashed and doesn't load.

### Steps to reproduce

- Install multi mc
- install the mcsr basic mods
- install fabric
- create an instance with the things above combined and run it on a macOS.

### Suspected cause

It might be because I have way too many minecraft stuff, I have a separate Minecraft launcher for CurseForge and Lunar Client. If that's the cause, can you tell me a way or find a tutorial to organize all of my minecraft folders neatly?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by EpikGoose** [comment]
Btw, almost forgot, here's the pastebin thingy:
https://paste.ee/p/RxJYB

**Comment by FeedTheChunk** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
