### ISSUE TITLE
Forge 1.12.2

### ISSUE THREAD

**Issue by TomagPlays** [MultiMC/Launcher#5408]
### Operating System

Windows

### Description of bug

When i run the game, it doesn't open(i have java 17)
https://paste.ee/p/MBD1J 

### Steps to reproduce

run forge 1.12.2

### Suspected cause

?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You answered your own problem there

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
