### ISSUE TITLE
not sure what is causing crash

### ISSUE THREAD

**Issue by hackingrulessodobipeople** [MultiMC/Launcher#5415]
### Operating System

Windows

### Description of bug

here is log

https://paste.ee/p/05bQW

### Steps to reproduce

launch

### Suspected cause

mod incompatibility

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by hackingrulessodobipeople** [comment]
I will try removing mods one by one to try and find the issue but i would still appreciate some help😊

**Comment by FeedTheChunk** [comment]
Start with using java 17.  If that doesn't do it, then take Phit's advise and ask in Discord.

**Comment by phit** [comment]
you aren't even using MultiMC, so no you won't get any help here, especially with that modlist

**Comment by hackingrulessodobipeople** [comment]
oh my apologies i am using my sons computer so it might be one of his mods.😊

I did not mean to waste your time.
