### ISSUE TITLE
Unable to use new version

### ISSUE THREAD

**Issue by CRYang1107** [MultiMC/Launcher#5417]
### Operating System

Windows

### Description of bug

I want to use the new versions of Minecraft (1.20.5 & 1.20.6), but it seems there are glitches in the code, and now I can only use versions below 1.20.4.
[New Paste 1.txt](https://github.com/MultiMC/Launcher/files/15295931/New.Paste.1.txt)

### Steps to reproduce

1.edit instance
2.change version
3.choose the version(1.20.5&1.20.6)
4.error occurred after launching

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Java is version 17.0.9.

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
