### ISSUE TITLE
cant sign in

### ISSUE THREAD

**Issue by d7oom4234** [MultiMC/Launcher#5418]
### Description of bug

every time i want to log in he reject me and tells me : Microsoft user authentication failed.

### Steps to reproduce

![Capture](https://github.com/MultiMC/Launcher/assets/169854170/951d3cb3-64b6-4d67-a46d-0b70e4712c0d)
![Capture](https://github.com/MultiMC/Launcher/assets/169854170/d5e7688f-b73c-46c5-87a7-31880522a577)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to use a different login method, like code via auth app or password https://account.live.com/proofs/manage/additional
code via email does not work for oauth for a couple of months now
