### ISSUE TITLE
My Jar Files Are Gone! 

### ISSUE THREAD

**Issue by Mdol0** [MultiMC/Launcher#5419]
### Operating System

Windows

### Description of bug

So when i tried to open MultiMC it was normal but when i re-opened it 
was all gone

### Steps to reproduce

.

### Suspected cause

i don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Wolf68k** [comment]
After you downloaded the MMC zip did you extract all of the contents to a folder? Example: c::\games\multimc\

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.
