### ISSUE TITLE
Mutimc freeze when trying to open mods window

### ISSUE THREAD

**Issue by loject** [MultiMC/Launcher#5421]
### Operating System

Windows

### Description of bug

When attempting to open the mods window by clicking the "View mods" button on minecraft instance version 1.20.4 with mods, the multimc freezes for approximately 15 seconds to 1 minute and fully utilises 1 core of CPU before the mods window appears.
Mods:
  [✔️] baritone-standalone-fabric-1.10.2.jar
  [✔️] fabric-api-0.97.0+1.20.4.jar
  [✔️] FallingTree-1.20.4-1.20.4.3.jar
  [❌] ferritecore-6.0.1-fabric.jar.disabled (disabled)
  [❌] indium-1.0.27+mc1.20.1.jar.disabled (disabled)
  [✔️] journeymap-1.20.4-5.9.25-fabric.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] litematica-fabric-1.20.4-0.17.2.jar
  [✔️] lithium-fabric-mc1.20.4-0.12.1.jar
  [✔️] malilib-fabric-1.20.4-0.18.1.jar
  [✔️] sodium-extra-0.5.4+mc1.20.4-build.116.jar
  [✔️] sodium-fabric-0.5.8+mc1.20.4.jar
  [✔️] stack-to-nearby-chests-mc1.20.4-0.5.4.jar
  [✔️] WI-Zoom-1.5-MC1.20.2.jar
  [✔️] Xaeros_Minimap_24.1.1_Fabric_1.20.4.jar
![image](https://github.com/MultiMC/Launcher/assets/29097142/566d2780-cdeb-48c6-a215-669cf17008d0)

### Steps to reproduce

* open multimc
* select minecraft version(1.20.4)
* start minecraft
* load world
* exit world
* exit minecraft
* press "view mods" button

### Suspected cause

Instance folder around 9gb mb cause this?
![image](https://github.com/MultiMC/Launcher/assets/29097142/fee5453e-d734-4f28-8fa5-cc4d4fa2513e)
world folder 2 gb size
![image](https://github.com/MultiMC/Launcher/assets/29097142/04ab276d-c8ad-42c1-af0a-c24ac660ee18)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
yeah https://github.com/MultiMC/Launcher/issues/4228
