### ISSUE TITLE
bug with xbox and microsoft store

### ISSUE THREAD

**Issue by asukalangleyuwu** [MultiMC/Launcher#5422]
### Operating System 

Windows 10

### Description of bug

At the time of running the Minecraft luncher from the Xbox store, it threw me an account unlink to do a verification to my email at the same time in Microsoft it threw me the error 0x803F8001. It also appeared to me that I didn't have the Minecraft Bedrock and Java in my library (but at the time of buying it I can't because it appears that I have it) and all this happened after installing the Multimc luncher

### Steps to reproduce

Play Minecraft without Multimc the right way 
Install MultiMC and run it
Open Minecraft on Xbox (authentication failed)
Open Microsoft Store Perform Authentication
Open the launcher from the Microsoft Store (error 0x803F8001)
Fix application bugs using Windos and System32 (in vain)

### Suspected cause

Maybe MultiMC isn't meant to be used as an extension, but rather to be used as a main program (?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
none of this has any relation to multimc, if you are having issues with microsofts services contact their support. multimc works fine alongside, with or without the official launcher as it is completely standalone.
