### ISSUE TITLE
Unable to authenticate using Microsoft

### ISSUE THREAD

**Issue by EarthenSky** [MultiMC/Launcher#5423]
### Operating System

Windows

### Description of bug

Unable to add a microsoft account

### Steps to reproduce

Go to settings, add Microsoft, go to  https://www.microsoft.com/link and input code. Login, then get redirected to microsoft account page.

### Suspected cause

https://answers.microsoft.com/en-us/xbox/forum/all/why-isnt-multimc-registering-a-successful-login-to/d4f1032c-58ca-4d16-b650-29ffcfeb2c6b

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
how are you signing into your microsoft account, are you using anything other than email and password? if so, what are you doing

**Comment by EarthenSky** [comment]
I was authenticating using GitHub. I just tried authenticating using a different method (single use code from email), and it was successful. Odd, but nice!

**Comment by phit** [comment]
yeah its a known issue on microsofts end, nothing we can do about that unfortunately
