### ISSUE TITLE
Process exited with code 1 (0x1) when starting Minecraft for the first time through the MultiMC launcher

### ISSUE THREAD

**Issue by Ikfe** [MultiMC/Launcher#5424]
### Operating System

Windows

### Description of bug

MultiMC version: 0.7.0-3857

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.45, 13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.246.45, 13.107.213.45]

api.mojang.com resolves to:
    [13.107.213.45, 13.107.246.45]

Minecraft folder is:
C:/Users/feodo/AppData/Roaming/MultiMC/instances/1.20.6/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/java.exe

Checking Java version...
Java is version 17.0.10, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/feodo/AppData/Roaming/MultiMC/instances/1.20.6/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/datafixerupper/7.0.14/datafixerupper-7.0.14.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-arm64.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-x86.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Users/feodo/AppData/Roaming/MultiMC/libraries/com/mojang/minecraft/1.20.6/minecraft-1.20.6-client.jar

Native libraries:

Params:
  --username Fedikill --version 1.20.6 --gameDir C:/Users/feodo/AppData/Roaming/MultiMC/instances/1.20.6/.minecraft --assetsDir C:/Users/feodo/AppData/Roaming/MultiMC/assets --assetIndex 16 --uuid <ID ПРОФИЛЯ> --accessToken <КЛЮЧ ДОСТУПА> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 22068

Using onesix launcher.

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Процесс завершён с кодом 1 (0x1).
Пожалуйста, обратите внимание, что обычно ни кода выхода, ни его описания недостаточно для диагностики проблем!
Всегда загружайте весь журнал целиком, а не только код выхода.
MultiMC: Log upload triggered at: 21 May 2024 23:35:05 +0300

### Steps to reproduce

first launch of the game from the launcher after installing minecraft and java version seventeen

### Suspected cause

I don’t know if this is the reason, but at the time of launching the game through the MultiMC launcher, I had downloaded the game in the official launcher, and also when I first entered MultiMC, I was asked to select java from the proposed list, only there was nothing in the list, only a black rectangle in middle of the screen
At the same time, I know that I had the eighth version of java installed and, again, through the official launcher the game launched without problems.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by Ikfe** [comment]
This helped me, thanks!21.05.2024, 23:52, "Philip T." ***@***.***>:
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
