### ISSUE TITLE
Repeatedly Crashing world without a recent backup is stuck in Trial chamber :(

### ISSUE THREAD

**Issue by ParksCanada** [MultiMC/Launcher#5425]
Windows Minecraft Java

### Description of bug

I went to a trial chamber (I have before with no problems, this is my third or fourth.

Drank bad omen 5, which activated into trial omen 5; as well, I think I have the silverfish potion effect applied currently...
and just constant crashes whenever I try to play it now :(

### Steps to reproduce

Just opening the world, it crashes within a moment :(

### Suspected cause

no clue :( 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by ParksCanada** [comment]
thanks philip
