### ISSUE TITLE
Says i need a different version

### ISSUE THREAD

**Issue by RGJoseff** [MultiMC/Launcher#5427]
### Operating System

Windows

### Description of bug

trying to use a modpack and it says Minecraft 1.18 Pre Release 2 and above require the use of Java 17

### Steps to reproduce

use modrinth modpack and select elden craft

### Suspected cause

im not sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
And...????  use Java 17 like it says.

**Comment by RGJoseff** [comment]
how

**Comment by FeedTheChunk** [comment]
Wiki: https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
