### ISSUE TITLE
java 17 issue

### ISSUE THREAD

**Issue by Liam9001** [MultiMC/Launcher#5429]
### Description of bug

Every time I try to launch Minecraft  it states that I do not have java 17 and that it is required but the issue is that I have java 17 (and 22 by accident) and I don't think it is an issue with the 2 mods that I am trying to play with (JEI and Create) the only other thing would be the shader pack Oculus (just check it is not and it has nothing to do with the version because I also checked that) I checked everything that I can think of and form what I have seen multiple people have complained about this (on a video about a fast way to download and play the Create mod where people complained about the same problem) the only other thing that I can think of that I didn't try is to put the java 17 mod into the instance and I have done this multiple times and I get the same result (not putting java 17 into the instance) but trying to launch the instance) it is also my 1st instance

### Steps to reproduce

install java 17 and press the launch button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Liam9001** [comment]
I just checked the version using command prompt and it is on java 17

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java#setting-up-java-in-multimc

**Comment by Liam9001** [comment]
Thank you for your help
