### ISSUE TITLE
Minecraft won't load

### ISSUE THREAD

**Issue by Kirb101** [MultiMC/Launcher#5432]
### Operating System

Windows

### Description of bug

# Hello
I have updated all mods, yet it still keeps crasing

### Steps to reproduce

* Update the game and all mods
* Update fabric version
* Launch

### Suspected cause

JDK 21 could've caused it.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
update fabric loader in the version tab
