### ISSUE TITLE
help me i am getting the error below

### ISSUE THREAD

**Issue by kehuydiettraidat** [MultiMC/Launcher#5433]
### Operating System

Windows

### Description of bug

[crash-2024-06-02_20.38.37-server.txt](https://github.com/user-attachments/files/15525495/crash-2024-06-02_20.38.37-server.txt)

### Steps to reproduce

don't know

### Suspected cause

don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).

**Comment by kehuydiettraidat** [comment]
ok i wil try

**Comment by kehuydiettraidat** [comment]
ok i will try
