### ISSUE TITLE
Account Constantly getting booted

### ISSUE THREAD

**Issue by reyak** [MultiMC/Launcher#5436]
### Operating System

Windows

### Description of bug

Try to run an instance, and have to re-log into Mojang/Microsoft... over and over... Today there's a java error, and it's not working, anyway.

### Steps to reproduce

Just run an instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by reyak** [comment]
"Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Too Many Requests"

**Comment by reyak** [comment]
Minecraft Java profile acquisition failed.

**Comment by phit** [comment]
solved in discord, assuming that was you, otherwise the microsoft servers were having issues at the time
