### ISSUE TITLE
Microsoft not linking

### ISSUE THREAD

**Issue by randomdude79** [MultiMC/Launcher#5438]
### Description of bug

When I tried to re-log in with my MS account (It was glitching) It did not log me in.

### Steps to reproduce

* Crash MultiMC or delete and account
* Re log in through MS?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
are you getting a "Too Many Requests" error? microsoft is having issues right now and that's outside of the launchers control

**Comment by PanDabStudios** [comment]
Do we have a clue on how (or when) this will be solved? I really like the launcher, but I cant use it lol (for some reason my account disconnected).

**Comment by phit** [comment]
keep an eye on https://bugs.mojang.com/browse/WEB-7179 and https://twitter.com/MojangStatus
the issue applies to all launchers
