### ISSUE TITLE
Launcher says previously functional account does not own a copy of the game.

### ISSUE THREAD

**Issue by JustSomeGuy7** [MultiMC/Launcher#5440]
### Description of bug

Recently got an update to the MultiMC launcher, and received a message that my Microsoft account login had expired. I re-logged and the launcher showed my player skin in the top right confirming that my login was successful and to the correct Microsoft account. Attempting to launch the game in both 1.20.6 and 1.18.2 now yields the "Account does not own Minecraft" prompt. Im unsure if this is an issue on the launchers end or Microsoft's.

### Steps to reproduce

Unsure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
See here: https://github.com/MultiMC/Launcher/issues/5391
