### ISSUE TITLE
Display stops refreshing following lag spike and texture glitching

### ISSUE THREAD

**Issue by Derpercoaster** [MultiMC/Launcher#5441]
### Operating System

Windows

### Description of bug

For no apparent reason, the game suddenly freezes for several seconds, even when there is no server load at all, including in singleplayer worlds. After a few seconds, the game resumes as if nothing happened, but the display stops refreshing. I can still move the player around, open menus, click things, and interact with the world, but the display is frozen on the last frame before the freeze. Restarting the game fixes this. I've also noticed that certain textures (namely the black outline when you look at blocks) turns into a glitchy rainbow effect before the freeze.

### Steps to reproduce

I don't know how to reproduce it, as it happens randomly, without any obvious similarities between instances of the bug occurring. The only consistency is I am playing on 1.20.4, vanilla, and it happens after I've been playing a while. Presumably, any world or server will be able to cause the crash. It's never happened on other versions, only this one.

### Suspected cause

I'm suspecting that something running in the background (related to Minecraft) is causing the game to suddenly dump too much stuff into the CPU, and when it figures it out, it somehow forgets to continue refreshing the screen. I suspect there is a problem in 1.20.4's code, as that's the only version it happens on.

As an aside, I can't find any evidence that this happens with the vanilla launcher, but I'll happily be proven wrong.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with Minecraft, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
