### ISSUE TITLE
1.21 release not an option in MultiMC, only the beta version is available

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5443]
### Operating System

Windows 10

### Description of bug

1.21 has been officially released but the option to install/upgrade 1.21 instances is still not available

### Steps to reproduce

Run a 1.20.6 instance and encounter a bug
Try to report the bug to Mojang
Find that 1.20.6 is no longer available to report bugs on and only 1.21 can be reported on. <-- This indicates that 1.21 release has been officially released.

### Suspected cause

MultiMC cannot obtain the latest release from Mojang for some reason.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
it takes up to an hour to show up in multimc, its there now

**Comment by Moltresrider** [comment]
@phit  No it is NOT. still not there.

**Comment by phit** [comment]
restart your launcher, it was added 3 hours ago https://github.com/MultiMC/meta-multimc/commit/bf774ac9b714b71c24fe56071c309b1db970eea9
