### ISSUE TITLE
Modpacks cannot be loaded into MultiMC either by import from zip or loader mods

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5444]
### Operating System

Windows

### Description of bug

When loading a modpack from a zip obtained from this page: https://www.curseforge.com/minecraft/modpacks/vorecraft
MultiMC does not accept the modpack. It throws an error message, "Archive does not contain a recognized modpack type" and refuses to accept the zip

Loading the zip directly into Loader Mods does not work either. It shows no mods even with forge installed

### Steps to reproduce

Download modpack: https://www.curseforge.com/minecraft/modpacks/vorecraft
Create a new instance
Choose 1.7.10 as your Minecraft version
Import the modpack into MultiMC through loader mods. 
Run the instance. No mods exist in the game
Close the instance
Install Forge. 
Run the instance
Still no mods exist in the game
Delete the instance
Create a new instance.
Now go to "Import from Zip: and select the same modpack that you just downloaded
Receive error:  "Archive does not contain a recognized modpack type" 

### Suspected cause

MultiMC thinks the zip is not a modpack when it clearly is

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc does not support curseforge https://github.com/MultiMC/Launcher/issues/4762
