### ISSUE TITLE
The mod package Direwolf20 Pack V2 no longer works.

### ISSUE THREAD

**Issue by Schlapp7** [MultiMC/Launcher#5445]
### Operating System

Windows

### Description of bug

Greetings, I wanted to play Direwolf20 Pack V2 again after a long time. I just downloaded it for this purpose. Unfortunately I am greeted with an error message.
[https://paste.ee/p/XDQ5u](url)

I use Java version 1.8.0.371

### Steps to reproduce

Add instance.
Select FTB legacy.
Select Direwolf20 Pack for Minecraft 1.4.7.
Select package version 5.3.2.
Press the OK button.
Start instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you need to use an older java 8 version, e.g. https://files.multimc.org/downloads/jre-8u51-windows-x64.zip
