### ISSUE TITLE
MultiMC not launching new instances

### ISSUE THREAD

**Issue by TyTubeRoblox** [MultiMC/Launcher#5447]
### Operating System

Windows

### Description of bug

When I tried to launch a new MultiMC Instance with either Fabric or Quilt, it doesn't launch and crashed almost instantly, this is my portable version running on a USB stick

Edit: I have tried the installation of Java 17 on the computer and not the USB and it's not Java screwing up

log: https://paste.ee/p/EG0DZ

### Steps to reproduce

1. create a new instance
2. install fabric or quilt (tested on 1.20.1 and 1.20.4)
3. hit Launch

https://github.com/MultiMC/Launcher/assets/144578134/6a4d2d3f-fab5-4eb2-90ae-3a2c01896992

### Suspected cause

I have no idea, my other instances run just fine

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Java is version 17.0.10  

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by FeedTheChunk** [comment]
Sorry I miss read the post.  Been a long day.

**Comment by phit** [comment]
> Caused by: java.io.IOException: the jar file F:\MultiMC\MultiMC\instances\Vulkanizer 1.4.0\.minecraft\.fabric\remappedJars\minecraft-1.20.1-0.15.9\client-intermediary.jar.tmp can't be written

looks like fabric issue, report to them. multimc just launches the game
