### ISSUE TITLE
bug of memory but i have 33GB

### ISSUE THREAD

**Issue by Alonsofanderealmadrid** [MultiMC/Launcher#5449]
### Operating System

Windows

### Description of bug

I have 33GB of space on my hard drive, but the registry says that I have little storage on the hard drive

### Steps to reproduce

i dont now 

### Suspected cause

I have 33GB of space on my hard drive, but the registry says that I have little storage on the hard drive

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
I have no idea what you are trying to report, please supply some screenshots and an actual description of the issue and I'll reopen this issue.
