### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TomagPlays** [MultiMC/Launcher#5451]
### Operating System

Windows

### Description of bug

https://paste.ee/p/ZEy6c

### Steps to reproduce

--

### Suspected cause

?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
This has nothing to do with MultiMC.  Your game crashed because Java ran out of memory.  If you need help, ask for help in Discord.

**Comment by TomagPlays** [comment]
Oh, ok
