### ISSUE TITLE
1.16.5 Forge modpack constantly crashing while launching

### ISSUE THREAD

**Issue by sadsawdde21** [MultiMC/Launcher#5452]
### Operating System

Windows

### Description of bug

I was launching a freshly self-made modpack with Create and MineColonies. At first it crashed because of Create and MineColonies (and also their library mods), but now it just seems to crash with no apparent reason. I keep looking at the crash-report and can't pinpoint exactly what's wrong cause none of the mods seem to be causing any errors if MineColonies and Create are not present

### Steps to reproduce

Launching the instance
https://drive.google.com/file/d/1QnxUcpQfaBGdMhCW7pUN5hB-E_pRYuGy/view?usp=sharing
https://drive.google.com/file/d/1E_mWWFVpmjI2__lRLQ6rUlP_7Apyf_TM/view?usp=sharing

### Suspected cause

MineColonies, Create, Flywheel, Structurize

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
