### ISSUE TITLE
Spam "GL error 0x0500: Invalid enum at pre-final"

### ISSUE THREAD

**Issue by GedeonGrays** [MultiMC/Launcher#5454]
### Operating System

Windows

### Description of bug

When entering a world with shaders enabled, MultiMC starts spamming with the error "GL error 0x0500: Invalid enum at pre-final". In order for spam to start, you must restart the client. If you turn on shaders and immediately enter the world, there will be no spam.
At the same time, everything from the game to the shaders themselves works normally.

https://github.com/MultiMC/Launcher/assets/32182901/fd6c31b7-67d2-4a91-8cfe-3b2c84c71259

### Steps to reproduce

1. Load into the client
2. Enable any shaders
3. Restart the client
4. Enter the world with shaders enabled
5. See the MultiMC log

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your mods, you can try asking in the mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
