### ISSUE TITLE
Endless login loop

### ISSUE THREAD

**Issue by f-michaut** [MultiMC/Launcher#5455]
### Operating System

Windows

### Description of bug

It sometimes happen that MultiMC tries to login and fails. When it does so, it retries which is by itself completely fine.

The issue is : There is a `play offline` button that I can press to supposedly stop the login attempts which are failing repeatedly and start the game in offline mode. 
This does **NOT** work. Clicking the button does nothing, and the launcher keep trying to relog endlessly.

Furthermore, clicking the cross of that "Login in as XBox user" does nothing as well. MultiMC is basically stuck, and has to be forcefully closed by the task manager.

But the issue does not stop there !
Once the launcher is killed, I can re-open it, and since attempting to play online-mode would put me back in that endless loop, I would like to use `offline-mode`. 
However, it seems that MultiMC attempts to log you in even in offline mode !!

Which leads me to be locked out of the game and incapable of playing.

### Steps to reproduce

- Login with Microsoft account
- Wait for a day where your internet connection or Xbox servers connection is bad (idk what is the issue tbh, it just seems to depend on the day, this is already the 3rd day in the last month)
- Try to play online or offline mode

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
It's not a bug.  When you try to play online MultiMC tries to re authenticate.  If it fails, now you have no valid log in with Mojan.  Trying to play offline you can't because MultiMC no longer knows if you own a valid license or not.  Playing offline will only work once you have a VALID login.  The servers are down so you can't login ATM.

https://github.com/MultiMC/Launcher/issues/5453

**Comment by Brokkonaut** [comment]
It is a bug that you cannot cancel the not working login and hang in an endless loop.

**Comment by UplandJacob** [comment]
I feel like the reason offline mode exists is for this situation. You should be able to launch the game with a technically invalid login, obviously without multiplayer.

Even besides all that, it COMPLELTY freezes MulitMC when this happens.

**Comment by FeedTheChunk** [comment]
> I feel like the reason offline mode exists is for this situation. You should be able to launch the game with a technically invalid login, obviously without multiplayer.
> 
> Even besides all that, it COMPLELTY freezes MulitMC when this happens.

Then you'd be in trial mode.  Does mojang still have a trial mode in the game?  I assume so.  So without a valid login you just can't play.  You'd have to take this up with Mojang which is basically asking to be able to play the game for free.  How do you think that'll go?

**Comment by UplandJacob** [comment]
I thought I was the only one that thought this for a second... Nope

_methodZz_ also reposted this:
https://x.com/ibxtoycat/status/1808224041117143049?s=46

![image](https://github.com/MultiMC/Launcher/assets/123428589/a8ea3b88-4d3a-404a-9809-3589ec2f455c)

**Comment by f-michaut** [comment]
@FeedTheChunk you don't need trial mode or anything. Turn off your wifi connection and open the official MC launcher.
The launcher will open, warn you that it can't verify your account, but allow you to play offline.
![image](https://github.com/MultiMC/Launcher/assets/33881730/6aac6b42-7197-44e3-83f0-91b6fb76b4c5)

The game can be launched with an invalid token, it doesn't check it and doesn't care, as the token is only required for multiplayer servers with offline-mode disabled. 

You don't need a valid one for singleplayer, and you don't need one for offline-mode multiplayer servers (cause that's what this option is for: allow you to still play on your server if the auth servers are down, or you are on a local network cut off the Internet).

MultiMC shouldn't enforce it more than the official launcher does. And the infinite loop with the UI completely locked is definitely a bug. 

Offline mode on servers exists to allow you to play when Auth servers are down. Offline Mode in the MultiMC launcher should allow for the same.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/5078
