### ISSUE TITLE
Failed to get authorization for Xbox services. Error %2.

### ISSUE THREAD

**Issue by MousePak** [MultiMC/Launcher#5456]
### Operating System

macOS

### Description of bug

All accounts have been logged out
MacOS x64
MultiMC no updates available 
- MultiMC 5 0.7.0 3862

When trying to add or authenticate accounts following microsoft signin process all completes 
Returning back to multimc the authentication fails with 

Failed to get authorization for Xbox services. Error %2.

### Steps to reproduce

- add new account (old account which been previously working)
- follow microsoft authentication 
- multimc account signon fails "Failed to get authorization for Xbox services. Error %2."

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
https://github.com/MultiMC/Launcher/issues/5453

**Comment by MousePak** [comment]
https://support.xbox.com/en-US/xbox-live-status
MS could be having major issues with accounts 

While issue could be MS, multimc bug would also be reporting error %2 which provides no insight 


```
CURRENT ISSUES
1 of 1
Sign-in
MAJOR OUTAGE
         
Status
Outage reported
7/2/2024, 7:07:00 PM
It's taking longer than anticipated
7/3/2024, 12:26:25 AM
Resolution : Pending
```

**Comment by FeedTheChunk** [comment]
> https://support.xbox.com/en-US/xbox-live-status MS could be having major issues with accounts
> 
> While issue could be MS, multimc bug would also be reporting error %2 which provides no insight
> 
> ```
> CURRENT ISSUES
> 1 of 1
> Sign-in
> MAJOR OUTAGE
>          
> Status
> Outage reported
> 7/2/2024, 7:07:00 PM
> It's taking longer than anticipated
> 7/3/2024, 12:26:25 AM
> Resolution : Pending
> ```

Did you not see https://github.com/MultiMC/Launcher/issues/5453 ?
