### ISSUE TITLE
my account is premium but multimc detects my account is demo

### ISSUE THREAD

**Issue by ferdik-afk** [MultiMC/Launcher#5459]
### Description of bug

my account is premium but multimc detects my account is demo

### Steps to reproduce

my account is premium but multimc detects my account is demo

### Suspected cause

my account is premium but multimc detects my account is demo

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ferdik-afk** [comment]
my account is premium but multimc detects my account is demo

**Comment by phit** [comment]
you probably logged in with the wrong account
