### ISSUE TITLE
[14:52:39] [Render thread/ERROR]: Reported exception thrown!

### ISSUE THREAD

**Issue by petermg** [MultiMC/Launcher#5462]
### Description of bug

Crashing when going to the End City
Here is the full log:
https://paste.ee/p/odOMG

### Steps to reproduce

Approaching the end city my game just crashes. Log link is attached.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
