### ISSUE TITLE
Offline Login without Microsoft account but with legal purchase

### ISSUE THREAD

**Issue by xdevs23** [MultiMC/Launcher#5465]
### Role

I play without having a Microsoft account

### Suggestion

Allow playing without Microsoft account but only when purchased legally

### Benefit

So I can actually play a game I paid for

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

MultiMC forces me to use either a Microsoft or a Mojang account. I do have a Mojang (minecraft.net) account but it fails to authenticate:
![image](https://github.com/user-attachments/assets/53614d70-be0d-4774-8e36-09289e6f7420)

I do not have any Microsoft accounts and I don't want a Microsoft account so I have not been able to migrate. But I paid for the game so I feel it is very unfair to just take the game away from me. Hence I would like to still be able to play the game.

**Comment by FeedTheChunk** [comment]
As I see it, you can either migrate your account or play something else.  MultiMC has no way of knowing if you have a valid account or anyway of checking if you own a valid copy of the game, other than taking your word for it.   Without the authorization then MultiMC would be in violation of Mojang's / Microsoft's T&C's.

**Comment by xdevs23** [comment]
> As I see it, you can either migrate your account or play something else. MultiMC has no way of knowing if you have a valid account or anyway of checking if you own a valid copy of the game, other than taking your word for it. Without the authorization then MultiMC would be in violation of Mojang's / Microsoft's T&C's.

I understand that MultiMC would be in violation of the T&C's without the authorization and I just have to accept that I suddenly can't play a game that I bought with my own money, but this is not MultiMC's fault. I do not want a Microsoft account so sadly I won't be able to play MC this way.

Farewell, block game.
