### ISSUE TITLE
Joining a MP server in any instance

### ISSUE THREAD

**Issue by herobrin8900** [MultiMC/Launcher#5467]
### Operating System

Linux(Debian 12)

### Description of bug

Attempting to join an MP server on any instance results in an error, stating: "unable to connect: the authorization servers are down for maintenance"

### Steps to reproduce

debian 12 xfce desktop environment
install multimc 5 launch any instance and try to play a MP sever

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them. https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs#uploading-logs
