### ISSUE TITLE
Versions 1.20.1 and earlier do not run.

### ISSUE THREAD

**Issue by MrSafron4ek** [MultiMC/Launcher#5471]
### Operating System

Windows

### Description of bug

They flatly refuse to run versions 1.20.1 and earlier. 
This does not depend on mods, versions of forge/fabric, java, or problems with the operating system. All possible manipulations related to this were carried out (even if the assembly was just created and immediately launched without other additions, it will not start; All available versions of Java, including the version from the FAQ, were used, the problem did not go away. I even went into the libraries MultiMC\libraries\com\mojang\minecraft and cleaned them so that the launcher would download them again) - nothing helped.
What’s noteworthy is that versions younger than (1.20.2 - 1.21) launch and work normally in any form and with any build.

### Steps to reproduce

Visually, the flight occurs like this:
I launch the assembly, the initial launch process goes through, the Minecraft window appears for a second, and then disappears, and in the crash report the code is -1. 
![2](https://github.com/user-attachments/assets/9c81baf9-df7c-4b44-b10d-ae906aceb454)
![1](https://github.com/user-attachments/assets/12f42f48-fa06-4601-98db-2a7414ee1066)

### Suspected cause

All standard problems such as incompatibility of mods, or Java, have been checked and rechecked many times. The reasons for the departure are not specified here in any way, and a similar window with instructions does not appear, as in the cases above.
The only thing I can suspect is:
- The only difference between the running and non-running versions is a certain file “LWJGL 3”, which is on par with Minecraft in the list of build versions. However, I read on the Nth site that this theme has been integrated into Minecraft, starting with some version, apparently 1.20.2;
- Perhaps something happened after the last launcher update. Until June 9th inclusive, this whole problem did not exist (then the last time I went to version 1.20.1, there was no problem).
And somewhere in the same area, I decided to update the launcher to the latest version (honestly, I don’t remember the exact time and sequence of these events);
- If the problem lies in my drivers, which is likely, then it will be very bad, because at the moment all possible drivers are on the latest version (of course, if believe the Driver Booster program from IObit).

At the moment I am at a dead end, because I can’t imagine how else I can solve this problem with my own hands, including the above assumptions, so I’m writing here. I didn’t find any other similar messages on the forum, and nothing in the FAQ is suitable, otherwise everything would have worked...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MrSafron4ek** [comment]
The only thing I haven't done yet is completely reinstall the launcher.

**Comment by FeedTheChunk** [comment]
Without any logs I would suggest that you look at the Java version and make sure you're using the correct Java.

https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by MrSafron4ek** [comment]
> Without any logs I would suggest that you look at the Java version and make sure you're using the correct Java.

I double-checked and used all possible versions. Did not help. I indicated this in the description

**Comment by FeedTheChunk** [comment]
Without any logs it's just guessing.

**Comment by MrSafron4ek** [comment]
> Without any logs it's just guessing.

I looked at the last log and was interested in these two suspicious lines. They are also in other logs. If this is an instruction, how can this be done better?
![3](https://github.com/user-attachments/assets/1825b8f3-5c14-4776-a0a1-988b8005dd54)

**Comment by FeedTheChunk** [comment]
Well you can click the button that say's Upload.  https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs.  

If you have the "Use system installation of GLFW" ticked in settings, untick it.

**Comment by MrSafron4ek** [comment]
> Ну, вы можете нажать кнопку «Загрузить». https://github.com/MultiMC/Launcher/wiki/Minecraft-Logs .
> 
> Если в компоненте установлен флажок «Использовать системную установку GLFW», удалите его.

https://paste.ee/p/Z5dFv

**Comment by FeedTheChunk** [comment]
So you are using the wrong java as I suggested in the first reply.

**Comment by MrSafron4ek** [comment]
> Значит, вы используете не ту Java, как я и предположил в первом ответе.

I have a version of jdk-22, which seems to be the latest, and with it there is also a pack of very different versions, and I have tried all of them. If not them, then what version should it be?

**Comment by phit** [comment]
the version depends on the game version, read https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

**Comment by MrSafron4ek** [comment]
> версия зависит от версии игры, читайте https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java

Downloaded and checked the required versions according to the instructions. Did not help

**Comment by FeedTheChunk** [comment]
You have edit the instance and tell it which version to use.  The wiki explains all of this.

**Comment by MrSafron4ek** [comment]
> You have edit the instance and tell it which version to use. The wiki explains all of this.

Exactly

**Comment by MrSafron4ek** [comment]
По итогу проблема решилась полной переустановкой лаунчера
