### ISSUE TITLE
Failed to get Minecraft access token

### ISSUE THREAD

**Issue by foxwolf151** [MultiMC/Launcher#5473]
### Description of bug

Hello, I just tried to log into MultiMC and it said my log in has expired which has never happened in the like two years I have been using this application. I tried to sign in do everything right through Microsoft but when I go back to the MultiMC launcher it says "Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Service Unavailable" and when I go to that link is gives me a black screen with code on it. I was wondering what I could do to fix this issue.

### Steps to reproduce

1- click profiles
2- click add microsoft
3- copy code and click on the link
4- sign into microsoft
5- hit the authorize button
6- Go back to MultiMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HoneyPS** [comment]
I and a couple of others are having the same issue I also tried changing my login options from my pin to number to finger print. the other guy thinks it might be a server crash prob is but idk i got no clue botu any of this stuff 
![Screenshot 2024-07-19 105010](https://github.com/user-attachments/assets/6040133f-3197-4e1d-aa9e-61ece43270ae)

**Comment by iiPythonx** [comment]
Xbox services regarding login are currently offline: https://support.xbox.com/en-US/xbox-live-status.
You're gonna have to wait for them to come back online.

**Comment by WolfMad** [comment]
hi this looks like Xbox live is offline and there is not a problem with MultiMC

**Comment by foxwolf151** [comment]
> hi this looks like Xbox live is offline and there is not a problem with MultiMC

Ahh I see thank you so much

**Comment by foxwolf151** [comment]
> hi this looks like Xbox live is offline and there is not a problem with MultiMC

I see thank you for the link!
