### ISSUE TITLE
Stuck on Logging in as an Xbox user

### ISSUE THREAD

**Issue by VenomGamesLive** [MultiMC/Launcher#5475]
### Operating System

Windows

### Description of bug

Everytime i try to play on one of my instances I'm in a constant stuck loop of loggin in and restarting. 

### Steps to reproduce

Open MultiMC, Click launch instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HoneyPS** [comment]
Multi Mc servers are down and xbox has been notified bout it a couple others are in a waiting game with this lol. 

https://support.xbox.com/en-US/xbox-live-status
