### ISSUE TITLE
self made modpack no longer working even after working before with no changes

### ISSUE THREAD

**Issue by Neutroncraft** [MultiMC/Launcher#5476]
### Operating System

Windows

### Description of bug

I expected minecraft to run but ends up just giving me an exit code of -1 from what i can see no aparent reason

### Steps to reproduce

1. press play and it crashes.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
