### ISSUE TITLE
Account Adding Not Working

### ISSUE THREAD

**Issue by CountryOfOR3O** [MultiMC/Launcher#5478]
### Description of bug

I Was Trying To Add An ely.by Account But It Said "Minecraft Java profile response could not be parsed"

### Steps to reproduce

Add ely.by button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
not sure what ely.by is, but multimc only supports official microsoft accounts

**Comment by phit** [comment]
whatever you are talking about is not multimc

**Comment by Insediotic** [comment]
its a cracked version of multimc, im assuming Ultimc 5?

**Comment by ghost** [comment]
I use ultimmc 5 and I had the same problem
