### ISSUE TITLE
Game zoomed out & off center!

### ISSUE THREAD

**Issue by vinnyg0621** [MultiMC/Launcher#5480]
### Description of bug

Minecraft should cover the whole screen, I don't wanna see that white background!
![Screenshot 2024-07-25 221333](https://github.com/user-attachments/assets/d31bca26-9bc3-4d52-96c1-18ca2c8e0d90)

### Steps to reproduce

1. launch any version of minecraft
2. it will show the white background in maximized and normal!

### Suspected cause

maybe I changed the JVM arguments? but it happens on every instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by vinnyg0621** [comment]
this happens to me in versions below 1.6

**Comment by vinnyg0621** [comment]
it also doesn't happen when I do it with the Minecraft launcher

**Comment by vinnyg0621** [comment]
can someone please help me? 🥺

**Comment by FeedTheChunk** [comment]
The search feature can be your best friend: https://github.com/MultiMC/Launcher/issues/5362
