### ISSUE TITLE
Unable to add Microsoft account, pages not loading

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5482]
### Operating System

Windows

### Description of bug

I was trying to add my Microsoft account and it just wouldn't work, the pages weren't even fully loading.

### Steps to reproduce

1. Clicked on "Add Microsoft account", copied the code and clicked the link
2. Pasted the link
3. Logged in my Microsoft account
4. On the last page, neither the next or cancel button would work
![Screenshot 2024-07-30 143807](https://github.com/user-attachments/assets/cd091662-2910-4113-b2cb-319c0c9e5268)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by VilcsiTH** [comment]
Suspected cause seems to be Microsoft themselves. Authentication servers are down globally.
![image](https://github.com/user-attachments/assets/e99c1e59-178d-4c70-871b-88e23696098e)

**Comment by ghost** [comment]
Oh yeah I just noticed, thank you.
