### ISSUE TITLE
Cannot add a Microsoft Account to MultiMC on macOS 10.13.6

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5484]
### Operating System

macOS

### Description of bug

Basically I wanted to add my Microsoft Account to the launcher and it gives out an error about the macOS version being too low, even though it is exactly the version it needs to add the account
![image](https://github.com/user-attachments/assets/5bcd41f6-3346-4058-bad4-f12a8e63b987)

### Steps to reproduce

- Open MultiMC
- Click Profile and Manage Accounts
- Click Microsoft
- Error pops-up

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what is your multimc version?

**Comment by ferrantbe** [comment]
I have the same issue.
Mac OS 14.6.1
MultiMC 0.7.0-3864

**Comment by phit** [comment]
please provide your MultiMC-0.log from the launcher folder

**Comment by ghost** [comment]
I changed my drive in the MacBook a week ago forgetting about this.
