### ISSUE TITLE
Mod won't add to loader mods

### ISSUE THREAD

**Issue by Moltresrider** [MultiMC/Launcher#5485]
### Operating System

Windows

### Description of bug

Loading BiomesYouGo1.7.1.jar into an instance with Minecraft 1.12.2 does not work. 

### Steps to reproduce

Create an instance and select Minecraft 1.12.2
Navigate to: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go
Go to files, and select 1.12.2
Download the file for 1.12.2, it should be BiomesYouGo1.7.1.jar
Try to import the file to any 1.12.2 instance in MultiMC
Watch as the mod adds and then immediately removes itself after a second. And the mod isn't added.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
You sure that you're using MultiMC?  There isn't an import mod function.  To add a mod to an instance you can copy the file to the MODS directory or drop the mod onto the Loader mods window when you're editing the instance.   Oh yeah I guess there is the Add function.  Are you using that?

**Comment by phit** [comment]
there's the add mods button, but I can't reproduce the issue

![image](https://github.com/user-attachments/assets/2ab33e6a-a2ca-4b56-93ae-5b0332436a20)
