### ISSUE TITLE
Won't let me login into my ms account

### ISSUE THREAD

**Issue by UsualBug** [MultiMC/Launcher#5486]
### Operating System

Windows

### Description of bug

it just says authentication failed, im on win 7 java 8

### Steps to reproduce

Profiles > Microsoft > do all the steps > it ends up failing to authenticate

### Suspected cause

Probably cause im in Serbia rn?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
can you login at minecraft.net?

**Comment by UsualBug** [comment]
yes

**Comment by UsualBug** [comment]
multimc version is 0.7.0-3863 on win32

**Comment by UsualBug** [comment]
@phit

**Comment by UsualBug** [comment]
> can you login at minecraft.net?
![Uploading Capture.PNG…]()

**Comment by UsualBug** [comment]
> can you login at minecraft.net?

yes

**Comment by phit** [comment]
are you using email code to login with microsoft?

**Comment by UsualBug** [comment]
yes

**Comment by UsualBug** [comment]
i have the password

**Comment by phit** [comment]
https://account.microsoft.com/
Log into your account > Security > "Manage how I sign in" > Select either "Enter Password" or "Send sign-in notification"

Email code does not work correctly due to a Microsoft bug.

**Comment by UsualBug** [comment]
ok
ill try

**Comment by UsualBug** [comment]
still doesnt work

**Comment by UsualBug** [comment]
says xbox authentication failed

**Comment by UsualBug** [comment]
@phit

**Comment by UsualBug** [comment]
![Capture](https://github.com/user-attachments/assets/03e7f426-ee75-4a2f-92c7-567e23d987ec)
