### ISSUE TITLE
Wont let me log into my ms account

### ISSUE THREAD

**Issue by UsualBug** [MultiMC/Launcher#5487]
### Operating System

Windows

### Description of bug

[PC INFO: Windows 7 Ultimate 32 bit] So i made this same issue 4 days ago and i gave up but, im here again., So as the title says for some reason it wont let me log into my ms account, even tho i didnt use my email code for login yet my password, the multi mc version is the latest one [downloaded today]. Everytime i try to login this pop up occurs:
![Capture](https://github.com/user-attachments/assets/3656bb40-5693-4a95-bdcd-10b42b9291e0)
Im trying to use Better Than Wolves, i do use Java 1.8 but idk what is happening with multimc.

### Steps to reproduce

-Account-Miscrosoft-copy code-insert code-agree for multimc to use ms account-close tab-pop up of xbox user authentication failed

### Suspected cause

maybe its this old ahh machine im using

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by UsualBug** [comment]
@phit

**Comment by phit** [comment]
make sure you windows 7 is fully up to date, if it still doesn't work provide your MultiMC-0.log file
