### ISSUE TITLE
MultiMC froze the game

### ISSUE THREAD

**Issue by andreasdc** [MultiMC/Launcher#5490]
### Description of bug

My game was frozen, MultiMC launcher appeared on top of the cpu usage in the task manager, when I closed it my game unfroze.

### Steps to reproduce

-

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
sounds like you had a mod with extreme log spam, nothing multimc can do about that

**Comment by andreasdc** [comment]
> sounds like you had a mod with extreme log spam, nothing multimc can do about that

Are you sure? The game was running fine without it, so I guess it's possible to do something?

**Comment by andreasdc** [comment]
> sounds like you had a mod with extreme log spam, nothing multimc can do about that

It happened after running for a long time too.
