### ISSUE TITLE
null jar is specified in the metadata,aborting 

### ISSUE THREAD

**Issue by frankysrd** [MultiMC/Launcher#5491]
### Operating System

Windows

### Description of bug

i have seen this bug issue report before but i dont know how to fix it.
the modpack is on 1.20.1 
it says Instance update failed because: Null jar is specified in the metadata, aborting. 
![Screenshot 2024-08-18 172242](https://github.com/user-attachments/assets/953953e8-cde4-4a61-ae2e-e1688a0a6146)
it happens on some modpacks but not all.

### Steps to reproduce

click on a modpack eg:flooded city
then press launch

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
wrong java version

**Comment by frankysrd** [comment]
> wrong java version

oh ok
thanks
