### ISSUE TITLE
Process exited with exit code -1 (0xffffffffffffffff).

### ISSUE THREAD

**Issue by kettl101** [MultiMC/Launcher#5492]
### Description of bug

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::64, 13.107.253.64]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::64, 13.107.246.64]

api.mojang.com resolves to:
    [2620:1ec:bdf::64, 13.107.253.64]

Minecraft folder is:
C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/instances/hypixel skyblock/.minecraft

Java path is:
C:/Program Files/Java/jdk-21/bin/javaw.exe

Checking Java version...
Java is version 21.0.4, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/instances/hypixel skyblock/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-arm64.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-x86.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/fancymodloader/earlydisplay/4.0.24/earlydisplay-4.0.24.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.3.0/terminalconsoleappender-1.3.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/JarJarFileSystems/0.4.1/JarJarFileSystems-0.4.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/securejarhandler/3.0.8/securejarhandler-3.0.8.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/machinezoo/noexception/noexception/1.7.1/noexception-1.7.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/minecraftforge/srgutils/0.4.15/srgutils-0.4.15.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/fancymodloader/loader/4.0.24/loader-4.0.24.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.4/nashorn-core-15.4.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/modlauncher/11.0.4/modlauncher-11.0.4.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/JarJarMetadata/0.4.1/JarJarMetadata-0.4.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-reader/3.20.0/jline-reader-3.20.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/jline/jline-terminal/3.20.0/jline-terminal-3.20.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/JarJarSelector/0.4.1/JarJarSelector-0.4.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/bus/8.0.1/bus-8.0.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/fabricmc/sponge-mixin/0.14.0+mixin.0.8.6/sponge-mixin-0.14.0+mixin.0.8.6.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/core/3.8.0/core-3.8.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/accesstransformers/10.0.1/accesstransformers-10.0.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/coremods/7.0.3/coremods-7.0.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/electronwill/night-config/toml/3.8.0/toml-3.8.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/accesstransformers/at-modlauncher/10.0.1/at-modlauncher-10.0.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/antlr/antlr4-runtime/4.13.1/antlr4-runtime-4.13.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/neoforged/mergetool/2.0.0/mergetool-2.0.0-api.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/cpw/mods/bootstraplauncher/2.0.2/bootstraplauncher-2.0.2.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar
  C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/libraries/com/mojang/minecraft/1.21.1/minecraft-1.21.1-client.jar

Native libraries:

Mods:
  [✔️] BazaarNotifier-1.6.1.jar
  [✔️] custom-crosshair-mod-v1.5.1-forge-mc1.8.9.jar
  [✔️] DulkirMod-1.2.8.jar
  [✔️] Hypixel Autocomplete-1.1 (1.8.9).jar
  [✔️] ItemPhysic_NEOFORGE_v1.8.0_mc1.21.jar
  [✔️] JavaSetup8u421.exe
  [✔️] jdk-21_windows-x64_bin (1).exe
  [✔️] jdk-22_windows-x64_bin.exe
  [✔️] NotEnoughUpdates-2.1.jar
  [✔️] OptiFine_1.20.4_HD_U_I7.jar
  [✔️] Patcher-1.8.9 (1.8.9).jar
  [✔️] Scrollable Tooltips-1.4 (1.8.9).jar
  [✔️] SkyblockAddons-1.7.2-for-MC-1.8.9.jar
  [✔️] SkyHanni-0.24.jar
  [✔️] Skytils-1.10.3.jar
  [✔️] smooth-scrolling-everywhere-1.1.jar

Params:
  --username kettl101 --version 1.21.1 --gameDir C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/instances/hypixel skyblock/.minecraft --assetsDir C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/assets --assetIndex 17 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --fml.neoForgeVersion 21.1.21 --fml.fmlVersion 4.0.24 --fml.mcVersion 1.21.1 --fml.neoFormVersion 20240808.144430 --launchTarget forgeclient

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 10980

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
[13:31:30.698] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, kettl101, --version, 1.21.1, --gameDir, C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/instances/hypixel skyblock/.minecraft, --assetsDir, C:/Users/charl/Downloads/mmc-develop-win32 (1)/MultiMC/assets, --assetIndex, 17, --uuid, <PROFILE ID>, --accessToken, â„â„â„â„â„â„â„â„, --userType, msa, --versionType, release, --fml.neoForgeVersion, 21.1.21, --fml.fmlVersion, 4.0.24, --fml.mcVersion, 1.21.1, --fml.neoFormVersion, 20240808.144430, --launchTarget, forgeclient, --width, 854, --height, 480] 
[13:31:30.701] [main/INFO] [Launcher/MODLAUNCHER]: JVM identified as Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 21.0.4+8-LTS-274 
[13:31:30.702] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.4 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0 
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.IllegalArgumentException: gg.skytils.ktx-serialization.json.internal: Invalid package name: 'ktx-serialization' is not a Java identifier
	at java.base/jdk.internal.module.Checks.requireTypeName(Checks.java:154)
	at java.base/jdk.internal.module.Checks.requirePackageName(Checks.java:72)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.lang.module.ModuleDescriptor$Builder.packages(ModuleDescriptor.java:2107)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.SimpleJarMetadata.computeDescriptor(SimpleJarMetadata.java:46)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.LazyJarMetadata.descriptor(LazyJarMetadata.java:18)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.computeDescriptor(Jar.java:46)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar$JarModuleDataProvider.descriptor(Jar.java:125)
	at cpw.mods.securejarhandler/cpw.mods.cl.JarModuleFinder$JarModuleReference.<init>(JarModuleFinder.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.JarModuleFinder.lambda$new$1(JarModuleFinder.java:29)
	at java.base/java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1637)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler/cpw.mods.cl.JarModuleFinder.<init>(JarModuleFinder.java:29)
	at cpw.mods.securejarhandler/cpw.mods.cl.JarModuleFinder.of(JarModuleFinder.java:43)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:124)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:83)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 8 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

im just trying to launch Minecraft with some mods and no matter what i do it just does the same thing ive tried updating multi mc

### Suspected cause

no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Not sure if this is the root cause or not but it's a place to start.
1. You have executables in your MOD directory that don't belong there
[✔️] JavaSetup8u421.exe
[✔️] jdk-21_windows-x64_bin (1).exe
[✔️] jdk-22_windows-x64_bin.exe

2. Optifine is for the wrong version for this version MC.  This is for version 1.20.4 not 1.21.1  Maybe this version works for later versions of MC but I highly doubt it.
[✔️] OptiFine_1.20.4_HD_U_I7.jar

I would start by disabling these and trying again.

**Comment by kettl101** [comment]
it works whithout any mods but all i want to add is neu

**Comment by FeedTheChunk** [comment]
There's you problem then.  If it works w/out mods then the mods are causing the problem not MultiMC.  You can ask in Discord for help with your modpack.

**Comment by kettl101** [comment]
i got banned from the discord and they didnt even help

**Comment by kettl101** [comment]
aperantly i spamed when the mesage 10 minits later
