### ISSUE TITLE
multi mc

### ISSUE THREAD

**Issue by kettl101** [MultiMC/Launcher#5493]
### Operating System

Windows

### Description of bug

https://paste.ee/p/vFVqm

### Steps to reproduce

i dont know what to do

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
https://github.com/MultiMC/Launcher/issues/5492  start by stop creating new threads and do as instructed.  Ask in Dicord for help with your mod pack.
