### ISSUE TITLE
Constantly kicked from servers while using 3rd party launchers like this

### ISSUE THREAD

**Issue by PlasmicPulse** [MultiMC/Launcher#5494]
### Operating System

Windows

### Description of bug

Alright, so I've recently come back to playing Minecraft after about 7 months away, and have been running into a recurring issue where when playing on servers I constantly get kicked. I usually play anarchy so I have alot of hacks and such.

![Screenshot 2024-07-15 181039](https://github.com/user-attachments/assets/350539b1-997a-45e3-ae55-681f49ebfdfa)
![Screenshot 2024-07-15 181429](https://github.com/user-attachments/assets/79aa295e-471e-4e1a-b64d-7123a87aa254)
![Screenshot 2024-07-15 182639](https://github.com/user-attachments/assets/ae31456c-5387-4e79-ac58-62b314daa4dd)
![Screenshot 2024-07-15 184145](https://github.com/user-attachments/assets/52f9d5f6-0f6b-42ca-b816-cc9089b12a80)
![Screenshot 2024-07-15 184246](https://github.com/user-attachments/assets/9dd3788f-9e0f-4495-a21c-3fe32512b067)
![Screenshot 2024-07-21 021526](https://github.com/user-attachments/assets/8336e564-54ea-4208-a1d2-a8c1df22daad)
![Screenshot 2024-07-28 002229](https://github.com/user-attachments/assets/50a90529-86e1-4f2c-9c66-ef7d7e1861e2)

It typically happens when using Flight, but can also just happen while running around.
It sometimes happens immediately, other times takes a few minutes
Before the kick my game will sometimes do this thing where I can still walk around and stuff but I can't interact with things. Other times it'll just freeze and kick me
Other people that I've spoken to have said it's a packet error, not a tech guru so I have no clue what that means

Things I've tried:

Turning off all mods and adding them back one-by-one, but it even does it with all them off

Un-installing and re-installing MC

Other launchers such as modrinth

Some obscure tutorial in the backend of yt on how to get better wifi

Before you ask, no it isn't an issue with my PC specs, trust me.

### Steps to reproduce

* No clue, so far nobody has had these issues

### Suspected cause

Current theories that I'm unable to test at the moment:
It could be an issue with my internet. I don't have a wifi attachment on my mb, so I use a USB wifi adapter. The running theory is that my internet is probably dropping for a fraction of a second, causing the kick. Other examples of this possibly happening are when I use Air Link on my Quest 2, and it crashes Air Link so frequently that I can't even load a game.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpacks or mod's support channels/forums.
