### ISSUE TITLE
b1.7.3 and earlier black screen

### ISSUE THREAD

**Issue by oponic** [MultiMC/Launcher#5495]
### Operating System

macOS

### Description of bug

When launching versions b1.7.3 and earlier, a black screen is shown. This is not the intended behavior.
There are similar issues from 2 years ago, but the Java version that is given is no longer downloadable. (jdk8u232-b09)

### Steps to reproduce

Launch b1.7.3 on macOS

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
you can get older java versions on archive.org https://archive.org/download/Java-Archive/Java%20SE%208%20%288u211%20and%20later%29/8u231/JRE/
