### ISSUE TITLE
Modpacks Keep crashing

### ISSUE THREAD

**Issue by JayHambrick2004** [MultiMC/Launcher#5496]
### Operating System

Windows

### Description of bug

Whenever i download any of the modpacks listed anywhere in the "add instance" button and i open them they crash as soon as i try to open a world

### Steps to reproduce

All i do is add a modpack and then open it and it crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
![](https://raw.githubusercontent.com/MultiMC/background-cat/master/apps/discord-cat/src/images/upload_log.png)
