### ISSUE TITLE
my mods are not working

### ISSUE THREAD

**Issue by harryroz** [MultiMC/Launcher#5502]
### Operating System

_1.21.1_

### Description of bug

my mods not working

### Steps to reproduce

my mods not working

### Suspected cause

do not know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
