### ISSUE TITLE
tf is this?

### ISSUE THREAD

**Issue by BEANANAS** [MultiMC/Launcher#5503]
### Operating System

Windows

### Description of bug

I got this error...
![Screenshot 2024-09-02 050605](https://github.com/user-attachments/assets/ac3aad62-d252-4451-b26a-ef67c573d01e)
All I have is this...
![Screenshot 2024-09-02 050624](https://github.com/user-attachments/assets/9fcb678f-85aa-4e02-9475-b00b413e9d6b)
![Screenshot 2024-09-02 050639](https://github.com/user-attachments/assets/f43f56e8-2f86-40db-90c5-e2c1e70f24d3)
Help?

### Steps to reproduce

* Open MultiMC
* Install Forge
* Install Titans Mod 1.7.10 0.425

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
