### ISSUE TITLE
minecraft bugs out when launching versions prior to beta 1.8

### ISSUE THREAD

**Issue by ULTIMATEUSERNAMEFORGITHUB** [MultiMC/Launcher#5505]
### Operating System

macOS

### Description of bug

i tried launching beta 1.7.3 with optifine for that version and it did something seizure inducing but for some reason the video does not capture it but basically it flashes black and red repeatedly(im on mac os 12.6.7 with an amd radeon r9 m370x 2 gb graphics card)

https://github.com/user-attachments/assets/7b71f73e-60ed-4a3e-a079-d90351050366

### Steps to reproduce

launch beta 1.7.3

### Suspected cause

i do not know why this is happening but here are the logs https://paste.ee/p/1TBJp
if the link is down https://web.archive.org/web/20240903151232/https://paste.ee/p/1TBJp

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
use an older java version https://archive.org/download/jdk-7u72-macosx-x64/jdk-7u72-macosx-x64.dmg

and to get audio, skins etc to work

> Betacraft proxy reference copied from their Discord discord.gg/d4WvXeQ, all credits to them and keep in mind you have to trust them to use this. No association to MultiMC or warranty are given by us, use at your own risk.
> 
> Pick your target game version and add them to the instance java arguments.
> 
> **c0.0.13a** to **c0.30-c-renew**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11701 -Djava.util.Arrays.useLegacyMergeSort=true`
> 
> **in-20091223-1459** to **a1.1.2_01**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11702 -Djava.util.Arrays.useLegacyMergeSort=true`
> 
> **a1.0.8**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11703 -Djava.util.Arrays.useLegacyMergeSort=true`
> 
> **b1.3-demo**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11704 -Djava.util.Arrays.useLegacyMergeSort=true`
> 
> **a1.2.0** to **b1.8.1**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11705 -Djava.util.Arrays.useLegacyMergeSort=true`
> 
> **b1.9-pre1** to **b1.9-pre6**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11706`
> 
> **1.0.0-rc1** to **1.5.2**:
> -> `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11707`
