### ISSUE TITLE
Java memory allocation should be shown as MB not MiB

### ISSUE THREAD

**Issue by Blueclipsa** [MultiMC/Launcher#5506]
### Role

I play Minecraft and allocate memory

### Suggestion

Change the abbreviation to the correct one

### Benefit

It will be less confusing to people who know what Mebibytes are

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

MultiMC uses megabytes for Java memory allocation for very valid reasons. However, the abbreviation used in the launcher is for mebibytes not megabytes. Its clear through reading documentation that it is supposed to be megabytes, so removing the lowercase "i" would be enough to eliminate any possible confusion

**Comment by phit** [comment]
MiB is the corrrect symbol in the context of Java
