### ISSUE TITLE
I'm trying to log into the launcher, going through all the stages of verification through Microsoft. In the window in the browser it says “everything was successful” and so on, but in the launcher itself it says “multimc microsoft user authentication error”

### ISSUE THREAD

**Issue by khruvee** [MultiMC/Launcher#5508]
### Operating System

Windows

### Description of bug

I'm trying to log into the launcher, going through all the stages of verification through Microsoft. In the window in the browser it says “everything was successful” and so on, but in the launcher itself it says “multimc microsoft user authentication error”

### Steps to reproduce

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://account.microsoft.com/
Log into your account > Security > "Manage how I sign in" > Select either "Enter Password" or "Send sign-in notification"

Email code does not work correctly due to a Microsoft bug.
