### ISSUE TITLE
Cannot login "XBox user auth failed" (Chrome OS / Linux)

### ISSUE THREAD

**Issue by STORM-MCCTC** [MultiMC/Launcher#5510]
### Operating System

Linux

### Description of bug

I am running Linux on Samsung Chromebook (chrome OS Version 128.0.6613.161  64-bit) (I know Chromebooks are bad but I just wanted to play an old version of Minecraft :P)

When I try signing in with Microsoft I get the error in the image:

![Screenshot 2024-09-25 1 50 31 PM](https://github.com/user-attachments/assets/dbb8516c-50b3-4fed-8965-c8013f533f96)

I downloaded MulitMC with the installer, not Flatpack or anything else like that

I tried logging in multiple times but I get this error every time. 

### Steps to reproduce

Logging in with Microsoft on Linux on Chrome OS

### Suspected cause

this might be a problem with my MulitMC install or Linux, I'm unsure tho 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://account.microsoft.com/
Log into your account > Security > "Manage how I sign in" > Select "Enter Password"
