### ISSUE TITLE
LWJGL 3.2.2 not installing

### ISSUE THREAD

**Issue by CyanideCarrot** [MultiMC/Launcher#5511]
### Operating System

macOS

### Description of bug

LWJGL should install when creating or updating an instance

### Steps to reproduce

Create instance, select version 23w35a or later, LWJGL does not install, game wont load

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
its included in the main minecraft bundle, if you are getting lwjgl errors, update multimc

**Comment by CyanideCarrot** [comment]
I already updated MultiMC and it still wasn't working. But when I do it again to generate a new crashlog suddenly it works now, even though absolutely nothing changed
