### ISSUE TITLE
Cannot Login with my Microsoft Account

### ISSUE THREAD

**Issue by Daniel13850** [MultiMC/Launcher#5512]
### Description of bug

When i login with my Microsoft Account and give MultiMC the access then this error appears:
![image](https://github.com/user-attachments/assets/bc7cece5-0c47-49f2-8f1d-2fb370045c18)
In english: Authorization for XBox failed. Error %2.

### Steps to reproduce

login with a Microsoft Account

### Suspected cause

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kyogre312** [comment]
In english: Authorization for XBox failed. Error %2.

**Comment by Daniel13850** [comment]
now it works.
