### ISSUE TITLE
Crash as soon as the game starts (error code -1)

### ISSUE THREAD

**Issue by guigoso** [MultiMC/Launcher#5514]
### Description of bug

i expected the game to start normally but it crashed as soon as it started

[log](https://paste.ee/p/e8Lab)

### Steps to reproduce

1. start the game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Looks like you are using minecraftforge but the modpack is made for neoforge, either way this doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
