### ISSUE TITLE
crash as soon as the game starts (error code-1)

### ISSUE THREAD

**Issue by guigoso** [MultiMC/Launcher#5515]
### Operating System

Windows

### Description of bug

the game didn't start and this showed up in the logs 
[New Paste 1.txt](https://github.com/user-attachments/files/17261796/New.Paste.1.txt)

### Steps to reproduce

1. launch the game

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/issues/5514#issuecomment-2394170098
