### ISSUE TITLE
MultiMC reset self on linux

### ISSUE THREAD

**Issue by 2Bela** [MultiMC/Launcher#5516]
### Operating System

Linux

### Description of bug

Multimc reset to as if it was a new install. no accounts, no instances, default settings.

The owner of the bin folder, the multimc binary itself, and the folder these were contained in were all set to "986". "986" is not an account that i otherwise know of.

My installation method was using the stable debian zip off of the official website and i had installed it in a games folder(created by me) inside my home directory.

It was on version 6.16 before the loss of data and now it is up to date on version 7.0

In the past i have known the updater to not work and data loss had occurred in the past as well. i did not care to investigate or report at the time so i lack evidence from then. since then have i been updating multimc by manually copying in newer files and replacing files from older versions.

### Steps to reproduce

[MultiMC-0.log](https://github.com/user-attachments/files/17268286/MultiMC-0.log)
[MultiMC-1.log](https://github.com/user-attachments/files/17268287/MultiMC-1.log)
[MultiMC-2.log](https://github.com/user-attachments/files/17268288/MultiMC-2.log)
[MultiMC-3.log](https://github.com/user-attachments/files/17268289/MultiMC-3.log)
[MultiMC-4.log](https://github.com/user-attachments/files/17268290/MultiMC-4.log)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
the official .deb has its data in `~/.local/share/multimc`, you probably are opening a different install.
