### ISSUE TITLE
Multimc crashes when opening.

### ISSUE THREAD

**Issue by wasdwasd69** [MultiMC/Launcher#5518]
### Operating System

Windows

### Description of bug

When launching mmc for fabric 1.21.1 with tweakeroo, litematica, and associated mods with shaders, mmc just crashes.
[crash-2024-10-10_15.33.38-client.txt](https://github.com/user-attachments/files/17333959/crash-2024-10-10_15.33.38-client.txt)

### Steps to reproduce

Launch multimc

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
