### ISSUE TITLE
Login Network Error

### ISSUE THREAD

**Issue by DEVGavrilCJ** [MultiMC/Launcher#5520]
### Description of bug

I'm Not Able To Use MultiMC It Just Gives Errors When I Try Login Like If I Login To Mojang One It Just Gives Error Called Ended With Network Error But The Network Is Fine If I Try Microsoft It Fails

### Steps to reproduce

Doing 2 Stuff Entering Code And Entering Login

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Please reproduce the issue and provide the logs. We cannot diagnose anything without them.
