### ISSUE TITLE
Importing pack from FTB App doesn't set neoforge version

### ISSUE THREAD

**Issue by SeanMcMillan** [MultiMC/Launcher#5521]
### Operating System

Windows

### Description of bug

When importing the Direworlf20 1.21 pack from the FTB App, it is imported without neoforge, so when you run it you get a vanilla minecraft instance. Adding neoforge makes it work correctly.

### Steps to reproduce

1. Install the Direwolf20 1.21 modpack in the FTB app
2. Run it once so it downloads all the bits.
3. Import the Dirework20 pack into MultiMc
4. Look at the Versions screen for the imported pack and see that neoforge is not there
5. Run the pack. It runs without mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DazedRazer** [comment]
I had the same problem, if you go to the instance settings and go to the version tab, there's a button in the right hand side bar that say's install neoforge.

**Comment by SeanMcMillan** [comment]
Yeah, you can fix it by installing neoforge yourself, but shouldn't it import that correctly as part of the import process?

**Comment by phit** [comment]
please update MultiMC and check if it's fixed now
