### ISSUE TITLE
minecraft closes when i press esc button not always but commonly

### ISSUE THREAD

**Issue by abdelrahman0elzero** [MultiMC/Launcher#5522]
### Operating System

Windows

### Description of bug

i play modded minecraft bmc4 + some mods like mekanism and powah but the game started to crash (the world saves before it crash so i think its closing)
log : https://mclo.gs/4ED0Yb7

### Steps to reproduce

pressing esc button 
(not always)

### Suspected cause

mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your modpack or mods, you can try asking in the modpack or mod's support channels/forums, or in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
