### ISSUE TITLE
Mod update checker (and maybe updater)

### ISSUE THREAD

**Issue by Karpatok9089** [MultiMC/Launcher#5523]
### Role

Playing modded Minecraft

### Suggestion

A buttom which displays mods that can be updated

### Benefit

So players can keep their mods up to date

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know that somebody has suggested this earlier, but their suggestion involved curseforge update checking. My suggestion is that the updater looks inside the mod and searches for the Modrinth webpage (If there isn't, then the mod isn't counted as updatable). If the mod has a newer version avaiable on the same game version (For example, you installed ExampleMod version 1.1 on 1.21.1 and it has a update 1.2 for 1.21.1), then the mod is marked as updatable. **Mod Menu already does this.**

**Comment by phit** [comment]
basically https://github.com/MultiMC/Launcher/issues/5461
