### ISSUE TITLE
Graphical issues in version 1.6.1

### ISSUE THREAD

**Issue by secondhandweed** [MultiMC/Launcher#5524]
### Operating System

Windows

### Description of bug

Some issues with graphical things in 1.6.1
No floating blocks when I break them
No cracks forming on blocks as I break them
No mobs
What could be causing this? How can I fix it?

### Steps to reproduce

> create an instance in 1.6.1 with no mods

> open it

> broken

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
multimc just launches the game
