### ISSUE TITLE
Краш всего лаунчера

### ISSUE THREAD

**Issue by SpeedDe23** [MultiMC/Launcher#5527]
### Description of bug

Я настраивал мод lootbeams на версии 1.21 на своей сборке, пока я тестировал параметры, 1 из запусков привёл сбой, и вместо запуска программы, окно с лаунчером закрылось. После открытия и запуска данной версии последовало тоже самое. А чуть позже и вовсе лаунчер перестал работать. Я решил перезагрузить устройство, но после перезагрузки приложения с лаунчером не находилось (вместо иконки была белая бумага (как текстовый документ) и при запуске писалось что не нашло данного приложения и само предложило удалиться. Если не соглашаться ничего не изменится, а при нажатии удалить, удалился лаунчер и после повторной установки - все созданые сборки пропали...

### Steps to reproduce

Выше рассказано все

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
extract multimc before use
