### ISSUE TITLE
Fabulously optimized 1.21.1 crashes on graphics settings

### ISSUE THREAD

**Issue by wraayyak** [MultiMC/Launcher#5529]
### Operating System

Windows

### Description of bug

The minecraft loads normally, but when im trying to open graphics settings, the minecraft just crashes.

### Steps to reproduce

https://paste.ee/p/DqG3T

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
MultiMC has nothing to do with the game running.  It just launches the game.  With that said, your issue is with Sodium.  Ask in Discord for more help.  Check the Sodium Git page for more information.
