### ISSUE TITLE
"Could not decide Minecraft version" error

### ISSUE THREAD

**Issue by AbdouRmRim12341** [MultiMC/Launcher#5530]
### Operating System

Windows 11 22H2

### Description of bug

If I want to play Minecraft on MultiMC, I need to open the app, and then I try to play, but I need an upgrade. So I click on ` --> Upgrade the instance` and when I click on it, it shows "**Could not decide Minecraft version.**"

### Steps to reproduce

1. Open MultiMC
2. Double click Unnamed Instance", showing `Upgrade is required` .
3. Click on `Upgrade the instance`

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Doesn't sound like you're running MultiMC.  MultiMC doesn't have an "Upgrade Instance" option.

**Comment by phit** [comment]
Restore your instance from backup or make a new one, and copy all files in the minecraft folder to the new one, your instance config is broken. Usually this is caused by a full or failing drive.
