### ISSUE TITLE
Weird Chunk Linking (Beta 1.7.3)

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#5532]
### Description of bug

I expected no chunk errors in my world, there was a chunk that looked and was the same chunk. This is incorrect as after you join the game once discovered it will freeze the game with a lot of pigs.

### Steps to reproduce

Note: It happens sometimes but not all the time.
* Load a world
* Find a chunk error
* Leave the Game / Instance.
* Join back and the world won't render.

### Suspected cause

There was not anything that was interfering the bug and the log overflowed as well.
Before this, I was trying to get multiplayer in a singleplayer world. So I did a symbolic link so the other instance can join, but it was only one person that can join, so I deleted my recordings.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
This doesn't look like an issue with MultiMC. If you want help with your game, you can try asking in the #minecraft channel in the [MultiMC Discord](https://discord.gg/multimc).
