### ISSUE TITLE
Instance update failed because: Failed to download assets

### ISSUE THREAD

**Issue by Qoolize** [MultiMC/Launcher#5533]
### Operating System

Windows

### Description of bug

Apparently the launcher has problems downloading data.
The error occurs in every instance.
It works in the normal MC launcher.

LOG (1.21):

> MultiMC version: 0.7.0-3863
> 
> 
> Launched instance in online mode
> 
> authserver.mojang.com resolves to:
>     [N/A]
> 
> session.minecraft.net resolves to:
>     [2620:1ec:bdf::45, 13.107.246.45]
> 
> textures.minecraft.net resolves to:
>     [2620:1ec:27:e65e::cafe:e65e, 40.90.65.144]
> 
> api.mojang.com resolves to:
>     [2620:1ec:29:1::45, 13.107.253.45]
> 
> 
> Minecraft folder is:
> I:/Spiele/Minecraft/MultiMC/instances/1.21/.minecraft
> 
> 
> Java path is:
> I:/Spiele/Minecraft/jdk-23.0.1/bin/java.exe
> 
> 
> Checking Java version...
> Java is version 23.0.1, using 64-bit architecture, from Oracle Corporation.
> 
> 
> Instance update failed because: Failed to download assets:
> Job 'Assets for 17' failed to process:
> https://resources.download.minecraft.net/f0/f00657542252858a721e715a2e888a9226404e35
> https://resources.download.minecraft.net/f0/f0194d3dcf61e81446cc5efd554d8811cf66faf3
> https://resources.download.minecraft.net/f0/f05f55328f2b98b3c7d881fcdef7e7964d8082fa
> https://resources.download.minecraft.net/f0/f094c30d1b70fbd1ce2f7f047a6139a3eac30991
> https://resources.download.minecraft.net/f0/f0a4327c7e3474dca8e7a83b5bba6af7f471cea1
> https://resources.download.minecraft.net/f0/f0b347346feff35af1cd8467d1ab363279d5e88f
> https://resources.download.minecraft.net/f0/f0b85996cef731751701d176b0c0d325f6fa7877
> https://resources.download.minecraft.net/f0/f0c2628e37f3553d63a93533750006f7feab09f0
> https://resources.download.minecraft.net/f0/f0c2a7819442973825b7bd869f476fdd43c7a2e8
> https://resources.download.minecraft.net/f0/f0d0d2cc12bda03b297a06672de9519022403cc3
> https://resources.download.minecraft.net/f0/f0d58706321168c2907cf13ae6f8ae9108244fc3
> https://resources.download.minecraft.net/f0/f0f67682c9f1f36d42a5b5202ee08f9c4ee06b56

LOG (SNAP 1.21.4):

> MultiMC version: 0.7.0-3863
> 
> 
> Launched instance in online mode
> 
> authserver.mojang.com resolves to:
>     [N/A]
> 
> session.minecraft.net resolves to:
>     [2620:1ec:29:1::45, 13.107.253.45]
> 
> textures.minecraft.net resolves to:
>     [2620:1ec:27:e723::cafe:e723, 104.212.67.194]
> 
> api.mojang.com resolves to:
>     [2620:1ec:29:1::45, 13.107.253.45]
> 
> 
> Minecraft folder is:
> I:/Spiele/Minecraft/MultiMC/instances/1.21.4-pre1/.minecraft
> 
> 
> Java path is:
> I:/Spiele/Minecraft/jdk-23.0.1/bin/java.exe
> 
> 
> Checking Java version...
> Java is version 23.0.1, using 64-bit architecture, from Oracle Corporation.
> 
> 
> Instance update failed because: Failed to download assets:
> Job 'Assets for 19' failed to process:
> https://resources.download.minecraft.net/f0/f00657542252858a721e715a2e888a9226404e35
> https://resources.download.minecraft.net/f0/f014d90070e4c722238e9a8ef9ffef3a19ace83b
> https://resources.download.minecraft.net/f0/f01c78ac7381b67f5e3014ae5ed153417fd9acf2
> https://resources.download.minecraft.net/f0/f0212098e16342cc0270c6b64eaffd7a6edc5c4c
> https://resources.download.minecraft.net/f0/f02183adf26fec7f79ae5b18ff6715cde7dd7f04
> https://resources.download.minecraft.net/f0/f03d18b2bce2a3c51e6e831747cd8b944f5771f6
> https://resources.download.minecraft.net/f0/f04f3818a8344179ea169eb252b8ead671836f69
> https://resources.download.minecraft.net/f0/f0621ec9192760a9ab4a97f279613b05320092b4
> https://resources.download.minecraft.net/f0/f06613bca60316fdc9ae333e39c1c9fd8a06e4de
> https://resources.download.minecraft.net/f0/f06d0edd6f684505e9d08c2d29524bdde10ad5c6
> https://resources.download.minecraft.net/f0/f072e1ea7949f1b7abc7546e1e995cc294661985
> https://resources.download.minecraft.net/f0/f083b4a80f957cdde6bbc30ae6a26f8d8d190ae4
> https://resources.download.minecraft.net/f0/f09c1001fd7e9982e0e6e3fabf4e1a7ced9b2cce
> https://resources.download.minecraft.net/f0/f09c4c67e1403d34cee7a60217b76099de3416d5
> https://resources.download.minecraft.net/f0/f0a4327c7e3474dca8e7a83b5bba6af7f471cea1
> https://resources.download.minecraft.net/f0/f0af45e814823e47963d702a38ef90c7d515bdc9
> https://resources.download.minecraft.net/f0/f0b85996cef731751701d176b0c0d325f6fa7877
> https://resources.download.minecraft.net/f0/f0c022a51c4e496fe8b57ee6a769e01e5b321e4d
> https://resources.download.minecraft.net/f0/f0c27e02d0ba89942516f75439ef211264f2e997
> https://resources.download.minecraft.net/f0/f0c4946eb21ffe8a3e81b83e4f103884e791f885
> https://resources.download.minecraft.net/f0/f0ca66561f832bf2f60b393837297c2692367cd5
> https://resources.download.minecraft.net/f0/f0cdd15e9eb0129cff065733cadbe1a4123ebfca
> https://resources.download.minecraft.net/f0/f0e15006b2f0b2687859fe57d623fa2351dfbc11

### Steps to reproduce

Tried several instances.
Downloaded the launcher again.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
looks like some kind of network issue on your end, judging by the dns log I'd doublecheck IPv6 works on your end, otherwise disable it in your OS/router
