### ISSUE TITLE
I don't know what this means EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Dannimax** [MultiMC/Launcher#5535]
### Operating System

Windows 10

### Description of bug

So I've never been able to run an instance through multimc, I made an account just for this so I apologize for any lack of knowledge. 
I'm trying to run a b1.7.3 instance but whenever it starts loading it crashes before showing anything on the screen, it's just black. I've tried changing my Java version, changing the max and min memory allocation, updating my drivers, even checked for any possible malware with FreeFixer but the result is always the same.

https://pastebin.com/1DxZEMcC

### Steps to reproduce

* Launch instance

### Suspected cause

I honestly have no idea.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Unsupported-Intel-GPUs
