### ISSUE TITLE
Minecraft doesn't launch

### ISSUE THREAD

**Issue by Timolar** [MultiMC/Launcher#5539]
### Operating System

Windows

### Description of bug

https://paste.ee/p/cWGet
when i'm trying to launch the instance, minecraft crashes. 

### Steps to reproduce

I just launched the instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
https://github.com/MultiMC/Launcher/wiki/Using-the-right-Java
