### ISSUE TITLE
Create Instance Shortcut

### ISSUE THREAD

**Issue by luskassb1** [MultiMC/Launcher#5540]
### Operating System

Windows

### Description of bug

I'm trying to create a shortcut for my instance, but for some reason, when I click, it doesn't create it, any error message apears, it just doesn't want to create the shortcut, someone can help me pls

### Steps to reproduce

[VanillaFPS-1.21.4.zip](https://github.com/user-attachments/files/18062271/VanillaFPS-1.21.4.zip)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
what is the error message?

**Comment by luskassb1** [comment]
> what is the error message?

Any error message apears on the screen, it just don't work

**Comment by phit** [comment]
any doesn't mean none or zero, so there is no error? what is the path to the instance

**Comment by luskassb1** [comment]
> any doesn't mean none or zero, so there is no error? what is the path to the instance

no error message, and I tried to put on my desktop, and in other file, but i didn't work

**Comment by FeedTheChunk** [comment]
Phit is asking where the mod pack is installed.  Something like c:\games\multimc\instances\problem_modpack\  Not where you're trying to create the shortcut.

**Comment by luskassb1** [comment]
its installed on the Multi MC's folder, i'm trying to create the shortcut in other folder

**Comment by FeedTheChunk** [comment]
> its installed on the Multi MC's folder, i'm trying to create the shortcut in other folder

Yes.  Tell Phit what the path is to your MultiMC folder.

**Comment by phit** [comment]
This issue is being closed for inactivity. If you're still having trouble with this, feel free to come by our [Discord server](https://discord.gg/multimc) and ask for help.

**Comment by phit** [comment]
probably duplicate of https://github.com/MultiMC/Launcher/issues/5009
