### ISSUE TITLE
Minecraft is not launching

### ISSUE THREAD

**Issue by lemelinha** [MultiMC/Launcher#5541]
### Operating System

Linux

### Description of bug

Im trying to launch Minecraft 1.8.9 using java 8, but isnt work

System Info:

- OS: arch Linux
- CPU: Ryzen 7
- RAM: 16Gb
- GPU: AMD radeon 580

### Steps to reproduce

Start the game
[log.txt](https://github.com/user-attachments/files/18087850/log.txt)

Exit code 255 (0xff)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by FeedTheChunk** [comment]
Try deleting options.txt file in the .minecraft folder.  Seems like I remember something a long time ago that the options file was causing the "No OpenGL context found in the current thread" issue.

**Comment by lemelinha** [comment]
sorry for the delay.
i dont find optins.txt file in .minecraft folder

still the same problem

**Comment by phit** [comment]
please post your full log and make sure you have xrandr installed

![](https://raw.githubusercontent.com/MultiMC/background-cat/master/apps/discord-cat/src/images/upload_log.png)

**Comment by lemelinha** [comment]
I installed xrandr and its work
thank you!
