### ISSUE TITLE
prism launcher or multi mc what is beter

### ISSUE THREAD

**Issue by dsijdshaij** [MultiMC/Launcher#5543]
### Role

a

### Suggestion

a

### Benefit

a

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

csdfdgfhgjkfghjklkjhgfhjhgd

**Comment by yusufumben09** [comment]
this isnt a issue with multimc, you should ask this somewhere else.
