### ISSUE TITLE
Creating Unicode Characters in Instance Causes the Instance not to launch

### ISSUE THREAD

**Issue by jredfox** [MultiMC/Launcher#5546]
### Operating System

Windows 10 / 11

### Description of bug

Refuses to launch vanilla 1.7.10 & Forge with no mods installed

### Steps to reproduce

Create 1.7.10 instance with "你的意思是每秒滴答数"
Edit Instance and Install Forge
Make sure to launch with Java 8

### Suspected cause

MultiMC not java is having trouble understanding what any non ANSII characters are in the path

```
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\jredfox\Desktop\MultiMC\instances\??????????\natives\lwjgl64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary1(Unknown Source) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.7.0_80]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[?:1.7.0_80]
	at java.lang.System.loadLibrary(Unknown Source) ~[?:1.7.0_80]
	at org.lwjgl.Sys$1.run(Sys.java:72) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:87) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:117) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2671) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
Java 8 does not support Unicode paths, some of the related fixes only arrived with Java 19+ or are even still broken
https://bugs.openjdk.org/browse/JDK-8272352
https://bugs.openjdk.org/browse/JDK-8124977

use ASCII only for paths on Windows, for MultiMC only allowing safe names this issue exists https://github.com/MultiMC/Launcher/issues/3402

**Comment by jredfox** [comment]
Java 8 does support Unicode Paths it's been supported always. UTF-16 strings in java since 1.0.0 try again. Why do you think Asian  people can play minecraft their user names are going to have asian characters inside the path and use java 8

**Comment by phit** [comment]
exactly, user directories with special characters also cause this problem, see https://github.com/java-native-access/jna/issues/238
https://github.com/MultiMC/Launcher/issues/4677#issuecomment-1128646794

**Comment by jredfox** [comment]
> exactly, user directories with special characters also cause this problem, see [java-native-access/jna#238](https://github.com/java-native-access/jna/issues/238) [#4677 (comment)](https://github.com/MultiMC/Launcher/issues/4677#issuecomment-1128646794)

JNA is not made by java but instead made by guys who allows you to call OS specific calls from java as if your in C / C++. but it's not that extensive and has bugs. MultiMC doesn't depend on JNA to launch minecraft nor does **MINECRAFT 1.7.10 require JNA***. 

All I am saying is please fix the issue. the real issue that I reported is multimc's DLL files don't get extracted with UTF-8 / UTF-16 characters thus causing the DLL's not to be found. I am sure there is an almost identicle issue on mac / linux if this only excepts ANSII

**Comment by phit** [comment]
they are extracted correctly, just tried by simply killing the multimc process during launch

![image](https://github.com/user-attachments/assets/d8850fcd-e3bf-4d4b-aad5-a40b9fb16772)

~~so if anything there's a problem with the string passed to java, looking at the multimc log that is actually where the issue seems to be `-Djava.library.path=D:/Games/MultiMC/INSTAN~1/18F8~1/natives`~~
those are short paths https://github.com/MultiMC/Launcher/blob/07907ded5cee269c338c2c7d12a1a1da1903294d/launcher/minecraft/launch/LauncherPartLaunch.cpp#L35-L49

**Comment by phit** [comment]
as far as I can tell there's nothing going wrong on MultiMC's side, but I would be happy to see someone proving me wrong as I would also like to use Emojis in my instance paths

**Comment by phit** [comment]
enabling this in the windows settings allows the game to run with Java 21, Java 8 still crashes

![image](https://github.com/user-attachments/assets/0ff33395-b546-44cc-b556-be5e7c2e3820)

**Comment by jredfox** [comment]
Ok I have no idea why the chinese username has unicode characters and works fine for the chinese friend but only when unicode characters are inside of the user directory does it struggle with it. 

Your right java doesn't work with UNICODE PATHS! This is observed considering the fact that java strings and everything brags about full unicode support what a joke!

**Reproduceable with "Hello World.jar"**
```
package purejava;

public class Main {
	
	public static void main(String[] arg)
	{
		System.out.println("Hello World!");
	}

}
```

Merry Christmass Closing Issue as a Java Distro Issue (java itself)

While in theory you could Prevent Instances from having the issue you can't prevent Asian people naming using their Asian characters causing issues. So yeah too problematic if you can only cause a partial fix due to it being java itself
