### ISSUE TITLE
Minecraft freezing after playing for 5-20 minutes

### ISSUE THREAD

**Issue by cardman012** [MultiMC/Launcher#5549]
### Operating System

Windows

### Description of bug

Game will freeze after minutes of playing and does not unfreeze. Minecraft will not close on it's own and has to be killed with task manager. 

### Steps to reproduce

1. Play Minecraft

2. Play until it freezes

### Suspected cause

I have no idea. This has only been an issue on this new laptop I have gotten. Once when playing and when my game had froze, I saw a bunch of cave systems loading in all at once.

https://paste.ee/p/HOkkz

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by phit** [comment]
increase the memory allocation https://github.com/MultiMC/Launcher/wiki/Increasing-Java%27s-memory-allocation

**Comment by cardman012** [comment]
tried at both minimum and maximum values, still freezes

![image](https://github.com/user-attachments/assets/0f656e04-1b15-4d46-83f2-f88727460149)

**Comment by phit** [comment]
looks like there's some deeper issues with that version and your setup, unfortunately that's way out of scope for this issue tracker, multimc just launches the game and we cannot support ancient game versions

this almost looks like some gpu driver crash with the messed up rendering

to rule out some more common issues, you can try the betacraft proxy, that should at least fix the other issues in your log
add these to the instance java arguments  `-Dhttp.proxyHost=betacraft.uk -Dhttp.proxyPort=11707`
