### ISSUE TITLE
i cant start an instance, it comes out saying that the java path could not be found, what do i do.

### ISSUE THREAD

**Issue by ghost** [MultiMC/Launcher#593]
mind you that I have just updated java to java 8

**Comment by Gustaa** [comment]
Hello i try to start a instance and this appears : Could not start java:
Error: Unable to access jarfile /Users/My USERNAME/Desktop/MultiMC/MultiMC.app/Contents/MacOS/jars/JavaCheck.jar

**Comment by Gustaa** [comment]
@peterix Hello I try to start up a instance and then this appears : Checking Java version...
Could not start java:
Error: Unable to access jarfile /Users/Gustaa/Desktop/MultiMC/MultiMC.app/Contents/MacOS/jars/JavaCheck.jar

**Comment by jikuja** [comment]
How is this problem related with this thread? My recommendation: open a new bug report and fill template.

**Comment by peterix** [comment]
Indeed. Locking this one, open a new one.
