### ISSUE TITLE
LiteLoader 1.8 not shown

### ISSUE THREAD

**Issue by Kush-Prajapati** [MultiMC/Launcher#676]
when i press install liteloader none of the 1.8 versions show up i tried adding the jar version of it to jar mods it still doesn't work could you possibly add the 1.8 versions or make me a version

the 1.8 downloads http://jenkins.liteloader.com/job/LiteLoaderInstaller/

**Comment by james508959** [comment]
The json file still fetch #42 instead of the newest one (as for now it's #45), any one know how to keep it updated?

**Comment by Orcinuss** [comment]
change anywhere it says '1.8.42 to 1.8.45' and change 'LiteLoader/42/artifact' to 'LiteLoader/45/artifact'

**Comment by peterix** [comment]
Yep. There's actually a '46' now, so I updated it to that.
