### ISSUE TITLE
Doesn't execute on LINUX 32bit

### ISSUE THREAD

**Issue by Frassmaster** [MultiMC/Launcher#70]
Downloaded and extracted MultiMC. The MultiMC  file is automatically set to executable. But it does nothing.

Running on well behaved UBUNTU 13.10

Don't know how to diagnose further (I really shouldn't be on github!)

**Comment by Zenith127** [comment]
How do u find the path for the mmc folder to cd it if it doesnt tell you because i keep getting it wrong and it says that there is no such file or directory?

**Comment by Cryotechnic** [comment]
In the Terminal you type:

cd /home/User/Downloads(if you didn't move it to another folder)/mmc(assuming you extracted it)/MultiMC.jar

That is, if I remember correctly, haven't used Linux in over a year.
